openshift/assisted-service

- Dockerfile.demo
- Dockerfile.test
- build_deploy.sh
- openshift/template.yaml
- pr_check.sh
Signed-off-by: Amador Pahim <apahim@redhat.com>
> Onboarding to app-interface

- openshift/template.yaml
Indentation was incorrect.
Signed-off-by: Amador Pahim <apahim@redhat.com>
> OpenShift Template fix

- openshift/template.yaml
We need that to be provided, not to be latest.
Signed-off-by: Amador Pahim <apahim@redhat.com>
> IMAGE_TAG as required argument

- build_deploy.sh
Skipper needs those variables according to
https://github.com/Stratoscale/skipper/blob/upstream/README.md#python3-environment
> Exporting variables for skipper.

- openshift/template.yaml
Reverts openshift/assisted-service#8
> Revert "Added "---" separator in openshift/template.yaml after adding a service."

- Jenkinsfile
We have seen situations where code in the script failed due to some
error, and no message was displayed in any of the logs
> Fixed indentation and removed usage of 'scripts' inside the steps

- deploy/assisted-service.yaml
- openshift/template.yaml
This will allow easier deployment to non-default namespaces
> Pass the current namespace as the NAMESPACE env var to assisted-service

- pkg/job/job.go
Always take newest version of image generation and kubeconfig generation
> MGMT-1178 - Change image pull policy to Always

- openshift/template.yaml
> Updated env variable name for route53-creds secret.

- internal/bminventory/inventory.go
- internal/host/instructionmanager.go
Rename the docker image names to call single docker image (https://quay.io/repository/ocpmetal/assisted-installer-agent:latest) by default
> MGMT-1767 Move git repo ori-amizur/introspector to opnshift/assisted-installer-agent

- internal/bminventory/inventory.go
Use s3 client instead of http.get - get don't always have permissions:
> MGMT-1797 fix get credentials

- tools/utils.py
in ingress the prefix is assisted-installer
> OCPBUGSM-15610 fix wait for service in oc-ingress target

- go.mod
- internal/network/dhcp_param_file.go
- internal/network/dhcp_param_file_test.go
- pkg/job/job.go
- pkg/job/local_job.go
> MGMT-1721 Pass mode of operation by bm-inventory to cause creation of flag file to Openshift

- openshift/template-monitoring.yaml
> Adding ServiceMonitor template

- pkg/job/job.go
The stable tag is still trying to set extra ACLs on the uploaded file
so it seem very old
cc @romfreiman @yevgeny-shnaidman
> Use the latest ignition generator image

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/network/machine_network_cidr.go
- models/cluster_update_params.go
- restapi/embedded_spec.go
- swagger.yaml
/cc @YuviGold 
/cc @filanov 
/cc @ronniel1
> MGMT-1720 Modify UpdateCluster to handle DHCP mode and machine network cidr change

- subsystem/cluster_test.go
this PR fix the test: install cluster requirement
@eranco74 please review
> fix subsytem test install cluster requirement

- internal/cluster/conditions.go
- internal/cluster/refresh_status_preprocessor.go
- internal/cluster/statemachine.go
- internal/cluster/transition.go
- internal/cluster/transition_test.go
- internal/cluster/validator.go
- internal/host/validator.go
/cc @avishayt 
/cc @ronniel1 
/cc @filanov 
/cc @YuviGold
> MGMT-1833 Change cluster and host state machines to adapt to DHCP mode

- internal/cluster/common.go
@filanov @ori-amizur @avishayt please review
> MGMT-1855 - Logs spammed from UpdateCluster

- internal/host/instructionmanager.go
/cc @ronniel1 
/cc @YuviGold 
/assign @YuviGold
> MGMT-1877 Wrong image for dhcp allocation containerized application

- build_deploy.sh
Reverts openshift/assisted-service#156
> Revert "Adding 'assisted-iso-generator' to app-interface."

- config/onprem-iso-config.ign
- config/onprem-iso-fcc.yaml
- docs/installer-live-iso.md
Follow-up patch to address comments in https://github.com/openshift/assisted-service/pull/175.
> MGMT-1450: remove s3 from live ISO

- Makefile
Forgot to remove on https://github.com/openshift/assisted-service/pull/151
> Mgmt-1768 Cleanup remaining s3-volume

- Jenkinsfile
This reverts commit e26d1f0e2eac586eba97e33e2e64b19c6182e20b.
> Revert "add link to notification"

- Jenkinsfile
- Makefile
- tools/clear_deployment.py
It will not run the command if the content of the pipe is empty
Will make the commands output cleaner
> Add -r option to xargs

- openshift/template.yaml
> Adding missing parameters to openshift/template.yaml.

- internal/network/machine_network_cidr.go
> MGMT-1924 Remove severity of logging message when a host does not belong to machine cidr when checking free_addresses

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster_test.go
- internal/cluster/refresh_status_preprocessor.go
- internal/cluster/statemachine.go
- internal/cluster/transition_test.go
- internal/cluster/validation_id.go
- internal/cluster/validator.go
- internal/network/cidr_validations.go
- models/cluster_validation_id.go
- restapi/embedded_spec.go
- swagger.yaml
/assign @eranco74 
/cc @ronniel1
> MGMT-1864 - Validate advanced networking fields

- pkg/job/job.go
- pkg/job/job_test.go
If a cluster installation was failed due error in kube config
generation job, the assisted-installer didn't clear it on
reset command. The result is that user couldn't start a new
installation since the previous job was already exist.
Added 'force' flag that determines whether to delete the job
even if it failed, assume that if the user requested to reset
the cluster we no longer need that job.
> MGMT-1865: Add 'force' flag to job Deletion

- Makefile
- tools/clear_deployment.py
In current pvc is pending or down, the size will be empty string.
Converted it to None so it will be handled like there is no current
size.
> MGMT-1644: pvc_size_utils.py current size check fix

- build_deploy.sh
- build_images.sh
- pr_check.sh
Added image building to pr_check.sh.
Now we also build `assisted-service` and `assisted-iso-generator` images
on PRs so we can discover failing builds before merging to master.
> Added image building to pr_check.sh.

- deploy/assisted-service.yaml
- openshift/template.yaml
> Adding 'liveness' and readiness probs to the deployments.

- internal/host/common.go
- internal/host/host_test.go
- internal/host/statemachine.go
- internal/host/transition_test.go
Align the text, add missing info for known status
> OCPBUGSM-15826: Rewrite status infos

- internal/bminventory/inventory.go
MGMT-1961 When switching between 2 machine CIDRS in DHCP mode, VIPS have to be erased from the database
MGMT-1986 vip_dhcp_allocation on cluster-create-params has no effect
> Multiple issues

- internal/cluster/validations/validation_test.go
- internal/cluster/validations/validations.go
> [MGMT-1984] No Proxy does not support '*' as value

- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
> MGMT-1955 Create event when vips leases are allocated

- internal/cluster/validations/validation_test.go
- internal/cluster/validations/validations.go
> [MGMT-1982] Proxy value must contain a scheme

- cmd/main.go
- deploy/assisted-service-configmap.yaml
- pkg/ocm/client.go
> MGMT-1857 Wrap logrus logger to OCM SDK logs

- internal/host/installcmd.go
- internal/host/installcmd_test.go
> MGMT-2033 Add agent image to the installer command line. Needed for log sender

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
The proxy should be configured also for the ignition file of the discovery image (in addition to the agent service).
If a proxy is configured for the cluster, it will appear as a one-liner 
```
{
"ignition": {
"version": "2.2.0",
"proxy": { "httpProxy": "http://10.46.41.7:3128", "httpsProxy": "http://10.46.41.7:3128", "noProxy": "10.46.41.7" }
},
...
}
```
> Use proxy for discovery image

- internal/bminventory/inventory.go
> MGMT-1826 Clear host's free addresses field becuase it is not needed by API users

- openshift/template-post-deploy-job.yaml
Depends on the app-interface counterpart:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/8907
> Adding post deploy Job to trigger external CI

- client/installer/disable_host_responses.go
- client/installer/enable_host_responses.go
- internal/bminventory/inventory.go
- internal/host/host.go
- internal/host/mock_host_api.go
- internal/host/transition.go
- internal/host/transition_test.go
- restapi/embedded_spec.go
- restapi/operations/installer/disable_host_responses.go
- restapi/operations/installer/enable_host_responses.go
- subsystem/cluster_test.go
- swagger.yaml
and return the cluster object.
> MGMT-2038: Refresh cluster/host status on enable/disable host

- openshift/template.yaml
> Adding RELEASE_TAG to openshift/template.yaml.

- internal/bminventory/inventory.go
> Format discovery ignition json

- cmd/main.go
- go.mod
- go.sum
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/validations/validation_test.go
- internal/cluster/validations/validations.go
- internal/host/mock_host_api.go
- pkg/auth/auth_handler_test.go
- pkg/auth/auth_handler_test_utils.go
- subsystem/subsystem_suite_test.go
- subsystem/wiremock_stubs.go
In case that Auth is enabled:
- Validate that the pull secret has a "cloud.openshift.com" section
- Validate that the pull secret user token user is the same as the user that initiated the Cluster creation
> MGMT-1814 - Add pull secret validation on create cluster

- internal/bminventory/inventory.go
> Use common error function

- pkg/s3wrapper/filesystem.go
> Set client name properly

- openshift/template-post-deploy-job.yaml
Signed-off-by: Amador Pahim <apahim@redhat.com>
> Adding missing parameters section

- internal/bminventory/inventory_test.go
> Add missing parameter to NewBareMetalInventory in test

- internal/common/common.go
I just happened to notice these while debugging test failures in this area.
> updates comments and errors to reflect use of tar instead of zip

- cmd/main.go
- deploy/assisted-service.yaml
- pkg/log/context.go
- pkg/ocm/client.go
- pkg/s3wrapper/client.go
- pkg/s3wrapper/filesystem.go
Please comment on where to configure the ENV variables for factory/staging/development
> MGMT-2019 Json log format for assisted service

- internal/bminventory/inventory.go
No need to update openshift template because it will take the default value from the code.
> MGMT-2147 increase image expirer timeout to 4h

- internal/host/connectivitycheckcmd.go
- internal/host/connectivitycheckcmd_test.go
- internal/host/connectivitycheckconvertor.go
- internal/host/instructionmanager_test.go
- subsystem/host_test.go
> MGMT-2115 Fix case for failure to convert hosts to connectivity params and error message is generated in log

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1878610
> noProxy in ignition should be formatted as array

- cmd/main.go
- openshift/template.yaml
- pkg/ocm/client.go
Set OCM SDK logger level according to OCM_LOG_LEVEL env var.
> ocm client: support OCM_LOG_LEVEL env var

- internal/bminventory/inventory.go
Add Cluster User filtering in "complete_installation" API.
> OCPBUGSM-17629 Filter cluster in "complete_installation"

- pkg/log/context.go
> MGMT-2019 change back default log format to text

- internal/bminventory/inventory.go
> OCPBUGSM-17295 Set HTTPS_PROXY to HTTP_PROXY if omitted

- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
> OCPBUGSM-17903 In DHCP mode VIPs are not updated in database when cluster is in pending-for-input state

- internal/bminventory/inventory.go
- Add timeout of 300 seconds by default to wait for image pull
/cc @ronniel1
> OCPBUGSM-18042 Agent unable to start container during discovery

- internal/cluster/validations/validation_test.go
- pkg/auth/auth_handler.go
- pkg/ocm/pullsecret_auth.go
This reverts commit 8bd7f4bd01bba7d601620fe14a21e3a5ba7a1d75.
> Revert "OCPBUGSM-17629 Move Agent Auth cache to AuthHandler (#401)"

- internal/cluster/common.go
/cc @YuviGold 
/cc @RazRegev 
/cc @filanov 
/hold
> MGMT-2239 Fix occasional failure when cluster is updated with "nothing have changed" message

- go.mod
- go.sum
Newer OCM SDK should have retries for SSO token retrieval.
> OCPBUGSM-17629 Update OCM SDK for SSO retries

- internal/bminventory/inventory.go
- internal/cluster/validations/validation_test.go
- internal/cluster/validations/validations.go
- subsystem/cluster_test.go
> OCPBUGSM-16309 There is no BE DNS name validation - fix calling location

- internal/bminventory/inventory.go
- restapi/embedded_spec.go
- subsystem/cluster_test.go
- subsystem/host_test.go
- swagger.yaml
> MGMT-1970 Set DHCP vip allocation mode as true by default

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster_test.go
- internal/cluster/transition_test.go
- internal/cluster/validator.go
- internal/network/cidr_validations.go
> OCPBUGSM-17615 Installation hang on Finalizing

- pkg/job/job.go
Previously if we failed to clean up one of these jobs we would not
be able to re-deploy
> MGMT-2282 Create a random name for the initial iso job

- internal/bminventory/inventory_test.go
- internal/cluster/validations/validation_test.go
- internal/cluster/validations/validations.go
Use regex to verify given ssh key pattern.
> OCPBUGSM-13814-Extended-ssh-key-validation

- OWNERS
Signed-off-by: Erez Alster <erez@alster.co.il>
> NO-JIRA add kni-projects team to reviewers

- internal/ignition/ignition.go
- internal/ignition/ignition_test.go
This is an initial refactoring PR to make the ignition generation (and tests) a bit easier to edit as multiple people seem to be working  on it simultaneously.
> Refactor ignition generation

- internal/bminventory/inventory.go
Since the operations read and write from db as part of the refresh status.
> MGMT-2038: Make for-update transaction in enable/disable

- internal/cluster/registrar.go
Used models.ClusterStatusAddingHosts in RegisterAddHostsCluster.
> MGMT-2072 register cluster - use adding hosts status

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
Suggesting to print the internal error in the events and improve errors messages later.
> BUG-1885001 Register Error event will show internal error

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
Added a log when the api is finished to let us know how long it took
There is no event when cluster registration failed because there is no id to get this event from
> MGMT-2182 Add event on successful cluster registration

- Dockerfile.assisted-iso-create
- Makefile
- README.md
MGMT-2138 Added asisted-iso-create rhcos image download back
> MGMT-2138 Added asisted-iso-create rhcos image download back

- go.mod
- go.sum
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster.go
- internal/common/common.go
- pkg/s3wrapper/client.go
- pkg/s3wrapper/filesystem.go
- pkg/s3wrapper/mock_s3wrapper.go
Cluster log file: ClusterName_ClusterID.tar.gz
Host log file: ClusterName_HostRole_HostName.tar.gz
> MGMT-2128: Change log filenames, including for presigned S3 urls

- client/installer/get_cluster_install_config_responses.go
- client/installer/get_host_requirements_responses.go
- client/installer/update_cluster_install_config_responses.go
- restapi/embedded_spec.go
- restapi/operations/installer/get_cluster_install_config_responses.go
- restapi/operations/installer/get_host_requirements_responses.go
- restapi/operations/installer/update_cluster_install_config_responses.go
- swagger.yaml
In response to https://github.com/openshift/assisted-service/pull/310#discussion_r485945277
> Use infra_error for all 401 and 403 responses

- internal/bminventory/inventory.go
- internal/host/transition.go
- internal/host/transition_test.go
return forbidden error code when host in installing-pending-user-action tries to register after passing the reboot stage.
> MGMT-2359: Event log spam fix 

- internal/host/host.go
Removed redundant debug log in UpdateApiVipConnectivityReport.
> host: removed redundant debug log

- internal/host/host.go
- internal/host/host_test.go
- internal/host/transition_test.go
- internal/metrics/metricsManager.go
- internal/metrics/mock_netricsManager_api.go
- subsystem/host_test.go
/assign @ErezAlster 
/assign @nmagnezi
> MGMT-2341 Add host hw type to host metrics

- OWNERS
This reverts commit 05dd42a37c673abd6e8f2c0ebdcde050c116b206.
> Revert "Temporarily disable push to master"

- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/transition_test.go
- internal/host/host.go
- internal/host/host_test.go
- internal/host/monitor.go
- internal/host/monitor_test.go
monitor using batches of hosts and clusters and not load everything into memory at once
> MGMT-2296 Host and cluster monitor iterate in baches

- tools/deploy_olm.py
- tools/utils.py
- Fixing [BZ1874631](https://bugzilla.redhat.com/show_bug.cgi?id=1874631)
- Fixing [BZ1874632](https://bugzilla.redhat.com/show_bug.cgi?id=1874632)
- Fixing [BZ1874633](https://bugzilla.redhat.com/show_bug.cgi?id=1874633)
> [BZ1874632] Fixing Monitoring deployment

- internal/common/common_unitest_db.go
it will help run tests locally from inside the direcoty - current db version fail some of the tests
> NO-ISSUE Set local ut run db to alpine

- internal/host/instructionmanager.go
Renamed VERIFY_API_VIP_CIDR env var to SUPPORT_L2.
> MGMT-2427 use SUPPORT_L2 env var

- internal/network/cidr_validations.go
Removed the suggestion
/cc @avishayt 
/cc @ronniel1
> OCPBUGSM-17572 misleading suggestions when saving invalid CIDR

- openshift/template.yaml
Added SUPPORT_L2 flag to template.yaml
@gamli75 @ybettan @yevgeny-shnaidman
> MGMT-2427 openshift template: added SUPPORT_L2

- Jenkinsfile
Reverts openshift/assisted-service#471
It allows also PRs to publish.
> Revert "Publish images per versions"

- internal/cluster/transition_test.go
- internal/cluster/validator.go
- internal/common/common.go
- subsystem/cluster_test.go
> OCPBUGSM-18082 - Worker number should not be 1

- models/disk.go
- restapi/embedded_spec.go
- swagger.yaml
> MGMT-2420 Collect additional bootable information on disks

- subsystem/cluster_test.go
- subsystem/utils_test.go
Timeout for waiting to cluster state change iincreased to match 2 workers setup
> OCPBUGSM-18082 - Increase defaultWaitForClusterStateTimeout

- subsystem/cluster_test.go
> OCPBUGSM-18082 - Fix install command failed test

- Dockerfile.assisted-service
- Dockerfile.assisted-service-onprem
It's a quarter the size and we know who built it
This is the followup mentioned in https://github.com/openshift/assisted-service/pull/551#pullrequestreview-508380261
> NO-ISSUE Use the centos image from app-sre

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
> MGMT-2389 - Missing cluster_id in some logs

- models/dhcp_allocation_request.go
- models/dhcp_allocation_response.go
- restapi/embedded_spec.go
- swagger.yaml
> MGMT-2659 DHCP server changes the VIPs addresses after installation has started - Swagger changes

- Makefile
When deploying onprem assisted-service, we must mount in the livecd and
coreos-installer the same way we would if running on livecd.
> NO-ISSUE Update Makefile for onprem

- internal/host/host.go
- internal/host/host_test.go
- internal/host/instructionmanager.go
- internal/host/instructionmanager_test.go
Temporary add get inventory to installing-in-progress state
to get change of the formatted disks in the inventory model (bootable)
> MGMT-2770 add inventory to installing-in-progress

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/host/common.go
- internal/host/host.go
- internal/host/instructionmanager.go
- internal/host/statemachine.go
- internal/host/transition.go
- internal/host/transition_test.go
- internal/host/validator.go
/assign @danielerez 
/assign @ori-amizur
> MGMT-2464 - update state machine and instruction for day2 OCP

- tools/deploy_assisted_installer.py
Force single replica for the service installed on an ocp cluster.
> MGMT-2465: day2 - single replica for ocp

- internal/host/transition.go
- internal/host/transition_test.go
> MGMT-2965 Reset fields when enabling host

- tools/deploy_assisted_installer_configmap.py
This will allow changing the images so those commands as expected
> NO-ISSUE - Added missing env forwarding in deploy configmap

- models/inventory.go
- restapi/embedded_spec.go
- swagger.yaml
This reverts commit 1ac2c61ac6978b9535badb56181f5036a8b8bb3c.
@avishayt accidentally approved it
> Revert "MGMT-3078 - Add a unfiltered_disks list entry to the inventory API (#740)"

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/host/common.go
- internal/host/host.go
- internal/host/host_test.go
- internal/host/mock_host_api.go
- models/cluster_update_params.go
- models/host.go
- restapi/embedded_spec.go
- subsystem/day2_cluster_test.go
- swagger.yaml
/cc @yevgeny-shnaidman @filanov @romfreiman
> MGMT-3054 Add host machine config pool

- internal/bminventory/inventory.go
In order to reduce method cyclomatic complexity
> NO-ISSUE add helper method to updateClusterData

- pkg/auth/auth_handler_test.go
- pkg/auth/auth_suite_test.go
- pkg/auth/authz_handler_test.go
- pkg/log/logcontext_test.go
Change auth package tests to use httptest server
Change log package tests to use httptest server
> MGMT-3130: Change unit tests to use httptest server instead of http server

- internal/host/monitor.go
- internal/host/statemachine.go
- internal/host/transition_test.go
> OPCBUGSM-20841: Wrong boot order hosts will be set to error when cluster status is error

- dashboards/grafana-dashboard-assisted-installer-general-overview.configmap.yaml
Starting with assisted-installer-vendor-phases
> MGMT-2254 Migrate Grafana dashboards to assisted-service codebase

- OWNERS_ALIASES
Signed-off-by: Antoni Segura Puimedon <antoni@redhat.com>
> NO-ISSUE Adding Richard Su and Sudarshan Acharya

- go.mod
- go.sum
- internal/hardware/mock_validator.go
- internal/hardware/validator.go
- internal/hardware/validator_test.go
- internal/host/host.go
- internal/host/host_test.go
- internal/host/validator.go
- models/disk.go
- restapi/embedded_spec.go
- subsystem/host_test.go
- swagger.yaml
The reverted PR caused the service to crash (probably) due to lack of database migration. Will re-open the PR after investigating / adding migrations
> MGMT-3078 - Reverted #772

- internal/network/ntp_utils.go
Fixes https://github.com/openshift/assisted-service/pull/796
> OCPBUGSM-21552 Bugfix trailing parenthesis

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/mock_cluster_api.go
- internal/cluster/validations/validation_test.go
- internal/cluster/validations/validations.go
- internal/common/common.go
- internal/connectivity/mock_connectivity_validator.go
- internal/events/mock_event.go
- internal/hardware/mock_validator.go
- internal/host/mock_host_api.go
- internal/host/mock_instruction_api.go
- internal/metrics/mock_netricsManager_api.go
- internal/network/mock_ntp_utils.go
- internal/oc/mock_release.go
- models/cluster.go
- models/cluster_create_params.go
- models/cluster_update_params.go
- models/ntp_synchronization_request.go
- pkg/generator/mock_install_config.go
- pkg/k8sclient/mock_k8sclient.go
- pkg/leader/mock_leader_elector.go
- pkg/ocm/mock_authorization.go
- pkg/ocm/mock_pullsecret_auth.go
- pkg/s3wrapper/mock_s3iface.go
- pkg/s3wrapper/mock_s3wrapper.go
- restapi/embedded_spec.go
- swagger.yaml
Completes https://github.com/openshift/assisted-installer-agent/pull/118
> OCPBUGSM-21366 Support comma-separated NTP sources list

- internal/host/logscmd.go
- internal/host/logscmd_test.go
Gather all IPs for must-gather logs, in case of None-Platform
> MGMT-2991 None-Platform logs commands IPs

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/hardware/validator.go
- internal/host/host.go
- internal/host/host_test.go
- internal/host/installcmd.go
- internal/host/mock_host_api.go
- internal/hostutil/host_utils.go
> MGMT-3117 select boot disk

- Makefile
- tools/deploy_assisted_installer.py
- tools/utils.py
Populated Makefile targets for openshift's ci, and tweaked the Makefile and some deployment python scripts to support deployment on openshift's ci
> MGMT-2256: openshift ci build and deploy

- internal/host/installcmd.go
- internal/host/installcmd_test.go
This reverts commit 9ede34392f7d21ee7fccc9e613d582f90e6c74d1.
> Revert "MGMT-3410 Add HA mode to install command (#835)"

- internal/host/installcmd.go
- internal/host/installcmd_test.go
This reverts commit cc6eec50adfd986b3c0409b7e9b7d8ecb4db5381.
> MGMT-3410 Add HA mode to install command

- Jenkinsfile
example resault: http://assisted-jenkins.usersys.redhat.com/job/assisted-service/job/master/4128/
> MGMT-3452 Collect logs from onprem on AI CI

- restapi/embedded_spec.go
PR #755 created some generated files that were not committed, this PR adds them
> MGMT-3100 - Add missing generated files from #755

- build_deploy.sh
> NO-ISSUE Stop trying to push the iso create image

- Makefile
- openshift/template.yaml
> MGMT-3330 default OPENSHIFT_VERSION 

- go.sum
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- subsystem/ipv6_test.go
BZ-1912560 Fix duplicate entries in host networks seen in IPv6 networks
/cc @ronniel1
> OCPBUGSM-22671,  OCPBUGSM-22656 Remove IPv6 networks from host networks.

- cmd/main.go
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/mock_installer_internal.go
- internal/controller/api/v1alpha1/image_types.go
- internal/controller/api/v1alpha1/zz_generated.deepcopy.go
- internal/controller/config/crd/bases/adi.io.my.domain_images.yaml
- internal/controller/controllers/cluster_controller_test.go
- internal/controller/controllers/error_utils.go
- internal/controller/controllers/image_controller.go
- internal/controller/controllers/image_controller_test.go
Added 'create' functionality to image reconcile which use
GenerateClusterISO logic to generate the required image.
Will create an image for each new event.
> MGMT-3361: Image Controller - Create

- internal/bminventory/inventory.go
- internal/ignition/ignition.go
- models/static_ip_config.go
- restapi/embedded_spec.go
- swagger.yaml
Adds optional IPv6 static IP in addition to IPv4, makes IPv4 static IP optional.
> MGMT-3200 Add IPv6 static IP

- dashboards/grafana-dashboard-assisted-installer-general-overview.configmap.yaml
- dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml
update general & weekly overview to have the options to be filtered by oc versuion 
dev dashbards:
> MGMT-3508 Adjust Grafana dashboards to filter data by openshift version

- Makefile
- cmd/main.go
- internal/controller/api/v1alpha1/cluster_types.go
- internal/controller/config/crd/bases/adi.io.my.domain_images.yaml
- internal/controller/config/rbac/role.yaml
- internal/controller/config/rbac/secret_patch.yaml
- internal/controller/controllers/cluster_controller.go
- internal/controller/controllers/cluster_controller_test.go
- internal/controller/controllers/controllers_suite_test.go
Reconcile existing cluster every 10 seconds to the a new status from the backend,
it's a temporary solution until we implement notifications from the backend
> MGMT-3434 Support cluster update with k8s API

- Makefile
Adding format-check so it can be called in prow. Needed for: https://github.com/openshift/release/pull/14816
> NO-ISSUE Add format-check to Makefile

- go.mod
- go.sum
- internal/bminventory/inventory.go
- internal/cluster/cluster.go
- internal/host/host.go
- internal/host/mock_host_api.go
- internal/metrics/metricsManager.go
- internal/metrics/metricsManager_test.go
- internal/metrics/mock_metrics_manager_api.go
- subsystem/metrics_test.go
> MGMT-3442: Report metrics for host validation errors.

- internal/cluster/transition.go
- internal/common/common.go
- internal/ignition/ignition.go
- internal/network/manifests_generator.go
Also make these configurations only when installing IPv6
/cc @YuviGold
> MGMT-3680 Make IPv6 configuration be sent by ignition and not by manifest when not in single node

- pkg/auth/authz_handler_test.go
- restapi/embedded_spec.go
- swagger.yaml
[OCPBUGSM-23132](https://issues.redhat.com/browse/OCPBUGSM-23132) - Add listSupportedOpenshiftVersions test.
> OCPBUGSM-23132 - Allow read-only-admin to call openshift_versions call

- internal/bminventory/inventory.go
It will help us when debugging and searching for install and update progress flows
It provide the request id in order to see the flows
> NO-ISSUE Add info logs to install and update progress apis

- internal/cluster/cluster_test.go
- internal/cluster/transition.go
- internal/ignition/ignition.go
- internal/network/manifests_generator.go
- internal/network/manifests_generator_test.go
- internal/network/mock_manifests_generator.go
> MGMT-3691 Move IPv6 single IP configuration after pivot to use ignition instead of manifest

- internal/ignition/ignition.go
DHCP ipv6 configuration changes nm connections directory of the Network Manager,
therefore causing it to ignore the static ip configurations in the default path.
In case of IPv6 config present , static ip configs must be moved to a new path
> MGMT-3717 support IPv6 config for DHCP in static ip scenario

- internal/installcfg/installcfg.go
- internal/installcfg/installcfg_test.go
> OCPBUGSM-23568 Generate default no proxy in install-config to avoid passing internal cluster communication through the proxy

- dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml
This PR is a followup to https://github.com/openshift/assisted-service/pull/879
> MGMT-3747 Filter ISO Generated data by openshift version

- internal/ignition/ignition.go
For the minimal iso + static IP case we need to ensure we have
networking before we attempt to fetch the rootfs. This means that
we need to configure a static IP address early in the boot process.
In this environment we have a limited set of tools so to make the
script work for both scenarios this commit removes `find`, `envsubst`,
and `systemd-cat` from the script.
Additionally it adds a conditional to change the location to write
out the networking config. In the initrd environment, we write to
`/run/NetworkManager`, but in the booted system, we would write to
`/etc/NetworkManager`.
> MGMT-3510 Alter the static ip config script to work during boot

- internal/host/host.go
- internal/metrics/metricsManager.go
- internal/metrics/mock_metrics_manager_api.go
- subsystem/metrics_test.go
Reverts openshift/assisted-service#952
> Revert "MGMT-3658: Generate event/metric in case an host validation is changing."

- subsystem/kubeapi_test.go
- subsystem/subsystem_suite_test.go
and utils to be used in future tests
> MGMT-3362: Subsystem for kube api with basic installation test

- internal/host/common.go
- internal/host/statemachine.go
- internal/host/transition.go
- internal/host/transition_test.go
test-infra test: http://assisted-jenkins.usersys.redhat.com/job/assisted-test-infra/job/master/4188/
> MGMT-3802 + MGMT-3299 Cluster fail if host is not responsive

- internal/host/transition_test.go
- internal/host/validator.go
Changed validation to be pending if there are not at least 3 non disabled hosts in cluster
/cc @avishayt
> OCPBUGSM-19591 Host connectivity validation fails when only 2 nodes booted

- internal/host/hostcommands/instruction_manager_test.go
- internal/host/hostcommands/logs_cmd_test.go
Resolves https://github.com/openshift/assisted-service/pull/1008 change for the tests.
/cc @rollandf
> MGMT-3576 Fix logs_cmd timeout test

- tools/handle_ocp_versions.py
This is in order to allow
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/14577
to work as expected
> MGMT-3826 - Versions JSON validation exception for specific single-node version

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1916661
> OCPBUGSM-23207 - Overwrite the default value of host_networks

- internal/controller/controllers/clusterdeployments_controller.go
One change here is that in hive clusterDeployment Spec, PullSecretRef
is a LocalObjectReference, meaning it has no Namespace attribute.
Therefore, under the assumption that a k8s secret and clusterDeployment
reside on the same namespace, I remove that from the if statement.
> MGMT-3908 Port mapSecretToCluster to clusterDeployment controller

- Makefile
> NO-ISSUE add swagger changes validation to the build

- internal/controller/config/crd/kustomization.yaml
This is a followup to https://github.com/openshift/assisted-service/pull/1023
> MGMT-3920 rename host crds to agents in kustomization.yaml

- internal/cluster/transition_test.go
- internal/ignition/ignition.go
- internal/operators/ocs/utils.go
- internal/operators/ocs/validations.go
Each disk requires additional 2 cpus , 5gb ram
> MGMT-3884: Modified OCS validations to use all disks

- Makefile
- tools/utils.py
> Get cluster server and verify cluster instead of specific minikube

- subsystem/metrics_test.go
> MGMT-3911: Fixing 'belongs-to-majority-group' validation test.

- tools/handle_ocp_versions.py
> MGMT-4061: using the PULL_SECRET env-var to access the OCP image

- Jenkinsfile
- Makefile
- skipper.yaml
Eliminating the unit-tests coverage output conversion for standalone builds
> NO-ISSUE standalone build performance improvements

- config/onprem-iso-config.ign
- config/onprem-iso-fcc.yaml
- default_ocp_versions.json
- onprem-environment
- openshift/template.yaml
@romfreiman @ronniel1 @gamli75 @oshercc
> MGMT-4059, Bump OCP version from 4.6.12 to 4.6.16 (auto created)

- tools/deploy_assisted_installer_configmap.py
- tools/update_bm_cm.py
- tools/utils.py
> use 'safe_load' instead of 'load' to remove deprecation warning

- internal/host/host.go
- internal/host/host_test.go
- internal/host/validator.go
- subsystem/host_test.go
> OCPBUGSM-25012 Check download rate only for an image with a positive size

- tools/handle_ocp_versions.py
/hold
/cc @YuviGold 
fixes #527
> NO-ISSUE: validate PULL_SECRET value before using it

- internal/bminventory/inventory.go
Some validation failures are not printed to log on cluster
registration, but just returned as part of the api response.
Since we use the internal registration logic in the cluster
controller we can miss some errors that are not logged in
UpdateClusterInternal.
In this PR I updated the error logging in case of cluster
registration failure and made sure the error will be printed.
> MGMT-3370: Added error logs to RegisterClusterInternal

- Makefile
Fixing deployment to OCP cluster
> NO-ISSUE add target to deploy-resources

- config/onprem-iso-config.ign
- config/onprem-iso-fcc.yaml
- default_ocp_versions.json
- onprem-environment
- openshift/template.yaml
@romfreiman @ronniel1 @gamli75 @oshercc
> MGMT-4161, Bump OCP version from 4.7.0-fc.4 to 4.7.0-rc.2 (auto created)

- Dockerfile.assisted-service
Add build and setup of the nmstate lib to the Assisted Service container
Currently we are building and setting the code from the master branch
Once the needed code is pushed into nmstate 4.8 reelase, we will be
able to installed released package
> MGMT-4088 add nmstate package to the AssistedService image

- openshift/template.yaml
> NO-ISSUE: Adding WITH_AMS_SUBSCRIPTIONS to deployment template.

- cmd/main.go
- internal/cluster/cluster_test.go
- internal/cluster/transition_test.go
- internal/cluster/validator.go
- internal/ignition/ignition_test.go
- internal/operators/manager.go
- internal/operators/manager_test.go
- internal/operators/ocs/consts.go
- internal/operators/ocs/validations.go
> OCPBUGSM-1927631 Modified the ocs validations to use all HDD or SSD driveType disks except installation disk

- client/installer/complete_installation_parameters.go
- client/installer/get_cluster_parameters.go
- client/installer/get_host_parameters.go
- client/installer/get_next_steps_parameters.go
- internal/ignition/ignition.go
- models/api_vip_connectivity_response.go
- models/cluster.go
- models/dhcp_allocation_response.go
- models/disk.go
- restapi/embedded_spec.go
- restapi/operations/installer/complete_installation_parameters.go
- restapi/operations/installer/get_cluster_parameters.go
- restapi/operations/installer/get_host_parameters.go
- restapi/operations/installer/get_next_steps_parameters.go
- swagger.yaml
> NO-ISSUE Fix typos

- tools/deploy_assisted_installer_configmap.py
will log the git revision when the git revision label is available
```assisted-installer image for deployment: quay.io/ocpmetal/assisted-installer:latest
[INFO] 2021-02-21 21:33:57,069 - deploy-service-configmap - quay.io/ocpmetal/assisted-installer:latest using b4974e7dc0d5d216fb96e58707fa9fbf9bb57890 git_revision
assisted-installer-controller image for deployment: quay.io/ocpmetal/assisted-installer-controller:latest
[INFO] 2021-02-21 21:34:17,641 - deploy-service-configmap - quay.io/ocpmetal/assisted-installer-controller:latest using b4974e7dc0d5d216fb96e58707fa9fbf9bb57890 git_revision
assisted-installer-agent image for deployment: quay.io/ocpmetal/assisted-installer-agent:latest
Overriding assisted-service deployment image according to env SERVICE
assisted-service image for …
```
> MGMT-3667 Print git_revision label for every image on deployment

- internal/host/host.go
- internal/host/host_test.go
> MGMT-4295 Verify that a host is valid to be master not only if it is in known state

- internal/cluster/transition_test.go
- internal/operators/ocs/validations.go
Signed off by: Rewant Soni resoni@redhat.com
> OCPBUGSM-1928868 : Add validation for Auto-assign role

- models/domain_resolution_request.go
- models/domain_resolution_response.go
- restapi/embedded_spec.go
- swagger.yaml
This API is yet to be used by anyone so this is an okay API breaking change
> MGMT-3856 - Fix weird domain resolution auto-generated swagger name

- internal/operators/manager.go
- internal/operators/ocs/utils.go
> OCPBUGSM-1931840 Removed channel from Subscription manifest to allow OCS to install latest version

- config/onprem-iso-config.ign
- config/onprem-iso-fcc.yaml
- default_ocp_versions.json
- onprem-environment
- openshift/template.yaml
@romfreiman @ronniel1 @gamli75 @oshercc
> MGMT-4281, Bump OCP versions

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/validations/validation_test.go
- internal/cluster/validations/validations.go
- subsystem/ipv6_test.go
This combination is currently not supported
> MGMT-3865 Block VIP DHCP allocation with IPv6 machine network

- internal/controller/controllers/common.go
- internal/controller/controllers/controllers_suite_test.go
- subsystem/kubeapi_test.go
Change the format to match the same as Hive using
> MGMT-4347 Fix pull secret format to dockerconfigjson

- models/cluster.go
- restapi/embedded_spec.go
- swagger.yaml
log-info format should be the same on host and cluster objects
> MGMT-3854 API convert log info on cluster to ref

- docs/user-guide/restful-api-guide.md
- docs/user-guide/user-guide.md
> MGMT-4343 Document how to set static network config with curl

- internal/bminventory/inventory.go
- internal/network/cidr_validations.go
> OCPBUGSM-25000 Unclear error message when saving wrong service CIDR

- internal/operators/ocs/validations.go
> MGMT-4345 Removed setOperatorStatus from OCS validations code

- dashboards/grafana-dashboard-assisted-resource-dashboard.yaml
Replacing https://github.com/openshift/assisted-service/pull/1159
> NO-ISSUE Performance grafana dashboard

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/common.go
- internal/cluster/mock_cluster_api.go
- internal/cluster/statemachine.go
- internal/cluster/transition.go
- internal/cluster/transition_test.go
- internal/host/host.go
- internal/host/host_test.go
- internal/host/hostutil/update_host.go
- internal/host/mock_host_api.go
- internal/host/monitor.go
- internal/host/statemachine.go
- internal/host/transition.go
- subsystem/cluster_test.go
- subsystem/utils_test.go
/assign @tsorya 
Please ignore the debug messages in the review. I will pull them out after I'll fix all the code review comments
> Log info implementation

- docs/dev/olm-operator-plugins.md
- internal/operators/builder.go
This PR updates OLM operator plugins development doc and adds cnv operator to monitored operators.
> MGMT-4079 CNV update

- internal/operators/ocs/ocs_operator.go
> OCPBUGSM-1936338 Fixed the total disks to be used while generating OCS manifests.

- internal/isoeditor/rhcos.go
- internal/isoeditor/rhcos_test.go
Used gzip to compress the custom RAM disk before writing
into the placeholder (as done for the ignition archive).
> MGMT-4366 compress custom ramdisk archive

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
Added image type (full-iso/minimal-iso) to the following events:
* Started image download (image type is "<image_type>")
* Re-used existing image rather than generating a new one (image type is "<image_type>")
Similar to the exisiting event: Generated image (Image type is "minimal-iso...
> OCPBUGSM-25057 added image type to events

- Makefile
Until we are building the bundle in Jenkins, we probably shouldn't attempt to publish it :sunglasses:
> NO-ISSUE: remove bundle from publish

- Makefile
The publish step is failing with
"quay.io: unauthorized: access to the requested resource is not authorized"
> NO-ISSUE Revert PR#1285 adding operator-bundle to build-all and publish

- internal/cluster/transition.go
> MGMT-3109 increase timeout for cluster logs when logs requested

- internal/operators/cnv/cnv_operator.go
> MGMT-4079 Check whether inventory available

- internal/operators/ocs/manifest.go
> OCPBUGSM-26476 Set portable to false for StorageCluster CR

- go.mod
- internal/bminventory/inventory.go
- internal/bminventory/mock_installer_internal.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
- internal/controller/controllers/crd_utils.go
- subsystem/kubeapi_test.go
Once the cluster in installed, the ClusterDeployment CR is updated:
- Change Spec.Installed to True
- Create a Secret for Admin password and update Spec.ClusterMetadata.AdminPasswordSecretRef
- Create a Secret for KubeConfig  and update Spec.AdminKubeconfigSecretRef
> MGMT-4234 Update ClusterDeployment CR MetaData

- subsystem/kubeapi_test.go
There can be a race condition when updating the Agent CR:
"Operation cannot be fulfilled on agents.adi.io.my.domain \"8eba2a11-92fb-46a4-b30a-90a1da274ab3\": the object has been modified; please apply your changes to the latest version and try again"
Adding a retry will prevent false alerts.
> NO-ISSUE Add retry to update agent in kube-api subsystem test

- OWNERS_ALIASES
jira: NO-ISSUE
Signed-off-by: Flavio Percoco <flaper87@gmail.com>
> NO-ISSUE  Add flaper87 to OWNERS_ALIASES

- docs/operator.md
jira: NO_ISSUE
Signed-off-by: Flavio Percoco <flaper87@gmail.com>
> NO-ISSUE: Fix typo in the documentation

- subsystem/kubeapi_test.go
Sometimes updating a CR fails if a change in the revision happened
between the time we get the CR to the time we update it.
> NO-ISSUE: Add retries to Agent Update in kube-api

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/common/disks_info.go
- internal/host/host.go
- internal/host/host_test.go
- internal/host/mock_host_api.go
- Add support for new tool invocation
- Database update as result of new tool
/cc @YuviGold 
/cc @eranco74
> MGMT-4398 Handle post step reply changes for new tool in assisted service

- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/refresh_status_preprocessor.go
- internal/cluster/transition.go
- internal/cluster/transition_test.go
- internal/host/host.go
- internal/host/transition_test.go
- internal/metrics/metricsManager.go
- internal/metrics/mock_metrics_manager_api.go
- subsystem/cluster_test.go
- subsystem/kubeapi_test.go
- subsystem/metrics_test.go
- subsystem/utils_test.go
Cluster lifecycle:
Metric and event will be generated if a cluster validation went to
`failed` state after being in `succeed` state. Another event will be
sent once the validation is fixed.
Cluster deletion:
Metric will be generated for each cluster validation on `failed`
status on cluster deletion.
In addition, this is also making sure each cluster RefreshStatus
updates the DB with the updated cluster validations_info if new data
exist.
e2e:
```
"Registered cluster \"test-infra-cluster-assisted-installer\""
"Successfully registered cluster test-infra-cluster-assisted-installer with id f0bd776d-4563-48a9-9db3-6d38530b3450"
"Updated status of cluster test-infra-cluster-assisted-installer to pending-for-input"
"Generated image (Image type is …
```
> MGMT-3659,MGMT-3483: Generate metrics/event on cluster validations failure/changes.

- subsystem/kubeapi_test.go
- Increase timeout on some asserts
- Wait for Installing instead of Preparing for Installation
> NO-ISSUE Fixes in kubeAPI subsystem tests

- internal/operators/ocs/manifest.go
Signed-off-by: priyanka19-98 <pjiandan@redhat.com>
> OCPBUGSM-25994 Fix for unbalanced disks on OCS StorageCluster

- subsystem/image_test.go
Uncomment and fix existing tests and handle versions better. We shouldn't be making API calls outside of the per-test lifecycle. If any of the assertions outside of an `It` block fail the suite panics.
Did you intend for these to remain commented out @yevgeny-shnaidman ?
Is there any reason not to run them?
They were commented in https://github.com/openshift/assisted-service/pull/1096
cc @YuviGold I think we talked about these tests in the past
> NO-ISSUE Fix image subsystem tests

- pkg/s3wrapper/filesystem.go
- pkg/s3wrapper/filesystem_test.go
Currently, when multiple versions are specified in OPENSHIFT_VERSIONS
while using the filesystem client the image file gets corrupted. With
this change, the filesystem client will simply download the image(s)
specified in OPENSHIFT_VERSIONS and use the appropriate version when
building discovery ISOs.
> OCPBUGSM-26705: multi-version support fs client

- internal/operators/cnv/cnv_operator.go
Follow-up for https://github.com/openshift/assisted-service/pull/1329#discussion_r596001227 review comment.
> MGMT 4531 refactor cnv operator

- internal/operators/ocs/manifest.go
- internal/operators/ocs/manifests_test.go
Signed-off-by: Priyanka Jiandani <pjiandan@redhat.com>
> OCPBUGSM-26879 Fixed indentation issues in OCS manifest generation along with unit-tests

- dashboards/grafana-dashboard-assisted-resource-dashboard.yaml
Fixes some templating issues with this Grafana dashboard
> NO-ISSUE Update QE grafana Perf dashboard

- docs/Kube-API-examples.md
- docs/crds/clusterDeployment-SNO.yaml
- docs/crds/clusterDeployment.yaml
- docs/crds/installEnv.yaml
- docs/crds/nmstate.yaml
- docs/crds/pullsecret.yaml
This will replace https://github.com/nmagnezi/assisted-service-crs
> MGMT-4694 Adds KubeAPI CRD examples

- subsystem/metrics_test.go
It fails on Prow, I cannot reproduce it locally and since it doesn't
add any cover edge to the validations metrics/event generation I am
removing it.
> NO-ISSUE: Removing flaky test on cluster validations metrics.

- docs/crds/clusterDeployment-SNO.yaml
SNO will be supported starting from OpenShift 4.8
> NO-ISSUE Update clusterDeployment CRD imageSetRef name to openshift-v4.8.0

- internal/migrations/20201019194303_change_overrides_to_text_test.go
- internal/migrations/20201202140700_change_image_ssh_key_text_test.go
- internal/migrations/20210218160100_validations_info_to_text_test.go
- internal/migrations/20210223090000_host_validations_info_to_text_test.go
- internal/migrations/migrations_suite_test.go
Migration unit tests didn't delete the test DB they created,
now they will.
/cc @carbonin
> NO-ISSUE - Migrations unit tests database cleanup

- Makefile
- config/assisted-service/kustomization.yaml
Missed these changes in https://github.com/openshift/assisted-service/pull/1397
@rwsu @djzager Anything else I missed? :worried:
> NO-ISSUE Add the local auth secret to the operator bundle

- internal/bminventory/inventory.go
> MGMT-4749 Add cluster id to logs on cluster create

- internal/cluster/cluster.go
- subsystem/cluster_test.go
User's manifests considered as part of cluster configuration, therefore
on cluster-reset they should retain.
> OCPBUGSM-26495 Resetting a cluster removes user's created manifests

- cmd/main.go
Previously on the first deploy of the service with multiple
replicas each pod would set `haveLatestMinimalTemplate` to true
and then block on the leader lock. When a pod got the lock it would
force an upload of the minimal template file even if it had been
uploaded by another replica already.
Additionally, we need to keep the check for the template outside
of the version loop as the template version marker file is shared
between all iso versions.
As a solution we take the lock once and only check if we have the
latest minimal template while holding the lock. Then we can safely
upload the boot files for all versions in a single replica. By the
time the other replicas get the lock they will see that the template
version is up to date and will no-op the uploads.
This issue was causing …
> NO-ISSUE Fix boot file upload race

- cmd/main.go
- go.mod
- go.sum
- internal/bminventory/inventory.go
- internal/installercache/installercache.go
- internal/oc/release.go
- internal/oc/release_test.go
Added retry in case `oc extract` failed for any reason.
https://bugzilla.redhat.com/show_bug.cgi?id=1940149
> Retry extracting the installer from the release image

- Makefile
- build_images.sh
> NO-ISSUE Remove skipper dependency from build_images.sh AppSRE script

- docs/crds/clusterDeployment-SNO.yaml
- docs/crds/installEnv.yaml
- internal/controller/api/v1alpha1/installenv_types.go
- internal/controller/api/v1alpha1/zz_generated.deepcopy.go
- internal/controller/config/crd/bases/adi.io.my.domain_installenvs.yaml
- internal/controller/config/crd/resources.yaml
- internal/controller/controllers/installenv_controller.go
- subsystem/kubeapi_test.go
That key will get injected into the discovery image for debug proposes
> MGMT-4580 InstallEnv should only accept a single optional SSH key

- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/transition.go
- subsystem/cluster_test.go
Co-authored-by: osher cohen <oscohen@localhost.localdomain>
> MGMT-4822 Skip un-needed cluster status update (#1423)

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
This PR adds the ability to select an installation disk based on the RootDeviceHints provided by the BMH. Note that only the hints supported by OpenShift (BareMetal Operator, specifically) were implemented here. The rest of the filters and operations supported by ironic are not needed for now as they are not even used today in the OpenShift case.
> MGMT-4850 set InstallationDiskID based on RootDeviceHints

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
This commit simplifies the logic to get the agent to use for the BMH reconcile process. Instead of the complex logic that had been implemented, this PR switches to using the newest agent as the creation date is authoritative for this case.
> MGMT-4848 Return the newest agent in findAgent

- models/gpu.go
- restapi/embedded_spec.go
- swagger.yaml
This PR adjusts the GPU data model to meet capabilities of GPU detection tooling.
> MGMT-4734 Adjust GPU data model

- internal/network/machine_network_cidr.go
- internal/network/manifests_generator.go
Fixing error message in GetIpForSingleNodeInstallation
> OCPBUGSM-27612 - Fix typo in dnsmasq description

- subsystem/kubeapi_test.go
Currently those test tries to update clusterdeployement once and if fails test will fail.
From get clusterdeployement to update, it can change and we will fail.
Adding eventually update to fix it
> NO-ISSUE making subsystem for ignition override less flaky

- Makefile
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/common/error_utils.go
Fix `_post_test` target to collect junit reports to exclude the `REPORTS` directory.
> MGMT-4996 Bugfix Wrap REST error StatusNotFound when gorm record isn't found

- internal/operators/ocs/validation_test.go
- internal/operators/ocs/validations.go
Update Standard mode CPU requirements to 30 and RAM requirements to 81
> OCPBUGSM-1948449: Update Standard Deployment RAM and CPU requirements

- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
- subsystem/kubeapi_test.go
Untill dynmaic z stream is supported 4.8 will be installed for both SNO and muli node clusters
> MGMT-5249 AI controller will install only OCP 4.8

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster_test.go
- internal/cluster/common.go
- internal/cluster/registrar.go
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/infraenv_controller.go
- internal/host/host.go
- internal/operators/handler/handler.go
- subsystem/kubeapi_test.go
This function is deprecated on gorm v2.
> NO-ISSUE Replace gorm.IsRecordNotFoundError with errors.Is

- dashboards/grafana-dashboard-assisted-installer-validations.configmap.yaml
This dashboard shows validations statistics for the hosts and the
cluster objects during the cluster lifecycle and on cluster
deregistration.
> MGMT-3443: Adding Grafana dashboards for validations metrics.

- cmd/main.go
- go.mod
- go.sum
- internal/host/host.go
- internal/host/host_test.go
- internal/host/monitor_test.go
- internal/host/refresh_status_preprocessor.go
- internal/host/refresh_status_preprocessor_test.go
- internal/host/statemachine.go
- internal/host/statemachine_test.go
- internal/host/transition_test.go
Split PR from #1432. This PR focuses only on the logic to disable host validations and remove those validations from the require state machine conditions. 
@YuviGold can you take a look?
Thanks
/Jordi
> MGMT-5265 Add the ability to disable host validations via configuration

- internal/host/statemachine.go
- internal/host/transition_test.go
Missing transition for epic https://issues.redhat.com/browse/MGMT-3563
/cc @filanov
> MGMT-5288 Handle NOOP transition for host "preparation-successful" state

- internal/operators/ocs/consts.go
- internal/operators/ocs/ocs_operator.go
- internal/operators/ocs/ocs_operator_test.go
- internal/operators/ocs/test_utils.go
- internal/operators/ocs/validation_test.go
- internal/operators/ocs/validations.go
- pkg/conversions/conversions.go
Signed-Off-By: Rewant Soni <resoni@redhat.com>
OCS Host Validation with AI: https://docs.google.com/document/d/1qax4_lPvj5wLz7TjupcHhE0WDeflqSZApyg9uaUEhWQ/edit
> MGMT-4557: Add Host Validation for OCS

- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
On reboot, NetworkManager doesn't wait for IPv4 addresses if it
gets IPv6 addresses from DHCP. As a result, ignition download
over IPv4 fails. To control this behavior, pass `ip=dhcp` in case
of IPv4, and `ip=dhcp6` in case of IPv6.
> OCPBUGSM-26846 Fix DHCP failing silently on reboot

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
This PR is based on the work already done by Sudarshan here https://github.com/openshift/assisted-service/pull/1514/commits/7601896f469af6e186c5492df18105d4ae7c1aea and fixes the failing test case by making necessary changes.
Ref: https://issues.redhat.com/browse/MGMT-5236
> MGMT-4494 Unit tests for reconciling day2 worker

- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/refresh_status_preprocessor.go
- internal/cluster/transition_test.go
- internal/controller/api/v1beta1/agent_types.go
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
- internal/controller/controllers/conditions.go
- subsystem/cluster_test.go
- subsystem/kubeapi_test.go
Removing use of Platform conditions
Add support for conditions:
SpecSynced
ReadyForInstallation
Installed
Validated
> MGMT-3879 Add ClusterDeployment Conditions

- docs/baremetal-agent-controller.md
> NO-ISSUE fix some typos

- internal/controller/controllers/agentserviceconfig_controller.go
Matching https://github.com/openshift/assisted-test-infra/pull/725
> MGMT-5274 Allow override SERVICE_BASE_URL for test-infra port-forwarding

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
An Agent is deemed to have started by checking that its status is installed, in-progress, or failed.
After installation has started, Ironic should not manage the host.
The detached annotation is removed from the BMH if BMH.spec.Image is removed.
> NO-ISSUE: Adds BMH detached annotation if Agent installation has started

- pkg/auth/rhsso_authenticator.go
For some reason it was removed and we are getting way to much
`OCM-CapabilityReview` calls (100-300 requests/sec) so it needs to be
cached.
There was a discussion with the AMS team and the conclusion was that
AccessReview and CapabilityReview can be cached simultaneously for short
periods of time (few minutes).
> MGMT-5362: Add CapabilityReview to OCM's cache.

- internal/operators/lso/ls_operator.go
- internal/operators/lso/manifest.go
> OCPBUGSM-28353 Modified LSO Subscription manifest to use default channel

- docs/set-discovery-password.md
- Verify the user generated some ISO before so we have some ignition to
modify
- Verify user performed `ocm login` correctly
- Don't fail silently on curl by using the `--fail` curl flag
- Log some of the script activity to improve debuggability
- Print an error when failing using bash trap
- Don't download the ISO, ask the user to re-generate the ISO using the
UI after the ignition was patched (Downloading the ISO did not work
anyway, and re-generating was required anyway)
> NO-ISSUE - Improve the docs example script for changing discovery ISO password

- client/events/list_events_parameters.go
- internal/cluster/cluster_test.go
- internal/controller/controllers/controller_event_wrapper.go
- internal/events/event.go
- internal/events/event_test.go
- internal/events/events_api.go
- internal/events/mock_event.go
- models/event.go
- restapi/embedded_spec.go
- restapi/operations/events/list_events_parameters.go
- restapi/operations/events/list_events_urlbuilder.go
- swagger.yaml
/event returns non-internal events
/event?categories=all returns all events
/event?categories=metrics returns metric events
> MGMT-5373 filter events by category

- internal/controller/controllers/clusterdeployments_controller.go
> NO-ISSUE Check that CD PullSecretRef is not nil

- deploy/operator/setup_assisted_operator.sh
Anything else we want to customize?
/cc @YuviGold @flaper87 
/hold
> NO-ISSUE enable providing SERVICE_BASE_URL in operator's installation

- Dockerfile.assisted-service
Reverts openshift/assisted-service#1615
> Revert "MGMT-5441 assisted-service should use oc client with ICSP support"

- dashboards/grafana-dashboard-assisted-installer-ocm-operations.configmap.yaml
- dashboards/grafana-dashboard-assisted-installer-validations.configmap.yaml
There were some typos in the legend.
> NO-ISSUE: Fixing OCM-Operations and Validations Grafana dashboard.

- deploy/operator/deploy.sh
- deploy/operator/libvirt_disks.sh
- deploy/operator/setup_lso.sh
- deploy/operator/utils.sh
Having less code on ``release`` repo is always good.
/cc @YuviGold @flaper87 
/hold
> MGMT-5419 Move disks creation code to assisted-service repo

- docs/Kube-API.md
Notify the users to create NMStateConfigs before InfraEnv
> OCPBUGSM-27596 Update KubeAPI docs for nmstate

- tools/handle_ocp_versions.py
> NO-ISSUE Set release_version when overriding ocp image

- internal/operators/cnv/cnv_operator.go
This PR changes validation ID `const` used for CNV operator host validation; the value of the `const` stays the same.
> NO-ISSUE Use correct validation ID for CNV host validation

- docs/Kube-API.md
- docs/kube-api-select-ocp-versions.md
Added documentation for: 'Hive Integration - Selecting OpenShift Versions'
> MGMT-5456 docs: hive integ - z-stream support

- cmd/main.go
- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/host/host.go
- internal/metrics/metricsManager.go
- internal/metrics/mock_metrics_manager_api.go
- Fix performance issue Bugzilla 1926329
- convert: Duration, Host stage duration, Host metrics
> MGMT-4529 convert host and cluster metrics to ELK

- internal/operators/ocs/consts.go
- internal/operators/ocs/ocs_operator.go
- internal/operators/ocs/ocs_operator_test.go
- internal/operators/ocs/validation_test.go
- internal/operators/ocs/validations.go
> NO-ISSUE: Change the memory unit from GB to GiB for OCS

- subsystem/metrics_test.go
when the configured storage is 'filesystem', a filesystem usage metrics
are reported when filesystem is modified.
The test will verify that the expected metric is collected after ISO is
generated (which writes file to disk and therefore changes the
filesystem usage) and its value is of type float and in the expected range.
The test should be skipped for non-filesystem storage, since no metrics
should be collected in that case.
> MGMT-5331 Subsystem test for filesystem usage metrics

- client/installer/get_host_requirements_parameters.go
- internal/bminventory/inventory.go
- internal/hardware/mock_validator.go
- internal/hardware/validator.go
- internal/hardware/validator_test.go
- internal/host/validator.go
- restapi/embedded_spec.go
- restapi/operations/installer/get_host_requirements_parameters.go
- swagger.yaml
From my cluster :
Minimum hardware requirements
One host is required with at least 8 CPU cores, 32.00 GiB of RAM, and 10 GB of filesystem storage.
> MGMT-5449 Provide Minimum HW requirements for SNO

- cmd/main.go
In operator deployments the assisted-service and postgres
are deployed in the same pod in separate containers. Currently,
assisted-service does not wait for the postgres to be ready
before attempting to open a connection to postgres, and often
times the first start fails causing the container to restart.
Because both are in the same pod, initContainers cannot be used
to wait for postgres to be ready before starting up
assisted-service.
Database connection retry is added to give more time for postgres
to be ready. Instead of failing the container immediately (by
logging a fatal error) when the db connection cannot be established,
it will now retry every 2 seconds for up to 10 seconds. After 10
seconds, if a connection has not been established, it will log a
fatal error.
A 10 second timeout …
> OCPBUGSM-26820 Add database connection retry

- internal/installcfg/installcfg.go
- internal/installcfg/installcfg_test.go
> MGMT-6090 - fix erroneous mirror CA is set in the master ignition

- internal/operators/ocs/ocs_operator.go
- subsystem/cluster_test.go
This PR adjusts OCS preflight requirements to be in line with changes introduced by #1456
> MGMT-4477 adjust OCS preflight requirements

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
This commit adds a watch on the ClusterDeployment resource to ensure
that we schedule a reconcile when the ClusterDeployment is installed.
Renames mapAgentToClusterDeployment to mapAgentToBMH for clarity
now that it is being used in two watches.
> MGMT-4943 Watch the ClusterDeployment resource for BMH reconcile

- internal/bminventory/inventory.go
- subsystem/cluster_test.go
- subsystem/operators_test.go
- subsystem/subsystem_suite_test.go
- subsystem/utils_test.go
- Make sure sno is reported correctly as well as
other  the default features upon cluster creations
- Capitalize the operator names
> MGMT-4134 Fixes to usage dashboard

- internal/operators/ocs/ocs_operator.go
- internal/operators/ocs/ocs_operator_test.go
> OCPBUGSM-28705: replace MiB unit to GiB when ocs host requirement fails

- internal/bminventory/inventory.go
POST and DELETE /clusters/<cluster_id>/actions/enable response returns incomplete hosts list.
> OCPBUGSM-28332 - Fix enable/disable host operations returns cluster resource with only enabled hosts list

- docs/dev/hardware-requirements.md
Documentation explaining how to override default hardware requirements.
> NO-ISSUE Add documentation for overriding hardware requirements

- dashboards/grafana-dashboard-assisted-installer-deployment-overview.configmap.yaml
> MGMT-6413 Add current deployment state dashboard

- go.sum
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
- subsystem/kubeapi_test.go
Add owner reference to ClusterDeployment on AgentClusterInstall
> MGMT-6420 add owner reference to AgentClusterInstall

- docs/enhancements/README.md
- docs/enhancements/template.md
A slimmed down version of the template one would find in https://github.com/openshift/enhancements is included and referenced.
> NO-ISSUE: Add docs/enhancements directory

- internal/host/hostcommands/install_cmd.go
Minor improvements following code review comments to PR #1672.
> MGMT-6063 Minor improvements to DHCP kernel arg

- internal/operators/cnv/cnv_operator.go
- internal/operators/cnv/config.go
- internal/operators/cnv/manifest.go
- internal/operators/cnv/manifests_test.go
There are differences in cnv subscription manifest between upstream and downstream so we need to make if configurable via environment variables.
> NO-ISSUE configure hco subscription

- docs/Kube-API.md
Adding mirror registry section to the KUBE-API.md
> MGMT-6473 - adding mirror registry documentation

- subsystem/kubeapi_test.go
Fix case of clusterAgentClusterInstallName
> NO-ISSUE fix case of AgentCluster

- deploy/operator/libvirt_disks.sh
> MGMT-5274 Check nodes disks before attach/detach script

- deploy/operator/setup_assisted_operator.sh
Following https://github.com/openshift/assisted-service/pull/1699 the
base environment variables `SERVICE_BASE_URL` and `OPENSHIFT_VERSIONS` need
to be defined as part of the ConfigMap passed to AgentServiceConfig.
/cc @osherdp  @djzager
> MGMT-5274 Setup assisted operator ConfigMap

- .gitignore
- Dockerfile.bundle
- deploy/olm-catalog/bundle.Dockerfile
- deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
- deploy/olm-catalog/metadata/annotations.yaml
- hack/generate.sh
- hack/setup_env.sh
- Update the operator-sdk binary to 1.7.2 that orders labels/annotations
https://github.com/operator-framework/operator-sdk/pull/4772
- Update hack/generate.sh to also update the bundle.Dockerfile +
annotations.yaml
- Rebuild the manifests
> NO-ISSUE: upgrade operator-sdk binary

- subsystem/kubeapi_test.go
> MGMT-6025 Enable day2 subsystem for kubeapi

- internal/host/host.go
- internal/host/transition_test.go
- models/host_stage.go
- restapi/embedded_spec.go
- swagger.yaml
Added:
- HostStageWaitingForBootkube
- HostStageWaitingForController
Removed:
- HostStageStartWaitingForControlPlane - obsolete
> MGMT-6584 Add host progress stages while waiting for control plane

- docs/kube-api-conditions.md
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
In case of Host in status pending-for-input, the Validated Condition
should be False, and te message should show the failing vaidations
> MGMT-6562 Agent CRD Validated fails on pending-for-input

- subsystem/kubeapi_test.go
This check is flaky, removing until the root cause is found
> MGMT-5255 Disable check for clearing events URL

- docs/Kube-API.md
Document what CD and ACI finalizers do upon deletion
> MGMT-6639 kubeAPI docs: CD and ACI cleanup

- go.mod
- go.sum
- pkg/ocm/client.go
The current version contains a security vulnerability.
> NO-ISSUE: Bumping ocm-sdk version.

- internal/bminventory/inventory.go
- pkg/log/context.go
Removing the free-addresses long output from the post step reply step
The message was: time="2021-03-30T16:33:41Z" level=info msg="Received step reply <free-network-addresses-76210f63> from cluster <7af19149-96ab-4fbe-b5d5-00d5330dff2d> host <396bb210-6665-4254-a044-58fd657656fb>  exit-code <0> stdout <[{\"free_addresses\":[\"192.168.124.0\",\"192.168.124.2\",\"192.168.124.3\",\"192.168.124.4\",\"192.168.124.5\",\"192.168.124.6\",\"192.168.124.7\",\"192.168.124.8\",\"192.168.124.9\",\"192.168.124.15\",\"192.168.124.16\",\"192.168.124.17\",\"192.168.124.18\",\"192.168.124.19\",\"192.168.124.20\",\"192.168.124.21\",\"192.168.124.22\",\"192.168.124.23\",\"192.168.124.24\",\"192.168.124.25\",\"192.168.124.26\",\"192.168.124.27\",\"192.168.124.28\",\"192.168.124.29\",\"192.168.124.30\",\"192.16 …
> MGMT-4823 Remove spammy logs from the service

- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/infraenv_controller.go
> NO-ISSUE Add logs on error in controllers

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
There are cases when the InfraEnv or ClusterDeployment parameters are chagned, which requires AI
to rebuild the discovery ISO. When this happens, BMAC must make sure that the BMH is properly updated
and that care is taken so that the existing image can be properly deprovisioned before the new one is
added.
This PR does that by comparing the existing ISODownloadURL value with the one set in the BMH. When they difer,
BMAC assumes that a deprovision of the existing URL must happen and the new one should be, eventually, provisioned.
Note that the AI base url doesn't change and this PR relies on the signature of the URL to change. This will only
happen when AI is running with authentication enabled. In a non-auth environment, this workflow won't work.
Signed-off-by: Flavio Percoco …
> OCPBUGSM-29476 Trigger BMH's deprovision when the ISODownloadURL changes

- .gitignore
- deploy/operator/ztp/agentClusterInstall.j2
- deploy/operator/ztp/assisted-installer-crds-playbook.yaml
- deploy/operator/ztp/baremetalHost.j2
- deploy/operator/ztp/clusterDeployment.j2
- deploy/operator/ztp/clusterImageSet.j2
- deploy/operator/ztp/deploy_spoke_cluster.sh
- deploy/operator/ztp/infraEnv.j2
Migrate code from ``openshift/release`` to assisted-service.
> Move ZTP flow code to assisted-service

- internal/cluster/statemachine.go
- internal/cluster/transition.go
- When a timeout occurs during preparing for installation, add an event indicating what happened.
> OCPBUGSM-29535 In case of timeout in preparing for installation add event

- deploy/operator/gather.sh
Adding BMH objects and infraenv data.
/cc @YuviGold 
/hold
No need to backport to ocm-2.3 branch
> migrating gathering logic to assisted-service

- CONTRIBUTING.md
- README.md
- docs/pull_request_template.md
This template will be proposed every time a new PR is created. The
author of the PR will be prompted with it and expected to fill in the
suggested sections, as needed.
None of these sections are required but they are definitely recommended
as they will make the review process easier for everyone.
More on PR templates here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests
- Should this PR be tested in a …
> NO-ISSUE Add a PULL_REQUEST_TEMPLATE for assisted-service

- subsystem/cluster_test.go
Add actual state for failures message be more detailed.
the current status and status info were appended to the message.
Before:
Cluster 70856a66-d419-4edb-9bd9-710932c1a370 wasn't in state
ready for 2 times in a row.
After:
Cluster 3a7b2123-ca14-41df-90a9-e00aa7eab496 wasn't in state
ready for 2 times in a row.
Actual insufficient (Cluster is not ready for install)
> NO-ISSUE Enhance subsystem waitForState functions

- deploy/operator/README.md
Maybe have asked for us to have this.
It will explain step-by-step how to setup the environment and run the flow.
/cc @eranco74 @flaper87 @YuviGold @tsorya 
/hold
> MGMT-6765 document how to run ZTP workflow

- internal/network/manifests_generator.go
> NO-ISSUE: Fixing typo in stage telemeter URL.

- internal/operators/ocs/ocs_operator.go
- internal/operators/ocs/validations.go
> Bug 1967842: Removed log messages from OCS cluster validation to prevent spamming of logs.

- docs/pull_request_template.md
This PR fixes spelling in the PR template used to open this PR.
/assign @flaper87 
> NO-ISSUE Fix spelling in the PR template

- docs/kube-api-conditions.md
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
- internal/controller/controllers/conditions.go
- The conditions of ACI and Agent now include validations that are "Pending" and "Error" in addition of "Failed".
- New reason "ValidationsUserPendingReason" is added to ValidatedCondition in case of "pending-for-input" state
- [] None
```
- lastTransitionTime: "2021-06-06T13:46:27Z"
message: 'The agent''s validations are pending for user: Machine Network CIDR is undefined; the Machine …
```
> Bug 1968067: KubeAPI add all none-success validations to conditions

- dashboards/grafana-dashboard-assisted-installer-deployment-overview.configmap.yaml
Add to deployment status dashboard installation status
> NO-ISSUE: Add to deployment status dashboard installation status

- docs/pull_request_template.md
Some changes impact our CI and automation environments only (configs, deployment, etc). Allow for authors to explicitly state that.
- [x ] Reviewers have been listed …
> NO-ISSUE Add CI to the list of environments for the PR template

- cmd/main.go
Currently, controllers doesn't take into account the current state
of the REST API and can be started before we've uploaded rhcos base
image, or before we've validated the pull-secret for auxiliary images
(controller, agent, installer). To this PR I added to the controllers
initialization section a blocking part that waits for the REST API
readiness before continuing.
Please, add one or …
> OCPBUGSM-29808: Wait for REST api before starting controllers

- deploy/operator/setup_hive.sh
Enable AlphaAgentInstallStrategy in hive installation on CI, to have a complete valid flow of installations.
This will affect ``e2e-metal-assisted-operator-ztp`` flow, and *does not* require any backporting effort (as CI follows master branch).
/assign @nmagnezi 
/hold
> Enable AlphaAgentInstallStrategy feature of hive in CI

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
A recent change[0] introduced a bug where inspection and cleaning were not being disabled unless the InfraEnv
URL was ready to be reconciled. This commit fixes this issue by always setting these two parameters, regardless
of the InfraEnv and BMH state.
[0] 1401e62482d1c78459ec92081d4a8211e74138ca
Please, add one or two reviewers that …
> OCPBUGSM-30084: Always disable inspection and cleaning for BMH

- docs/Kube-API.md
Doc update: add example to print ACI conditions
/assign @rollandf 
/assign @danielerez 
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTIN …
> NO-ISSUE Doc update: add example to print ACI conditions

- deploy/operator/gather.sh
Gather the Agents CRD data on the CI ZTP flow
> NO-ISSUE: ZTP flow gather agents CRDs data

- pkg/generator/generator.go
Bug 1966545:
This is an edge case that will probably not happen when using with UI.  It happens when cluster starts installing, then installation is cancelled (and possibly reset), and then starts installing again.
Since the cluster preparation for installation may be long, there is a possibility that two go-routines (one per each installation attempt) each preparing the same cluster will run in parallel.
Both of these go-routines are using the same work directory **prefix/cluster-id** for preparation artifacts and may collide with each other.
The solution for it is to let each of these go-routines to use different work directory, so they will not disturb one another.
The work dir is a temporary directory (ioutil.TempDir).
It's recommended to take a …
> OCPBUGSM-29819: Installation fails after cancel and reset of installation before node reboot

- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/common.go
- internal/cluster/installer.go
- internal/cluster/installer_test.go
- internal/cluster/transition.go
- internal/cluster/transition_test.go
/assign @RazRegev 
- [  ] Relevant issues have been associated (see [CONTRIBUTING] guide)
> MGMT-6707: Move cluster status update to central function

- internal/network/manifests_generator.go
Bug 1968634:
We believe that issue was caused by race when different services/scripts are trying
to write to resolv.conf. It caused the dns script that
sets sno dnsmasq data to resolv.conf wrote to clean resolv.conf
Provided fix can be separated to 2 parts:
1. Do all "sed" operations on /run/NetworkManager/resolv.conf and not on
etc/resolv.conf
2. Make writing new /etc/resolv.conf in atomic action (write to tmp
file and move it to /etc/resolv.conf)
- …
> OCPBUGSM-30146 - Fixing the issue with missing data in /etc/resolv.conf after reboot of SNO host

- internal/controller/controllers/bmh_agent_controller.go
* Bug 1969304: Don't queue BMH reconcile if the InfraEnv URL hasn't changed
The reconcileBMH function already verifies whether the InfraEnv URL has changed or not. The InfraEnv watcher doesn't, tho.
This commit checks whether the BMH should be reconciled based on the InfraEnv info, before queuing the request. The check is
now used by both, the watcher and the reconcileBMH function
* Bug 1969304: Apply suggestions from code review
Co-authored-by: David Zager <dzager@redhat.com>
* Bug 1969304: Resolve merge conflict issue
Co-authored-by: Flavio Percoco <flavio@redhat.com>
Co-authored-by: David Zager <dzager@redhat.com>
(cherry picked from commit d35ba1c854f4c4d43655ae2d3ee7778629501b08) …
> Bug 1969315: Don't queue BMH reconcile if the InfraEnv URL hasn't changed

- Dockerfile.assisted-service
This is the round two! Let's make all the required changes now in both, this repo and CI workflows.
Reverts openshift/assisted-service#1774
> Revert "Revert "MGMT-5430 Move assisted service image to stream8""

- docs/operator.md
Documentation now states how configuring the mirror registry
affects the discovery image's ignition config and the
install-config.yaml file used to install a cluster.
The limitation where the registries.conf mirroring must be repo
scope and not registry scope is explained.
Closes: [OCPBUGSM-30062](https://issues.redhat.com/browse/OCPBUGSM-30062)
- [] None
- Any logs, screenshots, etc that can help with the …
> Bug 1968124: Clarify "Mirror Registry Configuration" doc

- OWNERS_ALIASES
Adding @sagidayan as code-reviewer
/cc @
/cc @ …
> NO-ISSUE Adding sagidayan as a code-reviewer

- docs/baremetal-agent-controller.md
This PR is catching up with the latest changes in dev-scripts and
assisted-installer installation script.
/cc @flaper87
> NO-ISSUE: Update BMAC documentation

- docs/pull_request_template.md
Fix a PR template typo
/cc @flaper87 
/cc @rollandf  …
> NO-ISSUE: Fix a PR template typo

- README.md
Elaborate assisted-service tests categories and execution flags on README documentation
/cc @filanov 
/cc @empovit 
> NO-ISSUE: Elaborate assisted-service tests documentation

- go.mod
- go.sum
There was some special handling added to our service account in the 
cloud to deal with the recent sso changes. This new version will
ensure we don't have an outage if/when the workaround is removed.
No
Yes
The OCM SDK is only used in the cloud environment so the real test will be when this gets deployed to integration, but we don't expect any change in behavior.
Please, add one or two …
> MGMT-7074: Update OCM sdk version

- docs/operator.md
Documentation now states how configuring the mirror registry
affects the discovery image's ignition config and the
install-config.yaml file used to install a cluster.
The limitation where the registries.conf mirroring must be repo
scope and not registry scope is explained.
cherry-pick of #2021
> [ocm-2.3] Bug 1968452: Clarify "Mirror Registry Configuration" doc

- hack/setup_env.sh
- tools/deploy_assisted_installer_configmap.py
> NO-ISSUE Add skopeo to image and log image information withouit running a container

- deploy/operator/utils.sh
- deploy/operator/ztp/deploy_spoke_cluster.sh
Make sure hive have acknowledged installation and marked cluster deployment as installed.
/cc @YuviGold 
/cc @filanov 
> MGMT-7084: Validate clusterDeployment status becomes installed

- internal/ignition/ignition.go
- internal/ignition/ignition_test.go
- Change function `getUserSSHKey` from a string based to a marshaled struct based
- Function will return a stringified JSON block and an error if needed
- In `FormatDiscoveryIgnitionFile` will return an error if `getUserSSHKey` returns an error
/cc @
/cc @ …
> Bug 1968572: Assisted Service does not escape backslash characters on public SSH keys

- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
Add to `Completed` condition message the status and status info of the CVO if exists.
Example of `Completed` condition on Finalizing stage:
```
- lastProbeTime: "2021-06-27T12:43:08Z"
lastTransitionTime: "2021-06-27T12:43:08Z"
message: 'The installation is in …
```
> Bug 1968448: Add CVO progress to condition

- internal/bminventory/inventory.go
- internal/cluster/cluster_test.go
- internal/cluster/common.go
- internal/common/db.go
- internal/common/monitor_query_generator.go
- internal/host/common.go
- internal/host/host.go
- internal/host/host_test.go
- internal/host/hostutil/update_host.go
- internal/host/transition.go
> MGMT-7083: [WIP] Alternative solution for selective monitoring

- docs/hive-integration/baremetal-agent-controller.md
/cc @flaper87 
/cc @pawanpinjarkar
> NO-ISSUE: Add more troubleshooting to BMAC docs

- internal/network/manifests_generator.go
Assisted controller needs to apply manifests and gather must-gather
logs. It uses admin kubeconfig for it that is pointing to external api.
To make it work and align with BM installation we are adding this new
dns record
- [] None
/cc @eranco74 
> OCPBUGSM-31519: Adding api.<cluster-name>.<domain> entry to sno dnsmasq configuration

- docs/hive-integration/baremetal-agent-controller.md
> NO-ISSUE: Fixed a broken link

- docs/enhancements/installation-progress-bar.md
> MGMT-6908: Adding enhancement for installation-progress-bar.

- subsystem/image_test.go
Moves the test for generating and downloading the assisted service live iso out of the per-image-type loop.
This test doesn't change based on image type so we shouldn't run it twice.
/cc @YuviGold 
> NO-ISSUE: Move live iso test out of image type loop

- docs/hive-integration/baremetal-agent-controller.md
> Bug 1978744: Add docs explaining automatedCleaningMode overrides

- Makefile
- subsystem/metrics_test.go
This is needed to show some information like 'By' outputs etc.
It was originally removed because one of its side effects was to always
spill the content of GinkgoWriter although, originally, it should spill
the content only if a test failed.
Anyway those subsystem tests using the GinkgoWriter will be remove in
MGMT-7122, therefore, there is no harm in removing the writer at this
point.
/cc @
/cc @
> MGMT-7152: Adding verbose printing for ginkgo.

- Makefile
- docs/hive-integration/README.md
- internal/controller/controllers/agentserviceconfig_controller.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
- subsystem/kubeapi_test.go
Enable Day 2 cluster in kube api
/cc @nmagnezi 
/cc @filanov 
> NO-ISSUE: Enable Day 2 cluster in kube api

- subsystem/kubeapi_test.go
The `deployAgentClusterInstallCRD` function included an instruction to create a
ClusterImageSet resource, which caused some workarounds in the tests,
especially when a second ACI needs to be created.
This change decouples the creation of the above-mentioned resources:
1. deployAgentClusterInstallCRD function will now only create an ACI resource.
2. ClusterImageSet gets created on test setup - `BeforeEach`.
/cc @rollandf 
/cc @filanov 
> NO-ISSUE: kubeAPI subsystem tests: decouple ACI and ClusterImageSet Creation

- Dockerfile.bundle
- Dockerfile.test
- config/crd/bases/agent-install.openshift.io_agents.yaml
- config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
- config/crd/bases/agent-install.openshift.io_infraenvs.yaml
- config/crd/bases/agent-install.openshift.io_nmstateconfigs.yaml
- config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
- hack/setup_env.sh
Updating the go modules could cause breakages. We would like to avoid it.
```
/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:705:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:724:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:742:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:763:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:782:11: invalid operation: loggr != nil (mismatched types logr.Logger and nil)
/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:783:3: undefined: logr.WithCallDepth …
```
> NO-ISSUE: Remove -u flag from go get commands to use fixed versions

- subsystem/image_test.go
Investigation so far points toward this being a CI infrastructure
problem. Mark these as pending until we get a better answer to
avoid the failures.
/cc @YuviGold 
> MGMT-7054: Mark iso download tests as pending

- internal/installcfg/installcfg.go
Support vsphere platform on assisted service https://issues.redhat.com/browse/MGMT-7067
> MGMT-7121: Add vsphere platform support to install-config.yaml

- hack/generate.sh
- hack/setup_env.sh
Spectral seems to have removed all the linux release binaries
which is causing all our tests to fail trying to build the build
container.
This temporarily stops trying to install spectral which should work
around the problem.
/cc @YuviGold 
/cc @oshercc 
> NO-ISSUE: Don't lint swagger for now to make tests green

- api/hiveextension/v1beta1/agentclusterinstall_types.go
- api/hiveextension/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
- internal/controller/controllers/clusterdeployments_controller.go
Add Machine net CIDR to ACI status.
/cc @filanov 
/cc @rollandf 
> OCPBUGSM-31691: Add Machine net CIDR to ACI status

- Dockerfile.bundle
- Dockerfile.test
- config/crd/bases/agent-install.openshift.io_agents.yaml
- config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
- config/crd/bases/agent-install.openshift.io_infraenvs.yaml
- config/crd/bases/agent-install.openshift.io_nmstateconfigs.yaml
- config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
- hack/generate.sh
- hack/setup_env.sh
1. If specral linter can not be run from the repository directly run it inside a container from the latest image
Originally submitted by djzager
2. Remove -u flag from go get commands to use fixed versions. Originally submitted by YuviGold
3. Fix CRDs description. Originally submitted by YuviGold
/cc @YuviGold 
/cc @djzager 
> NO-ISSUE: Fix CI issues

- .github/dependabot.yml
[dependabot](https://dependabot.com/) creates automatically PRs for bumping dependencies.
/cc @osherdp 
/cc @flaper87 
> NO-ISSUE: Add dependabot.yml file

- internal/cluster/cluster.go
- internal/host/transition_test.go
- internal/host/validator.go
- internal/network/utils.go
[MGMT-7195](https://issues.redhat.com/browse/MGMT-7195): Add calculation of L3 majority groups to cluster monitor
- In addition to L3 connectivity groups calculate L3 connectivity groups both for IPv4 and IPv6.
[MGMT-7208](https://issues.redhat.com/browse/MGMT-7208): Modify belongs-to-majority-group validation to check L3 connectivity for none Platform
- Instead of always returning success for none platform, use L3 majority groups to evaluae the validation
belongs-to-majority-group
/cc @empovit 
> Multiple issues: MGMT-7195, MGMT-7208

- api/hiveextension/v1beta1/agentclusterinstall_types.go
- config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
Add `AgentClusterInstall` shortName  --> aci
/cc @filanov 
/cc @rollandf 
> MGMT-7228: Add AgentClusterInstall shortName aci

- docs/operator.md
Added namespace to the `oc rollout` command
/cc @
/cc @
> NO-ISSUE: Update document

- subsystem/host_test.go
- Set progress_stage_updated_at to current time in installation in progress status to verify
that host will not move into error by monitor during test.
/cc @YuviGold 
> MGMT-7154: Flaky test: Host tests next step - DHCP

- pkg/s3wrapper/util.go
Commit ea07b14e fixed an issue introduced in commit ebe50b8c but the
earlier commit is not in this branch. For our cloud deployments,
those versions are being maintained elsewhere and need to be updated.
This PR will force the updates made in our deployment scripts to take
effect when this new image is deployed. Without this change we would not
upload a new version of the minimal template image even if we update the
openshift versions map in prod.
Original PR: https://github.com/openshift/assisted-service/pull/2189
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1980753
/cc @gamli75  …
> NO-ISSUE: Force minimal iso template update

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster_test.go
- internal/cluster/refresh_status_preprocessor.go
- internal/cluster/statemachine.go
- internal/cluster/transition_test.go
- internal/cluster/validation_id.go
- internal/cluster/validator.go
- internal/installcfg/installcfg.go
- internal/installcfg/installcfg_test.go
- internal/operators/ocs/validation_test.go
- models/cluster.go
- models/cluster_create_params.go
- models/cluster_update_params.go
- models/cluster_validation_id.go
- restapi/embedded_spec.go
- subsystem/ipv6_test.go
- swagger.yaml
give the user the option to choose a network type out of the options of OVS and SDN with the limitation on ipv6 has to use OVN.
/cc @avishayt
> MGMT-6768: Allow users to choose between SDN or OVN network types

- internal/cluster/transition.go
> MGMT-7288 Add degraded cluster event for failed OLM operators

- internal/ignition/ignition.go
- internal/ignition/ignition_test.go
In order to identify BMH file as master, the name was expected to contain "-master-" .  This changed
Now the name contains the hostname.  In order to identify master correctly, a match is done by
getting hostnames for masters and workers and matching them to the name in the BMH file.
If no match is found, then the previous logic (search for "-master-") is applied.
/cc @filanov 
/cc @flaper87 
> OCPBUGSM-31996: Preparing for Installation failed with message: Failed to prepare the installation due to an unexpected error. Please retry later

- internal/host/common_test.go
- internal/host/host.go
- internal/host/host_test.go
- internal/host/validator.go
- internal/metrics/metricsManager.go
- internal/metrics/mock_metrics_manager_api.go
- subsystem/cluster_test.go
- subsystem/day2_cluster_test.go
- subsystem/ipv6_test.go
- subsystem/kubeapi_test.go
- subsystem/metrics_test.go
- subsystem/utils_test.go
~~**This PR contains the commit from #2098**~~
Defines 2 new prometheus metrics of type histogram for capturing host network latency and packet loss between hosts:
Network latency:
```
metric basename: assisted_installer_host_network_latency_in_ms
labels: clusterVersion,sourceRole,targetRole
```
Packet loss:
```
metric basename: assisted_installer_packet_loss_percentage
labels: clusterVersion,sourceRole,targetRole
```
For more information about histograms, head to the [prometheus documentation](https://prometheus.io/docs/concepts/metric_types/#histogram) website.
/cc @
/cc @ …
> MGMT-7085: Add metrics network latency packet loss

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
"AND" was always concatenated to the where condition regardless if
there's a user or not (i.e. when the operation was made by an admin).
The proper way to implement concatenating strings with a delimiter is
using `strings.Join`.
/cc @filanov 
/cc @gamli75 
/cc @ybettan 
> OCPBUGSM-32244: Bugfix ListClusters for admin role

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/mock_installer_internal.go
- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/mock_cluster_api.go
> MGMT-7219: Add internal API to transform a cluster from day1 to day2

- deploy/s3/pvc.yaml
In CI we're seeing a large number of failures reporting "no space left on device" while trying to upload to s3.
Hopefully this will reduce the "no space left on device" failures
while we figure out why we're using so much space.
/cc @YuviGold 
/cc @filanov 
> MGMT-7343: Increase s3 pod volume size

- internal/controller/controllers/clusterdeployments_controller.go
Remove unused params from cd controller functions.
/cc @
/cc @
> NO-ISSUE: remove unused params from cd controller functions

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
With this change, the assisted-service backend will generate
an event for cluster log collection only for the very first time
that event took place.
The assisted-installer ctrl pod will currently upload cluster
logs every five minutes, so this change aims to avoid spamming
the events log.
/cc @
/cc @
> MGMT-7374: Issue a single cluster log collection event

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
To be able to get ignition from the MCS on from spoke cluster, we must have a certificate of the MCS and connect to tls port of MCS.  To increase the capacity of the spoke cluster on day2, while adding remote worker nodes to the spoke cluster, we need to pull the MCS certificate from the spoke cluster and inject it as part of the ignition config
before the node boots so that there is no failure due to Certificate signed by Unknown Authority
Ref: https://access.redhat.com/solutions/4799921
Ref: https://issues.redhat.com/browse/MGMT-4561
- [] None
/cc @
/cc @ …
> MGMT-4561 Add MCS certificate to worker's pointer ignition on installation start

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- models/cluster_create_params.go
- restapi/embedded_spec.go
- swagger.yaml
Currently for creating a vsphere cluster we have to call 2 APIs:
registerCluster and then updateCluster to set the platform
Now we can create a vsphere cluster with a single API call
Relevant for the test-infra and where the user comes from the UI vSphere section rather than Bare Metal.
/cc @
/cc @
> MGMT-7389: Create cluster with a platform

- cmd/main.go
- internal/host/hostcommands/container_image_availability_cmd.go
- internal/host/hostcommands/container_image_availability_cmd_test.go
- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
- internal/host/hostcommands/instruction_manager_test.go
- internal/versions/mock_versions.go
- internal/versions/versions.go
- internal/versions/versions_test.go
- Required for support in olm operators must-gather reports
- Kube-api support will be delivered in a spearate commit
- backward compatible with old controllers
/cc @empovit 
/cc @filanov 
> MGMT-4893: Add Must Gather Image map

- deploy/operator/ztp/deploy_spoke_cluster.sh
"joined agents" is ambiguous, it is not clear if it refers to agents who
have been discovered or installed and joined the cluster.
/cc @
/cc @
> NO-ISSUE: Making agent discovered message more informative.

- config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
- deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
- docs/operator.md
- internal/controller/controllers/agentserviceconfig_controller.go
- Add default values to agentserviceconfig in the samples directory
- Add documentation to the new Spec field (mustGatherImages)
- Add documentation to the code
see the main implementation in  https://github.com/openshift/assisted-service/pull/2338
- Add default values to agentserviceconfig in the samples directory
- Add documentation to the new Spec field (mustGatherImages)
- Add documentation to the code
see the main implementation in  https://github.com/openshift/assisted-service/pull/2338
/assign @djzager 
/assign @flaper87 
> MGMT-4893: Add default values and doc to MUST_GATHER_IMAGES in kube-api

- cmd/main.go
- internal/cluster/cluster.go
- internal/cluster/common.go
- internal/cluster/statemachine.go
- internal/cluster/transition.go
- internal/cluster/transition_test.go
MGMT-5444: Set 24 hours timeout for installation to complete
The installation might hang while the assisted service wait for user action
e.g. host with wrong boot order or a host that didn't return after reboot.
Since some certificates generated by the installer are valid for 24 hours
it's unlikely for the installation to complete successfully once 24 hours pass.
In order to avoid debugging strange installation failures due to TLS
certificates expiration, this code adds a global timeout of 24 hours for the installation.
This timeout is calculated according to the `cluster.InstallStartedAt`
which get updated in PostPrepareForInstallation
- Is this PR relying on CI for an e2e test run? yes, for regression 
- Should this PR be tested in a …
> MGMT-5444: Set 24 hours timeout for installation to complete

- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
This info will be needed by the assisted-installer and assisted-installer controller
for updating host progress and downloading host ignition
/cc @
/cc @
> MGMT-7437: Add infra-env-id to the install command per host

- internal/bminventory/inventory.go
log line is relevant to all the logs and not only for host, so in case of controller logs we will get null
/cc @tsorya 
> NO-ISSUE: Remove host ID from upload logs log

- docs/enhancements/arm64-cpu-architecture.md
An enhancement proposal for 'ARM64 CPU architecture support':
In order to support additional platforms, the assisted-service
should accept and handle selection of other platforms.
The focus of this enhancement is specifically arm64, but the introduced
infrastructure should facilitate future support of more platforms (e.g. PPC).
> MGMT-7309: enhancement proposal for ARM64 CPU architecture support

- internal/cluster/cluster.go
- internal/operators/api/api.go
- internal/operators/api/mock_operator_api.go
- internal/operators/cnv/cnv_operator.go
- internal/operators/cnv/manifest.go
- internal/operators/cnv/manifests_test.go
- internal/operators/lso/ls_operator.go
- internal/operators/lso/manifest.go
- internal/operators/lso/manifests_test.go
- internal/operators/manager.go
- internal/operators/manager_test.go
- internal/operators/ocs/manifest.go
- internal/operators/ocs/manifests_test.go
- internal/operators/ocs/ocs_operator.go
- restapi/embedded_spec.go
- restapi/operations/installer/download_cluster_files_parameters.go
- swagger.yaml
This PR change the custom_manifest.yaml file to custom_manifest.json
file. The JSON file contains the manifest of each OLM operator as
separate field in the JSON array. With such we can apply the specific
manifest as needed in the assisted-installer side.
The `custom_manifests.json` file example:
```json
[{"Name":"lso","Content":"YXBpVmVyc2lvbjogImxvY2FsLnN0b3JhZ2Uub3BlbnNoaWZ0LmlvL3YxYWxwaGExIgpraW5kOiAiTG9jYWxWb2x1bWVTZXQiCm1ldGFkYXRhOgogIG5hbWU6ICJsb2NhbC1kaXNrcyIKICBuYW1lc3BhY2U6ICJvcGVuc2hpZnQtbG9jYWwtc3RvcmFnZSIKc3BlYzoKICBzdG9yYWdlQ2xhc3NOYW1lOiAibG9jYWxibG9jay1zYyIKICB2b2x1bWVNb2RlOiBCbG9jawogIGRldmljZUluY2x1c2lvblNwZWM6CiAgICBkZXZpY2VUeXBlczoKICAgICAgLSAiZGlzayI="}, {"Name": "cnv", "Content": "YXBpVmVyc2lvbjogImxvY2FsLnN0b3JhZ2Uub3BlbnNoaWZ0LmlvL3YxYWxwaGExIgpraW5kOiAiTG9jYWxWb2x1 …
```
> MGMT-7292: Split custom manifest in custom_manifest file

- api/v1beta1/agent_types.go
- config/crd/bases/agent-install.openshift.io_agents.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/mock_crd_utils.go
- internal/controller/controllers/crd_utils.go
- internal/controller/controllers/crd_utils_test.go
In case the InfranEnv is not associated to a Cluster, the Agent CR
should be created without a reference to a ClusterDeployment.
Also, make the ClusterDeployment reference in Agent CR optional.
/cc @filanov 
/cc @nmagnezi 
> MGMT-7472: Create Agent CR without Cluster

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
This PR changes the UpdateInfraEnv method to update also Ignition, so
the ISO is generated after the call.
- [ X] Bug fix
/cc @rollandf 
> MGMT-7520: Update ignition as part of infraEnv update

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
The ProviderSpec and BareMetalHost annotation are required for the machine-controller to reconcile the Machine. If they are not provided, the Machine does not reconcile, and the Machine status is unavailable.
The Machine status is required for Discovery CSR auto-approval. The status contains the machine address which is used to match with the Node name during CSR approval.
This patch is built on top of the original patch suggested by Richard here https://github.com/openshift/assisted-service/pull/2143
This patch retrieves checksum and URL values from the ProviderSpec object of a master machine from the day 2 spoke cluster and sets the values when creating a spoke machine for a worker on day2 spoke cluster. 
All the master machines use the same value so it is safe to set the same value in …
> OCPBUGSM-31544: Spoke worker BMH does not join cluster because CSR was not auto approved

- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
- internal/host/hostcommands/instruction_manager.go
Cleanup old obsolete code
This parameter isn't used and will not be supported once https://github.com/openshift/assisted-installer/pull/341 merges
- Is this PR relying on CI for an e2e test run? For regression
-->
/cc @YuviGold 
/cc @tsorya 
> NO-ISSUE: Removed obsolete installation-timeout from the install command

- go.sum
- internal/host/host.go
- internal/host/host_test.go
- subsystem/day2_cluster_test.go
Workers will not reboot till 2 masters will not join that's why we need
new status that will show that workers are waiting for it
/cc @
/cc @
> MGMT-7178: Adding new worker status, waiting-for-control-plane

- dev-requirements.txt
- hack/setup_env.sh
- tools/ocp_version_update/Jenkinsfile.default_release_update
- tools/ocp_version_update/update_default_release_versions_to_latest.py
- tools/update_default_release_versions_to_latest.py
Jenkins will keep the OCP versions up to date with the relevant scripts already located int this repo
-->
/cc @YuviGold 
> Move the ocp version script from assisted-installer-deployment to this repo

- client/installer/download_infra_env_discovery_image_headers_responses.go
- client/installer/download_infra_env_discovery_image_responses.go
- client/installer/installer_client.go
- restapi/embedded_spec.go
- restapi/operations/assisted_install_api.go
- restapi/operations/installer/download_infra_env_discovery_image.go
- restapi/operations/installer/download_infra_env_discovery_image_headers.go
- restapi/operations/installer/download_infra_env_discovery_image_headers_urlbuilder.go
- restapi/operations/installer/download_infra_env_discovery_image_urlbuilder.go
- swagger.yaml
Currently this API i already implemented under url:
/v2/infra-envs/{infra_env_id}/image
This PR moves it to:
/v2/infra-envs/{infra_env_id}/downloads/image
/cc @
/cc @
> MGMT-7509: Implement V2 infra env download image API

- internal/host/transition.go
> NO-ISSUE: clearing logs timestamp when node re-register

- internal/network/machine_network_cidr.go
This PR extends the validator checking whether the host belongs to the
machineNetwork so that instead of a single entry, the host is compared
against all the networks specified as Machine Networks.
Contributes-to: [MGMT-6670](https://issues.redhat.com/browse/MGMT-6670)
/cc @
/cc @
> MGMT-6670: Extend validator for host in machineNetwork

- deploy/operator/README.md
Update readme file
/cc @
/cc @
> NO-ISSUE: Update ztp readme file

- README.md
- docs/user-guide/README.md
Create a direct link to user guide in the main readme
/cc @lranjbar 
/cc @flaper87 
> NO-ISSUE: Create a direct link to user guide in the main readme

- skipper.yaml
Mount k3d binary in skipper conf
/cc @osherdp 
/cc @eranco74 
> NO-ISSUE: Mount k3d binary in skipper conf

- OWNERS_ALIASES
> MGMT-7597: Remove ronniel1, razregev, and sacharya from OWNERS

- internal/common/events/events.go
- internal/controller/controllers/controller_event_wrapper.go
- internal/events/event.go
- internal/events/mock_event.go
- tools/generate_events.py
Replace the type of the generated `clusterID\hostID` from `*strfmt.UUID` to `strfmt.UUID` for safety reasons.
This PR continues #2412
/cc @mhrivnak 
/cc @masayag 
> MGMT-7588: Replace the type of the generated clusterID and hostID

- tools/ocp_version_update/update_default_release_versions_to_latest.py
Remove updating ocp version PR to app-interface since it is no longer relevant
+ make adjustments to the script to work with a older git version 
/cc @gamli75 
> NO-ISSUE: OCP update only to github

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- Change the download URL in InfraEnv to contain V2 URL instead of V1 URL.
> MGMT-7620: Change download URL in InfraEnv to contain V2 URL

- internal/bminventory/inventory.go
- internal/cluster/auth.go
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/gencrypto/token.go
- internal/gencrypto/token_test.go
- pkg/auth/local_authenticator.go
- pkg/auth/local_authenticator_test.go
- subsystem/kubeapi_test.go
Migrate local auth to use InfraEnv:
Add the possibility to create JWT token for local auth with claim id with infraenv or cluster id
The option for cluster id is needed for kube API AgentClusterInstall event and logs URL, as AgentClusterInstall does not have a direct link to InfraEnv
/cc @filanov 
> MGMT-7529 Migrate local auth to use InfraEnv

- internal/host/host.go
- internal/host/host_test.go
- The cluster is used to determine disks eligibility and set the information into the inventory.
This will be done only if host is bound.
> MGMT-7649: Update inventory should not try to get cluster if host is unbound

- internal/controller/controllers/controller_event_wrapper.go
- internal/controller/controllers/controller_event_wrapper_test.go
In case that an event is sent with InfraEnv ID and Host ID and
the host is bind to a Cluster, notify a cluster event to the controllers.
/cc @filanov 
/cc @masayag 
> MGMT-7648: Notification on event for binded Host

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
Update StaticNetwork in infraEnv update
/cc @filanov 
/cc @nmagnezi 
> MGMT-7675: Update StaticNetwork in infraEnv update

- internal/cluster/common.go
- internal/host/common.go
- internal/host/hostutil/test_utils.go
- internal/host/transition.go
- internal/host/transition_test.go
Updated the timeout
Added UT for SNO and multi node cluster
Update the wording and added the installation disk to the status info (MGMT-7641)
- Is this PR relying on CI for an e2e test run? yes for regression
-->
/cc @tsorya 
/cc @lalon4 
> Bug 1996531: Reduce singleNodeRebootTimeout from 120 minutes to 80 minutes

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/versions/mock_versions.go
- internal/versions/versions.go
- internal/versions/versions_test.go
In case that the Openshift version is not provided when creating an
InfraEnv, auto select the latest version.
This is needed for Kube API where OpenShift version is not available in
InfraEnv CRD.
/cc @filanov 
> MGMT-7642: Select latest version in InfraEnv create

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- Return the inner error when calling GenerateIso
- Return updated InfraEnv after calling updateInfraEnv
/cc @filanov 
> MGMT-7650: Align GenerateIso error handling

- internal/cluster/common.go
- internal/cluster/common_test.go
The former transaction solution introduced on
https://github.com/openshift/assisted-service/pull/2468
created a deadlock when using multiple transactions concurrently.
A better solution would be to delete and update the machine network cidr
only in case necessary.
For that, we check that the new machine cidr is different from the old
one. Only in that case, we first update the value and then remove the
old one. This way, we won't end up with a gap of an empty value during
the update.
/cc @filanov 
> MGMT-4321: Bugfix flaky auto assign machine cidr deadlock

- Dockerfile.assisted-service
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/ignition/dummy.go
- internal/ignition/ignition.go
- internal/ignition/mock_ignition.go
- internal/installercache/installercache.go
- internal/oc/mock_release.go
- internal/oc/release.go
- internal/oc/release_test.go
- models/platform_type.go
- pkg/generator/generator.go
- restapi/embedded_spec.go
- swagger.yaml
- Added support in Release to extract according to platform type:
- Extract openshift-install binary for none platform.
- Otherwise, extract openshift-baremetal-install.
- For now, non default CPU architectures (x86_64) are supported only with User Managed Networking.
- Added none to platform_type to swagger.
- None value is used only for non x86_64 architectures (i.e. not used by SNO for now)
The change was tested with a 4.9 release image for arm64 (not yet supported), so no real effect on behaviour, just a preparation for supporting arm64.
/cc @eranco74 
/cc @filanov  …
> MGMT-7549: extract openshift-install for none platform

- subsystem/cluster_test.go
- subsystem/infra_env_test.go
- subsystem/utils_test.go
Adds subsystems test for infra-env scenarious. The tests are only for infra-env CRUDs APIs.
Tests for infra-env + host, infra-env + host + cluster scenarious will be added in
a different PRs
/cc @
/cc @
> MGMT-7692: add subsystem test for infra env V2 scenarios

- models/infra_env_update_params.go
- restapi/embedded_spec.go
- swagger.yaml
For now we are not going to allow to change CLusterID of the InfraEnv
once it was created. Otherwise we will need to deal with moving already registered
host to a cluster
/cc @
/cc @
> MGMT-7695:  remove a ClusterID option from InfraEnvUpdateParams

- api/v1beta1/infraenv_types.go
- cmd/main.go
- config/crd/bases/agent-install.openshift.io_infraenvs.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/mock_installer_internal.go
- internal/common/db.go
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
- internal/controller/controllers/common.go
- internal/controller/controllers/infraenv_controller.go
- internal/controller/controllers/infraenv_controller_test.go
- subsystem/cluster_test.go
- subsystem/kubeapi_test.go
- subsystem/utils_test.go
InfraEnv controller uses V2 API to update InfraEnv in backend
/cc @filanov 
/cc @nmagnezi 
> MGMT-7234: InfraEnv Controller migrate to v2

- internal/versions/versions.go
- internal/versions/versions_test.go
> MGMT-7642: Use GetOpenshiftVersion in GetLatestVersion

- Makefile
- tools/wait_for_assisted_service.py
Remove manual sleep in Makefile & Extend sleep interval when waiting to the service
/cc @filanov 
/cc @osherdp 
> NO-ISSUE: Remove manual sleep in Makefile & Extend sleep interval when waiting to the service

- Dockerfile.assisted-service
> Update swagger-codgen-cli to its latest version

- internal/controller/controllers/bmh_agent_controller.go
> MGMT-7690: BMAC agent reference to CD is optional

- internal/operators/manager.go
- internal/operators/manager_test.go
- restapi/embedded_spec.go
- restapi/operations/installer/download_cluster_files_parameters.go
- swagger.yaml
This reverts commit 06e852cac188b7d5753f823f584caa85b1046207.
/cc @YuviGold 
/cc @
> MGMT-7292: Revert Add custom_manifest.yaml to not break tests

- docs/user-guide/README.md
- docs/user-guide/network-configuration.md
This PR creates a initial documentation explaining different options of
network configuration available when deploying an OCP cluster using
Assisted Service.
/cc @flaper87 
/cc @lranjbar 
/cc @djzager 
/cc @kwozyman 
> NO-ISSUE: Create initial docs about network configuration

- docs/cloud.md
Update cloud.md how to get JTW_TOKEN without ocm client
/cc @rollandf 
/cc @
> Update cloud.md how to get JWT_TOKEN without ocm client

- tools/ocp_version_update/update_default_release_versions_to_latest.py
- In order to ensure correlation between the default versions jsons, update also default_os_images.json and default_release_images.json.
- As release and rhcos fields are optional in default_ocp_versions.json, update them only if available.
I.e. these fields are just a fallback in case that os/release images files are missing.
Tested using a 'dry-run', still need to test the full flow in jenkins. 
/cc @oshercc 
/cc @gamli75 
/cc @filanov 
> MGMT-7568: ocp_version_update - support os/release images

- data/events.yaml
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/common/events/events.go
- internal/controller/controllers/controller_event_wrapper.go
- internal/controller/controllers/controller_event_wrapper_test.go
- internal/events/event.go
- internal/events/mock_event.go
- tools/generate_events.py
Host events properties requirements support infraEnv resources as follows:
- `InfraEnvID` is a mandatory property
- `ClusterID` is an optional property.
Support InfraEnv events:
- Add InfraEnv Event Type, for events related to infraEnv only.
`SendInfraEnvEvent` will be used for creating events that refer to the InfraEnv resource.
Within this PR, the value of the `InfraEnvID` will be stored as the `cluster-ID`.
This will be changed in future PRs in which we'll extend the events table to store also the `infraenv_id`
Up next:
- InfraEnv events API, model, and DB updates will be updated in future PRs.
/cc @masayag 
/cc @YuviGold 
/cc @filanov 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/gui …
> MGMT-4872: Update events requirements

- internal/hardware/mock_validator.go
- internal/hardware/validator.go
- internal/hardware/validator_test.go
- internal/host/host.go
- internal/host/host_test.go
- internal/host/monitor_test.go
- internal/host/transition_test.go
- internal/host/validator.go
- subsystem/host_v2_test.go
Upon any update of the inventory, disk eligibility is determined
by checking it size againt the OCP cluster and operators requirements
When updating inventory for infra-env host, its isze should be checked
against the smallest OCP cluster requirement (worker or master)
/cc @
/cc @
> MGMT-7704: Fix disk validation for infra-env host

- internal/bminventory/inventory.go
> NO-ISSUE: Trigger VIP reallocation only when the primary machine CIDR changes

- internal/controller/controllers/clusterdeployments_controller.go
Since that the ISO creation has been separated in the backend, no need
to update the InfraEnv controller from the ClusterDeployment controller
when the pull secret is updated or when the cluster is created.
/cc @nmagnezi 
/cc @filanov 
> MGMT-7724: Remove notification CD to InfraEnv

- internal/bminventory/inventory.go
> NO-ISSUE: Fix typo in log

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
This commit adds a backwards compatibility for setting network
configuration using the following structures
* MachineNetworkCidr
* ClusterNetworkCidr
* ClusterNetworkHostPrefix
* ServiceNetworkCidr
This works in a way that whenever the old data structure is received by
the service, the respective values in both old and new structures are
set internally.
In case when service receives both old and new data structure in the
same request, the old data structure will take precedence.
Follows-up: #2455
Contributes-to: [MGMT-7498](https://issues.redhat.com/browse/MGMT-7498)
Contributes-to: Bug 1999752
+++++++++++++++++++++++++++++
+++ TEST SERVICE NETWORKS +++
+++++++++++++++++++++++++++++
```
$ curl http://chocobomb:6008/api/assisted-install/v1/clusters/82b8c284-8024-4a30-9bef-4b5a8180061b …
```
> MGMT-7498: Add missing backwards compatibility for network configuration

- internal/controller/controllers/crd_utils.go
> MGMT-7472: Fix log to print infraenv ID

- internal/common/test_configuration.go
- internal/host/refresh_status_preprocessor.go
- internal/host/statemachine.go
- internal/host/validation_id.go
- internal/host/validations_test.go
- internal/host/validator.go
- models/host_validation_id.go
- models/inventory.go
- restapi/embedded_spec.go
- subsystem/cluster_test.go
- swagger.yaml
We need to make use all the hosts respect the minimal requirements for
disk-encryption in order to notify the user in case they doesn't before
the installation start, and eventually fail.
/cc @
/cc @
> MGMT-7457: Adding validations for disk-encryption.

- internal/controller/controllers/bmh_agent_controller_test.go
Related to #2510 
/cc @filanov 
/cc @flaper87 
/cc @nmagnezi 
> MGMT-7725: BMAC add test for agent without cluster

- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
Support unbound status in Agent conditions
/cc @filanov 
/cc @nmagnezi 
> MGMT-7686: Support unbound status in conditions

- internal/operators/cnv/cnv_operator.go
- internal/operators/cnv/cnv_operator_test.go
We returned only master requirements for SNO. With this PR we sum both master and worker memory and cpu requirements.
/cc @jakub-dzon 
/cc @YuviGold 
> Bug 1979950: Fix minimal requirements for cnv

- internal/bminventory/inventory.go
- internal/bminventory/mock_installer_internal.go
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
- subsystem/kubeapi_test.go
> MGMT-7090: Bind and Unbind Agent

- api/v1beta1/agentserviceconfig_types.go
- config/manager/manager.yaml
- config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
- internal/controller/controllers/agentserviceconfig_controller.go
- internal/controller/controllers/agentserviceconfig_controller_test.go
- internal/controller/controllers/images.go
- restapi/embedded_spec.go
- swagger.yaml
Update the agentserviceconfig controller to deploy the
assisted-image-service. Include the assisted-image-service image
references in the operator manifests.
/cc @
/cc @
> MGMT-7253: Add assisted-image-service to AgentServiceconfig

- api/v1beta1/agent_types.go
- docs/hive-integration/kube-api-conditions.md
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
- subsystem/kubeapi_test.go
Add Bound condition to Agent CRD
/cc @nmagnezi 
/cc @filanov 
/cc @avishayt 
> MGMT-7730: Add Bound condition to Agent CRD

- tools/ocp_version_update/update_default_release_versions_to_latest.py
Pre-release OCP 4.9 has been recently added to default_ocp_versions.json.
As the pre-release rhcos images are now available only in a dedicated folder[1],
added support to include pre-releases if no stable yet.
[1] https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/
Tested script manually in jenkins job.
/cc @oshercc 
/cc @gamli75 
/cc @YuviGold 
/cc @filanov 
> MGMT-7643: support pre-releases in update_versions

- internal/bminventory/inventory.go
- subsystem/authz_test.go
When authtype is RHSSO don't allow admins to download cluster sensitive files.
Using same logic as in endpoint `GET /v1/clusters/{cluster_id}/downloads/files`
related to:
- [MGMT-7475](https://issues.redhat.com/browse/MGMT-7475)
- [MGMT-7564](https://issues.redhat.com/browse/MGMT-7564)
- [MGMT-7699](https://issues.redhat.com/browse/MGMT-7699)
/cc @carbonin
/cc @osherdp
> Bug 2001029: presigned files access

- Dockerfile.assisted-service-build
- Jenkinsfile
- Makefile
- hack/generate.sh
- hack/setup_env.sh
- hack/update_local_image.sh
- hack/utils.sh
- skipper.yaml
[MGMT-7639](https://issues.redhat.com/browse/MGMT-7639): Support using podman in the deploy-test make target
1. Upgrade our build image form Centos7  to quay.io/centos/centos:stream8 which is relatively new centos because the old image has a very old podman which lack a lot of features
2. Support podman in the make file
3. Run podman-remote from the skipper container by sharing the socket (you have to enable the socket first)
To enable the socket use "systemctl --user enable --now podman.socket" and "sudo loginctl enable-linger $USER"
See: https://github.com/containers/podman/blob/main/docs/tutorials/remote_client.md for details
/cc @YuviGold 
/cc @ybettan 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-m …
> MGMT-7639: Support using podman in the assisted-service

- internal/cluster/cluster.go
- internal/cluster/progress_test.go
- subsystem/cluster_test.go
- subsystem/day2_cluster_test.go
When a host reports its installation progress, we also update the cluster's
progress accordingly but this update should be skipped for day2 clusters
as their progress doesn't mean anything.
/cc @
/cc @
> NO-ISSUE: Skip cluster progress update on day2 clusters.

- Dockerfile.assisted-service-build
- Jenkinsfile
- Makefile
- hack/generate.sh
- hack/setup_env.sh
- hack/update_local_image.sh
- hack/utils.sh
- skipper.yaml
- tools/utils.py
1. Upgrade our build image form Centos7 to quay.io/podman/stable:latest which is relatively new fedora with podman installed on it because the old image has a very old podman which lack a lot of features
2. Support podman in the make file
3. Run podman-remote from the skipper container by sharing the socket (you have to enable the socket first)
To enable the socket use "systemctl --user enable --now podman.socket" and "sudo loginctl enable-linger $USER"
See: https://github.com/containers/podman/blob/main/docs/tutorials/remote_client.md for details
4. Fixing make publish issue
/cc @
/cc @ …
> MGMT-7639: Support using podman in the deploy-test make target (#2451)

- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
- subsystem/kubeapi_test.go
Before this patch, if the referenced ClusterDeployment in Agent was not found in DB or kubernetes, the Agent CR was deleted.
With this patch:
- In case that the referenced cluster is not found in DB, update SpecSync condition with Backend Error, retry
- In case that the referenced cluster is not found in kubernetes, update SpecSync condition with Input Error, no retry
/cc @filanov 
/cc @nmagnezi 
> MGMT-7726: Handle non existing cluster in Agent controller

- subsystem/cluster_test.go
When dealing with pointers, an object can be changed by mistake. In
those cases in which we don't want to accidentally change the object for
other tests we should make a copy of the object before changing it.
/cc @
/cc @
> NO-ISSUE: Fixed a flaky subystem-test related to disk-encryption.

- docs/events.yaml
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/common/events/events.go
- internal/events/eventstest/events_test_utils.go
- internal/host/host.go
- internal/host/host_test.go
- internal/host/hostcommands/instruction_manager_test.go
- internal/host/hostrole_test.go
- internal/host/hostutil/update_host.go
- internal/host/hostutil/update_host_test.go
- internal/host/monitor_test.go
- internal/host/transition_test.go
- internal/host/validations_test.go
Generate events related from internal/host package by the new events API.
This PR continues #1854 and depends on #2497.
/assign @masayag 
/cc @YuviGold 
/cc @filanov 
> MGMT-4872: Generate host package events

- models/event.go
- restapi/embedded_spec.go
- swagger.yaml
Adds infra_env_id to event properties
/cc @
/cc @
> MGMT-7799: Adds infra_env_id to event properties

- Dockerfile.assisted-service-build
> NO-ISSUE: install epel for centos8 stream

- openshift/template.yaml
Added OS_IMAGES and RELEASE_IMAGES to Deployment env in template.yaml
/cc @filanov 
/cc @osherdp 
/cc @rollandf 
> NO-ISSUE: added OS_IMAGES/RELEASE_IMAGES to template

- docs/events.yaml
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/common/events/events.go
The PR introduces an event type for a successful cluster registration.
Previously, the same event used for cluster registration was reused for notifying on the successful cluster registration, appearing as a duplicated event.
By adding a dedicated event, the duplicity is avoided.
/cc @nmagnezi 
> OCPBUGSM-34901: Add register successfully event

- docs/hive-integration/README.md
- docs/hive-integration/crds/infraEnvLateBinding.yaml
- docs/hive-integration/late-binding.md
/cc @avishayt 
/cc @filanov 
/cc @nmagnezi 
> MGMT-7780: Late Binding Kube API documentation

- docs/dev/events.md
Document how to add new events using the events generating.
/cc @rollandf 
/cc @nmagnezi 
> MGMT-7840: Document events usage

- subsystem/kubeapi_test.go
> MGMT-7698: KubeAPI subsystem - restore upload logs tests

- deploy/operator/gather.sh
Print resources for easy debugging of operator installation
/cc @
/cc @
> NO-ISSUE: Print resources for easy debugging of operator installation

- deploy/operator/upgrade/README.md
Operator upgrade readme file.
Ref: https://issues.redhat.com/browse/MGMT-7282
/cc @
/cc @
> MGMT-7282: Operator upgrade readme

- internal/bminventory/inventory.go
- internal/usage/consts.go
- subsystem/cluster_test.go
Feature-usage is already in use for multiple features and allows us to
monitor the global uses of different features in assisted via Elastic.
/cc @
/cc @
> MGMT-7421: Adding feature usage for disk-encryption.

- deploy/operator/setup_assisted_operator.sh
- deploy/operator/upgrade/before_upgrade.sh
- deploy/operator/upgrade/upgrade.sh
Use community operators to install AI operator for ocm-2.3. Use the existing catalog_source_name everywhere but override and set  `CATALOG_SOURCE_NAME` to  `community-operators` in case of operator upgrade scenario. Also, set the channel to `ocm-2.3` when creating the subscription from `community-operators`  before the operator upgrade. To upgrade, set the channel to `alpha`.
`CATALOG_SOURCE_NAME` , `CHANNEL_INSTALL_OVERRIDE`and  `CHANNEL_UPGRADE_OVERRIDE` will be set in the job config for the operator upgrade test in openshift/release.
/cc @lranjbar 
/cc @djzager  …
> MGMT-7282: Use community operators to install AI operator for ocm-2.3

- internal/host/hostcommands/logs_cmd.go
This commit fixes a bug causing UploadLogsCmd not pass CA certificate in
case when assisted service runs in the HTTPS mode. This causes any
attempt to upload logs from the agent to the service to fail with the
error
```
x509: certificate signed by unknown authority
```
Closes: [OCPBUGSM-35383](https://issues.redhat.com/browse/OCPBUGSM-35383)
/cc @carbonin 
/cc @flaper87 
> Bug 2006549: Pass CA certificate to the UploadLogsCmd

- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
- subsystem/kubeapi_test.go
In case that the user change the ClusterDeployment ref of an agent from a CD to an another, the Agent Controller will first Unbind and will bind once the Agent is registered again.
/cc @nmagnezi 
/cc @filanov 
> MGMT-7732: Late binding - support move agent

- docs/events.yaml
- internal/common/events/events.go
- internal/events/eventstest/events_test_utils.go
- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
This patch uses event generation for creating events for disk quick format.
In addition, the verbosity of the event matcher in case of a failure is increased to provide more context about the failure.
/cc @nmagnezi 
> MGMT-4872: Generate event for disk quick format

- docs/events.yaml
- internal/common/events/events.go
- internal/operators/handler/handler.go
- internal/operators/handler/handler_test.go
This patch uses event generation for creating events for reporting the
operator status.
/cc @nmagnezi 
> MGMT-4872: Generate event for operator status

- CONTRIBUTING.md
- README.md
- docs/dev/running-test.md
- docs/dev/testing.md
Add documentation on the repository CI
/cc @lranjbar
/cc @flaper87 
/cc @osherdp 
> MGMT-7599: Add documentation on the repository CI

- tools/ocp_version_update/update_default_release_versions_to_latest.py
cc reviewers instead of just mentioning them
/cc @YuviGold 
/cc @eliorerz 
> use /cc command to set reviewers for ocp bump PRs

- docs/events.yaml
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/common/events/events.go
- internal/events/eventstest/events_test_utils.go
> Bug 2009349: Adds InfraEnv Register Deregister events

- tools/ocp_version_update/Jenkinsfile.default_release_update
/cc @YuviGold @eliorerz 
Will only impact ocp-bump-versions job, I'll also validate it right after it gets pushed.
> NO-ISSUE: changed creds used in ocp bump job

- OWNERS_ALIASES
> NO-ISSUE: fix ci-approvers list

- docs/dev/testing.md
> NO-ISSUE: Fix tests url on dev testing documentation

- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
Use V2 in log URL in ACI
/cc @nmagnezi 
/cc @filanov 
> Bug 2010319: Use V2 in log URL in ACI

- internal/bminventory/inventory.go
This change updates UpdateInfraEnvInternal to hide InfraEnvUpdateParams.PullSecret
print when printing InfraEnvUpdateParams. Instead, it will print:
"pull secret was updated but will not be printed for security reasons."
/cc @filanov 
/cc @rollandf 
> Bug 2005656: UpdateInfraEnvInternal should not log InfraEnvUpdateParams.PullSecret

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1998483
/cc @filanov 
/cc @avishayt
> OCPBUGSM-33932:  Fix image_info content differs in response to GET and PATCH in /v1/clusters/UUID

- internal/installcfg/installcfg.go
Changed 'Platform' to 'platform' and 'Proxy' to 'proxy' in the install-config.yaml
all install-config.yaml fields should start with a lowercase
The capital P break the baremetal tests yaml parser
-->
/cc @Gal-Zaidman 
/cc @rollandf 
> NO-ISSUE: Changed Platform to platform in the install-config.yaml

- internal/host/host.go
- Manual set of host role to auto-assign failed with db error
- The root cause is that the role update opened a SELECT FOR UPDATE transaction
and the monitor inherited this transaction and attempted to run aggregated query
with this transaction in parallel to the role update
- The solution is to replace the count query with a select
/cc @
/cc @
> OCPBUGSM-36009: Fix role selection query

- docs/hive-integration/late-binding.md
- internal/bminventory/inventory.go
- internal/bminventory/mock_installer_internal.go
- internal/controller/controllers/controller_event_wrapper.go
- internal/controller/controllers/infraenv_controller.go
- internal/controller/controllers/infraenv_controller_test.go
- subsystem/kubeapi_test.go
- Add a finalizer to InfraEnv CR
- When InfraEnv is deleted, the hosts related to it will be deleted if
they are Unbound or Installed
- If no more hosts are connected, the InfraEnv is deleted from backend
and the finalizer is removed
- If there are still hosts connected, the InfraEnv will not be deleted
and the finalizer not removed. The controller will requeue for 1
minutes and recheck.
/cc @nmagnezi 
/cc @filanov 
> MGMT-7779: Delete Agents when InfraEnv is deleted

- OWNERS_ALIASES
Remove user yuvigold
/cc @
/cc @
> NO-ISSUE: Remove user yuvigold

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
If the user tries to unbind an host that has been created from an
InfraEnv that is connected to Cluster, a Conflict status is returned.
/cc @nmagnezi 
/cc @nshidlin
> Bug 2012811: Unbind host from bound InfraEnv conflict

- subsystem/metrics_test.go
> MGMT-7998: Fix nil pointer dereference in subsystem metrics tests

- internal/host/host.go
- internal/host/host_test.go
- internal/host/monitor.go
> MGMT-7876: auto-assign select weakest masters first

- deploy/operator/common.sh
The operator upgrade flow requires using the previous OCP version if ASSISTED_UPGRADE_OPERATOR is true. Otherwise, use the latest version. Hence, to ensure we fetch the proper version, sorted the release images list and filtered out non-default cpu architecture (as not relevant for the operator).
E.g.
* When ASSISTED_UPGRADE_OPERATOR is false:
ASSISTED_OPENSHIFT_VERSION = openshift-v4.9
ASSISTED_OPENSHIFT_INSTALL_RELEASE_IMAGE = quay.io/openshift-release-dev/ocp-release:4.9.0-x86_64
* When ASSISTED_UPGRADE_OPERATOR is true:
ASSISTED_OPENSHIFT_VERSION = openshift-v4.8
ASSISTED_OPENSHIFT_INSTALL_RELEASE_IMAGE = quay.io/openshift-release-dev/ocp-release:4.8.13-x86_64
/cc @osherdp  …
> NO-ISSUE: use appropriate image in operator upgrade

- internal/cluster/transition_test.go
- internal/cluster/validator.go
OVN is not supported when VIP DHCP allocation is enabled, thus, added a proper validation to cluster validator (as part of 'isNetworkTypeValid' validation).
/cc @tsorya 
/cc @avishayt 
/cc @filanov 
> MGMT-8094: validate OVN with VIP allocation

- internal/host/host.go
Improve validations debuggability.
/cc @
/cc @
> MGMT-7439: Improve validations debuggability

- docs/enhancements/agents-back-to-infraenv.md
Enhancement doc for return Agents to InfraEnv
/cc @filanov 
/cc @avishayt 
/cc @mhrivnak 
> MGMT-8062: Enhancement doc for return Agents to InfraEnv

- docs/events.yaml
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/transition.go
- internal/cluster/transition_test.go
- internal/common/events/events.go
- internal/controller/controllers/controller_event_wrapper_test.go
- internal/host/host.go
- internal/host/host_test.go
- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
- internal/host/hostrole_test.go
- internal/host/validations_test.go
- internal/imgexpirer/imgexpirer.go
- internal/imgexpirer/imgexpirer_test.go
Renamed events to a uniform format by the structure `<event-context>_<past-verb>`.
/cc @
/cc @
> NO-ISSUE: Renamed events to a uniform format

- config/manager/manager.yaml
- config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
- deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
We are moving to a new org in Quay.io. This is to assisted with the operator-publish as described in https://github.com/openshift/release/pull/23142
[MGMT-8113](https://issues.redhat.com/browse/MGMT-8113)
/cc @djzager 
/cc @osherdp 
No backport needed. I will make the changes to the open PR in ocm-2.4 for this as well.
> MGMT-8113: Update the postgresql image in the operator CSV to the new org in Quay.io

- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
In case that the Progress in empty on the host, clear also in the Agent Status.
/cc @nmagnezi 
/cc @filanov 
> MGMT-8108: Clear Progress in Agent status

- api/v1beta1/agentserviceconfig_types.go
- config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
- config/crd/resources.yaml
- config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
- deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
- deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
Add more links to AI related projects in CSV
/cc @lranjbar 
/cc @flaper87 
/cc @celebdor 
> NO-ISSUE: Add more AI links to CSV

- docs/dev/events.md
Added documentation regarding events name format.
/cc @
/cc @
> NO-ISSUE: Add event name documentation

- docs/dev/events.md
Added documentation regarding events severity levels.
/cc @
/cc @
> NO-ISSUE: Add event severity documentation

- docs/enhancements/agents-back-to-infraenv.md
Remove support for unbind of a single Agent if the installation already
started.
/cc @avishayt 
/cc @filanov 
> MGMT-8062: Update doc for agents-back-to-infraenv

- api/hiveextension/v1beta1/agentclusterinstall_types.go
- api/v1beta1/agent_types.go
- config/crd/bases/agent-install.openshift.io_agents.yaml
- config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
- deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/validations/validations.go
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/ignition/ignition.go
- internal/ignition/ignition_test.go
- internal/ignition/mock_ignition.go
- models/cluster.go
- models/cluster_create_params.go
- models/cluster_update_params.go
- models/host.go
- models/host_update_params.go
- models/v2_cluster_update_params.go
- restapi/embedded_spec.go
- swagger.yaml
This PR add API specification for Ignition Enpoint URL and Igntion token.
/cc @avishayt 
/cc @
> MGMT-6893: Support custom Ignition Endpoint URL and Ignition token

- models/feature_support_level.go
- restapi/embedded_spec.go
- swagger.yaml
Added enum values for feature_id
/cc @avishayt 
> MGMT-8126: Exposing feature_id in swagger

- api/v1beta1/agent_types.go
- docs/hive-integration/kube-api-conditions.md
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
Add support in Agent conditions for host status unbinding-pending-user-action
/cc @filanov 
/cc @nmagnezi 
/cc @avishayt 
> MGMT 8078: Agent conditions for unbinding-pending-user-action

- internal/bminventory/inventory.go
- subsystem/manifests_test.go
> MGMT-8166: updateClusterData should handle updates for Tang servers

- docs/events.yaml
- internal/bminventory/inventory.go
- internal/common/events/events.go
- internal/controller/controllers/controller_event_wrapper_test.go
Cluster event logs are missing in cluster installation events. I.E. stage Starting installation.
Added `cluster_id` as a property to any event that is related to the cluster in order to solve this.
/cc @
/cc @
> Bug 2019415: Cluster installation stages missing from cluster event logs

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/registrar.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
- internal/controller/controllers/infraenv_controller.go
- subsystem/kubeapi_test.go
When a cluster is deleted:
- For each of the hosts:
- If the Host's InfraEnv is associated to the Cluster (not late binding):
- Delete the Host
- If the Host's InfraEnv is not associated to the Cluster (late binding):
- Unbind the Host
/cc @filanov 
> MGMT-8130: Unbind hosts on cluster delete

- internal/cluster/validator.go
[MGMT-8165](https://issues.redhat.com/browse/MGMT-8165): Enhance message when hosts' clocks are not in sync and have more than 4 min gap
/cc @
/cc @
> MGMT-8165: Enhance message when hosts' clocks are not in sync and have more than 4 min gap

- docs/events.yaml
- internal/bminventory/inventory.go
- internal/bminventory/inventory_v2_handlers.go
- internal/common/events/events.go
- internal/host/host.go
- internal/host/hostcommands/install_cmd.go
Update the properties order in host-type events by the following:
1. `host_id` (UUID)
2. `infra_env_id` (UUID)
3. `cluster_id` (UUID_PTR - optional)
/cc @masayag 
/cc @nmagnezi 
> MGMT-8188: Update properties order of host events

- internal/host/hostcommands/logs_cmd.go
- internal/host/hostcommands/logs_cmd_test.go
[MGMT-8192](https://issues.redhat.com/browse/MGMT-8192): Logs_cmd command fails if insecure flag is set to true 
When insecure=true logs sender will try to use certificate that was set in --cacert flag.
Service currently always sets "cacert" flag with path that was not mounted and not exist.
This commit fixes setting cacert flag all the time and will set it only
in case certificate path was provided, same as in install_cmd
/cc @oshercc 
/cc 
> MGMT-8192: Logs_cmd command fails if insecure flag is set to true

- docs/dev/kube-api-webhook.md
/cc @isaacdorfman 
/cc @filanov 
> NO-ISSUE: Update webhook doc

- docs/hive-integration/README.md
- docs/hive-integration/late-binding.md
Update of the late binding doc with the `Return Agents to InfraEnv` flow.
/cc @filanov 
/cc @avishayt 
> MGMT-8099: Late binding doc update

- internal/host/hostcommands/logs_cmd.go
- internal/host/hostcommands/logs_cmd_test.go
[MGMT-8207](https://issues.redhat.com/browse/MGMT-8207): Worker logs does not collected while cluster in status error
We tried to mount not existing file on all nodes though it should exist
only in bootstrap
- [] None
/cc @osherdp 
/cc @
> MGMT-8207: Worker logs does not collected while cluster in status error

- client/installer/unbind_host_responses.go
- restapi/embedded_spec.go
- restapi/operations/installer/unbind_host_responses.go
- subsystem/cluster_v2_test.go
- subsystem/day2_cluster_test.go
- subsystem/host_v2_test.go
- subsystem/infra_env_test.go
- subsystem/utils_test.go
- swagger.yaml
Add Bind/Unbind flows to REST API subsystem tests for host and cluster
/cc @
/cc @
> MGMT-7693: More V2 subsystem tests

- subsystem/cluster_v2_test.go
Additional subsystem tests via REST API for unbinding hosts on cluster
deletion.
/cc @filanov 
> MGMT-8101: Add subsystem for return host to InfraEnv

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
- Ask BMH to reboot the agent from ISO on late unbind scenario when the agent mark that it is ready by setting UnbindCondition to UnbindingPendingUserActionReason
- This is done by re-attaching the BMH and removing the image URL so the provisioning cycle will restart
/cc @
/cc @
> MGMT-8079: reboot BMH on unbind-pending-user-action

- docs/dev/olm-operator-plugins.md
Modify the docs to include odf operator.
/cc @pkliczewski 
/cc @avishayt 
/cc @gobindadas 
> MGMT-7231: ODF docs

- internal/controller/controllers/agentserviceconfig_controller.go
> Bug 2023616: Add LivenessProbe to Image Service (#2751)

- internal/cluster/validations/validation_test.go
- internal/cluster/validations/validations.go
This PR fixes the URL validation for ignition endpoint, where before we
didn't expect https to be valid.
/cc @eranco74 
/cc @avishayt 
> MGMT-6893: Fix ignition endpoint URL validation

- docs/hive-integration/kube-api-conditions.md
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
Add added-to-existing-cluster host state handling in RequirementsMet
Agent condition.
/cc @avishayt 
/cc @filanov 
> MGMT-8276: Add Day2 state in Agent conditions

- pkg/auth/rhsso_authenticator.go
Since they are user issues with tokens there are not much
we can do about this in terms of debugging when going over
the AI logs.
The error is still clearly presented to the user via the API
/cc @
/cc @
> MGMT-8243: remove log msg about user issues with tokens

- dev-requirements.txt
- tools/ocp_version_update/Jenkinsfile.default_release_update
- tools/ocp_version_update/update_default_release_versions_to_latest.py
Up until now, when updating OCP versions we create a Jira ticket along with the change. Every Jira ticket adds pretty much no data over the PR description, tends to become out-of-sync with the PR status, and adds another point of failure when Jira is on maintenance.
This change will remove any kind of Jira access for this process (also for this repository), only requiring GitHub credentials for pushing the changes and creating a PR. It will still look at all open PRs to see if the same change has already been suggested.
I've tested the two main flows manually, we should also test Jenkins changes once it's in.
/cc @eliorerz  …
> Skip tickets creation when bumping OCP versions

- subsystem/kubeapi_test.go
- subsystem/utils_test.go
To make it easier (or actually, possible) to look into a failure from and
understand what happened in the backend, the subsystem tests should print
all resources when a test fails (clusters, hosts, infraenvs).
/cc @
/cc @
> MGMT-8281: subsystem print resources when subsystem tests fail

- subsystem/cluster_test.go
fix flaky reset log test by changing some of the logic to wait for a more stable condition
/cc @
/cc @
> MGMT-8307: fix flaky reset log test

- subsystem/host_test.go
The DB may sometimes take an extra moment to update host status,
as done with this test. Therefore, the test should try to compare
the host status to the expected status several times before failing the test.
/cc @
/cc @
> MGMT-8222: Fix flaky subsystem test register_same_host_id

- internal/controller/controllers/agent_controller.go
Move NTP source update log to debug as it is a status update not a
change in the spec.
/cc @nmagnezi 
> NO-ISSUE: AgentController move log to debug

- openshift/template.yaml
This allows us to specify this parameter in the saas file when deploying
to various environments in the cloud.
It is not marked as required because, for now, it will only be enabled
in integration. The default value for this was always an empty string in
our source so this won't change the behavior of stage or prod.
Locally processed the template to ensure it rendered properly:
`oc process -f openshift/template.yaml --local --param-file=env`
where `env` contained:
```
IMAGE_TAG=image-tag
SERVICE_BASE_URL=https://example.com/assisted
JWKS_URL=https://example.com/jwks
ALLOWED_DOMAINS=https://example.com/allowed-domains
AUTH_TYPE=rhsso
OCM_BASE_URL=https://example.com/ocm
HW_VALIDATOR_REQUIREMENTS={}
INSTALLER_IMAGE=installer-image
CONTROLLER_IMAGE=controller-image …
```
> MGMT-7716: Add IMAGE_SERVICE_BASE_URL to template

- internal/bminventory/inventory_v2_handlers.go
- internal/cluster/cluster.go
- internal/cluster/common.go
IN GORM v2, when performing update, if the model object contains other
db objects, GORM attempts to UPSERT them using INSERT with ON CONFLICT
clause.  This is undesirable behavior that occcasionaly causes error in the service
code.
The solution is to use empty model with addition of explicit primary key of the
model.
/cc @tsorya 
/cc @
> MGMT-8333: Cluster failed to update console operator status

- internal/bminventory/inventory.go
> NO-ISSUE: Fix typo in error message

- internal/migrations/20211125182200_change_hosts_pkey.go
- internal/migrations/20211125182200_change_hosts_pkey_test.go
- internal/migrations/migrations.go
https://issues.redhat.com/browse/MGMT-8333
/cc @tsorya 
> MGMT-8351: Hosts table primary key has to be migrated from (cluster_id, id) to (infra_env_id, id)

- api/v1beta1/agent_types.go
- config/crd/bases/agent-install.openshift.io_agents.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
The current hostname is already available in Status.Inventory.HostName.
/cc @filanov 
/cc @avishayt 
/cc @eranco74 
> MGMT-8337: Remove unsused hostname from Agent CRD

- Dockerfile.assisted-service-build
Seems like on #2916 we moved to a base-image that doesn't have an updated git version (it's ``1.8.3.1``), which led to the following failure when QE deployed assisted-installer on PSI:
```
command=git clone --branch master https://github.com/openshift-metal3/facet /home/assisted/assisted-service/build/assisted-installer-ui exited with an error=warning: templates not found /usr/share/git-core/templates\r\nfatal: Unable to find remote helper for 'https' code=128\r\nmake: *** [deploy-ui] Error 1"
```
This should make sure we use an updated package of git. …
> Upgrade git on build image

- internal/host/transition_test.go
- internal/host/validator.go
[MGMT-7943](https://issues.redhat.com/browse/MGMT-7943): changing message for image availability validation failure
/cc @
/cc @
> MGMT-7943: changing message for image availability validation failure

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
Set machine_network_cidr_updated_at when vip_dhcp_allocation changes
value
/cc @tsorya 
/cc @
> MGMT-8203: DHCP server failed to allocated VIPs when VIPs are manually cleared

- internal/bminventory/inventory_test.go
- subsystem/cluster_test.go
Adding subsystem test for oVirt provider, test different installation flows for the new provider option.
@avishayt 
@yevgeny-shnaidman  
@ori-amizur 
/cc @Gal-Zaidman
> OCPRHV-635: add tests for ovirt provider

- subsystem/ams_subscriptions_test.go
- subsystem/authz_test.go
- subsystem/cluster_test.go
- subsystem/cluster_v2_test.go
- subsystem/day2_cluster_test.go
- subsystem/events_test.go
- subsystem/host_test.go
- subsystem/host_v2_test.go
- subsystem/image_test.go
- subsystem/infra_env_test.go
- subsystem/ipv6_test.go
- subsystem/kubeapi_test.go
- subsystem/manifests_test.go
- subsystem/metrics_test.go
- subsystem/operators_test.go
- subsystem/subsystem_suite_test.go
- subsystem/utils_test.go
> MGMT-8299: Subsystem refactor: Implement a global AfterEach func

- docs/hive-integration/README.md
- docs/hive-integration/import-installed-cluster.md
Add documentation on how to import an existing cluster to add additional nodes.
/cc @nmagnezi 
/cc @filanov 
/cc @avishayt 
> MGMT-7901: Kube-API import cluster doc

- Dockerfile.assisted-service
- hack/generate.sh
- tools/client_package_initializer.py
Replace the python client  artifact on the service image with the artifact we upload to PYPI (versionised)
/cc @osherdp
> MGMT-8370 - Replace the client on the service with the new generated one

- cmd/main.go
- internal/garbagecollector/garbageCollector.go
- internal/infraenv/infraenv.go
- internal/infraenv/infraenv_test.go
- internal/infraenv/mock_infraenv_api.go
- subsystem/cluster_v2_test.go
- tools/deploy_assisted_installer.py
Add a garbage collection for infraenvs.
Cloud env only.
/cc @nmagnezi 
/cc @filanov 
> MGMT-8178: InfraEnv garbage collector

- internal/featuresupport/support_levels_list.go
> MGMT-8451: Setting VIPs support level to dev-preview on all versions

- Dockerfile.assisted-service-build
The new CI job for unit tests needs the files from assisted service to be able to run the `make ci-unit-test` target.
/cc @
/cc @
> MGMT-7330: Copy files for CI to run the unit tests

- OWNERS
> NO-ISSUE Add api-review label to k8s API changes

- cmd/main.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/progress_test.go
- internal/cluster/transition_test.go
- internal/operators/ocs/validation_test.go
Update event text on Add Host to Installed Cluster to redirect user to console.redhat.com
/cc @filanov 
/cc @nmagnezi 
/cc @nirfarkas 
> MGMT-8313: Update event on Add Host to Installed Cluster

- internal/host/hostcommands/api_vip_connectivity_check_cmd.go
- internal/host/hostcommands/api_vip_connectivity_check_cmd_test.go
- models/api_vip_connectivity_request.go
- restapi/embedded_spec.go
- swagger.yaml
Add support to pass to agent a custom ignition endpoint along with a CA and  auth token.
Also use configured pool name if exists.
/cc @eranco74 
/cc @avishayt 
/cc @filanov 
> Mgmt-8424: Day 2 ignition endpoint check customization

- internal/infraenv/infraenv_test.go
Add a sleep in the test to make sure there is enough difference between the
updated_at and the inactive check.
/cc @eliorerz 
/cc @nmagnezi 
/cc @filanov 
> MGMT-8472: Fix flacky test infraenv GC

- internal/controller/controllers/controller_event_wrapper.go
A small change to fix the logged InfraEnv name.
Before the change:
"Pushing InfraEnv event %!s(*string=0xc0015903c0) spoke-cluster"
After the change:
"Pushing InfraEnv event myinfraenv spoke-cluster"
/cc @rollandf 
/cc @filanov 
> MGMT-8505: Fix logger for NotifyKubeApiInfraEnvEvent

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
> MGMT-8504: Fix InfraEnv image updated event loop

- tools/deployment_options.py
> NO-ISSUE: Allow short or fqdn for image in manifest

- openshift/template.yaml
Add InfraEnv GC to OpenShift template
/cc @osherdp 
/cc @filanov 
> MGMT-8178: Add InfraEnv GC to OpenShift template

- models/ignition_endpoint.go
- restapi/embedded_spec.go
- swagger.yaml
updated documentation 
-->
/cc @rollandf 
/cc @avishayt 
> MGMT-8623: Updated ignition-endpoint ca_certificate description to say that the content should be base64 encoded

- internal/network/manifests_generator.go
changing sno dnsmasq name from 99.. to 50..
/cc @
/cc @
> NO-ISSUE: changing sno dnsmasq name from 99.. to 50..

- models/disk_encryption.go
- restapi/embedded_spec.go
- swagger.yaml
> NO-ISSUE: Added example for tang_server JSON-formatted string to swagger.

- internal/bminventory/inventory.go
- internal/network/cidr_validations.go
- internal/network/cidr_validations_test.go
The idea of sno is to minimize resources required by customers to run openshift.  We should allow the minimal cidr size as possible. 
/cc @
/cc @
> Allow /30 machine cidr in SNO

- docs/events.yaml
- internal/bminventory/inventory_test.go
- internal/common/events/events.go
Before this change, the event 'ignition_config_image_generated' got called
with infra_env_id value at the place of the 'cluster_id' parameter.
/cc @
/cc @
> MGMT-8095: Change 'ignition_config_image_generated' event type to infra-env

- dev-requirements.txt
Apparently we import `pyyaml` but it's not installed as part of the dev-requirements 
/cc @osherdp
> NO-ISSUE - Add pyyaml to python requirements

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
Before this change, when searching for hosts for a deleted (or just bad) InfraEnv id,
the backend returned an empty host list.
With this change, the backend will first check the DB for the requested
InfraEnv id and return 404 Not Found if it can't find a match.
/cc @filanov 
/cc @rollandf 
/cc @avishayt 
> MGMT-8671: Fix V2ListHosts response when InfraEnv does not exist

- Makefile
Allow to pass specific UI and IMAGE_SERVICE images when deploying on podman
/cc @osherdp 
/cc @
> MGMT-8709: Allow to override IMAGE_SERVICE and ASSISTED_UI images

- internal/host/common.go
[MGMT-8228](https://issues.redhat.com/browse/MGMT-8228): Fixed the error message when a host fails to reboot so that it's grammatically correct. 
/cc @carbonin 
/cc @rollandf 
> MGMT-8228: Fixed the error message when a host fails to reboot

- docs/dev/feature-usage.md
> MGMT-7385: feature usage doc

- api/hiveextension/v1beta1/agentclusterinstall_types.go
- config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
- subsystem/cluster_test.go
- subsystem/kubeapi_test.go
- subsystem/utils_test.go
- Add support for user managed networking in agent cluster install
/cc @
/cc @
> MGMT-8663: Support none platform in kube-api for day1

- internal/host/common.go
- internal/host/host.go
- internal/host/host_test.go
> MGMT-8721: Allow host updates when unbound or binding

- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
- internal/host/hostcommands/logs_cmd.go
- internal/host/hostcommands/next_step_runner_cmd.go
- internal/host/hostcommands/next_step_runner_cmd_test.go
[MGMT-8498](https://issues.redhat.com/browse/MGMT-8498): Adding mounting /etc/pki to next_step,installer and logs commands to allow providing additional certificate bundle
/cc @
/cc @
> MGMT-8498: Adding mounting /etc/pki to next_step,installer and logs commands to allow providing additional certificate bundle

- go.mod
- go.sum
Upgraded github.com/moby/moby v1.13.1 to v20.10.12
/cc @osherdp 
/cc @filanov 
> NO-ISSUE: upgrade moby to v20.10.12

- docs/dev/feature-usage.md
Added a note under `How to add a usage entry`
> Since we also maintain a feature support list (ref: featuresupport/support_levels_list.go),
> If you do add a new constant to usage/consts.go, Please add the ID into swagger: `#/definitions/feature-support-level`.
> The feature ID is CAPITAL_SNAKE_CASE_OF_CONST. You can refer to `usage/manager.go:UsageNameToID` to see
> how the ID is generated.
> Update the feature support level if needed.
/cc @
/cc @
> NO-ISSUE: Update to dev docs regarding feature-usage

- OWNERS
> MGMT-8606: Add api-review label to Events API changes

- tools/generate_events.py
> NO-ISSUE: minor cleanup to the events generator

- restapi/embedded_spec.go
- swagger.yaml
> MGMT-8301: Add a V1 API deprecation warning in swagger

- docs/user-guide/install-customization.md
> MGMT-8703: Document adding additional trust bundle

- subsystem/kubeapi_test.go
Verify that the event URL in the CRDs is actually bringing events.
/cc @nmagnezi 
/cc @filanov 
> NO-ISSUE: Check events in kubeapi subsystem

- internal/host/transition_test.go
- internal/host/validator.go
Currently we say "Require a disk of at least 120 GB" which makes it seem that
the capacity isn't large enough, even if the real reason that disks are insufficient
aren't related to capacity.
/cc @
/cc @
> Bug 1994696: Clarify not eligible disk error message

- internal/common/events/events.go
- internal/controller/controllers/controller_event_wrapper.go
- internal/controller/controllers/controller_event_wrapper_test.go
- internal/events/api/event.go
- internal/events/api/mock_event.go
- internal/events/event.go
- internal/events/event_test.go
- internal/events/events_api.go
- models/event.go
- restapi/embedded_spec.go
- subsystem/events_test.go
- swagger.yaml
- tools/generate_events.py
Events are a part of assisted-service API.
Event names will now be stored in db and included
in the events list API response.
/cc @filanov
/cc @masayag 
/cc @rollandf 
> MGMT-8607: Store event names in the DB

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- subsystem/cluster_v2_test.go
Cherry-picks #3082
/cc @slaviered @lalon4
> [cloud_hotfix_releases] MGMT-8477: invoke cluster validations when updating a host (#3082)

- internal/bminventory/inventory.go
> MGMT-7307: Tweak media disconnected message

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/instruction_manager_test.go
- models/import_cluster_params.go
- restapi/embedded_spec.go
- skipper.yaml
- subsystem/day2_cluster_test.go
- swagger.yaml
> MGMT-8755: Make openshift_version optional for day2 cluster in REST API

- internal/host/transition.go
- internal/host/transition_test.go
[MGMT-8841](https://issues.redhat.com/browse/MGMT-8841): Container image availability check is not running in some cases
In case image availability succeed and then host got reset , it will not run one more time
Need to clean images_status on host re-registering
- [] Tests
- [] None
/cc @carbonin 
/cc @
> MGMT-8841: Container image availability check is not running in some cases

- internal/common/common.go
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
- subsystem/kubeapi_test.go
The PR for the ticket [MGMT-8280](https://issues.redhat.com/browse/MGMT-8280) did not include integration tests.
This PR adds them to the code.
/cc @
/cc @
> MGMT-8765: Add integration tests to the MGMT-8280 code

- api/hiveextension/v1beta1/agentclusterinstall_types.go
- config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
oc get aci -A
NAMESPACE            NAME                                  CLUSTER                 STATE
assisted-installer   test-agent-cluster-install-b1e786b5   test-cluster-06f5d8ad   preparing-for-installation
/cc @filanov 
/cc @nmagnezi 
> MGMT-7305: Fix ACI column

- deploy/operator/README.md
- deploy/operator/ztp/agentClusterInstall.j2
- deploy/operator/ztp/assisted-installer-crds-playbook.yaml
- deploy/operator/ztp/deploy_spoke_cluster.sh
- deploy/operator/ztp/none_platform_utils.sh
Create ZTP installation flow for None platform.  For this the following changes were needed:
- Add user-managed-networking variable support for this flow as it is needed by assisted service
- Remove API and Ingress VIPs from agentclusterinstall YAML file when running this flow.
- Add load balancer on top of nginx for none platform use
- Add support for DNS definition in libvirt that adds DNS names needed by Openshift to complete none platform installation.
The following environment variables were added to support this flow:
export USER_MANAGED_NETWORKING="${USER_MANAGED_NETWORKING:-false}"
\# Spawn load balancer for none platform on local machine 
export SPAWN_NONE_PLATFORM_LOAD_BALANCER="${SPAWN_NONE_PLATFORM_LOAD_BALANCER:-false}"
\# Add DNS entrries in LIBVIRT network to point to the …
> MGMT-8664: Add none ztp platform installation flow with load-balancer for libvirt

- go.mod
- go.sum
Due to SSO system upgrade, all users of ocm-sdk-go should update
to >= v0.1.205 which handles capitalized Bearer
/cc @cben 
/cc @filanov 
/cc @osherdp 
> MGMT-8887: Upgrade OCM SDK

- deploy/operator/common.sh
- deploy/operator/gather.sh
- deploy/operator/setup_assisted_operator.sh
The CI test `e2e-metal-assisted-operator-ztp-periodic-upgrade` fails on `release-ocm-2.4` branch because of the missing fix openshift/assisted-service@22868a6. 
This PR adds the fix from the master branch to this branch.
/cc @
/cc @
> Bug 2038250: Fix catalogsource name

- go.mod
- go.sum
Due to SSO system upgrade, all users of ocm-sdk-go should update
to >= v0.1.205 which handles capitalized Bearer
/cc @
/cc @
> [cloud_hotfix_releases] MGMT-8887: Upgrade OCM SDK

- docs/user-guide/rest-api-v1-v2-transition-guide.md
> NO-ISSUE: Fix broken URLs in REST V1 to V2 doc

- docs/user-guide/restful-api-guide.md
> NO-ISSUE: add vlan and bond nmstate examples

- internal/featuresupport/support_levels_list.go
Added 4.10 to SupportLevelsList and set arm64 feature as dev-preview.
/cc @filanov 
/cc @avishayt
/cc @sagidayan  
> MGMT-8893: set arm64 support as dev-preview

- docs/user-guide/restful-api-guide.md
> NO-ISSUE: Add syntax highlighting to restful API guide

- docs/user-guide/restful-api-guide.md
> NO-ISSUE: update static networking guide to v2

- api/hiveextension/v1beta1/agentclusterinstall_types.go
- api/v1beta1/infraenv_types.go
- config/crd/bases/agent-install.openshift.io_infraenvs.yaml
- config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
- deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
- internal/bminventory/inventory.go
- internal/controller/controllers/agentserviceconfig_controller_test.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
- internal/controller/controllers/infraenv_controller.go
- subsystem/kubeapi_test.go
- CPUArchitecture field is added to InfraEnv spec
- The Cluster Deployment infers the architecture from
the ImageSet
- The backend verifies that the InfraEnv architecture
matches the bound cluster, if such exist and also
verifies that late binding hosts has the same architecture
as the cluster they are binding into
/cc @
/cc @
> MGMT-8428: cpu architecture support in kube-api

- OWNERS
- OWNERS_ALIASES
Update lists based on new team members.
Also, make the alias groups a bit more intuitive.
/cc @filanov
> NO-ISSUE: update approvers and reviewers lists

- README.md
> NO-ISSUE: clarifies prerequisites in README

- subsystem/kubeapi_test.go
Fix "deploy CD with ACI and agents with ignitionEndpoint" subsystem
test, use eventually to update agent CR, avoiding conflict with existing CR version.
change updateAgentClusterInstallCRD interval to 1 sec to reduce test time.
/cc @osherdp 
> MGMT-9027: fix flaky subsystem test

- deploy/podman/README.md
This will hopefully let us remove an external document that describes
the same process.
/cc @
/cc @
> NO-ISSUE: extends doc with podman pod config detail

- deploy/podman/pod.yml
> NO-ISSUE: corrects image reference in pod definition

- api/v1beta1/agent_types.go
- config/crd/bases/agent-install.openshift.io_agents.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
[MGMT-7896](https://issues.redhat.com/browse/MGMT-7896): Added the host's log's URL to the Agent CR's debugInfo when it becomes available so that the user may view and download that host's logs.
Manually tested by deploying nodes using the assisted-test-infra repository. Then once the status was updated with the logs  URL, curling it locally to see if the url is correct and contains the correct logs.
/cc @rollandf 
/cc @carbonin  …
> MGMT-7896: Add host's log's URL to Agent CR's status.

- internal/network/cidr_validations.go
- internal/network/cidr_validations_test.go
[MGMT-9068](https://issues.redhat.com/browse/MGMT-9068): Allow /31 machine cidr in SNO 
After looking on equinix integration we saw that we need to allow 2 ips for sno
- [] Bug fix
- [] Automation (CI, tools, etc)
- [] None
- [] assisted-test-infra environment
/cc @
> MGMT-9068: Allow /31 machine cidr in SNO

- config/rbac/base/role.yaml
- deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
A leader is currently locked over ConfigMap resource. This kind of
locking mechanism is deprecated in favor of using Leases
Phase I for replacing the locking mechanism with leases is to
allow the assisted-service to create and read lease objects
/cc @
/cc @
> MGMT-8582: rbac permission for leases

- docs/set-discovery-password.md
- docs/set-minimal-iso.md
- docs/user-guide/deploy-on-bare-metal.md
- docs/user-guide/install-customization.md
- docs/user-guide/rest-api-v1-v2-transition-guide.md
- docs/user-guide/samples/cluster.json
This change update the current documentation to use V2 REST-API endpoints.
It also addes some syntax highlighting and other corrections.
with '#' will be ignored, and an empty message aborts the commit.
/cc @filanov 
/cc @avishayt 
> MGMT-8943: Update documentation to V2 REST-API

- docs/user-guide/rest-api-day2.md
- docs/user-guide/rest-api-getting-started.md
Adding documentation on how to deploy dat2 hosts via REST-API V2.
Documentation includes two scenarios:
- With late binding.
- Without late binding.
/cc @filanov 
/cc @avishayt 
> MGMT-8823: Document REST-API V2 Day2 flows

- internal/bminventory/inventory.go
- subsystem/cluster_v2_test.go
> MGMT-9077: refresh cluster after host unbound

- .codecov.yml
- Makefile
- hack/publish-codecov.sh
Publish unit test code coverage to codecov.io.
The script is inspired from
https://github.com/openshift/boilerplate/blob/master/boilerplate/openshift/golang-osd-operator/codecov.sh.
- [] None
/cc @osherdp 
/cc @
> MGMT-9069: Report unit tests code coverage

- internal/host/host.go
- internal/host/host_test.go
The image_status_updated event message will now:
1. Use float numbers up to two decimal places.
2. Display image size in Megabytes instead of bytes.
/cc @empovit
/cc @filanov 
> BUG 1969933: Improve image_status_updated event message

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
> MGMT-8046: BMAC should not create BMHs on the spoke cluster if it sees that platform==none

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/common/error_utils.go
…erInstallConfig
/cc @filanov 
/cc @carbonin 
> MGMT-9114: Remove V1 operationId GetClusterInstallConfig, UpdateCluster

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- subsystem/authz_test.go
- subsystem/cluster_test.go
The V1 endpoint `DownloadClusterKubeconfig`, was deprecated in favor
of `DownloadClusterCredentials`. Find unit-tests coverage `"[V2] V2DownloadClusterCredentials"`
/cc @filanov 
/cc @carbonin 
> MGMT-9113: Remove V1 GetCredentials, DownloadClusterKubeconfig

- internal/manifests/manifests.go
- internal/manifests/manifests_test.go
- internal/operators/manager.go
- internal/operators/manager_test.go
- subsystem/cluster_test.go
- subsystem/manifests_test.go
> MGMT-9116: Remove V1 operationId CreateClusterManifest, DeleteClusterManifest

- internal/manifests/manifests.go
- internal/manifests/manifests_test.go
- subsystem/cluster_test.go
- subsystem/manifests_test.go
> MGMT-9117: Remove V1 operationId DownloadClusterManifest, ListClusterManifests

- internal/controller/controllers/controller_event_wrapper.go
- internal/events/api/event.go
- internal/events/api/mock_event.go
- internal/events/event.go
- internal/events/events_api.go
- subsystem/image_test.go
> MGMT-9129: Remove V1 operationId ListEvents

- internal/host/refresh_status_preprocessor.go
- internal/host/validator.go
- models/api_vip_connectivity_response.go
- restapi/embedded_spec.go
- swagger.yaml
Changes in validation messages, validation function names and swagger
documentation.
/cc @filanov 
/cc @
> MGMTBUGSM-85: Change occurances of "API VIP connectivity" to "Ignition downloadable"

- internal/operators/manager.go
- internal/operators/manager_test.go
[MGMT-8380](https://issues.redhat.com/browse/MGMT-8380): 
**Problem**:
There are two scenarios when manifests need to be created:
1. When an OLM operator is enabled for a Cluster
2. When a user requests to create custom manifests for a Cluster
Both the scenarios above called the same create manifest function,
which sets a feature flag called "Custom Manifests" to true. This
is incorrect behavior for the first scenario since an OLM operator's
manifests are not custom manifests and should not enable this feature
flag.
**Solution**: Use the create manifest internal function instead when
creating manifests for OLM operators. The internal function evades
setting the custom manifest feature flag.
1. Used the assisted-test-infra environment to deploy nodes
2. List the cluster to see if the …
> MGMT-8380: Stop setting custom manifest feature flag for OLM operators

- deploy/podman/README.md
Adds podman version 3.3+ requirement.
Documents requirement to set IMAGE_SERVICE_BASE_URL.
Moves optional config section above the "run it" section.
/cc @
/cc @
> NO-ISSUE: updates docs for running with podman

- docs/user-guide/deploy-on-bare-metal.md
- Fix IPXE url
- Fix ignition extraction:
- Guess compression tool
- Use cpio so compacted jsons also work
- Improve scripts
- Use Rock Ridge extensions in isoinfo to directly use real filenames
- Change backticks to modern command substitution
- Add docker.io server to image names
- Only export variables if needed
/cc @
/cc @
> NO-ISSUE: Guess compression tool used and improve scripts

- OWNERS_ALIASES
> NO-ISSUE: Add @vrutkovs to OWNERS

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- subsystem/cluster_test.go
InstallHosts got deprecated in favor of V2InstallHost.
ResetCluster is replaced by V2ResetCluster.
/cc @
/cc @
> MGMT-9120: operationId Remove V1 InstallHosts, ResetCluster

- subsystem/image_test.go
This is a pre-requisite code for removing V1 RegisterCluster.
It changes the flow of the image_test suite to use V2RegisterCluster.
As a follow-up, it also generates the ISO via InfraEnv as mixing of V1 and V2 flows is not possible.
The coverage rate may drop due to this PR. However, this is only a temporary drop until the main PR is submitted with some code deletion on the BE.
/cc @
/cc @ …
> MGMT-9134: convert image_test to v2

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/migrations/20220221193600_change_static_config_format.go
- internal/migrations/20220221193600_change_static_config_format_test.go
- internal/migrations/migrations.go
- pkg/staticnetworkconfig/generator.go
- pkg/staticnetworkconfig/generator_test.go
- pkg/staticnetworkconfig/mock_generator.go
- subsystem/kubeapi_test.go
- Change the format of the field to JSON, with all effected locations
- Add migration from old format to new format.
> MGMT-9225: Change the format if field StaticNetworkConfig in infra-env to JSON

- docs/user-guide/rest-api-v1-v2-transition-guide.md
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- subsystem/cluster_test.go
- UploadHostLogs and DownloadHostLogs API endpoints return 404
- Adjust unit tests and subsystem tests
- [] None
/cc @
/cc @
> MGMT-9125: Remove V1 operationIds UploadHostLogs and DownloadHostLogs

- docs/hive-integration/kube-api-getting-started.md
> NO-ISSUE: Corrected indentation in example.

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- subsystem/day2_cluster_test.go
- subsystem/metrics_test.go
> MGMT-9132: Remove V1 operationId RegisterAddHostsCluster

- docs/user-guide/rest-api-v1-v2-transition-guide.md
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- subsystem/authz_test.go
- subsystem/cluster_test.go
- subsystem/kubeapi_test.go
> MGMT-9118: Remove V1 UploadClusterIngressCert, CompleteInstallation

- pkg/staticnetworkconfig/generator.go
- Before calling nmstatectl, file needs to be synced and closed to
verify that nmstatectl reads all the data that was wriiten to the file
/cc @carbonin 
> MGMT-9393: Close file before passing it to nmstatectl

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- subsystem/ams_subscriptions_test.go
- subsystem/authz_test.go
- subsystem/cluster_test.go
- subsystem/day2_cluster_test.go
- subsystem/ipv6_test.go
- subsystem/manifests_test.go
- subsystem/metrics_test.go
- subsystem/operators_test.go
- subsystem/utils_test.go
> MGMT-9111: Remove V1 operationId GetCluster, DeregisterCluster

- docs/user-guide/rest-api-v1-v2-transition-guide.md
- internal/operators/handler/handler.go
- pkg/staticnetworkconfig/generator.go
- subsystem/cluster_test.go
- subsystem/operators_test.go
- subsystem/utils_test.go
> MGMT-9130: Remove V1, ListOfClusterOperators, ReportMonitoredOperatorStatus, ListSupportedOperators, ListOperatorProperties

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/inventory_v2_handlers.go
- subsystem/authz_test.go
- subsystem/cluster_default_config_test.go
- subsystem/cluster_test.go
- subsystem/day2_cluster_test.go
- subsystem/utils_test.go
> MGMT-9376: Remove V1 ListClusters, DownloadClusterFiles, GetClusterDefaultConfig, ResetHost

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/inventory_v2_handlers.go
- internal/bminventory/mock_installer_internal.go
- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/mock_cluster_api.go
- internal/cluster/registrar.go
- internal/cluster/registrar_test.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
Remove v1 flags in RegisterCluster APIs throughout the code
and adjust the tests
/cc @
/cc @
> MGMT-9109: v1 RegisterCluster cleanup

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
> MGMT-9126: Remove V1 GetHostIgnition, UpdateHostIgnition, DownloadHostIgnition

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- subsystem/authz_test.go
> MGMT-9108: Remove V1 GetPresignedForClusterFiles (GET)
