openshift/assisted-service

internal/host/host.go
internal/metrics/metricsManager.go
subsystem/metrics_test.go

When capturing the connectivity report metrics, the method used to process the information contains the new report metrics, but the code inside discards it in favor of the old information in the host structure. This causes errors the first time the code runs, as there is no data available in the host to process.
/cc @gamli75 

Bug 1985449: Use report variable for unmarshaling

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/host/validator.go
subsystem/kubeapi_test.go

Day2 hosts should not be validated for:
- `hasSufficientNetworkLatencyRequirementForRole`
- `hasSufficientPacketLossRequirementForRole`
Additionaly, `InstallSingleDay2HostInternal` should not call `setMajorityGroupForCluster`.
/cc @filanov 

MGMT-7424: Remove undeeded network validations for day2 hosts

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

The previous code was trying to create spoke resources such as BMH, machine, secret, in the same namespace on the spoke cluster as in the hub cluster i.e. assisted-spoke-cluster namespace. This namespace is not present on the spoke cluster and results in a failure while creating a spoke BMH (surely we can create the namespace but we shouldn't).
This change fixes this bug and correctly creates the resources such as spoke BMH, and spoke machine on the spoke cluster when adding workers on day2. Use "openshift-machine-api" namespace just like the other master agent/BMH/machines on the spoke cluster. 
Create OCP cluster using dev-scripts. Deploy assisted service operator and deploy spoke cluster. Create a BMH on the hub cluster with worker role on a day2 cluster.  Spoke BMH should be created …

OCPBUGSM-32618: Create worker's spoke machines in the "openshift-machine-api" namespace

---

deploy/operator/ztp/deploy_spoke_cluster.sh

Waiting for 1.5 hours, to have a chance to get to actual timeout of installation in case of a failure.
/cc @YuviGold 
/cc @ybettan 
/hold

wait 1.5 hours for installation

---

deploy/operator/ztp/deploy_spoke_cluster.sh

We right now just waiting for "completed" event to be true. In case of an early failure, we will spend too much time waiting for something that will never be true.
/cc @filanov 
/cc @YuviGold 

Wait for the 'stopped' condition to save time on early failure

---

subsystem/kubeapi_test.go

KubeAPI subsystem cleanUpCRs to assert via Eventually
/cc @YuviGold 
/cc @

NO-ISSUE: KubeAPI subsystem cleanUpCRs to assert via Eventually

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

- Make the verification during update-cluster only if at least one of the CIDRs was part of the update
/cc @avishayt 

MGMT-7445: During update-cluster CIDRs are checked for overlap even if they were not provided as part of the update

---

deploy/operator/ztp/assisted-installer-crds-playbook.yaml
deploy/operator/ztp/baremetalHost.j2
deploy/operator/ztp/deploy_spoke_cluster.sh

Currently the ZTP script only pulls info on the first host. This will update it to add all the baremetal hosts defined in the `extra_baremetalhosts.json` created by dev-scripts.
/cc @YuviGold 
/cc @osherdp 
/cc @djzager 

MGMT-6735: Update ZTP script to allow for multiple baremetal hosts

---

internal/cluster/cluster.go
internal/common/db.go
internal/common/monitor_query_generator.go
internal/host/host.go
internal/host/hostutil/test_utils.go
internal/host/monitor.go
internal/host/monitor_test.go
internal/host/validator.go

- Change selective monitoring to support infra-envs in addition to clusters
- Change host monitoring to monitor by infra-envs in addition to clusters
/cc @ravidbro 

MGMT-7427: Add support for hosts that do not belong to cluster in host monitoring

---

cmd/main.go
internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
internal/controller/controllers/common.go

The internal cache now filters out secrets without the AI custom label "agent-install.openshift.io/watch": "true". Secrets are retrieved using the non-caching client if it fails to find the Secret in the current cache.
This is a combined fix for [OCPBUGSM-32941](https://issues.redhat.com/browse/OCPBUGSM-32941) and [OCPBUGSM-32966](https://issues.redhat.com/browse/OCPBUGSM-32966). 
Without this fix, the BMAC and ClusterDeployment controllers can't find the required secrets even if they are actually present.
Ref: 
https://issues.redhat.com/browse/OCPBUGSM-32941
https://issues.redhat.com/browse/OCPBUGSM-32966
/cc @
/cc @ …

OCPBUGSM-32941: Cache secrets for spoke cluster

---

internal/bminventory/inventory.go
internal/cluster/cluster.go
pkg/auth/authz_handler_test.go
restapi/embedded_spec.go
subsystem/authz_test.go
swagger.yaml

Files that only cluster owners can download:
- kubeconfig
- kubeconfig-noingress
- kubeadmin-password
---
- Updated swagger security for endpoint `/v1/clusters/{cluster_id}/downloads/kubeconfig`
- Added logic in `/v1/clusters/{cluster_id}/downloads/files` handler
- Added subsystem tests to check file accessibility
/cc @avishayt 
/cc @YuviGold 

MGMT-7475: allow only cluster owners to download sensitive files.

---

deploy/operator/ztp/deploy_spoke_cluster.sh

Currently, the deploy script overrides the SPOKE_INGRESS_VIP and SPOKE_API_VIP. This PR
re-uses the values if they have been set.
/cc @lranjbar 
/cc @YuviGold 

NO-ISSUE: Use variables from env if set

---

internal/bminventory/inventory.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
subsystem/kubeapi_test.go

ClusterDeployments controller will now use the internal transform API
to change a cluster from day1 to day2.
/cc @filanov 

MGMT-7220: CD controller to transform day1 cluster to day2 

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
models/disk.go
restapi/embedded_spec.go
swagger.yaml

Avoid formatting of USB and SD cards that suppose to belong
to the users and should be controlled by them
Avoid formatting mmblk devices (NVIDIA servers case where such
a device was part of the server infrastructure
/assign @avishayt 
/assign @omertuc 

MGMT-7443: skip removable disks format

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

BMAC currently sets the BMH's hostname to the value inspected by the agent. However, this is not necessarily
the final desired valueas the bmac.agent-install.openshift.io/hostname annotation could've been set.
Use the value from the annotation if present. Otherwise, use the one from the agent's inventory
I also manually set the `hardwaredetails` for an BMH in an existing cluster. Doing this resulted in the `Machine` resource getting the right hostname in the status, and eventually the CSR being approved:
Machine:
CSR:
Note that the above also depends on #2325 …

OCPBUGSM-31544: Set the BMH's hostname to the desired value

---

Makefile
subsystem/image_test.go

Deploy only the default version as defined on the OPENSHIFT_VERSIONS
json when deploying locally.
When deploying from the CI - deploy all the supported versions.
/cc @omertuc
/cc @filanov 

NO-ISSUE: Deploy multiple versions on CI only

---

internal/network/connectivity_groups.go

This PR changes the IPv4 and IPv6 constants used for parsing the routing information coming from the agent, to use golang's unix constant `AF_INET` and `AF_INET6` for IPv4 and IPv6 respectively. This PR follows up on the [agent's side](https://github.com/openshift/assisted-installer-agent/pull/222), where the usage of the incorrect value causes the agent to be unable to filter out the routing information specific for IPv4 and IPv6, effectively duplicating the resulting values as the underlying library is unable to identify which protocol to filter for (because it expects `AF_INET` or `AF_INET6`) and it returns all entries on each call. 
/assign @ori-amizur 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-req …

Bug 1994060: Change IP version to golang's unix constant

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

Previously it was impossible to download sensitive cluster files when
using "none" auth type because we were unconditionally checking the user
name in the context, but that is only being set when we use rhsso auth.
https://issues.redhat.com/browse/MGMT-7567
Unit tests
/cc @sagidayan 
/cc @avishayt 

MGMT-7567 Check cluster owner for file downloads only with rhsso auth

---

internal/host/host.go
internal/host/hostutil/host_utils.go
internal/host/transition.go

Since https://github.com/openshift/assisted-service/pull/2343 was merged reboot timeout leads to installing-pending-user-action status
So now that the timeout during reboot no longer fails the installation we can lower it to 40 minutes.
- Is this PR relying on CI for an e2e test run? yes for regression
-->
/cc @avishayt 
/cc @tsorya 
- [ x Relevant issues have been associated (see [CONTRIBUTING] guide) …

MGMT-5443: Reduced reboot timeout to 40 minutes

---

pkg/auth/authz_handler_test.go
restapi/embedded_spec.go
subsystem/authz_test.go
swagger.yaml

Cluster credentials should be accessible only for cluster owner.
Updated swagger security for endpoint /v1/clusters/{cluster_id}/credentials
/cc @avishayt 
/cc @

MGMT-7564: cluster credentials only for cluster owner

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/host/hostcommands/container_image_availability_cmd.go
internal/host/hostcommands/container_image_availability_cmd_test.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/hostcommands/instruction_manager_test.go
internal/versions/mock_versions.go
internal/versions/versions.go
internal/versions/versions_test.go

In order to simplify the Versions API and avoid code duplication, removed the GetReleaseImage and GetReleaseVersion functions. Instead, a single func (GetOpenshiftVersion) that returns the entire OpenshiftVersion struct should be used.
That way, extending the struct with additional fields should be easier, as the validation code is encapsulated in one place.
Just an internal code-change.
Added relevant unit-tests.
/cc @YuviGold 
/cc @filanov 
/cc @osherdp 

MGMT-7569: remove release getters from Versions

---

internal/bminventory/inventory.go
internal/host/host.go
internal/host/host_test.go

In case the event being raised is a host event (hostID != nil )
then the clusterID param should contain InfraEnvID of the host.
This is a temp solution until we have a complete solution for
event generation with late-binding
/cc @
/cc @

MGMT-7583: AddEvent function should be used with InfraEnvID

---

api/hiveextension/v1beta1/agentclusterinstall_types.go
config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
config/crd/resources.yaml
deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml

This PR changes the definition of the ACI CR so that clusterNetwork,
serviceNetwork and machineNetwork accept unlimited number of entries.
Contributes-to: [MGMT-7315](https://issues.redhat.com/browse/MGMT-7315)
/cc @
/cc @

MGMT-7315: Make ACI CR accept multiple subnets

---

Makefile
cmd/main.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
tools/deploy_assisted_installer_configmap.py

This feature should always be enabled.
Once a day1 cluster finished the installation process successfully,
The clusterDeployments controller will invoke an internal API to transform
that cluster into a day2 cluster.
/cc @
/cc @

MGMT-7497: Remove KubeAPI EnableDay2Cluster flag

---

internal/ignition/ignition.go
internal/ignition/ignition_test.go

Add context to internal functions in order to log everything with the
same request id, it will be used to search the logs and see the output
of the failure.
Installer output can be long so we will not return it in the api.
/cc @osherdp 
/cc @tsorya 

MGMT-7600 log ignition generator user request id from the api

---

internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/common.go
internal/cluster/registrar.go
internal/cluster/registrar_test.go
internal/common/db.go
subsystem/utils_test.go

Delete `ClusterNetwork`, `ServiceNetwork`, and `MachineNetwork` models on
cluster deletion.
- `DeregisterCluster` - Triggered by the user owner when he deletes the cluster.
- `PermanentClustersDeletion` - Triggered by a cron job deleting idle clusters.
- `clearDB` - Subsystem teardown utility to start tests from scratch.
/cc @filanov 

MGMT 4321: delete networks records on deletion

---

docs/hive-integration/crds/agentClusterInstall-dualstack-SNO.yaml
docs/hive-integration/crds/agentClusterInstall-dualstack.yaml

This PR creates a sample AgentClusterInstall manifests for OCP
installation using dual-stack. ACI for SNO cluster provides
required clusterNetwork, machineNetwork and serviceNetwork whereas the
ACI for the multi-node cluster provides clusterNetwork and
serviceNetwork, as machineNetwork values are calculated automatically by
the assisted-service.
Contributes-to: [MGMT-6670](https://issues.redhat.com/browse/MGMT-6670)
/cc @
/cc @

MGMT-6670: Create sample ACI manifests for dual-stack OCP

---

internal/bminventory/inventory.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/common.go
internal/cluster/validator.go
internal/host/validator.go
internal/installcfg/installcfg_test.go
internal/network/machine_network_cidr.go
internal/network/machine_network_cidr_test.go
internal/network/utils.go

This PR creates a getter function that returns a CIDR for respective
Machine Network based on its id.
Contributes-to: [MGMT-6670](https://issues.redhat.com/browse/MGMT-6670)
/cc @YuviGold 
/cc @

MGMT-6670: Create a getter for Machine Network CIDR

---

data/events.yaml
internal/common/events/events.go
internal/controller/controllers/controller_event_wrapper.go
internal/controller/controllers/controller_event_wrapper_test.go

Bug fix in `controller_event_wrapper.go` file, where the functions `SendClusterEvent` and `SendHostEvent` should notify kube-api according to the event type.
This PR continues #1854
/cc @masayag 
/cc @filanov 

MGMT-7588: Fix event wrapper to notify kube-api

---

deploy/operator/ztp/agentClusterInstall.j2
deploy/operator/ztp/clusterDeployment.j2

Set machine network only in case of SNO. Remove unused VIPs from cluster deployment. Setting machine network when deploying multi-node cluster results in the below error- 
> [root@hardprov-fx2-21 ~]# oc get aci assisted-agent-cluster-install -n assisted-spoke-cluster  -o=jsonpath='{range .status.conditions[*]}{.type}{"\t"}{.status}{"\t"}{.reason}{"\t"}{.message}{"\n"}{end}'
SpecSynced	False	InputError	The Spec could not be synced due to an input error: Setting Machine network CIDR is forbidden when cluster is not in vip-dhcp-allocation mode
RequirementsMet	False	ClusterNotReady	The cluster is not ready to begin the installation
Validated	False	ValidationsUserPending	The cluster's validations are pending for user: The API virtual IP is undefined and must be provided.,The API virtual IP is …

NO-ISSUE: Set machine network only in case of SNO. Remove unused VIPs from cluster deployment.

---

restapi/embedded_spec.go
swagger.yaml

Seems like we're offering false-advice in our examples as for how to override OVNKubernetes via install-config override mechanism.
Changing example from using ``OVN-Kubernetes`` to ``OVNKubernetes``.
/cc @tsorya  
/cc @oshercc 

NO-ISSUE: fix typo in overriding OVNKubernetes via install-config

---

internal/installcfg/installcfg.go
internal/installcfg/installcfg_test.go
internal/network/machine_network_cidr.go

This PR changes the logic of install-config.yaml generation regarding
the machine networks. Till now we have been always passing only single
IPv4 subnet (coming either from the cluster parameters or discovered
from the bootstrap host).
With this change the logic is as follows
* if cluster params contains multiple machine networks, we pass them all
to the installcfg structure
* if cluster params do not have any machine networks, we generate them
from the cluster's bootstrap node's inventory; we pick at most one
IPv4 network and at most one IPv6 network
Contributes-to: [MGMT-7464](https://issues.redhat.com/browse/MGMT-7464)
/cc @YuviGold 
/cc @flaper87 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message …

MGMT-7464: Pass multiple machine networks to install-config.yaml

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

V2GetHost parameters should now include InfraEnvId and HostID
instead of ClusterID and HostID
/cc @
/cc @

MGMT-7638: implement V2 Get Host API

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster_test.go
internal/cluster/common.go

This PR adds a backwards compatibility for retrieving network
configuration using the old data structures
* MachineNetworkCidr
* ClusterNetworkCidr
* ServiceNetworkCidr
This works in a way that whenever the new structures are assigned, their
respective values are replicated to the old ones.
Please note, it is not possible to write using old structures as they
are not forward-synchronized.
Contributes-to: [MGMT-7498](https://issues.redhat.com/browse/MGMT-7498)
/cc @YuviGold 
/cc @flaper87 

MGMT-7498: Add backwards compatibility for network configuration

---

internal/common/test_configuration.go
internal/constants/files.go
internal/host/hostcommands/domain_name_resolution_cmd.go
internal/host/refresh_status_preprocessor.go
internal/host/statemachine.go
internal/host/transition_test.go
internal/host/validation_id.go
internal/host/validator.go
models/host_validation_id.go
restapi/embedded_spec.go
subsystem/ams_subscriptions_test.go
subsystem/authz_test.go
subsystem/cluster_test.go
subsystem/day2_cluster_test.go
subsystem/kubeapi_test.go
subsystem/manifests_test.go
subsystem/metrics_test.go
subsystem/operators_test.go
subsystem/utils_test.go
swagger.yaml

Add new validation that checks if the host has DNS wildcard entry for
*.cluster_name.base_dns_domain_name
If a wildcard was configured in the cluster network
it will cause insight pods to fail report to cloud.redhat.com
And cluster version will complain about the insight operator's degraded status.
By testing domain name resolution for a non-existing domain name under 
cluster_name.base_dns_domain_name we can determine if wildcard was
configured and alert the user accordingly.
/cc @tsorya 
/cc @omertuc 
/cc @eranco74

MGMT-6911: Validate that DNS wildcard entry is not configured.

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/common/common.go
internal/common/db.go
internal/common/test_configuration.go
internal/host/hostcommands/container_image_availability_cmd.go
internal/host/hostcommands/container_image_availability_cmd_test.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/hostcommands/instruction_manager_test.go
internal/versions/mock_versions.go
internal/versions/versions.go
internal/versions/versions_test.go
models/cluster.go
models/cluster_create_params.go
models/infra_env.go
models/infra_env_create_params.go
restapi/embedded_spec.go
swagger.yaml

As a preparation to support arm64 CPU architecture, introduced the following changes:
-  swagger: Added a 'cpu_architecture' property to the following objects:
- cluster/cluster-create-params
- infra-env/infra-env-create-params
-  Added cpuArchitecture to GetOpenshiftVersion func in versions:
- Try to fetch a release image url and version from ReleaseImages list according to the requested CPU architecture.
- An empty cpu_architecture implies the default x86_64.
- When registering a new cluster, set CPUArchitecture according to parms.
- Validate by fetching available architectures (versions -> GetCPUArchitectures). 
- Notes:
- Day2 flow supports only x86_64 for now.
- Will be updated in following PRs: handle_ocp_versions.py/generate ISO flow/upload ISO flow.
- This PR is based on changes …

MGMT-7114: support CPUArchitecture in Cluster

---

internal/migrations/20210713123129_populate_infra_env.go
internal/migrations/20210822134659_multiple_networks.go
internal/migrations/20210822134659_multiple_networks_test.go
internal/migrations/migrations.go
tools/migration_generator/migration_generator.go

Add a migration to switch from a single CIDR values to multiple subnets arrays.
Only in case there are values for `ClusterNetworkCIDR`,
`ServiceNetworkCidr`, and `MachineNetworkCIDR` - The `ClusterNetworks`,
`ServiceNetworks`, and `MachineNetworks` arrays would create accordingly.
/cc @filanov 
/cc @gamli75 

MGMT-7498: Migrate multiple networks

---

internal/cluster/common.go

In parallel we run the monitoring loop.
The loop tries to auto-assign the machine cidr  every interval.
The functionality is on `UpdateMachineCidr`.
Previously, when you changed from X value to X value you couldn't sense any change.
But now, we delete previous machine networks records.
So we fail on the gap between the deletion and the insertion of the new auto-assigned value.
The solution for that would be to make it all as a transaction.
Then, the DB would get locked until the deletion and the insertion is finished,
and any other process won't be able to fail on the gap between them. …

MGMT-4321: Bugfix flaky auto assign DHCP machine cidr

---

restapi/embedded_spec.go
swagger.yaml

UI don't use that API anymore and uses
/v1/clusters/{cluster_id}/preflight-requirements instead.
In addition we have only 2 hits on that API in prod so users doesn't
seems to use it either.
/cc @
/cc @

NO-ISSUE: Deprecating /v1/clusters/{cluster_id}/host-requirements API.

---

cmd/main.go
internal/assistedserviceiso/assistedserviceiso_api.go
internal/assistedserviceiso/assistedserviceiso_api_test.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/versions/mock_versions.go
internal/versions/versions.go
internal/versions/versions_test.go
pkg/s3wrapper/client.go
pkg/s3wrapper/client_test.go
pkg/s3wrapper/filesystem.go
pkg/s3wrapper/filesystem_test.go
pkg/s3wrapper/mock_s3wrapper.go
pkg/s3wrapper/util_test.go

- Added CPU architecture postfix to the rhcos object templates for supporting multiple architectures for each version:
- E.g. rhcos-48.84.202107202156-0-x86_64
- Added cpuArchitecture to GetOsImage signature for filtering images according to the specified architecture.
- On service startup, upload OS images of all available CPU architectures.
- GenerateClusterISO should support available architectures by using a base image with the appropriate architecture.
As this PR is adding an infrastructure for later arm64 support, no substantial impact in behaviour should occur. I.e. added tests should cover the changes. The major internal change is the addition of cpu architecture suffix for the base images.
/cc @YuviGold
/cc @carbonin 
/cc @filanov
/cc @osherdp  …

MGMT-7187: support multiple architectures in uploadISOs

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/oc/release.go
pkg/generator/generator.go

- Validate UserManagedNetworking on UpdateCluster:
- Prohibit disabling for a cluster with non-x86 CPU architecture.
- Simplify platform type indication in installGenerator:
- Use none platform openshift-install binary for enabled UserManagedNetworking.
/cc @eranco74 
/cc @filanov
/cc @rollandf 
/cc @YuviGold 

MGMT-7484: validate UserManagedNetworking for non-default arch cluster

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

This PR fixes the validation of VIP DHCP allocation in case multiple
Machine Networks are provided.
Given that we currently allow only single address for API and Ingress
VIPs, it does not make sense to perform a validation against all the
machine networks, but only against the first one (i.e. the one from
which the VIPs must be coming).
Contributes-to: [MGMT-6898](https://issues.redhat.com/browse/MGMT-6898)
For the request
```
--data '{"machine_networks": [{"cidr":"192.168.145.0/24","cluster_id":"82b8c284-8024-4a30-9bef-4b5a8180061b"},{"cidr": "1001:db8::/120","cluster_id":"82b8c284-8024-4a30-9bef-4b5a8180061b"}]}' -H "content-type: application/json" --request PATCH
```
the cluster looks as follows
```
"machine_network_cidr": "192.168.145.0/24",
"machine_networks": [
{
"cidr": …
```

MGMT-6898: Fix MachineNetworks validation for multi-network setup

---

api/v1beta1/agentserviceconfig_types.go
config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
config/crd/resources.yaml
config/manager/manager.yaml
deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
hack/generate.sh
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/images.go

- Added getOSImages func to AgentServiceConfigReconciler:
- Converts the specified OSImages array in spec to a json string for using as OS_IMAGES env var.
- Fallback to specified OS_IMAGES var if not available in spec.
- Modified generate.sh script:
- Added relevant OS images to manager.yaml.
- Used OS_IMAGES for the sample AgentServiceConfig file (instead of OPENSHIFT_VERSIONS).
/cc @djzager 
/cc @filanov 
/cc @sagidayan 
/cc @rollandf 

MGMT-7479: support OS_IMAGES in AgentServiceConfig

---

internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go
internal/network/manifests_generator.go
internal/network/manifests_generator_test.go
models/disk_encryption.go
restapi/embedded_spec.go
subsystem/manifests_test.go
swagger.yaml

Added default values to 'mode' and 'enable_on' properties in
disk-encryption.
This makes the code simpler as we can always assume that the values of
those properties are always one of the enum possibilities (and not empty).
/cc @
/cc @

NO-ISSUE: Fixing disk-encryption definition in swagger.yaml.

---

internal/bminventory/inventory_test.go
internal/cluster/cluster.go

Downloading the kubeconfig-noingress should be allowed in case the cluster is "Installing pending user action".
This is required by assisted-test-infra in order to get the must-gather logs when the installation hangs
/cc @tsorya 
/cc @YuviGold 

MGMT-7714: Allow downloading kubeconfig-noingress while cluster is "Installing pending user action"

---

hack/setup_env.sh

Sometimes we fail on Version v4.2.0 does not exist, which actually means we hit rate-limiter of GitHub. For example:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/2510/pull-ci-openshift-assisted-service-master-lint/1432667157698711552
This will use non-limited APIs of GitHub, and will allow us to workaround this issue.
/cc @YuviGold 

NO-ISSUE: downloading kustomize release directly to handle rate-limiters

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/common_test.go
internal/cluster/validator.go
internal/common/common.go
internal/controller/controllers/clusterdeployments_controller.go
internal/network/utils.go

This PR fixes handling of Machine, Cluster and Service Networks when
the value passed is a non-empty array with empty objects.
The current assumption that the MachineNetworks (or other) variable is
either empty or contains a valid set of CIDRs is incorrect, as it has
been discovered that the following requests arrive to the service
```
--data '{"machine_networks": [{}]}'
```
Those should be rather arriving as
```
--data '{"machine_networks": []}'
```
but in order to handle all the possibilities, we add a scenario for the
former in this change.
Contributes-to: [MGMT-6670](https://issues.redhat.com/browse/MGMT-6670)
/cc @YuviGold 
/cc @flaper87 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guideli …

MGMT-6670: Fix handling of empty network in various network params

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/host/common.go
internal/host/host.go
internal/host/host_test.go
internal/host/mock_host_api.go
internal/usage/consts.go
models/host.go
restapi/embedded_spec.go
subsystem/cluster_test.go
swagger.yaml

Assisted Pull Request
First phase of early auto assign implementation:
1. add suggested-role field to host
2. whenever AutoAssignRole is called, first fill the suggested role
for hosts in auto-assign and then assign the host role from the
suggested field
3. report usage when auto selection is done and there is a real
choice (i.e. more than 3 nodes are involved)
In the next phases the suggested-role will be calculated in the
monitor and AutoAssignRole would just use that recommendation
without calling it directly
/cc @
/cc @

MGMT-4475: add suggested-role

---

internal/host/host.go
internal/host/statemachine.go
internal/host/transition.go

The progress stage for day2 hosts was kept as Rebooting, even after it had been
added to the host. Let's make sure the stage transitions to Done so that it reflects
the actual phase of the installation and the progress of the agent
With the current code, this is what the host record in the DB looks like after a successful deployment of a day2 host:
```
installer=# select id, cluster_id, status, status_info, progress_current_stage, progress_progress_info from hosts where id='068e58b1-5f2d-4392-b800-271023b31f26';
id                  |              cluster_id              |          status           | status_info | progress_current_stage | progress_progress_info
--------------------------------------+--------------------------------------+---------------------------+-------------+----------- …
```

OCPBUGSM-34158: Transition day2 hosts to Done

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/bmh_agent_controller.go

commit 6da57ff459b363fcf052db5cef93a77d9949fe84:
Bug 2000612: Use the agent's inventory hostname as the source for BMH's hostname
The hostname was not being set in the BMH's hardware details when the
hostname annotation was not used. This is because the reconcile step was
using agent.Spec.Hostname as the source of hostname rather than the
inventory. The former is latter set (after inspection) while the former
is only set when the annotation is set
commit 3e5e0331c0409ca6f444f9629153f6dbee07ea23
Bug 2000614: Handle HostStatusAddedToHost status when reconciling agent
This will set the agent condition as Installed for the Agent CR when the agent resource reaches
the added-to-host status
/cc …

MGMT-4505 Fixes RWN creation when no hostname annotation is passed

---

tools/ocp_version_update/update_default_release_versions_to_latest.py

Clone the assisted-service repo before making changes to the json files.
/cc @oshercc 

MGMT-7568: ocp_version_update - clone repo before updates

---

internal/bminventory/inventory.go
internal/usage/consts.go
subsystem/cluster_test.go

Have a separate line in feature usage table for OVN-based clusters vs. SDN
/cc @
/cc @

NO-ISSUE: report OVN and SDN nw types separately

---

internal/host/hostcommands/instruction_manager.go
internal/host/hostcommands/instruction_manager_test.go
restapi/embedded_spec.go
subsystem/host_v2_test.go
subsystem/utils_test.go
swagger.yaml

Once Bind command isssued, the host moves to Binding state and its ClusterID is set
to the target cluster. So, from instruction manager POV this host is now bound host and
not unbound host. The fix is to move binding instuction from unboind host instruction manager
commands set, to the bound host instruction manager command set.
In addition fixing the security definitions for Bind (adn unbind) command. It should be user
auth, and not agent auth
/cc @
/cc @

MGMT-7742: Fixing host getting stuck in "binding" state

---

internal/host/pool_host_statemachine.go
internal/host/statemachine.go
internal/host/transition_test.go

The fix is in statemachine. Once UnbindHost API succeeds, host becomes unbound.
So we need to update pool_host_statemachine to include Unbinding state for
RegisterHostTransaction
/cc @
/cc @

MGMT-7751: fix unbound host not reaching discovering-unbound state

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/common.go
internal/cluster/common_test.go
internal/cluster/validator.go
internal/common/common.go
internal/controller/controllers/clusterdeployments_controller.go
internal/network/utils.go

Rebased on top of https://github.com/openshift/assisted-service/pull/2553.
This PR adds backwards compatibility for the network configuration. Specifically, it cherry-picks 3 PRs:
* https://github.com/openshift/assisted-service/pull/2455
* https://github.com/openshift/assisted-service/pull/2485
* https://github.com/openshift/assisted-service/pull/2512
/cc @flaper87 
/cc @gamli75 

Backwards backport of backward compatibility work

---

docs/dev/migrations.md

This PR changes the wording in the `preMigration` docs. The documentation could be more extensive so I'm happy to incorporate suggestions from other folks.
Addresses comment from: https://github.com/openshift/assisted-service/pull/2536#discussion_r701591290
/cc @carbonin 

NO-ISSUE: Change wording for the preMigration section in docs

---

deploy/operator/common.sh

Updating '4.8' key since ocp 4.9 has been recently added to default_ocp_versions and we use 'max' release image in [common.sh](https://github.com/openshift/assisted-service/blob/7bc89fcbdb3cd412e40df1dc74a520f1a5bd5399/deploy/operator/common.sh#L31).
Note: the script should be refactored to use OS_IMAGES/RELEASE_IMAGES - will be handled as part of MGMT-7705.
/cc @YuviGold 
/cc @osherdp
/cc @filanov 

MGMT-7643: update ocp to 4.9 in operator/common

---

internal/host/common.go
internal/host/host.go
internal/host/host_test.go
internal/host/hostrole_test.go
internal/host/hostutil/test_utils.go
internal/host/validations_test.go

Add calculation of suggested role in host monitor
This is Phase II of auto assign role feature. In Phase III
the assignment in Install will be removed and a validation
added instead 
/cc @
/cc @

MGMT-4475: suggested role in monitor

---

internal/isoutil/isoutil.go

As the aarch64 rhcos image[*] contains a single boot image (efiboot.img),
added a proper support to isoutil for creating an ISO with only that boot platform.
This should facilitate the creation of a minimal ISO template for arm64 CPU architecture.
Note: the logic should later be cherry-picked to assisted-image-service:
https://github.com/openshift/assisted-image-service/blob/main/pkg/isoeditor/isoutil.go
[*] https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/pre-release/4.9.0-fc.1/rhcos-4.9.0-fc.1-aarch64-live.aarch64.iso
/cc @carbonin 
/cc @omertuc 
/cc @filanov  …

MGMT-7754: Support iso creation with EFI boot only

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go

This PR adds more validations when setting parameters configuring disk
encryption. It ensures that whenever the user enables encryption the
mode is also being set, as well as ensures that disabling the encryption
must not contain an encryption mode in the payload.
Closes: [OCPBUGSM-34496](https://issues.redhat.com/browse/OCPBUGSM-34496)
/cc @carbonin 

Bug 2001973: Add more validations for Disk Encryption settings

---

internal/host/host.go
internal/host/host_test.go
internal/host/transition.go
internal/host/transition_test.go

Host kind is set during Register operation. In case host already exists in DB,
the value stored in the DB is the one that is stored after register. Since host can be bound
to day2 cluster, unbound abd then bound again to day1 cluster we need to reset during unbind
operation. We also need to set the Kind based on the cluster, which is set during Register.
We must propagate this value into the host already stored on DB
/cc @
/cc @

MGMT-7768: Handle Host's Kind field during bind/unbind/register

---

internal/host/validator.go

[MGMT-7395](https://issues.redhat.com/browse/MGMT-7395): Improve error messages for DNS validations
The current implementation of the error messages is too generic, it needs to include
some additional data for each case to help the user configure the correct DNS entries.
/cc @avishayt 
/cc @eranco74 
/cc @nirfarkas

MGMT-7395: Improve error messages for DNS validations

---

internal/bminventory/inventory.go
internal/bminventory/mock_installer_internal.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go

Updates:
- UpdateClusterNonInteractive
- DownloadClusterFilesInternal to V2DownloadClusterCredentials. Not using v2DownloadClusterFilesInternal
since the controller used the v1 DownloadClusterFilesInternal for kubeconfig.
/cc @filanov 
/cc @rollandf 

MGMT-7633: Update CD controller to use V2 API

---

internal/host/host.go

add operators host criteria to canBeMaster. Now it also takes into account the operator's ValidateHost() results
/cc @
/cc @

MGMT-4475: add operators host criteria to canBeMaster

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/validations/validation_test.go
internal/cluster/validations/validations.go

This PR contains two commits modifying network validators for a better support of dual-stack installations
* IPv4 must be the first subnet in case of dual-stack setup
* In non-IPv6 setups IPv6-only clusters are forbidden, but dual-stack are valid
Contributes-to: MGMT-4321
/cc @YuviGold 
/cc @flaper87 

MGMT-4321: Extend network validators for dual-stack support

---

Makefile
cmd/main.go
go.mod
go.sum
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/mock_installer_internal.go
internal/common/test_configuration.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
internal/host/hostcommands/container_image_availability_cmd.go
internal/host/hostcommands/container_image_availability_cmd_test.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/hostcommands/instruction_manager_test.go
internal/oc/mock_release.go
internal/oc/release.go
internal/oc/release_test.go
internal/versions/mock_versions.go
internal/versions/versions.go
internal/versions/versions_test.go

In order to support kube-api flow with a specified list of OS images only
(instead of RHCOS images info in OpenshiftVersions), made the following changes:
* Refactor AddOpenshiftVersion to AddReleaseImage:
* Create/update ReleaseImage entity according to the specified image URL.
* Keeping backwards compatibility by using GetOsImage (which fallbacks to OpenshiftVersions map).
* Still updating DisplayName and SupportLevel in OpenshiftVersions.
* Refactor GetOpenshiftVersion to GetReleaseImage:
* Similar to GetOsImage, should return a ReleaseImage according to a specified openshift version.
* Fallback to fetching info from OpenshiftVersions.
* Added GetOpenshiftVersions func:
* Returns available versions by specified OS images.
* Fallback to the keys of OpenshiftVersions.
* Added …

MGMT-7785: support AddReleaseImage in Versions

---

Makefile

This is to fix the breaking changes from the PR: https://github.com/openshift/assisted-service/pull/2451
Not sure if the bundle build commands were tested with this changes.
There was an attempt to see if operator-framework worked with podman-remote: https://github.com/openshift/assisted-service/pull/2596
Operator framework doesn't to support podman-remote as we are still seeing the following error:
```
13:35:43  opm index add --bundles quay.io/****/****-service-operator-bundle:5600072078a351bc9bf595bb4aa10cea780d39f6 --tag quay.io/****/****-service-index:jenkins-****-service-master-11370 --container-tool podman-remote
13:35:43  INFO[0000] building the index                            bundles="[quay.io/****/****-service-operator-bundle:5600072078a351bc9bf595bb4aa10cea780d39f6]"
13:35:44 …
```

Update operator-index-build to use podman fixing broken Jenkins builds

---

internal/host/statemachine.go
internal/host/transition.go
internal/host/transition_test.go

The following fields will be resetted upon unbinding:
cluster_id, kind, connectivity, domain_name_resolutions,
free_addresses, images_status, installation_disk_id,
installation_disk_path, machine_config_pool_name,
role, api_vip_connectivity, suggested_role
/cc @
/cc @

MGMT-7796: reset host data, set by the cluster on unbind operation

---

cmd/main.go
internal/cluster/cluster.go
openshift/template.yaml
pkg/app/middleware.go
pkg/commonutils/common_utils.go
pkg/thread/thread.go

The assisted-installer cluster-monitor seems to hang for hours from time to time, whenever it hangs clusters dont' get updated by the monitor.
This cause few issues, that lead to installation failures (mainly we've seen clusters stuck in timeout while preparing for installaiton until they timeout).
Adding last run timestamp to each thread object that will run monitor.
Updated liveness probe to watch the last run timestamp with 5 minutes timeout
Adding logs around cluster monitor in order to see what takes so long.
- Is this PR relying on CI for an e2e test run? For regression
This PR was tested using this …

MGMT-7804: Create healthchecks for monitoring routines

---

internal/bminventory/inventory.go
internal/common/common.go
internal/host/host.go
internal/host/hostcommands/instruction_manager.go
internal/host/hostcommands/instruction_manager_test.go
internal/host/hostcommands/ntp_synchronizer_cmd.go
internal/host/pool_host_statemachine.go
internal/host/transition_test.go
internal/host/validator.go

- Make NTP sources be extracted from AdditionalNtpSources in ifra-env for NtpSynchronizer step if such sources fo not exist for cluster.
This applies also to unbound states.
- Extract NTP sources from all infra-envs of cluster, if the cluster does not have its own NTP sources.

MGMT-7728: Add NTP configuration to ISO

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

The agent has two fields for the Hostname: Spec.Hostname and
Status.Inventory.Hostname.
The former is the one provided to the agent, the desired hostname. The
latter is the hostname discovered. The discovered hostname is sent
*before* the node's hostname is set. Relying solely on the discovered
hostname may cause inconsistencies when the desired hostname is
different from the discovered one.
Use the desired hostname (assuming the agent will succeed when setting
it) if present, otherwise rely on the discovered one.
Test based on unit-test and in @alknopfler environment
/cc @djzager 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message …

OCPBUGSM-34323: Use the hostname in the Spec if present

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go

Reference the object in the array rather than the reference in the loop. Golang's gotcha's strike back
/cc @carbonin 
/cc @

OCPBUGSM-35037: Fix osImages refenrece passing

---

internal/controller/controllers/agentserviceconfig_controller.go

This will allow for remote worker nodes to be deployed on an L3 topology
/cc @djzager 

MGMT-7790: Set SUPPORT_L2 to False from the operator

---

docs/events.yaml
internal/bminventory/inventory.go
internal/common/events/events.go
internal/events/event.go
internal/host/host.go
internal/host/host_test.go
tools/generate_events.py

Currently host/cluster events store ClusterID as strfmt.UUID. As a result, APIs
that create events also expect clusterId parameter as strfmt.UUID. In case of
unbound host this may cause issues, since ClusterID will be nil.
We change the host event to store ClusterID as pointer, and propagate it as is
to SendHostEvent* APIs, which already handle the case where it is nil
/cc @
/cc @

MGMT-7806: Change host events API in order to solve segmentation fault

---

cmd/main.go
internal/cluster/cluster.go
openshift/template.yaml
pkg/app/middleware.go
pkg/app/middleware_test.go
pkg/commonutils/common_utils.go
pkg/thread/thread.go

The assisted-installer cluster-monitor seems to hang for hours from time to time, whenever it hangs clusters dont' get updated by the monitor.
This cause few issues, that lead to installation failures (mainly we've seen clusters stuck in timeout while preparing for installaiton until they timeout).
Adding last run timestamp to each thread object that will run monitor.
Updated liveness probe to watch the last run timestamp with 5 minutes timeout
Adding logs around cluster monitor in order to see what takes so long.
Should this PR be tested by the reviewer? No
Is this PR relying on CI for an e2e test run? For regression
Should this PR be tested in a specific environment?
Any logs, screenshots, etc that can help with the review process?
This PR was tested using this branch in subsystem with …

Monitor logs

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go

Default values are already defined in swagger but when the API is used
without the clients, the default values aren't generated. This code is
aligning with the swagger's default values.
Cluster creation:
* default values for 'enable_on':   'none'
* default values for 'mode':        'tpmv2'
Cluster update:
We need to allow partial updates, here is a trivial use case:
- the user set disk encryption to work on masters
- default values set mode to tpmv2
- then the user changes his mind and want to encrypt all hosts
* we should not make him choose again the encryption mode
/cc @
/cc @ …

NO-ISSUE: Fixing default values for disk-encryption on cluster creation.

---

config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml

Turns out that the versions included in the olm.skipRange annotation
must exist for certain OLM features to work properly.
See https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/224
/cc @flaper87 
/cc @

NO-ISSUE: Fix olm skip range

---

models/os_image.go
models/release_image.go
restapi/embedded_spec.go
swagger.yaml

This commit aligns the definition of OsImages and ReleaseImages to what was discussed in the enhancement
proposal[0]. The default architecture should be x86_64.
[0] https://github.com/openshift/assisted-service/blob/34c986435c1e85776b2bcb0544eab2e6e77a2c2b/docs/enhancements/arm64-cpu-architecture.md\#cluster-creation-and-iso-generation
/cc @carbonin 
/cc @djzager 

OCPBUGSM-35242: Set x86_64 as the default architecture for OsImages and ReleaseImages

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/host/hostcommands/api_vip_connectivity_check_cmd.go
internal/host/hostcommands/api_vip_connectivity_check_cmd_test.go
internal/host/hostcommands/instruction_manager.go
models/api_vip_connectivity_request.go
openshift/template.yaml
restapi/embedded_spec.go
swagger.yaml

This environment variable was used to "enable L3" connectivity for day2
hosts. More precisely, this environment variable would disable
agent-side CIDR validation on the host, which was most relevant when
adding worker nodes.
The CIDR validation happens at the service level for *all* day1 hosts.
The validation for day2 hosts was pushed to the agent. In a PR pushed to
the agent repo[0] the logic to validate CIDR on the agent side is being
removed and this PR is focused on removing the variable controlling such
feature.
**IMPORTANT**
These 2 PRs will effectively remove any CIDR validation for day2 hosts
since the CIDR validation on the server-side is only done for day1. This
is fine since the only thing we really care about is connectivity to the
VIP, which is still being validated by the …

MGMT-7847: Remove SUPPORT_L2 env var

---

cmd/main.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go

This PR has two parts:
1. Make assisted service set the infra env download URL to the image service when the image service base url is provided
- This also adds a new environment variable to assisted service `IMAGE_SERVICE_BASE_URL`.
- The presence of this string changes the behavior of assisted service (images will not be generated internally and the template images will not be downloaded/created)
2. Provide `IMAGE_SERVICE_BASE_URL` to assisted service using the agent service config operator.
- Specifically we pass in the route host with https as this will be used to build a link for users which should be accessible from outside the cluster we're running on.
https://issues.redhat.com/browse/MGMT-7258
Deployed the operator on a local CRC cluster, created agent service config to deploy …

MGMT-7258: Use image service in assisted service

---

deploy/operator/ztp/assisted-installer-crds-playbook.yaml
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/network/cidr_validations.go

This commit adds an ability to manually provide machine networks in the
following scenario
* dual-stack OCP cluster
* non-DHCP mode
* VIPs manually provided
Previously whenever VIPs were provided, machine network was
automatically calculated based on them and the available networks on the
hosts. This is not a valid case anymore in case of a dual-stack cluster,
as multiple VIPs are not allowed.
In such a case we want to enable users to explicitly provide machine
networks so that the dual-stack cluster can be installed.
A sample CR presenting this scenario would look as follows
```
spec:
apiVIP: 192.168.111.100
ingressVIP: 192.168.111.101
networking:
machineNetwork:
- cidr: "192.168.111.0/24"
- cidr: "fd2e:6f44:5dd8:c956::/120"
[...]
provisionRequirements:
controlPlaneAgents: 3
``` …

MGMT-7315: Allow providing machine networks for multi-node non-DHCP

---

deploy/operator/ztp/add-remote-nodes-playbook.yaml
deploy/operator/ztp/add_day2_remote_nodes.sh
deploy/operator/ztp/assisted-installer-crds-playbook.yaml
deploy/operator/ztp/baremetalHost.j2

This playbook is meant to be run after `remote_nodes.sh` that lives in dev-scripts. After running `remote_nodes.sh` there is a file called `remote_baremetalhosts.json` that is similar to `extra_baremetalhosts.json`
While dev-scripts generates it's own manifests we still need to apply the correct `infraenv` to the host. This reuses the existing code to do this.
I also renamed `extra_baremetalhosts` to `baremetalhosts` to make it more generic.
TODO: Find validation for the remote hosts once they are applied.
/cc @flaper87

MGMT-7223: Changes for adding remote worker node jobs

---

cmd/operator/main.go
config/manager/manager.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
internal/controller/controllers/agentserviceconfig_controller.go

There is a common pattern in OpenShift to create [infrastructure machinesets](https://docs.openshift.com/container-platform/4.8/machine_management/creating-infrastructure-machinesets.html). These allow the cluster admins to have machines specialized for running the things like Hive, ACM, assisted, etc.
The upcoming Open Cluster Management 2.4 release adds support for running the operators in the infrastructure nodes. In order to satisfy the expectation that the OCM components run in the infrastructure nodes, we need to make sure that the workloads that we spawn remain in the same node selection as the Infrastructure operator does.
The way this commit seeks to achieve that, is by retrieving the node selection and the toleration that OCM set for the  infrastructure operator and set it for …

MGMT-7687: Propagate Infrastructure Operator node selection and tolerations to its workloads

---

docs/events.yaml
internal/common/events/events.go
internal/imgexpirer/imgexpirer.go
internal/imgexpirer/imgexpirer_test.go

The patch replaces the in-code event with a generated one for cluster
image expired.
/cc @nmagnezi 

MGMT-4872: Generate Image Expirer Event

---

internal/common/db.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/hostcommands/instruction_manager_test.go

Originally, assisted-service would add the `--copy-network` argument to
the coreos-install command when the cluster.StaticNetworkConfigured flag
was set. This flag, however, is only been set to true for cloud-managed
deployments.
The cluster.StaticNetworkConfigured flag became a cached value of data
that should be considered dynamic, which broke the abstraction and the
separation of concerns of the various objects managed internally.
Specifically, it put in the cluster data that should only belong to the
infraenv.
This commit removes the use of `cluster.StaticNetworkConfigured` when
deciding to pass the `--copy-network` flag in favor of just checking
that the `infraenv.StaticNetworkConfig` is not empty.
The field in the model is not being removed in this commit as this will
be backported …

Bug 2007515: Pass copy-network when infraEnv.StaticNetworkConfig is set

---

internal/common/db.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/instruction_manager_test.go

Commit 8cf51023fecb0ef0d213b8d0d216176f903f0190 (#2662) introduced a bug
which broke late binding.
The `GetInfraEnvByClusterFromDB` function introduced by that commit
wrongly assumed that every infra env must have a corresponding cluster
ID. This is not the case for late-binding infra-envs where infra envs
can have no cluster ID.
This commit gets rid of the `GetInfraEnvByClusterFromDB` function and instead fetches
the infra-env database object during install command creation by taking the infraenv
ID from the host and using the existing `GetInfraEnvFromDB` function.
All "modern" hosts are guaranteed to have an infra env ID.
Older hosts in the database might not have an infra env ID, but we
do not expect any user to actually try to go through with "installation"
of these old hosts. In any …

Bug 2007515: Fix regression introduced by copy-network bugfix

---

internal/controller/controllers/agentserviceconfig_controller.go

This commit removes the explicit setting of ImagePullPolicy so that we
can rely on the default behavior of the OCP that is
* If the tag is latest, OpenShift Container Platform defaults
imagePullPolicy to Always.
* Otherwise, OpenShift Container Platform defaults imagePullPolicy to
IfNotPresent.
Closes: [MGMT-7867](https://issues.redhat.com/browse/MGMT-7867)
/cc @djzager 
/cc @flaper87 

MGMT-7867: Use default ImagePullPolicy behaviour from OCP

---

internal/common/db.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/hostcommands/instruction_manager_test.go

Originally, assisted-service would add the `--copy-network` argument to
the coreos-install command when the cluster.StaticNetworkConfigured flag
was set. This flag, however, is only been set to true for cloud-managed
deployments.
The cluster.StaticNetworkConfigured flag became a cached value of data
that should be considered dynamic, which broke the abstraction and the
separation of concerns of the various objects managed internally.
Specifically, it put in the cluster data that should only belong to the
infraenv.
This commit removes the use of `cluster.StaticNetworkConfigured` when
deciding to pass the `--copy-network` flag in favor of just checking
that the `infraenv.StaticNetworkConfig` is not empty.
The field in the model is not being removed in this commit as this will
be backported …

Bug 2007539: Pass copy-network when infraEnv.StaticNetworkConfig is set

---

deploy/operator/utils.sh

When deploying the operator, we wait 22m for the service pods to become ready,
and if they don't become ready, we give up and exit with an error.
I've had a run fail due to this timeout being too short, where the pod did eventually
became ready - if the timeout were to be higher, it would've probably worked just fine.
/cc @yuvigold
/cc @carbonin

NO-ISSUE - Increase operator deployment wait-for-service-pod-ready timeout

---

tools/ocp_version_update/Jenkinsfile.default_release_update
tools/ocp_version_update/update_default_release_versions_to_latest.py

Assigned user on ocp versions bump job should be changed now.
Currently the job fails with this error:
```
10:31:58  Traceback (most recent call last):
10:31:58    File "tools/ocp_version_update/update_default_release_versions_to_latest.py", line 534, in <module>
10:31:58      main(parse_args())
10:31:58    File "tools/ocp_version_update/update_default_release_versions_to_latest.py", line 333, in main
10:31:58      title, task = create_jira_task(updates_made_str, dry_run, args)
10:31:58    File "tools/ocp_version_update/update_default_release_versions_to_latest.py", line 492, in create_jira_task
10:31:58      _, task = create_task(args, TICKET_DESCRIPTION + " " + versions_str)
10:31:58    File "tools/ocp_version_update/update_default_release_versions_to_latest.py", line 137, in …
```

Fix OCP bump job by updating assigned user

---

internal/controller/controllers/infraenv_controller.go
internal/controller/controllers/infraenv_controller_test.go
subsystem/kubeapi_test.go

In case of an internal error in the InfraEnv controller reconcile loop,
the condition message is showing:
'Failed to create image: internal error'
With this patch, the internal error message is also available.
For example:
'Failed to create image due to an internal error: failed to get secret
assisted-installer/pull-secret-nope from API: secrets "pull-secret-nope" not found'
/cc @nmagnezi 
/cc @filanov 

Bug 2009204: Add error msg to InfraEnv condition

---

internal/host/host_test.go
internal/host/transition_test.go
models/host.go
restapi/embedded_spec.go
swagger.yaml

These old fields are irrelevant anymore because they exist under `progress` field.
* stage_started_at
* stage_updated_at
/cc @filanov 
/cc @carbonin 

MGMT-2391: Deprecate host stage_started_at and stage_updated_at fields

---

deploy/operator/setup_lso.sh

See the # comment in the diff for the rationale
This should solve the widespread LSO CI errors we've been seeing recently
/cc @YuviGold
/cc @osherdp

NO-ISSUE: Use 4.8 redhat-operators catalog on OCP 4.9

---

internal/host/host_test.go
internal/host/transition_test.go
models/host.go
restapi/embedded_spec.go
swagger.yaml

Reverts openshift/assisted-service#2681
QE test environments always work with the same latest client version.
It means that when the `master` changes and the client got updated accordingly, the staging still uses the old protocol.
Since this change is just nice-to-have and isn't mandatory, it would be much faster to revert this PR and adjust the QE pipeline later on.
cc @lalon4 @filanov @gamli75

Revert "MGMT-2391: Deprecate host stage_started_at and stage_updated_at fields"

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go
subsystem/kubeapi_test.go

BMH controller check for empty conditions list but if because of a bug
specific conditions doesn't exdists, controller will panic
If agent reesource create and not reconciled or conditions is not found
there would be a panic in the test.
/cc @rollandf 
/cc @nmagnezi 

Bug 2010168: Fix flaky test point to a nil pointer conditions

---

internal/bminventory/inventory_test.go
internal/cluster/validations/validation_test.go
internal/cluster/validations/validations.go
internal/network/cidr_validations.go
internal/network/dual_stack_validations.go
internal/network/utils.go

This commit extends the validations performed for dual-stack OCP
clusters by making sure the following requirements are met if a cluster
is dual-stack
* exactly 2 machine networks are provided (if any)
* exactly 2 service networks are provided
* exactly 2 cluster networks are provided
* for every list containing 2 networks, the first one has to be IPv4 and
the second one IPv6
Closes-bug: #2007106
Contributes-to: #2005440
Closes: [OCPBUGSM-35447](https://issues.redhat.com/browse/OCPBUGSM-35447)
Contributes-to: [OCPBUGSM-35273](https://issues.redhat.com/browse/OCPBUGSM-35273)
```
time="2021-09-28T11:38:22Z" level=error msg="Failed to registered cluster test-infra-cluster-assisted-installer-debug with id c89e1293-7b2e-4959-bc1a-b6934a20a6f3" …
```

Bug 2007106: Extend dual-stack network subnet validations

---

client/versions/list_supported_openshift_versions_responses.go
cmd/main.go
internal/common/test_configuration.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/host/hostcommands/container_image_availability_cmd_test.go
internal/versions/versions.go
internal/versions/versions_test.go
models/openshift_version.go
restapi/embedded_spec.go
restapi/operations/versions/list_supported_openshift_versions_responses.go
swagger.yaml

As OPENSHIFT_VERSIONS env var should be deprecated, the openshift_versions API
(used by the UI to display versions list) is now generated according to RELEASE_IMAGES env var.
* Added 'default' property to 'release-image' object.
* Should be manually specified in release_images instead of in openshift_versions.
* Added 'cpu_architectures' array to openshift-version:
* Generated according to available architectures in release_images.
* Since openshift-versions is now optional, the 'openshift-version' model is used
as a simple struct without required properties.
* SupportLevel is detected according to the release image version.
I.e. rc/fc/nightly are considered as beta.
/cc @filanov 
/cc @YuviGold   …

MGMT-7708: Generate openshift_versions API from RELEASE_IMAGES

---

cmd/main.go

The database is configured to accept a max of 100 connections. If we
also have our connection pool configured to 100 we'll hit the limit
before we stop giving out connections and error out some requests that
could have succeeded.
Reducing the max in the gorm connection pool will prevent these errors.
https://bugzilla.redhat.com/show_bug.cgi?id=2010479
I deployed assisted service in minikube locally and did 1000's of simultaneous queries to attempt to max out the connection pool.
Without this fix I hit errors as described in the BZ:
```
time="2021-10-04T18:08:35Z" level=error msg="Failed to get infra env e058a8ba-7f5b-4c89-9b27-3359e8f6bc40" func="github.com/openshift/assisted-service/internal/bminventory.(*bareMetalInventory).V2DownloadInfraEnvFiles" …
```

Bug 2010479: Reduce open db connection limit to under the max

---

config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
hack/generate.sh
internal/versions/versions.go
internal/versions/versions_test.go

If 'cpuArchitecture' is not specified under osImages in AgentServiceConfig,
an empty string is specified in OS_IMAGES[*].
Hance, handling an empty string as missing property - default to x86_64.
Also added the property to the CRD sample to make it explicit.
[*]
https://github.com/openshift/assisted-service/blob/824eef89ac58cf89a474d9272e9d54b4b353c911/internal/controller/controllers/agentserviceconfig_controller.go#L1206
/cc @flaper87 
/cc @rollandf 
/cc @filanov 

OCPBUGSM-35272: empty cpu architecture implies default

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

https://bugzilla.redhat.com/show_bug.cgi?id=2009670
Fix assisted service can panics after creating a cluster with registered hosts and call the 'supported-platforms' endpoint.
/cc @filanov 
/cc @rollandf

OCPBUGSM-35727: Fix calling 'supported-platforms' just after the cluster creation causes a panic

---

internal/cluster/common.go
internal/cluster/validator.go
internal/common/common.go
internal/hardware/validator.go
internal/host/common.go
internal/host/common_test.go
internal/host/host.go
internal/host/host_test.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/logs_cmd.go
internal/host/hostrole_test.go
internal/host/hostutil/host_utils.go
internal/host/mock_host_api.go
internal/host/monitor.go
internal/host/transition_test.go
internal/host/validations_test.go
internal/host/validator.go
internal/ignition/ignition.go
internal/installcfg/builder/builder.go
internal/operators/cnv/cnv_operator.go
internal/operators/ocs/ocs_operator.go
internal/operators/ocs/ocs_operator_test.go
internal/operators/ocs/validations.go
subsystem/cluster_test.go

- role based validations now takes into account the
suggested role in case of auto-assign. This results
in timely failures in case the role to be assigned
is incompatible with the validation's logic
- role evaluation is now being done in its own function
within the monitoring instead of in RefreshStatus
/cc @
/cc @

MGMT-4475: validations to consider effective role

---

docs/enhancements/arm64-cpu-architecture.md
docs/hive-integration/kube-api-select-ocp-versions.md
docs/operator.md

Updated documentation:
* operator/kube-api: added cpuArchitecture to osImages example.
* arm64 enhancement: added an explanation regarding OS_IMAGES/RELESE_IMAGES.
/cc @rollandf 
/cc @filanov 
/cc @flaper87 

MGMT-7801: update docs on os_images and release_images

---

internal/ignition/ignition.go

- Increasing timeout for pre-network-manager-config.service to 60
seconds.  It was checked by the customer that timeout of 30 fixes the problem.

OCPBUGSM-35106: pre-network-manager-config failed due to timeout when static config is used

---

internal/operators/cnv/cnv_operator.go
internal/operators/cnv/cnv_operator_test.go

Added a validation to cnv_operator to ensure that "OpenShift Virtualization" is enabled only for clusters with x86_64 CPU architecture.
/cc @avishayt 
/cc @pkliczewski 
/cc @jakub-dzon 
/cc @filanov 

MGMT-7181: CNV operator cpu architecture validation

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

In Kube API flow, when an host registers a corresponding Agent CR is
created.
Before this patch, in case that the Agent CR creation fails, the host was still created
in the DB. That would lead to a state where the InfraEnv cannot be
deleted as it still has hosts connected.
To fix this issue,  the host is deleted from DB if the creation of the Agent CR fails.
/cc @filanov 
/cc @omertuc 
/cc @nmagnezi 

Bug 2013791: Delete host from DB if Agent creation fails

---

deploy/operator/utils.sh

This commit updates the ansible library used in Python script
responsible for deploying the AI operator.
Relates-to: https://github.com/openshift-metal3/dev-scripts/pull/1301
/cc @flaper87 
/cc @celebdor 

NO-ISSUE: Use ansible_collections instead of ansible.plugins

---

internal/host/common.go
internal/host/host.go

When adding Day2 agent, the agent's stateInfo field remain in 'rebooting' status even after the node has successfully joined the cluster.
The root cause is that UpdateInstallProgress function select the statusInfo text to match the rebooting stage while the Host's status in Day2 reflects the special meaning reboot has in Day2 (The last known stage)
The fix introduces a new statusInfo to match the state in this case
/cc @
/cc @

Bug 2013419: fix status_info in case of day2 host

---

tools/ocp_version_update/update_default_release_versions_to_latest.py

update_default_release_versions_to_latest:
When a new stable rhcos version is introduced to an existing pre-release, the image/rootfs URLs should be updated to stable format.
/cc @osherdp 
/cc @filanov 

NO-ISSUE: update default versions - support new stable

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
subsystem/cluster_test.go

Validate UserManagedNetworking and VipDhcpAllocation when creating a cluster with None HighAvailabilityMode:
* User Managed Networking must be enabled on single node OpenShift:
* If UserManagedNetworking not specified, should be set to true.
* If false, return an API error.
* VIP DHCP Allocation cannot be enabled on single node OpenShift:
* If VipDhcpAllocation not specified, should be set to false.
* If true, return an API error.
/cc @eranco74 
/cc @tsorya 
/cc @avishayt 
/cc @filanov 

OCPBUGSM-35151: validate HA properties on register cluster

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
models/proxy.go
restapi/embedded_spec.go
subsystem/infra_env_test.go
swagger.yaml

Instead of htps_proxy it creates a field http_s_proxy.
To solve, create a tag to set the column name

MGMT-8029: Gorm creates wrong field name for https_proxy field in infra-env

---

tools/ocp_version_update/update_default_release_versions_to_latest.py

OCP y-stream versions have 3 channels: stable, fast and candidate (even y values have ``eus`` as well). Up until now, we only bumped OCP versions by querying stable-channels, but for sure it's only relevant to environments/customers that can wait as long as needed until release-team feels comfortable enough with it.
This script changes upstream testing, which should prioritize early integration over stability, so we should at least do this change.

NO-ISSUE: bump OCP versions based on fast-channels instead of stable-channels

---

docs/hive-integration/README.md

Working with mirror registry point to ../operator.md#mirror-registry-configuration
Creating InstallConfig overrides point to ../user-guide/install-customization.md#install-config
Creating host installer args overrides point to specific commit https://github.com/openshift/assisted-service/blob/38a9d0398b96e81ef494029277e362a7256df44e/internal/host/hostutil/host_utils.go#L150
/cc @
/cc @

BUG-2016158: fix links in hive-integration README.md

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

v1 ListHosts used customizeHost() to populate the requested_hostname host
attribute, among other things. V2ListHosts Should do the same.
/cc @
/cc @

Bug 2017866: Populate requested_hostname in V2ListHosts

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/cluster/cluster.go
internal/cluster/progress_test.go
internal/host/host.go
internal/host/mock_host_api.go

The reason for the irregular behavior is that SNO stages are different than
an ordinary bootstrap node by design
The solution is to define a new set of progress rules for SNO node and pass
it on the host
/cc @
/cc @

Bug 2005259: Progress bar out of order in SNO

---

subsystem/events_test.go

Recent CI results show that some tests may expect to get
two or three cluster events.
The reason is that it might take an extra second or two
to list events for a given cluster after it got registered.
So it will always get the following events:
- Registered cluster
- Successfully registered cluster
And sometimes it will also get:
- Updated status of the cluster to pending-for-input
This PR changes the tests to:
1. expect any number of events per cluster_id filtering
2. assert that all returned events do match the given cluster_id
/cc @filanov 
/cc @rollandf  …

MGMT-8120: Change Events subsystem tests assertion

---

internal/installcfg/installcfg.go

This should allow users to specify clusterOSImage in the install-config-overrides
- Is this PR relying on CI for an e2e test run? no, it was tested by qe
- Should this PR be tested in a specific environment? OCM-2.4 + ignition override for clusterOSImage
-->
/cc @tsorya 
/cc @filanov 

Bug 2016178: Add ClusterOSImage to Baremetal platform

---

tools/ocp_version_update/update_default_release_versions_to_latest.py

When opening a PR for bumping OCP releases, it writes a description that holds information about the releases and it adds the following:
```
/test all
/hold
```
The first should run all tests, the second one should hold the PR until someone can take a look and approve it.
Actually ``/test all`` doesn't really run all tests, but rather runs all tests that have been triggered by default with respect to the PR's changes. Also, it seems like when including this command it breaks the run of the jobs right away for some reason.

NO-ISSUE: remove '/test all' that just breaks all jobs

---

internal/bminventory/inventory.go
subsystem/cluster_test.go

A bug in the implementation caused the usage always to be
set and never to be cleared
Now the implementation set the networkType related usages
in a mutually exclusive way
/cc @
/cc @

NO-ISSUE: fix usage report on SDN/OVN

---

dev-requirements.txt
tools/utils.py
tools/wait_for_assisted_service.py

Currently there are multiple CI failures due to `RuntimeError` raised while running `kubectl --namespace assisted-installer get service assisted-service` command
The error is: `Error from server: etcdserver: request timed out code=1`
/cc @osherdp

MGMT-8128 - Fix wait_for_assisted_service failing on multiple tests

---

config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml

One more modification to the operator manifests, I pray the last, to get the operator-publish script in openshift/release to create the PR in community-operators.
/cc @lranjbar 
/cc @celebdor 

NO-ISSUE: Expand operator CSV description

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/hostcommands/inventory_cmd.go
internal/host/hostcommands/inventory_cmd_test.go
internal/host/hostcommands/next_step_runner_cmd.go

Dry run modes have been introduced to the agent/installer (and in the
future also to the controller):
https://github.com/openshift/assisted-installer-agent/pull/250
https://github.com/openshift/assisted-installer/pull/371
To make these dry run modes work more easily, the service required some
minor modifcations, implemented by this commit.
The changes are as follows -
1) Propagate host agent environment to next-step-runner and inventory
This commit makes it so the `CONTAINERS_CONF` and `CONTAINERS_STORAGE_CONF` environment
variables from the host agent also propagate to the the next_step_runner container.
This allows the assisted-swarm to freely control how other environment variables
propagate to the step containers, and also how podman storage is
managed for those containers.
Currently …

MGMT-8074: Make the assisted-service more dry run friendly

---

models/host_progress.go
models/host_progress_info.go
restapi/embedded_spec.go
swagger.yaml

- This will be needed for go-swagger v0.28 since the generated code
cases the python client to crash if this field is empty.
/cc @
/cc @

MGMT-8129: Remove required attribute from current_stage in both host_progress and host_progress_info

---

internal/bminventory/inventory.go
internal/host/hostutil/test_utils.go
internal/host/validator.go
internal/network/manifests_generator.go
internal/network/manifests_generator_test.go

Until now we were just checking that the disk-encryption object is
empty, but we recently added default values to disk-encryption feature
that always fill the object with data in such way that the 'enable_on'
field is set to 'none' by default, therefore, the condition for disabled
disk-encryption has changed.
/cc @
/cc @

Bug 2020928: Changing the condition that check if disk-encryption is enabled.

---

internal/bminventory/inventory.go
internal/host/hostutil/test_utils.go
internal/host/validator.go
internal/network/manifests_generator.go
internal/network/manifests_generator_test.go

Backported from #2887 
Until now we were just checking that the disk-encryption object is
empty, but we recently added default values to disk-encryption feature
that always fill the object with data in such a way that the 'enable_on'
field is set to 'none' by default, therefore, the condition for disabled
disk-encryption has changed.

NO-ISSUE: changing the condition that check if disk-encryption is enabled

---

internal/cluster/transition.go
internal/host/hostutil/update_host.go
internal/host/transition.go
subsystem/cluster_test.go

After reset the progress is not going back to zero
The solution is to reset the progress fields on reset so the calculation can start anew - the same as in first time installation
/cc @
/cc @

OCPBUGSM-36598: clean progress on reset

---

cmd/webadmission/main.go
internal/controller/controllers/agentserviceconfig_controller.go
pkg/validating-webhooks/agentinstall/v1beta1/infraenv_admission_hook.go
pkg/validating-webhooks/agentinstall/v1beta1/infraenv_admission_hook_test.go
pkg/validating-webhooks/hiveextension/v1beta1/agentclusterinstall_admission_hook.go

Adding a webhook that validates that InfraEnv's clusterRef does not get updated.
/cc @
/cc @

MGMT-7834: webhook infraenv update

---

hack/crds/hive.openshift.io_clusterdeployments.yaml
hack/crds/hive.openshift.io_clusterimagesets.yaml

Kubernetes 1.22 [no longer supports](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122) CRDS with version `apiextensions.k8s.io/v1beta1`. This [impacts](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1196/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-kube-api/1455153244295663616/build-log.txt) using minikube version v.1.22.0 and above when creating a cluster with the `assisted-test-infra`.
```
RuntimeError: command=kubectl --namespace assisted-installer apply -f /home/assisted/assisted-service/hack/crds//hive.openshift.io_clusterdeployments.yaml exited with an error=error: unable to recognize "/home/assisted/assisted-service/hack/crds//hive.openshift.io_clusterdeployments.yaml": no …
```

NO-ISSUE: Graduate hive CRDs to apiextensions.k8s.io/v1

---

internal/host/validator.go

Day2 hosts encryption isn't implemented yet, therefore, we should skip
the validations on those hosts until it is implemented.
/cc @
/cc @

OCPBUGSM-36974: Skipping disk-encryption validation on day2 hosts.

---

Makefile
docs/dev/testing.md
hack/wait_for_postgres.sh
internal/common/common_unitest_db.go

Use `quay.io/edge-infrastructure/postgresql-12-centos7:latest` image. Use only one consistent Postgres image in the existing code. Currently, we have 2 different images in the code - `quay.io/ocpmetal/postgres:12.3-alpine` and `quay.io/ocpmetal/postgresql-12-centos7` which is now the same as `quay.io/edge-infrastructure/postgresql-12-centos7:latest`. 
Some additional changes such as the use of `postgres` user for test cases are added to address the `pq: permission denied` error while creating a database. Also, the password for the admin account `postgres` is added using POSTGRESQL_ADMIN_PASSWORD env var.
Ref: https://issues.redhat.com/browse/MGMT-8196
` skipper make unit-test`
/cc @
/cc @
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors …

MGMT-8196: Use postgresql-12-centos7:latest image

---

docs/events.yaml
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/common/events/events.go

This event is only used once in V2RegisterHost with InfraEnv[1].
The rationale for renaming is:
1. Event name should be on par with the respective cluster
event: cluster_registration_succeeded
2. host_registration_succeeded is on par with host_registration_failed.
3. The event does not include a cluster id.
[1] https://github.com/openshift/assisted-service/blob/c48bcdf24e33c114545089df0ae90fa27b926e24/internal/bminventory/inventory.go#L6273-L6275
/cc @filanov 
/cc @masayag 
/cc @arielireni  
/cc @avishayt  

MGMT-8198: Rename host_cluster_registered to host_registration_succeeded

---

internal/bminventory/inventory.go
internal/common/conversions.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
subsystem/kubeapi_test.go

* Reset API require OpenshiftClusterID in V2ImportClusterInternal but because it is in internal function it can be called without OpenshiftClusterID, for example by controller packages, because this parameter is not required for the ACM we can skip it in the controller.
* Importing cluster can add optional parameter OpenshiftClusterID when creating day2 clsuter without having day1 (import cluster) OpenshiftClusterID is added by setting ACI.spec.clusterMetadata.clusterID
* Add subsystem test that create installed CD and ACI to check that cluster can be imported without being installed by AI controller.
/cc @nmagnezi 
/cc @rollandf  …

MGMT-8200: Fix controller crash when import installed cluster 

---

internal/controller/controllers/bmh_agent_controller.go

BMAC currently caches the spokeClient instance. This was originally done as an optimization
to avoid creating client instances on very loop. Unfortunatelly, this causes issues as the spokeClient
instance being cached is able to speak to just one spoke cluster, whereas BMAC should be able to speak
to many spoke clusters when adding day2 workers.
Ultimately, the caching was not really needed as BMAC stops reconciling BMH CRs that have been detached, which
reduces the number of times it has to talk to the spoke cluster
Tests were done in a QE environment /cc @trewest 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message- …

Bug 2014262: No cache no client cause hub gotta speak to spoke when retrying

---

docs/events.yaml
internal/bminventory/inventory.go
internal/common/events/events.go

As a follow up to MGMT-8198, there are two additional host registration
events that may include a cluster_id:
host_registration_failed
host_registration_setting_properties_failed
We should add cluster_id as an optional parameter to make those
consistent with: host_registration_succeeded
/cc @filanov 
/cc @arielireni 
/cc @masayag 

MGMT-8229: All host registration events to include optional cluster_id

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

Set explicitly the PlatformType on V2ImportClusterInternal as the property has been changed to a pointer as part of go-swagger upgrade[1]. I.e. currently, upon day2 cluster creation, assisted-service python client fails with ValueError on PlatformType model deserialize[2] as type in the response is null[3].
[1]
https://github.com/openshift/assisted-service/pull/2872/files#diff-3657f5d7ebd63c86fef223229378261d08b79e7d363b6f297cd6595e74683697R27
[2]
:type: PlatformType
"""
if self._configuration.client_side_validation and type is None:
raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `type`, must not be `None`
[3]
day2 cluster repsonse:
...
"platform": {
"ovirt": {},
"type": null,
"vsphere": {}
},
/cc @osherdp 
/cc @eliorerz 
/cc …

NO-ISSUE: set PlatformType on ImportCluster

---

hack/check-commit-message.sh

Allow having commits like in this format (which lots of the backports are having):
```[release-ocm-2.4] Bug xxxxxxx: bla bla```
/cc @rollandf 
/cc @flaper87 

NO-ISSUE: fix commit message validator to allow [<tag>] at start

---

internal/cluster/progress_test.go
internal/cluster/transition.go

When reboot is stuck and the cluster moved to pending user action state
the progress bar returns to 10% after the boot error is solved and the 
installation process continues
The root cause is that a initialization code of the progress bar is called
again on transition between pending-user-action and installing
The solution is to limit the initialization to the correct transition, namely
the transition between preparing-for-installation to installing
/cc @
/cc @

OCPBUGSM-36861: progress bar goes to 10% after pending user action on reboot

---

cmd/webadmission/main.go
internal/controller/controllers/agentserviceconfig_controller.go
pkg/validating-webhooks/agentinstall/v1beta1/agent_admission_hook.go
pkg/validating-webhooks/agentinstall/v1beta1/agent_admission_hook_test.go

Reject change in ClusterDeploymentName in Agent CR if Agent is currently installing.
/cc @isaacdorfman 
/cc @filanov 

MGMT-8127: Webhook block unbind if Agent is installing

---

internal/ignition/ignition.go
internal/ignition/ignition_test.go

The CA cert is already base64 encoded and there is no need to encode it again.
-->
/cc @avishayt 
/cc @machacekondra 

NO-ISSUE: there is no need to base encode an already base64 encoded CA cert

---

internal/controller/controllers/agent_controller.go

use swag.StringValue when checking the value of string pointer
We get panic in case the ignition endpoint token is set:
```
│ panic: runtime error: invalid memory address or nil pointer dereference                                                                                               │
│ [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2935398]                                                                                               │
│ goroutine 883 [running]:                                                                                                                                              │
│ github.com/openshift/assisted-service/internal/controller/controllers.(*AgentReconciler).updateIfNeeded(0xc00027a8c0, 0x380a370, 0xc0012ca330, 0x3851b70, …
```

MGMT-8295: reconcile fail in case agent spec.IgnitionEndpointToken isn't empty due to null pointer dereference

---

internal/installcfg/installcfg.go

This is a manual cherry-pick of #2862

Bug 2025280: Add ClusterOSImage to Baremetal platform (#2862)

---

internal/bminventory/inventory.go
subsystem/host_v2_test.go

Allow updating agent properties before binding to a cluster
/assign @yevgeny-shnaidman 

MGMT-8278: Allow updating agent properties before binding

---

tools/ocp_version_update/Jenkinsfile.default_release_update

Use a neutral user for creating OCP version upgrades. This should be better than relying on some personal account.
/cc @eliorerz 

Make openshift-edge-bot author for OCP version bump

---

internal/host/transition.go
subsystem/cluster_test.go

Timestamps for logs were not clear even though the logs themselves
were deleted
This has cause errors in e2e tests
Timestamps for logs were not clear even though the logs themselves
were deleted
This has cause errors in e2e tests
/cc @tsorya 
/cc @gamli75 

NO-ISSUE: clear host's log timestamp when deleting the logs

---

tools/ocp_version_update/update_default_release_versions_to_latest.py

When an environment has no ``~/.netrc`` file on the host, docker will create this path on the host as a directory.
This should make sure we only take this path into account if it's a file. 

Only inspect netrc file in case file exists

---

internal/host/host.go
internal/host/host_test.go

MCP can't be set unless the host is day2 (Error: "Host %s must be in day2 to update its machine config pool name to %s"). This makes sense in the REST API, but in the k8s API once the host is day2 the installation already starts and it's too late. Consider moving the check to apply only to the REST API.
This change allows unbound hosts to set the machineConfigPool
Note that unbound hosts have the same kind as day-1 hosts hence this change
allow changing the machineConfigPool of day-1 hosts as well.
- Is this PR relying on CI for an e2e test run? yes for regression
-->
/cc @avishayt  …

MGMT-8298: MCP can’t be set until the host is day2

---

internal/ignition/ignition.go
internal/ignition/ignition_test.go

MGMT-8305: Ignition token passes extra colon

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/host/host.go
internal/host/host_test.go
internal/host/mock_host_api.go

Until now the UpdateHost API didn't update the ignition endpoint token.
Unit tests
/assign @eranco74 

MGMT-8296: Ignition token is not updated in UpdateHost API

---

internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
internal/controller/controllers/common.go

To avoid a missing release image on host installation, ClusterDeploymentsReconciler now ensures that the relevant image exists in version cache before invoking installation.
/cc @rollandf 
/cc @filanov 
/cc @eranco74 
/cc @nmagnezi 

MGMT-8279: kube-api - ensure release images exists upon install

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/featuresupport/support_levels_list.go
internal/usage/consts.go
models/feature_support_level.go
restapi/embedded_spec.go
subsystem/cluster_test.go
swagger.yaml

The feature usage of cluster managed newtorking with VMs support was returning wrong data.
Now marking `CLUSTER_MANAGED_NETWORKING_WITH_VMS` when cluster `userManagedNetworking` is false and there is at least one VM host in cluster.
Note: Changed featureID `USER_MANAGED_NETWORKING_WITH_VMS` -> `CLUSTER_MANAGED_NETWORKING_WITH_VMS`
/cc @sagidayan 

MGMT-8237: incorrect api responses for cluster managed networking with vms (#2936)

---

internal/host/pool_host_statemachine.go
internal/host/transition_test.go

validate hostname (should not be localhost) before transition to known-unbound in the InfraEnv state machine.
localhost is the hostname assigned by the NetworkManager in case there was no configuration either via NM config, RHEL config or DHCP. so any node that does not have hostname defined by either of those methods will be named localhost. This means that we might end up with at least 2 nodes with the same name, which is illegal for Kuberentes cluster, since it identifies nodes by the hostname
/cc @
/cc @

MGMT-8088 validate hostname before transition to known-unbound

---

Makefile

The postgres data directory in the postgres image used by the unit tests
used to be /var/lib/postgresql/data but looks like the image has changed
and now it's /var/lib/pgsql/data.
It's important to put this directory on a tmpfs because disks are slow
and there's no importance in persisting unit-test database data
Related to 084723e740441ad8ecac0c2031a93558c97c5d05
/cc @
/cc @

MGMT-4502: Put unit-test pgsql data on tmpfs again - the path changed

---

docs/events.yaml
internal/bminventory/inventory_test.go
internal/common/events/events.go
internal/events/eventstest/events_test_utils.go
internal/host/host_test.go
internal/host/hostutil/update_host.go
internal/host/hostutil/update_host_test.go
internal/host/monitor_test.go
internal/host/transition_test.go
internal/host/validations_test.go

Host status update events currently only include InfraEnv.
Example:
"Host test-infra-cluster-assisted-installer-master-0: updated status
from discovering to pending-for-input Waiting for user input"
When a host is bound to a cluster, the cluster-ID should also be included.
Adding cluster-ID will allow a view of those events when queries are filtered by a cluster-Id.
/cc @filanov 
/cc @masayag 
/cc @arielireni 
/cc @avishayt 

MGMT-7929: Host status update events to include optional cluster ID

---

internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go

Assisted-service ignore base path when building image-service URL
if the base url contain additional path it will be ignored
url: https://api.integration.openshift.com/api/assisted-images
resutl: https://api.integration.openshift.com/images/{infa-env-id}?{params}
expected result: https://api.integration.openshift.com/api/assisted-images/images/{infa-env-id}?{params}
/cc @osherdp 
/cc @carbonin 

MGMT-8346: fix iso url when using image service

---

Dockerfile.assisted-service-build
Makefile
hack/setup_env.sh
hack/start_db.sh
internal/common/common_unitest_db.go

Instead of the current `unit-test` target which does multiple things in one target -  create a docker DB, run unit tests and clean/kill docker db container, create separate targets for each task. 
- `run-db-container` only creates a container database
- `run-unit-test` runs the unit tests
- `kill-db-container` kills the DB container
The current `unit-test` target functionality remains as-is for local development - `unit-test` calls `run-db-container`, ` run-unit-test` and `kill-db-container`.
For running unit tests in CI, the assisted-service-build dockerfile is updated to use `quay.io/edge-infrastructure/postgresql-12-centos7:latest` as the base image and installs required dependencies. When running unit tests in CI job, invoke `make ci-unit-test` which will first start the database, and …

MGMT-7330: Create a job in prow CI to run assisted-service unit tests

---

internal/manifests/manifests.go
subsystem/manifests_test.go

In each `feature usage` there is an option to add additional data related to that feature.
`Custom manifests` feature was storing a map of filenames in that `data` field.
We have no need for the file names at the moment, and the data size is significantly bigger.
This PR will no longer store that data.
[MGMT-8372](https://issues.redhat.com/browse/MGMT-8372)
/hold
/cc @osherdp 

MGMT-8372: Removing data from "Custom manifests" usage

---

internal/host/transition.go

This fix handles the following case:
1. installation is aborted
2. host are going through force re-discovery
/cc @
/cc @

OCPBUGSM-36598: reset progress on re-discovery

---

internal/bminventory/inventory.go
internal/common/db.go
internal/controller/controllers/agent_controller.go
internal/host/host.go
internal/host/host_test.go
internal/ignition/ignition.go
internal/ignition/ignition_test.go
internal/ignition/mock_ignition.go
models/host.go
restapi/embedded_spec.go
swagger.yaml

The ignition endpoint token is sensitive information and should not be
returned to users once it is set. Instead, we have a boolean flag
showing that it has been set.
/assign @eranco74 

MGMT-8302 Ignition endpoint token should not be returned

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/versions/mock_versions.go
internal/versions/versions.go
internal/versions/versions_test.go

* In day2 context, when a release image for the existing cluster is missing, fallback to the the default version.
E.g. adding a host to an existing cluster based on 4.5 release image - would use 4.8 release image when installing the new added host.
* Added and helper to versions for fetching the default release image (GetDefaultReleaseImage).
/cc @rollandf 
/cc @filanov 

MGMT-8180: day2 - fallback to default ocp version

---

tools/deploy_ui.py

Just updating script to use the correct location of assisted-ui repository.
It's either way redirecting, just figured out it's better leading directly to the correct location.

Update assisted-ui repo location

---

docs/events.yaml
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/common/events/events.go
internal/events/eventstest/events_test_utils.go
subsystem/image_test.go

Upon cluster registration two events were produced:
- Registered cluster
- Successfully registered cluster
To match with host events, the 'Registered cluster' was removed.
Additionally, some registration failures did not produce any event.
This change addresses that problem as well.
/cc @
/cc @

MGMT-7925: Remove a redundant cluster registration event

---

Makefile

Fix failing CI due to invalid `assisted-python-client` tar.gz artifact.
/cc @osherdp

NO-ISSUE: Fix upload to pypi as it failed while uploading the tar.gz artifact

---

internal/bminventory/inventory.go
internal/common/error_utils.go

- Instead set error string "error is nil"
- In addition, fix a potential location that nil error was sent to  NewApiError
/cc @osherdp 
/cc @filanov 

MGMT-8461: Avoid panic in case nil is passed to GenerateError

---

internal/provider/vsphere/consts.go

Fix wrong vsphere provider db consts to match
database column names.
/cc @avishayt 
/cc @eliorerz

MGMT-8308: Fix vsphere provider db fields.

---

internal/operators/ocs/manifest.go

The latest version of OCS is always installed, after ODF is released,
OCS4.9 will be installed which doesn't take care of noobaa deployment.
So we need to make sure that whenever we install ocs, we install OCS4.8.
/cc @gobindadas 
/cc @pkliczewski 

MGMT-8482: Add channel for ocs operator

---

api/v1beta1/agentserviceconfig_types.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go

A new condition on the AgentServiceConfig Agent object is added to report the health status of the underlying operands (deployments) the infrastructure operator operates on. 
If all the 3 deployments `agentinstalladmission`, `assisted-image-service` and `assisted-service` have the condition status as `True` for condition type `Available` and `Progressing`, then the condition `DeploymentsHealthy` is set to `True` on the AgentServiceConfig else set to `False`
https://issues.redhat.com/browse/MGMT-8413
Install assisted service/infrastructure operator using the ztp scripts. If all the 3 deployments are healthy, the AgentServiceConfig object should have a condition `DeploymentsHealthy` set to `True`. Scale down the infrastructure-operator deployment and then scale down any of the 3 …

MGMT-8413: Add new condition on AgentServiceConfig Agent object

---

internal/cluster/common_test.go

Before this change this test was failing locally because the string
representation of the time didn't match even though it was actually the
same time.
Example failure:
```
• Failure in Spec Teardown (AfterEach) [0.520 seconds]
update_cluster_state
/home/ncarboni/Source/assisted-service/internal/cluster/common_test.go:19
UpdateCluster
/home/ncarboni/Source/assisted-service/internal/cluster/common_test.go:42
negative
/home/ncarboni/Source/assisted-service/internal/cluster/common_test.go:50
no_matching_rows [AfterEach]
/home/ncarboni/Source/assisted-service/internal/cluster/common_test.go:58
Expected
<string>: 0000-12-31T19:03:58.000-04:56
to equal
<string>: 0001-01-01T00:00:00.000Z
/home/ncarboni/Source/assisted-service/internal/cluster/common_test.go:67
```
/cc @jordigilh

NO-ISSUE: Use .Equal to compare time objects

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/mock_installer_internal.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
internal/versions/mock_versions.go
internal/versions/versions.go
internal/versions/versions_test.go

In kube-api context, instead of always invoking 'oc adm' in AddReleaseImage on day1/day2 cluster installation, use relevant
values from the existing cluster.
I.e. AddReleaseImage is invoking 'oc' for fetching ocpReleaseVersion and cpuArchitecture from the specified releaseImageUrl. So as an optimization, these values are now simply retrieved from the existing cluster.
/cc @rollandf 
/cc @filanov 

MGMT-8315: use values cached in cluster for AddReleaseImage

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/common.go

This PR consists of 2 commits - enabling to convert single-stack cluster to dual-stack in one API call and disabling autogeneration of machine networks for dual-stack clusters. A combination of those 2 allows at the end to create a complete dual-stack cluster with only a single API call.
Previously, because the check of the "stackness" of the cluster was happening without taking the updated params into consideration, at least 2 API calls were needed to change the status of the cluster. With this change in order to check what is the "stackness" of the cluster we are using a merge of 2 states
* current cluster network configuration
* updated configuration passed as an update parameter
Because of this, we no longer use the stale state.
The logic behind automatic calculation of Machine …

MGMT-8300: Improve behaviour of dual-stack via REST API

---

Dockerfile.assisted-service-build
Makefile

When running the unit tests in CI, the image is built as root but run as non-root.
CI isn't able to create the reports directory and results in the error
`mkdir: cannot create directory '/opt/app-root/src/reports': Permission denied`
During runtime, directories can't be added outside of `/tmp`.
To address this, `ROOT_DIR`, `COVER_PROFILE`, and `GINKGO_REPORTFILE` are made overridable. CI when running the unit tests will set these to the below values:
- TMPDIR                  "/tmp"
- COVERPROFILE   "/tmp/unit_coverage.out"
- REPORTFILE          "/tmp/junit_unit_test.xml"
Run `skipper shell`. Once inside the skipper environment, set the env variables. Run `make ci-unit-test`
/cc @lranjbar 
/cc @ …

MGMT-7330: Make `ROOT_DIR`, `COVER_PROFILE` and `GINKGO_REPORTFILE` overridable for running unit tests in CI

---

internal/bminventory/inventory.go
internal/network/dual_stack_validations.go
internal/usage/consts.go
subsystem/cluster_test.go

This commit adds a feature flag for marking clusters that use dual-stack
networking. This enables us to collect statistics about usage of this
feature so that we are able to prioritize future developments in this
area.
Contributes-to: [MGMT-7507](https://issues.redhat.com/browse/MGMT-7507)
/cc @osherdp 

MGMT-7507: Add feature usage for dual-stack

---

models/api_vip_connectivity_response.go
restapi/embedded_spec.go
swagger.yaml

Added ignition property to api_vip_connectivity_response for populating when invoking apivip_check cmd in agent.
The ignition is required to fetch disk LUKS (disk encryption) information for workers in the cluster.
/cc @ybettan 
/cc @nmagnezi 
/cc @filanov 
/cc @rollandf 
/cc @avishayt 

MGMT-7428: added ignition to apivip check response in swagger

---

docs/events.yaml
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/common/events/events.go

This PR backports part of https://github.com/openshift/assisted-service/pull/2884 and cherry-picks https://github.com/openshift/assisted-service/pull/3049 to add an infra-env event when the image info is updated.
This is only relevant when we're using the image service (which is the case in stage currently).
https://issues.redhat.com/browse/MGMT-8532
https://issues.redhat.com/browse/MGMT-7254
https://issues.redhat.com/browse/MGMT-8504
On the original PRs
/cc @osherdp 
/cc @nmagnezi

MGMT-8532: Backport infra-env event handling for image service

---

Jenkinsfile
Makefile

Following openshift/release#21127, we now have unit-tests running via prow, which makes it redundant to run it also on Jenkins.
Also, it's redundant to include linting/testing before building the image, as those are non-dependent actions.
/cc @filanov 
/cc @lranjbar 
/hold

MGMT-7330: remove unit-test logic from Jenkins

---

internal/host/hostutil/test_utils.go
internal/host/validations_test.go
internal/host/validator.go
models/api_vip_connectivity_response.go
restapi/embedded_spec.go
swagger.yaml

Added disk encryption validation for day2 in host validator.
Introduced the following changed to host/validator:
* Added getDiskEncryptionForDay2 func for fetching LUKS (disk encryption) from the ignition, which should be available in APIVipConnectivityResponse.
* In diskEncryptionRequirementsSatisfied:
* Used luks info from the ignition for identifying disk encryption support for workers in the cluster.
* If TPM2 is enabled in the cluster for workers - ensure TPM2 is available in the host. Otherwise, the disk could be encrypted only using tang.
/cc @ybettan
/cc @nmagnezi
/cc @filanov
/cc @rollandf …

MGMT-7428: disk encryption validation for day2

---

client/installer/list_infra_envs_parameters.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
models/infra_env.go
restapi/embedded_spec.go
restapi/operations/installer/list_infra_envs_parameters.go
restapi/operations/installer/list_infra_envs_urlbuilder.go
subsystem/infra_env_test.go
swagger.yaml

This PR adds an optional cluster id parameter to the infra-env list endpoint (`/v2/infra-envs`).
When provided, the endpoint will only return infra-envs which are _directly_ related to the given cluster.
https://issues.redhat.com/browse/MGMT-8516
1. Deployed assisted-service locally on minikube
2. Created several infra-envs (some with cluster ids, some without)
3. Tested list infra-envs endpoint with and without cluster parameter
/cc @avishayt 

MGMT-8516: Allow filtering infra-env list by cluster id

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
subsystem/cluster_v2_test.go

When updating a host the cluster level validation may be affected. For example, when
changing a role of a host from master to worker the sufficient count validation may fail.
If the installation is confirmed quickly using the UI, it may fail with out a warning because
the monitor has no time to run again and execute the validations
This code make sure that the cluster validation runs when the host parameters are updated
without having to wait for the monitor
/cc @
/cc @

MGMT-8477: invoke cluster validations when updating host

---

tools/deploy_ui.py
tools/deployment_options.py

It seems like we're expecting docker images for a specific revision to be saved as ``<revision>`` instead of ``latest-<revision>``. The case for all our repositories should be the same, and it should be in the later pattern.
Also, using ``edge-infrastructure`` organization for the following images as well:
* assisted-service
* assisted-installer
* assisted-installer-controller
* assisted-installer-agent.
https://issues.redhat.com/browse/MGMT-8677
/cc @nshidlin 
/cc @hardengl 
/cc @eliorerz 

MGMT-8677: use "edge-infrastructure" organization for all images

---

cmd/main.go
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

When installing day2 hosts using the capi-provider-agent the provider saves the ignition endpoint CA cert and token in a secret.
Currently the agent_controller fail to get the token:
`"Failed to get user-data secret clusters-test-infra-cluster-fbe4fef1/user-data-test-infra-cluster-fbe4fef1-a7e8660f: Secret \"user-data-test-infra-cluster-fbe4fef1-a7e8660f\" not found`
The agent_controller is missing the rbac permissions to get secrets, yet that's not what caused the failure because the pod does have get, list & watch permissions for secrets thanks to the clusterdeployment_controller.
The root cause for this error is the secrets cache added [here](https://github.com/openshift/assisted-service/blob/76c1586d1a351af02e56205aece963298207ef76/cmd/main.go#L808)
In order to get the secret (that …

MGMT-8710: Assisted-service fail to get the agent ignition token

---

client/installer/download_cluster_i_s_o_responses.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
restapi/embedded_spec.go
restapi/operations/installer/download_cluster_i_s_o_responses.go
swagger.yaml

This PR backports https://github.com/openshift/assisted-service/pull/3023 for redirecting v1 downloads to image service. This is required to avoid failing when calling the service directly for downloading the discovery image.
This scenario is relevant for the 'cloud_hotfix_releases' branch since the deployment is actually done using 'master' branch - which means that the assisted-image-service is being used.
Specifically, this change fixes day2-periodic test in CI as that e2e test still uses v1 API.
/cc @carbonin 
/cc @osherdp 
/cc @filanov 

MGMT-8448: Redirect v1 image downloads to the image service

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

A possible race between the BE decision to assign role for automatic role and spec alignment
Kube Api should not update auto-assign role to BE after initialization phase
/cc @
/cc @

Bug 2029876: auto-assign node fails SpecSync

---

Makefile

Up until now, we've used a postgresql image that got copied once to our organization. It has the following disadvantages:
* Relying on manual updates being made to take latest image, or worse than that having an outdated image
* Potentially becoming an unplanned dependency for other software
This change should make all our podman deployment mode to use the upstream image.
/cc @filanov 
/cc @eliorerz 

MGMT-8724: use upstream postgres image for podman

---

internal/controller/controllers/infraenv_controller.go

Convert the code that computes the static addresses to use LabelSelectorAsSelector function
/cc @
/cc @

MGMT-8364: use LabelSelectorAsSelector for nmstate

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
internal/controller/controllers/controller_event_wrapper.go
internal/controller/controllers/controller_event_wrapper_test.go
internal/events/events_api.go
subsystem/kubeapi_test.go

With this change, both `ACI` and `Agent` controllers will use
the V2 Events endpoint for `DebugInfo.EventsURL`.
In addition, this change `controllerEventsWrapper` to use V2
Events instead of V1. Lastly, subsystem tests will now match
EventsURL with a relevant regex (to accommodate for auth
token additions) instead of asserting some non-empty value
in EventsURL.
/cc @filanov 
/cc @rollandf 
/cc @avishayt 

MGMT-8727: KubeAPI Controllers to use V2 Events endpoint

---

internal/provider/ovirt/base.go
internal/provider/ovirt/base_test.go
internal/provider/ovirt/ovirt_suite_test.go
internal/provider/vsphere/base.go
internal/provider/vsphere/base_test.go
internal/provider/vsphere/vshpere_suite_test.go

During discovery, host inventory may not be set yet, when checking for
supported platforms providers should consider this state and return
false in case host inventory is not populated
Once the inventorty is populated api will return all the supported
platforms
Added tests to ovirt and vsphere packages
/cc @rollandf 
/cc @osherdp 

MGMT-8713: fix ovrit and vshere platform check

---

hack/generate.sh

Onprem periodic jobs seem to have the following error:
```
File "<string>", line 7, in <module>
AttributeError: module 'yaml' has no attribute 'FullLoader'
make[1]: Leaving directory '/home/assisted/assisted-service'
make[1]: *** [Makefile:176: generate-configuration] Error 1
```
For example:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-onprem-periodic/1475264752438480896
It fails consistently, and this is probably because of an older pyYAML library that we have there.
The reason we don't have the updated library from ``./dev-requirements.txt`` is that we don't call ``make generate-configuration`` using ``assisted-service-build`` image, so we're left with what we have by …

NO-ISSUE: fix 'yaml' has no attribute 'FullLoader'

---

cmd/main.go
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
internal/controller/controllers/common.go
internal/controller/controllers/infraenv_controller.go
internal/controller/controllers/infraenv_controller_test.go
internal/gencrypto/token.go
subsystem/kubeapi_test.go

Populate EventsURL in InfraEnv
/cc @
/cc @

MGMT-8722: Populate EventsURL in InfraEnv

---

internal/cluster/cluster.go
internal/cluster/common.go
internal/cluster/common_test.go
internal/cluster/progress_test.go
internal/cluster/transition.go
internal/cluster/transition_test.go

In case 3 hosts and 2 workers are installed the cluster is considered installed
even if there are additional workers that fails to install
In such cases:
1. Add status_info message like  "Cluster is installed but some workers did not join"
2. Change the progress bar logic to return 100% if status is "installed"
In case 3 hosts and 2 workers are installed the cluster is considered installed
even if there are additional workers that fails to install
In such cases:
1. Add status_info message like  "Cluster is installed but some workers did not join"
2. Change the progress bar logic to return 100% if status is "installed"
/cc @
/cc @ …

MGMT-8698: update status_info, progress when extra workers fails to install

---

internal/bminventory/inventory.go

Set V2 link in cluster's HREF
/cc @
/cc @

MGMT-8513: V2 link in cluster's Href field

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

When checking if an agent image has changed, a full image name was compared to an image tag. This resulted in an agent update message being printed to the log even when the image remained the same. Example:
```
"Host 1cd887cd-fc53-4cae-9e6e-f1b5c5a66925 in infra-env 1b4bdb7b-cd30-4a92-a497-93bbbed1250e has outdated agent image quay.io/edge-infrastructure/assisted-installer-agent@sha256:cfdc7488e142c2d3c21d0aec58725e14fe8af798bb88346db6473106405af4a2, updating to cfdc7488e142c2d3c21d0aec58725e14fe8af798bb88346db6473106405af4a2"
```
Comparing the full image name used by a registering host to the full image name configured on the service should solve the problem and produce an agent update message only when there was an actual change in agent image or version.
The message is used for …

MGMT-8741: Use full name when logging agent update

---

cmd/main.go

This PR backports part of https://github.com/openshift/assisted-service/pull/2708.
It is required since we use the new operator scripts also in release-ocm-2.4 branch
of assisted-test-infra: https://github.com/openshift/assisted-test-infra/pull/1276.
I.e. the OPENSHIFT_VERSIONS var should be optional since the operator deployment
script is specifying only OS_IMAGES and RELEASE_IMAGES in release-ocm-2.4 branch
of assisted-test-infra.
/cc @eliorerz 
/cc @osherdp 
/cc @filanov 

MGMT-7705: ignore empty OpenshiftVersions

---

README.md

For some reason generator.swagger.io url parameter is not working anymore
Switching the link to petstore.swagger.io works
/cc @avishayt 
/cc @

NO-ISSUE: fix swagger UI link

---

internal/cluster/transition_test.go
internal/cluster/validator.go
internal/network/cidr_validations.go
internal/network/utils.go

Fix current validation logic so it detects overlapping
Cluster and Machine Networks.
/cc @
/cc @

MGMT-8748: detect overlapping networks in SNO

---

hack/generate.sh
hack/setup_env.sh

Currently, we are unable to run ``make generate-configuration`` on prow without relying on leasing a packet server. The reason is that either docker or podman usage on prow's pods is unsupported (maybe even not possible).
This change will install ``butane`` binary, which is the new name of ``fcct``. it then use it just the same way we used it to generate the ignition, minus the redundant bind volumes.
It will also make sure we verify everything we install via ``yum`` is actually available to install, and remove the unavailable (for the specific distribution we use) ``libvirt-clients`` package.
/cc @eliorerz  …

Replace docker usage with binary installation for conf generation

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

[MGMT-8755](https://issues.redhat.com/browse/MGMT-8755): remove mco image , must-gather and openshift version from day2 installation command.
Those params are relevant only for day1 bootstrap flow and are not used
at all at any other
- [] None
/cc @
/cc @

MGMT-8755: remove mco image , must-gather and openshift version from day2 installation command.

---

internal/common/events/events.go
internal/events/api/event.go
internal/events/api/mock_event.go
internal/events/eventstest/events_test_utils.go
internal/host/hostutil/update_host.go
internal/host/hostutil/update_host_test.go
tools/generate_events.py

Event messages on the assisted installer UI have redundant text in them, this text should be removed.
Steps to reproduce:
Install cluster 
Get events
Examples:
"Host master-0-0: updated status from preparing-successful to installing Installation is in progress(Installation is in progress)"
"Host master-0-0: updated status from installing to installing-in-progress Starting installation(Starting installation)"
The fix removes the duplication while leaving brackets around the status, the messages above will look like
"Host master-0-0: updated status from preparing-successful to installing (Installation is in progress)"
"Host master-0-0: updated status from installing to installing-in-progress (Starting installation)"
In addition to this update, changes have been made to tests to allow us to …

MGMT-8510: Duplicate hosts status messages on events

---

internal/operators/cnv/manifest.go
internal/operators/cnv/manifests_test.go
internal/operators/lso/manifest.go
internal/operators/lso/manifests_test.go
internal/operators/ocs/manifest.go
internal/operators/ocs/manifests_test.go
internal/provider/ovirt/consts.go

Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>
Using the 99_ prefix disables the option for users to override default configuration.
Users should be able to override everything.
/cc @filanov 
/cc @pkliczewski 

MGMT-8851: Remove 99_ prefix from manifests

---

pkg/auth/local_authenticator.go

[MGMT-5425](https://issues.redhat.com/projects/MGMT/issues/MGMT-5425): When either `InfraEnv` or `Cluster` objects don't exist, the local authenticator keeps spamming logs that they don't exist. This PR removes those logs.
/cc @carbonin 
/cc @tsorya 

MGMT-5425: stop spamming logs from local authenticator

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go

Previously the proxy env vars were provided to the the assisted service, but not to the image service.
https://bugzilla.redhat.com/show_bug.cgi?id=2038903
Deployed with the operator, set the proxy values on the subscription and make sure they're set on the image service.
/cc @flaper87 
/cc @nmagnezi

Bug 2038903: Add proxy env vars to image service

---

deploy/assisted-installer-ingress-tls.yaml
deploy/assisted-installer-ingress.yaml

The v1beta1 API for Ingress was deprecated in k8s 1.19 and removed in
1.22. OCP 4.9 is based on k8s 1.22, so these manifests stopped working
and caused `make deploy-all` to fail.
I tested these changes by running `make deploy-all TARGET=oc-ingress`
successfully.
https://issues.redhat.com/browse/MGMT-8871
- [] None
`make deploy-all TARGET=oc-ingress`

MGMT-8871: updates Ingress usage to v1

---

docs/pull_request_template.md

* Remove the initial headers since not many people actually re-arrange the description under the right section
* Add an enhancement option to the list of changes types
* Make the reviewers checklist just a bullet list
/cc @
/cc @

NO-ISSUE: Minor clean up to the PULL_REQUEST template

---

cmd/main.go
openshift/template.yaml
pkg/app/middleware.go
pkg/app/middleware_test.go

This will allow us to easily ensure that clients are no longer using v1
without removing the implementation entirely
/cc @osherdp 
/cc @filanov

NO-ISSUE: Add a middleware to optionally disable v1 API

---

Dockerfile.assisted-service-build

Fix issue when `assisted_service_build` image can't find minikube
```
$ minikube status
E0112 13:26:37.720563 1062458 status.go:261] The "minikube" host does not exist!
minikube
type: Control Plane
host: Nonexistent
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Nonexistent
```
/cc @osherdp 

NO-ISSUE: Fix assisted_service_build image can't find minikube

---

internal/migrations/20220113152127_change_cluster_ssh_key_to_text.go
internal/migrations/20220113152127_change_cluster_ssh_key_to_text_test.go
internal/migrations/migrations.go

Previously this was varchar(1024) but we should be able to support ssh
keys larger than that.
This was fixed for new deployments in
dcae87ef02533706758fda476dc999e065539a7f, but that commit didn't add a
migration. This means that the SaaS environments still have the old
column types.
https://issues.redhat.com/browse/MGMT-8085
- Deployed the service locally with an edit to the swagger yaml to not automigrate the column in question to text
- Built and deployed an image from this branch
- Observed the column get migrated to the new type
/cc @filanov 
/cc @osherdp 

MGMT-8085: Change the cluster ssh_public_key field to text type

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

* Check the number of active hosts instead of
'HighAvailabilityMode' for SNO discovery.
* Return platform 'none' when it's an SNO or
there are no enabled hosts.
/cc @flaper87 

OCPBUGSM-38736: Fix 'supported-platforms' endpoint

---

go.mod
go.sum

Removed github.com/coreos/etcd from go.mod as it's not directly used (still in go.sum since used indirectly by other packages).
/cc @osherdp 
/cc @filanov 
/cc @rollandf 

NO-ISSUE: remove unused etcd pkg from go.mod

---

deploy/operator/ztp/agentClusterInstall.j2

This commit fixes the AgentClusterInstall template used by the CI jobs.
In its current form the template generates a wrong template when applied
to a dual-stack cluster, i.e.
```
serviceNetwork:
- 172.30.0.0/16
userManagedNetworking: false
- fd02::/112
```
The initial change has been introduced in #3084.
/cc @flaper87 
/cc @filanov 

MGMT-8664: Fix ACI template breaking dual-stack configuration

---

internal/common/common.go
internal/ignition/ignition.go

This commit simplifies confguration of the Network Manager in case IPv6
is used. Till now we were
* configuring consistent DHCPv6 client identification
* creating system-connections-merged overlay configuration
* manually configuring keyfile path
We are able to simplify this flow for the following reasons
* with the introduction of InfraEnvs, the static network configuration
is now a property of InfraEnv and not of a cluster
* RHCOS handles creation of systemConnectionMerged whenever needed and
if so, it handles configuration of the keyfile paths
Until now, the configuration applied by Assisted Service was not causing
problems as in RHCOS <=4.9 the keyfile paths were overriden whenever a
different overlay directory has been created.
Starting from RHCOS 4.10 this is no longer the case and …

MGMT-8894: Simplify IPv6 Network Manager configuration

---

internal/common/common_test.go
internal/ignition/ignition.go

This commit extends the OCP version used when comparing in order to
comply with rules of the semantic versioning and release naming schema
in OCP.
This is because only "4.10" does not catch "4.10.0-fc.1" nor e.g. a
nightly release "4.10.0-0.nightly-2022-01-23-013716" - as per rules,
pre-releases have lower priority over normal versions.
In order to catch all of those, we are comparing against
"4.10.0-0.alpha" so that we cover FC releases as well as nightlies.
Closes: [MGMT-8894](https://issues.redhat.com/browse/MGMT-8894)
Closes: Bug-2030289
Relates-to: Bug-2040195
/cc @nshidlin  …

MGMT-8894: Catch FCs and nightlies when comparing OCP versions

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

BMAC was using the agent spec's role field rather than the status. This worked fine because, so far, it's
been a requirement to set the role annotation for the BMH. However, if this annotation is not set, the service
will auto-dected the role of the host, which means the spec's role field will remain empty, while the status' one
will be correctly populated.
Since the status role field is always populated, BMAC should just stick to using that to know what role the agent is.
/cc @

NO-ISSUE: Use agent's status role instead of spec

---

config/rbac/base/role.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
pkg/leader/leaderelector.go
subsystem/leader_test.go

A leader is currently locked over ConfigMap resource. This kind of
locking mechanism is deprecated in favor of using Leases
Replace the current lock with LeaseLock and clear the current
ConfigMap that is currently being used for the locking mechanism
On rolling upgrade, the existing leader will lose the leadership
and one of the newly upgraded instances will take the lead
/cc @
/cc @

MGMT-8582: Leader elector to use leases

---

internal/bminventory/inventory.go
internal/bminventory/inventory_v2_handlers.go

[MGMT-8744](https://issues.redhat.com/browse/MGMT-8744): Add log indicating that with auth none image url will not change
When using authorisation types "local" and "RHSSO"; it is expected that the ISO image URL will change due to digital signatures added to the URL.
When using an authorisation type of "none" this is not expected. It is desired that we notify the user in the log that the URL will not be changing.
This change seeks to address that.
- [ X] Enhancement 
- [] None
* This was tested manually by first running the unit-tests and subsystem tests to check for any regressions, none were found.
* Then a manual test was applied to verify that this change affects the log output by deploying the dev test environment locally and then monitoring logs with...
`kubectl …

MGMT-8744: Add log indicating that with auth none image url will not change

---

cmd/main.go
docs/hive-integration/kube-api-select-ocp-versions.md
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/versions/mock_versions.go
internal/versions/versions.go
internal/versions/versions_test.go

Added support to maintain OS and release images with cpu_architecture in major.minor.patch format. This functionality is a means to allow multiple z-stream versions concurrently, instead of the previous behaviour which limited a single z-stream for every y-stream.
The following changes were made in versions package in order to introduce the new behaviour:
* GetReleaseImgae:
* Returns an image based on the specified x.y.z.
* If missing, fallback to x.y (as previously).
* GetOsImage:
* Returns an image based on the specified x.y.z.
* If missing, fallback to x.y (as previously).
* If x.y is not available, try to find the latest applicable image for the specified x.y.z. This is done to avoid forcing a direct version match between OS and release image. E.g. for kube-api custom z-stream release …

MGMT-8783: support multiple patch versions of os/release images

---

internal/versions/versions.go
internal/versions/versions_test.go

Use the previous behaviour of using the OpenshiftVersion as key in /openshift-versions API.
This would avoid an failure in test-infra on release image override flow, as the version
is truncated to x.y:
https://github.com/openshift/assisted-test-infra/blob/b3888faa715871a5e6b56df23f72a85f0d247aa3/src/assisted_test_infra/test_infra/utils/utils.py#L497
/cc @osherdp 
/cc @eliorerz 

NO-ISSUE: use OpenshiftVersion as key in openshift-versions API

---

docs/operator.md
internal/controller/controllers/agentserviceconfig_controller.go

[Bug 2034686](https://bugzilla.redhat.com/show_bug.cgi?id=2034686): Expose a way for users to disable TLS verification in image service through the agent service config. 
/cc @carbonin 
/cc @flaper87 

Bug 2034686: Expose a way for users to disable TLS verification in image service through the agent service config

---

deploy/operator/common.sh

When installing spoke cluster with ZTP flow, the installation scripts
sorts and selects the OS images by openshift version which is a string.
In this case version "4.9" is considered higher than "4.10".
The fix trasforms the version to array of numbers where the comparison
behaves as expected.

MGMT-9070: ZTP versions are not compared correctly for sorting and filtering

---

internal/bminventory/inventory.go
internal/ignition/ignition.go

We need temporary solution to install arm with baremetal platform till openshift-baremetal-installer multi-arch version will not be added to arm payload as it is done with openshift-install.
We decided to add os env with option to override release image for extracting openshift-baremetal-install as temporary solution and with minimum code changes .
It should be visible that this is officially unsupported solution and will be used only in specific custom podman installations 
/cc @avishayt 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributor …

MGMT-9096: Add temporary solution to install baremetal arm on 4.10

---

internal/common/common.go
internal/ignition/ignition.go

This commit simplifies confguration of the Network Manager in case IPv6
is used. Till now we were
* configuring consistent DHCPv6 client identification
* creating system-connections-merged overlay configuration
* manually configuring keyfile path
We are able to simplify this flow for the following reasons
* with the introduction of InfraEnvs, the static network configuration
is now a property of InfraEnv and not of a cluster
* RHCOS handles creation of systemConnectionMerged whenever needed and
if so, it handles configuration of the keyfile paths
Until now, the configuration applied by Assisted Service was not causing
problems as in RHCOS <=4.9 the keyfile paths were overriden whenever a
different overlay directory has been created.
Starting from RHCOS 4.10 this is no longer the case and …

Bug 2049034: Simplify IPv6 Network Manager configuration

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/controller/controllers/infraenv_controller.go
internal/versions/versions.go
internal/versions/versions_test.go
models/infra_env_create_params.go
restapi/embedded_spec.go
subsystem/day2_cluster_test.go
subsystem/host_v2_test.go
subsystem/infra_env_test.go
swagger.yaml

When creating an infraenv, openshift_version should be optional:
* Removed openshift_version from required properties of infra-env-create-params.
* Register infraenv already fallbacks to latest OS image when OpenshiftVersion
is not specified - fixed getOsImageOrLatest to use semantic version comparison.
/cc @tsorya 
/cc @filanov 
/cc @osherdp 

MGMT-7709: optional openshift_version in infraenv

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
subsystem/day2_cluster_test.go

On day2 the image is taken from the infraenv when the host is added.
Day2 cluster should not contain the architecture and should not infer
the image.
Those calculations are done exclusively in V2InstallHost
and ISO generation is /v2/infraenvs
/cc @
/cc @

MGMT-8524: support day2 cpu arm arc

---

internal/ignition/ignition.go
internal/ignition/ignition_test.go

Set overwrite as true for /etc/hostname file in ignition.
Kept the default value[*] for the other included files.
[*] https://coreos.github.io/ignition/migrating-configs/#files-now-default-to-overwritefalse
/cc @carbonin 
/cc @filanov 

MGMT-9009: enable overwrite for hostname in ignition

---

go.mod
go.sum
internal/host/hostcommands/install_cmd_test.go
internal/host/hostcommands/logs_cmd_test.go

Ginkgo run specs in a random order, setting global variables can affect
results or expectations between different tests
Fix setting global variable in a log_cmd_test.go to copy the config
struct and setting values on the copy
Add coverage to install_cmd.go by testing with and without CA certificate
settings

NO-ISSUE: fix ut inconsistency

---

internal/bminventory/inventory_v2_handlers.go

This log does not indicate an issue, just information for the user,
there's no good reason for it to be a warning
Originally added in 224c267c321d6fb1120941bbce443bdbb94961b3
Changing this was previously suggested in this comment that came in too late
https://github.com/openshift/assisted-service/pull/3246#discussion_r793383981
Some users were complaining about this log thinking it was the cause
for the issues they were having
/cc @filanov …

MGMT-8744: Change image URL auth type log from warning to info

---

.codecov.yml

Don't wait for all the CI jobs to complete to send the coverage report.
We will then get the coverage as soon as the unit tests have run.

NO-ISSUE: Don't wait for CI to update coverage

---

internal/bminventory/inventory.go
internal/cluster/common.go

[MGMT-8853](https://issues.redhat.com/browse/MGMT-8853): Prevents conflict errors with machine networks table in database.
**Context**: Subsystem tests were failing due to the infrequent error
```
time="2022-02-02T00:45:24Z" level=error msg=updateClusterData func="github.com/openshift/assisted-service/internal/bminventory.(*bareMetalInventory).updateClusterInternal" file="/go/src/github.com/openshift/origin/internal/bminventory/inventory.go:2403" cluster_id=fbf88971-6338-4be3-b6e1-0c4a6ccd3e14 \
error="failed to update machine network {1.2.3.0/24 fbf88971-6338-4be3-b6e1-0c4a6ccd3e14} of cluster fbf88971-6338-4be3-b6e1-0c4a6ccd3e14: ERROR: duplicate key value violates unique constraint \"machine_networks_pkey\" (SQLSTATE 23505)" go-id=127982 pkg=Inventory …
```

MGMT-8853: Prevents machine networks conflict errors

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/network/cidr_validations.go

When an empty CIDR is passed to one of the CIDR validations,
the function net.ParseCIDR return and error 'nvalid CIDR address'
This was misleading because there were cases that by mistake the user
thought other parameters are wrong such as illegal network prefix size.
In case such error occures in CIDR validations, it will be preceeded
by "Failed to parse CIDR '%s'" which will make it clearer.
This handles this bug https://bugzilla.redhat.com/show_bug.cgi?id=2007723
and https://bugzilla.redhat.com/show_bug.cgi?id=2007730
/cc @filanov  …

OCPBUGSM-35526: Failed validation: Machine network CIDR : invalid CIDR address

---

subsystem/cluster_test.go
subsystem/ipv6_test.go

As a prerequisite for deleting v1 Register Cluster API, this PR
converts updates of host role from UpdateCluster API (deprecated v1) to
V2UpdateHost.
This conversion is needed since once v1 RegisterCluster is removed, the
entire register cluster flow should be converted to v2. Otherwise,
subsystem tests will fail.
/cc @
/cc @

MGMT-9109: convert update role to v2 in subsystem

---

cmd/main.go
pkg/app/middleware.go
pkg/app/middleware_test.go

This commit removes the code to upload the template images to S3 which
is only done when the image service is not being used.
Additionally this ensures that the image service base URL is set on
startup.
https://issues.redhat.com/browse/MGMT-8447
Deployed the app with this patch to minikube, created an infra-env and downloaded an iso.
/cc @nmagnezi 

MGMT-8447: Remove template image upload code

---

Makefile
data/default_okd_os_images.json
data/default_okd_release_images.json
deploy/podman/README.md
deploy/podman/okd-configmap.yml
hack/generate.sh
internal/ignition/ignition.go

This PR adds assisted-installer support for OKD clusters. Most notable difference between OCP and OKD install is that OKD starts with Fedora CoreOS instead of RHCOS. FCOS doesn't have kubelet/crio/mcd (but has podman), so in order to make bootstrap work on live CD we do the following:
* pull an image with RPMs (`OKD_RPMS_IMAGE` env var)
* create an overlayFS for `/usr` (as its read-only on rpm-ostree systems)
* extract RPMs from the image and use `rpm` to install them
* expand `/var` and `/run` partitions to 6 GB (in FCOS these partitions are 3.2 GB for 16 GB VM which is insufficient for bootstrap to complete)
* hold off agent.service until RPMs are installed
* add fake `systemd-journal-gatewayd.socket` (required from `mcd --once-from` to complete, as FCOS doesn't have journal gateway …

NO-ISSUE: Add OKD support

---

internal/bminventory/inventory.go
internal/host/validations_test.go
internal/host/validator.go
subsystem/day2_cluster_test.go

The root cause of the problem was that a day2 cluster had an empty disk encryption configuration while a day2 host was created with an auto-assign role.
The empty disk encryption configuration caused the disk encryption validation to execute. At the same time, a mix of day1 and day2 logic in the validation's code failed the validation due to an absent role.
The fix is to separate day2 from day1's logic in the validation  (day2 logic does not need role assertion) and specifically assign a worker role to day2 hosts.
The latter will also prevent future problems stemming from validations that pends on role assignment.
/cc @
/cc @ …

MGMT-9233: disk validation fails for day2 hosts

---

subsystem/ams_subscriptions_test.go
subsystem/authz_test.go
subsystem/cluster_test.go
subsystem/manifests_test.go
subsystem/metrics_test.go
subsystem/operators_test.go
subsystem/utils_test.go

Prepare for converting tests to use v2 RegisterCluster by making sure that all register host utilities in subsystem use infraEnvID for host manipulation and clusterID for cluster manipulation.
Right now the same ID serves for both purposes, but this will change with the main PR that will introduce the new cluster/infraenv flow
/cc @
/cc @

MGMT-9109: separate clusterID and infraenvID in register host utils

---

internal/bminventory/inventory.go
internal/host/validations_test.go
internal/host/validator.go
subsystem/day2_cluster_test.go

This hotfix contains to fixed in master:
-  [MGMT-9233](https://issues.redhat.com/browse/MGMT-9233): set MachineConfigPoolName for day2
-  [MGMT-9233](https://issues.redhat.com/browse/MGMT-9233): disk validation fails for day2 hosts
/cc @
/cc @

Fix disk encryption role error in day2

---

internal/bminventory/inventory.go
subsystem/day2_cluster_test.go

In V2RegisterHost day2 flow, MachineConfigPoolName was previously set to worker only if the role was auto-assign.
As we set role to worker in day2 flow, fixed it by setting MachineConfigPoolName explicitly to worker when the host is registered.
/cc @osherdp 

MGMT-9233: set MachineConfigPoolName for day2

---

pkg/leader/leaderelector.go
subsystem/leader_test.go

A leader is currently locked over ConfigMap resource. This kind of
locking mechanism is deprecated in favor of using Leases
Replace the lock with LeaseLock and clear any configmaps
that were previously being used for the locking mechanism
RBAC permissions were submitted in an earleir PR to
ensure framework readiness
/cc @
/cc @

MGMT-8582: Leader elector based on lease lock

---

internal/ignition/ignition.go

16GB VM creates 3.2GB /var partition. Larger nodes however create bigger partitions, so downsizing /var to 6GB breaks the install. This commit ensures that we resize /var only if necessary
https://kubernetes.slack.com/archives/C6AD6JM17/p1644846272611069
/cc @omertuc 

NO-ISSUE: OKD: expand /var if its less than 6GB

---

docs/user-guide/rest-api-v1-v2-transition-guide.md
internal/bminventory/inventory.go
internal/domains/managed_domains.go
internal/domains/managed_domains_test.go
internal/versions/versions.go
internal/versions/versions_test.go
pkg/auth/authz_handler_test.go
subsystem/cluster_test.go
subsystem/image_test.go
subsystem/subsystem_suite_test.go
subsystem/versions_test.go

This change does the following:
- Remove `GetClusterHostRequirements`: Deprecated in favor of `GetPreflightRequirements`.
- `GetPreflightRequirements`: changed to `v2GetPreflightRequirements`.
- `ListManagedDomains`: changed to `V2ListManagedDomains`.
- `ListComponentVersions`: changed to `v2ListComponentVersions`.
- `ListSupportedOpenshiftVersions`: changed to `v2ListSupportedOpenshiftVersions`.
- Updates the doc `rest-api-v1-v2-transition-guide.md`.
/cc @
/cc @ …

MGMT-9131: Remove V1 GetClusterHostRequirements, GetPreflightRequirements, ListManagedDomains, ListComponentVersions, ListSupportedOpenshiftVersions

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

[MGMTBUGSM-98](https://issues.redhat.com/browse/MGMTBUGSM-98)
Originally when populating the logs URL in the agent CR, there
was no check for the clusterID so if there was a nil clusterID
then assisted service would go into a crash loop.
This change moves the logic for populating the logs URL under
the check for the cluster ID.
To be tested in @jelkosz's environment
/cc @carbonin 
/cc @filanov 
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTI …

MGMTBUGSM-98: Prevent nil pointer error when cluster ID is nil.

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
subsystem/cluster_test.go

This is a pre-requisite code for removing V1 RegisterCluster.
Updating hostname is now done via V2UpdateHost rather than via UpdateCluster
/cc @
/cc @

MGMT-9134: convert update hostname to v2 in subsystem

---

internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/host/validator.go
internal/network/manifests_generator.go
internal/network/manifests_generator_test.go
internal/network/mock_manifests_generator.go

If SNO DNSMasq manifest is not enabled, validator should check that external api/api-int domain exists. This is mostly useful for OKD SNO, where dnsmasq hack won't work - it uses systemd-resolved and dnsmasq is not included.
/cc @omertuc 
/cc @eranco74 

NO-ISSUE: validate api/api-int when ENABLE_SINGLE_NODE_DNSMASQ is not set

---

subsystem/cluster_test.go
subsystem/host_test.go
subsystem/metrics_test.go

This is a pre-requisite code for removing V1 RegisterCluster.
EnableHost/DisableHost are APIs that were replaced in V2 by either unbinding to deregistration. Once we move to use V2 RegsiterCluster, the subsystem tests can no longer use those APIs.
This PR deletes the tests that aim to check EnableHost/DisableHost flow because we will soon remove those flows from the BE.
In other cases, DisableHost was used to induce an error. In these cases, the test generates another type of error instead or uses V2DergisterHost API to remove the host altogether.
V2UnbindHost API can not replace DisableHost because the InfraEnv in the tests is bound to a cluster. It is illegal to unbound a host from such an InfraEnv.
The coverage rate may be reduced by this PR, but this will be soon corrected by removing …

MGMT-9122: Remove DisableHost from subsystem

---

docs/hive-integration/agent-labels.md
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

First, set an annotation with the inventory hash so that it is not computed on every single reconcile.
Second, add 3 inventory-based labels as a starting point:
1. storage-nonrotationaldisk (boolean): true if host has at least 1 SSD, aligns to NFD
2. cpu-architecture (string): The host's CPU architecture, does not exist in NFD
3. cpu-virtsupport (boolean): true if the CPU has the VMX or SVM flag on, does not exist in NFD
Third, add a label version annotation currently set at 0.1 so that clients can know what labels to expect.
/cc @
/cc @ …

MGMT-9223: Automatic agent inventory labels

---

internal/common/test_configuration.go
internal/host/hostcommands/container_image_availability_cmd_test.go
internal/versions/versions.go
internal/versions/versions_test.go
models/openshift_version.go
restapi/embedded_spec.go
swagger.yaml

* Removed unused properties: release_image/release_version/rhcos_image/rhcos_rootfs/rhcos_version
* Define required properties: display_name/support_level/cpu_architectures
/cc @filanov 
/cc @osherdp 
/cc @batzionb

MGMT-9185: clean openshift-version object in swagger

---

internal/controller/controllers/infraenv_controller.go
internal/controller/controllers/infraenv_controller_test.go

Currently, an InfraEnv takes all nmstateconfigs in namespace if no
selector is specified
Original behavior:
1. Create an NMStateConfig
2. Create an InfraEnv without any selectors
3. Infraenv uses the NMStateConfig
New behavior:
1. Create an NMStateConfig
2. Create an InfraEnv without any selectors
3. Infraenv doesn't use the NMStateConfig
InfraEnv should not use any NMStateConfig if no NMStateConfig selectors
are specified on it
If the user didn't specify any labels, it's probably because they don't
want any NMStateConfigs, not because they want *all of them*.
/cc @slaviered
/cc @nmagnezi …

MGMT-9416 - InfraEnv should not use any NMStateConfig if no selector is specified

---

internal/bminventory/inventory_test.go
internal/cluster/installer_test.go
pkg/auth/authz_handler_test.go

This PR converts usages of UpdateCluster for host-related
parameters to v2 V2UpdateHost
- Tests that have exact parallels in v2 are removed
- Other tests are merged with v2 update host tests
- Setting hostname in v2 SNO should no longer return an error
/cc @
/cc @

MGMT-9110: v1 host related UpdateCluster to v2

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/ignition/ignition.go
internal/ignition/ignition_test.go
pkg/generator/generator.go
pkg/generator/mock_install_config.go

[MGMT-9206](https://issues.redhat.com/browse/MGMT-9206): Allow arm baremetal platform installation 
We want to allow baremetal platform installation on saas, for this we require  to override release image from which we will extract baremetal installer to the x86 one
This pr adds functionality to override arm image with x86 in case
ALLOW_INSTALLER_RELEASE_IMAGE_OVERRIDE env param is set to true, default
is false.
In case of arm and bm platform were choosed, we will get x86 release
image of the same version and extract openshift-baremetal-installer executer from it.
/cc @avishayt 
/cc @eranco74  …

MGMT-9206: Allow arm baremetal platform installation

---

docs/enhancements/ipxe-host-boot.md

Not all user infrastructure is able to boot isos directly, and iPXE is a commonly
used alternative for booting machines. We should support this by making the
application directly serve iPXE artifacts so that systems can boot with no
other iPXE infrastructure required.
https://issues.redhat.com/browse/MGMT-9383
/cc @mhrivnak 
/cc @avishayt 
/cc @filanov 
/cc @flaper87 
/cc @dtantsur 

MGMT-9383: Add enhancement doc for iPXE boot

---

internal/operators/cnv/cnv_operator.go
internal/operators/cnv/cnv_operator_test.go
pkg/conversions/conversions.go

Fix OpenShift Virtualization disk validation message to display size in GB instead of Gi
(We expect GB since AI is aligned to GB when it comes to storage).
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>
/cc @lalon4 
/cc @

MGMT-9014: Fix OpenShift Virtualization disk validation message for HPP disk

---

internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
subsystem/kubeapi_test.go

Detect key conflict when looping over data in each ManifestsConfigMap.
Spec sync status should be changed to error in case of a conflict.
(see discussion in the support [PR](https://github.com/openshift/assisted-service/pull/3342#discussion_r805353501))
/cc @filanov 
/cc @avishayt 
/cc @mhrivnak
/cc @2uasimojo 

MGMT-9485: validate manifests names uniqueness specified in configmaps

---

Dockerfile.assisted-service
hack/generate.sh

Fix mismatch swagger-codgen versions. 
Since v2.4.19 the client Configuration object was created multiple times adding each time a new logging handler causing multiple log lines per entry.
/cc @eliorerz 
/cc @

MGMT-9541: Fix mismatch swagger-codgen versions. Set both versions to v2.4.18

---

README.md

Local minikube environment won't boot without `minikube tunnel` active, as some services type `LoadBalancer` are deployed.
Added documentation to hint at starting `minikube tunnel`
- [ X] Documentation
- [ X] Title and description added to both, commit and PR.

improve docs: mention minikube tunnel

---

client/installer/v2_download_infra_env_files_responses.go
docs/enhancements/ipxe-host-boot.md
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
restapi/embedded_spec.go
restapi/operations/installer/v2_download_infra_env_files_parameters.go
restapi/operations/installer/v2_download_infra_env_files_responses.go
swagger.yaml

As described in [the enhancement](https://github.com/openshift/assisted-service/blob/c5eacda676475f5a6de123678c1af353a2368bd3/docs/enhancements/ipxe-host-boot.md
) this PR implements the ipxe-boot script download endpoint.
Specifically `GET /v2/infra-envs/{infra-env-id}/downloads/files?file_name=ipxe-script`.
Deployed assisted service locally with podman, created an infra-env, called the new endpoint.
/cc @filanov 

MGMT-9334: Add an endpoint to download an ipxe-boot script

---

internal/network/manifests_generator.go
internal/network/manifests_generator_test.go

This PR addresses issue [MGMT-8824](https://issues.redhat.com/browse/MGMT-8824). 
When a user defined [additional NTP sources](https://github.com/openshift/assisted-service/blob/master/swagger.yaml#L6976) (or via the [InfraEnv](https://github.com/openshift/assisted-service/blob/master/api/v1beta1/infraenv_types.go#L57) CR), only the sources that were in state `synchronized|synced` were copied into the respective [chrony](https://chrony.tuxfamily.org/) manifest, if any. Which resulted in the additional NTP sources missing from the chrony sources altogether. 
With this change, all user defined additional NTP sources, irrespective of their state, are copied into the chrony manifest and are reflected in the chrony sources.
> The possible source states can also be found …

MGMT-8824: Copy additional NTP sources to chrony manifests

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
subsystem/kubeapi_test.go

Ensures that label values are valid and updates the Agent CR when labels
are added/changed.
/assign @nmagnezi 

MGMT-9550: Fix automatic agent inventory labels

---

deploy/operator/mirror_utils.sh
deploy/operator/setup_assisted_operator.sh

In this PR we try to address are multiple problems when running e2e-metal-assisted-operator-disconnected CI job
Most of the problem arise only while running in disconnected mode:
- The assisted service operator catalog name is different while disconnected, and this needs to be consistent throughout the code
- If OS_IMAGES has multiple entries, all of them need to be mirrored
- While handling multiple mirrored artifacts we need to keep their full url path on the mirror to prevent name collisions
- Mirrored OS_IMAGES have to be added to AgentServiceConfig to override the default ones
- Due to a bug in hive, the condition that checks that ClusterDeployment is installed needs longer wait time
/cc @
/cc @
- Is there …

MGMT-8809: Fix e2e-metal-assisted-operator-disconnected CI job

---

deploy/olm-catalog/pin-latest.py
deploy/olm-catalog/requirements.txt

This script replaces occurrences of operand container image "URL"s in the
assisted operator's CSV manifest which have a `:latest` tag with "URL"s
that use a `@sha256:<hash>` tag instead. The hash chosen is simply the
hash of the image manifest that's currently behind `:latest` at the time
of running that script.
This script is going to be used by a work-in-progress prow job whose
purpose is generating an operator bundle image + catalog index image
containing said bundle image and pushing them to a public repository
in quay.io so it can be used by our test workflows and local
development.
/cc @
[Kubernetes …

MGMT-9470 - Add a pin-latest.py script that pins catalog dependencies

---

hack/setup_env.sh

building assisted-service-build in ci fails sporadically
with the message:
Cannot retrieve metalink for repository: epel/x86_64
cleaning the cache and updating certificates was recommended as
the course of action to reduce the probability of such an error
/cc @
/cc @

NO-ISSUE: sporadic ci failure to get epel metadata

---

internal/host/host.go
internal/metrics/metricsManager.go
internal/metrics/mock_metrics_manager_api.go
subsystem/metrics_test.go

Currently post step reply for connectivity check stores metrics for
packet loss and latency to all other hosts in the cluster.
In case there are 100 hosts in the cluster, 20000 metrics will be saved
(100\*100\*2).
Since these metrics is not used, and saving them cause a lot of load,
they will be removed.
/cc @filanov 
/cc @

MGMT-9277: Optimize connectivity check post step reply to improve load for large multi-node clusters

---

Makefile
hack/generate.sh

When doing things like `make generate-python-client`, we instructed
docker to map the local user into the container, so that the files will
have the right ownership after the Docker part of the build.
In podman, when running it rootless (there's no reason why we'd ever
need to run those steps with root podman), root inside the container is
already the right user outside of the container, so we need to prevent
this setting from applying.
The commit also makes sure that if you have the docker command supported
with podman, it will detect rightly that it is podman you are using.
Yes, preferably by somebody using either docker and/or podman in Linux and Mac OS 
Yes
It was tested on Fedora 35 with …

NO-ISSUE: generate support rootless podman

---

pkg/validating-webhooks/hiveextension/v1beta1/agentclusterinstall_admission_hook.go
pkg/validating-webhooks/hiveextension/v1beta1/agentclusterinstall_admission_hook_test.go

ImageSetRef is immutable after creating an AgentClusterInstall, hence, added a proper validation in the ValidatingAdmissionHook. When updating ImageSetRef an error as follows should be displayed:
admission webhook "agentclusterinstallvalidators.admission.agentinstall.openshift.io" denied the request: Attempted to change AgentClusterInstall.ImageSetRef which is immutable
/cc @filanov 
/cc @tsorya 
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBU …

MGMTBUGSM-112: validate ImageSetRef in ACI webhook

---

deploy/olm-catalog/pin-latest.py

Make the script compatible with Python 3.6 because it is the version
available in the base iamge we are using for developement and CI
(registry.ci.openshift.org/openshift/release:golang-1.17).

MGMT-9470: Make script to pin catalog compatible with python 3.6

---

deploy/olm-catalog/pin-latest.py

When publishing the Infrastructure Operator bundle and catalog to quay
for the master branch, we scan the operator's manifests
(clusterserviceversion in particular) for the "latest" tag and pin it to
a particular image manifest digest. This is done using the pin-latest.py
script and the choice of "latest" tag is hardcoded in that script.
We would like to use the same script for doing similar pinning but for
our release branches. In those release branches, the CSV manifest
doesn't have :latest tags, it has, for example, ocm-2.5 tags.
The script should be modified to accept, through an environment
variable, a different tag that needs to be pinned, so it can be used in
release branch catalog/bundle quay publishing CI jobs. …

Bug 2065661: `pin-latest.py` should allow a custom tag to be set

---

.dockerignore
Dockerfile.assisted-service-build
hack/setup_env.sh

assisted-service-build image size gotten to 7GB, which impacts developers environment (and running time).
This change aims to get rid of several redundant things:
1. Ignoring big files that sometimes local podman deployment creates
2. Removing installation of 7zip and EPEL
After those changes, assisted-service-build image size is 3.72GB in my environment.
/cc @filanov @paul-maidment @avishayt 
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTIN …

NO-ISSUE: optimize build image size

---

Makefile
internal/cluster/validations/validation_test.go
pkg/auth/auth_utils.go
pkg/auth/authz_handler.go
pkg/auth/authz_handler_test.go
pkg/ocm/authorization.go
pkg/ocm/mock_authorization.go
pkg/ocm/utils.go
subsystem/authz_test.go
subsystem/subsystem_suite_test.go
tools/auth_keys_generator.go

The current authorization scheme in the SaaS grants read and write
access only to the cluster's owner. To align with the OCM authorization
scheme, we would like to allow the following:
- A tenancy-based read-only access to resources.
- Users should be allowed to grant editing capabilities to their
resources to other users in their organization.
To establish a tenancy-based authorization, the auth middleware now
performs the following:
- 'Ownership' is now defined on an organization level (a user is allowed
access if they belong to the same organization as the resource's creator).
- For Update and Delete of cluster-related APIs, the authorizer shall issue
an additional query to AMS to check if the user is allowed to change the
resource. This change supports the 'Cluster Editor' role …

MGMT-9443: tenancy based auth

---

deploy/assisted-service.yaml
internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go
subsystem/kubeapi_test.go

The reconcile loop was already stopping the BMH reconcile for CR's that
didn't have the infraenv label. However, this was happening after the
`inspect` label and cleaning were disabled, which caused BMAC to modify
BMH CR's that weren't part of the ZTP flow.
Move the infraenv check earlier in the `reconcileBMH` step so that BMAC
can stop the loop before doing changes to the CR.
/cc @filanov  …

Bug 2035638: Stop BMH reconcile if InfraEnv label is missing

---

internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go

Presently when setting a cluster to become "Day 2", the Stopped
condition is incorrectly configured with default values that do not make sense.
```
condStatus = corev1.ConditionFalse
reason = hiveext.ClusterNotStoppedReason
msg = hiveext.ClusterNotStoppedMsg
```
as a Day 2 cluster represents a completed Day 1 cluster, then the
Stopped condition should be set to a completed state as follows.
```
condStatus = corev1.ConditionTrue
reason = hiveext.ClusterStoppedCompletedReason
msg = hiveext.ClusterStoppedCompletedMsg
```
This commit addresses that issue.
So far I have executed the unit tests and the subsystem tests.
The bugzilla we are addressing is here https://bugzilla.redhat.com/show_bug.cgi?id=2066786
/cc @avishayt 
/cc @omertuc 
- Are the title and description (in both PR and commit) …

Bug 2066786: Set the correct stopping state for a day2 cluster.

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go
models/cluster_create_params.go
restapi/embedded_spec.go
subsystem/cluster_test.go
swagger.yaml

This commit changes the behaviour of cluster creation in order to allow
passing API VIP directly when creating a cluster. This is in order to
remove a need for a subsequent cluster update in order to provide the
value.
This changes the cluster creation API as before it did not allow passing
API VIP. A set of validators is created in order to make sure that API
VIP is allowed for a specific set of scenarios and not unconditionally
for any arbitrary network configuration.
Closes: [MGMT-8300](https://issues.redhat.com/browse/MGMT-8300)
/cc @filanov 
/cc @flaper87  …

MGMT-8300: Allow API VIP on cluster creation

---

client/installer/list_infra_envs_parameters.go
client/installer/v2_list_clusters_parameters.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/identity/identity.go
internal/identity/identity_test.go
restapi/embedded_spec.go
restapi/operations/installer/list_infra_envs_parameters.go
restapi/operations/installer/list_infra_envs_urlbuilder.go
restapi/operations/installer/v2_list_clusters_parameters.go
restapi/operations/installer/v2_list_clusters_urlbuilder.go
swagger.yaml

Added owner query param to the following GET list: clusters and infra-evns.
If the owner param is provided, the returned list includes only clusters/infra-envs that are owned by the specified user.
/cc @avishayt 

MGMT-9371: added owner query param to clusters/infraenvs requests

---

internal/controller/controllers/agentserviceconfig_controller.go

When deleting the assisted installer namespace the agent controller
remains hanged and the api server is not deleted.
This PR sets the agent service config controller as an owner of
the api server webhook so when it is done it will also clean up
the api server.
/cc @
/cc @

Bug 2055333: gc api server when controller is done

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/ignition/ignition.go
internal/ignition/ignition_test.go
internal/ignition/mock_ignition.go

Currently there is a bug that causes day-2 worker ignition override to
be ignored without any error message.
This PR changes the behaviour of ignition generator so that the function
handling day-2 nodes takes the override into account. Given that there
are separate functions for day-1 and day-2 nodes, this PR also renames
the latter so that it's clear that it's used only for day-2.
Closes: [MGMT-9064](https://issues.redhat.com/browse/MGMT-9064)
Closes: Bug-2065288
Closes: [MGMTBUGSM-201](https://issues.redhat.com/browse/MGMTBUGSM-201)
Supersedes: #3502
/cc @eranco74 …

Bug 2065288: Add support for Ignition overrides for day2 worker

---

internal/bminventory/inventory.go

UpdateHostApprovedInternal is currently filtering hosts by user_name when the entity is fetched.
Since this func is used exclusively in kube-api [flow](https://github.com/openshift/assisted-service/blob/f28bddc8d95a89a4804b77b362dda721e3e14214/internal/controller/controllers/agent_controller.go#L1175), the filter has no effect (kube-api uses kube_key_namespace to [retrieve](https://github.com/openshift/assisted-service/blob/f28bddc8d95a89a4804b77b362dda721e3e14214/internal/controller/controllers/agent_controller.go#L144) the host). Hence, we can safely remove AddUserFilter from the func.
Note: perhaps we should consider marking UpdateHostApprovedInternal as relevant only for kube-api. I.e. to avoid missing authorization if ever exposed to the external API.
/cc @carbonin …

MGMT-9404: remove user filter from UpdateHostApproved

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/common.go

ACM 2.5 will GA the DR (disaster recovery) feature, which will automatically backup all required resources created by each component on hub side, then in case the hub goes down, DR can use the backed up resources to recreate the info on a new hub. In order for AI ClusterDeployments to support this all generated secrets need to have either `hive.openshift.io/secret-type` (kubeconfig) or `cluster.open-cluster-management.io/backup` labels (agent auth, postgres secret, BMH secret).
`kubeconfig` is already labelled with `hive.openshift.io/secret-type=kubeconfig`, so this PR labels remaining secrets with  `cluster.open-cluster-management.io/backup=true`
TODO:
Not entirely sure how to test that the whole env can be backed up / restored
/cc @avishayt 
/cc @omertuc

Bug 2066196: ensure secrets have backup labels

---

internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go
internal/controller/controllers/clusterdeployments_controller.go

This PR implements a missing piece that populates Machine Networks
as well as API VIP defined in the AgentClusterInstall's spec already
during cluster creation and not only during its reconciliation.
This is a left over from the implementation of dual-stack in KubeAPI
that has been discovered only after network validations became more
strict in the PR #3258.
Closes: [MGMT-9742](https://issues.redhat.com/browse/MGMT-9742)
/cc @flaper87  …

MGMT-9742: Populate API VIP and  Machine Networks in cluster creation via KubeAPI

---

restapi/embedded_spec.go
swagger.yaml

New API was added to get cluster hosts by using filters.
The assisted installer should use this API, but agentAuth was missing
from API definition.
(X-Secret-Key header).
This fixes the missing definition.
/cc @tsorya 
/cc @filanov 

MGMT-9776: [Assisted-4.10] [Staging] multi cluster - installation failing

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster_test.go
internal/cluster/common.go
internal/cluster/common_test.go
internal/host/transition_test.go
internal/installcfg/builder/builder_test.go
internal/migrations/20220325125504_multiple_networks_cleanup.go
internal/migrations/20220325125504_multiple_networks_cleanup_test.go
internal/migrations/migrations.go
models/cluster_network.go
models/machine_network.go
models/service_network.go
restapi/embedded_spec.go
subsystem/cluster_test.go
subsystem/cluster_v2_test.go
subsystem/infra_env_test.go
swagger.yaml

During the dual-stack implementation the new structures have been
introduced - machine_networks, cluster_networks and service_networks
(all of them of type []string). In order to preserve backwards
compatibility, there were wrappers created that translate e.g.
machine_network_cidr (of type string) to machine_networks (of type
[]string).
Usage of the old parameters makes it impossible to pass multiple
networks (because of type mismatch). Given that in API v2 the new
structures ([]string) are fully implemented, there is no need to
support old ones any more.
This PR does not modify DB schema, however it modifies existing clusters
so that the value of deprecated fields becomes empty or zeroed. A
following PR will completely remove the fields from the swagger and from
the DB and will be …

MGMT-7365: Deprecate single network configuration fields

---

subsystem/authz_test.go

Added update cluster test to authz_test when org tenancy is enabled - to ensure authorization for PATCH requests.

NO-ISSUE: tenancy authz - added PATCH cluster test

---

internal/common/test_configuration.go
internal/host/hostcommands/free_addresses_cmd.go
internal/host/hostcommands/free_addresses_cmd_test.go

Free addresses runs for IPv4 only.  Currently GetNextSteps for
Free addresses generates error message in the log.
In case IPv6 addresses exist, no such message will be written to the
log.
/cc @filanov 
/cc @

MGMT-9172: Misleading "No networks found for host" errors reported for hosts which don't have any IPv4 addresses

---

deploy/operator/setup_assisted_operator.sh

In the late binding job, we try to download the ISO image from the
assisted-image-service but this one is not available yet.
This change waits for the assisted-image-service to be up before exiting the
deployment script.

MGMT-9726: Wait for assisted-image-service when deploying the operator

---

internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/common.go
internal/cluster/validator.go
internal/common/test_configuration.go
internal/network/machine_network_cidr.go
internal/network/utils.go

When SNO cluster is created without machine CIDR, the cluster will not
become ready until machine CIDR is set.
There are cases that the machine networks can be deduced from the
discovered networks, and the configuration of service and cluster
networks.
When both of these configurations have the same address familes,
and there is a single discovered network per family in (service/cluster)
networks, then the machine networks can be auto assigned for SNO.
/cc @
/cc @ …

[release-ocm-2.5] Bug 2069974: Host status change to insufficient when binding a host to a cluster

---

Makefile
tools/wait_for_cluster_info.py

In some cases, the user does not own the cluster and thus cannot
run cluster-info without the scope of a namespace.
/cc @osherdp 
/cc @omertuc 

MGMT-9779: Call cluster-info with a namespace

---

internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go

Improved the error message on ClusterImageSet sync error to give the user better info on the source of the issue.
E.g.
'The Spec could not be synced due to backend error: failed to add release image 'quay.io/openshift-release-dev/ocp-release:4.10.invalid-x86_64'. Please ensure the releaseImage field in ClusterImageSet 'openshift-v4.10' is valid.'
/cc @filanov 
/cc @nirfarkas 

Bug 2066069: improve ClusterImageSet sync error message

---

cmd/main.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/common/db.go
pkg/auth/authz.go
pkg/auth/none_authz_handler.go
pkg/auth/rhsso_authz_handler.go
pkg/auth/rhsso_authz_handler_test.go

Authorization becomes more complex with the tenancy based feature and more authorization scheme added for other projects.
In the current implementation the application layer is using stateless utilities to check for access permission to object on top of the existing mechanism. These checks are sometimes redundant and or not quite aligned with new authorization schemes.
Using stateless utilities make us expose feature flags and states in the auth API where they do not belong. For all those reasons an API for authorization that will be shared by all authorization handlers and expose a coherent access control algorithms to the application is required.
This is the first installment of the enhancement. It defines The `OwnedBy` interface that wraps the db object with authorization-related …

MGMT-9673: Ownerhsip API to authz

---

go.mod
go.sum

Update golang.org/x/crypto to v0.0.0-20220331220935-ae2d96664a29
/cc @filanov 
/cc @osherdp 
/cc @gamli75

[release-ocm-2.4]  NO-ISSUE: Bump crypto version

---

internal/cluster/common.go
internal/manifests/manifests.go
subsystem/manifests_test.go

The manifest handler implements its own access checks within the application layer. Those verifications are redundant and with the new tenancy policies also incorrect.
Since manifests are sub-objects of clusters, their access should is governed by the cluster access rules in the auth layer which should be the sole responsible for authorization checks.
Tests were changed accordingly and the case of missing cluster (which is handled by the auth middleware) was moved to the subsystem tests.
/cc @
/cc @
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#com …

MGMT-9672: align manifest authz

---

internal/bminventory/inventory.go
subsystem/kubeapi_test.go

When creating aci with "networkType: OpenShiftSDN" and "controlPlaneAgents: 1", the
aci is created and synced, only for the validation network-type-valid to fail.
This PR validates the network type on creation and update and make sure
that with SNO there is no SDN configured.
/cc @
/cc @

Bug 2069101: fail SNO deployment with SDN

---

pkg/staticnetworkconfig/generator.go
pkg/staticnetworkconfig/generator_test.go

When updating infra-env, static network configuration is saved if it is
present in the update parameters and if it is different from the
previous value already in the database. Updating infra-env causes
download URL regeneration which is undesirable.
Since this configuration is a slice of elements, that each of them
contains a slice, changing the order of items in any of the slices, may
cause the static network configuration to be different than the previous
value, but equivalent in terms of configuration when applied.
To prevent this, sort was added to verify that equivalent configurations
will generate same string value to be stored in the database.
/cc @filanov 
/cc @
- Is there a bug required (and linked) …

Bug 2061317: when using nmstateconfigs ISO is re-generated for each nmstateconfig

---

pkg/auth/auth_utils.go
pkg/auth/authz.go
pkg/auth/none_authz_handler.go
pkg/auth/rhsso_authz_handler.go
pkg/auth/rhsso_authz_handler_test.go
subsystem/authz_test.go

Authorization becomes more complex with the tenancy-based feature and more authorization schemes added for other projects.
In the current implementation, the application layer is using stateless utilities to check for access permission to objects on top of the existing mechanism. These checks are sometimes redundant and or not quite aligned with the new authorization scheme.
Using stateless utilities makes us expose feature flags and states in the auth API where they do not belong. For all those reasons, an API for authorization that will be shared by all authorization handlers and expose coherent access control algorithms to the application is required.
This is the second installment of the enhancement. It defines The HasAccessTo interface that queries whether the current user can access …

MGMT-9673: Add HasAccessTo API to authz

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

It seems that the semantics of agent version may
change over time, being reperesented either by a
full image name or just by the image tag. We make
the log message that informs about agent update
more robust by accomodating both these variants.
That is, if the agent version is a tag we compare
it to the tag in `AGENT_DOCKER_IMAGE`, but if it
is a full name we compare it to the entire content
of `AGENT_DOCKER_IMAGE`.
/cc @tsorya  …

MGMT-8741: Accept full name OR tag for agent version

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/common/conversions.go
internal/events/eventstest/events_test_utils.go

With the current implementation, when image_info_updated gets
generated for an unbounded InfraEnv (meaning no clusterID),
we pass a pointer to an empty string rather than nil, which is what
the querying function expects. This change addresses this issue.
Additional events that have a similar problem with an optional cluster_id:
- host_logs_uploaded
- host_deregistered
/cc @
/cc @

 MGMT-9912: Handle a nil cluster_id with events that have an optional cluster_id

---

internal/common/common_unitest_db.go

Instead of exposing docker socket when running unit-tests locally we could make use of k8s (deployed via cluster-bot or minikube). `kind` could work as well, but it doesn't seem to set External IPs for LB svc here.
/cc @flaper87 
/cc @paul-maidment 

NO-ISSUE: tweak unit tests to allow running PostgreSQL on k8s instead of docker

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

When cluster_id is specified in RegisterInfraEnv request, ensure user authorization for updating the cluster.
No need to check authorization when registering without a specific cluster_id.
/cc @slaviered
/cc @avishayt

MGMT-9810: check cluster update authz in RegisterInfraEnv

---

deploy/olm-catalog/pin-latest.py
deploy/olm-catalog/requirements.txt

When publishing the Infrastructure Operator bundle and catalog to quay
for the master branch, we scan the operator's manifests
(clusterserviceversion in particular) for the "latest" tag and pin it to
a particular image manifest digest. This is done using the pin-latest.py
script.
We would like to use the same script for doing similar pinning but for
our release branches.
This is needed because currently our
`periodic-ci-openshift-assisted-service-release-ocm-2.4-e2e-metal-assisted-kube-api-late-binding-single-node-periodic`
job is failing because it's using an outdated operator catalog image
that's no longer being published.
This script is needed for the new publishing process that we already
have in place for `release-ocm-2.5` and `master`. …

[release-ocm-2.4] Bug 2072892: Backport `pin-latest.py` script

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

Added proper authz to BindHostInternal func by using HasAccessTo API.
The specified cluster (the should be bounded to host) is checked for ensuring user's update permissions. I.e. cluster is owned by the user, or, if tenancy is enabled, we query AMS with the associated subscription.
/cc @avishayt 

MGMT-9732: add user authorization to BindHost

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
pkg/auth/auth_handler_test_utils.go

Replaced identity.AddUserFilter in V2UpdateHostInstallerArgsInternal and V2UpdateHostIgnition funcs.
Instead, used authzHandler.HasAccessTo API. When tenancy is enabled, HasAccessTo should query AMS
and check whether the user has update perms for the cluster associated to the host (i.e. if there's a bounded cluster).
Otherwise, the relevant filter should be added to the db query.
/cc @avishayt  …

MGMT-9758: replace AddUserFilter with HasAccessTo API

---

Dockerfile.assisted-service

The oc in this link contain the ICSP lookup feature https://github.com/openshift/oc/pull/829
The lack of ICSP support is the reason the assisted-service didn't upstream oc since https://github.com/openshift/assisted-service/pull/1655
- Should this PR be tested in a specific environment? disconnected env
-->
Hopefully it won't impact anything, but this code is in play in all environments
/cc @tsorya 
/cc @flaper87  …

MGMT-5442: assisted-service should use official oc client

---

internal/host/host.go
internal/host/host_test.go

If the environment variable BOOTSTRAP_HOST_MAC is set, select a host
with that MAC address as the bootstrap and ensure it is designated to be
a control plane host.
This will be used in the ephemeral installer to ensure that the host
running assisted-service is also used as the bootstrap.
/cc @flaper87 
/cc @avishayt 

AGENT-34: Allow preconfiguration of bootstrap host

---

internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/common.go
internal/controller/controllers/infraenv_controller.go

This change makes sure InfraEnv secrets are being labelled for backup when infraenv is being created/updated. We don't manage the secret directly, but since its required for InfraEnv to be restored correctly.
Fixes https://github.com/stolostron/backlog/issues/21490
TODO:
/cc @filanov 

Bug 2072728: ensure secret is labelled when it is being reconciled

---

api/hiveextension/v1beta1/agentclusterinstall_types.go
config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
config/crd/resources.yaml
deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
subsystem/kubeapi_test.go

Exposed APIVIP and IngressVIP in the status of AgentClusterInstall CRD.
The values are now copied from the cluster when updating ACI's status in ClusterDeploymentsReconciler.
/cc @tsorya 
/cc @eranco74 
/cc @filanov 

Bug 2073413: expose API/Ingress VIPs in ACI

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/controller/controllers/clusterdeployments_controller_test.go
internal/ignition/ignition.go
internal/ignition/ignition_test.go
internal/ignition/mock_ignition.go

Currently there is a bug that causes day-2 worker ignition override to
be ignored without any error message.
This PR changes the behaviour of ignition generator so that the function
handling day-2 nodes takes the override into account. Given that there
are separate functions for day-1 and day-2 nodes, this PR also renames
the latter so that it's clear that it's used only for day-2.
Cherry-picks: #3524
Closes: Bug-2070949
/cc @carbonin 
/cc @ …

Bug 2070949: Add support for Ignition overrides for day2 worker

---

Dockerfile.assisted-service

Add a retry to curl when fetching oc in order to make the docker build
more reliable.

NO-ISSUE: Add a retry when fetching oc with curl

---

internal/versions/versions.go
internal/versions/versions_test.go

https://issues.redhat.com/browse/MGMT-10062
Problem: When SERVICE_VERSION is unset, the service
provides a default value that's incorrect.
This PR removes the default value so that when
the SERVICE_VERSION is not set, it'll return
Unknown when queried.
````
{"versions":{"assisted-installer":"quay.io/edge-infrastructure/assisted-installer:latest","assisted-installer-controller":"quay.io/edge-infrastructure/assisted-installer-controller:latest","assisted-installer-service":"Unknown","discovery-agent":"quay.io/edge-infrastructure/assisted-installer-agent:latest"}}
$ curl -s http://192.168.39.97:30780/api/assisted-install/v2/component-versions | jq '.versions."assisted-installer-service"'
"Unknown"
````  
/cc @omertuc 
/cc @carbonin 
- Are the title and description (in both PR and commit) …

MGMT-10062: Remove default service version

---

hack/Makefile

The target that creates the build directory is not available from the
included Makefile in `hack/` directory. As a result, the some generate*
commands fail to execute.

NO-ISSUE: create build directory for generate targets

---

deploy/operator/setup_assisted_operator.sh
deploy/operator/ztp/deploy_spoke_cluster.sh

Patching the Provisioning CR triggers a rollout of the metal3
deployment. Since the metal3 deployment has just 1 replica, during the
rollout the metal admission webhook is unavailable. As a result any
interaction during that time with BMH resources causes an error (as the
webhook is down).
This is why after patching the Provisioning CR we have to wait for that
process to complete. This includes waiting a few seconds for the
baremetal operator to notice our patch (there's no simple robust way to
do this. It usually happens almost immediately, but we wait 10 seconds
just in case). Then we wait for the deployment to finish rolling out,
and finally we wait for the metal3 pod to be ready.
When applying the spoke cluster ZTP manifests generated by the ansible
playbook, we used this loop: …

Bug 2077921: Operator deployment script doesn't wait after patching the Provisioning CR

---

hack/Makefile

Depends on https://github.com/openshift/release/pull/28113.
Basically we no longer need this redundant target after we changed all occurrences of it.
/cc @eliorerz 
/hold

MGMT-10029: remove generate-all target

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
pkg/auth/rhsso_authz_handler.go
subsystem/authz_test.go
subsystem/wiremock_stubs.go

For scenarios in which a user can't manipulate an object (i.e. update/delete cluster/infraenv), but, is allowed to read the object - return StatusForbidden (403). If a user can't read nor write - return StatusNotFound (404).
This is required to avoid exposing any information for users who can't read the object.
While returning a specific error for users allowed to get the object.
/cc @filanov  …

MGMT-10109: return status forbidden for manipulation ops

---

pkg/auth/rhsso_authz_handler.go
subsystem/authz_test.go

Ensuring StatusNotFound (404) is returned when fetching a non-existent infra-env.
/cc @slaviered
/cc @filanov 

MGMT-10163: return StatusNotFound on non-existent infra-env

---

tools/debug/s3-list-cron.yaml

The cc76ac838ed02b476c07f78cc464290774d25907 commit added this example
CronJob manifest:
>CronJob to periodically list objects in S3
>
>Useful for debugging the s3 object expiration, the job runs every 15
>minutes and you can see the list of objects in the pod's log.
It uses a deprecated kubernetes API that is going to be removed in
upcoming Kubernetes versions.
In case someone is still using this job somewhere, this commit updates
the manifest to use the newer API.
/cc @avishayt

NO-ISSUE: Don't use deprecated APIs

---

Makefile

Enable doing ``make generate`` to generate all code.
Starting from https://github.com/openshift/release/pull/28113 we'll start doing ``make generate`` instead of ``make generate-all``.
/cc @eliorerz 

MGMT-10164: fix generate target

---

deploy/olm-catalog/metadata/annotations.yaml

Seems like we're lacking code generation validation for the ``release-ocm-2.5`` branch, thus resulting in generated code not synchronized to its source-of-truth, well... source.
Automated jobs will be added shortly.
/cc @eliorerz 

MGMT-10164: sync generated code

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

1. Calling hostutil.UpdateHostStatus with InfraEnvID rather than ClusterId.
InfraEnvID is expected by UpdateHostStatus, but this reference wasn't updated.
2. Reverting https://github.com/openshift/assisted-service/pull/3225/. Setting the status of the host to Error instead of Disconnected.
Currently, after setting the status to Disconnected, the stateMachine reverts the status to the original cluster status.
/cc @
/cc @ …

MGMT-8738: Media disconnection status doesn't updated

---

deploy/assisted-image-service.yaml
tools/deploy_image_service.py

Currently deploy-image-service image is defined statically at assisted-image-service.yam.
This PR add the option to override it using REPLACE_IMAGE_SERVICE_IMAGE key.
The IMAGE_SERVICE env var default is defined on the Makefile
/cc @osherdp

NO-ISSUE - Add the ability to override image-service image when deploying the assisted-image-service

---

Dockerfile.assisted-service

Updated the oc-image to an updated version of oc that support the new oc-mirror behavior
The oc image was built from this commit:
https://github.com/eranco74/oc/commit/20d61f4260917d444bda6fb1e761c49d2a3bc02d
- Should this PR be tested by the reviewer? not a must
- Should this PR be tested in a specific environment? disconnected env using a mirror registry created with oc-mirror
-->
https://bugzilla.redhat.com/show_bug.cgi?id=2069976
Disconnected environment
Tested the functionality of the oc client in a disconnected env against mirror registry while creating the release mirror with `oc adm release mirror` and `oc-mirror`, in both cases …

Bug 2069976: oc client in AI failed to resolve MCO image when working with oc-mirror

---

api/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
internal/bminventory/inventory.go
internal/common/common.go
models/install_cmd_request.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/install_cmd_request.go

1: When A day2 worker node is trying to join a single node cluster, the
node was being incorrectly assigned the wrong role (master instead of
worker) this code fixes that problem.
2: Ensure that the High Availability Mode install command parameter is
not mandatory.
It used to be the case that a day 2 worker could only be added to an HA
cluster. We are making this change to allow the addition of a day 2
worker to a non HA cluster.
The condition [1] was blocking this.
That validation ensures that Day 1 SNO clusters will only accept Master
or Bootsrap roles for the host being installed.
So an ideal solution was to pass an empty string for "HA mode" whenever
the role of the host is "Worker" as when adding a worker "High
Availability" mode is not relevant. (Especially when sometimes it is not …

MGMT-9379: Service changes to allow day 2 workers on single node

---

docs/operator.md

As the OLM operators must gather isn't something
we'd like to be widely used, yet, we are removing
it from the operator docs.

removing OLM operator must-gather from docs

---

pkg/staticnetworkconfig/generator.go
subsystem/infra_env_test.go

[MGMT-9574](https://issues.redhat.com/browse/MGMT-9574)
Previously when a user updates an infra env with an invalid
network yaml, the error message included a traceback given
from the stderr which is confusing and unclear.
This changes the message returned so that it's clear what
went wrong.
1. Deploy assisted-service with changes
2. Run `make deploy_nodes` to deploy a cluster
3. Curl the infra-envs patch API
````bash
curl -XPATCH  --header "Content-Type: application/json" $SERVICE_URL/api/assisted-install/v2/infra-envs/$INFRA_ENV_ID -d '{"static_network_config":[{"network_yaml":"aaaa","mac_interface_map":[{"mac_address":"52:54:00:ee:42:e1","logical_nic_name":"eth0"}]}]}'
````
5. Check the error message returned
/cc @carbonin 
/cc @filanov 
- I added a subsystem test …

MGMT-9574: Improve error message when updating static IP

---

docs/user-guide/network-configuration.md

The documentation clearly states that on SNO only OVNKubernetes is
allowed yet uses OpenShiftSDN in one of the example CRs for SNO
This commit fixes that documentation mistake
/cc @romfreiman
/cc @empovit

MGMT-9180 - Fix bad SNO OVN/SDN doc example CR

---

pkg/auth/rhsso_authz_handler.go
pkg/auth/rhsso_authz_handler_test.go

Removed the caching of the response for ocm.Subscription AccessReview.
This should prevent redundant wait when granting/removing ClusterEditor role.
We should investigate later if/how cache impl can be done.
/cc @slaviered  
/cc @filanov 

MGMT-10160: remove cache for subscription access review

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

Usage of the API change as mentioned in
https://github.com/openshift/assisted-service/commit/2f82f2a21d94a21b39dab9909b51eb527afaf384
/cc @ omertuc
/cc @ ori-amizur

MGMT-9379: Do not pass "HA mode" parameter for worker nodes.

---

internal/cluster/validations/validation_test.go
internal/cluster/validations/validations.go

[Bug 2083075](https://bugzilla.redhat.com/show_bug.cgi?id=2083075)
Previously, assisted installer only allowed cluster names
to start with a lowercase letter. OCP allows clusters that
start with a number.
This change allows the cluster name to start with either
a lowercase letter or a number.
/cc @carbonin 
/cc @filanov 

Bug 2083075: Allow cluster name to start with number

---

deploy/operator/setup_lso.sh
deploy/operator/utils.sh

From time to time, the `oc annotate` fails with the following error:
```
Created project openshift-local-storage
Error from server (Conflict): Operation cannot be fulfilled on namespaces "openshift-local-storage": the object has been modified; please apply your changes to
the latest version and try again
```
This change works around this issue with a retry.

Bug 2084612: Add a retry in setup lso

---

internal/bminventory/inventory.go
internal/bminventory/mock_installer_internal.go
internal/cluster/cluster.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
internal/host/host.go
internal/host/host_test.go
internal/host/mock_host_api.go

When installing large clusters, bringing hosts from DB takes a lot of
resources.  To eliminate this, hosts where removed from the result of
GetClusterByKubeKey
[MGMT-10262](https://issues.redhat.com//browse/MGMT-10262): To start installation with Kube API, create a function that uses aggregate db query
Currently, cluster controller counts hosts to find out of they are all
ready and approved before starting installation. Since the query to get
cluster does not bring the hosts anymore, a function that performs
aggregate query was added that replaced the previous functionality.
[MGMT-10294](https://issues.redhat.com//browse/MGMT-10294): Create query to find of any of cluster hosts had their logs collected
Replacement for iterating over hosts to find if any of the hosts had
their logs …

MGMT-10261: For call GetClusterByKubeKey don't bring hosts

---

internal/bminventory/inventory.go

This commit makes sure assisted always logs the output of debug.Stack() when
failing to recover. Failing to recover means a go-routing crashed/paniced and
we need to have access to the failure data from the logs
I used this change to debug a failure in one of our ZTPFW environments
/cc @nmagnezi 

NO-ISSUE: Log stack trace when failing to recover

---

docs/hive-integration/kube-api-select-ocp-versions.md

The AgentServiceConfig Custom Resource can specify a RootFS URL for when a minimal-iso configuration is specified for Discovery ISO generation.  This is done by setting the `.spec.[]osImages.rootFSUrl` string value.
This modification is simply an update to include it in the example documentation in the file `docs/hive-integration/kube-api-select-ocp-versions.md`
Also added documentation information around the previously defined `.spec.[]osImages.cpuArchitecture` example that was not listed below with an explanation.
N/A
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide …

NO-ISSUE: Add .spec.[]osImages.rootFSUrl to example and docs

---

client/installer/v2_get_preflight_requirements_parameters.go
data/default_hw_requirements.json
deploy/podman/configmap.yml
deploy/podman/okd-configmap.yml
docs/dev/hardware-requirements.md
internal/hardware/validator_test.go
internal/hardware/versioned-requirements_test.go
internal/host/transition_test.go
restapi/embedded_spec.go
restapi/operations/installer/v2_get_preflight_requirements_parameters.go
subsystem/cluster_test.go
swagger.yaml

Seems like since OCP 4.6, disk requirements were set on 100GB for all nodes:
https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal
Since we don't support installation of OCP <= 4.5 in any environment, it makes sense to change it for all OCP minor releases.
This PR is not doing relevant changes for the operator (in the ``agentserviceconfig`` object), as it should follow BZ tickets instead of Jira ones.
I've tested local environments of minikube and podman, trying to create envs with different disk sizes. I'll also follow up checking integration env ``preflight-requirements`` endpoint.
@gamli75 @eliorerz 
- …

MGMT-9682: fix default disk size requirement

---

api/vendor/github.com/openshift/assisted-service/models/cluster.go
api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
cmd/main.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/progress_test.go
internal/cluster/transition_test.go
internal/common/common.go
internal/operators/odf/validation_test.go
internal/provider/baremetal/consts.go
internal/provider/baremetal/inventory.go
internal/provider/base.go
internal/provider/mock_base_provider.go
internal/provider/ovirt/inventory.go
internal/provider/registry/mock_providerregistry.go
internal/provider/registry/registry.go
internal/provider/registry/registry_test.go
internal/provider/vsphere/inventory.go
models/cluster.go
models/cluster_create_params.go
models/v2_cluster_update_params.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/cluster.go
vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go

The current implementation of the schedulable masters feature allows to enable the scheduling of workloads in the control plane. However, it's not possible to disable the scheduling of workloads explicitly. Additionally, the current API always returns  the value of the 'schedulable_masters' property saved in the database at cluster creation time (defaults to "false" if omitted). However the UI needs the API to return the default correct value depending on the number of hosts in the cluster.
The proposed changes allow to effectively disable the scheduling of workloads on control plane and returns the expected default values for each platform in case the 'schedulable_masters' property was not actively set at cluster creation time. 
/cc @filanov 
/cc @avishayt

MGMT-9259: Enhance the schedulable masters feature

---

internal/host/host.go
internal/host/monitor.go
internal/host/validator.go

When running refresh-status on cluster hosts, hostname-unique validation
checks that the current hostname is unique.  In order to get a host's
hostname, there is a need to unmarshall its inventory.  For cluster with
many hosts, the number of unmarshalls is (# of hosts)^2 (squared), since
each host has to unmarshall the inventory of the other hosts.
To change that, an inventory cache was added, so each inventory is
unmarshalled once per monitoring cycle.
/cc @filanov 
/cc @ …

MGMT-9315: Create inventory cache during refresh status preprocessing, to avoid unnecessary inventory unmarshalling

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/bminventory/mock_installer_internal.go
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/network/utils.go
internal/network/utils_test.go

Calling refresh-status not from monitor produces excessive load.  To
avoid this load, refresh status was removed in bm-inventory if
called from Kube API.
The refresh was kept for REST API since UI expects immediate affect to
update operation.
In addition, the refresh status was removed from install if no role was
updated as part of auto-assign operation.
This change also verifies that refresh will be triggered if any of the
networks were actually changed.
/cc @filanov 
/cc @ …

MGMT-10263: Do not call refresh status from bm-inventory if called from Kube API

---

pkg/validations/validations.go
pkg/validations/validations_test.go

https://issues.redhat.com/browse/MGMT-10347
Only allows hostnames to have lowercase alphanumerical
characters, dashes, and periods. Hostnames must also
start and end with a lowercase alphanumerical character.
It no longer allows capital letters in the hostname.
This change was made to align with OCP and K8s standards for hostnames.
/cc @omertuc 
/cc @filanov @carbonin 

MGMT-10347: Disallow capital letters from hostnames

---

internal/common/common.go
internal/common/expiring_cache.go
internal/connectivity/validator.go
internal/host/hostcommands/connectivity_check_cmd.go
internal/host/hostcommands/connectivity_check_cmd_test.go
internal/oc/release.go
internal/oc/release_test.go

When installation starts, many threads attempt to get the image
concurrently.  Each creates a process that attempts to get it, but all
need the same information.
Added cache that verifies that an image is retrieved only once, and all
other threads are waiting for the result.
[MGMT-10271](https://issues.redhat.com//browse/MGMT-10271): Get only id, status, and inventory when querying hosts for connectivity check
Only these fields are needed to construct the connectivity-check step.
[MGMT-10267](https://issues.redhat.com//browse/MGMT-10267): Create cache for host valid interfaces
In order to construct the connectivity check step, each host valid
interfaces are needed.
Since the Unmarshal operation is costly, the valid interfaces of each
host are kept in cache to speed up the valid interfaces …

MGMT-10275: When getting release image, let a single thread query it, and other threads wait for it

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/hardware/validator.go
internal/host/host.go
internal/host/hostcommands/dhcp_allocate_cmd.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/instruction_manager.go
internal/host/hostcommands/instruction_manager_test.go

When cluster starts installation, all the workers poll the service to
find if there are already 2 masters that joined the control plane in
before they reboot. For this they query first the cluster.
Even if the hosts are not returned from the service, parallel invocation
of this query may cause out of memory contention, since the result from
the database consumes a lot of space.
[MGMT-10265](https://issues.redhat.com//browse/MGMT-10265): Skip eager loading when getting installation disk speed threshold
Eager loading is not needed to find out the installation disk speed
threshold since the data is part of the cluster.
[MGMT-10268](https://issues.redhat.com//browse/MGMT-10268): When getting cluster for update inventory, skip eager loading
Eager loading is not needed when updating the …

MGMT-10264: In GetClusterInternal, do not bring hosts also from db unless requested explicitly

---

internal/host/validator.go

When there is no api vip connectivity information yet on the host
the disk validation shows a misleading message about missing role
assignment.
This PR sorts out the cases for ValidationPending and prints a
proper message for each case
/cc @
/cc @

MGMT-10179: transient day2 misleading validation message

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

This PR extends the Agent CR by creating labels with a reference to the
clusterDeployment. This is so that in the future it will be possible to
list agents belonging to a particular clusterDeployment only by
filtering Agents by label and not by iterating over all the objects and
querying their spec.
Due to the fact that maximum length for a label value is 63 characters 
but the resource name can be up to 253, we are labeling only the 
namespace as this one has the limit of 63 characters.
This leverages the fact that api server can filter objects by label, but
it cannot filter by the arbitrary field in spec.
The PR is part of a bigger change that is going to extend error
reporting in ClusterDeployment controller and AgentClusterInstall
controller.
Contributes-to: …

Bug 2076333: Add clusterDeploymentRef as label to the Agent

---

internal/network/manifests_generator.go

This also cleans up some empty fields that were previously being
specified in the ignition spec.
The old ignition version was originally added in
9feb42c785968109e5df62a2bba5295bbcc77a6e which doesn't have any specific
reasoning about why that version was chosen.
We did intentionally use ignition 2.2.0 very early on in the discovery
ignition (commit 796ca8e97e5cbb777be73e7b1469096a343b56d9), but that was
updated soon after (commit 01d9152b460a5e800b86c1e5fbc1bbf4ee43eda3) to
3.1.0 to support rhcos 4.6.
For reference the 3.1 spec is described at https://coreos.github.io/ignition/configuration-v3_1/
https://issues.redhat.com/browse/MGMT-10253
/cc @filanov 
/cc @tsorya  …

MGMT-10253: Use a modern ignition version for our machine config manifests

---

api/vendor/github.com/openshift/assisted-service/models/cluster.go
api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
cmd/main.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/progress_test.go
internal/cluster/transition_test.go
internal/common/common.go
internal/operators/odf/validation_test.go
internal/provider/baremetal/consts.go
internal/provider/baremetal/inventory.go
internal/provider/base.go
internal/provider/mock_base_provider.go
internal/provider/ovirt/inventory.go
internal/provider/registry/mock_providerregistry.go
internal/provider/registry/registry.go
internal/provider/registry/registry_test.go
internal/provider/vsphere/inventory.go
models/cluster.go
models/cluster_create_params.go
models/v2_cluster_update_params.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/cluster.go
vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go

This reverts commit 7296f386338fe038eab9f7bf2463eac66eda7c63.
Following a couple of blocker bugs found by QE, we'd rather revert this
change for now and work for the fixes in 2.5.0.
/cc @gamli75 
/cc @mmartinv 
/cc @omertuc 
/cc @lalon4 

Revert "MGMT-9259: Enhance the schedulable masters feature (#2861)"

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/controller/controllers/common.go

Presently when using ZTP, if you have a single node and wish to approve
day2 CSRs, this is not possible because the AgentClusterInstall CR does
not have UserManagedNetworking set and we are unable to determine the
state of this for SNO. Therefore we will need to check based on the
number of control plane nodes requested.
- [] Enhancement 
/cc @filanov 

MGMT-10494 Make sure that SNO is considered when auto approving CSRs

---

hack/Makefile

After viewing openshift/assisted-service#3830, it seems like we don't have the ``generate-bundle`` makefile target called when we're doing ``generate``. It means OCP bumps PRs (both manual and automatic) might
include non-intended changes.
This change aims to include ``generate-bundle``, to handle code-generation verification right when developer introduced changes in the bundles.
/cc @filanov @danielerez  …

NO-ISSUE: add 'generate-bundle' to the 'generate' target

---

deploy/operator/utils.sh

The function didn't actually retry in the way it was
written, it just gave up after the first failure.
Not sure why exactly (it didn't seem to be because of errexit),
but I've rewritten it in a different way and it now works.
Originally introduced in f45e1b54d6a6b8b91f7127fb0937e7d08e8a187a
- Made sure it retries properly

Bug 2089337: Fix the retry function to actually retry

---

deploy/operator/gather.sh

Seems like using ``oc logs`` by specifying pods with selectors does not show all logs for those pods but rather truncates it.
Using ``--tail=-1`` should output the whole logs even when using selectors queries.
Thanks @omertuc for showing me the relevant tweet about it :)
/cc @eranco74 
/cc @omertuc 

MGMT-10493: fix gathering logs in ZTP flow

---

.gitattributes

This should make files generated in ``vendor/`` dir hidden from GitHub review system by default:
Files will still be shown as changed files, but at least browser will not try to load any information at first.
/cc @filanov 
/cc @nmagnezi 

NO-ISSUE: skip vendor dirs generated files

---

internal/network/manifests_generator.go
internal/network/manifests_generator_test.go

envconfig.Process requires a pointer to the structure, not the structure itself. As a result, `NewConfig` has been throwing errors all the time.
Added unit tests to ensure it no longer happens and networkCfg has expected values based on env vars
/cc @filanov 
/cc @tsorya 

MGMT-10548: internal/network: fix NewConfig to avoid throwing errors

---

api/vendor/github.com/openshift/assisted-service/models/interface.go
models/interface.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/interface.go

[MGMT-10473](https://issues.redhat.com/browse/MGMT-10473)
As part of epic https://issues.redhat.com/browse/MGMT-10087
This field will be populated by the agent and will allow
the service to filter interfaces as the agent has done
previously. The filtering on the service side prevents
the additional interfaces from being stored if the
user has not requested the additional interfaces.
1. Deployed the service image with the new property added
2. Deployed a node using assisted-test-infra
3. Posted to the API with the following json:
````
$ cat data.json
{"step_type":"inventory","output":"{\"interfaces\":[{\"name\":\"lo\",\"type\":\"physical\",\"ipv4_addresses\":[\"127.0.0.1\"],\"ipv6_addresses\":[],\"flags\":[\"up\",\"broadcast\",\"multicast\"]}]}"}
$ curl …
```

MGMT-10473: Add interface type to Interface API

---

internal/common/test_configuration.go
internal/host/transition_test.go
internal/host/validator.go

When using single stack IPv6 or dual stack, and the machine networks
and connectivity groups contain unequal but equivalent values, then the
belongs-to-connectivity-group validations fails.
Ex: 1001:db8::/120 vs 1001:0db8:0::/120
Changed validation that it checks equivalence for machine-networks instead of
equality.
/cc @filanov 
/cc @

Bug-2084410: Deploying OCP 4.8 on RHCOS with assisted-installer Failing validation blocks deployment with Insufficient error message

---

Dockerfile.assisted-service.ocp

AGENT-205: Fix OCP image build

---

internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go
internal/oc/mock_release.go
internal/oc/release.go

This is required in order to allow the converged flow to work on ARM machines.
Since the ironic agent image isn't a multi-arch image we need to get the agent image from the release image that match the arch we are trying to install, hence we will get it from the release image for the installation.
In case the service fails to get the ironic agent from the release image it will fall back to the default ironic agent image provided via env. 
- Should this PR be tested in a specific environment? ZTP using dev scripts 
- Any logs, screenshots, etc that can help with the review process? we can check which ironic agent image is used on the node prior to the node installation.
--> …

MGMT-10375: Get the ironic image from the release image for the arch

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go
internal/controller/controllers/preprovisioningimage_controller.go

Since we don't want to change the current ZTP behavior where the assisted-agent is cleaning only the installation disk.
BMAC should keep disabling the AutomatedCleaningMode on the BMH spec so that Ironic agent won't clean all the disks
- Should this PR be tested in a specific environment? dev scripts
-->
https://issues.redhat.com/browse/MGMT-10633
/cc @avishayt 
/cc @flaper87 …

MGMT-10633: BMAC should disable the BMH AutomatedCleaningMode in the converged flow as well

---

.github/dependabot.yml

For now, almost all dependabot's Python PRs are failing due to outdated
Python version we use (Python 3.6). We will first stop them for now
until we upgrade the Python version to at least 3.9.
As an example for such PR, see:
https://github.com/openshift/assisted-service/pull/3844
/cc @carbonin 

MGMT-10631: remove Python dependencies auto bump

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/common.go

This ensures that mirror registry configmap gets backed up along with other CRs required for DR
/cc @filanov 
/cc @osherdp 

Bug 2090415: internal/controller/controllers: label mirrorRegistryRef configmap for backup

---

internal/provider/baremetal/installConfig.go
internal/provider/registry/registry_test.go
subsystem/cluster_test.go
subsystem/ipv6_test.go

[MGMT-9175](https://issues.redhat.com/browse/MGMT-9175)
Part of epic https://issues.redhat.com/browse/MGMT-10087
The assisted installer agent has changes to
pass all interfaces to the assisted service.
PR for the agent changes:
https://github.com/openshift/assisted-installer-agent/pull/360
Originally, the assisted service selected the first interface
in the list, which might not have a MAC address.
This change now looks for an interface with a MAC
address and uses it for the install config.
/cc @carbonin 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/gui …

MGMT-9175: Use an interface with a Mac address

---

cmd/main.go
internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go

Initialize the PreprovisioningImage VersionsHandler and OcRelease
- Is this PR relying on CI for an e2e test run? For regression
- Should this PR be tested in a specific environment? dev scripts
-->
https://bugzilla.redhat.com/show_bug.cgi?id=2093503
Testing manually - WIP
/cc @filanov 
/cc @tsorya  …

Bug 2093503: Assisted service POD keeps crashing after a bare metal host is created

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

This commit softens the checks for IP stack when `cluster.HostNetworks`
are propagated from the hosts' inventory. Currently disabled
`cfg.IPv6Support` implies that all the IPv6 subnets will be removed and as
a result dual-stack hosts will create a cluster with only IPv4 host
networks.
This issue is only affecting clusters created using the UI. This is
because UI propagates its forms with `cluster.HostNetworks` property
whereas users of the API are requested to manually provide
`cluster.MachineNetworks`.
This is not a desired behaviour as it prevents from forming a correct
host networks. With this change, if host contains both IPv4 and IPv6
subnets in its inventory, we will form host networks from both stacks
even if `cfg.IPv6Support` is False.
This goes in line with our current approach …

MGMT-10713: Soften IP-stack checks for host_network propagation

---

cmd/main.go
internal/ignition/ignition.go
internal/ignition/ignition_test.go
pkg/generator/generator.go

Allow the ephemeral installer to supply the TLS certificates needed to generate the kubeconfig. Copy these certs to the installer work dir. This enables the ephemeral installer to pre-generate a kubeconfig alongside the ISO and later have it accepted by the cluster.
Enhancement proposal: openshift/enhancements#1125
/cc @mhrivnak 
/cc @avishayt 

AGENT-40: Supply TLS certs for kubeconfig to openshift-install

---

api/vendor/github.com/openshift/assisted-service/models/disk.go
internal/hardware/mock_validator.go
internal/hardware/validator.go
internal/hardware/validator_test.go
internal/host/host.go
internal/host/host_test.go
models/disk.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/disk.go

This PR allows installation on disks that are identified as multipath, and where all paths are Fibre Channel (not iSCSI, for example).
/cc @tsorya 

MGMT-10705: Allow installation on FC multipath

---

cmd/main.go
internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go

This should be reverted once https://bugzilla.redhat.com/show_bug.cgi?id=2089683 is resolved
Users can enable the ZTP converged flow by setting `ALLOW_COVERGED_FLOW="true"` in the assisted environment.
- Should this PR be tested in a specific environment? dev scripts
-->
https://bugzilla.redhat.com/show_bug.cgi?id=2089683
/cc @tsorya 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull- …

BZ-2089683: Disable ZTP converged flow

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
subsystem/cluster_test.go

A call for V2UpdateCluster returns an updated cluster object
in the payload, which did not include the whole hosts' information.
This change adds a call to customizeHost() that will add this
information to the returned payload.
One use case where this is needed is an update UI does for VIP DHCP
allocation, to which it needs to retrieve the host requested name.
The UI currently worked around the issue by calling v2GetCluster,
including the above-mentioned info.
/cc @
/cc @ …

MGMT-8435: Fix V2UpdateCluster response to include hosts info

---

internal/hardware/mock_validator.go
internal/hardware/validator.go
internal/host/refresh_status_preprocessor.go
internal/host/validation_id.go
internal/host/validations_test.go
internal/host/validator.go

The parameter disk.EnableUUID is necessary so that the VMDK always presents a consistent UUID to the VM, thus allowing the disk to be mounted properly.
Please read https://access.redhat.com/solutions/4606201
/cc @
/cc @

MGMT-9561: VSphere platform lacking setting disk.EnableUUID guidance

---

docs/enhancements/extract-os-image-from-release.md

Added an enhancement document for: Extract CoreOS image from OCP release image
/cc @carbonin 
/cc @filanov 

MGMT-10618: enhancement doc - extract OS image

---

pkg/auth/rhsso_authenticator.go
pkg/auth/rhsso_authenticator_test.go

Default golang http server type is 500, so instead of unauthorized users get "server error"
Found during schema test fuzzing - almost all endpoints return HTTP 500 instead of HTTP 401
/cc @filanov 
/cc @osherdp 

auth: AuthUserAuth errors should be wrapped in HTTP 401

---

api/vendor/github.com/openshift/assisted-service/models/cluster_default_config.go
internal/bminventory/inventory.go
internal/bminventory/inventory_v2_handlers.go
models/cluster_default_config.go
restapi/embedded_spec.go
subsystem/cluster_default_config_test.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/cluster_default_config.go

This PR extends the default-config API to contain more defaults
regarding network configuration. This is driven by the fact that
Assisted UI allows now to create single- as well as dual-stack clusters
with multiple combinations of IPv4 and IPv6, therefore it's useful to
have an endpoint that will provide suggested values.
Closes: [MGMT-9710](https://issues.redhat.com/browse/MGMT-9710)
/cc @carbonin 
/cc @batzionb …

MGMT-9710: Provide extended networking defaults in default-config API

---

internal/ignition/ignition.go

To better support FC multipath, this commit configures the ignition
config to create multipath.conf and enable multipathd by default in the
live ISO.
/cc @javipolo 
/cc @tsorya 

MGMT-10656: Enable multipathd by default in live ISO

---

internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/infraenv/infraenv.go
internal/infraenv/infraenv_test.go
pkg/s3wrapper/client.go

Recently all the remaining ISOs were removed from all S3 environments so
this kind of code should never be needed from now on.
/cc @nmagnezi 

NO-ISSUE: Remove code for deleting ISOs from S3

---

deploy/operator/capi/deploy_capi_cluster.sh

In order to control the version of the hosted cluster from the Prow job
definition, we are explicitly passing the `--release-image` to the
`hypershift create` command. This is leveraging the current design that
uses `ASSISTED_OPENSHIFT_INSTALL_RELEASE_IMAGE` to decide what is the
OCP version used in the spoke cluster in the ZTP flow.
Contributes-to: [MGMT-10780](https://issues.redhat.com//browse/MGMT-10780)
/cc @eranco74 
/cc @ …

MGMT-10780: Explicitly pass OCP version to Hypershift

---

internal/common/test_configuration.go
internal/host/host.go
internal/host/host_test.go
internal/provider/baremetal/base.go
internal/provider/baremetal/installConfig.go

[MGMT-10411](https://issues.redhat.com/browse/MGMT-10411)
As part of epic https://issues.redhat.com/browse/MGMT-10087
Exposes an environment variable in the service
that allows virtual interfaces to be
used.
/cc @carbonin 
/cc @filanov 

MGMT-10411: Allow enabling virtual interfaces

---

deploy/operator/ztp/deploy_spoke_cluster.sh
deploy/operator/ztp/none_platform_utils.sh

The present implementation only uses the LOAD_BALANCER_IP, which works
fine for multi node but not for single node.
This commit changes that by obtaining the correct api IP for the single
node prior to setting up the libvirt DNS.
/cc @omertuc 

MGMT-10597 API address should be correct for SNO

---

Makefile
dev-requirements.txt
tools/wait_for_cluster_info.py

This is a modified version of the automated cherry-pick #3963
Modified to include missing Python requirements needed by the cherry-picked
code
/assign otuchfel

[release-ocm-2.4] BUG 2097820: CI - Retry cluster-info readiness 

---

docs/hive-integration/README.md
internal/ignition/ironic.go
internal/ignition/ironic_test.go

- Should this PR be tested in a specific environment? devscripts
-->
https://issues.redhat.com/browse/MGMT-10637
/cc @tsorya 
/cc @avishayt 

MGMT-10637: Add default ironic agent for ARM platform

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

Now that LVM volumes are returned in the inventory we should be sure not
to format them.
/cc @tsorya 

MGMT-10855: Do not format bootable LVM logical volumes

---

deploy/operator/ztp/deploy_spoke_cluster.sh

Reason for having this kind of message is to track down similar errors in a positive way which most CI tools are capable of.
/cc @eranco74 @tsorya 

NO-ISSUE: more indicative message when agents not coming up

---

deploy/ui/ui_ingress.yaml

Seems like newer OpenShift versions (in our case 4.9) have newer Kubernetes versions that do not support "networking.k8s.io/v1beta1" anymore. "networking.k8s.io/v1" has been introduced since 1.19 so we should move to the newer api-version.
There should be no problem moving to it, as OpenShift 4.6 already has Kubernetes 1.19 (and I don't know any env using OCP < 4.6)
/cc @lalon4 
/cc @eliorerz 
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTIN …

NO-ISSUE: update networking api-version to v1

---

subsystem/cluster_test.go

Until we'll stabilize this test, we should skip it as it fails way too much.
/cc @slaviered @gamli75 

NO-ISSUE: skip flaky auto-assign subsystem test

---

internal/controller/controllers/bmo_utils.go
internal/controller/controllers/bmo_utils_test.go

In this test [log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/29654/rehearse-29654-pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-ipv4-sno-ocp-410/1539452879935377408/artifacts/e2e-ai-operator-ztp-ipv4-sno-ocp-410/assisted-baremetal-operator-gather/artifacts/assisted-service.log) it seems that the nightly image is evaluated lower than the minimal version:
`The baremetal operator version is 4.11.0-0.nightly-2022-06-21-151125, the minimal version for the converged flow is 4.11.0-0`
This PR update the minimal version to include nightly builds
- Any logs, …

NO-ISSUE: fix MinimalVersionForConvergedFlow to include 4.11.0 nightly builds

---

deploy/assisted-image-service-service.yaml
deploy/assisted-image-service.yaml
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
tools/deploy_image_service.py

Following the change in https://github.com/openshift/assisted-image-service/pull/83, added IMAGE_SERVICE_SCHEME and IMAGE_SERVICE_HOST to image-service Deployment.
deploy_image_service.py: parsed IMAGE_SERVICE_BASE_URL and set both env vars.
AgentServiceConfigReconciler: retrieved assisted-image-service route and extracted scheme/host to set in image-service StatefulSet.
/cc @carbonin 
/cc @filanov 
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTR …

MGMT-10753: add base url to image-service deployment

---

hack/setup_env.sh

We currently have problems with golangci-lint installation, resulting with failing tests. For example:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-service-release-ocm-2.5-subsystem-kubeapi-aws-periodic/1540032169336901632
This changes log-level for that installation script to DEBUG, to help us understand what's exactly the problem.
TBD

NO-ISSUE: turn on debug logging for golangci-lint

---

deploy/operator/ztp/add-remote-nodes-playbook.yaml
deploy/operator/ztp/add_day2_remote_nodes.sh
deploy/operator/ztp/infraEnv-latebinding.j2
deploy/operator/ztp/infraEnv.j2

This is to facilitate testing of late binding functionality and is
powered by an environment variable.
If you set DAY2_LATE_BINDING to True and then call the
add_day2_remote_nodes.sh;
1: A new infraenv is generated, with no cluster reference
2: Internally within the script, this is used wherever we need an
infraenv.
3: A note is kept of the proper cluster reference and this is used later
to assign the cluster reference to any agents that need it.
/cc @omertuc 
/cc @osherdp  …

MGMT-10868: Add late binding to Day2 remote script.

---

cmd/agentbasedinstaller/agent_based_installer.go
internal/oc/mock_release.go
internal/oc/release.go
internal/oc/release_test.go
internal/versions/versions.go
internal/versions/versions_test.go

Use the mirror when running 'oc image info', similar to how all of the other 'oc' commands are used to get release info.
This functionality is only used by the agent based installer.
/cc @
/cc @

Use releaseImageMirror in GetReleaseArchitecture

---

internal/ignition/ignition.go
internal/ignition/ignition_test.go

OKD doesn't have multipathd installed, so don't try to enable it in the
agent's ignition config.
Fixes #3976
- [x Bug fix
/cc @vrutkovs 

MGMT-10956: Do not enable multipathd on OKD agent

---

OWNERS

Scripts stored under deploy/ are not included in the product, therefore
a requirement of opening a dedicated Bugzilla for master as well as
cherry-pick branch are an unnecessary burden. With this PR, whenever
such a change is opened against the OCM-2.5 branch the label will be
autoamtically applied in order to streamline the process.
Please note that we are not introducing this change in the master branch
as that one requires a manual review, but on the other hand does not
require opening a Bugzilla.
/cc @osherdp 
/cc @eranco74

Automatically label deploy/ directory with valid-bug

---

cmd/agentbasedinstaller/host_config.go

Before an agent's inventory has been discovered, we cannot match it to
any host configuration (which would require knowing the MAC addresses).
Therefore, treat it as equivalent to the host not having shown up yet.
Previously we exited with an error caused by trying to Unmarshal from
zero-length data, which results in the install failing when the
configuration command runs before inventory is available.
Part of [AGENT-227](https://issues.redhat.com/browse/AGENT-227)
This change will need to be backported to the release-4.11 branch, possibly as part of #4026.
/cc @celebdor  …

AGENT-227: Don't exit when inventory not available

---

api/v1beta1/agentserviceconfig_types.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go

When all deployments managed by infrastructure-operator are healthy,
the condition in AgentServiceConfig should have a success reason.
This fix changes the reason from DeploymentFailure to DeploymentSucceeded.
E.g.
```
Conditions:
Message: All the deployments managed by Infrastructure-operator are healthy.
Reason:  DeploymentSucceeded
Status:  True
Type:    DeploymentsHealthy
```
/cc @filanov 
/cc @carbonin 
/cc @nmagnezi  …

MGMT-10914: fix ASC deployment reason on success

---

api/vendor/github.com/openshift/assisted-service/models/cluster.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/mock_cluster_api.go
internal/common/common.go
internal/common/common_test.go
models/cluster.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/cluster.go

Create a new cluster property called `schedulableMastersForcedTrue` that
overrides `scheduleMasters` regardless its value when the number of
hosts (5) doesn't match the requirement for `scheduleMasters` to be
disabled.
This new property can be fetched from the UI and react accordingly
depending if the value for `scheduleMasters` can be set by the user or
not (e.g.: if `schedulableMastersForcedTrue == true` then disable the
toggle in the UI).
- [] None
/cc @carbonin 
/cc @avishayt 
/cc @mmartinv 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pul …

MGMT-8089: schedulableMasters field in clusters api returns wrong default values

---

deploy/operator/common.sh
deploy/operator/ztp/add-remote-nodes-playbook.yaml
deploy/operator/ztp/add_day2_remote_nodes.sh
deploy/operator/ztp/deploy_spoke_cluster.sh

Following https://github.com/omertuc/assisted-service/commit/8306b067be6e8441739fd3897a7175dbb70f2f66
A default value for `DAY2_LATE_BINDING` was not set, and as a result, jobs
that don't set it began failing since it merged. e.g. https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-operator-ztp-sno-day2-workers-periodic/1540851047231131648
Also `ASSISTED_CLUSTER_DEPLOYMENT_NAME` was not defined in that file, so
I moved it and `ASSISTED_INFRAENV_NAME` to `common.sh` as they're used
by both the spoke script and the day-2 script.
Also some ansible variables needed for the late-binding infraenv
templates were missing from the day-2 playbook
/cc @ …

MGMT-10868 - Fix unbound `DAY2_LATE_BINDING` variable error

---

hack/setup_env.sh

It's usage was removed in dc59fc0581c82393913628f8a734b662ba3a3ec9
/cc @carbonin
/cc @osherdp
/cc @mkowalski

NO-ISSUE: Remove unused butane utility

---

docs/enhancements/agent-upgrade.md

This patch adds a document describing the feature that will allow
upgrading agents without rebooting the hosts.
To be done.

MGMT-10832: Add document for agent upgrade feature

---

Makefile

Seems like we've never passed ``TARGET`` and ``INGRESS_DOMAIN" variables to the image-service deployment script, breaking the deployment when we actually needed to connect to the services.
This led to failing of PSI installations, where they cannot access the image-service URL.
/cc @lalon4 

Fix oc-ingress installation method

---

deploy/operator/common.sh
deploy/operator/ztp/deploy_spoke_cluster.sh

Following 53701f7b41730605ad0407b8b88adb6f2dbcbe4f, I missed the `ASSISTED_PULLSECRET_NAME`
variable so it lead to:
```
- lastTransitionTime: "2022-06-30T14:35:40Z"
message: 'Failed to create image due to an internal error: failed to get secret
assisted-spoke-cluster/ from API: resource name may not be empty'
```
on the late-binding infra-env as the pull secret is empty: `pullSecretRef: {}`
This commit should fix it by moving `ASSISTED_PULLSECRET_NAME` from
`deploy/operator/ztp/deploy_spoke_cluster.sh` to `deploy/operator/common.sh`
Related to https://github.com/openshift/release/pull/29787
- Cannot be tested without the job in https://github.com/openshift/release/pull/29787
/cc @osherdp
- Is …

MGMT-10868 - Fix missing `ASSISTED_PULLSECRET_NAME` in ZTP day-2 scripts

---

deploy/operator/ztp/add_day2_remote_nodes.sh
deploy/operator/ztp/infraEnv-latebinding.j2

While rehearsing 400e890fbaa096253a63fa14f2dae0d99dcda7ac in https://github.com/openshift/release/pull/29787 we encountered this failure:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/29787/rehearse-29787-periodic-ci-openshift-assisted-service-master-edge-e2e-metal-assisted-operator-ztp-sno-day2-workers-latbnd-prdc/1542833980045266944
You can see the infra-env being created is mistakenly called
`assisted-infra-env-latebinding-latebinding` rather than
`assisted-infra-env-latebinding`:
```
time="2022-07-01T13:52:56Z" level=info msg="Register infraenv: assisted-infra-env-latebinding-latebinding with id ffa05b80-7f23-4b48-bf68-0fe4d700888f" func="github.com/openshift/assisted-service/internal/bminventory.(*bareMetalInventory).RegisterInfraEnvInternal" …
```

MGMT-10868: Fix duplicate `-latebinding` suffix in ZTP latebinding scripts

---

deploy/ui/ui_ingress.yaml

Since move from 'networking.k8s.io/v1beta1' to 'networking.k8s.io/v1',
there's a need to do a couple of modifications:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
Some of those changes have been made in
https://github.com/openshift/assisted-service/pull/4003, this change
should make another modification that is needed.
/cc @lalon4 
/cc @gamli75 

Fix ui-ingress object to new API

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

This commit optimizes a call that lists all the Agents existing in the
Hub cluster. Given that we now have each Agent labeled by the
ClusterDeployment's namespace, we can ask K8s API `List()` call to
immediately filter returned resources instead of manually iterating over
all of them.
Closes: MGMG-10997
/cc @avishayt 
/cc @

MGMT-10997: Use label filtering when listing Agents via K8s API

---

cmd/main.go
internal/ignition/ignition.go
internal/ignition/ignition_test.go
internal/ignition/templates.go
internal/ignition/templates/agent.service
internal/ignition/templates/discovery.ign
internal/ignition/templates/node.ign
internal/ignition/templates/okd-overlay.service
internal/ignition/templates/pre-network-manager-config.service
internal/ignition/templates/selinux.service
internal/ignition/templates/systemd-journal-gatewayd.socket

Currently the ignition files are generated from Go templates that are
defined in constants inside the Go code. Those templates also contain
the unit files for the agent and for other systemd units. Changing those
unit files is uncomfortable, because they need to be manually encoded as
a long JSON string. To make those ignition and systemd files easier to
change this patch moves them to external files, using the `embed`
mechanism introduced in Go 1.16.
This patch also introduces to new template functions named
`executeTemplate` and `toJson` that simplify including templates from
other templates. For example, the `agent.service` template is included
from the `discovery.ign` file with this code:
```
"contents": {{ executeTemplate "agent.service" . | toJson }}
```
Manually verified that the …

NO-ISSUE: Use `go:embed` for ignition templates

---

cmd/main.go
internal/host/host.go
internal/host/host_test.go
internal/host/hostrole_test.go
internal/host/monitor_test.go
internal/host/transition_test.go
internal/host/validations_test.go

The install progress message in for a node is misleading when a Day2
host is rebooting as it states that "No further updates will be posted"
This is inaccurate as there are certain activities that could lead to an
update to the agent status. For example CSR auto signature operations.
This commit rectifies this problem by removing the confusing part of the
message.
/cc @omertuc 
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTI …

MGMT-10850: Message for Day2 reboot is misleading

---

api/vendor/github.com/openshift/assisted-service/models/cluster_default_config.go
internal/bminventory/inventory_v2_handlers.go
models/cluster_default_config.go
restapi/embedded_spec.go
subsystem/cluster_default_config_test.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/cluster_default_config.go

Presently, the frontend has no way of determining the forbidden
hostnames as defined by the backend.
This PR makes those hostnames available as part of the
cluster_default_config endpoint.
This is part of the effort being made in epic [MGMT-10990](https://issues.redhat.com//browse/MGMT-10990)
/cc @omertuc 

MGMT-10991: Add forbidden hostnames to cluster_default_config

---

cmd/main.go
internal/host/host.go
internal/host/host_test.go
internal/host/hostrole_test.go
internal/host/monitor_test.go
internal/host/transition_test.go
internal/host/validations_test.go

This PR seems to break the capi flow
it seems that as a result of this PR the agent CR of a day 2 worker will hang in rebooting and never get to done. 
This reverts commit e34274ae119fa9a3d5cd6786dd6de4716897729a.

Revert "MGMT-10850: Message for Day2 reboot is misleading (#3970)"

---

internal/host/host.go
internal/host/host_test.go
internal/metrics/metricsManager.go
internal/metrics/mock_metrics_manager_api.go

Creating an entire histogram for every host makes it impossible to query
/ graph this metric over a long period of time, prometheus can't handle
summing that many time-series.
It also doesn't make sense because each host/image pair only really
(most of the time) generates a single data point. This metric should not
include the host ID. Per-host information can be easily obtained through
the corresponding event if needed.
On top of the host ID label causing slowness, the two other labels -
"result" and "image" were used the other way around. The result
("success" or "failure") was being set in the "image" label and the
image pull-spec was being set in the "result" label.
I've swapped them back - but since this is a "metric backwards
incompatible" change I've also renmaed the metric from …

NO-ISSUE: Remove host ID from the `serviceLogicClusterHostImagePullStatus` histogram metric

---

api/hiveextension/v1beta1/agentclusterinstall_types.go
internal/controller/controllers/clusterdeployments_controller.go
subsystem/kubeapi_test.go
vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go

This PR adds a new "UnsyncedAgents" condition for marking clusters where
at least one of Agents has SpecSynced failure. Currently if this happens
we are showing a misleading error "UnapprovedAgents" coming from the
fact that data in the DB is not in sync with K8s CRs.
Contributes-to: [MGMTBUGSM-307](https://issues.redhat.com//browse/MGMTBUGSM-307)
/cc @avishayt 
/cc @

Bug 2076333: Add UnsyncedAgents error in ClusterDeployment and ACI

---

internal/common/common.go
internal/common/common_test.go
internal/metrics/metricsManager.go
internal/metrics/metricsManager_test.go
internal/metrics/suite_test.go

Currently the `assisted_installer_host_installation_phase_seconds_...`
metrics contain the agent version in the `discoveryAgentVersion` label, with
values like `v1.0.0-141`. This is copied directly from the
`discovery_agent_version` column of the `hosts` table. But with the
introduction of the agent upgrade feature this column will be changed to
store the full image reference instead of just the version number. That
means that the code that populates the metric labels needs to be changed
to detect if the `discovery_agent_version` is a full image reference,
and in that case extract the version from the tag of the image. That is
what this patch does.
Tested using the included `_test.go` files.
/cc @
/cc @
- Is …

MGMT-11026: Use image tag for metrics

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/bminventory/mock_installer_internal.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go

When a cluster is removed in the kubeAPI the clusterdeployments
controller removes all the cluster references from all the agents. This
should cause the agent controller to unbind each of those agents.
The clusterdeployment controller also calls `DeregisterClusterInternal`
which also unbinds the hosts from the cluster.
This isn't a problem currently because both operations should be doing
the same thing, but it will become a problem when hosts should be moved
back to the infraEnv on unbind only if they are not associated with an
BMH, and the kubeAPI is being used. In this case the agent controller
will know if the host should be moved to the infraEnv or not, but the
unbind call from `DeregisterClusterInternal` would have to assume that
the hosts should _not_ be moved back to the infraEnv …

MGMT-10848: Fix double agent unbind when deregistering a cluster

---

cmd/agentbasedinstaller/client/main.go
cmd/agentbasedinstaller/host_config.go
cmd/agentbasedinstaller/register.go

The errors returned from the API are not especially human-readable, they
print something like:
[POST /v2/clusters][400] v2RegisterClusterBadRequest  &{Code:0xc00052e790 Href:0xc00052e7a0 ID:0xc00053ed84 Kind:0xc00052e7b0 Reason:0xc00052e7c0}
Passing through GetAssistedError() returns an error that is readable in
the logs, including describing the reason for the failure.

NO-ISSUE: Improve error reporting in ephemeral installer client

---

api/vendor/github.com/openshift/assisted-service/models/host.go
internal/host/pool_host_statemachine.go
internal/host/statemachine.go
models/host.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/host.go

Adds the statemachine transitions and new states in order to implement
the following diagram:
```
-----------------------
| HostStatusInstalled |
-----------------------
|
User unbinds agent
|
Kube API and no BMH     |   REST API, Kube API with BMH, or other machine management
-------------------+-------------------
|                                     |
V                                     V
-----------------------------            ----------------------------
| TransitionTypeReclaimHost |            | TransitionTypeUnbindHost |
-----------------------------            ----------------------------
|                                               |
V                                               |
------------------------                                  |
| HostStatusReclaiming | …
```

MGMT-10734: Add host states and transitions for reclaim

---

internal/provider/ovirt/consts.go
internal/provider/ovirt/ignition.go
internal/provider/ovirt/installConfig.go
internal/provider/registry/registry_test.go

Set 'replicas' to 0 in the machinset instead of the install-config.yaml
This way we avoid the side effect of enabling the scheduling on masters
and MCO does not try to provision additional VMs at installation time.
This pull request depends on #3971 
/cc @eliorerz 
/cc @osherdp 

OCPRHV-637: Set 'replicas' to 0 in the machinset for the oVirt provider

---

subsystem/infra_env_test.go

[Slack thread](https://coreos.slack.com/archives/C014N2VLTQE/p1657119034700649)
Currently the subsystem test for static network config
is flaking (see thread linked) so the test will
be skipped for now to unblock the CI.
/cc @osherdp 
/cc @

NO-ISSUE: Skip failing static network subsystem test

---

cmd/agentbasedinstaller/agentbasedinstaller_suite_test.go
cmd/agentbasedinstaller/client/main.go
cmd/agentbasedinstaller/host_config.go
cmd/agentbasedinstaller/register.go

This patch extends the `register` command of the agent based installer cli by adding the possibility to register extra manifests for the cluster to be installed.

AGENT-231: Agentbasedinstaller register extra manifests

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

If the converged flow is enabled BMAC should detach the BMH only once it's provisioned
-->
https://bugzilla.redhat.com/show_bug.cgi?id=2104117
/cc @avishayt 
/cc @flaper87 
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUT …

Bug 2104117: BMH  stuck “available” after changing a BIOS attribute via the converged workflow

---

client/installer/get_infra_env_presigned_file_url_parameters.go
client/installer/v2_download_infra_env_files_parameters.go
docs/user-guide/deploy-on-bare-metal.md
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
restapi/embedded_spec.go
restapi/operations/installer/get_infra_env_presigned_file_url_parameters.go
restapi/operations/installer/get_infra_env_presigned_file_url_urlbuilder.go
restapi/operations/installer/v2_download_infra_env_files_parameters.go
restapi/operations/installer/v2_download_infra_env_files_urlbuilder.go
subsystem/infra_env_test.go
swagger.yaml

When using iPXE would like to handle any boot order.  The options are
[network, hd], and [hd, network].
Currently we are only handling the second case, where we attempt to boot
from hd first.  If we fail, then we attempt to boot from network.
If network is first, we need to handle the case that hd is already
installed and host is rebooting, or installed.  In this case we would
like to avoid using the iPXE booting and boot from hd instead.
/cc @filanov 
/cc @carbonin  …

MGMT-9982: Alter ipxe-script endpoint to handle boot order

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

When the user selects a multipath device for the installation disk, we
should pass the following kernel args:
- root=/dev/disk/by-label/dm-mpath-root
- rw
- rd.multipath=default
However when a multipath device is present but was not selected for the
installation disk, we should not pass any kernel args. Doing so causes
the host not to boot properly.
/cc @carbonin 

MGMT-11098: Pass correct kernel args for multipath

---

pkg/staticnetworkconfig/generator.go

NMState configurations are currently validated via 'nmstatectl gc' command,
which may fail for various reasons. The currently hardcoded "invalid yaml"
prefix will mislead the users to think that the problem
lies with.. well, an invalid YAML.
We have seen cases where 'nmstatectl gc' fail for other reasons.
Hence, the wording should change to something more generic + keep printing stderr.
/cc @
/cc @ …

MGMT-11120: Fix a misleading NMState error log

---

deploy/assisted-installer-ingress.yaml

Seems like we did not route access to '/boot-artifacts' endpoint of the
assisted-image-service. This PR adds this kind of route so that we can
make the flow of minimal-iso that requires it.
Without it, we're getting the following error when booting the hosts:
The downloaded file is basically a "500" HTML output in PSI environment, because this route does not exist.
/cc @eliorerz 
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBU …

MGMT-11161: fix rootfs access in PSI installations

---

internal/common/test_configuration.go
internal/host/host.go
internal/host/host_test.go

[MGMT-10844](https://issues.redhat.com/browse/MGMT-10844)
As part of epic [MGMT-10087](https://issues.redhat.com/browse/MGMT-10087)
Virtual interface data per host and per cluster are available
in the SaaS environment, even if the feature is not enabled.
This PR records the virtual interfaces each host/cluster has and
exposes it as a metric. The data will help determine if this is a
viable feature we can enable in SaaS by allowing us to predict
performance/scalability and allowing us to see any patterns/common
interfaces.
**Note**: These metrics only cover the first two data points listed in this
[document](https://docs.google.com/document/d/1eFNcEHGv14iR50Z7cSN8lQuyQx4JaPVc4uaIbGvPdgI/edit?usp=sharing) since the rest require enabling the feature. (See Caveats under 
each data point type) …

MGMT-10844: Add virtual interface metrics for SaaS

---

api/vendor/github.com/openshift/assisted-service/models/host.go
internal/bminventory/inventory.go
internal/host/host.go
internal/host/hostutil/test_utils.go
models/host.go
restapi/embedded_spec.go
subsystem/host_test.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/host.go

This PR introduces a new host property RegisteredAt in order to track
all the registration attemps. This is because an already existing host
can e.g. reboot what would trigger a new registration attempt that
currently is not tracked as a property of the host even though it
triggers an event.
This is going to be helpful as there are scenarios when we want to know
if the host rebooted after the initial registration. With this change it
will be as simple as comparing timestamps of CreatedAt and RegisteredAt.
Contributes-to: [MGMT-11131](https://issues.redhat.com//browse/MGMT-11131)
/cc @carbonin 
/cc @ …

MGMT-11131: Track hosts' registration times

---

deploy/operator/utils.sh

Since bump of Ansible to v5.9.0
(https://github.com/openshift-metal3/dev-scripts/pull/1407) we no longer
have the function
``ansible_collections.ansible.netcommon.plugins.filter.ipaddr`` but rather
it's placed at
``ansible_collections.ansible.utils.plugins.filter.nthhost``.
Otherwise, we get the following warning:
```
++ python -c 'from ansible_collections.ansible.netcommon.plugins.filter import ipaddr; print(ipaddr.nthhost('\''192.168.111.0/24'\'', 85))'
File "<string>", line 1, in <module>
ImportError: cannot import name 'ipaddr' from 'ansible_collections.ansible.netcommon.plugins.filter' (/usr/local/lib/python3.9/site-packages/ansible_collections/ansible/netcommon/plugins/filter/__init__.py)
```
and the ``SPOKE_API_VIP`` and ``SPOKE_INGRESS_VIP`` are …

Change importing of Ansible's nth-host function

---

internal/bminventory/inventory.go
internal/host/hostcommands/api_vip_connectivity_check_cmd.go

Currently whenever we generate a day2 ignition file, we hardcode
`worker` in the filename. In order to enable day2 master nodes, we want
the filename to reflect the effective role of the host. This PR
implements the change without changing the current behaviour for adding
a worker node.
Contributes-to: [MGMT-8578](https://issues.redhat.com//browse/MGMT-8578)
/cc @

MGMT-8578: Use host's role when generating day2 ignition

---

deploy/assisted-installer-ingress-tls.yaml

Back in https://github.com/openshift/assisted-service/pull/4134 I've added the ``/boot-artifacts/`` route to the regular ingress yaml that is supposedly not used in PSI installations. This will hopefully do the fix as required.
QE will test those changes, now that they have added the ability to parameterize branches.
/cc @eliorerz 

MGMT-11161: Add "/boot-artifacts/" route to ingress-tls

---

internal/host/host.go

The updateInventory function in the host package is called with db
object parameter.  This may be a transactional object.  If it is, direct
use of the internal db object cause a new db connection to be requested
from the db connection pool.  If all the connections in the db
connection pool are in use, then this function will wait.  Since this
goroutine is holding a transaction, this may result in complete halt of
all database operations.
Changed to use only the db object received as parameter.
/cc @filanov 
/cc @carbonin 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/gui …

Bug-2106496: Make sure that updateInventory function does not use the  internal DB object.

---

docs/enhancements/auto-return-agent-to-infra-env.md

Without a BareMetalHost there is currently no way to automate the process
of unbinding a host from a cluster. When a user wants to reuse a host for a new 
cluster they have to use the assisted-service unbind API, then manually boot
the host back into the discovery image.
To support automating this procedure, the assisted-service will configure nodes
in installed clusters to run an agent. When appropriate this agent will
reconfigure the host to boot into a discovery image, allowing the host to
be made available for installation without the user manually interacting with
a management system to reboot the host into the discovery image.
/cc @mhrivnak 
/cc @avishayt 
/cc @filanov 
/cc @oourfali  …

MGMT-10445: Add enhancement for automating returning an agent to the infra-env

---

internal/ignition/templates.go
internal/ignition/templates/discovery.ign

Currently the `executeTemplate` template function returns a string,
therefore assuming the result is text. This could make it difficult to
generate binary files. To make that more feasible this patch changes it
so that it returns an array of bytes. The conversion to UTF-8 encoded
strings will be performed by a new `toString` function.
Tested manually in the development environment.
/cc @
/cc @ …

NO-ISSUE: Return bytes from `executeTemplate` template function

---

internal/bminventory/inventory.go

auto-assign during host registration
It is not needed since host registration is no interactive operation.
Do not perform select for update on InfraEnv during host registration.
This is not needed since the InfraEnv is not updated in this operation.
This avoids contension while many hosts register to the same InfraEnv.
/cc @filanov 
/cc @carbonin 

Bug-2106496: Do not perform refresh status on hosts after roles need to

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go
internal/controller/controllers/clusterdeployments_controller.go

Define agent labels as variables
/cc @eranco74 

MGMT-9354: Define agent labels as variables

---

subsystem/infra_env_test.go

[Slack Thread](https://coreos.slack.com/archives/C014N2VLTQE/p1657119034700649)
The subsystem test for failing static network config check
was failing (see thread linked) due to a new version of
nmstatectl that causes the original test to pass instead of
fail.
This PR fixes the invalid network config used for the failing
test and removes the skip that was introduced in
https://github.com/openshift/assisted-service/pull/4094
/cc @osherdp 
/cc @ …

NO-ISSUE: Fix failing static network config subsystem test

---

deploy/assisted-image-service.yaml
deploy/podman/configmap.yml
deploy/podman/okd-configmap.yml
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
tools/deploy_image_service.py

Following to https://github.com/openshift/assisted-image-service/pull/88 and https://github.com/openshift/assisted-image-service/pull/89, IMAGE_SERVICE_SCHEME and IMAGE_SERVICE_HOST vars are now deprecated. Instead, all deployments should now specify only  IMAGE_SERVICE_BASE_URL.
/cc @carbonin 
/cc @filanov 

MGMT-11124: remove usage of IMAGE_SERVICE_SCHEME/HOST

---

internal/host/host.go
internal/host/host_test.go

In order to make sure that domain name resolution validation is updated
right after the domain resolution result of the host is updated, the
trigger_monitor_timestamp is updated along with the domain resolution.
Setting this field causes the monitor to be triggered.
/cc @filanov 
/cc @

MGMT-10861:  When removing/adding api* and apps records, it takes 5-15 minutes till host/cluster status is updated

---

internal/host/common.go

to worker
In case the prepare-to-installation phase failed and the role of a
master is changed to be a worker afterwards, the bootstrap flag is
not cleared which lead to repeating failures to re-install.
This PR cleans sets the bootstrap flag to false when the role of
a host is changed to worker
/cc @
/cc @

OCPBUGSM-46053: bootstrap flag is not cleaned after changing role

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/mock_cluster_api.go
internal/common/db.go
internal/host/host.go
internal/host/monitor.go
subsystem/cluster_test.go

A race between resetting the host roles on registration time and calculating the hosts' roles in the monitor has been identified in the CI.
The monitor loop would have picked up the cluster and hosts. Then, a context switch woud have ocuured. During that time, a the new host would have registered, and the roles resetted. 
Once the monitor took control again, it kept calucalting the roles only on the subset of hosts in its memory.
In the next monitoring round, it did read the new host - but since there were three masters assigned already,  it assigned that new host to server as worker, making the reset inefectual.
The fix eliminates the race by putting the reset and the re-calculation in the same thread. 
/cc @
/cc @
- Are the title and description (in both PR and commit) meaningful and …

MGMT-10852: auto-assign races

---

api/v1beta1/infraenv_types.go
client/installer/get_infra_env_presigned_file_url_parameters.go
client/installer/v2_download_infra_env_files_parameters.go
config/crd/bases/agent-install.openshift.io_infraenvs.yaml
config/crd/resources.yaml
deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
docs/user-guide/deploy-on-bare-metal.md
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/controller/controllers/infraenv_controller.go
internal/controller/controllers/infraenv_controller_test.go
restapi/embedded_spec.go
restapi/operations/installer/get_infra_env_presigned_file_url_parameters.go
restapi/operations/installer/get_infra_env_presigned_file_url_urlbuilder.go
restapi/operations/installer/v2_download_infra_env_files_parameters.go
restapi/operations/installer/v2_download_infra_env_files_urlbuilder.go
subsystem/infra_env_test.go
swagger.yaml
vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go

1.   Add Boot Control Kube API documentation
2.   Refactor boot control parameter to be ipxe-script-type both in the REST API and Kube API.
This parameter is enum with 2 possible values:
- DiscoveryImageAlways: Boot unconditionaly from the network discovery image
- BootOrderControl: Boot from discovery ISO depending on the state of
the host.
/cc @carbonin 
/cc @mhrivnak 

MGMT-11174: Add Boot Control Kube API documentation.

---

internal/bminventory/inventory.go
internal/common/common.go
internal/host/hostcommands/api_vip_connectivity_check_cmd.go
internal/host/validator.go

Presently we fetch the API address for ignition download and validation
using two independent pieces of code, these also prioritise cluster.APIVip and
cluster.APIVipDNSName in different ways, which leads to incorrect validation.
This commit addresses that by extracting this logic into a function that
may be called from both locations.
During the development of this feature, it was decided that the only
valid address during installation is cluster.APIVipDNSName and so this
function has been created to only return that.
At least for future modification, this logic is in a single location.
Additionally, the validation of whether or not an ignition is downloadable for Day2 hosts was skipped for hosts with user managed networking enabled. We have removed this so that the validation will be …

 MGMT-10790: Always use APIVipDNSName to obtain API address

---

internal/bminventory/inventory.go

Updating platform type was accidentally remove on https://github.com/openshift/assisted-service/pull/4163. 
/cc @eranco74 
/cc @gamli75 

NO-ISSUE: Fix set `platform_type` on cluster update.

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/progress_test.go
internal/cluster/transition.go
internal/cluster/transition_test.go
internal/host/host.go
internal/host/host_test.go
internal/metrics/metricsManager.go
internal/metrics/metricsManager_test.go
internal/metrics/mock_metrics_manager_api.go

This PR aims to reduce number of unnecessary labels for exported prometheus metrics.
The reason is that we want to be able to alert if our statistics (elasticsearch) falls behind (clusters, events, etc) compared to the service itself.
Once this gets merged, we will add a follow-up PR that will only add exporting event count, to enable comparison between the two systems with the most meaningful stat.
/cc @gamli75 
/cc @osherdp 
/cc @jhernand  …

MGMT-11309: clean up prom metrics to enable meaningful alerts

---

internal/host/validator.go

Just removing some comment leftover from some refactoring
Random

NO-ISSUE: Remove leftover comment

---

internal/bminventory/inventory.go
internal/bminventory/inventory_v2_handlers.go
internal/bminventory/mock_installer_internal.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go

As part of 564650feca372064314282d98d6fd9c6ee69bd2c we pretended
imported kube-api clusters are not imported, which is wrong, just
to disable DNS validations because those validations were causing
issues in the CAPI CI and we had to merge the PR quickly because
it was needed for a SaaS release.
This commit reverts that hack. We expect the capi CI to fail, but
at-least now we can fix it without hurrying to get it merged for
a release.
/cc @eranco74 …

MGMT-10973 - kube-api imported clusters should be considered imported

---

api/vendor/github.com/openshift/assisted-service/models/cluster.go
api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/usage/consts.go
models/cluster.go
models/cluster_create_params.go
models/v2_cluster_update_params.go
pkg/validations/validations.go
pkg/validations/validations_test.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/cluster.go
vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go

Introduced 'tags' support for clusters:
* Added tags property to Cluster entity.
* Support add/update tags in RegisterCluster/UpdateCluster API.
* The tags property in cluster is a comma-separated list of free-text strings.
* It is validated to support tags consist of word characters (a-zA-Z0-9_) and inner whitespaces.
E.g. "tags": "tag1,tag 2,tag3"
* When tags are set for clusters, the feature usage is enabled (for monitoring).
/cc @avishayt 
/cc @filanov 
/cc @romfreiman
/cc @rccrdpccl  
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-messag …

MGMT-11153: Add cluster tags support

---

tools/deploy_route53.py

Newer versions of Python have the following behavior:
```
In [1]: if "asd" is "asd":
...:     print("qwe")
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-1-20a61c98179a>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
if "asd" is "asd":
qwe
```
So to remove the warning we should change to the right syntax.
/cc @eliorerz 

fix python syntax of string comparison

---

internal/controller/controllers/bmh_agent_controller.go

This commit changes the way we add `detached` annotation to the BMH.
Instead of doing it always manually, we now call a helper function
responsible for logging this action and taking care of handling empty
annotations.
Contributes-to: Bug-2099929
/cc @flaper87 
/cc @omertuc

Bug 2099929: Detach BMH using dedicated function

---

internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/common/common.go

[MGMT-11362](https://issues.redhat.com//browse/MGMT-11362): Set api vip and not dnsname for day2 cluster (transform) for bm platform
We see cases where user are not able to manage dns inside their org and
they are stuck with trying to add hosts. We know that in BM case there
is no need to set dns name if we can set api vip.
Changing tranform to day2 logic to set vip in case it can
/cc @
/cc @
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING …

MGMT-11362: Set api vip and not dnsname for day2 cluster (transform) for bm platform

---

internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/controller/controllers/controller_event_wrapper.go
internal/events/api/event.go
internal/events/api/mock_event.go
internal/events/event.go
internal/host/host.go
internal/host/host_test.go
internal/host/validations_test.go

Added NotifyInternalEvent to events Sender intervace
Now when the host/cluster monitor calls reportValidationStatusChanged it will send notification in case the validation status changed.
This notification will trigger reconciliation of the relevant agent
Prior to this commit status changes from Pending to Success/Failure were ignored by reportValidationStatusChanged
- Should this PR be tested in a specific environment? kube-api
-->
https://bugzilla.redhat.com/show_bug.cgi?id=2109637
/cc @omertuc 
/cc @tsorya 
- Is there a bug required (and …

bug-2109637: Agent validations out of sync with the host validation

---

internal/bminventory/inventory.go

This commit changes the log level from INFO to DEBUG for the content of
the ignition placed inside ISO generated for a specific InfraEnv. This
is so that when using a default log level we don't print the whole
content but only the message indicating that the generation has
happened.
/cc @omertuc

NO-ISSUE: Don't log whole ignition for InfraEnv

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

This PR fixes the issue where returning `reconcileComplete{dirty: true}`
does not stop the reconciliation loop what leads to unexpected races and
objects being modified multiple times.
Closes: Bug-2112321
/cc @flaper87 
/cc @omertuc

Bug 2112321: Stop reconcile loop after changing CR inside BMAC

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

When updating machine network, we need to make sure that the field
macine_network_cidr_updated_at is updated.  Otherwise, we might get
timeout to allocate VIPs.
/cc @filanov 
/cc @

MGMT-10960: [Staging] changing machine network cidr while allocate IPs via DHCP checked , show error massage

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

This PR fixes the issue where returning `reconcileComplete{dirty: true}`
does not stop the reconciliation loop what leads to unexpected races and
objects being modified multiple times.
Cherry-picks: #4201
Closes: Bug-2112817
/cc @flaper87

Bug 2112817: Stop reconcile loop after changing CR inside BMAC

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/validations/validation_test.go
internal/cluster/validations/validations.go
subsystem/cluster_test.go
subsystem/infra_env_test.go
subsystem/kubeapi_test.go

Changed introduced here:
1. Check OCP version only if a wildcard got detected in cluster noProxy settings.
2. Never for OCP version for infraEnv noProxy settings.
3. wildcard detection should catch all cases. It will now include cases
where '*' is listed alongside other elements.
4. The 'no-proxy value '*' is not supported' will now include the OCP release version.
where '*' is listed alongside other elements.
/cc @
/cc @ …

MGMT-11035: Allow noProxy wildcard for infraEnv, regardless of OCP version

---

openshift/template-monitoring-postgres.yaml
openshift/template-monitoring.yaml

This PR adds prometheus exporter for assisted-installer.
It has been added to a separate template file, so that we can deploy it indipendently as it is not related directly with AI code, but only with its dependency.
This will allow us to have better insights on PG metrics. In this specific instance we were looking to count  added events, and we're trying to achieve this with the autoincrement counter (to account for deletions).
It also exposes other pg metrics that can be useful as replication lag and such (default in helm template used to generate this manifest)
/cc @gamli75  …

MGMT-11309: add prometheus expoter for postgresql

---

internal/ignition/ignition.go

With this PR, whenever a day2 ignition override is applies, we will
print it to the debug log. This is in order to make debugging easier as
currently the overrides are stored in BareMetalHost and Agent CRs, but
the final state (and what's pulled by the host) is the file in S3. With
this log we'll get an output of what's closer to the final ignition that
the host will apply.
In any case for day2 host we will print the rendered ignition just
before it's stored in S3 so that debug logs from the service contain all
the required content.
Contributes-to: [MGMTBUGSM-447](https://issues.redhat.com//browse/MGMTBUGSM-447)
/cc @omertuc

Bug 2099929: Print merged ignition for day2

---

docs/user-guide/README.md

Right now https://red.ht/assisted redirects to a doc that is mostly just
screenshots and explanations, with no link to the actual product. This
commit fixes that

NO-ISSUE: https://red.ht/assisted doc should link to the actual hosted installer

---

pkg/mirrorregistries/generator.go
pkg/mirrorregistries/generator_test.go

Currently the code assumes that existence of registries.conf file means
there are always registry mirrors configured. It has been observed that
the default file has no `[[registry]]` section but is still a correct
file. For such a scenario we want to proceed as the file did not exist
instead of failing.
/cc @carbonin 

MGMT-8890: Handle registries.conf without any mirrors correctly

---

deploy/operator/ztp/add-remote-nodes-playbook.yaml
deploy/operator/ztp/assisted-installer-crds-playbook.yaml
deploy/operator/ztp/baremetalHost.j2

This PR adds the possibility to have CI ZTP job create BMH definitions
containing ignition override.
Please note the override here is very opinionated and crafted based on
one of the most problematic we have encountered till now. It's hardcoded
here so that we don't need to carry it around o/release. Given that the
sole use of jinja templates here is our CI and the default disables it,
it carries no risk.
Contributes-to: Bug-2099929
Contributes-to: [MGMTBUGSM-447](https://issues.redhat.com//browse/MGMTBUGSM-447)
/cc @omertuc

Bug 2099929: Allow CI ZTP job with ignition override

---

deploy/operator/setup_lso.sh

A couple of months ago we didn't have LSO available in 4.11 catalog of redhat-operators index
This reverts https://github.com/openshift/assisted-service/pull/4060 as we should now have it in place.
TBD

MGMT-11020: revert usage of 4.10 catalog for 4.11 ZTP jobs

---

Dockerfile.assisted-service-build
hack/setup_env.sh

Basically a manual backport of https://github.com/openshift/assisted-service/pull/4077.

[release-ocm-2.5] MGMT-11412: fix flaky installation of golangci-lint

---

internal/controller/controllers/bmh_agent_controller.go
internal/ignition/ignition_test.go

This PR changes the order of calling ignition merge function in BMAC.
This is because the function is not performing a merge towards the
latest provided ignition but merges towards the ignition version
provided as a second parameter.
Because of this behaviour we have observed cases where user providing
ignition override v3.2.0 was receiving a rendered ignition v3.1.0 with
some data lost (i.e. features introduced in 3.2 and not available in
3.1).
Fixes: Bug-2113954
Fixes: Bug-2099929
Closes: [MGMTBUGSM-447](https://issues.redhat.com//browse/MGMTBUGSM-447)
Closes: [MGMTBUGSM-499](https://issues.redhat.com//browse/MGMTBUGSM-499)
/cc @carbonin

Bug 2113954: Fix order when merging ignitions

---

docs/events.yaml
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/common/events/events.go
internal/host/host.go
internal/host/host_test.go
subsystem/metrics_test.go

Updated both cluster and host monitors to send an event for every failing validation regardless of the previous validation status (unless it was already failing...)
The monitor will send validation status changed metrics only in case it moved from success to failure,
keeping this logic for the metrics since thats what what the metrics name implys e.g. assisted_installer_cluster_validation_failed_after_success_before_installation
Update Host/ClusterValidationFailedEvent message string to be more generic
- Any logs, screenshots, etc that can help with the review process? the change should be visible in the events tab
--> …

MGMT-11426: Assisted-service should publish event for failing validations

---

internal/common/test_configuration.go
internal/host/validations_test.go
internal/host/validator.go

Fixes the following issue and adds test to a feature that previously
didn't have tests:
The IsDNSWildcardNotConfigured validation should be pending before the agent responds with domain resolutions
100%
1. Boot a host
2. See that IsDNSWildcardNotConfigured is in error
3. Wait for DNS resolutions to arrive from the agent
4. See that IsDNSWildcardNotConfigured is no longer in error
IsDNSWildcardNotConfigured is in error for a while because it's can't decode the empty non-existing result as JSON
IsDNSWildcardNotConfigured should never be in error before resolutions, it should be pending instead …

MGMT-11444 - Wildcard DNS validation should be pending before we have DNS resolutions

---

api/vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_response.go
internal/host/validations_test.go
internal/host/validator.go
models/api_vip_connectivity_response.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_response.go

The current message (constructed by the UI) is "API IP connectivity
failure - To continue installation, configure your DNS or alternatively
<a>Update cluster with API IP</a>"
There are multiple issues with the current message:
1) The title says "API IP connectivity failure". This is not technically
correct. The issue is reaching the API in general. It doesn't
necessarily have anything to do with an "IP address".
2) The suggestion to "configure your DNS or Update cluster with API IP"
is misleading - it seems to imply that if the user chooses to not
configure their DNS, they can simply "update the cluster with API IP"
and everything will work fine. This is not necessarily correct -
none-platform clusters require the user to configure DNS, regardless
of whether they provide us with the IP …

MGMT-11447: Improve ignition downloadable (day2 API connectivity check) validation message

---

dev-requirements.txt

Somewhere around July 31 2022, the 'publish-python-client' job started failing (see
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-assisted-service-master-edge-publish-python-client/1553847262923198464) with the following error:
```
python3 -m twine upload --skip-existing
"/home/assisted-service/build/ci-op-9xpc88fc/assisted-service-client/dist/*.whl"
File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/opt/venv/lib64/python3.9/site-packages/twine/__main__.py", line
22, in <module>
from twine import cli
File "/opt/venv/lib64/python3.9/site-packages/twine/cli.py", line 18,
in …
```

MGMT-11521: Fix twine upload of assisted-service-client

---

api/hiveextension/v1beta1/agentclusterinstall_types.go
api/hiveextension/v1beta1/zz_generated.deepcopy.go
config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
config/crd/resources.yaml
deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
internal/controller/controllers/clusterdeployments_controller.go
subsystem/cluster_test.go
subsystem/kubeapi_test.go
subsystem/utils_test.go
vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go

Add support for defining PlatformType in Kube API.
The PlatformType names are aligned with OpenShift PlatformTypes.
Since the BE can set the platform type and the UserManagedNetworking flag,they are both reflected in the Status section.
/cc @
/cc @

MGMT-11416: support platform in kube-api

---

cmd/main.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/mock_installer_internal.go
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/controller/controllers/agent_reclaimer.go
internal/controller/controllers/agent_reclaimer_test.go
internal/host/host.go
internal/host/host_test.go
internal/host/mock_host_api.go
internal/host/transition_test.go
subsystem/kubeapi_test.go

Run a pod on the spoke node when the agent associated with that node is unbound.
This agent will boot the host back into the discovery image, allowing it to be reused from the same infraEnv.
This is only done when the agent does not have an associated BareMetalHost.
This PR also adds a feature flag for all of this that will prevent us from moving to `HostStatusReclaiming` even if the BMH isn't present. This is added so that the feature can be worked on incrementally. Without this we would need all the agent commands to be implemented before this could be merged.
https://issues.redhat.com/browse/MGMT-10739
Part of the implementation for the [Automatically Return Agents to InfraEnv enhancement](https://github.com/openshift/assisted-service/blob/6b8401d3b0f0ceea5a837f33c17b9b1cd5ec52a3/docs/e …

MGMT-10739: Reclaim agents on unbind

---

internal/host/common.go
internal/host/common_test.go
internal/host/hostutil/test_utils.go
internal/host/validator.go

When there are many connectivity check packet losses, the packet loss validation
status message contains list of the failed hosts, and the failure
percentage for each.
In order to create the list of failed hosts, each failed host is
identified by its IP address.  Since the IP address is in the inventory,
to identify the host all inventories in the cluster need to be
unmarshalled.
The change is to identify the host by host-id and not by the IP address.
In this case, inventory unmarshalling is not needed for host
identification, because the search is by host id.
/cc @filanov 
/cc @ …

MGMT-11543: When there are many connectivity check packet losses, the host monitoring thread gets stuck

---

internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/progress_test.go
internal/cluster/statemachine.go
internal/cluster/transition.go
internal/cluster/transition_test.go
subsystem/cluster_test.go

In order to move cluster to finalizing, 3 masters and 2 workers have to
be installed.  The others are still may not be installed yet.
If the cluster installation is complete (operators are up and kubeconfig
in place) but some nodes have not completed installation, these hosts
will never move to installed because they depend on the controller to
report the stage.
The controller stops running if cluster is not in installation status.
This means that these hosts will eventually move to error on timeout.
This change ensures that cluster can move from finalizing to insllled
only if all its hosts are either installed, or in error.
This change also enables transition from finalizing to
pending-user-action if there is a host in pending-user-action while the
cluster is finalizing. The cluster will …

Bug-2107617:  Attempted 240 node cluster with MCE / Assisted-installer and ended up with 187 node cluster

---

internal/cluster/validations/validation_test.go
internal/cluster/validations/validations.go

[MGMT-11621](https://issues.redhat.com/browse/MGMT-11621)
[MGMT-11614](https://issues.redhat.com/browse/MGMT-11614)
Subdomains are allowed according to RFC 1123, so
this change modifies the regex to  allow cluster
names to have subdomains.
/cc @nmagnezi 
/cc @jtomasek 
/cc @filanov 

MGMT-11621: Allow subdomains in cluster name

---

internal/common/common.go
internal/versions/versions_test.go

This PR adds a set of explicit unit tests to ensure that extending
release image with `cpu_architectures` didn't break compatibility with
images using `cpu_architecture` and ignoring the old fields.
This tests adds explicit coverage for the following two scenarios:
1) image containing `cpu_architecture` and missing `cpu_architectures`
2) image containing both `cpu_architecture` and `cpu_architectures`
Contributes-to: [MGMT-11494](https://issues.redhat.com//browse/MGMT-11494)

MGMT-8890: Unit test to ensure compatibility of release images

---

Dockerfile.assisted-service

We started getting a lot of failures when installing 'oc' as part of assisted-service build:
```
11:31:32 Step 31/41 : RUN curl --retry 5 -s $OC_URL | tar -xzC
/usr/local/bin/ oc
11:31:32  ---> Running in 344822c28b1b
11:31:32
11:31:32 gzip: stdin: unexpected end of file
11:31:32 tar: Child returned status 1
11:31:32 tar: Error is not recoverable: exiting now
11:31:32 The command '/bin/sh -c curl --retry 5 -s $OC_URL | tar -xzC
/usr/local/bin/ oc' returned a non-zero code: 2
11:31:33 make: *** [update-minimal] Error 2
11:31:33 Build step 'Execute shell' marked build as failure
11:31:33 Finished: FAILURE
```
It seems to affect builds on both app-sre and dptp platforms.
How reproducible:
On CI systems 100% (see prow and ci.ext.devshift.net), locally I
couldn't produce it.
More concrete …

MGMT-11708: install oc from quay.io

---

internal/common/common.go
subsystem/kubeapi_test.go

This PR changes the value used to mark multiarchitecture OpenShift
clusters from "multiarch" to "multi". This is because the official
version marker is `-multi` so that all the tooling relying on this name
does not have to perform any translation.
An example of the currently performed translation is "amd64" and
"x86_64" that are representing the same architecture in two different
ways. With this change here we will not need to handle "multi" and "multiarch"
as the only used one will be "multi".
The change is safe as there are no clusters created using multiarch
release payload yet.
/cc @carbonin 
/test edge-e2e-ai-operator-ztp-multiarch-sno-ocp-411

MGMT-8890: Use "multi" as a keyword for multi-arch OpenShift

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/host/host.go
internal/host/host_test.go
internal/host/mock_host_api.go
internal/host/transition.go
internal/host/transition_test.go

Adds handling for agent step replies for the `download-boot-artifacts` step type.
A successful response transitions the host from `Reclaiming` to `ReclaimingRebooting` a failure transitions the host to `UnbindingPendingUserAction`
https://issues.redhat.com/browse/MGMT-11335
Rebased this PR onto https://github.com/openshift/assisted-service/pull/4117 and manually posted the agent response.
Saw the agent progress into `ReclaimingRebooting` then into `Known` after I manually booted the machine from the discovery ISO.
/cc @nmagnezi 

MGMT-11335: Handle agent reclaim step replies

---

internal/host/host.go
internal/host/host_test.go

[MGMT-10850](https://issues.redhat.com//browse/MGMT-10850): Fix misleading day 2 reboot message.
Note: This change combines changes made in https://github.com/openshift/assisted-service/pull/3970 that had to be rolled back due to a problem >
There is an epic to solve the underlying issues https://issues.redhat.com/browse/MGMT-11047 however this is complex and will take some time for>
In the meantime, I have patched my original commit so that the host will be moved to "Done" correctly when not using KubeAPI.
/cc @tsorya 
/cc @filanov  …

MGMT-10850: Fix misleading message during KubeAPI reboot

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/versions/versions.go
internal/versions/versions_test.go
subsystem/cluster_v2_test.go
subsystem/infra_env_test.go
subsystem/kubeapi_test.go
subsystem/subsystem_suite_test.go

This PR adds a logic that ensures we create InfraEnvs that refer to
existing release images. This is in order to prevent the following
scenario
* release image contains architecture [x86_64 ppc64le s390x]
* OS images available for [x86_64 arm64]
* infraenv created for arm64
The current logic for creating the ISO already detects the case when
InfraEnv uses architecture for which no RHCOS image is available.
However a scenario where RHCOS exists but OpenShift release image does
not was not covered till now. Without the change introduced by this PR
the missing release image would be detected only during the
installation. With this change it will happen very early in the
process so that we can prevent the installation from even starting.
Closes: …

MGMT-8890: InfraEnv to validate content of release image

---

internal/versions/versions.go
internal/versions/versions_test.go

This PR modifies the openshift-versions API call so that for multiarch
release images it unpacks the supported architectures. This is required
so that instead of response containing
```
"4.11":{"cpu_architectures":["multi"]
```
we get a list of architectures from this image. With the current
behaviour it is effectively impossible to query the service about
possible architectures that are supported. This PR removes the
limitation.
Closes: [MGMT-11758](https://issues.redhat.com//browse/MGMT-11758)
/cc @carbonin

MGMT-8890: Update openshift-versions API call to return all archs

---

internal/ignition/ignition.go

Set the kubelet IP for all architectures, not just multinode. This will help us guarantee that the kubelet will always pick the right IP instead of letting other services (like OVN) advertise what IP it should get
/cc @tsorya 
/cc @

MGMT-11779: Add the kubelet IP for all architectures

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/provider/baremetal/base.go
internal/provider/registry/registry.go
internal/provider/registry/registry_test.go
subsystem/kubeapi_test.go

- Make `none platform` as a valid platform
- When setting `UserManagedNetworking` (on cluster creation and on cluster update), if `UserManagedNetworking=true && Platform.Type == "baremetal"` than `cluster.Platform.Type` is set to `"none"`
- Allow creating and updating cluster with `Platform.Type = none`  
- `GetSupportedProvidersByHosts` returns also `none` platform alongside `baremetal`
/cc @eranco74 
/cc @avishayt 
/cc @gamli75

MGMT-10816: Returning the actual resulting cluster platform

---

internal/versions/versions.go
internal/versions/versions_test.go

With this commit we are changing behaviour of the "openshift-versions"
API call so that it returns only versions and architectures if there is
a matching release image as well as RHCOS image.
This is in order to cover a scenario when a multi-arch release image is
used by the service, but available OS images do not contain every
architecture that is provided by the release. For such a scenario we
only want to mark availability for those combinations that have a
coverage in both release as well as RHCOS image.
Closes: [MGMT-11780](https://issues.redhat.com//browse/MGMT-11780)

MGMT-8890: Add OS image validator to openshift-versions API call

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
subsystem/cluster_v2_test.go

This PR introduces a change that marks all the cluster using multiarch
release image as multiarch clusters. This is in order not to force users
(whether via API or via UI) to manually set that property if based on
the selection of the release image we know that the cluster is able to
consist of multiple architectures.

MGMT-8890: Mark cluster as multi-arch automatically

---

internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go

When creating a ClusterDeployment we call AddReleaseImage to ensure the relevant release image is available.
If an applicable OS image is missing, the sync condition should include a proper message. Hence, added to the underlined issue to the condition message.
E.g.
`The Spec could not be synced due to backend error: failed to add release image 'quay.io/openshift-release-dev/ocp-release:4.7.52-x86_64'. Please ensure the releaseImage field in ClusterImageSet 'openshift-v4.11' is valid (error: No OS images are available for version 4.7.52 and architecture x86_64).`
/cc @filanov
/cc @nmagnezi  …

MGMTBUGSM-482: kube-api - improve error msg for missing OS image

---

internal/ignition/templates/discovery.ign

Fix the modes of scripts to their proper decimal representation.
This addresses issue #4310

Update discovery.ign to fix incorrect file modes

---

cmd/agentbasedinstaller/register.go

Currently the network type is unspecified for cluster0. When
unspecified the network type defaults to OpenShiftSDN, even
if the user had specified OVNKubernetes.
We need the cluster to reflect the network type specified in
AgentClusterInstall. The CreateClusterParams for cluster0 now
includes the AgentClusterInstall's NetworkType value.
A compact cluster was deployed using dev-scripts. dev-scripts was modified to use a custom assisted-service image containing this change and was modified to set the AgentClusterInstall's NetworkType to OVNKubernetes. After the cluster has been installed, I verified that ovn kubernetes was deployed by seeing these pods listed:
```
openshift-ovn-kubernetes                           ovnkube-master-26dpc …
```

AGENT-325: Support setting network type from AgentClusterInstall

---

pkg/validations/validations.go
pkg/validations/validations_test.go

Added more details to invalid cluster tags format error message. The message should mention  which characters are valid for tags (as described in the [doc](https://github.com/openshift/assisted-service/blob/2343139dee37c5950e159513ff85bba8b3fdb9b2/docs/user-guide/rest-api-cluster-tags.md#L3-L4).
/cc @filanov 
/cc @avishayt 

MGMT-11596: improve invalid tags format message

---

internal/versions/versions.go
internal/versions/versions_test.go

This PR fixes labeling of the default release image in case when x86
single-arch as well as multi-arch are provided. We are now allowing to
set the "default" property on any image for a specific OCP version
without requiring the flag to be present on a particular architecture.
Contributes-to: [MGMT-11563](https://issues.redhat.com//browse/MGMT-11563)
/cc @osherdp

MGMT-11563: Fix default label for release image

---

internal/controller/controllers/agent_controller.go

This condition was reverted, it should run getClusterDeploymentAdminKubeConfigSecretName if clusterDeployment CR was retrieved successfully
Identified by @carbonin -> https://github.com/openshift/assisted-service/pull/3411/files#r955343608
/cc @carbonin

NO-ISSUE: Fix condition to get kubeconfig secret name from CR

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

Fix changes made on https://github.com/openshift/assisted-service/pull/4158.
One case was missed, if platform (e.g. vsphere) is different than none or baremetal with user-managed-networking enabled it will result none platform instead of the desired platform.
/cc @gamli75 
/cc @vrutkovs

MGMT-11973: Fix vSphere platform with enabled user-managed-networking results none platform

---

client/installer/v2_download_infra_env_files_parameters.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/ignition/ignition.go
internal/ignition/ignition_test.go
internal/ignition/mock_ignition.go
restapi/embedded_spec.go
restapi/operations/installer/v2_download_infra_env_files_parameters.go
restapi/operations/installer/v2_download_infra_env_files_urlbuilder.go
swagger.yaml

This adds a non-mandatory field that may contain the values 'full-iso' or 'minimal-iso' when it is set in the request.
This will override any defaults that we read from the infra-env
and will inject or omit static network config from the discovery ignition as applicable.
If the parameter is left undefined then the existing behaviour of generating static network config based on the infra env type will be used.
This corresponds to the truth table shown below.
-----------------------------------------------------------------------------------------------
infraenv type | overrideImageType          | discovery ignition contains static network config?
-----------------------------------------------------------------------------------------------
full iso      | nil                        | yes …

MGMT-11442: Add override ISO type parameter for v2DownloadInfraEnvFiles

---

docs/pull_request_template.md

Since draft mode enables us to start off with no reviewers being mentioned, we can remove that part now.
/cc @flaper87 

Remove reviewers listing from PR template

---

Dockerfile.assisted-service-build

This fixes the following issue with with generating mocks:
```
assisted-service/internal/provider/registry/gomock_reflect_1416499741/prog.bin: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by assisted-service/internal/provider/registry/gomock_reflect_1416499741/prog.bin)
assisted-service/internal/provider/registry/gomock_reflect_1416499741/prog.bin: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by assisted-service/internal/provider/registry/gomock_reflect_1416499741/prog.bin)
```
The problem seems to have shown up when we moved back from centos9 to centos8, but didn't revert all of the original changes in the build dockerfile from b89497057.
One of these changes added these `CGO_CFLAGS`
Previously `skipper make generate-mocks` failed.
With this change it …

Remove CGO_CFLAGS in build image

---

internal/operators/cnv/manifest.go

Operations require a default storage class to function properly, since we are installing those, we can also mark them default:
- Set HPP storage class as default
- LVM Operator takes care of creating and setting its storage class to default: https://github.com/red-hat-storage/lvm-operator/pull/210 So no action required.
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>
/cc @Mrudraia 
/cc @gamli75  …

NO-ISSUE: Assign default storage classes on SNO

---

cmd/main.go
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

This was needed so that we could merge the work a bit at a time. Now that all the pieces are in place for reclaim to work correctly this can be removed.
This isn't a problem for non-kubeapi deployments as the agent controller is the only place we will ever run the reclaim transition.
https://issues.redhat.com/browse/MGMT-12062
cc @CrystalChun 
cc @danielerez 
cc @ori-amizur

MGMT-12062: Remove host reclaim feature flag

---

cmd/main.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/versions/mock_versions.go
internal/versions/versions.go
internal/versions/versions_test.go
pkg/ocm/utils.go
subsystem/authz_test.go
subsystem/cluster_v2_test.go
subsystem/subsystem_suite_test.go
subsystem/utils_test.go
subsystem/versions_test.go
subsystem/wiremock_stubs.go

Contributes-to: [MGMT-11563](https://issues.redhat.com//browse/MGMT-11563)
Contributes-to: [MGMT-11859](https://issues.redhat.com//browse/MGMT-11859)
Implements: https://github.com/openshift/assisted-service/pull/3744
Implements-enhancement: saas-per-organization-feature-access
/cc @nmagnezi 

MGMT-11563: Allow org-based filtering for multiarch images

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

We missed a case when first we have (creating or creating + updating) cluster with platform different than baremetal/none and next updating the cluster UMN to with sone value (true or false)
Issue: https://issues.redhat.com/browse/MGMT-12063
/cc @eranco74 
/cc @gamli75

MGMT-12063: Fix update cluster UMN when platform is different from baremetal/none

---

internal/bminventory/inventory_test.go
internal/provider/base.go
internal/provider/none/installConfig.go
internal/provider/vsphere/installConfig.go

Starting installation when platform=vsphere and UMN enabled it immediately returning from preparing-for-installation to ready state (returning to the `Review and create` tab).
From the service log it seems that one of the CIDRs is empty:
`error="invalid CIDR address: "`
It seems that the machine_networks on the install-config was empty. This PR configuring the networking properly. 
Task: https://issues.redhat.com/browse/MGMT-12063
/cc @tsorya 
/cc @gamli75

MGMT-12066: Fix installation failed to start when UMN is enabled

---

internal/host/hostcommands/instruction_manager.go
internal/host/transition_test.go
internal/host/validator.go

[MGMT-12078](https://issues.redhat.com//browse/MGMT-12078): When install cmd is sent we were asking agent to run next
step after 2 minutes and it is leaving us only with one more try of next
step in order not to be disconnected.
There is not reason for it currently as we handle already double install
cmd issues
[MGMT-12078](https://issues.redhat.com//browse/MGMT-12078): Bootstrap got disconnected due to long wait in agent
after install cmd and recreation of resolv.conf by dispatcher scripts
Increasing disconnection timeout for bootstrap as it's resolv.conf is
recreated in the middle of installation and it causes dns lost sometimes
that in it's turn causes disconnection of the bootstrap and installaiton
failure
- …

MGMT-12078: increasing disconnection timeout for bootstrap and allowing running next step command after a minute on Installing state

---

docs/enhancements/add-external-providers.md

`SetPlatformValuesInDBUpdates` was removed as part of https://issues.redhat.com/browse/MGMT-10815
/cc @gamli75

NO-ISSUE: Remove `SetPlatformValuesInDBUpdates` from `ProviderRegistry` enhancement

---

ci-images/Dockerfile.base
ci-images/Dockerfile.code-generation
ci-images/Dockerfile.lint
ci-images/Dockerfile.subsystem
ci-images/Dockerfile.unit-tests

In order to be able to do quick fixes with less rehearse jobs and to spot duplicated code, we should have all CI-related images inside the repository (currently it's configured ad-hoc in the ``openshift/release`` repo).
This mainly copies the Dockerfiles to this repo without any significant changes.

MGMT-11753: moving CI Dockerfiles to the repo

---

internal/common/common.go
internal/common/common_test.go

When generating the Ignition files, the installer already sets schdulableMasters to true when there are no worker nodes (i.e. in the SNO and compact cluster topologies. (See
https://github.com/openshift/installer/pull/2004) Therefore it is unnecessary to override it here (though it may be preferred to avoid a warning log from the installer).
Since https://github.com/openshift/installer/pull/6247, attempting to override the schedulableMasters setting causes installation to fail, because there are two manifests of the same type and name that conflict.
Since we don't need to set this override when the installer would already do it, avoid doing so and triggering the error when the value is determined by the number of hosts rather than explicitly set by the user.
The conflict still needs to be …

OCPBUGS-1482: Don't override schedulableMasters unnecessarily

---

internal/bminventory/inventory.go
internal/bminventory/mock_installer_internal.go
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/host/host.go

When adding a worker to an existing cluster we move straight from Rebooting to Done.  However,  with the k8s API we have the kubeconfig and can determine the stages more accurately.
1. If kubeAPIEnabled, do not move the Agent to Done, leave it in Rebooting.
2. If the agent-controller sees:
a. a ready node for that host, move the Agent to Done
b. a non-ready node for that host, move the Agent to Joined
- Should this PR be tested in a specific environment? yes, with the infrastructure-operator
- Any logs, screenshots, etc that can help with the review process? nope
-->
https://issues.redhat.com/browse/MGMT-11047
/cc @carbonin 
/cc @nmagnezi  …

MGMT-11056: Additional stages when adding workers with k8s API

---

hack/update_local_image.sh

This PR changes the hack script to build the service image in the context of minikube cluster instead of using directly a Podman or Docker runtime.
The rationale for this is the following - Minikube allows selection of driver (aka. where it runs) and runtime (aka. what it runs). It means that we can have a Minikube cluster running in the following combinations:
* in a VM, serving CRI-O API
* in a VM, serving Docker API
* in a container, serving CRI-O API
* in a container, serving Docker API
In order to talk natively using `podman` or `docker` CLI on the host, Minikube cluster must be serving a matching version of the runtime, e.g.
* RHEL host with Podman 4.0 cannot talk to Minikube serving Docker API
* RHEL host with Docker can talk to minikube serving Docker API
Because any kind of …

NO-ISSUE: Increase compatibility of hacks for different OS

---

deploy/operator/libvirt_disks.sh

This change enable the shell debug in `libvirt_disks.sh` in order to
investigate why ztp jobs fail from time to time with the following
error:
```
[2022-09-22 11:23:24] Creating libvirt disks and attaching them...
[2022-09-22 11:23:24] Formatting '/tmp/ostest_worker_0-sdb.img', fmt=raw size=53687091200
[2022-09-22 11:23:24] error: Failed to attach disk
[2022-09-22 11:23:24] error: Requested operation is not valid: Domain already contains a disk with that address
```
https://search.ci.openshift.org/?search=Domain+already+contains+a+disk+with+that+address&maxAge=168h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

NO-ISSUE: Add shell debug for libvirt_disks.sh

---

internal/bminventory/inventory_test.go
internal/host/hostutil/host_utils.go
internal/host/hostutil/host_utils_test.go

https://issues.redhat.com/browse/MGMT-12130
Previously, we allowed hostnames longer than 64 characters which caused an issue with setting Kubernetes labels. Now we reduced the limit to 64 characters.
/cc @carbonin @filanov

MGMT-12130: Reduce hostname length to 64 characters

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/controller/controllers/clusterdeployments_controller_test.go

Abstract the way that we're getting the spoke Admin KubeConfig name
This way it can be reused if needed and we can also run some tests against it
/cc @carbonin

NO-ISSUE: Abstract how to get spoke kubeconfig from ClusterReference and add tests

---

internal/host/host.go
internal/host/mock_host_api.go
internal/host/mock_transition.go
internal/host/statemachine.go
internal/host/transition.go
internal/host/transition_test.go

This function is not called, its purpose is not entirely clear at this
point, so it should be removed to simplify the state machine.

NO-ISSUE: Remove unused `RegisterInstalledOCPHost` and its associated transition

---

internal/bminventory/inventory.go
pkg/staticnetworkconfig/generator.go
pkg/staticnetworkconfig/generator_test.go
restapi/embedded_spec.go
restapi/operations/installer/v2_download_infra_env_files_parameters.go
subsystem/infra_env_test.go
swagger.yaml

[MGMT-11443](https://issues.redhat.com/browse/MGMT-11443)
Adds an API to get the network manager config files at the endpoint `/v2/infra-envs/<infra-env-id>/downloads/files?file_name=static-network-config`
Returns a tar archive of the network config files for this infra-env.
WIP: Still need to add unit tests
[MGMT-11443](https://issues.redhat.com/browse/MGMT-11443)
/cc @carbonin

MGMT-11443: Add API to retrieve Network Manager Config Files

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/operators/manager.go
internal/operators/manager_test.go
subsystem/cluster_test.go
subsystem/operators_test.go

MGMT-11635: Bad request error when user chooses both LVM and CNV

---

pkg/validations/validations_test.go

MGMT-11878: Extend validator unit-tests to contain IPv6 URLs

---

docs/dev/running-test.md

This change allows to use the same setup for test-infra and subsystem. As the default minikube tries to use as much of Docker as possible, we want to explicitly point it to use Podman.

NO-ISSUE: Update subsystem docs to use minikube with podman

---

api/v1beta1/hypershiftagentserviceconfig_types.go
cmd/operator/main.go
config/rbac/role.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
internal/controller/controllers/common.go
internal/controller/controllers/hypershiftagentserviceconfig_controller.go
internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
internal/spoke_k8s_client/spoke_k8s_client.go
vendor/github.com/openshift/assisted-service/api/v1beta1/hypershiftagentserviceconfig_types.go

In order to deploy assisted-service on a spoke hypershift cluster, the agent-install CRDs must first exist on it.
Hence, introduced the following flow to ensure each CRD exists (and not stale) on the spoke cluster:
* List the relevant CRDs on the management cluster.
* For each one, create/update on the spoke cluster.
/cc @mhrivnak 
/cc @carbonin 
/cc @filanov 

MGMT-11751: ensure agent-install CRDs exist spoke cluster

---

cmd/agentbasedinstaller/register.go
docs/hive-integration/crds/agentClusterInstall-with-installconfig-overrides.yaml
subsystem/agent_based_installer_client_test.go

The annotation was mistakenly ignored. This sets it on the cluster.
- Should this PR be tested in a specific environment? agent based installation …

AGENT-374: agent-based-client: Apply installconfig overrides

---

cmd/operator/main.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go

First installment of refactoring ASC reconciler so code can be shared between the HypershiftAgentServiceConfig and the existing ASC.
Existing State:
----------------------
1. Component functions (function that returns the k8s artifacts required for deployment) assume default pre-configured namespace.
2. Component functions receive reference to AgentServiceConfig type.
3. Component functions are members of the AgentServiceConfigReconciler.
Changes:
-----------------
1. Component functions accept namespace as parameter. The calling function now passes the above pre-configured namespace (r.Namespace)  as a parameter.
2.  Define a state object ASC which holds the state of the reconciler and the common part of the configuration. This allows inversion of control in the component functions where …

MGMT-11736: refactor ASC reconciler

---

deploy/operator/mirror_utils.sh
deploy/operator/setup_lso.sh

Starting from OCP 4.12 the CatalogSources are replaced with file-based catalogs. Because of that, our current catalogs are not working when the Hub cluster is OCP 4.12. In order to workaround this we follow the recommendation from https://access.redhat.com/articles/6977554 and use the legacy mode.
/cc @vrutkovs 
/hold

NO-ISSUE: Use legacy security context for disconnected CI

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

This PR changes the behaviour of logic responsible for appending `ip=<nic>:dhcp` kernel parameters. Those must not be added when static network configuration is used as in some specific cases it causes loss of connectivity due to NetworkManager having to deal with two contradicting configurations (static config created by NMstate and DHCP as requested by kernel parameter).
With this change as soon as we detect that InfraEnv has network configuration provided by the user, we will not add any `ip` kernel param. This is not expected to cause any trouble as the behaviour will be as follows
* with no static configuration, `ip=<nic>:dhcp` will be set on the NIC that is used to provision the server (behaviour like today)
* with static configuration the NIC used to provision the server should …

Bug 2106110: Don't set ip=<nic>:dhcp kernel params with static networking

---

internal/host/validations_test.go
internal/host/validator.go

This commit improves the bad DNS wildcard validation message to include
the list of IP addresses that the bad wildcard domain resolves to.  This
might help users understand where the bad wildcard record is coming
from.
See https://github.com/openshift/assisted-service/issues/4477 - user was
stuck on this validation for a while but was able to figure out the
issue almost immediately when I told them the IP address that gets
resolved is 127.0.0.1 (turns out it's some weird known router
issue/behavior)
Also fixed a (theoretical) bug where when the agent omitted the wildcard
entry from its DNS resolution response, the validation would fail
(instead of error) and would tell the user that the domain is resolving
while in reality we don't really know whether it's resolving or not.
- Unit test
- …

NO-ISSUE: DNS bad wildcard validation message should include IP addresses

---

deploy/podman/README-disconnected.md
deploy/podman/configmap-disconnected.yml
deploy/podman/pod-persistent-disconnected.yml

NO-ISSUE: Adding documentation on how to use the Assisted Installer in a disconnected mode.
In working on a Proof of Concept, I needed the ability to use the Assisted Installer in a fully disconnected/air-gaped environment. The README and associated yaml are the results of this POC, which allowed for using the Assisted Installer in a fully disconnected environment, leveraging a container image registry and mirror of the RHCOS ISO. This is a documentation/process update only.
Signed-off-by: Mark DeNeve <xphyr@users.noreply.github.com>
I have tested this documentation against two different environments to ensure that there were no steps missed.
/cc @mhrivnak 
- [x ] Title and description added to both, commit and PR.
- [x ] Relevant issues have been associated (see …

document process for using assisted installer in a disconnected env

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/versions/mock_versions.go
internal/versions/versions.go
internal/versions/versions_test.go
subsystem/cluster_v2_test.go
subsystem/kubeapi_test.go

This PR creates the `ValidateReleaseImageForRHCOS` function responsible for validating whether a specified RHCOS version has a matching OCP release available, as otherwise it makes no sense to create such an InfraEnv as it would be effectively unusable until a valid OCP version appears.
This has been discovered only after multi-arch clusters got the validation between InfraEnv (i.e. RHCOS image) and OCP release. With the ability to perform weak matching we don't need to align RHCOS image to the z-stream of OCP, so e.g. we can offer `4.12.0-ec.3-multi` to be served by `4.12` RHCOS (without that change we need to label RHCOS explicitly as `4.12.0-ec.3-multi`).
Single-arch clusters are not affected, as for such a cluster InfraEnv does not perform any validation whatsoever.
Closes: …

MGMT-8890: Create validator for RHCOS and OCP versions

---

docs/events.yaml
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/common/events/events.go

[MGMT-11642](https://issues.redhat.com/browse/MGMT-11642)
Adds host bind/unbind events and correct the unit tests to expect these new
events where appropriate.
Previously, these unit tests incorrectly expected events which was not caught
by ginkgo. When ginkgo is upgraded to v2, these unit tests will correctly fail. The 
original event expected `HostRegistrationFailedEvent` did not match the test or
flow.
Bind/Unbind hosts should trigger an event, since binding/unbinding is different from
registering/unregistering.
[MGMT-11642](https://issues.redhat.com/browse/MGMT-11642) …

MGMT-11642: Add Host Bind/Unbind Events

---

tools/pvc_size_utils.py

The kubectl command was missing curly braces. The output would be: `".spec.resources.requests.storage"`, causing the rest of the script to error out.
- deployed subystem tests and `make deploy-service-for-subsystem-test` passed successfully. 
- Also added the following into `tools/pvc_size_utils.py` and ran `$ python3 tools/pvc_size_utils.py` to make sure the output was correct.
```
if __name__ == "__main__":
size = get_current_size_if_exist(target="local", namespace="assisted-installer", pvc_name="postgres-pv-claim")
print(size)
``` …

NO-ISSUE: Fix command syntax for getting postgres size

---

internal/host/common.go
internal/host/host_test.go
internal/host/hostutil/host_utils.go

This PR adds validation for the Agent's role whenever an update is requested. This is in order to prevent configuration where an incorrect role causes the Node to try to download a non-existing ignition file and fail the installation without a clear error returned to the end user.
With this change, as soon as an attempt to set an invalid role is detected, an API error will be returned preventing the change to be applied (in the REST API flow) or causing Agent CR to return a SpecSync error (in the Kube API flow).
Closes: [MGMTBUGSM-473](https://issues.redhat.com//browse/MGMTBUGSM-473)
/cc @omertuc

Bug 2107715: Add validation for Agent's role

---

docs/user-guide/rest-api-getting-started.md

Signed-off-by: Mark D <xphyr@users.noreply.github.com>
Fixed a small documentation error in the "Patch InfraEnv" section where the curl example was using a "POST" instead of a "PATCH".  Should make the docs more usable.

fixing small documentation error in Patch InfraEnv section

---

deploy/operator/setup_assisted_operator.sh
go.mod
go.sum
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_storage_validation_test.go
internal/controller/controllers/controllers_suite_test.go
internal/testing/fake_cluster.go
vendor/github.com/bombsimon/logrusr/v3/.gitignore
vendor/github.com/bombsimon/logrusr/v3/LICENSE
vendor/github.com/bombsimon/logrusr/v3/README.md
vendor/github.com/bombsimon/logrusr/v3/logrusr.go
vendor/github.com/go-logr/logr/README.md
vendor/github.com/go-logr/logr/logr.go
vendor/modules.txt

Currently when the user creates an instance of the _AgentConfigService_
object the sizes of the volumes aren't validated. This patch changes the
controller so that it validates these sizes.
To avoid potential issues with environments that were created before
this change the validation will not generate an error and stop
reconciliation if the corresponding persistent volume claims and
stateful set have already been created.
Related: https://issues.redhat.com/browse/MGMT-11700
Tested manually deploying the operator and trying to create _AgentServiceConfig_ objects with incorrect sizes. …

MGMT-11700: Validate storage requirements

---

deploy/operator/mirror_utils.sh

Use the digest of the remote image to name the mirrored image locally.
e.g.: `quay.io/me/index@sha256:a02f...` will become
`mylocalregistry/olm-index/index:a02f...` locally.
x-ref: https://github.com/openshift/release/pull/32685

MGMT-12167: Make possible to mirror an index referenced by digest

---

internal/ignition/ignition.go
internal/ignition/ignition_test.go

We should not set bootstrap kubelet ip in case of user managed network (not sno) as user can't set machine cidr and we can actually set wrong one and fail the installation

Bug 2135714: Don't set bootstrap kubelet ip in case of UMN

---

subsystem/cluster_test.go

Since OCP version 4.12, the default network type is OVN, but OVN can not run with VIP allocation mode. Since the tests run in different versions, ensure that this test creates a proper cluster for all OCP versions.

NO-ISSUE: flaky test due to network type mismatch

---

docs/events.yaml
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/common/events/events.go

Backport of PR
https://github.com/openshift/assisted-service/pull/4490
* [MGMT-11642](https://issues.redhat.com//browse/MGMT-11642): Add Host Bind/Unbind Event
Added a new host bind/unbind event since host
registration refers to a host registering to an
infra env whereas binding is related to a cluster.
* [MGMT-11642](https://issues.redhat.com//browse/MGMT-11642): Call Host Bind/Unbind Events
Call host bind/unbind events where appropriate.
* [MGMT-11642](https://issues.redhat.com//browse/MGMT-11642): Fix unit test by expecting the correct events
https://issues.redhat.com/browse/MGMT-11642
Previously, these unit tests still passed even though the expected mock events were either missing, incorrect, or not called.
Once ginkgo is upgraded, these tests will fail because ginkgo will actually …

MGMT-11642: Add Host Bind/Unbind Events (#4490)

---

cmd/main.go
internal/host/config.go
internal/host/config_test.go
internal/host/host.go
internal/host/host_test.go
internal/host/transition.go
internal/host/transition_test.go

Currently the host stage timeouts are hardcoded and can't be configured. This patch makes them configurable via environment variables. The names of these environment variables will be calculated from the name of the stage. For example:
- _Starting installation_ - `HOST_STAGE_STARTING_INSTALLATION_TIMEOUT`
- _Waiting for control plane_ - `HOST_STAGE_WAITING_FOR_CONTROL_PLANE_TIMEOUT`
The values of these environment variables will be strings acceptable by the `time.ParseDuration` function, for example `42s` or `51m`.
Related: https://issues.redhat.com/browse/MGMT-11075 …

MGMT-1107: Make host stage timeouts configurable

---

internal/installcfg/builder/builder.go
internal/installcfg/builder/builder_test.go

Users can influence the install-config `AdditionalTrustBundle` through `InstallConfigOverrides`.
This generally works. Except for in the situation described below.
`getCAContents` is a function that in some circumstances returns
internal CA certificates that need to be set in the install-config
`AdditionalTrustBundle`.
In most cases, `getCAContents` returns an empty string and everything
works fine.
But when `getCAContents` actually returns certificates, then we
completely overwrite the install-config `AdditionalTrustBundle`,
even when the user modified it through `InstallConfigOverrides`.
This is bad.
The situations in which `getCAContents` is non-empty is when the
Assisted Service admin deploys it with either:
- Red Hat Root CA (`INSTALL_RH_CA` env)
- This is the case in our staging …

MGMT-12261: Respect `InstallConfigOverrides` when `getCAContents` is non-empty

---

docs/user-guide/multiarch-and-heterogeneous-openshift.md

This PR completes the multiarch implementation by adding a documentation explaining base concepts as well as outlining the usage. It briefly explains the differences between multiarch and heterogeneous clusters. It also explains how to create a cluster that uses multiarch release image and allows adding worker nodes of another architecture.
/cc @javipolo

MGMT-8890: Create intro doc into multiarch

---

internal/installcfg/installcfg.go

In order to support composible openshift, we need to add capabilities fields to install-config, given that we're not importing from https://github.com/openshift/installer/blob/f7e1ded6aad8c0f32a6bff4f365d4eb775cd2391/pkg/types/installconfig.go#L89-L193
The capabilities feature gets documented by https://github.com/openshift/assisted-service/pull/4213
/cc @omertuc
Tried to update install-config via API customizing capabilities …

MGMT-12317: Add capabilities entries to install-config

---

deploy/operator/ztp/deploy_spoke_cluster.sh

This commit fixes the logic of API IP detection and libvirt DNS entries that are created in a scenario when spoke is a multi-node without UMN.
Currently for such a scenario the DNS entry for Spoke's API uses the default value of 192.168.111.1 which is incorrect. Because of that, the kubeconfig for such a Spoke cluster is unusable.
With this change, if there is no dedicated loadbalancer deployed, the API IP will be detected based on the `.status.apiVIP` of the AgentClusterInstall. This will help us to get the day2 CI back on track.
Closes: [MGMT-12314](https://issues.redhat.com//browse/MGMT-12314)
/test edge-e2e-ai-operator-ztp-compact-day2-workers
/cc @vrutkovs

MGMT-12314: Fix API IP detection for day2 ZTP CI

---

internal/bminventory/inventory_v2_handlers.go
pkg/s3wrapper/client.go
pkg/s3wrapper/client_test.go

Using curl to upload a file without providing an `upfile` parameter leads to a nil pointer exception. This fix adds a check for nil before:
1. The attempt to upload the file via `s3client`.
2. The cleanup done with `params.Upfile.Close()`

MGMT-12300: Fix nil pointer exception with v2uploadLogs

---

internal/cluster/cluster_test.go

While the failure is difficult to reproduce it feels likely that we could run through the test so quickly that the golang time and database time could be different enough (or similar enough) to cause this test to fail.

NO-ISSUE: Add some time to the cluster delete test to avoid flakes

---

Dockerfile.assisted-service-debug
hack/setup_env.sh
skipper.yaml

Since they have the tendency to change existing runtime dependencies, this changes all occurrences of 'go get' to 'go install' for wherever we want to just install a testing-related dependency.
If someone has an env with ``docker`` installed, I'd like to see if ``skipper make update-minimal-debug`` works for him/her!
Basically I want to make sure we use a default podman sock address if ``podman`` command doesn't exist. The resulting "default" value isn't important, as either way it's unused when using ``docker``, just that it should not crash. …

MGMT-11799: change all 'go get' commands

---

deploy/operator/ztp/add-remote-nodes-playbook.yaml
deploy/operator/ztp/add_day2_remote_nodes.sh
deploy/operator/ztp/baremetalHost.j2

This commit adds an ability to add BMHs for day2 nodes with the explicit role annotation. With this, we are able to easily control from the CI whether nodes will be installed with master or autoassing (i.e. worker) role.
Contributes-to: [MGMT-8578](https://issues.redhat.com//browse/MGMT-8578)
Contributes-to: [MGMT-12143](https://issues.redhat.com//browse/MGMT-12143)

MGMT-8578: Framework for day2 master CI ZTP jobs

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/hypershiftagentserviceconfig_controller.go

Currently in AgentServiceConfigReconciler -> init: asc.conditions are initialized with a copy of instance.Status.Conditions. Hence, when updating the instance status on reconcileComponent, the conditions are not updated (as instance.Status.Conditions are always empty).
To mitigate the issue, changed conditions property in ASC struct to a pointer. I.e. asc.conditions should keep a pointer to instance.Status.Conditions, so updating asc.conditions would affect the instance. …

MGMT-12318: fix conditions update on ASC

---

deploy/operator/setup_lso.sh

The annotation on project is currently failing with:
```
$ oc annotate project openshift-local-storage openshift.io/node-selector="" --overwrite=true
The Project "openshift-local-storage" is invalid:
* metadata.namespace: Invalid value: "openshift-local-storage": field is immutable
* metadata.namespace: Forbidden: not allowed on this type
```
while the annotation on the namespace seems to work:
```
$ oc annotate namespace openshift-local-storage openshift.io/node-selector="" --overwrite=true
namespace/openshift-local-storage annotated
```

NO-ISSUE: annotate lso namespace instead of project

---

cmd/main.go
docs/hive-integration/README.md
internal/controller/controllers/bmo_utils.go
internal/controller/controllers/bmo_utils_test.go
internal/controller/controllers/preprovisioningimage_controller_test.go

This sets the ALLOW_CONVERGED_FLOW env var to true by default
Additionally this only allows the converged flow to be used
on hub clusters at version 4.12.0-ec.4 or later to ensure that
https://issues.redhat.com/browse/METAL-256 is resolved.
Resolves https://issues.redhat.com/browse/MGMT-11997

MGMT-11997: Default to using converged flow for 4.12 hub versions

---

api/v1beta1/agentserviceconfig_types.go
config/rbac/role.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
internal/controller/controllers/hypershiftagentserviceconfig_controller.go
internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go

This PR handles the following:
* Create namespace on spoke cluster to ensure it exists (the namespace of HASC resource).
* Create assisted-service service-account on both hub and spoke clusters.
* Restore client on AgentServiceConfigReconcileContext upon finishing reconcile (as there's a single context).
Note: to avoid switching the client property between hub and spoke, client should be extracted from AgentServiceConfigReconcileContext. That way, we could avoid sharing it and just pass it as needed.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#co …

MGMT-11750: ensure namespace exists on spoke cluster (HASC)

---

internal/cluster/transition_test.go
internal/cluster/validator.go

[MGMT-12380](https://issues.redhat.com//browse/MGMT-12380): Improve message of vip validation failure
Currently our message says
"VIP does not belong to the Machine CIDR or is already in use" and customers don't understand what is going on as they think that it only should match cidr . Fixing it to return different error per each case

MGMT-12380: Improve message of vip validation failure

---

openshift/template.yaml

This PR is introducing `initialDealySeconds` parameter for readiness probe.
Startup usually takes around 10s, which normally produces 2 messages of readiness probe failed.
This is not an issue, but it makes people think there might be a problem with readiness as the message looks like this:
`Warning  Unhealthy       18m (x3 over 18m)  kubelet            Readiness probe failed: Get "http://10.129.24.18:8090/ready": dial tcp 10.129.24.18:8090: connect: connection refused`
These errors ocurred at the start of the pod, but it looks like it failed 3 times in the last 18m - which is technically correct but it all happened in the first 20s.
This PR aims at reducing this kind of messages. The downside of this is that we will always wait 15s from startup before the pod being ready in the best case …

NO-ISSUE: add initialDelaySeconds for readiness probe

---

restapi/embedded_spec.go
swagger.yaml

This is required for the image service to query an infra env to get any kernel arg overrides for the discovery image.
https://issues.redhat.com/browse/MGMT-12402

MGMT-12402: Add url auth for getting a single infra-env

---

internal/bminventory/inventory.go
internal/usage/consts.go
subsystem/cluster_test.go

https://issues.redhat.com/browse/MGMT-9023
The hyperthreading feature usage will appear like
this:
````
"Hyperthreading": {
"data": {
"hyperthreading_enabled": "all"
},
"id": "HYPERTHREADING",
"name": "Hyperthreading"
},
````
Test steps:
1. Deploy assisted-service with these changes and created a cluster
2. Get the cluster's feature usage to see the default setting was applied
````
$ curl ${ASSISTED_SERVICE_URL}/api/assisted-install/v2/clusters/${CLUSTER_ID} | jq -r '.feature_usage' | jq '.Hyperthreading'
"Hyperthreading": {
"data": {
"enabled": "all"
},
"id": "HYPERTHREADING",
"name": "Hyperthreading"
}
````
3. Patch the cluster to not use hyperthreading
````
$ curl ${ASSISTED_SERVICE_URL}/api/assisted-install/v2/clusters/${CLUSTER_ID} -X PATCH -H "Content-Type: application/json" -d …
```

MGMT-9023: Add hyperthreading feature usage

---

internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go

If the architectures don't match the controller now sets an error condition. The user can change the infraenv arch to resolve the issue.
Resolves https://issues.redhat.com/browse/MGMT-10819
Set the arch incorrectly on an infraenv linked to a preprovisioning image and observe the conditions.

MGMT-10819: Ensure the preprovisioningimage arch matches the infraenv

---

api/v1beta1/agentserviceconfig_types.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/hypershiftagentserviceconfig_controller.go
internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go

Added conditions handling to HypershiftAgentServiceConfig:
* Extracted conditions in ASC to updateConditions func.
* Extracted StatefulSet condition update to ensureImageServiceStatefulSet func.
* Reused conditions funcs in HASC.
* Added condition update for ReasonSpokeClusterCRDsSyncFailure.

MGMT-12318: handle conditions in HASC

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/provider/common.go

We missed the case where the cluster has platform different than baremetal/none and the user set the platform to baremetal.
Furthermore, UMN current value should be taken into account when updating the platform, for example if cluster platform is vsphere and UMN is enabled the user should not set the platform to BM (because `platform=baremetal and UMN=true` is not a valid state).
This PR handles those invalid cases and return the correct update value if it wasn't met to any condition
/cc @eranco74 
/cc @gamli75

MGMT-12422: Fix bm platform update failure when cluster platform different than bm/none

---

internal/cluster/cluster.go
internal/network/machine_network_cidr.go
internal/network/machine_network_cidr_test.go

This PR renames the function `GetClusterNetworks` to `GetInventoryNetworks` in order to remove confusion about what Cluster Network is.
The logic of the function goes over the inventory of all discovered hosts and returns all the CIDRs that have been found.
On the other hand, Cluster Network in the OpenShift universe is a network that is used for Pods to talk with each other and is not related at all to the physical network where Nodes belong to.
In order to remove a confusion (because we already have `GetClusterNetworkCidrs` which does something completely different than `GetClusterNetworks`) we are renaming it and use Inventory Networks.
/cc @nmagnezi

NO-ISSUE: Rename misleading network utility function

---

dev-requirements.txt

This dependency doesn't seem used in the repo, maybe not even when it first got defined at:
https://github.com/openshift/assisted-service/commit/a7836211dcfc0e3cb473686e80b8e04575cc4235

Remove redundant boto3 dependency

---

internal/host/host.go

A recent regression caused the host stage to be prematurely moved to "Done" when the installation is in KubeAPI mode. This change aims to fix that by setting the correct status.
- [] None
I used aicli to create a hub/spoke setup and proceeded to use KubeAPI to add a Day2 node to a spoke. 
Prior to this fix, the CSR's of the node would not be signed. 
After this fix, the CSRs are signed correctly and the node joined the cluster successfully. …

MGMT-12398: Regression fix: Move host stage to "Done" only when not in KubeAPI mode.

---

internal/controller/controllers/clusterdeployments_controller.go

In order to make it easier to debug race conditions in the KubeAPI, this PR adds additional debug logs that will be returning results of the intermediate steps that lead to marking cluster as `UnsyncedAgents` or `UnapprovedAgents`.
Contributes-to: [MGMT-12423](https://issues.redhat.com//browse/MGMT-12423)
/cc @omertuc

MGMT-12423: Add debug logs for counting unsynced agents

---

internal/common/db.go
internal/migrations/20221031103047_multiple_vips.go
internal/migrations/20221031103047_multiple_vips_test.go
internal/migrations/migrations.go

With the new way of storing the data, we need to pre-populate database so that the new tables `api_vips` and `ingress_vips` get the data for all the existing clusters filled.
This PR is resposible for going over all the existing clusters and populating the newly created DB tables with already known IP addresses.
Closes: [MGMT-12354](https://issues.redhat.com//browse/MGMT-12354)
/cc @nmagnezi

MGMT-12354: Migrate single VIP values to the new data structure

---

internal/controller/controllers/bmo_utils.go
internal/controller/controllers/bmo_utils_test.go

The previous minimum version ensured that all the bugs associated with the converged flow were fixed, but excluded nightly releases.
It is better to include nightly releases for ease of testing. If versions earlier than ec.4 are used and have issues it should be easy enough to recognize the problem as it would only happen internally.
Resolves https://issues.redhat.com/browse/MGMT-12434
Unit tests should be enough here
cc @eranco74 
cc @trewest

MGMT-12434: Allow nightly 4.12 builds to use the converged flow

---

internal/controller/controllers/clusterdeployments_controller.go

Remove useless getReleaseImage function

---

internal/common/common_unitest_db.go
internal/host/hostutil/host_utils_test.go

When running unit tests directly from a directory without skipper sometimes tests will fail if the test start before DB container is ready To avoid that db initialization should try to connect to the DB before starting the test.
In addition fixing hostutil tests to initialize DB in the test preperation

MGMT-12522 Fix unit test DB connection failure

---

internal/network/utils.go
internal/network/utils_test.go

This PR creates a set of utility functions that are returning cluster's VIPs as a simple `[]string` or `string` instead of a custom data structures. This is to make it easier to perform parsing and validations when only the value of the VIP is required and not the whole context it carries.
/cc @nmagnezi

MGMT-9915: Create utility functions to get cluster's VIPs

---

internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go

It seems that the ignition endpoint override triggers a call to v2UpdateClusterInternal regardless if an update is required.
The v2UpdateClusterInternal call failes because the cluster is already installing, this result in early termination of the reconcile function.
- Should this PR be tested in a specific environment? kube-api
- Any logs, screenshots, etc that can help with the review process? check the clusterdeployment controller logs and see that you no longer get the update failure errors
https://issues.redhat.com/browse/MGMT-12478
- Should …

MGMT-12478: AgentClusterInstall remains in installed state when using ignitionEndpoint

---

internal/host/common.go

The old message implied that the host failed to boot from the installation disk, but in practice this timeout is mainly a result of misconfigured network, preventing the host from pulling ignition, the new message reflects that.
https://issues.redhat.com/browse/AITRIAGE-4441
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commi …

MGMT-12492: update statusRebootTimeout info message to ask the user to look at the host console.

---

internal/host/common.go
internal/host/common_test.go
internal/host/validator.go

[MGMT-12489](https://issues.redhat.com//browse/MGMT-12489): We should validate that inventory is not nil while returning from GetOrUnmarshal in installer cache.
Without validation monitor can crash due to null pointer exception in further functions where we provide inventory

MGMT-12489: We should validate that inventory is not nil while returning from GetOrUnmarshal in installer cache.

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/host/host.go
internal/host/host_test.go

The following applies to kube-API only:
The host UpdateInstallProgress will not update day-2 hosts to HostStatusAddedToExistingCluster if the host stage is Rebooting. The host UpdateInstallProgress will update day-2 hosts to HostStatusAddedToExistingCluster if the host stage is Done The agent controller will keep updateing day-2 agents if the agent stage is Rebooting, Configuring or Joined.
- Should this PR be tested in a specific environment? kube-api
-->
https://issues.redhat.com/browse/MGMT-12552
- Is there a bug required (and linked) for this …

MGMT-12552: Day-2 agent stuck with status_info rebooting although the node is already part of the cluster

---

cmd/main.go
docs/hive-integration/README.md

Having this on by default without also having a good way to detect what ironic agent image should be used for every use case would not be a good experience. Leaving it opt-in for now allows users who need it for BIOS configuration to use it while also not disrupting disconnected users who would need to all of a sudden mirror additional images.
When 4.13 releases and includes multi-arch images in every case, we should be able to detect a suitable ironic agent image from the hub release image and instruct disconnected users to mirror that.
https://issues.redhat.com/browse/MGMT-11997
cc @eranco74 @filanov @trewest

Disable converged flow by default

---

skipper.yaml
tools/deploy_assisted_installer_configmap.py
tools/deploy_image_service.py
tools/deploy_inventory_service.py
tools/deploy_ui.py
tools/deployment_options.py
tools/utils.py

This change is about:
* Enable running e2e tests via assisted-test-infra when hub-cluster is a
kind cluster.
* There's another side of this automation in assisted-test-infra
repository, which depends on this change.
* A bit of cleaning-up, as some stuff on those automation scripts are
pretty yucky. For example: removing confusing k3d binary mount,
refactor code to have a less-nested indentation, etc.
* Kind is able to mirror ports from the kubernetes node to the external
host. We have chosen to mirror 80->80 (I can accept other suggestions
if anyone rejects that). In addition, we have an ingress-controller,
meaning we just use <host>:80 to access
assisted-service/assisted-image-service. This should explain most of
the changes here. I preferred usage of ingress instead of
load-balancer …

MGMT-8357: Support kind hub-cluster for e2e tests

---

internal/provider/nutanix/ignition.go

Worker machineset needs to be removed so that MachineAPI operator would not go degraded due to placeholder credentials on install

MGMT-11266: nutanix: remove worker MachineSet too

---

api/v1beta1/agentserviceconfig_types.go
internal/controller/controllers/hypershiftagentserviceconfig_controller.go
internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go

Added conditions for the following scenarios:
* Failure to fetch secret by KubeconfigSecretRef.
* Failure to create a spoke client using the secret.

MGMT-12318: added conditions for spoke kubeconfig secret

---

deploy/operator/libvirt_disks.sh

The target disk given to `virsh attach-disk` is a hint for the guest OS. Sometimes, the target disk collides a disk already mounted in the guest OS (e.g.: a target `sdb` will be seen as `/dev/sda` in the guest OS) and `virsh attach-disk` fails with `error: Requested operation is not valid: Domain already contains a disk with that address`. This issue is one cause of flakiness for ZTP jobs.
This change tries to attach the first target available for a given disk name. The target as no impact on the reachability of the disk on the guest OS because later we use the wwn which is derived from the disk name.
Example of flaky job: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-installer/580/pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp/1 …

MGMT-12588: fix attach-disk failure

---

internal/ignition/ignition_test.go

Currently some of the mock controllers in the ignition tests aren't finished. As a result some of the expectations aren't verified, and some of the tests are incorrect. With the introduction of Ginkgo 2 the controllers will be automatically finished, and that will make these tests fail. In order to reduce the size of that migration to Gingo 2 this patch fixes those tests and changes them to explicitly finish the mock controllers. …

NO-ISSUE: Explicitly finish mock controller in ignition tests

---

api/vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
api/vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
models/infra_env_create_params.go
models/infra_env_update_params.go
restapi/embedded_spec.go
subsystem/infra_env_test.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go

REST API only
This commit also adds "x-omitempty: false" in the swagger for kernel
arguments.  This causes the kernel arguments to always be part of the
infra-env register and update payloads.  This was needed to enable clear
operation on kernel arguments.
When clearing kernel arguments, empty slice is sent to indicate the request to clear them.
This is opposed to null value when the kernel arguments should not be manipulated.
When omitempty is present, empty slice and null slice are ignored and
not sent in the payload.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide …

MGMT-12332: Subsystem tests for discovery kernel arguments

---

Dockerfile.assisted-service-debug
Dockerfile.bundle
hack/setup_env.sh

Manual backport of https://github.com/openshift/assisted-service/pull/4619

MGMT-11799: Change 'go get' commands

---

internal/controller/controllers/hypershiftagentserviceconfig_controller.go
internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go

Condition message for missing kubeconfig secret should contain concise informat of the error. Thus, logging the internal error and expose a clear message.

MGMT-12318: improve condition message of missing secret

---

internal/host/hosts_suite_test.go
internal/host/transition_test.go

Currently some of the mock controllers in the host transition tests aren't finished. As a result some of the expectations aren't verified, and some of the tests are incorrect. With the introduction of Ginkgo 2 the controllers will be automatically finished, and that will make these tests fail. In order to reduce the size of that migration to Gingo 2 this patch fixes those tests and changes them to explicitly finish the mock controllers.
[Kubernetes …

NO-ISSUE: Explicitly finish mock controller in host transition tests

---

internal/host/hostcommands/download_boot_artifacts_cmd_test.go
internal/host/hostcommands/install_cmd_test.go

Currently some of the mock controllers in the host command tests aren't finished. As a result some of the expectations aren't verified, and some of the tests are incorrect. With the introduction of Ginkgo 2 the controllers will be automatically finished, and that will make these tests fail. In order to reduce the size of that migration to Gingo 2 this patch fixes those tests and changes them to explicitly finish the mock controllers. …

NO-ISSUE: Explicitly finish mock controller in host command tests

---

Makefile
tools/deployment_options.py

Since we're gonna (temporarily) have two deployment methods that have different network configuration, we should rename 'local' to 'minikube'. Then assisted-test-infra can pass its value of ``DEPLOY_TARGET`` to what assisted-service calls ``TARGET`` (seems ``DEPLOY_TARGET`` in assisted-service is already used in some other constellation).

MGMT-8357: change 'local' deployment method to 'minikube'

---

deploy/operator/gather.sh
deploy/operator/hypershift/deploy_hypershift_cluster.sh

Added webhooks test to deploy_hypershift_cluster script:
* positive: successful validation on update of InfraEnv CR
* negative: failed validation on invalid update of InfraEnv CR

MGMT-12592: added webhooks tests to hypershift e2e

---

internal/host/transition_test.go
internal/host/validator.go

The current message for host packet loss is not helpful to end users and does little to help them get to the root of their issues.
This update attempts to remedy that by providing more concise information on how to troubleshoot the issue.
This code has unit test coverage.
/cc @nmagnezi 
/cc @omertuc 

MGMT-11506: Present a more useful validation message for packet loss

---

cmd/main.go
internal/ignition/ignition.go
internal/ignition/ignition_test.go
internal/oc/mock_release.go
internal/oc/release.go

If payload has `okd-rpms` image Assisted Service should automatically apply OKD Ignition overrides. This would enable us to add OKD payload to AI without additional configuration option

OKD-90: Support automated extraction of OKD RPMs

---

Dockerfile.assisted-service
Dockerfile.assisted-service.ocp
Makefile
cmd/main.go
internal/versions/versions.go

Go 1.18 adds some commit information to the binary automatically when running go build.
* This requires building the package without file patterns This PR adds the git commit to the output logs.
- Any logs, screenshots, etc that can help with the review process? check the service logs
--> …

NO-ISSUE: log build version

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go

Return bad-request on single-node cluster when setting the platform type to different from none.
/cc @gamli75 
/cc @eranco74

MGMT-12379: PlatformType is not validated when installing SNO cluster

---

deploy/operator/hypershift/deploy_hypershift_cluster.sh
deploy/operator/hypershift/playbooks/hasc-playbook.yaml
deploy/operator/hypershift/playbooks/templates/hasc.j2

The 'e2e-ai-operator-ztp-hypershift-zero-nodes' CI [job](https://github.com/openshift/release/blob/4721a60662841beeaf592d9e5a377a04d88d5e76/ci-operator/step-registry/assisted/baremetal/operator/hypershift/assisted-baremetal-operator-hypershift-commands.sh#L5-L6) depends on 'assisted-common-setup-prepare' which sets the [PUBLIC_CONTAINER_REGISTRIES](https://github.com/openshift/release/blob/323c572130449387ba5d338ed81e03d57b7e8039/ci-operator/step-registry/assisted/common/setup/prepare/assisted-common-setup-prepare-commands.sh#L91) var. E.g. it includes the ci registry as 'registry.build04.ci.openshift.org'.
On deploy_hypershift_cluster.sh [script](https://github.com/openshift/assisted-service/blob/0493e129a277f8ede5249006140c8aaea1ae1b14/deploy/operator/hypershift/deploy_hypershift_cluster …

NO-ISSUE: add unauthenticatedRegistries to HASC on deploy

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/constants/files.go
internal/host/hostutil/host_utils.go
internal/ignition/ignition.go

When possible, fetch MCS certificate from spoke cluster and use it to provision day2 workers via HTTPS Ignition endpoint.
TODO:
* * hub cannot contact spoke cluster and won't add MCS cert to ignition override
* * user has set Ignition override with CA manually
In that case day2 worker would attempt to use HTTPS and fail as Ignition server cannot be contacted using user-provided CA.
Do we consider this usecase likely to happen and serious enough to fix?
Discussed with mko and omer - hub->spoke connection is a requirement on day2, so we can rely on having MCS cert in ignition override. Users are rarely setting host-specific overrides for CA (this would be replaced by a new API later), so it looks like a low-risk assumption to me

MGMT-8818: clusterdeployments: set HTTPS Ignition URL when finalizing the cluster

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go
internal/network/machine_network_cidr.go
internal/network/utils.go
subsystem/cluster_test.go

This PR adds support for plural API and Ingress VIPs, both to
`V2RegisterCluster` and `V2UpdateCluster`.
Note that API backward compatibility is currently kept, and thus singular API VIP
and Ingress VIP were not removed.
However, please look at https://github.com/openshift/assisted-service/pull/4245 to understand the expected behavior when old and new API parameters.
As this PR is big enough on its own, a follow-up PR will handle the
plural versions of `isApiVipValid` and `isIngressVipValid` state-machine validations.
Contributes-to: [MGMT-12355](https://issues.redhat.com//browse/MGMT-12355)
Implements: https://github.com/openshift/assisted-service/pull/4245
- Is there a bug required (and linked) for this …

MGMT-12355: API and Ingress VIPs CRUD implementation

---

internal/bminventory/inventory.go
internal/usage/consts.go
subsystem/cluster_test.go

This commit adds a feature flag for marking clusters that use dual-stack VIPs. This enables us to collect statistics about usage of this feature. The flag is independent from the usage of dual-stack networking, as it is still possible to have a dual-stack cluster that uses only a single pair of VIPs. For this reason it's desired to track separately `DualStackUsage` and `DualStackVipsUsage`.
Contributes-to: [MGMT-12389](https://issues.redhat.com//browse/MGMT-12389)
/cc @nmagnezi

MGMT-12389: Add feature usage for dual-stack VIPs

---

cmd/agentbasedinstaller/register.go
cmd/main.go
internal/installercache/installercache.go
internal/oc/release.go
internal/oc/release_test.go

https://github.com/openshift/assisted-service/pull/4141 added support for the --icsp-file parameter to the "oc adm release extract" using the contents of imageContentSources in install-config.yaml. The other oc commands didn't use the --icsp-file option as they used the mirror defined in the env variable OPENSHIFT_RELEASE_IMAGE_MIRROR.
Relying on this mirror setting can be problematic if this env variable cannot be set, or if the oc method of deriving the mirror using the --icsp-file is different than the env variable value. This change adds support for the --icsp-file param to the remaining oc commands. The ICSP contents are read from /etc/containers/registries.conf as the install-config.yaml containing the imageContentSources may not be available.
- Are the title and description (in …

MGMT-12635: Add icsp-file support for all oc commands

---

internal/bminventory/inventory.go
internal/host/mock_transition.go
internal/host/statemachine.go
internal/host/transition.go
internal/host/transition_test.go

This patch changes the service so that it returns a 403 error response when an agent tries to register when the cluster is already installed, as otherwise the agent will keep trying to register and spam both the log and the events.
Related: https://issues.redhat.com/browse/MGMT-12616
Related: https://issues.redhat.com/browse/MGMT-2359
Related: https://issues.redhat.com/browse/MGMT-1041
Tested manuall installing a cluster and then rebooting one of the nodes with the installation ISO.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guide …

MGMT-12616: Reject register after install

---

docs/operator.md

https://issues.redhat.com/browse/MGMT-12666
Epic: https://issues.redhat.com/browse/MGMT-8789
Update documentation related to adding
`unauthenticatedRegistries` to the spec of the
`AgentServiceConfig` so users know how to specify
image registries that don't require authentication.
/cc @carbonin

MGMT-12666: Document Unauthenticated Registries

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/mock_installer_internal.go
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/controller/controllers/crd_utils.go
internal/controller/controllers/crd_utils_test.go
internal/controller/controllers/infraenv_controller.go
internal/controller/controllers/infraenv_controller_test.go
internal/host/host.go
internal/host/mock_host_api.go
subsystem/cluster_test.go
subsystem/cluster_v2_test.go

When a user deletes a host, the cluster validations do not run immediately. Therefore the UI presents an incorrect view of the validation status. For example, master count validation shows erroneous status.
That may lead to a user starting an installation when the cluster is actually not ready to be installed.
This PR adds a refresh cluster after host deletion so the validation will run before the result is returned to the UI. …

MGMT-11536: refresh cluster after host deletion

---

internal/controller/controllers/clusterdeployments_controller.go

We are adding additional debug logging to dump the status of all the Agents that belong to a queried AgentClusterInstall. We will dump each Agent's ignition override as well as its conditions. Based on this, we can say if the UnsyncedAgents counter is working properly or not.
Contributes-to: [MGMT-12423](https://issues.redhat.com//browse/MGMT-12423)
/cc @omertuc

MGMT-12423: Additional debug logs when collecting Agents from ACI

---

internal/host/statemachine.go
internal/host/transition_test.go

Currently when a host is in the _pending for input_ state it can't register again. This produces the following situation when the host is rebooted or when the agent restarts to upgrade the agent:
- The host tries to register, fails and retries. This generates error events indicating that the host can't register.
- Eventually, after several tries, the host will be moved to the _disconnected_ state.
- The host will try again to register and now it will succeed because we do allow the registration from the _disconnected_ state.
This patch changes the state machine so that the host will be allowed to register from the _pending for input_ state.
https://issues.redhat.com/browse/MGMT-12806
- Is there a bug required …

MGMT-12806: Allow registration when pending for input

---

cmd/main.go

It looks like the intention was to activate pprof http server if debug mode, but the condition was never matching.

MGMT-12400: enable pprof when debug mode for memory profiling

---

internal/controller/controllers/clusterdeployments_controller.go

This PR changes the data structure used internally when collecting
Agents belonging to the specified AgentClusterInstall. This is in order
to avoid a potential scenario when we collect by-value and the
underlying Agent gets modified between its collection and parsing the
interesting data.
Contributes-to: [MGMT-12423](https://issues.redhat.com//browse/MGMT-12423)

MGMT-12423: Use pointers when collecting Agents from ACI

---

cmd/agentbasedinstaller/register.go
cmd/main.go
internal/installercache/installercache.go
internal/oc/release.go
internal/oc/release_test.go

https://github.com/openshift/assisted-service/pull/4141 added support for the --icsp-file parameter to the "oc adm release extract" using the contents of imageContentSources in install-config.yaml. The other oc commands didn't use the --icsp-file option as they used the mirror defined in the env variable OPENSHIFT_RELEASE_IMAGE_MIRROR.
Relying on this mirror setting can be problematic if this env variable cannot be set, or if the oc method of deriving the mirror using the --icsp-file is different than the env variable value. This change adds support for the --icsp-file param to the remaining oc commands. The ICSP contents are read from /etc/containers/registries.conf as the install-config.yaml containing the imageContentSources may not be available.
(cherry picked from commit …

MGMT-12635: Add icsp-file support for all oc commands (#4684)

---

internal/common/common_test.go

There are locations that our code assumes that embedded structure is always not nil.  This change adds tests to verify it.
For more information: https://github.com/go-gorm/gorm/issues/5431
/cc @filanov

NO-ISSUE:  Verify that GORM embedded structure is always part of containing structure

---

cmd/main.go
internal/versions/api.go
internal/versions/api_test.go
internal/versions/mock_versions.go
internal/versions/versions.go
internal/versions/versions_test.go

Tracking versions generally and specifically responding to API requests are very different things. There's no reason for these methods to be on the same struct.
Compose the objects instead of reusing one.
Part of the ongoing versions handler refactor.
The entire thing can be found [here](https://github.com/openshift/assisted-service/pull/4645)

Move version API handlers to a separate struct

---

internal/cluster/cluster_suite_test.go
internal/cluster/transition_test.go

Currently some of the mock controllers in the cluster transition tests aren't finished. As a result some of the expectations aren't verified, and some of the tests are incorrect. With the introduction of Ginkgo 2 the controllers will be automatically finished, and that will make these tests fail. In order to reduce the size of that migration to Gingo 2 this patch fixes those tests and changes them to explicitly finish the mock controllers.
[Kubernetes …

NO-ISSUE: Explicitly finish mock controllers in cluster transition tests

---

cmd/main.go
internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go
internal/ignition/ironic.go
internal/ignition/ironic_test.go

Previously the preprovisioning image controller was using the infra-env
`OpenshiftVersion` field to attempt to find a release image, but this
field is an rhcos version (i.e. a key in `OS_IMAGES`), not a release
image version.
This caused issues when the OS version keys didn't match the release
image keys which can happen when specifying a particular z-stream or
during pre-releases.
This commit only attempts to extract the ironic agent image from the
release image if the infra-env has a cluster reference
(non-late-binding) and if that release image is above the minimum
required for the converged flow.\
This PR also moves all the logic about what image should be used into the
preprovisioning image controller. This makes the logic a bit easier to reason about
rather than sometimes passing an …

Use the cluster version when extracting the ironic agent image from a release

---

internal/cluster/cluster_test.go

This PR fixes a wrong unit test in the machine network autoallocation. In the current form the test does not compare the cluster value with expected value, but only expected value with itself. This is not a correct behaviour as in order to test the functionality we need to assert cluster's state with a desired state, and not a desired state with itself.
/cc @ori-amizur

NO-ISSUE: Fix wrong unit test for CIDR autoallocation

---

pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook_test.go

Upon upgrade from older versions mutating webhook kicks in and try to mutate existing CRs that are in post-install status. Then the mutated ACO goes through the validation webhook that rejects it due to an attempt to change immutable fields post installation.
The result is failure to upgrade and to delete or update those existing CRs.
This PR prevents mutating post-install.

OCPBUGS-4493: do not mutate ACI post installation start

---

internal/oc/release.go

OKD flow checks for `okd-rpms` image in the payload. In OCP payload its not present, so
`execute` should throw a warning as its a happy path

OKD-90: execute should throw a warning

---

openshift/template.yaml

Policy hasn't been a beta API since 4.7
This was causing errors when deploying to integration like:
```
error: unable to recognize "STDIN": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
```
cc @osherdp

Use policy/v1 for pod disruption budget

---

internal/installcfg/builder/builder.go
internal/installcfg/builder/builder_test.go
internal/oc/release.go
internal/oc/release_test.go
pkg/mirrorregistries/generator.go
pkg/mirrorregistries/generator_test.go

/wip
extractLocationMirrorDataFromRegistries had a bug that just picked the first mirror for each sources.
as long the mirror registry was created using `oc adm release mirror` this wasn't an issue since each source had a single mirror.
For some time now customers use `oc-mirror` for creating the mirror registry, `oc-mirror` create few mirrors for a single source and thus triggers the bug in the title.
- Should this PR be tested in a specific environment? disconnected
- Any logs, screenshots, etc that can help with the review process? you can check the install-config.yaml ImageContentSource content
-->
https://issues.redhat.com/browse/MGMT-12863
- Are the title and description (in …

MGMT-12863: Assisted Spoke install-config does not generate icsp with multiple mirror to entries

---

internal/cluster/cluster.go
internal/cluster/common.go
internal/cluster/common_test.go

Contributes-to: [MGMT-12366](https://issues.redhat.com//browse/MGMT-12366)
/cc @nmagnezi

MGMT-12366: Allow to use UpdateMachineCidr for multiple networks

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/host/transition_test.go
internal/host/validator.go

Assisted-install failing with None platform when multiple IP interfaces configured
Allow setting machine cidr in with UserManagedNetwork set to true

OCPBUGS-1683: Allow setting machine cidr in with UserManagedNetwork set to true

---

docs/user-guide/install-customization.md

Document on OpenShift Capabilities customization to exclude components
/cc @
/cc @

TELCODOCS-831: Document capabilities exclusion

---

cmd/operator/main.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_storage_validation_test.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/hypershiftagentserviceconfig_controller.go
internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go

In HypershiftAgentServiceConfigReconciler, we currently need to switch between clients (hub and spoke), since a single client property exists in AgentServiceConfigReconcileContext.
Hence, to avoid sharing the property with both clients in order to have a clear notion of the client in use; moved it to ASC struct for explicitly specifying the required client.
I.e. instead of a single ASC with alternating clients, created a separate one for the spoke using the generated client.
Also, moved the 'properties' from ASC to AgentServiceConfigReconcileContext as the map is used for sharing values between clients. …

NO-ISSUE: extract client from reconcile context

---

cmd/main.go
openshift/template.yaml
pkg/ocm/client.go

After https://github.com/openshift/assisted-service/pull/4712 setting log level was racing between OCM logger and generic loger.
The idea is to instantiate two new instances of the logger so we can have independent settings.

NO-ISSUE: use two logger instance for generic and ocm logging

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

Tested manually creating a cluster with the console disabled and waiting for the installation to complete.
```shell
$ cat > disable-console.json <<.
{
"capabilities": {
"baselineCapabilitySet": "None",
"additionalEnabledCapabilities": [
"baremetal"
]
}
}
.
$ cat disable-console.json | jq -sR > disable-console.patch
$ ocm patch /api/assisted-install/v2/clusters/.../install-config --body disable-console.patch
``` …

MGMT-12471: Don't wait for console if it is disabled

---

docs/hive-integration/README.md

It not using late binding the ironic agent image is extracted from the spoke cluster release.
If using late binding the image ref is taken from the env vars which can be overridden.
Also add a note to ensure these are mirrored if required.
Resolves https://issues.redhat.com/browse/MGMT-10877

Document the ironic agent image behavior for converged flow

---

hack/setup_env.sh

I was surprised by the size of assisted-service-build image!
```
docker images assisted-service-build
REPOSITORY               TAG       IMAGE ID       CREATED        SIZE
assisted-service-build   latest    e028dbb254a4   24 hours ago   4.65GB 
```
Seems that half of it is added by this command:
```
docker image history e028dbb254a4 | grep GB
0e7f26998968   12 days ago    /bin/sh -c ./setup_env.sh assisted_service      1.8GB 
```
Which seems to install few packages (nothing that should cost ~2GB)
The changes in this PR reduce the image size to:
```
docker images assisted-service-build
REPOSITORY               TAG                                        IMAGE ID       CREATED       SIZE
assisted-service-build   latest                                     769b0b5c3487   4 hours ago   2.9GB …
```

NO-ISSUE: reduce build image size

---

internal/bminventory/inventory_test.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
internal/controller/controllers/common.go
subsystem/kubeapi_test.go

This PR implements a missing CRUD operations to handle dual-stack VIPs in case when KubeAPI is used.
Closes: [MGMT-12870](https://issues.redhat.com//browse/MGMT-12870)
/cc @nmagnezi

MGMT-12870: Add missing dual-stack VIP CRUD for KubeAPI

---

cmd/main.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/mock_installer_internal.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
internal/controller/controllers/common.go
internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go
internal/host/hostcommands/container_image_availability_cmd.go
internal/host/hostcommands/container_image_availability_cmd_test.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/hostcommands/instruction_manager_test.go
internal/ignition/ignition.go
internal/ignition/ignition_test.go
internal/versions/api_test.go
internal/versions/mock_versions.go
internal/versions/versions.go
internal/versions/versions_test.go

As it is today the versions handler does too much and doesn't function well as a cache when we need to add release images from `ClusterImageSets`.
This has caused a few issues such as https://issues.redhat.com/browse/MGMT-8279 and https://issues.redhat.com/browse/MGMT-11956. The solution to these has been to add the release image from more places, but that means the issue will continue to occur.
Additionally the way the cluster deployment controller added to the cache, but the main inventory code read from it was going to make it difficult to separate out the controllers from the API in the future.
This effort began by splitting unrelated functionality off of the existing `versions.Handler` interface.
Really it did several unrelated things that are split into new structs/interfaces:
1. …

Refactor the versions handler into a proper cache

---

internal/ignition/ignition.go

This PR modifies the regex expression that we use to extract the name of the image. The previous version worked only with images passed via tag, but did not support images passed by SHA. With this modification we now support both naming schemas.
/cc @omertuc

OCPBUGS-2953: Fix regex to filter images by tag and by sha

---

cmd/operator/main.go
internal/controller/controllers/hypershiftagentserviceconfig_controller.go
internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go

In HypershiftAgentServiceConfigReconciler, we fetch the agent-install CRDs by filtering using the label added by OLM ('operators.coreos.com/assisted-service-operator.[ns]').
However, MCE are [applying](https://github.com/stolostron/backplane-operator/blob/main/main.go#L148-L164) the [CRDs](https://github.com/stolostron/backplane-operator/tree/main/pkg/templates/crds/assisted-service) (scraped from [community-operators-prod](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/assisted-service-operator/0.4.50)) manually without using OLM.
Hence, no labels exist in the CRDs. So instead of relying on the label, search for relevent CRDs according to 'agent-install.openshift.io' group.
- Are the title and description (in both PR and commit) meaningful and …

MGMT-12886: fetch CRDs by group in HASC ctrl
