openshift/assisted-service

Dockerfile.demo, Makefile, build_deploy.sh
Now the current deployment will run `bm-inventory`'s code instead of a
busy box.
=> Updated the deployed app from demo to bm-inventory.

openshift/template.yaml
Now a Service should be deployed in addition to `bm-inventory` pod in
the integration environment.
=> Added a Service for bm-inventory app.

openshift/template.yaml
Port name can't be longer than 15 characters.
=> Renamed port's name 'assisted-service' --> 'assisted-svc'.

openshift/template.yaml
Without it the new service for `assisted-installer` isn't deployed.
=> Added "---" separator in openshift/template.yaml after adding a service.

cmd/main.go
Bucket is already created in integration env therefore re-creating it
will resolved in an "Access denied" error from S3.
=> Removed S3 bucket creation.

openshift/template.yaml
This ServiceAccount was authorized to create Jobs within the same
namespace, we need it so `assisted-service` can create `dummy-image` job
without errors.
=> Connected `assisted-service` deployment to its ServiceAccount.

openshift/template.yaml
`assisted-service` expects an environment variable named DB_PASS
and not DB_PASSWORD.
=> Fixing DB password's env variable in openshift/template.yaml.

openshift/template.yaml
It was removed at cc3db2a67f0ffd73926ce9396942aaa7f5c01a1f so the
template was needed to be updated.
=> Removed s3-object-expirer from openshift/template.yaml.

Makefile
This image has the fix to make things work with python 3.7
additionally the previous image was archived and unmaintained.
Fixes https://github.com/filanov/bm-inventory/issues/522
Moved from https://github.com/filanov/bm-inventory/pull/524
=> Use official swagger codegen docker image for client generation

restapi/embedded_spec.go, subsystem/cluster_test.go, subsystem/host_test.go, swagger.yaml
In https://github.com/oshercc/ignition-manifests-and-kubeconfig-generate, there is call to assisted-service for Hosts List API.
In this PR, I enable the API to be able to be called it as a Agent authenticated in addition to User.
This is needed for :
https://github.com/oshercc/ignition-manifests-and-kubeconfig-generate/pull/19
=> Add Agent Auth to Hosts list API

client/installer/download_cluster_i_s_o_responses.go, cmd/main.go, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, models/image_info.go, pkg/s3wrapper/client.go, pkg/s3wrapper/mock_s3wrapper.go, restapi/embedded_spec.go, restapi/operations/installer/download_cluster_i_s_o_responses.go, subsystem/image_test.go, swagger.yaml
1. Upon generating image, create a presigned S3 URL and store it in download_url.  If S3 isn't exposed, DownloadClusterISO can still be used and it will download from the presigned URL.  The UI should show either the presigned URL or the assisted-service URL depending on the deployment.
2. Added image size and expiration time.
=> MGMT-1669 / MGMT-1637: Add image presigned URL, size, and expire time

pkg/auth/auth_handler.go
To avoid log flood per each new request when auth disabled, move to debug
=> Set Auth disabled log to debug mode

Dockerfile.assisted-service-onprem, Makefile
The on-prem assisted-service now runs as non-root user and `/data` is not be world-writeable.
```
podman top installer
USER        PID   PPID   %CPU    ELAPSED        TTY     TIME   COMMAND
assisted-installer   1     0      0.000   8.482246148s   pts/0   0s     /assisted-service 
podman exec -it installer ls -ld /data
drwxr-xr-x. 1 assisted-installer assisted-installer 4096 Aug  7 01:49 /data
```
Ref: https://issues.redhat.com/browse/MGMT-1738
=> Run assisted-service on-prem as non-root

openshift/template.yaml
This is needed in order to set some env variables and also set different
values to theme for each integration, staging and production envs.
=> Adding ConfigMap to openshift/template.yaml

Dockerfile.assisted-service, Makefile, skipper.yaml, tools/generate_python_client.sh
Matching PR on openshift/release#10715
Made the production image to be a multistage because:
* In assisted-service we depend on a sequence of operations in runtime. In Prow all the images should be built in build time.
* DockerInDocker isn't available. e.g. to run client generation with a swagger container.
=> MGMT-1733 Make multistage production image to support Prow

openshift/template.yaml
This namespace is overwritten in app-sre according to the env so it is
not in use and just creating confusion.
=> Removing `namespace` field from all resources in openshift/template.yaml

pkg/s3wrapper/client.go
it is not needed for aws s3 or for scality
=> MGMT-1791 remove disable ssl from s3 client

openshift/template.yaml
Now the env variables are declared directly in the deployment, this mean
that the pod will restart for each change of those env variables values.
=> Removed ConfigMap from openshift/template.yaml.

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/installcfg/installcfg.go, internal/installcfg/installcfg_test.go, models/cluster.go, models/cluster_create_params.go, models/cluster_update_params.go, models/image_create_params.go, models/image_info.go, restapi/embedded_spec.go, swagger.yaml
The PR enables the user to set HTTP/S proxy values to be set for the installed cluster.
The values will be reflected in the generated `install-config.yaml`:
```
apiVersion: v1
baseDomain: redhat.com
proxy:
httpProxy: http://10.46.41.7:3128
httpsProxy: ""
noProxy: ""
```
On the installed cluster, the cluster-wide proxy [1] will contain those settings:
```
oc get proxy cluster -o yaml
apiVersion: config.openshift.io/v1
kind: Proxy
...
spec:
httpProxy: http://10.46.41.7:3128
...
```
[MGMT-1108] The agent runs on the nodes will use the same HTTP Proxy to communication with the assisted service:
```
oc describe pod -n assisted-installer createimage-4cb1cb1a-aa7c-441a-9ecf-7ea58054522b-202008051sfrfk
...
Environment:
IGNITION_CONFIG:        {
"ignition": { "version": "2.2.0" },
...
"contents": …
```
=> [MGMT-766][MGMT-1108] Provide HTTP/S Proxy for OCP cluster installation

cmd/main.go, deploy/assisted-service.yaml, openshift/template.yaml, pkg/s3wrapper/util.go, pkg/s3wrapper/util_test.go
Currently we sometimes are provided an s3 "url" which is just a
hostname. This causes an error when trying to upload the iso file.
This PR will add either http or https to the hostname to create
a valid url.
cc @ybettan @romfreiman
=> MGMT-1772 Use an env var to set the s3 url scheme if not present

Dockerfile.assisted-service-onprem, pkg/job/local_job.go
Update to use the new assisted-iso-create command. In case of local, there is no k8s job and the assisted-iso-create
runs inside the installer container itself.
=> Update local job to use assisted-iso-create

subsystem/cluster_test.go
fix failed tests: cancel installation with a disabled host and reset cluster with a disabled host
fix failed test: http://10.46.10.2:8080/job/assisted-service-subsystem-test/1195/consoleFull
http://10.46.10.2:8080/job/assisted-service-subsystem-test/1198/consoleFull
@RazRegev @filanov please review
=> fix subsystem test - cancel installation with a disabled host

Dockerfile.assisted-iso-create
This allows a user with root group (as we will run on OpenShift) to
write to this directory
=> The working directory needs group write permissions

internal/bminventory/inventory.go, pkg/transaction/transaction.go
Return a new object don't overwrite the pointer value becuase GORM is using a pointer for a parent
=> MGMT-1839 fix adding query_option to db pointer

tools/wait_for_assisted_service.py
Service will start reploying to request only after all the components are created.
Durring the creation of the inventory there is a dummy job to pull iso-generation image
Pulling this iso can take a long time
=> MGMT-1841 Increase wait for service timeout

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/common/db.go, subsystem/image_test.go
Image should be generated based on its recent updated properties.
We need to consider proxy settings change in order to generate a
new image.
The PR adds a check when downloading ISO for changed in proxy settings.
If there was a change, a new image will be generated and the new proxy
changes will be computed and saved for next ISO download check.
=> [MGMT-1828] Generate new ISO after proxy was changed

build_deploy.sh
Nothing is triggered on PRs, on merges to master the new image will be
built and pushed to quay.io.
=> Adding 'assisted-iso-generator' to app-interface.

deploy/assisted-service.yaml
As assisted-service is based on ubi8 instead of scratch now,
aws credenetials file is expected at /root/.aws/ path.
Hence, set AWS_SHARED_CREDENTIALS_FILE env var to /etc/.aws/credentials
=> deployment: change aws mountPath

go.mod, internal/bminventory/inventory.go, internal/cluster/validations/validation_test.go, internal/cluster/validations/validations.go
Proxy attributes should be validated on cluster registration
and on cluster update.
=> Validate Proxy settings

go.mod, go.sum, pkg/ocm/authorization.go
Use CapabilityReview API from ocm-sdk-go instead of a manually generated request.
=> MGMT-1859: use CapabilityReview via SDK

config/onprem-iso-config.ign, config/onprem-iso-fcc.yaml, docs/README.md, docs/installer-live-iso.md
Contains documentation and ignition config to create an
assisted-service live ISO.
Requires a follow-up PR that does the correct DNS translation
for SERVICE_BASE_URL=http://assisted-api.local.openshift.io:8080.
The discovery ISO's /etc/hosts will be modified to include the
live ISO host's ip addresses and they will be mapped to
assisted-api.local.openshift.io. This is being worked on in a
separate PR.
=> MGMT-1450: Create assisted installer artifact to run on-prem

Makefile, assisted-iso-create/main.go, pkg/job/local_job.go, subsystem/image_test.go
If the ISO already existed on disk, the coreos-installer command would error out. This
PR ensures that when coreos-installer runs, any previous ISO has been deleted first.
This change also:
- adds a 10s sleep to a test because the API requires 10s to elapse between ISO
create requests
- captures stderr output when running coreos-installer
- specifies a 30m timeout for onprem subsystem tests, matching the k8s test
suite. The default 10m was not enough
- enables `make clean-onprem` to work even if the pod does not exist
=> fixes error when re-generating an ISO for the same cluster on-prem

Makefile, tools/clear_deployment.py
This reverts commit 3f53620644be27b21deedde4c50e26b178f08bfc.
no defult value to added arg, failes jenkins ci
```
20:29:03  python3 ./tools/clear_deployment.py --delete-namespace True --delete-pvc  --namespace "assisted-installer" --profile "minikube" --target "minikube" || true
20:29:03  usage: clear_deployment.py [-h] [--delete-namespace DELETE_NAMESPACE]
20:29:03                             [--delete-pvc DELETE_PVC] [--namespace NAMESPACE]
20:29:03                             [--profile PROFILE]
20:29:03                             [--target {minikube,oc,oc-ingress}]
20:29:03                             [--domain DOMAIN]
20:29:03                             [--deploy-tag DEPLOY_TAG | --deploy-manifest-tag DEPLOY_MANIFEST_TAG | --deploy-manifest-path DEPLOY_MANIFEST_PATH | …
```
=> Revert "MGMT-1849: Delete PVCs on clear-deplyment by flag (#161)"

internal/identity/identity.go, pkg/auth/auth_handler.go, pkg/auth/authz_handler.go, pkg/ocm/pullsecret_auth.go
When authentication is disabled, new clusters should be created with 'admin' as user_name.
=> MGMT-1867: set user_name as 'admin' when auth is disabled

Dockerfile.assisted-service-build, tools/deploy_ui.py, tools/utils.py
Replace using Docker to generate a UI deployment descriptor with running the generation script directly from a repository clone. The Docker method effectively requires a container to run within a container, which not always works and does not work with Podman.
=> MGMT-1723 Run UI yaml generation directly

config/onprem-iso-config.ign, config/onprem-iso-fcc.yaml, docs/installer-live-iso.md
The temporary string that represents auth.json needs to be base64
or the transpiler will error.
=> MGMT-1450: Fix auth.json path in live ISO and FCC

tools/deploy_assisted_installer_configmap.py
This handles yaml parsing issues in Python reflected in CI
=> Wrap JWKS and OCM URLs with quotation marks in configMap

openshift/template.yaml
SELF_VERSION should use the smae value as ASSISTED_SERVICE_IMAGE:IMAGE_TAG.
=> Updating the value of SELF_VERSION parameter in openshift/template.yaml.

openshift/template.yaml
The TAG should follow the same TAG as `assisted-service` TAG.
The previous TAG was removed from IMAGE_BUILDER variable.
=> Changed the TAG of IMAGE_BUILDER in openshift/template.yaml.

cmd/main.go, tools/wait_for_assisted_service.py
health api will indicate the service is started and have all the needed clients
ready will indicate that service is ready to recive API calls and will start to be active only
after dummy iso is generated
Using middleware to enable the api after the dummy iso is generated
Service is health but not ready
```
 mfilanov  …  github.com  openshift  assisted-service  curl -i http://192.168.39.203:30948/health
HTTP/1.1 200 OK
Date: Wed, 26 Aug 2020 14:50:11 GMT
Content-Length: 0
 mfilanov  …  github.com  openshift  assisted-service  curl -i http://192.168.39.203:30948/ready
HTTP/1.1 503 Service Unavailable
Date: Wed, 26 Aug 2020 14:50:12 GMT
Content-Length: 0
```
After the dummy iso job is completed the service is ready:
```
curl -i http://192.168.39.203:30948/ready
HTTP/1.1 200 OK …
```
=> MGMT-1792 add ready api to assisted-service

build_deploy.sh, pr_check.sh
The helper script `build_images.sh` should run in the same process
because the variables between them are shared.
=> Fixing build_deploy.sh and pr_check.sh.

internal/host/common.go
In case statusInfo is empty on host status change (e.g host that
changes to status Known), there should be no empty parenthesis
in the event info.
=> OCPBUGSM-16205: Remove empty parenthesis from event info

internal/bminventory/inventory.go, internal/cluster/validations/validation_test.go, internal/cluster/validations/validations.go, subsystem/cluster_test.go
In register & update cluster, if user passed SSH key - verify it
is not malformed before updating db.
=> OCPBUGSM-13814: Added SSH public key validation

Makefile
```
kubectl describe configmaps assisted-service-config  | grep INSTALLATION_TIMEOUT -A 2
INSTALLATION_TIMEOUT:
----
120m
```
```
python3 ./tools/deploy_assisted_installer_configmap.py --target "minikube" --domain "" \
--base-dns-domains "" --namespace "assisted-installer" --profile "minikube" \
--installation-timeout 120m  \
--enable-auth "False" 
```
=> Fix installation timeout deployment in makefile

Makefile
Due to recent changes, the target argument is now used to decide if
running on minikube or on OCP.
Since this argument was missing the code assumed it is running in
minikube
=> OCPBUGSM-16649 - added missing target argument to deploy_sso_secret

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, pkg/s3wrapper/client.go
AWS returns 405 MethodNotAllowed when trying to update tags of an object
that was deleted, rather than the expected 404.
=> OCPBUGSM-16612: Handle MethodNotAllowed when updating tags

build_images.sh
Renamed:
* from:     quay.io/app-sre/assisted-iso-generator
* to:       quay.io/app-sre/assisted-iso-create
in build_images.sh.
We are waiting for https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/8566 to be merged first.
=> Renamed image name on quay.io/app-sre/.

build_deploy.sh
A variable name was changed in build_images.sh but not in
build_deploy.sh, this fix should fix the issue.
=> Fixing build_deploy.sh.

openshift/template.yaml
No one is making use of ROUTE53_SECRET variable in the code so
apparently the credentials are expected to be red from a file.
=> Consuming route53-creds secret as a volume in openshift/template.yaml.

pkg/auth/auth_handler.go
Fix log and print the error string, not the obj.
**Example:**
```level=error msg="Error parsing token: Token is expired" pkg=auth```
**Used to be:**
```
) %!e(uint32=16) %!e(string=)}" func="github.com/openshift/assisted-service/pkg/auth.(*AuthHandler).AuthUserAuth" file="/go/src/github.com/openshift/origin/pkg/auth/auth_handler.go:161" pkg=auth
```
=> MGMT-1940 Fix token parsing error format

internal/bminventory/inventory_test.go, internal/network/cidr_validations.go
1.  All subnet sizes should include at least 128 addresses
2. Host network prefix should have a maximum value of 25 (128 addresses).
=> MGMT-2018 Advanced networking additional validations

openshift/template.yaml
A variable should be set to the path of the credentials file otherwise
the default value will be used and the DNS validation will fail.
=> Fixing base DNS issue when trying to configure route53 to a cluster.

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/host/common.go, internal/host/host.go, internal/host/host_test.go, internal/host/installcmd.go, internal/host/instructionmanager_test.go, internal/host/transition_test.go, internal/hostutil/host_utils.go
Followed linux hostname rules:
Each element of the hostname must be from 1 to 63 characters long and the entire hostname, including the dots, can be at most 253 characters long.
Valid characters for hostnames are ASCII(7) letters from a to z, the digits from 0  to 9, and the hyphen (-). A hostname may not start with a hyphen.
=> MGMT=1918 Validate hostname validity on the backend

internal/host/statemachine.go, internal/host/transition.go, internal/host/transition_test.go
After host status is changed from installing to
installing-pending-user-action the agent is still tries to
register to the cluster.
Since there is no transition that handled registration from
source state installing-pending-user-action, the registration
always failed with error "Failed to register host: error
creating host metadata".
In this commit I extended the transition for register host
and return a specific error in such cases, which wont create
event log message on each try and prevent from the agent
to register every time.
=> MGMT-1707: fix installing-pending-user-action event log

openshift/template.yaml
`app-sre` contract requires `3` replicas for production env.
`integration` and `staging` envs will run `3` replicas as well.
We need to wait for https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/8449 to be merge first and then we can merge this one.
=> Adding REPLICAS_COUNT parameters to openshift/template.yaml.

deploy/assisted-service.yaml, internal/bminventory/inventory.go, internal/installcfg/installcfg.go, internal/installcfg/installcfg_test.go, openshift/template.yaml
In order to be able to pull container images from Brew, the root certificate for Red Hat IT needs to be installed on the live ISO.
Also for assisted-install-controller, the cert is added to InstallConfig in `AdditionalTrustBundle`
=> MGMT-2030 - Add Red Hat IT Root CA to ignition and InstallConfig

Dockerfile.assisted-iso-create, Makefile, README.md
This PR adds the required files to build the image builder service with a given RHCOS or Fedora CoreOS base OS image.
=> Added livecd iso creation files

pkg/s3wrapper/filesystem.go
ListObjectsByPrefix was not accounting properly for the base directory, so it was
failing to identify the desired files.
ListObjectsByPrefix returned a slice of full paths on the local disk instead of
object references.
UploadStream used a 0-byte Read to identify the end of a file instead of
io.EOF. I don't fully understand why, but in practice, I observed 0-byte reads
happening without an EOF.
Fixing these three issues was required to get the subsystem test
"[only_k8s]Download cluster logs" to pass.
Thanks are due to @rwsu who also helped identify and resolve these bugs.
=> fixes three bugs in pkg/s3wrapper/filesystem.go

internal/bminventory/inventory.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/transition_test.go, internal/cluster/validator.go, internal/common/db.go
- Change VIPs validation text to indicate if lease allocation has been timed out
- When lease allocation is timed out, cluster status remains insufficient
- Event is triggered when lease timeout occurs
=> MGMT-2012 Handle DHCP lease allocation timeout

internal/host/statemachine.go, internal/host/transition_test.go, subsystem/cluster_test.go
Should be allowed for edge cases where some hosts have this
status and other hosts are in error. In that case we can allow
abort and reset.
https://bugzilla.redhat.com/show_bug.cgi?id=1878154
=> OPCBUGSM-17391: cancel/reset from installing-pending-user-action

openshift/template.yaml
We need to disable route53 on production env, therefore this parameter
needs to be allowed to stay empty.
=> Make it possible to disable route53.

internal/bminventory/inventory.go, subsystem/cluster_test.go
Since host is loaded before EnableHost transition, we
should load it again before RefreshStatus.
Otherwise, it will skip the discovery part.
=> OPCBUGSM-17442-fix-enable-host

build_deploy.sh, build_images.sh, pr_check.sh
Before the fix the scripts `pr_check.sh` and `build_deploy.sh` will fail
only if the last command of each one of them fails, after the fix
each failure in the scripts will make it exit with error code
immediately.
=> Making app-sre-jenkins job fail if the scripts fails.

internal/host/installcmd.go
On D/S image, nsenter is being executed without environment variables,
therefore no proxy configuration are enabled to 'coreos-installer'
command which attempt to download a resource.
While the issue isn't happened to commands running on 'bash' image used
for U/S assisted-installer image, D/S image uses ubi8-minimal which
behaves differently and requires the env-vars to be provided explicitly
(assuming we'd like to avoid hacking the process id of the agent in
order to inherit the already-provided env-vars for proxy from it).
Depends on https://github.com/openshift/assisted-installer/pull/35
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1877
=> Pass proxy settings to install command

cmd/main.go
This PR is pending UI changes. Otherwise errors invalid format will be shown instead of dates in the UI.
=> MGMT-1015 Fix date format in Swagger APIs

internal/host/statemachine.go, subsystem/cluster_test.go
Without this transition, installation will hang on 'resetting' state if some hosts are disabled and
other passed the reboot stage, since the transition failed for the disabled hosts.
=> OPCBUGSM-17520: noop transition for resetting-pending-user-action (disabled host)

pkg/job/job.go
This commit adds a field to the job config struct for the secret name
then we use that to get the secret values rather than passing them
through directly. The other struct fields had to be kept as they
are used for local jobs.
=> MGMT-1776 Pass S3 secrets using a secret ref rather than plain text

internal/common/error_utils.go, pkg/auth/auth_handler.go, pkg/ocm/authorization.go
In case that OCM fails to retrieve a token from SSO, the return call of the API should be 503 and not 401.
=> OCPBUGSM-17629 Handle failure OCM call for IsAdmin

tools/check-commit-message.sh, tools/check-commits.sh
Instead of assuming "origin" is the remote that corresponds to
github.com/openshift/assisted-service, the script now finds the remote
corresponding to that location. This works better for devs who use "origin" as
the name for their fork's remote.
If the commit is rejected, a message is shown citing the location of the file
where the commit message is preserved. Previously, it looked to the dev like
their commit message had just been thrown away.
In the interest of ensuring the dev reads the error message in case of commit
rejection, the script no longer prints the entire commit message before
displaying the helpful error message. By not throwing a wall of text at the dev,
they'll be more likely to see the error info itself.
=> NO-JIRA improves commit message checking

internal/cluster/validations/validation_test.go, pkg/auth/auth_handler.go, pkg/ocm/pullsecret_auth.go
In order to minimize OCM calls, the cache is now updated after that the Admin Capability is checked.
=> OCPBUGSM-17629 Move Agent Auth cache to AuthHandler

cmd/main.go
Previously (I assume due to a typo) the log message when leader election failed
included the wrong error variable, so the message would end with:
`error="<nil>"`
=> NO-ISSUE: logs the correct error when leader election fails

openshift/template.yaml
If the parameter is not provided then we get the following error:
`envconfig.Process: assigning MYAPP_BMCONFIG_AGENT_TIMEOUT_START to AgentTimeoutStart: converting '' to type time.Duration. details: time: invalid duration " func=main.main file="/go/src/github.com/openshift/origin/cmd/main.go:110`
=> MGMT-2249 Add the old default as the default for the parameter

openshift/template-post-deploy-job.yaml
The smee client will handle routing to the correct path for us,
we just need to post to the url endpoint which is configured in a
secret in the openshift cluster.
cc @YuviGold
=> MGMT-1743 - use smee to proxy requests to run the jenkins job

pkg/auth/auth_handler.go
In order to avoid unnecessary requests to CapabilityReview API in AMS,
store the user payload in cache.
=> MGMT-2292 cache payload in UserAuth flow

Makefile, README.md, deploy/assisted-service-configmap.yaml, tools/deploy_assisted_installer_configmap.py, tools/update_bm_cm.py
This PR will add the capability to customize the deployment of OPENSHIFT_RELEASE_IMAGE used on the different OCP/K8s objetcs.
- This PR is related too with: https://github.com/openshift/assisted-test-infra/pull/156, we need to merge this current PR before this other from assisted-test-infra repo to make it work properly.
=> MGMT-2052 - Patching OPENSHIFT_RELEASE_IMAGE variable to make that customizable on the Assisted Service

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
This generates a new ignitionConfig without the secrets and logs it.
=> MGMT-2252: Don't log secrets from the ignitionConfig

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
In case the Authentication is disabled, (disconnected environment, on-prem) no need to validate that the pull secret contains the "cloud.openshift.com" auth and to add an env to Agent.
=> MGMT-2279 Pull Secret validation -  Auth disabled

.gitignore, Dockerfile.assisted-service-build, Jenkinsfile, Makefile, pkg/log/logcontext_test.go, pkg/requestid/requestid_test.go, pkg/thread/example_test.go
- Using [gotestsum](https://github.com/gotestyourself/gotestsum) tool for cleaner results
- Exporting results to `JUnit` format for Jenkins to be published
- Results are in a dedicated `$(REPORTS)` folder (ignored on `.gitignore`)
- Adding a timeout of 1m for postgres initialization (was endless in case of an error)
=> NO-ISSUE Use gotestsum tool for testing and publish junit on Jenkins

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
Looks like this was a typo in https://github.com/openshift/assisted-service/pull/442
cc @tsorya @eranco74
=> MGMT-2357: Return an error when the cluster is not found for upload logs

internal/bminventory/inventory_test.go, internal/cluster/validations/validations.go
Users can easily insert new lines or spaces on either side
of the pull secret. So for convience, remove them.
=> MGMT-1710: trimspace around provided pull secrets

tools/check-commit-message.sh
Without this builds were failing on jenkins on the merge commit
jenkins creates to test a PR.
=> NO-ISSUE add merge back to commit check regex

openshift/template-post-deploy-job.yaml
When a Job is created again out of the same git commit, K8S won't re-run the Job.
This patch assures that each time we create a Job it actually runs since the name will be unique.
=> APPSRE-2377 Use a random ID instead of the commit hash

internal/imgexpirer/imgexpirer.go, internal/imgexpirer/imgexpirer_test.go
Leader is already checked before starting the task, so the running task should be able to call its callbacks
=> MGMT-2381 Missed image expiration events upon leader change

internal/host/apivipconnectivitycheckcmd.go, internal/host/apivipconnectivitycheckcmd_test.go, internal/host/instructionmanager.go, models/api_vip_connectivity_request.go, restapi/embedded_spec.go, swagger.yaml
Added verify CIDR flag to:
- swagger: api_vip_connectivity_request -> verify_cidr
- InstructionConfig: VERIFY_API_VIP_CIDR env var
Passed to apivipConnectivityCheckCmd for invoking apivip_check accordingly.
=> MGMT-2318 pass verify CIDR flag to APIVIPConnectivityCheckCmd

.gitattributes
`git diff` output would be nicer.
Instead of generated files diff looking like that:
```bash
// MockS3API is a mock of S3API interface
diff --git a/pkg/s3wrapper/mock_s3wrapper.go b/pkg/s3wrapper/mock_s3wrapper.go
index 2a42b8b..b0a6ec4 100644
--- a/pkg/s3wrapper/mock_s3wrapper.go
+++ b/pkg/s3wrapper/mock_s3wrapper.go
@@ -6,12 +6,11 @@ package s3wrapper
import (
context "context"
+       gomock "github.com/golang/mock/gomock"
+       logrus "github.com/sirupsen/logrus"
io "io"
reflect "reflect"
time "time"
-
-       gomock "github.com/golang/mock/gomock"
-       logrus "github.com/sirupsen/logrus"
)
// MockAPI is a mock of API interface
diff --git a/site/ClusterStatus.dot b/site/ClusterStatus.dot
index 6c552d4..35bd3bb 100644
--- a/site/ClusterStatus.dot
+++ b/site/ClusterStatus.dot
@@ …
```
=> NO-ISSUE adding gitattributes declaring generated files

internal/events/event_test.go
Events are listed with the oldest first, but the unit test checked that
the newest was returned first. This mostly passed because on faster
machines the two timestamps were very similar and so the check passed.
=> MGMT-2367 Fix multiple events unit test

internal/host/stopinstallation.go
On installation cancelling, use podman stop instead of kill,
so containers that exited won't throw error. It will exit with
status code 0.
=> OCPBUGSM-18587: updated stop installation cmd

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/mock_cluster_api.go, internal/cluster/transition.go, internal/connectivity/mock_connectivity_validator.go, internal/events/mock_event.go, internal/hardware/mock_validator.go, internal/host/mock_host_api.go, internal/host/mock_instruction_api.go, internal/metrics/mock_netricsManager_api.go, models/cluster.go, pkg/generator/mock_install_config.go, pkg/leader/mock_leader_elector.go, pkg/ocm/mock_pullsecret_auth.go, pkg/s3wrapper/mock_s3iface.go, pkg/s3wrapper/mock_s3wrapper.go, restapi/embedded_spec.go, subsystem/cluster_test.go, swagger.yaml
When we upload controller logs we are setting this flag, when we reset
the cluster we are resetting it and when we are downloading logs we are
making sure is set with a valid timestamp otherwise we don't download.
=> MGMT-2326: Added controller_logs_collected_at to 'cluster' relation in DB.

internal/events/event_test.go
It's a rather inefficient way of setting the time.
=> NO-ISSUE Remove sleep from unit test

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/host/nextsteprunnercmd.go, internal/host/nextsteprunnercmd_test.go, subsystem/cluster_test.go, subsystem/day2_cluster_test.go, subsystem/host_test.go, subsystem/utils_test.go
Following review comments, moving the command for running the next-step agent to the `host` package
=> MGMT-2211 Move next step runner command to host package

internal/host/downloadinstallercmd.go, internal/host/downloadinstallercmd_test.go, internal/host/instructionmanager.go, internal/host/instructionmanager_test.go
Added download of the installer image in order to cache it for the installtion.
The command have a timeout of 15 minuts and will try to download the image during this period.
Images list from one of the hosts before installation:
```
sudo podman images
REPOSITORY                                  TAG      IMAGE ID       CREATED        SIZE
quay.io/ocpmetal/assisted-installer-agent   latest   10b6aace1fab   9 hours ago    473 MB
quay.io/ocpmetal/assisted-installer         latest   4cc8e21c65d5   12 hours ago   69.9 MB
```
Passed test-infra
=> MGMT-2448 Add installer image caching to host discovery

internal/host/host.go, internal/host/host_test.go
Send an event once when a host transitions to bootstrap.
The text of the event will be
```
Host <hostid>: set as bootstrap
```
=> MGMT-2313: Send an event when a host is chosen for bootstrap

go.mod, go.sum, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/mock_cluster_api.go, internal/host/refresh_status_preprocessor.go, internal/host/statemachine.go, internal/host/transition_test.go, internal/host/validation_id.go, internal/host/validator.go, internal/network/connectivity_groups.go, internal/network/connectivity_groups_test.go, internal/network/machine_network_cidr.go, models/cluster.go, models/host_validation_id.go, restapi/embedded_spec.go, subsystem/cluster_test.go, swagger.yaml
- Add logic to calculate connectivity majority groups
- Add validation to check that host belongs to majority groups
/cc @ronniel1 
/cc @filanov 
/cc @avishayt
=> Ori/mgmt 2401 Support connectivity majority groups

internal/metrics/recorder.go
This change is for matching cluster Id label name for HTTP
metrics (currently named `id`) to application metrics (`clusterId`)
=> MGMT-2415 change id label name for HTTP metrics to clusterId

pkg/auth/authz_handler_test.go
There are tests that uses a shared cache, but each tests should start with an empty one.
Although we flush it at the begging of each test, if it runs in parallel one test might get an error because of other test cached a different value for the requester authz.
This test takes no time to run, so it safer not to run in parallel anyway.
Error:
03:33:16  === Failed
03:33:16  === FAIL: pkg/auth TestAuthz/pass_access_review_from_cache (0.00s)
03:33:16  STEP: get cluster first attempt, store user in cache
03:33:16      TestAuthz/pass_access_review_from_cache: authz_handler_test.go:222:
03:33:16          	Error Trace:	authz_handler_test.go:222
03:33:16          	            				ginkgo_dsl.go:435
03:33:16          	            				authz_handler_test.go:218
03:33:16          	Error:      	Not …
=> MGMT-2480: Fixed flaky authz test

pkg/auth/authz_handler_test.go, pkg/log/logcontext_test.go
Since it collides with the logs test service port (8082).
=> MGMT-2480: change authz test server port

openshift/template-post-deploy-job.yaml
Previously all these clusters deployed to the various cloud
environments were a very generic "test-cluster" because we were
not providing anything different.
After this change the cluster will have a slightly more unique base
name but will also share a name with the openshift job that kicked
off the install which might be helpful in the future.
Fixes [MGMT-2295](https://issues.redhat.com/browse/MGMT-2295)
cc @gamli75
=> MGMT-2295 Give the test cluster a unique name

internal/host/common.go, internal/host/stopinstallation.go
[MGMT-2431](https://issues.redhat.com/browse/MGMT-2431): Added parameters to get logs command on installation failure.
--pid=host:
installer-gather.sh needs to run on the host filesystem rather than on
the container filesystem.
for installer-gather.sh command, in `assisted-installer-agent` we use
`nsenter` and we also need to add this flag in `assisted-service`.
-with-installer-gather-logging:
this is set to true because on cluster installation failure we need
those logs.
logs_sender (assisted-installer-agent) is also used from
`assisted-installer` in order to get logs on a cluster installation
success, in this case we won't need those logs.
=> MGMT-2431: Copy 'logs_sender' binary file to host.

Dockerfile.assisted-iso-create
The latest coreos-installer:release version was compiled with a newer
glibc version (2.32). Switching to an older tag.
https://issues.redhat.com/browse/MGMT-2635
=> MGMT-2635 Bugfix: GenerateClusterISO failing in subsystem tests

pkg/auth/authz_handler_test.go
On some cases authz tests starts before the mock server get to start.
In this commit added function to verify server is ready before starting
the tests (or throw timeout after a minute)
=> MGMT-2480: Wait until server is ready

internal/host/statemachine.go, internal/host/transition_test.go
Disabled hosts can try to register if it was rebooted, register will be accepted
=> OCPBUGSM-19585 Register disabled host

go.mod, internal/ignition/ignition.go, internal/ignition/ignition_test.go
Add direction to create file  "/etc/keepalived/unsupported-monitor.conf" in master ignition to signal OCP that it has to renew 
DHCP leases
/cc @eranco74 
/cc @ronniel1
=> MGMT-2674 VIPs DHCP leases are not renewed in OCP

pkg/auth/authz_handler_test.go
In a fix made to authz unit test where we wait for the server to be up, I created unexpected calls to access review and capability review. This causes the ci to fail sometimes:
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
15:32:14  	panic: runtime error: invalid memory address or nil pointer dereference
15:32:14  [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xea429f]
15:32:14
15:32:14  goroutine 88 [running]:
15:32:14  testing.tRunner.func1.1(0xfd68a0, 0x1ccc380)
15:32:14  	/usr/local/go/src/testing/testing.go:940 +0x2f5
15:32:14  testing.tRunner.func1(0xc0008a27e0)
15:32:14  	/usr/local/go/src/testing/testing.go:943 +0x3f9
15:32:14  panic(0xfd68a0, 0x1ccc380)
15:32:14  	/usr/local/go/src/runtime/panic.go:969 +0x166
15:32:14 …
=> MGMT-2692: Fixed waiting for server in authz test

cmd/main.go, go.mod, go.sum, internal/common/common_unitest_db.go, internal/migrations/20201019194303_change_overrides_to_text.go, internal/migrations/20201019194303_change_overrides_to_text_test.go, internal/migrations/migrations.go, internal/migrations/migrations_suite_test.go, internal/migrations/migrations_test.go, models/cluster.go, restapi/embedded_spec.go, swagger.yaml
The default for the swagger string type is 2048 characters and
these could be quite large if someone wants to specify an entire
config
Curious if column type changes like this can be cleanly handled by the automigration.
@filanov do you know? Do we have tests for this kind of thing (ensuring that schema changes don't break stuff)?
Fixes [MGMT-2466](https://issues.redhat.com/browse/MGMT-2466)
=> MGMT-2466 Make the override columns text and add migrations

internal/cluster/cluster_test.go, internal/cluster/transition_test.go, internal/cluster/validator.go
- search for eligable master candidates with role Master or Automatic up to 3
the rest of the hosts are worker candidates
- make sure that the cluster has at least 3 known master candidates and zero
or 2 and more worker candidates
=> OCPBUGSM-19500 - enforce worker count with auto-assign

Makefile, deploy/postgres/postgres-deployment-ephemeral.yaml, tools/deploy_assisted_installer.py, tools/deploy_postgres.py, tools/deployment_options.py, tools/utils.py
- Added 'deploy-service-on-ocp-cluster' target - deploys the service on an OCP cluster
- kubeconfig is retrieved from OCP_KUBECONFIG env var (default: build/kubeconfig).
- Added 'deploy-ui-on-ocp-cluster' target - same as above for the UI.
- Updated utils->get_kubectl_command: support 'ocp' target.
- DEPLOY_TARGET is set to 'ocp' (as it should use local FS for S3).
- Deploys ephemeral postgres (i.e. without a persistent storage volume).
=> MGMT-2462 AI on OCP cluster

deploy/monitoring/grafana/assisted-installer-k8s-grafana.yaml, deploy/monitoring/prometheus/assisted-installer-k8s-prometheus-svc.yaml
- Fixing [BZ1872302](https://bugzilla.redhat.com/show_bug.cgi?id=1872302)
=> [BZ1872302] Exposing grafana and prometheus as NodePort instead of clusterIP on Minikube

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/mock_cluster_api.go, internal/common/db.go, internal/host/dhcpallocatecmd.go, internal/host/dhcpallocatecmd_test.go, internal/host/mock_host_api.go, internal/host/mock_instruction_api.go, internal/ignition/ignition.go, internal/ignition/ignition_test.go, internal/network/lease_utils.go, internal/network/lease_utils_test.go
- Add lease information for DHCP leases in cluster DB
- Save leases when VIPs are saved in DB in DHCP mode
- Send leases to agent when renewing leases - so agent will renew and not ask for a new lease
- Create lease files in OCP using ignition so OCP will renew and not ask for a new lease
/cc @YuviGold 
/cc @ronniel1
=> MGMT-2659 DHCP server changes the VIPs addresses after installation has started - code changes

internal/connectivity/mock_connectivity_validator.go, internal/events/mock_event.go, internal/hardware/mock_validator.go, internal/host/inventorycmd.go, internal/host/inventorycmd_test.go, internal/host/mock_host_api.go, internal/host/mock_instruction_api.go, internal/metrics/mock_netricsManager_api.go, pkg/generator/mock_install_config.go, pkg/k8sclient/mock_k8sclient.go, pkg/leader/mock_leader_elector.go, pkg/ocm/mock_authorization.go, pkg/ocm/mock_pullsecret_auth.go, pkg/s3wrapper/mock_s3iface.go, pkg/s3wrapper/mock_s3wrapper.go
* It should enable getting disks and partitions additional info, such as: MOUNTPOINTs, FSTYPEs, storage controllers, etc.
* It should be backward-compatible with old AI agents as well
=> MGMT-2592: enable HW detection of host via new root path

tools/deploy_assisted_installer.py
'onprem' image has been recently removed: https://github.com/openshift/assisted-service/pull/592
Thus, the livecd should be manually copied on service deployment:
- Create an emptyDir volume.
- Mount assisted-iso-create image on initContainers.
- Copy iso to data folder in service container.
=> MGMT-2462: deploy on ocp - copy livecd

pkg/secretdump/secretdump_test.go, pkg/secretdump/struct.go
Contains functionality to dump structs in a manner that censors struct fields marked as secret
DumpSecretStruct generates a string representation of a struct with `secret:"true"` tagged fields removed.
Currently does not recurse into pointers to structs (or show pointer values in general), only regular nested structs.
This limitation can be improved in the future if needed.
Pointer addresses are redacted in order to not leak addresses.
=> MGMT-2629 Added secretdump package

Makefile, README.md, config/onprem-iso-config.ign, config/onprem-iso-fcc.yaml, docs/installer-live-iso.md, hack/verify-latest-onprem-config.sh, onprem-environment
* Use OPENSHIFT_INSTALL_RELEASE_IMAGE to use the same openshift version
* Add target to generate onprem ignition file
* Remove SERVICE_IPS from onprem-environment, as it's optional and
SERVICE_BASE_URL with ip:port serves the purpose. See
config/onprem-iso-fcc.yaml for how SERVICE_IPS is used.
=> NO-ISSUE: Generate and verify onprem configs in sync

pkg/s3wrapper/client.go, pkg/s3wrapper/client_test.go
Before the ISO generation optimization, we added a tag with the current
timestamp to the generated ISO and overwrote it if we wanted to reuse
the ISO.  The image expiration looked only at the tag to determine if it
should delete the image.
However, placing the tag on the initial image was accidentally left out
when the optimization code went in.  Thus, images that were never reused
do not have the timestamp tag, and are therefore never deleted.
This could be fixed by adding the tag back to the image generation flow.
However this would mean that we would need to manually clean old images
from deployments that do not have a tag.  Therefore the approach of this
commit is to check if the tag exists, and if not, fall back to the
object's creation time.
=> MGMT-2857: Fix image expiration

internal/host/common.go, internal/host/statemachine.go, internal/host/transition.go, internal/host/transition_test.go
So when the cluster will be recovered from that state, the
host won't get timeout error on the next refresh status in
cases it wasn't the problematic host.
=> MGMT-2868: refresh stage_updated_at if cluster is pending-user-action

internal/host/installcmd.go, internal/host/installcmd_test.go
The last user of this in the installer was removed in openshift/assisted-installer@93495e81245278863102d155b15b4d0782641ff4
=> MGMT-2633 Stop sending the hostname to the installer

internal/host/statemachine.go, internal/host/transition_test.go
It can happen that user rebooted the host manually after installation failure without changes in the cluster
if the registration return conflict or error then we have infinite number of events.
if the registration is blocked (403) it will break auto-reset feature.
So the best option is just accept the registration without changes in the DB
=> MGMT-2889 Allow registration of host in error state

internal/bminventory/inventory.go
In cancel and reset routs we read and write from the db multiple times
from a single transaction, therefore we need to add the for-update query
option, in order to avoid possible conflicts.
=> OCPBUGSM-18132: Added AddForUpdateQueryOption to cancel/reset

internal/ignition/ignition.go, internal/ignition/ignition_test.go
This adds a marker file to the bootstrap ignition so that the rest of the openshift installation knows that this cluster is using the assisted-installer and will need, for some time, to have a healthy 2-member etcd cluster.
This is intended to replace the [unsupported flag we currently use](https://github.com/openshift/assisted-installer/blob/08a0ca837247d867a3fbb1953415e8f417754ed2/src/k8s_client/k8s_client.go#L134-L154) to allow a 2-member etcd cluster.
I thought the `.done` naming was a bit misleading as we're not done with bootstrap when we write this file.
If anyone has a better name I'm open to suggestions.
cc @ironcladlou @hexfusion
=> MGMT-2888 Add marker file to bootstrap ignition

internal/host/common.go, internal/host/host.go, internal/host/transition.go, internal/host/transition_test.go, internal/host/validator.go
when the installation stages writing the image to disk and installing are timed out 
in case there was no check-in by the host for more then 3m the state info will contain information about the last checked in time
for example:
```
Host failed to install because its installation stage Writing the image to disk took longer than expected 10m0s, Host is not responding, last respond was at 2020-11-16T10:29:18.696Z
```
and 
```
Host failed to install because its installation stage Installing took longer than expected 1h0m0s, Host is not responding, last respond was at 2020-11-16T10:29:18.556
```
=> MGMT-2652 Inform there was a disconnectio when stage is timed out + test

pkg/s3wrapper/client_test.go, pkg/s3wrapper/upload_iso.go
AbortMultipartUploadWithContext use a new context because the opraiton will fail if the cancled context is used
Error before the fix:
```
time="2020-11-16T13:13:09Z" level=error msg="Failed to copy part 13 for file discovery-image-a36b49ad-2200-4fc0-914b-788f6d9e7246.iso: RequestCanceled: request context canceled\ncaused by: context canceled" func="github.com/openshift/assisted-service/pkg/s3wrapper.(*multiUpload).uploadPartCopy" file="/go/src/github.com/openshift/origin/pkg/s3wrapper/upload_iso.go:377" cluster_id=a36b49ad-2200-4fc0-914b-788f6d9e7246 go-id=3714 request_id=b8e1cf9a-5657-4576-b886-7b36f18a9221
time="2020-11-16T13:13:09Z" level=error msg="Failed to copy part 14 for file discovery-image-a36b49ad-2200-4fc0-914b-788f6d9e7246.iso: RequestCanceled: request context …
```
=> NO-ISSUE Handle ISO generation cancellation

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/host/host.go, internal/host/host_test.go, internal/host/mock_host_api.go, internal/host/monitor_test.go, internal/host/transition.go, internal/host/transition_test.go, subsystem/cluster_test.go
If a host is soft deleted by the user, there is a chance that
it will try to be registered to the cluster again. In
such cases, we should just remove the previews record of
the deleted host while registering it.
=> OCPBUGSM-20532: Allow register deleted hosts

models/system_vendor.go, restapi/embedded_spec.go, swagger.yaml
(First PR to solve https://issues.redhat.com/browse/MGMT-792)
This adds a virtual field to the system_vendor struct in the API so it can be populated by the agent. "false" if it doesn't think it's a virtual machine, "true" otherwise.
Will open a corresponding PR in the agent repo that actually populates this field once this one is merged.
=> MGMT-792 - Swagger - added virtual field to system_vendor

internal/cluster/registrar.go, internal/cluster/registrar_test.go, subsystem/cluster_test.go
If it was soft deleted in the past, and user is trying to register
the cluster again (with the same id), allow doing it by deleting any
previews record of the soft deleted cluster if exists.
=> OCPBUGSM-20563: Allow registering an unregistered cluster

internal/cluster/registrar.go, internal/cluster/registrar_test.go, subsystem/cluster_test.go
If it was soft deleted in the past, and user is trying to register
the cluster again (with the same id), allow doing it by deleting any
previews record of the soft deleted cluster if exists.
=> OCPBUGSM-20563: Allow registering an unregistered cluster (#694)

Jenkinsfile, Makefile, subsystem/cluster_test.go, subsystem/image_test.go
We have a shortage of resources in Jenkins and this prevents
us from running all subsystem tests for onprem in parallel.
To ensure we have some test coverage, we decided to run a small
subset of the subsystem tests that can exercise the onprem code
paths.
The tests that constitute the small subset have been tagged with
[minimal-set] in the test definitions.
=> MGMT-2765 Run a subet of subsystem tests for onprem in Jenkins

build_deploy.sh, build_images.sh
Before this change it was possible for an image built for a PR
to end up deployed to the integration environment.
To fix, we should have built the initial image as the git sha
then only if we needed to push, tag latest.
The race happened like this:
1. build for master starts
2. build for pr starts
3. build for master finishes and tags latest
4. build for pr finishes and tags latest
5. push latest
Fixes [MGMT-2982](https://issues.redhat.com/browse/MGMT-2982)
=> MGMT-2982 Fix image build race condition

models/cluster_create_params.go, restapi/embedded_spec.go, subsystem/cluster_test.go, swagger.yaml
[OCPBUGSM-20497](https://issues.redhat.com/browse/OCPBUGSM-20497) limit cluster name to 54 characters
=> OCPBUGSM-20497 limit cluster name to 54 characters

models/cluster_create_params.go, models/cluster_update_params.go, restapi/embedded_spec.go, restapi/operations/installer/upload_logs_parameters.go
This was the result of running `make generate-from-swagger` on the latest master
It looks like commits 89c1250f6d6901775c6d92d078f8f25cfbd33e07 and 0d610b28d817b91b55cf67d3d6ab6e463e03d567 should have included these changes.
cc @slaviered @asalkeld 
@filanov @YuviGold is this something we can add to a test suite? If files should be regenerated it would be great for the PR to fail tests. Otherwise I feel like these kinds of things will get missed constantly.
=> NO-ISSUE Regenerate files after swagger changes

internal/host/common.go, internal/host/instructionmanager.go, internal/host/logscmd.go, internal/host/logscmd_test.go, internal/network/machine_network_cidr.go
In order to gather logs on the agent side before the cluster creating is
completed we will need to use SSH in order to let bootstrap gather logs
from other masters, in order to do so we will need there IPs.
=> MGMT-2678: Adding list of IPs to logs cmd.

internal/host/common.go, internal/host/instructionmanager.go, internal/host/logscmd.go, internal/host/logscmd_test.go, internal/network/machine_network_cidr.go
In order to gather logs on the agent side before the cluster creating is
completed we will need to use SSH in order to let bootstrap gather logs
from other masters, in order to do so we will need there IPs.
=> MGMT-2678: Adding list of IPs to logs cmd. (#704)

pkg/error/error_utils.go, pkg/error/error_utils_test.go
Provides a work around for the error format bug returned
from the assisted service.
GetAssistedError function receives error and manually build
the message from Payload by the error type which is a struct
of pointers.
Will be used by assisted installer client when logging the
error messages.
=> MGMT-2411: Added error_utils.go

internal/host/logscmd.go
Workers don't have the public SSH key of bootstrap anyway so SSH to them
will fail, this is just adding noise to the real logs collection.
=> OCPBUGSM-20820: Removing workers IPs from logs cmd.

models/disk.go, restapi/embedded_spec.go, swagger.yaml
This field will be populated by the agent in a later pull request with the output of `smartctl -x --json=c <device>`
=> MGMT-3033 - Add S.M.A.R.T. field to inventory host disks

Jenkinsfile
Sinch the VM cleanup job is added, no need to run this
http://assisted-jenkins.lab.eng.tlv2.redhat.com/job/vm-cleanup/
(never really worked anyway)
=> NO-ISSUE Remove docker objects cleanup

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/common/error_utils.go, restapi/embedded_spec.go, restapi/operations/installer/download_cluster_files_parameters.go, swagger.yaml
This commit uploads the discovery ignition to S3 in addition to
the iso with the ignition embedded. It also allows for the ignition
to be downloaded through the same file download endpoint we use for
other cluster files.
This will be used for cases where the rest of the iso will be
made available in some other manner.
Fixes [MGMT-2943](https://issues.redhat.com/browse/MGMT-2943)
cc @avishayt @yrobla
=> MGMT-2943 Expose discovery ignition separately from iso

Makefile
Live ISO downloads sporadically fails with curl. Let curl retry
up to 5 times before failing.
=> MGMT-2955 add retry to live.iso curl download in deploy-onprem

models/inventory.go, restapi/embedded_spec.go, swagger.yaml
This list entry will contain all disks, even the ones that were filtered out. This is in contrast to the existing `disks` entry, which contains just the disks that are relevant for installation.
=> MGMT-3078 - Add an unfiltered_disks list entry to the inventory API

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
```
20:06:45  HTTP response body: {"code":"400","href":"","id":400,"kind":"Error","reason":"Invalid NTP source: envconfig:\"NTP_DEFAULT_SERVER\" default:\"0.rhel.pool.ntp.org\""}
```
=> MGMT-2322 Bugfix Default NTP value

internal/manifests/manifests.go, internal/manifests/manifests_test.go, pkg/job/local_job.go, subsystem/manifests_test.go
OnPrem `s3wrapper/filesystem` returned paths are prefixed with "/" since #337
`ListClusterManifests` didn't support this scenario so I trimmed the received path.
Added also a full manifests operations subsystem which would run for k8s and onprem.
/cc @masayag @mhrivnak
=> OCPBUGSM-20982 Bugfix List manifests onprem

OWNERS, OWNERS_ALIASES
Removed @romfreiman from all alias groups, made it so @romfreiman is only an approver (in `OWNERS` directly, without a group), so he won't be randomly assigned to review PRs
=> NO-ISSUE - Remove romfreiman from OWNERS_ALIASES

internal/host/common.go, internal/host/validator.go, internal/installcfg/installcfg.go, internal/network/cidr_validations.go, internal/network/family_utils.go, internal/network/machine_network_cidr.go, models/cluster.go, models/cluster_create_params.go, models/cluster_update_params.go, restapi/embedded_spec.go, swagger.yaml
- Swagger regex validation changes
- Change log-sender command to add --net=host flag to allow the container to communicate on top IPv6 network
- Disable majority group validation for IPv6 (temporary).
- Adapt other validations to support IPv6
- Use OVNKubernetes network type
/cc @ronniel1 
/cc @empovit 
/cc @filanov
=> MGMT-2780 - Changes for IPv6, Phase 2

internal/bminventory/inventory.go
Disabled password-based login for the `core` user in the discovery ISO. SSH login with public key based authentication is still supported.
In the future a mechanism for a randomized, per-cluster password will be added.
Until it's implemented, we remove the ability to login with the hard-coded password with this PR.
=> MGMT-3153 - Disable password login for discovery ISO core user

models/cluster.go, models/cluster_create_params.go, restapi/embedded_spec.go, swagger.yaml
Must be added in order to make https://github.com/openshift/assisted-test-infra/pull/328 work
Prow already runs with OCP version 4.7
=> NO-ISSUE Add 4.7 support on swagger

Makefile
The older format created containerPorts
We need the ports exposed on the host
see
https://github.com/containers/podman/blob/master/docs/source/markdown/podman-pod-create.1.md#--publishport--p
for clarity also added relevant line from podman doc into Makefile.
this is needed at lest in order to make it work with podman 2.2.1 ...
=> fix podman pod create format

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/manifests/manifests.go, internal/manifests/manifests_test.go, pkg/s3wrapper/client.go, pkg/s3wrapper/filesystem.go, pkg/s3wrapper/filesystem_test.go, pkg/s3wrapper/mock_s3wrapper.go, subsystem/image_test.go
This will force the user to re-generate the image after making changes
Fixes [MGMT-2758](https://issues.redhat.com/browse/MGMT-2758)
cc @eranco74
=> MGMT-2758 Remove image from s3 when editing the discovery ignition

go.mod, go.sum, internal/hardware/mock_validator.go, internal/hardware/validator.go, internal/hardware/validator_test.go, internal/host/host.go, internal/host/host_test.go, internal/host/validator.go, models/cluster_update_params.go, models/disk.go, restapi/embedded_spec.go, restapi/operations/installer/update_cluster_parameters.go, subsystem/host_test.go, swagger.yaml
Each disk in the API now has an "eligibility" field composed of a boolean saying whether it's eligible and an array of reasons of why it's not eligible.
It is expected that the agent fill in that struct with why **it** thinks the disk is not eligible. The service will then unmarshal the inventory blob, and add its own reasons on top of the agent's reasons of why it thinks the disk is ineligible, then combine (`&&`) the final decision and write it all in the eligibility struct.
Older agents will not report that struct - so we'll see a nil struct from older agents, so the service uses that to detect that the agent is old and behaves as if the agent marked the disk as eligible. 
The reason for not doing the entire decision-making in the service is because the agent (unlike the service) has …
=> MGMT-3078 - Add disk filtering reasons to the API

internal/network/ntp_utils.go, internal/network/ntp_utils_test.go
Two manifests should be created and uploaded - one per role.
- masters-chrony-configuration.yaml
- workers-chrony-configuration.yaml
=> OCPBUGSM-21552 Add workers chrony manifest

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
RHCOS already have RHEL default pool 2.rhel.pool.ntp.org defined on
/etc/chrony.conf.
Removing default RHEL value but keeping NTP_DEFAULT_SERVER configuration
option.
Adding some more tests to AdditionalNtpSource assignment.
=> OCPBUGSM-21583 Remove RHEL default NTP source

internal/cluster/cluster_test.go, internal/host/connectivitycheckconvertor.go, internal/host/connectivitycheckconvertor_test.go, internal/host/validator.go, internal/network/connectivity_groups.go, internal/network/connectivity_groups_test.go, internal/network/machine_network_cidr.go, internal/network/machine_network_cidr_test.go, subsystem/cluster_test.go
Enable L2 connectivity check in IPv6 environments.
This change depends on the agent reporting L2 connectivity when the addresses are IPv6.
=> MGMT-3120 IPv6 connectivity check

Makefile
The service is going to be default with 1 replica in a development environment.
e2e and production should run with 3 replicas.
=> NO-ISSUE Default of a single service replica

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster_test.go, internal/cluster/transition.go, internal/host/host_test.go, internal/host/transition.go
We saw in some triaging tickets that when we retrieve failed cluster
logs we can get hosts that were part of the previous installation.
In addition, if a host was re-registered with the same dns, we will
get duplicated log files after the second installation.
To avoid this we can simply delete previous installation log files
just before starting the new installation.
=> MGMT-3295: On installation delete old cluster logs

Makefile
Added makefile targets for managing build, deploy and test.
Those targets should allow us to finalize the Prow job definition for assisted-service on openshift/release repo.
Once we have that in place, we could apply further changes to the Prow CI process for assisted-service via PRs to the assisted-service repo alone.
=> MGMT-2256: placeholder makefile targets for openshift ci

go.mod, go.sum, internal/host/freeaddressescmd.go
Sometimes the address scanning takes longer than the interval we wait between invocations. To avoid flooding the log with "container already exists" errors, we silently fail by manually checking if it exists and only running if it doesn't
=> MGMT-2470 silently fail if free addresses container already running

Makefile, subsystem/leader_test.go, tools/deploy_assisted_installer.py
Populated Makefile target for openshift ci tests.
Modified procedure for establishing kubeconfig location in leader_test.go to support kubeconfig location in openshift ci
=> MGMT-2256: openshift ci test

internal/controller/controllers/cluster_controller_test.go
Entrypoint for unit tests with a dummy test that demonstrate usage of
fake client to handle the cluster reconciler logic.
=> MGMT-3407: Add cluster controller test infra

internal/bminventory/mock_installer_internal.go, internal/cluster/mock_cluster_api.go, internal/connectivity/mock_connectivity_validator.go, internal/events/mock_event.go, internal/hardware/mock_validator.go, internal/host/installcmd.go, internal/host/installcmd_test.go, internal/host/mock_host_api.go, internal/host/mock_instruction_api.go, internal/isoutil/mock_isoutil.go, internal/metrics/mock_netricsManager_api.go, internal/network/mock_ntp_utils.go, internal/oc/mock_release.go, internal/versions/mock_versions.go, models/disk.go, pkg/executer/mock_executer.go, pkg/generator/mock_install_config.go, pkg/k8sclient/mock_k8sclient.go, pkg/leader/mock_leader_elector.go, pkg/ocm/mock_authorization.go, pkg/ocm/mock_pullsecret_auth.go, pkg/s3wrapper/mock_s3iface.go, pkg/s3wrapper/mock_s3manageriface.go, pkg/s3wrapper/mock_s3wrapper.go, restapi/embedded_spec.go, swagger.yaml
It's harder for the service to tell apart which disks are installation media and which are not (as opposed to the agent which does it by looking at disk partition information, which is not passed on to the service).
Added a new column to inventory disks that says whether they're installation media or not (ISO) so the agent can tell the service. (Will open a PR for the agent)
Service will no longer attempt to format bootable disks marked as installation media, as they're usually read-only and that results in confusing errors / events.
=> MGMT-3456 - Will not attempt to format bootable disks that look like installation media

internal/operators/lso/utils.go
This PR is for the fix in the `lsoSubscription` manifest. The data type of the `spec.channel` is "string" (string with the quotes). 
cc: @rollandf 
=> NO-ISSUE: Fixed typo in spec.channel in lsoSubscription manifest

Makefile, internal/bminventory/mock_installer_internal.go, internal/cluster/mock_cluster_api.go, internal/connectivity/mock_connectivity_validator.go, internal/events/mock_event.go, internal/hardware/mock_validator.go, internal/host/mock_host_api.go, internal/host/mock_instruction_api.go, internal/isoutil/mock_isoutil.go, internal/metrics/mock_netricsManager_api.go, internal/network/mock_ntp_utils.go, internal/oc/mock_release.go, internal/versions/mock_versions.go, pkg/executer/mock_executer.go, pkg/generator/mock_install_config.go, pkg/k8sclient/mock_k8sclient.go, pkg/leader/mock_leader_elector.go, pkg/ocm/mock_authorization.go, pkg/ocm/mock_pullsecret_auth.go, pkg/s3wrapper/mock_s3iface.go, pkg/s3wrapper/mock_s3manageriface.go, pkg/s3wrapper/mock_s3wrapper.go
`make lint` uses [golangci-lint](https://github.com/golangci/golangci-lint
) for linting purposes.
This utility auto detects (and silently skips) generated files. It detects them by looking at comments at the top of the file and looking for phrases that might indicate that those files are generated.
On the other hand, as of now, `make format` blindly runs `goimports` and `gofmt` on a bunch of folders, some of them containing, among other things, some generated files.
**There are two problems with the way things are right now:**
1) `goimports` automatically runs `gofmt` too so it's redundant to run both of them
2) If someone generates files and doesn't run `make format`, the resulting files will pass the CI (because they're ignored by `make lint` since they're generated). The next person …
=> NO-ISSUE - make format target shouldn't format anything the linter doesn't check

internal/cluster/transition.go, internal/ignition/ignition.go
- Monitor should allow single master node
- No need to add the assisted-marker since it conflicts with the current SNO patch allowing etcd to start with a single node
=> MGMT-3489 Support None HighAvailabilityMode 

internal/bminventory/inventory.go, internal/installcfg/installcfg.go, internal/installcfg/installcfg_test.go
This uses the same validation from [openshift/installer](https://github.com/openshift/installer/blob/879e9bb8c3895546e3ea7e49986f4670b754d4e3/pkg/validate/validate.go#L29-L47)
to ensure that the provided certificate is formed correctly.
Before this, if a malformed certificate was added to the install config
we would patch the config successfully but the install process would fail
Fixes [MGMT-2712](https://issues.redhat.com/browse/MGMT-2712)
=> MGMT-2712 Validate cert in install config overrides

internal/bminventory/inventory.go, internal/metrics/metricsManager.go, internal/metrics/mock_netricsManager_api.go
Added "assisted_installer_cluster_host_disk_sync_duration_ms" metric for fdatasync duration fetched from fio.
=> MGMT-3459 added metrics for disk sync duration

pkg/s3wrapper/file_cache.go, pkg/s3wrapper/file_cache_test.go
This will be needed when we start editing the minimal iso template
per cluster. The cache will ensure that we don't download the iso
template unless we need to.
Based heavily on the [installercache package](https://github.com/openshift/assisted-service/blob/4ec616b70864668d8b497e266de46dc0ba61acd8/internal/installercache/installercache.go).
I can make this generic using some kind of callback function for how to fetch a file on a cache miss, but wasn't sure if it was worth the effort given the actual caching mechanism is pretty slim.
cc @danielerez
=> MGMT-2977 Add a cache for downloading files from S3

internal/isoutil/isoutil.go, internal/isoutil/isoutil_test.go, internal/isoutil/mock_isoutil.go
This PR makes a few additions and enhancements to the isoutil handler that will be useful when creating and customizing the minimal iso.
Specifically:
- Re-adds some code to get an iso's volume identifier which was originally added in #645 and removed in #755
- We will use it to preserve the original volume identifier when repackaging the minimal iso template and the customized minimal iso.
- Adds an `ExtractedPath` method which allows us to get a reference to a file in the extracted iso without knowing about the working directory
- Enhances the `Create` method so that we don't have to provide a size
- This size value doesn't determine the final image size, but is used to truncate the initial file. This value would be relevant if we were writing to a particular partition on a device, but …
=> MGMT-2977 Enhancements to isoutil

internal/host/fioperfcheckcmd.go, internal/host/installcmd.go, internal/host/installcmd_test.go
"flag" package in golang can accept a boolean input arguement in 2 format:
1) just an arguement without any value, the flag will be set to True (preferred)
2) <arguement>=<value> - flag will be set to value
if the argument is used in the following way:
<arguement> <value>
then the flag will be set to true, but all the rest of the input arguements will not be processed at all
=> MGMT-3568 - fix formatting of boolean input arguments in Install command

internal/hardware/validator.go, internal/hardware/validator_test.go
This check is no longer needed as we can assume that all inventories have been updated by now. If somehow ancient inventories from old versions somehow show up, their disks will show up as ineligible. This is unlikely to happen.
=> MGMT-3327 - Remove backwards compatibility code for listing ineligible disks

cmd/main.go, internal/isoeditor/rhcos.go, internal/isoeditor/rhcos_test.go, internal/isoutil/isoutil.go, internal/isoutil/mock_isoutil.go, pkg/s3wrapper/client.go, pkg/s3wrapper/client_test.go, pkg/s3wrapper/filesystem.go, pkg/s3wrapper/filesystem_test.go, pkg/s3wrapper/mock_s3wrapper.go, pkg/s3wrapper/util.go
- Added an iso editor that uses the isoutil package to modify the rhcos iso..
It currently implements creating the minimal iso template which
removes the rootfs and adds a reference to the url where the rootfs
should be downloaded ([MGMT-3535](https://issues.redhat.com/browse/MGMT-3535)).
- Boot files upload logic resides on S3Client (UploadBootFiles func).
Hence, in order to avoid re-downloading RHCOS image, integrated
minimal iso creation and upload in uploadBootFiles.
- Extracted upload logic from rhcosEditor into S3Client in order
to avoid cyclic dependency (i.e. so the editor won't import the client).
- Within boot files upload flow, use downloaded RHCOS image to create
the minimal ISO template.
- Uploaded the template to the public S3 bucket if doesn't exist.
=> MGMT-2976 create and upload minimal iso template

pkg/s3wrapper/client.go, pkg/s3wrapper/file_cache.go, pkg/s3wrapper/file_cache_test.go, pkg/s3wrapper/filesystem.go, pkg/s3wrapper/mock_s3wrapper.go
The minimal iso template is stored in the public S3 bucket so we need to be able to download it.
Currently the s3 client `Download` function only downloads from the non-public bucket and the boot files (the only objects we store in the public bucket) have a specific download function which is not a good match for a general-purpose s3 object cache.
=> MGMT-2977 Allow downloading and caching from the public S3 bucket

internal/bminventory/inventory_test.go
It took me a bit to figure out where `bm` was created for these tests that used a context related to kube jobs.
We don't actually use kube jobs for anything anymore and this was the only context we ran these tests in.
Ignore whitespace when reviewing :wink:
=> NO-ISSUE Removes some extra whitespace and contexts from tests

internal/isoeditor/rhcos.go, internal/isoeditor/rhcos_test.go
This specifically signals to coreos that the rootfs is included in the iso which, in the case of the minimal iso, it is not.
=> MGMT-2977 Remove coreos.liveiso kernel param for the template minimal iso

internal/hardware/validator.go, internal/host/host.go, internal/host/host_test.go, internal/host/installcmd.go
`GetHostValidDisks` had a surprising behavior of returning an error when there are no disks, instead of just returning an empty list and leaving it to the caller to decide whether that's an error or not.
Changed it so it only returns an error if the host inventory JSON is invalid, and changed all callers to behave properly when it returns an actual error.
This behavior caused a bug in these lines as part of the `UpdateInventory` function:
https://github.com/openshift/assisted-service/blob/b18e08ae96844c5c2743c1a27fc0af7362ed7834/internal/host/host.go#L297-L300
Those lines assumed that an error means an error and not just no-eligible disks - so the entire `UpdateInventory` call failed. Instead it should not fail and that scenario should be reflected to the user via the "minimum disks for …
=> MGMT-3630 - Fix missing validation for minimum host valid disks

internal/host/host.go, internal/host/transition_test.go
Worker nodes might need to wait longer than master nodes for the ignition since they get only after the master nodes formed a cluster.
24 hours should be more than enough for the worker to get the ignition from the MCS
=> MGMT-3446 Update Waiting for ignition timeout to 24 hours

Makefile
deploy-onprem is timing out waiting for installer to pass health
check. The installer container at times is waiting to establish
a db connection. CI logs show the installer does eventually
establish a connection to db and starts up:
http://assisted-jenkins.usersys.redhat.com/job/assisted-service/job/master/4699/
=> NO-ISSUE Extend on-prem installer startup timeout from 1m to 3m

internal/bminventory/inventory_test.go, internal/common/version.go, internal/ignition/ignition.go, internal/installcfg/installcfg.go
This will cause 4.7 clusters to have a Provisioning CR and for the baremetal-operator to be more enabled.
=> MGMT-2662 re-enable the baremetalProvisioningConfig

internal/host/transition.go, internal/host/transition_test.go
The statusInfoInstallationInProgressWritingImageToDiskTimedOut message should only be set if the transition that caused it is the "timeout" transition.
Hosts that were in the middle of writing to disk while the cluster entered an error state looked like they were timing out - even though what actually happened is they simply entered the error state like the rest of the hosts in the cluster. A wrong `if` statement in the post-refresh function wrongly assumed it was called from a timeout transition, although it was actually called from the "move all hosts to error because cluster is in error" transition.
=> MGMT-3763 - Fix misleading host progress error when cluster enters error state

internal/host/host.go, internal/metrics/metricsManager.go, internal/metrics/mock_metrics_manager_api.go, subsystem/metrics_test.go
The case we are trying to catch is if a host validation was went to
`failed` state after being in `succeed` state.
=> MGMT-3658: Generate event/metric in case an host validation is changing.

internal/bminventory/inventory.go, internal/host/transition.go
Reformat event message and add disk and user details 
`Host name missing in event :"error Failed to register host: error creating host metadata: Host is required to be booted from disk"`
=> MGMT-2622 - Add disk and user to event when booted into the ISO instead of into the installed OCP on disk

cmd/main.go, internal/host/hostcommands/install_cmd.go, internal/host/hostcommands/install_cmd_test.go, internal/host/hostcommands/instruction_manager.go, internal/host/hostcommands/logs_cmd.go, openshift/template.yaml, tools/deploy_assisted_installer_configmap.py
Use a singular agent image from configmap AGENT_DOCKER_IMAGE instead of
- CONNECTIVITY_CHECK_IMAGE
- INVENTORY_IMAGE
- FREE_ADDRESSES_IMAGE
- DHCP_LEASE_ALLOCATOR_IMAGE
- API_VIP_CONNECTIVITY_CHECK_IMAGE
- NTP_SYNCHRONIZER_IMAGE
- FIO_PERF_CHECK_IMAGE
=> NO-ISSUE Merge all agent sub-images into one

go.mod, go.sum
Previously go-diskfs would leak a temp dir with the entire iso contents
every time we built a new iso. This update includes my fix for the issue
in https://github.com/diskfs/go-diskfs/pull/91
cc @danielerez
=> NO-ISSUE Update go-diskfs to include temp dir leak fix

internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, internal/controller/controllers/common.go
Support cluster creation with ClusterDeploymnet definition
Missing variables from AgentEnvSpec
Currently putting all validtions, status and status info under conditions UnreachableCondition later need to move it to proper conditions or other variables that will store this data
=> MGMT-3721 ClusterDeployments support creation

pkg/s3wrapper/client.go, pkg/s3wrapper/client_test.go
Previously this would return the local url if S3EndpointURL was set
to the real aws endpoint leading to a failure
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1923245
cc @danielerez @lalon4
=> MGMT-3872 Fix s3 url for boot files

internal/host/host.go, internal/metrics/metricsManager.go, internal/metrics/mock_metrics_manager_api.go, subsystem/cluster_test.go, subsystem/day2_cluster_test.go, subsystem/metrics_test.go, subsystem/utils_test.go
The case we are trying to catch is if a host validation was went to
`failed` state after being in `succeed` state. Another event will be
sent once the validation is fixed.
=> MGMT-3658: Generate event/metric in case an host validation is changing. (#952)

cmd/main.go, internal/ignition/ignition_test.go, pkg/job/local_job.go, pkg/s3wrapper/filesystem.go, pkg/s3wrapper/filesystem_test.go
I'm also not sure how this worked previously. It looks like the s3 client used when uploading the generated files would have had a separate data directory form the one we then would have used to download the files.
It feels like it's either broken now, or this will break something, but I'm also not sure how to test this.
@djzager @mhrivnak can you help out here (or suggest someone who might be able to)?
=> NO-ISSUE Don't recreate the s3 client for local ignition generator

cmd/main.go, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/isoeditor/factory.go, internal/isoeditor/mock_factory.go, internal/isoeditor/rhcos_test.go, pkg/s3wrapper/client.go, pkg/s3wrapper/client_test.go, pkg/s3wrapper/filesystem.go, pkg/s3wrapper/filesystem_test.go, pkg/s3wrapper/util.go
This commit uses a buffered channel as a semephore to ensure
we're only running 10 minimal iso generation processes concurrently
by default.
To do this the isoeditor factory API changes implement a WithEditor
function that is provided a callback function to run when an editor
is available to use.
WithEditor will block the calling thread until an editor is available
or the provided context times out.
=> MGMT-3844 Limit concurrent minimal iso generations

go.mod, go.sum
This will be used in [MGMT-3979](https://issues.redhat.com/browse/MGMT-3979) to find where we need to write
the ignition and ramdisk files without unpacking the iso locally
Fixes [MGMT-3980](https://issues.redhat.com/browse/MGMT-3980)
cc @danielerez
=> MGMT-3980 Update go-diskfs to expose file offset in iso

internal/metrics/recorder.go
impacts on the metrics dashboards: https://coreos.slack.com/archives/C01FJCM6MBQ/p1612876189066400
=> OCPBUGSM-24603 Remove the cluster-id from http request/response metrics

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/isoeditor/mock_editor.go, internal/isoeditor/rhcos.go, internal/isoeditor/rhcos_test.go
In order to support the http proxy functionality, added the proxy
config to the custom RAM disk created as part of the minimal ISO.
rootfs image is fetched using curl in the dracut script[2],
so we can add the proxy config to the global curl config file (/root/.curlrc).
Another solution mentioned in [2] is to add the proxy env vars to
/etc/systemd/system/coreos-livepxe-rootfs.service.d/10-proxy.conf
[1] https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core[…]usr/lib/dracut/modules.d/35coreos-live/coreos-livepxe-rootfs.sh
[2] https://github.com/coreos/fedora-coreos-tracker/issues/744#issuecomment-778231239
=> MGMT-3999 http proxy support for minimal-iso

internal/host/host.go, internal/host/host_test.go
Having empty measurements is normal. But in that case, we would want to avoid printing just zeroes.
/cc @gamli75 @lalon4
=> OCPBUGSM-25004 Avoid printing empty image status measurements

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
[OCPBUGSM-23207](https://issues.redhat.com/browse/OCPBUGSM-23207) - Fix GenerateClusterISO sometimes return null in certain fields
https://bugzilla.redhat.com/show_bug.cgi?id=1916661
=> OCPBUGSM-23207 - Fix GenerateClusterISO sometimes return null 

internal/isoeditor/rhcos.go, internal/isoeditor/rhcos_test.go
Added proxy env vars in capital letters as well, per suggested improvement:
https://github.com/openshift/assisted-service/pull/1075#discussion_r576656603
=> MGMT-3999 minimal-iso proxy - capital env vars

internal/host/validator.go, subsystem/host_test.go
The 'First success bad bandwidth' host subsystem test used `common.TestImageStatusesSuccess` and changed its download rate for that test.
Afterward, other tests using the same global variable had a malformed download rate.
The flakiness was caused because the tests are running in random order.
In order to fix that bug, a new `ContainerImageAvailability` object was created with a bad download rate.
Fixes https://github.com/openshift/assisted-service/pull/1086.
Thanks, @rollandf for finding the bug.
=> OCPBUGSM-25012 Fixing bad bandwidth subsystem test

internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go
Until [HIVE-1383](https://issues.redhat.com/browse/HIVE-1383) is resolved OCP version is hard coded.
4.8 for SNO, 4.7 for other clusters.
=> MGMT-4168 SNO cluster will be created automatically with OCP 4.8

internal/bminventory/inventory_test.go
When unit tests where running with `WITH_AMS_SUBSCRIPTIONS="True"` the following tests failed:
```
Summarizing 6 Failures:
[Fail] TestRegisterCluster [It] success 
/home/jdzon/projects/assisted-service/pkg/ocm/mock_accounts_mgmt.go:41
[Fail] TestRegisterCluster [It] UserManagedNetworking default value 
/home/jdzon/projects/assisted-service/pkg/ocm/mock_accounts_mgmt.go:41
[Fail] TestRegisterCluster [It] UserManagedNetworking non default value 
/home/jdzon/projects/assisted-service/pkg/ocm/mock_accounts_mgmt.go:41
[Fail] TestRegisterCluster NTPSource [It] NTPSource default value 
/home/jdzon/projects/assisted-service/pkg/ocm/mock_accounts_mgmt.go:41
[Fail] TestRegisterCluster NTPSource [It] NTPSource non default value 
/home/jdzon/projects/assisted-service/pkg/ocm/mock_accounts_mgmt.go:41 …
```
=> MGMT-3137 Fix bminventory unit test with AMS mock

internal/bminventory/inventory.go, internal/ignition/ignition.go, internal/ignition/ignition_test.go
This will allow us to minimize changes when updating to newer ignition
versions in the future.
The strategy will always be to parse up to the latest supported
version then manipulate types that will not change in future minor
ignition versions (File, Config, Unit, etc).
Ideally the only place that will require a change will be where we
are specifically dealing with older versions.
This should address https://github.com/openshift/assisted-service/pull/1109#pullrequestreview-592663578
cc @ronniel1
=> MGMT-4191 Clean up ignition package naming

go.mod, go.sum, internal/isoeditor/factory.go, internal/isoeditor/rhcos.go, internal/isoeditor/rhcos_test.go, internal/isoutil/isoutil.go, internal/isoutil/isoutil_test.go, internal/isoutil/mock_isoutil.go
Before this change we would unconditionally extract isos to a
random directory in /tmp and would create new iso files directly
in /tmp
Now that base directory is configurable with the WORKSPACE_BASE_DIR
environment variable. The idea is that we may want this to be a PV
so we are not using the container filesystem.
=> MGMT-3970 Make the iso editor scratch space base dir configurable

pkg/ocm/accounts_mgmt.go
=> NO-ISSUE: Fixing a typo in OCM Delete subscription logs.

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/common.go, internal/cluster/installer_test.go, internal/cluster/registrar.go, internal/cluster/registrar_test.go, internal/cluster/transition_test.go, internal/cluster/validator.go, internal/common/db.go, internal/host/hostcommands/logs_cmd.go, internal/host/validator.go, subsystem/kubeapi_test.go
Add functions
- `GetClusterFromDB`
- `GetClusterFromDBWithoutDisabledHosts`
- `GetClusterFromDBWhere`
- `LoadHostsFromDB`
Introducing two new boolean types to be used for queries:
- `EagerLoadingState` including `UseEagerLoading`, `SkipEagerLoading`
- `DeleteRecordsState` including `IncludeDeletedRecords`, `SkipDeletedRecords`
=> NO-ISSUE Organize DB preloads with common functions

internal/bminventory/inventory.go, internal/constants/scripts.go, internal/host/hostcommands/install_cmd.go
The discovery ignition file will contain nmconnection files for all of the nodes.
This patch is responsible to copy only the relevant files for to the current host to the network-manager config directory.
Therefore the service to perform that action will run only once and before network manager service.
The destination folder on the host will be `./NetworkManager/system-connections/static_connection.nmconnection`
Depends on Depends on https://github.com/openshift/assisted-service/pull/1143
=> MGMT-4090 Use nmconnection settings relevant to current host

internal/controller/controllers/clusterdeployments_controller.go
Since the host prefix is an optional parameter we don't want to update it
if not provided.
=> MGMT-3598: clusterdeployments_controller.go: Update host prefix only if > 0

internal/isoeditor/rhcos.go, internal/isoeditor/rhcos_test.go
* Added 'assisted_installer_custom.img' file to images folder.
* Modified config files in the template to include it in initrd.
=> MGMT-3976: Embed ramdisk placeholder in template

cmd/main.go, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/registrar.go, internal/cluster/transition_test.go, internal/common/common_unitest_db.go, internal/common/db.go, internal/events/event.go, internal/events/event_test.go, internal/events/mock_event.go, internal/host/host_test.go, internal/host/monitor_test.go, internal/host/transition_test.go, internal/migrations/migrations_test.go, internal/network/manifests_generator_test.go
* Add `PrepareAssistedTables` common function to be called from main and from UT.
* Add `GetClustersFromDBWhere` and `LoadTableFromDB` functions.
* Moving `Event` db model to `common` package.
* Adding `filters based on openshift cluster ID` unit test.
=> NO-ISSUE Organize common db functions

internal/host/host.go, subsystem/metrics_test.go
We currently have some cases in which we don't update validations results
in DB, therefore, we keep looking at the "old" validations status which
never change and keep generating events/metrics.
=> MGMT-4372: Comment events/metrics generation on host validations changes.

Makefile
This would improve the delete-test Makefile target to always deploy a newer
service without needing to clear all the deployment by running
clear-deployment Makefile target.
/cc @filanov
=> NO-ISSUE Delete assisted-service pod before deploy-test

hack/get_ocp_versions_for_testing.sh
readlink command in MAC works different and has no -f flag 
so using python might  be overkill but it allows us to  run the build locally 
(I understand that we are working with the skipper but ....)
=> NO-ISSUE - Support make build without the skipper on MAC

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/common/db.go
In order to allow the discovery image to be re-generated, an indication
is added to describe the state of it.
When the discovery image is generated, the indicator will be set to false
and only after successful image generation it will be set to true.
The indicator will prevent the case in which a failed attempt to generate
an image will result with storing the image create parameters on the
cluster. In that case, the next attempt to generate the ISO will falsely
present as the image hasn't been changed without considering the new
parameters of the cluster.
=> MGMT-4339 Add indication for discovery image generation

cmd/main.go, pkg/s3wrapper/client.go, pkg/s3wrapper/client_test.go, pkg/s3wrapper/filesystem.go, pkg/s3wrapper/filesystem_test.go, pkg/s3wrapper/mock_s3wrapper.go, pkg/s3wrapper/util.go, pkg/s3wrapper/util_test.go
On service startup, need to ensure that the minimal ISO templates
aren't stale. Hence, using the following approach to upload latest version:
* Fetch template versions file from s3/fs that includes the latest revision number.
* If version is lower than the one hardcoded in code, force upload (overwrite) template.
* Update version in the file to latest (or create the file if doesn't exist).
=> MGMT-4165 handle minimal iso templates update

openshift/template.yaml
At least until we can add it to the parameters on the deploy side
=> MGMT-4274 Make AUTH_TYPE optional

internal/isoeditor/rhcos.go, internal/isoeditor/rhcos_test.go, internal/isoutil/isoutil.go, internal/isoutil/mock_isoutil.go
When customizing an iso for a specific cluster:
* Discover the offsets of the ramdisk and ignition placeholders (using initrd metadata in header's system area).
* Overwrite with the custom data for the cluster.
=> MGMT-3979: Embed ignition and ramdisk into cluster iso

internal/cluster/cluster_test.go, internal/cluster/statemachine.go, internal/cluster/transition_test.go, internal/cluster/validation_id.go, internal/hardware/validator.go, internal/host/host_test.go, internal/host/hostutil/test_utils.go, internal/host/monitor_test.go, internal/host/statemachine.go, internal/host/transition_test.go, internal/host/validation_id.go, internal/operators/builder.go, internal/operators/cnv/cnv_operator.go, internal/operators/cnv/utils.go, internal/operators/manager_test.go, models/cluster_validation_id.go, models/host_validation_id.go, restapi/embedded_spec.go, subsystem/operators_test.go, swagger.yaml
This PR provides initial validation and manifest generation for cnv operator.
=> MGMT-4079 Deploy cnv

internal/host/host.go, internal/host/host_test.go, internal/host/refresh_status_preprocessor.go, internal/host/transition.go, internal/host/transition_test.go
On each host status refresh, we will now update the DB with the new
validations results if they changed regardless of the matching
transition.
=> MGMT-4414: Adding DB update for each change in validations status.

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/isoeditor/rhcos.go, internal/isoeditor/rhcos_test.go
* Upon adding a custom RAM disk, validate that the placeholder embdeed
in the minimal iso template is large enough to accommodate the archive.
* Added an avent for generate cluster minimal iso failure.
=> MGMT-4365 validation for custom ramdisk size

internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, internal/controller/controllers/installenv_controller.go, internal/controller/controllers/installenv_controller_test.go
Update cluster from InstallEnv when setting Proxy and NTP conficution
Those parameters are reletaed only to discovery phase so they should not affect the cluster
Instead of having a ping-pong between cluster deployment controller and install env controller it is done once via InstallEnv controller.
Later when image will be separate from the cluster it will make things simple.
=> MGMT-4468 update cluster from installenv

models/monitored_operator.go, restapi/embedded_spec.go, swagger.yaml
This PR changes the prefix_name of the MonitoredOperator to the
subscription_name, which reflect the meaning of the attribute clearer.
=> MGMT-4204 Rename prefix_name to subscription_name

pkg/auth/auth_handler_test_utils.go, pkg/auth/auth_suite_test.go, pkg/auth/authenticator.go, pkg/auth/authenticator_test.go, pkg/auth/local_authenticator.go, pkg/auth/local_authenticator_test.go, pkg/auth/none_authenticator.go, pkg/auth/rhsso_authenticator.go
This uses ecdsa keys to keep the resulting token signing string small.
This will make it a better fit for using in urls later.
~~This *can* be merged as is, but I'm debating adding the token creation here as well.
Let me know if you think we'd rather merge this separately.~~
Did token creation in https://github.com/openshift/assisted-service/pull/1269
cc @nmagnezi @danielerez @mhrivnak @avishayt
=> MGMT-4275 Add local JWT authentication

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, pkg/ocm/accounts_mgmt.go, pkg/ocm/mock_accounts_mgmt.go, subsystem/ams_subscriptions_test.go, subsystem/wiremock_stubs.go
UI is using the subscription `display_name` in the subscription because
filtering the cluster list is done using this field.
On cluster registration:
* add cluster name on subscription creation.
On cluster update:
* update the cluster name in the subscription if it was changed in
the service.
=> MGMT-4442: Added cluster name to OCM subscription.

Makefile
https://github.com/openshift/assisted-service/pull/1230 omitted the operator-bundle from build-all which caused
the master builds to fail because it was attempting to publish
an image that hadn't been build.
=> MGMT-4428 Adds operator-bundle to build-all and publish

internal/cluster/cluster.go, internal/cluster/refresh_status_preprocessor.go, internal/cluster/validator.go, internal/hardware/validator_test.go, internal/host/host_test.go, internal/host/hostutil/test_utils.go, internal/host/monitor_test.go, internal/host/refresh_status_preprocessor.go, internal/host/transition_test.go, internal/host/validator.go, internal/operators/api/api.go, internal/operators/cnv/cnv_operator.go, internal/operators/lso/ls_operator.go, internal/operators/manager.go, internal/operators/mock_operators_api.go, internal/operators/ocs/ocs_operator.go, subsystem/cluster_test.go, subsystem/host_test.go, subsystem/ipv6_test.go, subsystem/metrics_test.go
This PR updates the CPU and memory validations for the host to add the resources request for the enabled operators to check that the cluster's CPU and usable memory are sufficient to deploy the selected operators (LSO, CNV or OCS) in that node.
@machacekondra @masayag @pkliczewski @jakub-dzon @gamli75 can you take a look in the meanwhile?
/Jordi
=> MGMT-4066 Add enabled operator CPU and memory requirements to host validation

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/validator.go, internal/network/machine_network_cidr.go, internal/network/machine_network_cidr_test.go, subsystem/cluster_test.go, subsystem/metrics_test.go, subsystem/utils_test.go
Cluster update should not validate that machine network cidr belong to once of the host.
Those network validations are done as part of the async validations anyway
=> MGMT-4219: update cluster: skip cidr validations 

internal/bminventory/inventory.go, internal/cluster/auth.go, internal/cluster/auth_test.go, pkg/auth/local_authenticator.go
This PR implements the token generation side of the new local auth for agents.
Instead of embedding the pull secret auth into the agent command in the discovery ignition this PR switches what we use based on the the authentication type.
Behavior is unchanged with rhsso and none authentication types, but will require `EC_PRIVATE_KEY_PEM` to be set to use local auth.
~~Built on https://github.com/openshift/assisted-service/pull/1228 which adds the local auth type.~~
Merged
=> MGMT-4471 Generate an agent auth token for local auth

config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
The operator currentlty mentions the need of a PVC for postgress but it doesn't
mention that it requires another one for the fs storage. This commit adds that text to
the docs
=> NO-ISSUE: Document the need for an extra PVC

internal/bminventory/inventory_test.go, internal/operators/cnv/cnv_operator.go, internal/operators/cnv/manifest.go, internal/operators/lso/ls_operator.go, internal/operators/lso/manifest.go, internal/operators/manager.go, internal/operators/ocs/manifest.go, internal/operators/ocs/ocs_operator.go
This PR fill the monitored_operator data with subscription_name and
namespace data.
Signed-off-by: Ondra Machacek <omachace@redhat.com>
=> MGMT-4204 Return subscription data in monitor operators

Makefile
The operator should only include the versions in
default_ocp_versions.json and not include experimental ISOs used
in development that are included by hack/get_ocp_versions_for_testing.sh.
=> MGMT-4450 Operator bundle should not include experimental ISOs

subsystem/metrics_test.go
When the cluster-id was removed from the metrics, some tests where
commented to not delay the fix merge, those tests are now fixed.
=> MGMT-4448: Updating host validations metrics test.

config/default/assisted-service-patch-init-containers.yaml
Changes assisted-service init container base image to ubi-minimal from
busybox.
The init container waits for the assisted-service service to be
created.
Also change service checks to using "getent hosts" from "nslookup".
nslookup is not available in ubi.
=> OCPBUGSM-25828 Use ubi for assisted-service init container

config/default/assisted-service-patch-iso-image-type.yaml, config/default/kustomization.yaml, docs/operator.md
Sets ISO_IMAGE_TYPE=minimal-iso for operator deployments through
kustomize.
Also updates the documentation with an example on how
to change values of environment variables through Subscription
config.
Contains additional updates to operator.md to include
Hive as prerequisite and installing the operator through
the command line using Subscriptions.
Reorganized the default kustomization.yaml to delineate
what is required and what is optional.
=> MGMT-4382 Sets minimal-iso as the default for operator and updates docs

Makefile
Unit tests that make use of the postgres database container are
typically very slow because that postgres container uses the disk
for storage. 
This commit mounts a tmpfs in the container in the directory where this postgres image
stores its data, causing significant performance improvement relative to
a regular disk filesystem
=> MGMT-4502 - Improve unit test performance by putting DB data in RAM rather than disk

Dockerfile.assisted-service
There is no need to re-generate swagger, the latest swagger is already copied as part of `COPY . .`
Moved the Python3 build to its own stage to improve caching a little bit
If everything went right this PR shouldn't change anything except for performance, slightly
=> MGMT-4501 - Remove unnecessary steps from Dockerfile

hack/generate.sh
Using the quay.io image
/cc @YuviGold @omertuc
=> NO-ISSUE: use swagger-codegen-cli from quay.io instead of docker hub

cmd/main.go, internal/controller/controllers/installenv_controller.go, internal/controller/controllers/installenv_controller_test.go, subsystem/kubeapi_test.go
Adds ImageType Config to InstallEnvReconciler.
Same as in done in the operator, the config will read env variable `ISO_IMAGE_TYPE` which can
either be: `minimal-iso` (default) or `full-iso`
=> MGMT-3811 KubeAPI Minimal ISO support

internal/bminventory/inventory.go
In order to display the original validation error message
we need to call secretValidationToUserError on the original
error, otherwise generic and non-informative error will be
returned.
=> OCPBUGSM-25786: Fixed pull secret validation message

OWNERS_ALIASES
This will prevent him from being automatically selected for PR review
=> NO-ISSUE - Remove erezalster from OWNERS

Jenkinsfile
We've recently seen some issues with the registry.svc.ci.openshift.org registry. It seems that someone might have logged in to those registries in some job and it affected future CI jobs that came after it. This commit makes it so there's a more 'clean slate' before trying to run the CI
=> NO-ISSUE - attempt to logout from problematic registries before running CI

internal/hardware/validator.go, internal/hardware/validator_test.go, internal/host/host_test.go, internal/host/hostutil/test_utils.go, internal/host/transition_test.go, internal/host/validator.go, internal/operators/cnv/cnv_operator.go, pkg/conversions/conversions.go
This PR moves existing size conversion functions to a separate package to avoid cyclic imports in other changes.
=> Moving conversion helpers to separate package

config/onprem-iso-config.ign, config/onprem-iso-fcc.yaml, onprem-environment
This is causing onprem periodic ci checks to fail with
FATA[0000]/go/src/github.com/openshift/origin/cmd/main.go:148 main.main.func1()
failed to create authenticator error="invalid authenticator type "
=> NO-ISSUE: AUTH_TYPE missing in onprem and liveiso configurations

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
The controller keeps updating host installation progress until all hosts
are installed or they are all in error.
In case the user is resetting the cluster, there is a time window in
which the controller still runs and continues to update the hosts,
therefore events are spammed until k8s kills the controller once 2
masters aren't part of the cluster anymore.
=> MGMT-4513: Don't do anything if we update host with unchanged info.

Dockerfile.assisted-service-build
/cc @rwsu
EDIT: I pinned it to 1.4.2 instead of 1.5.0 by mistake, but turns out it was a lucky mistake because 1.5.0 is broken (`make operator-bundle` doesn't work with 1.5.0 right now), so I'm keeping it 1.4.2 for now
=> NO-ISSUE - Operator SDK should have a pinned version to make sure the environment is consistent across dev machines

Dockerfile.bundle, Makefile
and build of bundle-image.
Previously we were downloading from latest. The latest URL has
disappeared and returns "Not Found" as the contents of the file
from curl.
This PR also turns back on bundle image build and publish.
=> NO-ISSUE Download specific version of operator-sdk, turn on publish

models/cluster_host_requirements_details.go, restapi/embedded_spec.go, swagger.yaml
Changing `cluster-host-requirements-details'` `ram_gib` to `ram_mib` because CNV has its requirements defined in MiB (150 MiB for master and 360 MiB for worker).
=> MGMT-4531 change ram_mib to ram_gib in cluster-host-requirements-details

config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
* Sets icon to generic Red Hat logo until official version is provided.
* Adds support and repository annotation.
* Adds maintainer section.
* Documents ClusterDeployment CRD from Hive as a prerequisites.
=> NO-ISSUE Add icon, additional metadata and annotations to operator CSV

internal/host/hostcommands/container_image_availability_cmd.go, internal/host/hostcommands/container_image_availability_cmd_test.go, internal/host/hostcommands/install_cmd.go, internal/host/hostcommands/install_cmd_test.go, internal/host/hostcommands/instruction_manager_test.go, internal/oc/mock_release.go, internal/oc/release.go, internal/oc/release_test.go
Extract must-gather image URL from release or release mirror and
send it to installer so that must-gather doesn't have to talk to
the cluster in order to extract the image, and won't use the
global default. Hopefully, it will allow must-gather to run on
broken clusters.
=> MGMT-4480 Get must-gather image from release

config/default/kustomization.yaml, config/default/ui-patch-init-containers.yaml
The service can potentially be installed in any namespace. The
proxy-pass URL in the ocp-metal-ui ConfigMap needs to be updated
if the operator is installed in a namespace not named
"assisted-installer". This patch creates init containers to update
the proxy-pass.
=> NO-ISSUE Update ocp-metal-ui proxy-pass URI with service route URI in operator

docs/user-guide/restful-api-guide.md
The static network config API expects a network_yaml along with a mapping file in order to set the static network configuration.
The example is updated accordingly.
=> MGMT-4517 Update static network config in  RESTful API user guide

Makefile, tools/deploy_assisted_installer.py
Assisted-service needs to be deployed without auth before running
kube-api tests. Therefore it will be run after all the other tests
finished running and the service redeployed with the proper config.
=> MGMT-4217: Run subsystem test for kube-api after rest-api tests

internal/controller/api/v1alpha1/installenv_types.go, internal/controller/config/crd/bases/adi.io.my.domain_installenvs.yaml
Not every cluster will have ignitionConfigOverride.
Therefore, this should be an optional parameter.
=> MGMT-4628 InstallEnv ignitionConfigOverride should be optional

internal/host/host.go
Controller will send joined state for hosts that joined but are not ready yet. That's why we need to allow joined state for all the types.
Currently we are missing joined state in bootstrap role and workers and it spams logs.
=> MGMT-4558 adding joined state for workers and bootstrap

docs/user-guide/install-customization.md
The folder name should be provided as a parameter to the request according to the API.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1939853
=> NO-ISSUE Update create manifests example

internal/manifests/manifests.go, internal/manifests/manifests_test.go, models/create_manifest_params.go, restapi/embedded_spec.go, subsystem/manifests_test.go, swagger.yaml
- Manifests provided by the user should have one of the following extensions: json, yaml or yml.
- Manifests content should be a valid JSON or YAML format.
=> MGMT-4576 Check manifests content on creation

Makefile
Ref: https://issues.redhat.com/browse/MGMT-4386
Instead of setting the RHCOS_BASE_ISO value from user env var or hardcoding it, the value is extracted from the OPENSHIFT_VERSIONS. For on-prem, the latest value of rhcos image is extracted from the OPENSHIFT_VERSIONS.
=> MGMT-4386: Use latest available rhcos for onprem

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/validations/validation_test.go, internal/cluster/validations/validations.go
In deployments where IPv6 support is turned off, block
IPv6 addresses and CIDRs in input fields.
=> MGMT-4568 Block IPv6 input when not supported

internal/manifests/manifests.go, internal/manifests/manifests_test.go, models/create_manifest_params.go, restapi/embedded_spec.go, swagger.yaml
According to the manfiest API the target folder for the manifest should
be provided via a dedicated parameter. Thefore the file-name needs to be
verified not to include it.
=> OCPBUGSM-26541 Verify file name does not include folder

cmd/main.go
`CHECK_CLUSTER_VERSION` is a variable defined in the service configmap to toggle whether an installation needs to monitor the `CVO` operator.
This variable is being used by `InstructionConfig` and `OperatorsManager` components. The main process needs to pass the variable value to the other components.
=> MGMT-3431 Bugfix pass CHECK_CLUSTER_VERSION value to other components

cmd/main.go, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/hardware/mock_validator.go, internal/hardware/validator.go, internal/hardware/validator_test.go, internal/hardware/virt/virt.go, internal/host/host.go, internal/host/host_test.go, internal/host/monitor_test.go, internal/host/transition_test.go, internal/host/validator.go, internal/operators/api/api.go, internal/operators/api/mock_operator_api.go, internal/operators/cnv/cnv_operator.go, internal/operators/lso/ls_operator.go, internal/operators/manager.go, internal/operators/manager_test.go, internal/operators/mock_operators_api.go, internal/operators/ocs/ocs_operator.go, pkg/conversions/conversions.go, subsystem/cluster_test.go
This PR introduces following changes:
- Implementation of the `/clusters/{cluster_id}/host-requirements` handler;
- Validation refactored to use the same code as the mentioned endpoint;
- Simplified OLM Generic Operator API - separate worker/master CPU/RAM/Disk requirements methods replaced by one (`GetHostRequirementsForRole`)
=> MGMT-4531 cluster host requirements handler

cmd/main.go, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/auth.go, internal/cluster/auth_test.go, internal/gencrypto/gencrypto_suite_test.go, internal/gencrypto/keys.go, internal/gencrypto/token.go, internal/gencrypto/token_test.go, pkg/auth/auth_handler_test_utils.go, pkg/auth/authenticator.go, pkg/auth/authenticator_test.go, pkg/auth/local_authenticator.go, pkg/auth/local_authenticator_test.go, pkg/auth/none_authenticator.go, pkg/auth/rhsso_authenticator.go, restapi/configure_assisted_install.go, restapi/embedded_spec.go, restapi/operations/assisted_install_api.go, swagger.yaml
Add a new authentication method which validates a token in the query params of the url.
This method will only be used on a small number of endpoints where the intended client both cannot provide an alternate form of authentication (in headers) and is already considered trusted (the token is a form of password).
Specifically this will be used in the kube-api use case when we need to post a download link to some artifact in a CR. Authentication using this method is only enabled when we are already using the new "local" auth handler which disables the header-based userAuth entirely.
This enables the new auth on the following endpoints:
- GET /clusters/{cluster_id}/downloads/files
- GET /clusters/{cluster_id}/downloads/image
- GET /clusters/{cluster_id}/downloads/kubeconfig
- GET …
=> MGMT-4425 Add presigned url authentication

internal/bminventory/inventory.go, internal/bminventory/mock_installer_internal.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go
Once the cluster is installed:
- Delete Day 1 cluster
- Create Day 2 cluster (For none SNO)
=> MGMT-4626 - KubeApi create day2 cluster after cluster is installed

subsystem/metrics_test.go
This test seems to be flaky and doesn't add any cover edge to the tests since
the metrics generation is generic for all validations so I removed it.
=> MGMT-4742: Removing flaky subsytem-test on cluster validations metrics.

internal/operators/cnv/cnv_operator.go, internal/operators/cnv/manifest.go
We need to use `stable` channel when creating cnv subscription. In the past ocp version was used instead.
=> MGMT-4079 change subscription channel to stable

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/operators/manager.go, internal/operators/manager_test.go, internal/operators/mock_operators_api.go
Until now, we resolved dependencies on the validation level only.
Hence, the user was unable to install a cluster with OCS/CNV requirements but without LSO requirements.
But still, LSO wasn't monitored and the UI is unable to show its status.
Now, moving the cluster OLM operators dependencies to be resolved on cluster
creation or cluster update operation level.
=> MGMT-4765 Bugfix Resolve OLM dependencies on cluster creation and update

internal/isoeditor/rhcos.go, internal/isoeditor/rhcos_test.go, internal/isoutil/isoutil.go, internal/isoutil/isoutil_test.go, pkg/s3wrapper/util.go
There were two issues preventing the image from booting properly with UEFI. Each is handled by a commit in this PR.
1. We need to compute the correct size for the number of sectors to load for the boot image
Load Sectors * 2048 should be the size of efiboot.img rounded up to a multiple of 2048.
This was preventing the uefi system from finding the boot image.
ref:
https://fedoraproject.org/wiki/User:Pjones/BootableCDsForBIOSAndUEFI#Testing_the_image
2. We need to quote the rootfs url parameter in grub.cfg
Some special characters which are legal in a url are used as separators in grub's syntax so we need quotes.
ref:
https://www.gnu.org/software/grub/manual/grub/html_node/Shell_002dlike-scripting.html
=> MGMT-4693 Make minimal iso boot with UEFI

Makefile, deploy/assisted-service.yaml, tools/deploy_local_auth_secret.py
This commit adds a python tool to create the local
auth key pair secret and adds the keys to env vars
in the service.
This will be created on every deployment, but will
only be used if AUTH_TYPE=local
=> MGMT-4358 Deploy the local secret with a make target

Makefile, docs/installer-stand-alone.md, internal/isoeditor/rhcos.go, pkg/s3wrapper/filesystem.go, pkg/s3wrapper/upload_iso.go
With this change we should be able to embed ignition configurations into
ISOs without using the coreos-installer binary directly.
=> MGMT-4072: Remove coreos-installer dep

internal/cluster/cluster_test.go, internal/cluster/refresh_status_preprocessor.go, internal/cluster/transition_test.go, internal/host/refresh_status_preprocessor.go, internal/host/transition_test.go
We need to sort `ValidationResults` being stored as part of `ValidationsOutput` to make sure it is not changing (only order of the results).
=> MGMT-4673 Sort ValidationsOutput to prevent uneeded updates

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/mock_cluster_api.go, subsystem/cluster_test.go
Changing its name to `IsConsoleUrlReady` and changing the implementation
to return the results only once console operator is ready and error
otherwise.
=> MGMT-4760: Updating cluster.GetCredentials function.

internal/controller/config/rbac/role.yaml, internal/controller/controllers/clusterdeployments_controller.go
In order to be able to set OwnerReference of the secrets to the ClusterDeployments, the controller need RBAC to `clusterdeployments/finalizers`
=> NO-ISSUE Update RBAC for controller

internal/host/validator.go
Relates to [BZ-1942521](https://bugzilla.redhat.com/show_bug.cgi?id=1942521)
Reverting back the change to use physical memory when validation host for role. If no operator is selected, it should match the behavior of minimum node requirement validation, which still uses physical memory.
I believe that node memory overall should not make use of the usable memory at this point, that should fall into the specific operator validation to determine if there is sufficient resources for its needs.
=> [BZ-1942521] Revert memory validation for host role to use physical instead of usable

deploy/assisted-installer-local-auth.yaml, tools/deploy_local_auth_secret.py
Even though we can't use it for the operator case, we still need
the secret object as the service references it unconditionally
Without this the operator deployment was failing with:
`Error: secret "assisted-installer-local-auth-key" not found`
=> NO-ISSUE Render a file for the local secret

internal/hardware/validator.go, internal/hardware/validator_test.go, internal/host/host_test.go, internal/operators/api/api.go, internal/operators/api/mock_operator_api.go, internal/operators/cnv/cnv_operator.go, internal/operators/lso/ls_operator.go, internal/operators/manager.go, internal/operators/manager_test.go, internal/operators/mock_operators_api.go, internal/operators/ocs/ocs_operator.go
Interface change is required to allow the OLM operator plugins to access inventory information while calculating host requirements.
=> MGMT-4733 provide host in Operator requirements API

internal/bminventory/inventory.go, internal/network/cidr_validations.go, internal/network/cidr_validations_test.go, internal/network/machine_network_cidr.go
- Use /26 for machine CIDR and /25 for Service and Cluster CIDR
/cc @tsorya
=> MGMT-4743 Assisted installer clusterDeployment uses same netmask to parse all networks (machine/service/cluster)

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
Customization APIs allow changes that can break installation,
so we want an easy way to tell if a user made  such changes.
Raise an event and write to the log when a user applies a custom:
- Cluster install config
- Cluster discovery ignition
- Host discovery ignition
- Host installer arguments
=> MGMT-4422 Add log and events for customizations

client/installer/installer_client.go, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/ignition/ignition.go, internal/ignition/ignition_test.go, internal/ignition/mock_ignition.go, restapi/configure_assisted_install.go, restapi/embedded_spec.go, restapi/operations/installer/get_discovery_ignition.go, restapi/operations/installer/update_discovery_ignition.go, swagger.yaml
The PR is responsible for the following:
1. It expands the description of `GET /clusters/{cluster_id}/discovery-ignition` in swagger.yaml to distinguish it from a different API that allows to d/w the actual discovery ignition.
2. It Changes `ignition.FormatDiscoveryIgnitionFile` not to rely on `ImageCreateParams`. Instead, it relies on the attributes that were updated for the cluster. By doing so, we remove the need to provide an empty `ImageCreateParams` for `GET /clusters/{cluster_id}/discovery-ignition`, which may override cluster's attributes that were updated by the latests ISO generation request. Therefore if this method is invoked after an ISO was already generated, the retrieved discovery ignition will be formatted using the parameters that were set for generating the last …
=> MGMT-4639 discovery ignition should be complete

Makefile, subsystem/authz_test.go, subsystem/cluster_test.go, subsystem/kubeapi_test.go, subsystem/subsystem_suite_test.go
Now when running subsystem for kube-api all user auth
is rejected and agent auth requires the new local token
cc @filanov
=> MGMT-4773 Use local auth with kube-api subsystem tests

internal/cluster/conditions.go, internal/cluster/refresh_status_preprocessor.go, internal/common/db.go, internal/hardware/boot_device.go, internal/hardware/validator.go, internal/hardware/validator_test.go, internal/host/conditions.go, internal/host/host.go, internal/host/host_test.go, internal/host/monitor_test.go, internal/host/refresh_status_preprocessor.go, internal/host/transition.go, internal/host/transition_test.go, internal/host/validation_id.go, internal/host/validator.go, models/host_validation_id.go, restapi/embedded_spec.go, swagger.yaml
[MGMT-3453](https://issues.redhat.com/browse/MGMT-3453) - Add support in requirement API to retrieve the value of installation_disk_speed_threshold_ms
[MGMT-4674](https://issues.redhat.com/browse/MGMT-4674) - Add validations and conditions for new state.  These include the disk FIO validations and conditions, and
installation preparations conditions.  These will be used in a later commit affecting cluster and host
state machines.
=> Multiple changes for epic MGMT-3563

models/l3_connectivity.go, restapi/embedded_spec.go, swagger.yaml
This PR adds the model details in swagger to extend the L3 connectivity structure to capture the network latency (average RTT and packet loss) between hosts. This information will be used next to validate whether a node is a good candidate to be a member of the etcd cluster based on its average RTT and packet losses captured during the node discovery phase.
I need to have the swagger model updated before I can import the new structure into the agent project and progress into capturing the extra details. Once I have that information, I can proceed to add a new validation that uses the new information to determine if a host that has role Master fits the etcd latency requirements.
@avishayt @jakub-dzon @pkliczewski @masayag @machacekondra please review at your discretion.
/Jordi
=> MGMT-4070 Capture network latency between hosts

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/bminventory/mock_installer_internal.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go
In case that the Cluster is a Day 2 cluster, hosts will be automatically installed if they are in Known status and Approved
=> MGMT-4715 Auto install Day 2 hosts in kube-api

Jenkinsfile, Makefile
Cannot use BUNDLE_IMAGE, needs to use published tag version:
quay.io/ocpmetal/assisted-service-operator-bundle:${PUBLISH_TAG}
=> NO-ISSUE: Index build needs to use the publish tag of bundle image

internal/controller/controllers/clusterdeployments_controller.go
This field is not needed, it can be inferred by cluster name and base domain.
=> NO-ISSUE Remove APIVipDnsname handling from CRD

internal/cluster/cluster.go, internal/cluster/cluster_test.go
On https://github.com/openshift/assisted-service/pull/1384
GetCredentials function logic changed to support looking on the
operator's status instead of on the cluster status. Hence when asking
for credentials the console operator status will be checked.
This change wasn't backward-compatible for clusters that don't weren't
registered and initialized with monitored operators' data. Hence, need to
keep checking the previous way for the cluster status for clusters that
don't have monitored operators at all.
/cc @gamli75 @ybettan
=> OCPBUGSM-27182 Backward-compatible IsOperatorAvailable function

docs/Kube-API-examples.md, docs/user-guide/install-customization.md, go.sum, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/bminventory/mock_installer_internal.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go
Support install-config patching using annotations on cluster-deployment CRD.
annotation key: "hive.openshift.io/install-config-overrides"
Adding, updating, or removing this annotation will trigger a call for UpdateClusterInstallConfigOverrides with the given string
The current implementation doesn't cover invalid configuration
=> MGMT-4587 Allow install-config overrides using annotations

internal/bminventory/inventory.go
This change will partially resolve [MGMT-4647](https://issues.redhat.com/browse/MGMT-4647).
We will also need to follow up with backend notifications, which will not be included in this PR.
This will prevent the following:
=> MGMT-4647 Remove HTTP409 event for `GenerateClusterISOInternal`

Jenkinsfile
Users may abort Jenkins jobs, it would be nice to know whether a job was
aborted or whether it actually failed in the Slack message.
This is what it looked like before:
Hopefully, after it would say either `"Attention! ... job ABORTED", ..."` or `"Attention! ... job FAILURE, ..."`
=> NO-ISSUE - Jenkins slack message distinction between failure and user abort

Dockerfile.assisted-service-build, Makefile, hack/update_local_image.sh, pkg/job/job.go, skipper.yaml, tools/clear_deployment.py, tools/debug/minikube_postgres.sh, tools/deploy_assisted_installer.py, tools/deploy_assisted_installer_configmap.py, tools/deploy_crd.py, tools/deploy_grafana.py, tools/deploy_inventory_service.py, tools/deploy_local_auth_secret.py, tools/deploy_mariadb.py, tools/deploy_namespace.py, tools/deploy_olm.py, tools/deploy_postgres.py, tools/deploy_prometheus.py, tools/deploy_role.py, tools/deploy_route53.py, tools/deploy_s3.py, tools/deploy_scality_configmap.py, tools/deploy_sso_secret.py, tools/deploy_ui.py, tools/deploy_wiremock.py, tools/deployment_options.py, tools/pvc_size_utils.py, tools/utils.py, tools/wait_for_assisted_service.py
Our Python scripts were dependent on `minikube` tool. Minikube requires a host with a KVM.
Making our scripts work regardless of the cluster. A simple `kubectl` command approach that is configured to some cluster. That cluster could be local or remote.
Some lightweight approaches like k3d and kind deploy a cluster on top of dockers, would be able to work as well.
=> NO-ISSUE Remove minikube code and PROFILE variable

internal/cluster/cluster.go, internal/cluster/cluster_test.go
On https://github.com/openshift/assisted-service/pull/1384
GetCredentials function logic changed to support looking on the
operator's status instead of on the cluster status. Hence when asking
for credentials the console operator status will be checked.
This change wasn't backward-compatible for clusters that don't weren't
registered and initialized with monitored operators data. Hence, need to
keep checking the previous way for the cluster status for clusters who
don't have monitored operators at all.
=> OCPBUGSM-27182 Backward-compatible IsOperatorAvailable function (#1437)

docs/architecture.md
This commit introduces an architecture document to the repo. Its goal is
to provide readers with a basic understanding of service's architecture.
It is not meant to provide exhaustive documentation on various features
of the service - those should be covered in separate docs, one per
feature.
=> NO-ISSUE Architecture document

internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/transition.go, subsystem/cluster_test.go
To prevent flusters from being constantly updated this will skip cluster status update in cast the status & info are not changd
=> MGMT-4822 Skip un-needed cluster status update

pkg/staticnetworkconfig/generator.go
A valid YAML, which is an invalid nmstatectl config, will cause assisted-service to crash.
The root cause for this is the fact that nmstatectl returns an empty config {} when it gets flags it does not recognize, and additionally return code=0
This is causing a panic in assisted-service, which won't be recovered until we delete that nmstate config.
nmstatectl returns an empty config and return code 0 here: https://github.com/openshift/assisted-service/blob/0d2c0170ff0ada57c7803246c0c961313baad860/pkg/staticnetworkconfig/generator.go#L76
Next, we have: https://github.com/openshift/assisted-service/blob/0d2c0170ff0ada57c7803246c0c961313baad860/pkg/staticnetworkconfig/generator.go#L96-L104
This empty config is accepted by `yaml.Unmarshal`, thus no error returned, but …
=> MGMT-4891 Validate hostNMConnections is not empty

internal/common/db.go, models/cluster.go, restapi/embedded_spec.go, swagger.yaml
UI needs it so they can query clusters from the service using
ams_subscription_id, therefore, it should be exposed for the user.
=> MGMT-4523: Exposing ams_subscription_id field in API cluster model.

Makefile, cmd/main.go, internal/controller/controllers/agent_controller.go, internal/controller/controllers/controller_event_wrapper.go, internal/controller/controllers/controller_event_wrapper_test.go, internal/controller/controllers/crd_events_handler.go, internal/controller/controllers/mock_crd_events_handler.go
Currently we reconcile every few seconds regardless if there was a change on the resource.
The reconcile should be based on two things, changes in the spec and based on changed from the backend. the important changes are state and validations. for both we have events.
So we should have a wrapper for the events interface that will notify host/cluster about the changes.
If the event contain host-id then agent resource should get a notification, otherwise cluster resource.
Both cluster and host have a kube key (namespace name) so a generic event can be used to notify the controller
The controllers will listen to channel that will get those events and call for a reconcile loop according to it.
=> MGMT-4834 Reconcile on backend events

config/manager/manager.yaml
Limit of 30Mi and request of 20Mi made the operator undeployable on
cluster-bot clusters. Resulting in "FailedCreatePodSandBox" errors.
=> NO-ISSUE Increase operator resource limit/requests

cmd/main.go, internal/cluster/cluster_test.go, internal/common/common.go, internal/hardware/validator_test.go, internal/host/monitor_test.go, internal/operators/ocs/ocs_operator.go, internal/operators/ocs/validation_test.go
"myapp" prefix parameter for envconfig appears in-line in many places and this PR defines a const that should be used instead.
=> NO-ISSUE Replace envconfig prefix in-line string with a const

internal/cluster/statemachine.go, internal/cluster/transition.go, internal/cluster/transition_test.go, subsystem/ams_subscriptions_test.go, subsystem/wiremock_stubs.go
Reordered the transitions in such why updating the console URL in OCM
won't be skipped and also added a condition to the transition so the
console URL is updated only when the console operator gets available.
=> NO-ISSUE: Fixing update of console URL in OCM.

Dockerfile.assisted-service-build, Jenkinsfile, Makefile, dev-requirements.txt, hack/setup_env.sh
Adding a setup_env.sh script for users that don't use Dockerfile to run
the Makefile targets, for example our Prow CI.
Make a common _test Makefile target that all tests targets would call -
subsystem, onprem, unit-test
The _test target will have the same flags except for TIMEOUT and TEST
Coverage will be generated only in case the BUILD_TYPE is not standalone
=> NO-ISSUE Publish susbsystem reports

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/controller/controllers/controller_event_wrapper.go, internal/controller/controllers/controller_event_wrapper_test.go
This comes as a followup to [MGMT-4834](https://issues.redhat.com/browse/MGMT-4834) Reconcile on backend events
We need an event so we can reconcile when it happens.
Also, this PR will change AddEvent log to Info, so we can better track those events.
Lastly, always push clusterDeployment updates, so we reconcile changes in clusterDeployment.
=> MGMT-4929 Add Agent Approval event

go.mod
This PR aims to fix the current CI problemby pinning the k8s.io/api package to version v0.20.0 to prevent the lint job from [failing](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/1476/pull-ci-openshift-assisted-service-master-lint/1380620849509306368) by pulling the latest version (v0.21.0), which is incompatible with the other libraries we use.
Related to #1479 
@osherdp @YuviGold @nmagnezi can you take a look?
=> NO-ISSUE Pin k8s.io/api to v0.20.0

internal/operators/ocs/validation_test.go, internal/operators/ocs/validations.go
RAM requirements for OCS minimal deployment are updated to be same as Standard Deployment Mode (57GB excluding disk requirements).
Signed-off-by: Priyanka Jiandani <pjiandan@redhat.com>
=> NO-ISSUE Updated Minimal Deployment RAM Requirements to 57GB

cmd/operator/main.go, config/manager/manager.yaml, config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml, docs/operator.md, internal/controller/api/v1alpha1/agentserviceconfig_types.go, internal/controller/config/crd/bases/adi.io.my.domain_agentserviceconfigs.yaml, internal/controller/config/crd/resources.yaml, internal/controller/controllers/agentserviceconfig_controller.go, internal/controller/controllers/common.go, internal/controller/controllers/images.go
The original PR#1422 left some comments unaddressed. This commit
addresses those comments and other concerns:
- Moving the passwordGenerator to common.go
- Making the error message when NAMESPACE isn't specified more clear
- Documenting that building the bundle+index isn't required
- Simplifying controller constants
- Abstracting the newFilesystemPVC+newDatabasePVC -> newPVC
- Emitting an event when reconcile completes
- Handle OPENSHIFT_VERSIONS
- Set IPV6_SUPPORT to True on assisted-service
- Set requests on assisted-service+postgres containers
- Add some basic guidelines for the filesystem+database PVC requests
- Add SERVICE_ACCOUNT_NAME using d/w API to operator, pass that to
the assisted-service-deployment
- Add 'http://' to host for `SERVICE_BASE_URL`
=> MGMT-4739: AgentServiceConfig controller cleanup

pkg/s3wrapper/util.go
This is not actually an error and was causing some confusion
when people see it in the logs.
Log just once as a warning and make the message less scary
cc @empovit @danielerez
=> NO-ISSUE Remove error log when iso template versions is missing

cmd/main.go
This adds some configuration that we can use to provide a
cert and key to serve https traffic.
=> MGMT-4991 Allow the service to serve https traffic

tools/deploy_assisted_installer.py, tools/deploy_namespace.py, tools/deploy_role.py
This PR changes the python print method to logging. It's needed because
we can see the time of the logging printed and the output and compare
the time of the execution in CI.
Signed-off-by: Ondra Machacek <omachace@redhat.com>
=> NO-ISSUE Use logging instead of print in tools scripts

cmd/main.go, docs/crds/clusterImageSet.yaml, hack/crds/hive.openshift.io_clusterimagesets.yaml, internal/controller/config/rbac/role.yaml, internal/controller/controllers/clusterdeployments_controller.go, models/cluster.go, models/cluster_create_params.go, models/openshift_version.go, restapi/embedded_spec.go, swagger.yaml, tools/handle_ocp_versions.py
Added the following crds and apis as preliminary dependencies for: https://github.com/openshift/assisted-service/pull/1319
* Added ClusterImageSet CRD
- Copied from:
https://github.com/openshift/hive/blob/34d28c1d6e001687fae2d0fc3ac722fe173f0c8c/config/crds/hive.openshift.io_clusterimagesets.yaml
- Added relevant roles to clusterdeployments_controller.
- Added an example to docs/crds.
* 'ocp_release_image' property in cluster entity and create params:
used for storing the release image URI.
* 'release_version' property in openshift-version:
used for storing the version in major.minor.patch format.
* Modified main and handle_ocp_version to handle missing release_image
(would be feteched from the cluster image set).
=> MGMT-4981: crds and dependencies for custom version support

internal/installcfg/installcfg.go, internal/installcfg/installcfg_test.go
hypethreading configuration is set in the install-config and is used
by the installer code to produce ignition kernel param for RHCOS.
by default hypethreading is enabled by the RCHOS, so installer code needs
to configure kernel arg only in case of hyperthreading disabling. the valid values
for hyperthreading parameter in ignition is Enabled and Disabled. In case the value is missing,
it is Enabled by default
=> MGMT-5176 - Fix support for disabling hyperthrreading

docs/crds/clusterDeployment-SNO.yaml, docs/crds/clusterDeployment.yaml
The `installConfigSecretRef` is forbidden by hive in case of agent install
strategy.
'# kubectl create -f  snocluster.yaml
The ClusterDeployment "test-infra-cluster-assisted-installer" is
invalid: spec.provisioning.installConfigSecretRef: Forbidden: custom
install config cannot be used with agent install strategy'
=> NO-ISSUE: Fix ClusterDeployment example

internal/bminventory/inventory.go
Both spellings canceled(Americans) and canceled(British) are in use.
This patch changes all `canceled` to `cancelled`.
https://bugzilla.redhat.com/show_bug.cgi?id=1923268
=> OCPBUGSM-24075 - Correct the spelling of 'canceled' on "canceled by user" event

internal/cluster/validator.go, internal/host/statemachine.go, internal/host/transition_test.go, subsystem/kubeapi_test.go
[OCPBUGSM-27929](https://issues.redhat.com/browse/OCPBUGSM-27929) - Make transition for cancel installation from known state not to fail
[MGMT-5253](https://issues.redhat.com/browse/MGMT-5253) - Make all-hosts-ready-for-installation validation pass for preparing statuses
NO-ISSUE - Fix flakey subsystem test "SNO deploy clusterDeployment full install and validate MetaData"
/cc @omertuc 
/cc @osherdp
=> Multiple issues

dashboards/grafana-dashboard-assisted-installer-validations.configmap.yaml
I have set the wrong name to the configmap (copy paste) and it is
failing on app-sre because this name already exist in another dashboard.
=> NO-ISSUE: Fixing validations dashboards name.

internal/network/cidr_validations.go, internal/network/cidr_validations_test.go
Handle network prefix in case a cluster has a single node. In such
case the entire machine CIDR or its part (but no less than 128
addresses) can be allocated to the node.
=> OCPBUGSM-25356 Handle net prefix for single node

dashboards/grafana-dashboard-assisted-installer-ocm-operations.configmap.yaml
The previous implementation had 2 issues:
1. It was using `histogram_quantile` function with 0.99, I believe in order
to ignore the non-working OCM API calls, but in fact this function
doesn't return the metrics count within the quantile but the quantile
itself. That caused the graph to appear as a relatively constant
graph.
2. It included a different query for each `operation` type, which mean
it didn't included any metrics with new `operation` types and for
each new metrics we needed to update the dashboard correspondingly.
The new implementation is fixing those 2 issues.
=> MGMT-4965: Fixing OCM-Operations Grafana dashboard.

internal/controller/api/v1beta1/agent_types.go, internal/controller/config/crd/bases/agent-install.openshift.io_agents.yaml, internal/controller/config/crd/resources.yaml, internal/controller/controllers/bmh_agent_controller.go, internal/controller/controllers/bmh_agent_controller_test.go
Ref: https://issues.redhat.com/browse/MGMT-4914
This PR is for the BMAC to read the annotation from BMH and set the IgnitionConfigOverride in the agent's spec, similar to role and hostname. This PR adds support for IgnitionConfigOverride customization. To customize ignition config override user will need to set annotation in bmh
example:
bmac.agent-install.openshift.io/ignition-config-overrides: {"storage": {"files": [{"path": "/tmp/example", "contents": {"source": "data:text/plain;base64,aGVscGltdHJhcHBlZGluYXN3YWdnZXJzcGVj"}}]}}
=> MGMT-4914: BMAC sets IgnitionConfigOverride to agent

internal/cluster/validations/validation_test.go, internal/cluster/validations/validations.go, internal/host/hostcommands/install_cmd.go, internal/host/hostcommands/install_cmd_test.go, internal/ignition/ignition_test.go, internal/installcfg/installcfg.go, internal/installcfg/installcfg_test.go
Asterisk (*) is a special value and cannot be used in combination
with a list of values (addresses, domains) in NoProxy field.
This value will be blocked until
https://bugzilla.redhat.com/show_bug.cgi?id=1947066 is fixed.
=> OCPBUGSM-17327 Handle asterisk in NoProxy values

cmd/main.go, go.mod, internal/metrics/metricsManager.go, internal/metrics/mock_metrics_manager_api.go, pkg/s3wrapper/filesystem.go, pkg/s3wrapper/filesystem_test.go
In order to inspect FS usage and allow user to define alert based on
reported metrics, each time FS is being changed (on create/delete file),
the metrics are updated to reflect the actual usage in percentage of the filesystem.
An example of the reported metrics:
```
service_assisted_installer_filesystem_usage_percentage 55
```
=> MGMT-3512 Report FS usage metrics

internal/bminventory/inventory.go, internal/hardware/mock_validator.go, internal/hardware/validator.go, internal/hardware/validator_test.go, internal/host/host.go, internal/host/mock_host_api.go, internal/host/transition_test.go, internal/operators/api/api.go, internal/operators/api/mock_operator_api.go, internal/operators/cnv/cnv_operator.go, internal/operators/cnv/cnv_operator_test.go, internal/operators/lso/ls_operator.go, internal/operators/manager.go, internal/operators/manager_test.go, internal/operators/mock_operators_api.go, internal/operators/ocs/ocs_operator.go, subsystem/cluster_test.go
Changes contained within this PR add implementation of `/clusters/{cluster_id}/preflight-requirements` endpoint handler that provides information about pre-flight hardware requirements - coming from OCP and supported OLM operators.
=> MGMT-4477 Preflight hardware requirements handler

cmd/main.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/garbagecollector/garbageCollector.go, internal/imgexpirer/imgexpirer.go, internal/imgexpirer/imgexpirer_test.go
The PR is responsible for reducing the amount of disk-space taken by the assisted-service and informing the user about exceeding a threshold in can kube-api is enabled:
* Delete discovery-image of deregistered clusters
* Shorten the lifetime of unregistered clusters
=> MGMT-3512 Reduce disk space taken by assisted service

internal/controller/controllers/agent_controller.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/infraenv_controller.go
It will help us to find bugs in Reconcile loops and give more visibility.
The log should include the resource name and namespace.
=> Mgmt 5282 kubeapi info log on reconcile entering

internal/controller/controllers/controller_event_wrapper.go, internal/events/event.go, internal/events/event_test.go, internal/events/mock_event.go, models/event.go, restapi/embedded_spec.go, swagger.yaml
Add JSON-formatter properties field to Event to hold free-formatted
additional properties and optional extra properties parameters to
Event API for hosting metrics parameters
additional internal severity filters out internal events from the UI
=> MGMT-4526 - Extended Event API

internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go
After SNO cluster is installed it will be deleted, the next reconcile
loop will return Not Found and should not update cluster deployment with
an error and just return and stop requeue
=> OCPBUGSM-28144 fix reconcile error of installed SNO cluster

internal/controller/controllers/agentserviceconfig_controller.go
This commit adds an annotation to the service which will cause a
tls secret to be created in the same namespace valid for that service
name. This secret is used to configure assisted-service to start an
https server.
Additionally, the route is configured to use "re-encrypt" tls
termination which will use the router's certificate to communicate
with the client, then re-encrypt the request from the router to the
service using the service cert.
Docs on the service annotation:
https://docs.openshift.com/container-platform/4.7/security/certificates/service-serving-certificate.html#add-service-certificate_service-serving-certificate
https://issues.redhat.com/browse/MGMT-4740
~~Depends on https://github.com/openshift/assisted-service/pull/1495~~ Merged
=> MGMT-4740 Encrypt traffic to assisted service

docs/Kube-API.md, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/bminventory/mock_installer_internal.go, internal/controller/api/v1beta1/agent_types.go, internal/controller/config/crd/bases/agent-install.openshift.io_agents.yaml, internal/controller/config/crd/resources.yaml, internal/controller/controllers/agent_controller.go, internal/controller/controllers/agent_controller_test.go, internal/controller/controllers/bmh_agent_controller.go, internal/controller/controllers/bmh_agent_controller_test.go, subsystem/kubeapi_test.go
Ref: https://issues.redhat.com/browse/MGMT-4463
This PR adds support for the IgnitionConfigOverrides parameter added in the agent spec (Ref: https://issues.redhat.com/browse/MGMT-4914). The parameter is reconciled and added in the backend (db). To customize IgnitionConfigOverrides, user will need to set annotation in bmh
example:
> bmac.adi.openshift.io/ignition-config-overrides: {"ignition": {"version": "3.1.0"}, "storage": {"files": [{"path": "/tmp/example", "contents": {"source": "data:text/plain;base64,aGVscGltdHJhcHBlZGluYXN3YWdnZXJzcGVj"}}]}}
=> MGMT-4463 Support IgnitionConfigOverrides in the Agent

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/common/common.go, internal/common/error_utils.go, pkg/s3wrapper/client.go, pkg/s3wrapper/errors.go, pkg/s3wrapper/filesystem.go, pkg/s3wrapper/util.go
s3wrapper depends on metric API which is a high level package and creates cyclic dependencies for the effort to migrate metric to events
=> NO-ISSUE remove dependency of common in s3wrapper

internal/host/hostcommands/install_cmd.go, internal/host/hostcommands/install_cmd_test.go
Use the machine CIDR calculation that takes into account
SNO/user-managed networking in order to pass `ip=dhcp` or `ip=dhcp6`
karg to the installer.
=> MGMT-5306 Handle dhcp karg in case of SNO

internal/bminventory/inventory.go, internal/cluster/transition.go, internal/cluster/transition_test.go, internal/common/common.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/cluster_test.go, subsystem/kubeapi_test.go
- Remove InfraID: was populated by mistake with cluster rest api uuid
- Update in CD CR status api and console url
=> Mgmt 4843 clusterdeployment api and console urls

internal/cluster/cluster.go, internal/cluster/transition.go, internal/cluster/validator.go
The change handles the flow when there are many clusters that do not need to be updated during RefreshStatus.
This flow should be fast as possible.  Testing showed that many db queries cause high CPU usage and latency in cluster monitoring.
So during the above flow the aim for clusters that do not need to change - to query the database much less than
the number of clusters.  Currently we use 100 clusters batch.
The solution is in cluster monitoring to query one per batch for all cluster operations in the loop (connectivity-groups, refresh-status).
This data should be used without additional database query unless update is attempted.
The main idea for the change is that clusters are queried only once in the monitoring loop with all the details needed (hosts,
operators etc.).  These …
=> MGMT-5359 High CPU usage of Assisted-Service with 500 clusters and not hosts

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/bminventory/mock_installer_internal.go, internal/common/test_configuration.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, internal/controller/controllers/common.go, internal/controller/controllers/controllers_suite_test.go, internal/controller/controllers/infraenv_controller.go, internal/controller/controllers/infraenv_controller_test.go, internal/oc/release.go, internal/versions/mock_versions.go, internal/versions/versions.go, internal/versions/versions_test.go, subsystem/kubeapi_test.go
Added an internal API for dynamically supporting a new custom OCP version,
and upload boot files according to specified OCP/RHCOS version/image.
In order to allow hive ClusterDeployment creation with custom OCP version, supporting the following flow:
* Set OPENSHIFT_VERSIONS env var only with RHCOS image/version and
OCP version in major.minor format as a key. I.e. {"4.8":{"rhcos_image":...,"rhcos_version":...}}
* Set the release image within an ImageSet referenced in the ClusterDeployment.
* Upon creating a new cluster in ClusterDeploymentsReconciler, use 'oc adm release info' to fetch the OCP version (in major.minor.patch format).
* Fetch stored OpenshiftVersion entity according to major.minor version.
* Update OpenshiftVersion with missing data (ReleaseImage and DisplayName), and cache …
=> MGMT-4554 API for supporting a custom OCP version

internal/controller/controllers/infraenv_controller.go, subsystem/kubeapi_test.go
If the InfravEnv is created before the ClusterDeployment, it will never create the image.
This patch add a notification between the ClusterDeployment to InfraEnv.
=> MGMT-4930 Add notifications from ClusterDeployment to InfravEnv

cmd/main.go
In operator deployment, when cluster entity is removed from the
database by the garbage collector, the clusterdeployment controller
will attempt to reconcile the clusterdeployment CR by re-creating a new
cluster entity in the database for it.
Therefore, the garbage collection job is not useful in operator
deployment and needs to be skipped.
=> MGMT-3512 Skip garbage collection jobs in operator deployment

dashboards/grafana-dashboard-assisted-installer-ocm-operations.configmap.yaml
I was querying for all metrics in bucket with le!="+Inf" but the
histogram is accumulative, means that I was counting the same metrics
over and over.
I just removed the 'bucket' suffix and used 'count' suffix instead,
after all we want to count also the "failing" requests (with le="+Inf").
=> MGMT-5386: Fixing OCM-Operations Grafana dashboard.

internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/common/test_configuration.go, internal/network/manifests_generator.go, internal/network/mock_manifests_generator.go
Add manifest to create a bash script file /etc/NetworkManager/dispatcher.d/05-disable-tunnel-offload
The manifest creation is invoked for clusters with vmware hosts only
The script checks if the driver is vmxnet3 and that the settings tx-udp_tnl-csum-segmentation and tx-udp_tnl-segmentation
can be updated, If these settings can be updated, the script sets the to off.
The script is relevant (and checks it) for "up" action only.
/cc @ronniel1 
/cc @tsorya 
/cc @gamli75
=> OCPBUGSM-28006 Fix vxlan vmware incorrect checksum in assisted installer

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
* Use major.minor.patch format version (cluster.OpenshiftVersion)
for ClusterRegistered metric
* Use same format for AddHostsCluster (as done in RegisterClusterInternal).
=> MGMT-4183 use z-stream version for ClusterRegistered metric

subsystem/cluster_test.go, subsystem/kubeapi_test.go, subsystem/utils_test.go
Tests that are validating the effect of successful or failed disk-speed-check response
on the flow of the installation. In case of failed response, the host should
return to insufficint as well as the cluster.  In case the all hosts succeeded preparing (successful disk-speed-check response),
installation should continue. The successful flow is already tested as part of the other installation tests.
=> MGMT-5174 Subsystem tests for epic MGMT-3563

deploy/operator/deploy.sh, deploy/operator/setup_assisted_operator.sh, deploy/operator/setup_hive.sh, deploy/operator/setup_lso.sh, deploy/operator/utils.sh
Moving operator installation scripts to assisted-service, just like other operators are doing.
Those scripts configure local-storage-operator (assumes several disks already existing), hive and assisted-service operator.
It allows for customizing several components' images, as well as referring to a specific catalog source.
=> MGMT-5372 added scripts for operator installation

Dockerfile.assisted-service-debug, Makefile, debug.md, deploy/assisted-service.yaml, skipper-mac.yaml, tools/deploy_assisted_installer.py, tools/deploy_inventory_service.py, tools/deployment_options.py, tools/wait_for_assisted_service.py
[MGMT-4967](https://issues.redhat.com/browse/MGMT-4967) Create a standard way to run a debugger on the service
Document how to debug deploy the service with debug information 
Open the debug ports on our k8s resources
Change the debug port to be configureable
Fixing skipper make deploy-test command on a macos
=> Mgmt 4967 Create a standard way to run a debugger on the service

subsystem/metrics_test.go
GinkgoWriter is an io.Writer that emit its content to the console if a
specific test fails.
In our case, we have some flaky tests due to the fact that multiple
metrics are filtered instead of a single one as part of the test. This
new info will help us understand why more than a single metric was
filtered.
=> NO-ISSUE: Adding debug info for failing validations subsystem tests.

internal/network/cidr_validations.go, internal/network/cidr_validations_test.go
Updated MinMachineMaskDelta to 4, it should allow /28 for machine network CIDR
=> Bug 1953586 - Assisted installer fails to allocate VIPs

internal/cluster/cluster.go
- Add explanation for sorting hosts when calculating connectivity groups
- Return 404 or 500 when there is an error retrieving cluster for connectivity groups
/cc @filanov
=> MGMT-5359 Fix comments from recent PR (https://github.com/openshift/assisted-service/pull/1573)

internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/host/host.go, internal/host/host_test.go
At some events, the cluster state was spelled canceled and not canceled .
=> OCPBUGSM-24075 - fix events using English spelling canceled

internal/controller/controllers/agentserviceconfig_controller.go
According to
https://docs.openshift.com/container-platform/4.7/security/certificate_types_descriptions/ingress-certificates.html#workflow
this configmap is the authoritative source of the certificate being used
for ssl on routes.
This commit also configures the SERVICE_CA_CERT_FILE environment
variable on the assisted service to point to the file in the new
configmap. This allows us to enforce trusted connections to the service
from the agent and controller.
Built on: https://github.com/openshift/assisted-service/pull/1506
=> MGMT-4741 Use the ingress cert to ensure trusted https connections

internal/host/hostcommands/install_cmd.go, internal/host/hostcommands/install_cmd_test.go, internal/network/machine_network_cidr.go
Set `ip=dhcp` or `ip=dhcp6`, according to address family of the
machine network, for reliable interface initialization in dracut mode.
In none-platform, determining the machine network relies on bootstrap
node. When the install command of a node is being generated, we need
to read the bootstrap host of the cluster from the DB.
We return an error if an address family cannot be determined:
1. A host cannot exist without an IP address, therefore not finding
one means a bug.
2. Situations when this kernel argument remains unset (i.e. default
value) may result in failed installations, and are very difficult
to detect and troubleshoot.
3. Having said that, it's not possible to tell the right address
family in day 2 scenario, so we have to leave the flag unset
=> MGMT-5408 Fix kernel arg for dhcp in none-platform

Dockerfile.assisted-service
Note that this is a temporary patch to mitigate the issue and there is a blocker bug for moving back to official oc client once it supports ICSP
=> MGMT-5441 assisted-service should use oc client with ICSP support

hack/crds/metal3.io_baremetalhosts.yaml, internal/controller/controllers/bmh_agent_controller.go, subsystem/cluster_test.go, subsystem/kubeapi_test.go
This PR also fixes an issue with the filtering of agents that have an empty MacAddress https://github.com/openshift/assisted-service/commit/55009fb17a984bfaae79f3cc80bd526345770f88
It is possible to create Agents that have an empty MacAddress. If this happens, and there are BMH's that don't have a BootMACAddress set, then the agent will be associated with that BMH, and hardwaredetails will be set on the resource.
This commit skips Agents that have an empty MacAddress just for extra safety measures
More tests will be added but, at least, this sets the basis to do so in more isolated PRs.
=> MGMT-3700 Add dedicated subsystem tests for BMAC day0 

internal/host/hostcommands/install_cmd.go, internal/host/hostcommands/install_cmd_test.go, internal/host/hostutil/host_utils.go, internal/host/hostutil/host_utils_test.go
In day 2 it's not possible to determing which IP family must be
used to enforce DHCP during reboot. In case a host has both IPv4
and IPv6 addresses, write a warning to the log for easier
troubleshooting.
=> MGMT-5408 Warning if day 2 host is dual stack

internal/controller/controllers/agentserviceconfig_controller_test.go
Just noticed this. We don't actually use gomock anywhere in here.
=> NO-ISSUE Remove unnecessary mock controller from service config test

pkg/auth/local_authenticator.go, pkg/auth/local_authenticator_test.go
Previously if we were missing the cluster in the token (or if any of the
other errors occurred) we ended up returning a 500 error because we
didn't specify one here. Now all the authentication errors will be 401
cc @tsorya @avishayt
=> MGMT-5420 Always return 401 for local auth errors

cmd/main.go, pkg/s3wrapper/filesystem.go
The PR changes the log level of filesystem usage to 'Warning' when it exceeds the filesystem usage threshold.
In order to prevent log flooding, when the FS usage exceeds the threshold, it will write a message to the log every 5 minutes.
In case the FS usage below the threshold, it will write to log only once per hour.
=> MGMT-3512 Decrease verbosity of filesystem logs

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
* No need to invoke UploadBootFiles on AddOpenshiftVersion func
as it's already called on service startup (main.go).
Hence, removed the redundant call.
Note: the function already checks files existence before trying
to upload, so there's no change in behaviour.
* Added unit-tests to AddOpenshiftVersion to ensure it's only
invoking the add version API.
=> NO-ISSUE remove redundant call to upload files

hack/get_ocp_versions_for_testing.sh, subsystem/cluster_test.go, subsystem/day2_cluster_test.go, subsystem/host_test.go, subsystem/image_test.go, subsystem/ipv6_test.go, subsystem/manifests_test.go, subsystem/metrics_test.go, subsystem/operators_test.go, subsystem/subsystem_suite_test.go, subsystem/utils_test.go, subsystem/versions_test.go, tools/handle_ocp_versions.py
This PR add a switch to tools/handle_ocp_versions.py script, that can
decide to deploy only single OCP version. If user pass the env var
SINGLE_VERSION_ONLY=1 it will first take --ocp-override version image,
and use it, if not set it will use OPENSHIFT_VERSION env var, if not set
it will take the latest version in the OPENSHIFT_VERSIONS definition.
Example with OPENSHIFT_VERSION set:
```
$ OPENSHIFT_VERSION=4.7 SINGLE_VERSION_ONLY=true hack/get_ocp_versions_for_testing.sh
Using only single version of the RHCOS ISO
{"4.7":{"display_name":"4.7.5","release_image":"quay.io/openshift-release-dev/ocp-release:4.7.5-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.0/rhcos-4.7.0-x86_64-live.x86_64.iso","rhcos_version":"47.83.202102090044-0","support_le …
```
=> MGMT-4356: Deploy only single openshift version

internal/cluster/cluster_test.go, internal/cluster/transition_test.go_disable, internal/cluster/validator.go, internal/host/host.go, internal/host/host_test.go_disable, internal/host/mock_host_api.go, internal/host/monitor.go, internal/host/monitor_test.go_disable, internal/host/transition.go, internal/host/validator.go, internal/operators/ocs/validation_test.go_disable
- Let host monitoring query clusters and hosts and use them, instead query cluster again for each host
- In PostRefreshHost update database only if status or status-info changed
- In hostApi.IsValidMasterCandidate, get cluster as parameter instead of query from database.  This is used by cluster monitoring
/cc @tsorya 
/cc @gamli75
=> MGMT-5390 Improve host monitoring performance (to release 1.0.19)

internal/cluster/cluster_test.go, internal/cluster/transition_test.go, internal/cluster/validator.go, internal/host/host.go, internal/host/host_test.go, internal/host/mock_host_api.go, internal/host/monitor.go, internal/host/monitor_test.go, internal/host/transition.go, internal/host/validator.go, internal/operators/ocs/validation_test.go
- Let host monitoring query clusters and hosts and use them, instead query cluster again for each host
- In PostRefreshHost update database only if status or status-info changed
- In hostApi.IsValidMasterCandidate, get cluster as parameter instead of query from database.  This is used by cluster monitoring
/cc @tsorya 
/cc @filanov 
/cc @ronniel1
=> MGMT-5390 Improve host monitoring performance (to master)

docs/operator.md, internal/controller/controllers/agentserviceconfig_controller.go, internal/controller/controllers/agentserviceconfig_controller_test.go, internal/controller/controllers/controllers_suite_test.go
This PR updates the agent service config controller to recognize
"unsupported.agent-install.openshift.io/assisted-service-config"
annotation and use that as EnvFrom on the assisted-service container.
Checklist
=> OCPBUGSM-28382: Accept cm annotation on ASC

deploy/operator/deploy.sh, deploy/operator/destroy.sh, deploy/operator/libvirt_disks.sh, deploy/operator/setup_assisted_operator.sh, deploy/operator/setup_hive.sh, deploy/operator/setup_lso.sh, deploy/operator/utils.sh
- Add destroy.sh script deleting the assisted-installer namespace, service
config and the assisted-service localvolume.
- Fix destroy of PVs from k8s.
- Add a generic print_help function to utils.sh
- Print k8s manifestes before applying them.
/cc @osherdp
=> MGMT-5274 Adjust operator scripts for test-infra usage

internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/host/monitor.go, internal/host/monitor_test.go, internal/metrics/metricsManager.go, internal/metrics/mock_metrics_manager_api.go, pkg/commonutils/common_utils.go
We want to have graph that will allow us to see how much time takes for cluster/host monitors to finish and how many hosts/clusters they monitor in each loop
=> MGMT-6011 Add monitoring for duration and number of clusters/hosts fr host/cluster monitors

internal/controller/controllers/bmh_agent_controller.go, internal/controller/controllers/bmh_agent_controller_test.go, subsystem/kubeapi_test.go
This commit adds a watch on the InfraEnv resource to make sure that we schedule a reconcile when
the ISOUrl has been set. This will protect us from missing this event due to a race or missing
reconcile
=> MGMT-4849 Watch the InfraEnv resource for BMH reconcile

internal/host/conditions.go, internal/host/refresh_status_preprocessor.go, internal/host/statemachine.go, internal/host/transition.go
- Make check if cluster is in error not to access database.  Use preprocessed condition instead.
- Make conditions in pending-user-action not to access database.  Instead use preprocessed condition.
/cc @tsorya 
/cc @filanov
=> MGMT-5390 Additional improvements to host monitoring

internal/operators/cnv/cnv_operator.go, internal/operators/cnv/cnv_operator_test.go, internal/operators/cnv/config.go, internal/operators/cnv/config_test.go
Each supported by CNV SR-IOV NIC present in the worker host should contribute to memory requirements for CNV - 1 GiB for each device. This PR introduces code that calculates that overhead based on inventory information attached to a host.
=> MGMT-4736 Calculate SR-IOV NICs-related memory overhead

subsystem/kubeapi_test.go
`WebConsoleURL` and `APIURL` may take several seconds to update.
We should not fail the test immidiatly but wait to see if the
expected URLs show up.
=> MGMT-6023 kubeAPI subsystem test - wait for URLs

internal/controller/controllers/agentserviceconfig_controller.go, internal/controller/controllers/agentserviceconfig_controller_test.go
ensureAgentRoute
One of the test for ensureAgentRoute checks that the route.Spec.Host
isn't overwritten by subsequent ensures/reconciles.
=> NO-ISSUE: Tests for agentserviceconfig_controller reconcile and

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/hardware/mock_validator.go, internal/hardware/validator.go, internal/hardware/validator_test.go, internal/host/host.go, internal/host/host_test.go, internal/host/mock_host_api.go, internal/host/statemachine.go, internal/host/transition_test.go, internal/host/validator.go, subsystem/cluster_test.go
Now, when host/hardware requirements are calculated based on cluster and host details, it is possible to check disk eligibility based on those requirements. 
That check will be more accurate, as it takes into account additional operator requirements.
=> MGMT-5348 cluster specific disk eligibility check

subsystem/cluster_test.go, subsystem/kubeapi_test.go
The subsystem tests currently cleanup all created objects aside
from pull-secret, this change fixes that.
=> MGMT-6010 kubeAPI subsystem tests should cleanup the pull-secret

tools/check-commit-message.sh
It's really frustrating to create reverts from GitHub only to find out that CI doesn't like the selected commit message
So it will enable reverts to be considered with legal commit messages.
/cc @YuviGold @eranco74
=> NO-ISSUE allow GitHub-created reverts to be used

internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go
As SSHPublicKey string is trimmed on RegisterClusterInternal,
same behaviour should be applied on ClusterDeploymentsReconciler (updateIfNeeded)
That way, we can avoid repeating the unnecessary cluster updating.
=> OCPBUGSM-28762 cd controller: trim ssh key before update

pkg/auth/local_authenticator.go, pkg/auth/local_authenticator_test.go
We will now only go to the database to check for presence of the cluster
from the token claim once every 10 minutes.
We don't store any data in the cache because the presence of the key is
enough to authenticate the request. We also don't cache failed responses
as we don't want it to take 10 minutes for a request to succeed if a
cluster is somehow not present, but will be in the future.
cc @tsorya
=> MGMT-6067 Add a cache for the local authenticator

docs/operator.md
The PR fixes the missing "EOF" in the Hive installation manifest.
=> NO-ISSUE Fix incomplete Hive installation manifest

docs/operator.md
This PR fixes the incorrect API version for AgentServiceConfig resource
mentioned in the Operator deployment documentation.
The currently used `operators.coreos.com/v1alpha1` does not define
`AgentServiceConfig` causing the following error to be thrown
```
error: unable to recognize "STDIN": no matches for kind "AgentServiceConfig" in version "operators.coreos.com/v1alpha1"
```
Instead, `agent-install.openshift.io/v1beta1` should be used.
=> NO-ISSUE Fix apiVersion for AgentServiceConfig

deploy/operator/libvirt_disks.sh, deploy/operator/mirror_utils.sh, deploy/operator/setup_lso.sh, deploy/operator/utils.sh
This is the first step towards working on top of a disconnected environment. Next steps:
* Hive installation, at first without using OLM as hive bundle reference hive image using tag instead of digest. Next we will use OLM when it's fixed
* Assisted Installer Operator installation via OLM. This also waits for the fix by @lranjbar that will allow that
* Going afterwards HubCluster scope, allowing full SNO installation on disconnected environment.
``mirror_utils.sh`` module enables:
* mirroring relevant operator package from the relevant catalog
* disabling default indexes that are usually connected to the external registries
* merging auth files, to allow accessing both external registries and internal registries
* ``opm`` installation which is required for the mirroring process
=> MGMT-6281 mirror LSO packages to local registry

tools/handle_ocp_versions.py
Avoid copying the 'default' key to avoid a conflict
(only a single version is applicable to be default).
=> MGMT-5270 handle_ocp_versions: ignore default key

config/rbac/role.yaml, internal/bminventory/inventory.go, internal/bminventory/mock_installer_internal.go, internal/common/db.go, internal/controller/controllers/agent_controller.go, internal/controller/controllers/agent_controller_test.go, subsystem/kubeapi_test.go
This change implements a finalizer in the agent controller.
Pre-deletion logic includes host deregistration from the backend.
The same logic gets invoked when the controller attempts to reconcile
for an agent that is not found. That ensures that the backend does
not hold a DB record for a host with no agent to represent it.
The controller will also place a deletion Finalizer when:
1. `clusterDeployment` cannot be retrieved for the reconciled agent.
2. Backend cluster cannot be retrieved for the reconciled agent.
3. The agent (host) is no longer a part of the  backend cluster (day2 scenario)
Lastly, to fetch a host when we have no information about its cluster,
I added a method to query it by host ID. Once we implement [MGMT-6006](https://issues.redhat.com/browse/MGMT-6006)
we may change …
=> MGMT-4261 Deregister Host on agent CR deletion

client/installer/list_clusters_parameters.go, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/common/db.go, restapi/embedded_spec.go, restapi/operations/installer/list_clusters_parameters.go, restapi/operations/installer/list_clusters_urlbuilder.go, subsystem/cluster_test.go, swagger.yaml
UI needs the option to fetch clusters based on a list of AMS
subscription IDs instead of getting a full list of cluster each time and
filter them one by one.
=> MGMT-5415: Adding filter to GET /clusters API.

internal/cluster/cluster.go, internal/host/common.go, internal/host/host.go, internal/host/host_test.go, internal/host/statemachine.go, internal/host/transition_test.go, internal/host/validation_id.go, internal/host/validator.go, models/host_validation_id.go, restapi/embedded_spec.go, swagger.yaml
- Remove status info "Host failed to prepare for installation because cluster failed to prepare for installation".  Instead use status-info-known.
- Change event when cluster preparation failed "Failed to prepare cluster for installation. Please retry later" to "Failed to prepare cluster for installation. Something went wrong on our side, please retry later"
- Change validation-id "sufficient-or-unknown-installation-disk-speed" to "sufficient-installation-disk-speed"  (remove unknown).
/cc @avishayt
=> MGMT-6001 Misleading status after prepare-for-install error

internal/hardware/validator.go
Object inside v.VersionedRequirements.GetVersionedHostRequirements is created once and if we had sno cluster we got those values changed to sno ones.
Removing overriding code. In case of sno we will always create values from scratch
=> MGMT-6458 - Don't override hw master requirements with sno one

hack/generate.sh, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/hardware/mock_validator.go, internal/hardware/validator.go, internal/hardware/validator_test.go, internal/hardware/versioned-requirements.go, internal/hardware/versioned-requirements_test.go, internal/host/transition_test.go
Following environments variables support have been removed:
- HW_VALIDATOR_MIN_CPU_CORES_WORKER
- HW_VALIDATOR_MIN_CPU_CORES_MASTER
- HW_VALIDATOR_MIN_RAM_GIB_WORKER
- HW_VALIDATOR_MIN_RAM_GIB_MASTER
- HW_VALIDATOR_MIN_DISK_SIZE_GIB
- HW_INSTALLATION_DISK_SPEED_THRESHOLD_MS
The requirements customization can be made through `HW_VALIDATOR_REQUIREMENTS`.
=> MGMT-6438 Removed deprecated requirements env variables.

subsystem/kubeapi_test.go
We had a race were some times agent cr didn't had mac yet that cause us to create bmh with "" as mac
=> MGMT-6451 fixing flaky subsystem tests with bmh deployments

config/rbac/role.yaml, deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml, deploy/olm-catalog/metadata/annotations.yaml, docs/operator.md, internal/controller/controllers/agentserviceconfig_controller.go, internal/controller/controllers/agentserviceconfig_controller_test.go
This PR fixes a bug where a custom ConfigMap configured via the
annotation
`unsupported.agent-install.openshift.io/assisted-service-configmap`
allowed to define additional variables, but did not allow to override
the ones provided by default by the service. This was causing a
confusion in scenario when custom ConfigMap contained e.g.
```
SERVE_HTTPS: 'False'
```
but the real state of the deployment was not reflecting it correctly
```
oc rsh deployment/assisted-service
env | grep SERVE_HTTPS
SERVE_HTTPS=True
```
With this PR we are creating a ConfigMap with all the service defaults.
When creating a service container, EnvFrom field will be populated with
both default ConfigMap as well as the one created manually (if present).
In order to simplify the logic, service secrets are not mounted …
=> Bug 1957227: Allow overriding defaults via provided ConfigMap

internal/operators/ocs/validation_test.go, internal/operators/ocs/validations.go
OCS installation fails on OCP 4.8.
OCS 4.6 is not supported on OCS 4.8 but OCS 4.7 has not yet been released.
Temporarily failing OCS validation on OCP 4.8 until OCS 4.7 is available.
=> OCPBUGSM-28708, OCPBUGSM-28573 Disable OCS installation on OCP 4.8

internal/controller/controllers/agentserviceconfig_controller.go
The Operator hasn't had `HW_VALIDATOR_REQUIREMENTS` set, which led to cluster validation problems. This PR sets default hardware requirements in code producing the assisted-service config map.
=> NO-ISSUE Fix HW_VALIDATOR_REQUIREMENTS value for the operator deployment

cmd/main.go, go.mod, go.sum
This is the first commit in a series of commits tha twill add
support for Elastic's APM agent throught assisted-service.
Elastic APM will allow for tracing performance metrics for assisted-service at
every level of the application. To start with, we are focusing on the following:
- HTTP Tracing
- Logs tracing
- DB Tracing
- Specific functions tracing
This commit adds the http and logs tracing. Both of them are behind a feature flag
called EnableElasticAPM as a way to prevent it from tracing requests in every environment. The
target is to enable it for Red Hat's hosted deployments only.
Here is a (partial) screenshot of what we are after (which was part of the POC):
=> NO-ISSUE Add Elastic APM agent

internal/versions/versions.go, internal/versions/versions_test.go
In order to avoid unnecessary invocations of 'oc adm release info',
AddOpenshiftVersion now ensures that the specified release image doesn't
already exist in versions cache. Otherwise, returns the relevant
version from cache.
=> MGMT-6456 fetch OpenshiftVersion from cache by ReleaseImage

Makefile, config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml, deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml, deploy/olm-catalog/metadata/annotations.yaml, hack/generate.sh
Now that 0.0.3 is released in community-operators, this PR:
* bumps the operator version to 0.0.4
* moves the operator-bundle make target into `hack/generate.sh` scripts
and now `make generate-bundle` will build the bundle (and the rbac +
crd manifests needed to get a correct bundle)
=> NO-ISSUE: Bump operator to 0.0.4

CONTRIBUTING.md
This PR adds some examples to the contributor guide explaining commit
messages that pass CI checks for the correctness regarding JIRA and
Bugzilla trackers.
=> NO-ISSUE Add examples to the contributor guide

subsystem/kubeapi_test.go
This reverts commit 85257f61af2f8c2299d0b4be39d9f8ec22f15c86.
=> NO- ISSUE Revert "MGMT-6451 Skip flaky subsystem kubeapi test deploy clusterDeployment with agent

internal/cluster/cluster_test.go, internal/common/test_configuration.go, internal/hardware/validator.go, internal/hardware/validator_test.go, internal/hardware/versioned-requirements.go, internal/host/common.go, internal/host/host.go, internal/host/hostutil/host_utils.go, internal/host/hostutil/test_utils.go, internal/host/refresh_status_preprocessor.go, internal/host/statemachine.go, internal/host/transition_test.go, internal/host/validation_id.go, internal/host/validator.go, models/cluster_host_requirements_details.go, models/host_validation_id.go, restapi/embedded_spec.go, subsystem/day2_cluster_test.go, swagger.yaml
*Update:*
* ~~The code now incorporates a new environment variable that specifies which hosts validations to disable. This change allows this new 2 validations to be added to the code as disabled, and avoid the potential impact in production environments.~~
* ~~This PR contains the commit from #1528~~  
--------------8<-----------------------8<------------------------8<-----------------------8<------------------------------
* Adds 2 new network validations to the host profile as disabled:
* Network latency for role: Leverages on the L3 connectivity remote host object to validate that each connection between the given host and any other host with the same role has a latency lower or equal than the threshold defined in the given role (master or worker). 
* Packet loss for role: Also …
=> MGMT-4878 Add host validation for network latency

Dockerfile.assisted-service
Based on the current `Dockerfile` it looks like the minimum required version is `1.0.2`. With this change we will be installing `1.0.3`
```
[root@b44e2acbacd8 /]# nmstatectl --version
1.0.3
[root@b44e2acbacd8 /]# dnf info nmstate
Failed to set locale, defaulting to C.UTF-8
CentOS Linux 8 - AppStream                                                                                                                                                                                                                       3.0 MB/s | 6.3 MB     00:02
CentOS Linux 8 - BaseOS                                                                                                                                                                                                                          1.0 MB/s | 2.3 …
```
=> MGMT-5430 -  use the nmstate RPM

internal/bminventory/inventory.go, internal/dns/dns.go, internal/dns/dns_test.go, internal/dns/mock_dns.go
Validate the length of base DNS doman and its labels.
The lenght must adhere to the 255-bytes limitation while
allowing also for auto-generated DNS names that an OCP cluster
needs, which are created by concatenating a reserved application name,
a cluster name, and a base domain.
Example:
'alertmanager-main-openshift-monitoring.apps.test-cluster.example.com'
where 'test-cluster' is the cluster name and 'example.com' is the base
domain.
=> OCPBUGSM-26546 Validate length of base DNS domain

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/transition_test.go, pkg/ocm/accounts_mgmt.go, pkg/ocm/mock_accounts_mgmt.go, subsystem/ams_subscriptions_test.go, subsystem/cluster_test.go, subsystem/wiremock_stubs.go
openshift_cluster_id is know at an earlier stage, before installation
begin, and this is when we need to update it in AMS subscription.
Currently we are experiencing a race with the subscription created by AMS
when cluster telemetry arrives.
In case the installation fails, we will remain with an obsolete
'external_cluster_id' (aka openshift_cluster_id) in the subscription
until the user restarts the installation (and the openshift_cluster_id is
overwritten) or until the cluster is deregistered from AI DB (and
therefore the subscription deleted in AMS).
=> MGMT-6282: Split openshift_cluster_id and status 'Active' update in AMS.

openshift/template.yaml
This PR removes last traces of env variables removed in #1715:
- HW_VALIDATOR_MIN_CPU_CORES_WORKER
- HW_VALIDATOR_MIN_CPU_CORES_MASTER
- HW_VALIDATOR_MIN_RAM_GIB_WORKER
- HW_VALIDATOR_MIN_RAM_GIB_MASTER
- HW_VALIDATOR_MIN_DISK_SIZE_GIB
=> MGMT-6438 Remove references to unused env variables for hardware requiremets

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, subsystem/cluster_test.go
When returning payload for `listClusters` we should not serve `Hosts` field because it may be a lot of data. This PRs clears the field but still keeps querying for it from the db to run `AfterFind` hook which populates other info we need.
=> MGMT-4658 Remove contents of Hosts field from payload

internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go
The day1 cluster will be deleted only after we update the status and reconcile.
=> MGMT-6469 Delete Day1 only after the state is updated in CRD

internal/controller/controllers/agent_controller.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, internal/controller/controllers/common.go, internal/controller/controllers/error_utils.go
Pull secret is optional in cluster deployment but it is required for assisted service.
Get pull secret will get a reference instaed of the name directly and will check if refence is not nil
if it's nil it will return input error that will cause sync error in the sync condtion.
Added new error type to the controllers inputError type that is changed
as internal error with `IsHTTP4XXError`.
=> OCPBUGSM-29303: fix crash on undefined pull-secret

internal/versions/versions.go, internal/versions/versions_test.go
Following to https://github.com/openshift/assisted-service/pull/1748,
use full release version format (as fetched from 'oc adm release info')
when adding an OpenShift version.
The full version format (e.g. '4.8.0-fc.3') is now used in the versions
json file[*] and supported for SNO cluster creation flow.
Thus, to keep consistency and simplify, it can be used when populating the
ReleaseVersion property when adding a version (instead of truncating to '4.8.0').
[*]
https://github.com/openshift/assisted-service/blob/49567c1c7d941313f03833a1759aadd345f8900f/data/default_ocp_versions.json#L23
=> NO-ISSUE kube-api: full format for release version

deploy/olm-catalog/metadata/annotations.yaml, internal/ignition/ignition.go, internal/ignition/ignition_test.go, pkg/generator/generator.go
Make OPENSHIFT_INSTALL_INVOKER configurable to distinguish between
types of deployments (cloud, operator). The value of
OPENSHIFT_INSTALL_INVOKER goes into the `invoker` attribute of an
installed cluster via a manifest. Using different values for different
deployment types can be used for telemetry and analytics to tell the
number of clusters installed from the cloud (`invoker: assisted-installer`)
vs. clusters installed by operator deployments
(`invoker: assisted-installer-operator`).
=> MGMT-6495 Parameterize OPENSHIFT_INSTALL_INVOKER

Dockerfile.assisted-service
Packages removed in this PR were added here b41e2b6af in order to be able to build `nmstate`. Now that we are installing the RPM, we don't need these packages anymore.
```
[root@eabcc7206785 /]# nmstatectl --help
usage: nmstatectl [-h] [--version]
{commit,edit,rollback,set,apply,show,version,varlink,gc} ...
positional arguments:
{commit,edit,rollback,set,apply,show,version,varlink,gc}
commit              Commit a change
edit                Edit network state in EDITOR
rollback            Rollback a change
set                 Set network state, deprecated please consider
using'apply' instead.
apply               Apply network state
show                Show network state
version             Display nmstate version
varlink             Varlink support for libnmstate
gc …
```
=> MGMT-5430 Move assisted service image to stream8

Dockerfile.assisted-service
Reverts openshift/assisted-service#1763
Image is being replaced by OpenShift CI and causes a variety of issues for subsystem tests.
We will revert for now until it will be solved.
```
Subsystem Suite: [kube-api]cluster installation deploy clusterDeployment and infraEnv and with NMState config
/go/src/github.com/openshift/assisted-service/subsystem/kubeapi_test.go:1102
Timed out after 120.000s.
Expected
<string>: Failed to create image: 1 error occurred:\n\t* <nmstatectl gc> failed, errorCode 2, stderr usage: nmstatectl [-h] [--version] {commit,edit,rollback,set,show,version} ...\nnmstatectl: error: invalid choice: 'gc' (choose from 'commit', 'edit', 'rollback', 'set', 'show', 'version')\n, input yaml <dns-resolver:\n  config:\n    server:\n    - 192.168.126.1\ninterfaces:\n- ipv4:\n …
```
=> Revert "MGMT-5430 Move assisted service image to stream8"

hack/generate.sh
This commit: https://github.com/openshift/assisted-service/pull/1743/commits/1a6191fcff8c6fdba552371d0cdf1da6bc8e5441
of #1743 made it so the operator manifests were generated on calls to `generate_all` (ie. via `make generate-all`). The problem is that the ordering of the metadata can change at random, for example:
```
13:30:43  --- a/deploy/olm-catalog/metadata/annotations.yaml
13:30:43  +++ b/deploy/olm-catalog/metadata/annotations.yaml
13:30:43  @@ -6,9 +6,9 @@ annotations:
13:30:43     operators.operatorframework.io.bundle.package.v1: ****-service-operator
13:30:43     operators.operatorframework.io.bundle.channels.v1: alpha,ocm-2.3
13:30:43     operators.operatorframework.io.bundle.channel.default.v1: alpha
13:30:43  +  operators.operatorframework.io.metrics.project_layout: …
```
=> NO-ISSUE: don't overwrite bundle metadata

Dockerfile.assisted-service-build, Makefile, deploy/operator/deploy.sh, deploy/operator/setup_hive.sh, hack/setup_env.sh
This enables hive installation with the upstream image, without OLM mechanism.
We're doing it to keep running forwards with disconnected environment testing, as hive operator doesn't currently refers to hive image using an image digest (but by a regular tag). Soon we'll fix hive operator bundle with the correct behavior.
Hive installation now supports two modes:
* ``bash setup_hive.sh with_olm`` currently not supporting disconnected environment
* ``bash setup_hive.sh from_upstream`` currently supporting both disconnected and connected environments
The flow of the new ``from_upstream`` mode:
* Clone or pull ``openshift/hive`` repo, that includes most of the internal logic for installation from upstream images
* On disconnected environment, mirror the image to a local registry. Also …
=> MGMT-6284 install hive without OLM

internal/bminventory/inventory.go, internal/hardware/validator.go, internal/hardware/validator_test.go
When patching a cluster first we update the hosts according to the parameters (For instance updating the installation path which succeed and updates the DB)
Then calling to the inventory.updateHostsAndClusterStatus which reads a new cluster object from the DB but calling the actual update with the old host objects (contain the old installation path in our example)
The updateInventory just reverts the user selection and reselect the old installationDiskId/Path
We have another issue that changing the selected disk add more and more identical messages.
=> OCPBUGSM-29119 Can't change Installation disk

subsystem/cluster_test.go
When removing a cluster, its discovery-image should be deleted as well.
=> MGMT-6411 Discovery image deleted on cluster removal

internal/host/hostcommands/next_step_runner_cmd.go
This PR is related to an agent PR: https://github.com/openshift/assisted-installer-agent/pull/197
This PR aready merged https://github.com/openshift/assisted-service/pull/1685 and reverted https://github.com/openshift/assisted-service/pull/1691 after discovering that /run/media/iso directory does not exist for a minimal ISO
so here we mounted the /run/media directory which exist in them both
When a media disconnection error occurred the system became unstable and the step execution might be stuck on IO errors or failed with an unfriendly message.
Media disconnection occurred when a network drive (mostly PXE) has any errors (Network issue) and the controller disconnects it automatically.
Since this error is common to all the steps, we add this verification to the agent.
/run/media/iso is …
=> MGMT-4966 Mapping /run/media directory to the next_step agent

docs/baremetal-agent-controller.md
This PR extends BMAC documentation to include all the steps required to
create a fully functional assisted service deployment. It collects links
to various CRDs described in this repository and outlines a step-by-step
process of deploying them.
Some additional debugging tips&tricks are added here&there.
=> NO-ISSUE Extend BMAC documentation

README.md, docs/installer-stand-alone.md
While going through the doc for a podman install, I noticed the following typos.
"support" changed to "supports", verb agreement.
"accross" changed to "across", correct the typo.
=> NO-ISSUE: Fixing doc typos

internal/controller/controllers/clusterdeployments_controller.go, subsystem/kubeapi_test.go
The API Key for auth in the event URL is regenerated every call, causing
a change in the CRD every reconcile loop.
=> MGMT-5255 KubeAPI Update event URL only once

config/rbac/role.yaml, deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go
clusterdeployments_controller:
When a CD CR gets deleted, the controller will place a
finalizer to trigger a pre-deletion cleanup.
The cleanup includes ACI deletion, which will place a finalizer on ACI.
ACI finalizer includes backend-cluster deregister and deletion of the
cluster agent resources.
As for subsystem tests:
1. Tests will now assert for agent deletion per ACI removal.
2. Tests will now assert for agent deletion and ACI per CD removal.
3. Each test will now use a unique CD and ACI CR name - to provide better
test isolation. This was also done because deletion via finalizers
takes an additional reconcile to be fully deleted.
4. Per 2, and to avoid any cleanup bugs, the cleanup done for subsystem
tests (AfterEach) is now followed up by verifyCleanUP
P.S.
Note that this PR does …
=> MGMT-4261 Agent CR and ACI cleanup when deleting CD

docs/kube-api-conditions.md, internal/controller/controllers/agent_controller.go, internal/controller/controllers/agent_controller_test.go, internal/controller/controllers/conditions.go
Added the following ReadyForInstallation conditions for Agent Conditions::
* type: ReadyForInstallation,
status: True,
reason: AgentIsReady,
message: The agent is ready to begin the installation,
desc: If the host is approved and in status "known"
* type: ReadyForInstallation,
status: False,
reeason: AgentIsNotApproved,
message: The agent is not approved,
desc: If the host is not approved and in status "known"
=> MGMT-6531 agent conditions: check if approved

internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/common.go, internal/controller/controllers/crd_utils.go, internal/controller/controllers/crd_utils_test.go, subsystem/kubeapi_test.go
Instead of using ClusterDeployment's namespace when creating
the Agent resource, use InfraEnv's namespace.
=> MGMT-4758 use InfraEnv namespace to create the Agent

cmd/main.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/network/manifests_generator.go, internal/network/manifests_generator_test.go, internal/network/mock_manifests_generator.go
Currently all clusters send metrics to the default Telemeter server
which is the prod instance of Telemeter in the cloud.
This is wrong for 2 reasons:
1. integration/stage clusters statistics shouldn't be a part of
production dashboards.
2. integration/stage service is configured to work against integration/stage
AMS therefore, for those clusters, when metrics reaches prod
Telemeter, they will fail on authN anyway.
This change make sure each env send it metrics to the correct server or
being disabled.
=> MGMT-6437: Redirecting cluster metrics to the correct Telemeter server.

docs/kube-api-conditions.md, internal/controller/controllers/agent_controller.go, internal/controller/controllers/agent_controller_test.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, internal/controller/controllers/conditions.go
In case that the installation stopped (error or installed):
Agent:
|ReadyForInstallation|False|AgentInstallationStopped|The agent installation stopped|If the agent has stopped installing ("installed", "error")
AgentCLusterInstall:
|RequirementsMet|True|ClusterInstallationStopped|The cluster installation stopped|If the cluster has stopped installing ("installed", "error")
=> OCPBUGSM-28872 Requirement Conditions for stopped state

cmd/operator/main.go, internal/controller/controllers/agent_controller.go, internal/controller/controllers/agentserviceconfig_controller.go, internal/controller/controllers/agentserviceconfig_controller_test.go, internal/controller/controllers/bmh_agent_controller.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/common.go, internal/controller/controllers/infraenv_controller.go
This change adds logger fields to controllers to specify the
resource name and namespace that is being reconciled.
Additionally, in a case that context does not have a request-id,
we'll generate one to track it down both in controllers and the backend.
Lastly, I added a log indicating that a reconcile iteration has ended.
=> MGMT-6455 KubeAPI Controllers Debuggability: Add Logger Fields 

internal/hardware/validator.go, internal/host/host_test.go, internal/host/monitor_test.go, internal/host/transition_test.go, internal/host/validator.go, pkg/mathutils/mathutils.go
`HW_VALIDATOR_MIN_CPU_CORES` and `HW_VALIDATOR_MIN_RAM_GIB` will no longer be supported and related runtime values will be calculated based on pre-flight OCP requirements; the smaller values of the requirements for master and worker will be used.
=> MGMT-6549 Removing support for min CPU and RAM env variables

cmd/main.go, openshift/template.yaml
Right now we are using unlimited connections with default number of idle. This default value is 2. When we have burst or more than 2 routines that reaches DB in parallel assisted-service will create new db connection and then close it after finishing db call. Creating this DB connection when we have some burst of apis is relatively expensive and can increase api call for a second.  
Max open connections number will be set to 100 by default (it is default value in postgress) but in cloud default will be 600 as we have db.r5.large instance with 16G ram and by https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.MaxConnections maximum number of open connections should be less than 1800 and we have 3 instances so it should be 1800/3
=> MGMT-6633  set db connection pool

subsystem/ams_subscriptions_test.go, subsystem/manifests_test.go, subsystem/utils_test.go
In case this is not a production env, the telemeter manifest should be
visible through the manifests API.
=> NO-ISSUE: Adding subsystem-tests for telemeter manifest generation.

internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go
Clear events URL when cluster is in "installed" state.
=> MGMT-5255 KubeAPI clear events URL when "installed"

internal/controller/controllers/agentserviceconfig_controller.go
A LoadBalancer type service exposes a port on the node.
We only want the service accessible through the route.
=> NO-ISSUE Use a ClusterIP service rather than LoadBalancer

Makefile, cmd/main.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, tools/deploy_assisted_installer_configmap.py
Add a flag to disable by default the automatic creation of Day2 cluster in KubeApi.
=> MGMT-5999 Add a flag to enable day2 in kubeapi

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/validator.go, internal/common/common.go, internal/common/monitor_query_generator.go, internal/host/host.go, internal/host/host_test.go, internal/host/monitor.go, subsystem/metrics_test.go
- Add selective monitoring for cluster and hosts.  The aim is to minimize the number of entities to perform the monitoring operation on
- It is done using the update_at field, so we try to monitor only the changed clusters/hosts
/cc @tsorya 
/hold
=> MGMT-6483 Selective monitoring for cluster and hosts

internal/bminventory/inventory.go, internal/controller/controllers/infraenv_controller.go, internal/controller/controllers/infraenv_controller_test.go
To avoid needless requeues (e.g. for `BadRequest`), the InfraEnv controller
will reflect the error in conditions, but will not return it alongside `ctrl.Result`
Additionally, to avoid `http.StatusConflict` (409) coming from the backend[1], in a case of a requeue the
InfraEnv controller will wait a bit longer.
[1] https://github.com/openshift/assisted-service/blob/cf99d1fca3fe29869a9245dc7b0b2400eaf11fc3/internal/bminventory/inventory.go#L903-L914
=> OCPBUGSM-27700 Fix NMstate requeue

internal/controller/controllers/crd_events_handler.go
Increasing channels size to 200 to avoid performance issues.
Before this change, channel sizes were set to 1, which blocks per-each
event, until it got consumed.
=> MGMT-6634 Increase kubeAPI event channels size to 200

internal/ignition/ignition.go
when modifying BMH on bootsrap, we need to not output Status field,
so that cluster bootsrap won't try to update it. since BMHStatus is
a struct in BMH, we need to splice a output string itself
=> OCPBUGSM-27828 - do not output Status field to the BMH on bootstrap

docs/kube-api-conditions.md, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, internal/controller/controllers/conditions.go
Added the following RequirementsMet conditions for AgentClusterInstall:
* type: RequirementsMet,
status: False,
reason: InsufficientAgents,
message: The cluster currently requires `X` agents but only `Y` are ready,
desc: If the cluster is ready but we don't have the expected number of ready agents
* type: RequirementsMet,
status: False,
reeason: UnapprovedAgents,
message: The installation is pending on the approval of `X` agents,
desc: If the cluster is ready with the expected number of ready agents, but not all have been approved
=> MGMT-6005 conditions for ready and approved agents

docs/crds/agentClusterInstall-SNO.yaml, docs/crds/agentClusterInstall.yaml, docs/crds/clusterDeployment.yaml, docs/crds/clusterImageSet.yaml, docs/crds/infraEnv.yaml
The purpose of those CRD examples is for everyone to
have out-of-the-box working examples.
Updates:
1. Image tag set to a valid tag, currently 4.8.0-fc.3-x86_64
2. Some CRDs refer to single-node and some to the multi node cluster. This change fixes that.
3. Commented out the 'you-ssh-key-here' (which are optional) as it fails for backend validations.
=> MGMT-6650 Example CRDs update with clusterImageSet tag and SNO cluster name

cmd/main.go
Signed-off-by: Ondra Machacek <omachace@redhat.com>
=> MGMT-5251: Print OpenshiftVersions data instead of memory address

internal/controller/controllers/infraenv_controller.go, subsystem/kubeapi_test.go
In order to support deploying infraenv CRD before CD/ACI
when using a different namespace, list infraenvs from all namespaces.
=> OCPBUGSM-29619 map clusterdeployment to infraenv from all namespaces

internal/controller/controllers/agentserviceconfig_controller.go, internal/controller/controllers/agentserviceconfig_controller_test.go
See PR #1756
By setting `INSTALL_INVOKER` to `assisted-installer-operator`, we
can distinguish clusters installed by the operator from clusters
installed by other assisted service deployments, e.g. the cloud.
The value of `INSTALL_INVOKER` is written to a cluster manifest like
```
[core@master-0 ~]$ cat /var/opt/openshift/manifests/openshift-install-manifests.yaml
...
data:
invoker: assisted-installer-operator
```
This field will be used by telemetry. Cloud installations will continue
to have `invoker: assisted-installer` as today.
=> MGMT-6514 Set invoker for assisted operator

pkg/s3wrapper/util.go, pkg/s3wrapper/util_test.go
Before this change if the GET request here failed in a way that didn't
produce an error we would continue on to try to extract the boot files
from the error response body.
According to https://golang.org/pkg/net/http/#Get non-200 responses do
not generate an error so we need to check this ourselves.
https://bugzilla.redhat.com/show_bug.cgi?id=1962957
=> Bug 1962957 - Check the response status code when downloading files

internal/controller/controllers/bmh_agent_controller.go, subsystem/kubeapi_test.go
This adds a Complete function to the `reconcileResult` interface so that it will be
possible to signal the main Reconcile function to return early after some of the
steps. This will help reducing queries, reconcile steps, and checks when we already
know that we are not ready to run those.
=> OCPBUGSM-28683: Allow to signal when the Reconcile should return

cmd/main.go
By not exporting it, it is not getting the value from the env variable
it is set to but instead an empty value.
=> OCPBUGSM-29655: Exporting the variable that supposed to hold the data.

cmd/main.go, subsystem/kubeapi_test.go, tools/deploy_assisted_installer.py
When cluster is deregistered, either by clusterdeployment or by the API,
the cluster record is softly deleted, meaning the  attribute `deleted_at`
in the DB is being set.
It is the responsiblity of the garbage collector to run periodically and
remove all of the cluster's resources.
For that purpose, the garbage collection should be enabled for clearing
cluster resources in operator deployment as well.
=> OCPBUGSM-29066 Remove cluster resources after clusterdeployment deletion

config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml, config/crd/resources.yaml, deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml, internal/controller/api/hiveextension/v1beta1/agentclusterinstall_types.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go
A new LogsURL field was added to AgentClusterInstall DebugInfo
field. It contains a link for download the controller (cluster)
logs which is available until the installation is completed.
```
Name:         test-infra-cluster-assisted-installer-agent-cluster-install
Namespace:    assisted-installer
Labels:       <none>
Annotations:  <none>
API Version:  extensions.hive.openshift.io/v1beta1
Kind:         AgentClusterInstall
Metadata:
Creation Timestamp:  2021-05-27T15:05:44Z
Finalizers:
agentclusterinstall.agent-install.openshift.io/ai-deprovision
Generation:  2
Managed Fields:
API Version:  extensions.hive.openshift.io/v1beta1
Fields Type:  FieldsV1
fieldsV1:
f:spec:
.:
f:apiVIP:
f:clusterDeploymentRef:
.:
f:name:
f:imageSetRef:
.:
f:name:
f:ingressVIP:
f:networking:
.:
f:clusterNetwork: …
```
=> MGMT-5422 AgentClusterInstall - Added LogsURL field

openshift/template.yaml
Support for HW_VALIDATOR_MIN_CPU_CORES and HW_VALIDATOR_MIN_RAM_GIB has been removed from code and they can be safely removed from template.yaml
=> MGMT-6549 Remove HW_VALIDATOR_MIN_* references in template.yaml

internal/ignition/ignition.go
This PR adds a handler for a failure scenario of `agent.service` which
removes the `assisted-installer-agent` container image.
This is a workaround for an issue where symlinks in `/var/lib/containers/`
are corrupted. Deleting an image in `ExecStartPre` means that every time
agent.service starts we make sure the image is available. If it's the
very first attempt to start `agent.service`, then the the image will be
pulled as it would be in any other scenario. Any consecutive attempt to
start `agent.service` will first check if the image is present and in
case of errors will remove it so that it can be pulled again.
We are not using the `OnFailure` directive because the unit defined
there would only be started once all the restarts attempts are exhausted
which is not a desired workflow in …
=> Bug 1964591: Remove AI Agent image in case of service failure

deploy/operator/libvirt_disks.sh, deploy/operator/setup_lso.sh, deploy/operator/utils.sh
The way disks were created didn't guarentee the disks locations as we
expect them to be for the localvolume.
In order to make an absolute expected destination, we should provide a
WWN hash that would be available as a link on
/dev/disk/by-id/wwn-<hash>.
The WWN token has to begin with a number, so it was prefixed with an
hardcoded 0 and afterwards 15 bytes of a digested hash from the original
disk name.
/cc @osherdp @michaellevy101
=> MGMT-6605 Create disks with WWN

internal/bminventory/inventory.go, internal/bminventory/mock_installer_internal.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go
If user deleted ClusterDeployment or AgentClusterInstall while the
cluster is installing, cancel is needed before deleting the backend
cluster.
=> Bug 1947154: Kubeapi cancel install before delete

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/controller/controllers/infraenv_controller.go, subsystem/kubeapi_test.go
The InfraEnv controller passes ImageCreateParams to the backend per
each reconcile, letting it decide whether or not it should generate a new image.
In turn, the backend clears up the image download URL, which eventually filled
the same URL when auth=none. However, when Assisted-Service configuration is
set to with auth=local and s3, a new URL will be generated both with a new or re-used image.
The above scenario caused the BMH, which is watching infaEnv and specifically
looks at the URL to retrigger hosts install.
This change will not clear up the URL only if the image does
not exist and will generate a URL only in a case of a newly generated image.
Lastly, the change included ed some debug-level
prints that helped to understand the issue.
Co-authored-by: Michael Filanov …
=> BUG 1965990: Keep Image URL for existing image with auth=local + S3

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
We should block api_vip_allocation in none platform as it is blocked in
sno already. Right now we block it in register cluster but allow in
update. This code should block it on update
=> MGMT-4189 - block in update cluster setting API VIP DHCP allocation when user_managed_network is set

cmd/main.go, internal/controller/controllers/bmh_agent_controller_test.go, internal/controller/controllers/common.go, internal/controller/controllers/spoke_cluster.go
The controller client, spokeClient, and tests client all register the
runtime.Scheme differently. This has led to bugs like the one linked to
this commit where the controller tries to interact with a custom
resource but doesn't have the right Scheme registered.
This commit uifies the process used to register these Schemes so that
the same one used everywhere. This prevents having schemes registered
for tests that are not registered in the real client and the other way
around.
=> OCPBUGSM-29621 Unify client Scheme registration

deploy/operator/setup_assisted_operator.sh
We'll go over used images for assisted-installer, controller, agent and postgres, get their registries and add them to the ``PUBLIC_CONTAINER_REGISTRIES`` config.
That will enable us to use images from prow's registries based on the cluster we're running on (build01, build02 or any other cluster).
No patch to ocm-2.3 is needed, as we use upstream code on CI.
=> enable defining public registries that should not be validated against PS

internal/cluster/transition.go, internal/cluster/transition_test.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go
In the case of the SNO cluster, set the api_vip and ingress_vip property in the backend upon
starting the installation, and remove it upon reset.
Ref: https://issues.redhat.com/browse/MGMT-6014
=> MGMT-6014: Missing VIP values in SNO cluster

docs/Kube-API.md
After changes to hyperthreading API, This example should reflect
The addition of the 'name' field. Otherwise, it does not apply
correctly
=> Bug 1965356 - Add `name: master` to the InstallConfig override example

internal/constants/scripts.go, internal/ignition/ignition.go
The current version of the NM in the 4.8 does not support priority between nmconnections
Until this is fixed, we need to remove default.nmconnection file (so that it won't interfere
with ours static network nmconnections) both in minimal and full ISO
=> Bug 1966268 - remove default.nmconnection as a WA for NM priority issue

internal/controller/controllers/agentserviceconfig_controller.go, openshift/template.yaml
This PR changes the default value of `CHECK_CLUSTER_VERSION` to True so
that deployments wait for the CVO to be ready before marking the cluster
as deployed.
This makes the behavior of operator-managed clusters consistent with
cloud deployments.
Closes: [OCPBUGSM-29806](https://issues.redhat.com/browse/OCPBUGSM-29806)
Configuration of the assisted-service
```
[...]
Name:         assisted-service
Namespace:    assisted-installer
Labels:       <none>
Annotations:  <none>
Data               
====
[...]
CHECK_CLUSTER_VERSION:      
----                       
True       
[...]
```
From the `pod/assisted-installer-controller-cqv69` on the target SNO
```
time="2021-06-02T12:47:18Z" level=info msg="Waiting for cluster version operator: true"
[...] …
```
=> Bug 1966485: [operator] Wait for CVO to be ready before marking as done

docs/Kube-API.md, docs/crds/infraEnv.yaml
A documentation update to kubeAPI docs and examples to clarify that the `infraEnv.Spec.pullSecretRef` is currently ignored by infraEnv controller.
/assign @rollandf 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message- …
=> Bug 1967121: Docs should clarify that the pullSecretRef is currently ignored

deploy/operator/utils.sh
Seems that sometimes the ZTP workflow is failing to wait for the pod.
This PR extends the waiting time from 10 minutes to 20 minutes.
/assign @RazRegev  …
=> NO-ISSUE: Extend waiting for pod to 20 minutes

deploy/operator/deploy.sh, deploy/operator/libvirt_disks.sh, deploy/operator/mirror_utils.sh, deploy/operator/setup_assisted_operator.sh, deploy/operator/setup_hive.sh, deploy/operator/setup_lso.sh
This will enable full environment installation of the Assisted Service operator.
On disconnected mode, it will mirror the assisted-service-operator package from given ``INDEX_IMAGE``, create a ``CatalogSource`` for mirrored index, and use it for the installation.
/cc @YuviGold @lranjbar
=> MGMT-6286 install AI operator on disconnected env

docs/Kube-API.md
Changin the example from hyperthreading to OVNKubernetes since hyperthreading
should be set in the main API and not via overriding
Some PRs addess specific issues. Please, refer to the [CONTRIBUTING] documentation for more
- Should this PR be tested …
=> Bug 1965356: Change install config override example to OVNKubernetes

internal/controller/controllers/infraenv_controller.go
The infraEnv controller doesn't have a way to know how many NMStateConfigs to anticipate.
Since the controller watches for NMStateConfig changes and invokes image regeneration per each NMStateConfig addition/removal/update, it would help to log the amount of NMStateConfigs in each image generation.
/assign @filanov …
=> OCPBUGSM-29957: InfraEnv should log the amount of NMstate Configs baked into the image

internal/operators/ocs/ocs_operator.go, internal/operators/ocs/ocs_operator_test.go
The ValidateHost method should not check the operator resource requirements. It has been changed to validate only non-resource requirements.
=> MGMT-6607: (OCS) remove resource checks in ValidateHost

internal/network/manifests_generator.go
Bug: 1963949
To allow documented customization, index at the beginning of the name and the file name is mandatory for every manifest
All
- [] Should this PR be backported?
=> OCPBUGSM-29525 Assisted installer chrony manifests missing index numbering

internal/cluster/validations/validation_test.go, pkg/auth/auth_handler_test_utils.go, pkg/auth/authenticator_test.go, pkg/auth/authz_handler_test.go, pkg/auth/local_authenticator_test.go, pkg/auth/rhsso_authenticator.go, pkg/auth/rhsso_authenticator_test.go
When running inside a VM (like minikube) the service clock may be slightly
late, therefore this validation can failed.
The validation will be removed in jwt-go v4 anyway and this is just a
work around in the meantime.
Without this fix, running e2e flow locally using auth will most probably
fail on that error.
=> MGMT-6533: Skip "Token used before issued" validation in jwt-go.

deploy/operator/README.md
Just fixing docs, as we have better configuration options in dev-scripts right now.
It's only docs, but this configuration is already running on CI.
/assign @lranjbar @YuviGold @eranco74
=> Fix docs to make use of 'EXTRA_WORKER_<X>' configurations

Makefile, subsystem/metrics_test.go
The test was using ginkgoWriter to print the metrics in case of failure
for debugging, but the issue was this buffer was filled multiple times
in each test, therefore, when printed, it duplicated the printed metrics
multiple times.
This fix is making sure the buffer gets written only once in each test.
Please, add one or two reviewers that …
=> NO-ISSUE: Fixing metrics subsystem-test's spamming.

deploy/operator/gather.sh
- export downloaded to file instead of piping into `jq`
- [] Cloud
- [] None
/assign @
/assign @ …
=> NO-ISSUE: ztp flow output log to file

deploy/operator/gather.sh
Downloading the logs from service running with HTTPS require `-k` arg to curl.
- [] None
- [] Does this change includes unit-tests (note that code changes require unit-tests)
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull …
=> NO-ISSUE: ztp flow download log as insecure

Makefile, docs/Kube-API.md, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go, tools/deploy_assisted_installer_configmap.py
Currently, once the cluster is installed, the day1 backend cluster is deleted.
Therefore the events and logs are not available anymore.
In this patch, the day1 is not deleted.
Note that day2 functionality will not work anymore and will need to be
revisited when the support for it will be required.
Test-infra run: debug URLs still available after install finished
```
- lastProbeTime: "2021-06-02T14:31:05Z"
lastTransitionTime: "2021-06-02T14:31:05Z"
message: The installation has stopped because it completed successfully
reason: InstallationCompleted
status: "True"
type: Stopped
connectivityMajorityGroups: '{"192.168.126.0/24":[],"192.168.141.0/24":[]}'
debugInfo:
eventsURL: http://10.1.37.42:6000/api/assisted-install/v1/clusters/76fb3d0f-f06f-4501-be6d-f …
```
=> Bug 1966546: KubeAPI keep day1 cluster after install

internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go
The clusterDeployments invokes AddOpenshiftVersion() with parameters
coming from clusterImageSet[1]. If it fails, (e.g. bad URL or it is
just unreachable at the moment), the controller currently requeues every 10s.
The controller should keep trying since we cannot currently determine the
reason for the failure. However, in this case, it should wait for
1 minute and not 10 seconds.
[1] https://github.com/openshift/assisted-service/blob/master/docs/crds/clusterImageSet.yaml
Testing by unit tests and manually by misconfiguring clusterImageSet and inspecting the svc log.
/assign @danielerez 
/assign @rollandf 
/assign @filanov  
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#com …
=> Bug 1967423: CD ctrl reqeueue after 1m when failing with AddOpenshiftVersion

docs/Kube-API.md, docs/crds/infraEnv.yaml
This reverts commit 0ced328781d5683f5f464b8c095f3bd99d358bcd.
/assign @rollandf  …
=> OCPBUGSM-30068: Revert "Docs should clarify that the pullSecretRef is currently ignored (#1898)"

OWNERS_ALIASES
=> NO-ISSUE: Add djzager to ci-reviewers

cmd/main.go, internal/controller/controllers/bmh_agent_controller_test.go, internal/controller/controllers/common.go, internal/controller/controllers/spoke_cluster.go
The controller client, spokeClient, and tests client all register the
runtime.Scheme differently. This has led to bugs like the one linked to
this commit where the controller tries to interact with a custom
resource but doesn't have the right Scheme registered.
This commit uifies the process used to register these Schemes so that
the same one used everywhere. This prevents having schemes registered
for tests that are not registered in the real client and the other way
around.
=> [ocm-2.3] Bug 1966947: Unify client Scheme registration

deploy/operator/README.md, deploy/operator/setup_assisted_operator.sh, deploy/operator/ztp/deploy_spoke_cluster.sh
Configuring BMO to watch all namespaces is more relevant as a hub-cluster configuration than spoke cluster configuration.
/assign @lranjbar 
=> move provisioning configuration for watching all namespaces to hub deployment

Jenkinsfile
Signed-off-by: Lisa Rashidi-Ranjbar <lranjbar@redhat.com>
Fixes a small bug where the wrong format date string was used. 😅 
I've been using the Jenkins replay functionality to test Jenkins changes:
Here is the manual replay log:
http://assisted-jenkins.usersys.redhat.com/job/assisted-service/job/ocm-2.3/36/console
First one is YMMdd (new), second is Ymd (current) third is H for the current hour.
/assign @djzager 
=> NO-ISSUE: Fix bug in the date for ocm tag

internal/controller/controllers/agentserviceconfig_controller.go
This updates the agent service config controller to use `log.Infof` so
that the name of the configmap is properly included in the formatted log
message.
/assign @flaper87 
- ~[] Does this change include unit-tests (note that code changes require unit-tests)~
=> [ocm-2.3] Bug 1966989: asc controller log line

docs/Kube-API.md
Some of the documentation for setting install config override in KubeAPI was still referencing ClusterDeployment instead of AgentClusterInstall.
/assign @nmagnezi  …
=> OCPBUGSM-30087: Fix doc for installconfig on ACI

docs/operator.md
This PR changes the documentation of the operator in the part describing
how to override environment variables of the assisted-service container.
Instead of `kubectl apply` we are using `oc annotate` so that we do not
recreate AgentServiceConfig resource but only patch the required
annotation (in this case `assisted-service-configmap`). This is caused
by the fact that using `kubectl apply` in case AgentServiceConfig
already exists and has its PersistentVolumeClaim created results in the
following error
```
"Failed to ensure filesystem storage: PersistentVolumeClaim \"assisted-service\"
is invalid: [spec.resources[storage]: Required value, spec: Forbidden: spec
is immutable after creation except resources.requests for bound claims\n  core.PersistentVolumeClaimSpec{\n  \tAccessModes: …
```
=> NO-ISSUE Use `annotate` instead of `apply` for AgentServiceConfig annotation

cmd/main.go
uploadISO flow from the main thread created contexts with no requestID. This commit adds the missing ID
/assign @
/assign @ …
=> OCPBUGSM-30145: Missing request ID field on image uploading logs

pkg/s3wrapper/util.go, pkg/s3wrapper/util_test.go
Before this change if the GET request here failed in a way that didn't
produce an error we would continue on to try to extract the boot files
from the error response body.
According to https://golang.org/pkg/net/http/#Get non-200 responses do
not generate an error so we need to check this ourselves.
This was previously addressed for s3 in b8d2b084 which uses a separate
function for downloading the iso.
https://bugzilla.redhat.com/show_bug.cgi?id=1962957
https://issues.redhat.com/browse/OCPBUGSM-29458
For a manual test I deployed the operator to my CRC instance on my laptop configured to deploy a service image built from my branch. I then created a service to host the iso images and deployed it to the `assisted-installer` namespace. I created an …
=> OCPBUGSM-29458: Check the response status code from http.Get

internal/controller/controllers/bmh_agent_controller.go
The reconcileBMH function already verifies whether the InfraEnv URL has changed or not. The InfraEnv watcher doesn't, tho.
This commit checks whether the BMH should be reconciled based on the InfraEnv info, before queuing the request. The check is
now used by both, the watcher and the reconcileBMH function
=> Bug 1969304: Don't queue BMH reconcile if the InfraEnv URL hasn't changed

internal/controller/controllers/bmh_agent_controller.go, internal/controller/controllers/bmh_agent_controller_test.go
Detached BMH resources are not considered to be part of the hub cluster as they belong
to a spoke cluster that has been installed already. Therefore, BMAC should not reconcile
these resources. This change will prevent re-deploying installed clusters when an ISO is
re-generated, which is the desired behavior.
Users that want to redeploy a node that has been installed will have to remove the
label from the BMH manually.
Signed-off-by: Flavio Percoco <flavio@redhat.com>Detached BMH resources are not considered to be part of the hub cluster as they belong
to a spoke cluster that has been installed already. Therefore, BMAC should not reconcile
these resources. This change will prevent re-deploying installed clusters when an ISO is
re-generated, which is the desired behavior.
Users that want to …
=> OCPBUGSM-30082: Don't reconcile BMH in a detached state

internal/controller/controllers/controller_event_wrapper.go
Since operator-based deployments will not report to ELK, metric events are disabled for such deployments
to save space in the db
/assign @
/assign @ …
=> OCPBUGSM-30278: disable metrics event when deploying via operator

config/crd/bases/agent-install.openshift.io_agents.yaml, config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml, config/crd/resources.yaml, deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml, deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml, internal/controller/api/hiveextension/v1beta1/agentclusterinstall_types.go, internal/controller/api/v1beta1/agent_types.go, internal/controller/controllers/agent_controller.go, internal/controller/controllers/agent_controller_test.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go
For better visibility of the install process, populate State and StateInfo in Agent and AgentClusterInstall CRDs.
Also, move to "DebugInfo" struct.
Output for Agent CR:
```
debugInfo:
eventsURL: http://10.1.37.42:6000/api/assisted-install/v1/clusters/6146e211-c6b0-49a6-b3a2-af3e85bbcfc6/events?api_key=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVyX2lkIjoiNjE0NmUyMTEtYzZiMC00OWE2LWIzYTItYWYzZTg1YmJjZmM2In0.dqA9LnGgkFpB-Mc0w8LN9Or8W-OECPbZO_zrJj2-lROgujZS-29ydOh0ro99pRsiYhDza47bViF_mTkbWR43ng&host_id=764254a7-36a6-4d79-aac9-29d50fa36305
state: installed
stateInfo: Done
```
Output for AgentClusterInstall CR:
```
debugInfo:
eventsURL: http://10.1.37.42:6000/api/assisted-install/v1/clusters/6146e211-c6b0- …
```
=> OCPBUGSM-30346: Populate State and StateInfo and move to DebugInfo in CRDs

cmd/main.go, internal/common/db.go, internal/controller/controllers/controller_event_wrapper.go, internal/controller/controllers/controller_event_wrapper_test.go, internal/controller/controllers/controllers_suite_test.go, internal/controller/controllers/crd_utils.go, internal/controller/controllers/crd_utils_test.go, internal/host/host.go, internal/host/host_test.go, internal/host/hostcommands/instruction_manager_test.go, internal/host/hostutil/test_utils.go, internal/host/mock_host_api.go, subsystem/kubeapi_test.go
As Agents are now created using InfraEnv namespace, 'NotifyAgentUpdates'
should be invoked using the namespace of the host instead of the cluster.
Hence, added 'kube_key_namespace' to Host struct (similar to Cluster)
in order to store the proper namespace upon Agent CR creation.
Some PRs addess specific issues. Please, refer to the [CONTRIBUTING] documentation for more
Tested using crd_utils unit-tests and …
=> OCPBUGSM-30056: host namespace on agent update notification

deploy/operator/gather.sh
Add ClusterDeployment and ClusterImageSet to ZTP CI gather. …
=> ZTP CI gather more CRDs

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
The purpose of this PR is to mark the host as failed and show an indicative error to the user via the AI UI.
The assisted-installer-agent returns a special exit code (256) which indicates to the assisted-service PostReply that media disconnection  event has occurred.
This PR is the completion of the media disconnection EPIC.
https://github.com/openshift/assisted-service/pull/1780
https://github.com/openshift/assisted-installer-agent/pull/197
=> MGMT-6747 Media disconnection: Mark host as failed and show an Indicative error

internal/controller/controllers/agentserviceconfig_controller.go
This updates the agent service config controller to use `log.Infof` so
that the name of the configmap is properly included in the formatted log
message.
Cherry pick of https://github.com/openshift/assisted-service/pull/1946 to try and address my failure to follow the correct procedure.
=> Bug 1970494: asc controller log line (#1946)

go.mod, internal/bminventory/inventory.go, internal/cluster/validations/validation_test.go, internal/cluster/validations/validations.go
Before OCP 4.8.0-fc4, it wasn't possible to use the wildcard (`*`) as a NoProxy value, meaning "bypass proxy for all destination". As https://bugzilla.redhat.com/show_bug.cgi?id=1947066 has been fixed, we want to re-enable `*` as a valid NoProxy value, but only for OCP versions 4.8 and later.
This removes (for OCP 4.8 and up) the restriction put by #1409.
It also cancels a need for UI changes as part of [MGMT-5267](https://issues.redhat.com/browse/MGMT-5267): Hide the possibility to use * as a valid no-proxy value until it becomes possible.
IMPORTANT: Successful installation is not sufficient - the cluster must be finalized and functional.
Testing:
1. Build a custom assisted service with this fix.
2. Choose a random IP that is not routeable in your …
=> MGMT-6647: Allow wildcard NoProxy with OCP 4.8+

internal/cluster/cluster.go, internal/cluster/cluster_test.go
When cluster is being removed, the folder cluster remains on the FS.
The GC needs to make sure that no leftovers remains after the cluster was removed.
=> OCPBUGSM-30014: Cluster folder should be cleared from FS

internal/network/manifests_generator.go, internal/network/manifests_generator_test.go, subsystem/manifests_test.go
Until now, in the service, we changed the default behavior of openshift,
which is to always send cluster metrics to prod-telemeter-server unless
changed by the user, and we:
* left untouched clusters created by cloud prod env
* redirected to telemeter-stage stage clusters
* redirected to dummy-url all other clusters
The issue with this approach is that all prod clusters that aren't
created in the cloud, operator clusters for example,  will fail to
deliver telemetry.
Instead, we will now default to prod-telemeter instead of dummy-url
unless we know better:
* left untouched clusters created by ALL prod envs (not just cloud)
* redirect to telemeter-stage stage clusters
* redirect to dummy-url integration clusters
Please, select one or more if …
=> OCPBUGSM-30853: Change default telemeter server of installed clusters to prod.

internal/controller/controllers/bmh_agent_controller.go, internal/controller/controllers/bmh_agent_controller_test.go
Currently for the `baremetalhost.metal3.io/detached` annotation we are
using `"true"` as a value whenever we decide to create it. Given that,
based on the behaviour of the baremetal-operator, this annotation
accepts string and not a boolean, it may create a confusion if an
administrator decides to set the value to e.g. `"false"` or
`"disabled"`.
It is a design decision in the upstream that the annotation could
provide a context from whatever external system the annotation is coming
from and that the value itself is completely ignored.
/assign @flaper87
=> NO-ISSUE: Change default value for BMH_DETACHED_ANNOTATION

docs/pull_request_template.md
The pull request template currently suggests usin /assign to add reviewers to the PR. This
duplicates the number of people associated to a PR since the bot will add 2 people to the
reviewers section, in addition to the 2 assignees added with /assign.
Switch from using /assign to using /cc to only have 2 (and relevant) people added to the PR.
- Any logs, screenshots, etc that can help with the review …
=> NO-ISSUE: Use /cc instead of /assign to link PRs to users

internal/controller/controllers/agentserviceconfig_controller.go
This PR fixes the INFO logline printed when an operator requests the
assisted-service deployment to be configured using a manually created
ConfigMap.
In the current version the log line does not render the name of the
ConfigMap correctly, so that the message appearing in the logs looks as
follows
```
level=info msg="ConfigMap %v being used to configure [...]
```
Closes: [OCPBUGSM-30263](https://issues.redhat.com/browse/OCPBUGSM-30263)
Using the `quay.io/mkowalski/assisted-service:bz1969796-2` image I got the following log entry
```
time="2021-06-15T08:20:10Z" level=info msg="ConfigMap my-assisted-service-config from namespace assisted-installer-bz1969796-2 being used to configure assisted-service deployment" agent_service_config=agent …
```
=> Bug 1969796: Fix logline containing ConfigMap for AgentServiceConfig

config/crd/bases/agent-install.openshift.io_agents.yaml, config/crd/resources.yaml, deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml, internal/controller/api/v1beta1/agent_types.go, internal/controller/controllers/agent_controller.go, internal/controller/controllers/agent_controller_test.go, subsystem/kubeapi_test.go
Agent CRD Status:
- Populate NTP Sources and Bootstrap fields.
- Add and populate Role field.
Output from subsystem Agent CR:
```
ntpSources:
- sourceName: clock.dummy.com
sourceState: synced
progress: {}
role: auto-assign
```
/assign @nmagnezi 
/assign @danielerez 
=> OCPBUGSM-30076: Add role, bootstrap and ntp sources to Agent CR

deploy/operator/gather.sh, deploy/operator/setup_hive.sh
Doing a couple of changes:
* Gathering data relevant to hive
* Enable configuring hive namespace
* Installing only on given namespace, instead on ``openshift-operators`` (which actually means on all namespaces)
/cc @lranjbar @YuviGold 
=> Gather hive logs on CI

deploy/operator/deploy.sh
Make operator deploy.sh exit in case of error
/cc @osherdp 
/cc @flaper87  …
=> NO-ISSUE: Make operator deploy.sh exit in case of error

deploy/operator/setup_hive.sh
In #2006 , I've changed installation of hive to occur on top of hive namespace instead of installing it on all namespaces.
What I forgot to do is to actually create the namespace.
This will take care of the failing job.
- [] None
- [] Manual (Elaborate on how it was tested)
Just ran it on my local environment.
/cc @YuviGold
=> Fix hive installation to create namespace and OperatorGroup

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/bminventory/mock_installer_internal.go, internal/controller/controllers/agent_controller.go, internal/controller/controllers/agent_controller_test.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, internal/controller/controllers/infraenv_controller.go, internal/controller/controllers/infraenv_controller_test.go, internal/network/machine_network_cidr.go, subsystem/cluster_test.go
[OCPBUGSM-26021](https://issues.redhat.com/browse/OCPBUGSM-26021):  Can't proceed beyond the first wizard screen, if a cluster already has VIPs but no hosts
- Do not force that machine network can be calculated during update
[OCPBUGSM-28971](https://issues.redhat.com/browse/OCPBUGSM-28971): The VIP fields remain disabled when de-selecting DHCP
- Return machine CIDR after setting VIPs when in interactive mode (REST)
[OCPBUGSM-27652](https://issues.redhat.com/browse/OCPBUGSM-27652): Assisted service not returning an error when setting API/Ingress vip outside of CIDR
- Perform VIPs verification when updating them throgh REST API
how this code was tested. Here are some …
=> UpdateCluster changes for REST API

docs/operator.md
AgentServiceConfig examples in operator.md doc should each contain databaseStorage + filesystemStorage
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1968125
/assign @djzager 
/assign @flaper87 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#co …
=> OCPBUGSM-30063: Bug 1968125: AgentServiceConfig examples in operator.md doc should each contain databaseStorage + filesystemStorage

deploy/operator/deploy.sh, deploy/operator/mirror_utils.sh, deploy/operator/setup_assisted_operator.sh
Mirroring RHCOS and Rootfs images to a HTTP local mirror, for handling the disconnected environment flow on CI.
This will require two more options: one for the directory serving all files, and one for the matching URL of the files.
/cc @YuviGold @lranjbar
=> MGMT-6286: add image mirroring in service installation automation for CI

internal/network/manifests_generator.go, internal/network/manifests_generator_test.go, subsystem/manifests_test.go
Until now, in the service, we changed the default behavior of openshift,
which is to always send cluster metrics to prod-telemeter-server unless
changed by the user, and we:
* left untouched clusters created by cloud prod env
* redirected to telemeter-stage stage clusters
* redirected to dummy-url all other clusters
The issue with this approach is that all prod clusters that aren't
created in the cloud, operator clusters for example,  will fail to
deliver telemetry.
Instead, we will now default to prod-telemeter instead of dummy-url
unless we know better:
* left untouched clusters created by ALL prod envs (not just cloud)
* redirect to telemeter-stage stage clusters
* redirect to dummy-url integration clusters
This PR clones …
=> Bug 1971589: Change default telemeter server of installed clusters to prod. (#1988)

cmd/main.go, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, models/cluster_default_config.go, restapi/embedded_spec.go, subsystem/cluster_default_config_test.go, subsystem/subsystem_suite_test.go, swagger.yaml
The UI want to warn the user that the kubeconfig/logs files won't be kept
in the service forever and he needs to download them.
In order to do that it needs the GC configuration.
```
$ curl -s $(minikube service assisted-service -n assisted-installer --url)/api/assisted-install/v1/clusters/default-config | jq '.'
{
"cluster_network_cidr": "10.128.0.0/14",
"cluster_network_host_prefix": 23,
"inactive_deletion_hours": 480,         <---------
"ntp_source": "",
"service_network_cidr": "172.30.0.0/16"
}
```
- …
=> MGMT-6628: Exposing the deregistration time on cluster API.

OWNERS_ALIASES
Add Lisa to owners for reviews :)
/cc @djzager 
/cc @flaper87 
=> NO-ISSUE: Add lranjbar to OWNERS_ALIASES

internal/oc/release.go, internal/oc/release_test.go
In order to avoid redundant calls to 'oc adm release info',
caching image when fetched from OCP release.
For simplicity, images map is maintained under release struct
in the following format: image name > release image URL > image URL.
The cache functionality could be tested by verifying that each image (machine-config-operator/must-gather) is fetched only once. The following info message should be available in the assisted-service log for each image: "Fetching image from OCP release...".
/assign @tsorya 
/assign @omertuc 
=> OCPBUGSM-30211: cache image fetched from release

internal/metrics/metricsManager.go
Add stage result to the result duration event 
/cc @slaviered
=> NO-ISSUE Add results to cluster.installation.results internal event

internal/controller/controllers/agentserviceconfig_controller.go
Cluster-wide proxy configuration (if exists) is automatically injected by OLM into the operators. But it is the responsibility of an operator to propagate the configuration to its operands. By copying proxy configuration from assisted installer operator to assisted service we make sure assisted service pods can communicate outside, for instance for extracting data from the OCP release image.
1. Deploy an IPv6-only cluster using test infra `make run_full_flow_with_install IPv6=yes IPv4=no VIP_DHCP_ALLOCATION=no PROXY=yes OPENSHIFT_VERSION=4.8`. The cluster cannot directly access quay.io.
2. Build a custom operator index image that includes the fix.
3.  Deploy the custom operator image `make deploy_assisted_operator INDEX_IMAGE=<fixed-index-image> KUBECONFIG=./build/kubeconfig …
=> Bug 1967956: Propagate proxy config to service

internal/bminventory/inventory_test.go, internal/cluster/cluster_test.go, internal/common/test_configuration.go, internal/host/host_test.go, internal/network/manifests_generator.go
As a convention, one of the following should be used when a dummy domain
name is required for testing or documentation purposes - `example.com`,
`.invalid`, `.example`, `.localhost` or `.test` as those are reserved by
IANA/IETF.
Using a domain from `.com` as a default value in our configuration may
cause undesired affects in the future if such a domain is not changed by
the operator and we use it for sending data out of the cluster.
Closes: [OCPBUGSM-30935](https://issues.redhat.com/browse/OCPBUGSM-30935)
/assign @
=> Bug 1972096: Use .invalid domain instead of dummy.com

internal/controller/controllers/infraenv_controller.go
[OCPBUGSM-30258](https://issues.redhat.com/browse/OCPBUGSM-30258) - Fix empty cluster name after applying InfraEnv.yaml
After applying `InfraEnv.yaml` the cluster name is empty on the log message:
`level=info msg="Image myinfraenv being prepared for cluster " `
/cc @nmagnezi
=> OCPBUGSM-30258: Fix empty cluster name after applying InfraEnv.yaml

internal/controller/controllers/infraenv_controller.go, internal/controller/controllers/infraenv_controller_test.go
InfraEnv controller should always requeue for backend response
HTTP StatusConflict (code 409).
The InfraEnv controller is expected to get HTTP StatusConflict (code 409)
from the backend for requests sent in a gap smaller than 10 seconds[1].
The backend generates that response without looking at the Generate ISO
request content (which may either be valid or not). The image should always
be on par with the spec. For that, each request must be served by the backend.
Currently, the controller will not requeue in a case of 409,
if the conditions indicate an error[2].
This PR modifies the InfraEnv controller to always requeue per 409, and set
RequeueAfter to 20 seconds to avoid repeated 409s.
[1] https://github.com/openshift/assisted-service/blob/5904203764b98b484b5e53b382c106939118f6fd/internal …
=> OCPBUGSM-30887: InfraEnv should always requeue on HTTP 409 backend response 

internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go
When specifying an invalid json in 'install-config-overrides'
anntation, a proper message should be specified in AgentClusterInstall
conditions.
E.g.
AgentClusterInstall CRD -> metadata.annotations:
agent-install.openshift.io/install-config-overrides: '{{{'
Message in conditions:
The Spec could not be synced due to an input error: Failed to parse
'agent-install.openshift.io/install-config-overrides' annotation:
invalid character '{' looking for beginning of object key string
Apply an AgentClusterInstall CRD with an invalid json in 'agent-install.openshift.io/install-config-overrides' annotaion.
A condition indicating a parsing error should be available in AgentClusterInstall status.
Please, add one or two reviewers that could help review this PR. Use …
=> OCPBUGSM-30089 parsing error indication for config override

cmd/main.go, internal/host/hostcommands/free_addresses_cmd.go, internal/host/hostcommands/free_addresses_cmd_test.go, internal/host/hostcommands/instruction_manager.go, internal/host/hostcommands/instruction_manager_test.go, internal/host/hostcommands/noop_cmd.go
- Add a configurable flag to indicate if free addresses is supported
- Avoid sending free addresses request in get-next-steps if the above flag is false or kube api is enabled
- Is this PR relying on CI for an e2e test run? No
- Should this PR be tested in a specific environment? No
- Any logs, screenshots, etc that can help with the review process? No
/cc @ronniel1 
/cc @filanov  …
=> OCPBUGSM-29588: ACM/ZTP with Wan emulation, several clusters fail to step past discovery

internal/host/transition.go, internal/host/transition_test.go
This is caused by agent caching and the fact that ntp_sources are reset when host is re-enabled.
When this happens, the agent caching blocks sending ntp result message which is identical to the previous one
while the service clears this field during enable.
The solution is to remove the reset of the ntp_sources during enable host operation. This will prevent the
host field "ntp_sources" to be out of sync from the ntp_sources in the agent.
- Is this PR relying on CI for an e2e test run? No
- Should this PR be tested in a specific environment? No
- Any …
=> OCPBUGSM-30844 NTP status is Unreachable after disable - enable host

pkg/s3wrapper/filesystem.go
We'd like to log the disk usage no more than once every 5 minutes if it
exceeds a predefined threshold. However, if disk usage wasn't changed
and exceeds it limit, we'd like a message to log it, regardless of the
previous disk usage.
=> Bug 1964623: Tune FS disk usage log messages

internal/controller/controllers/clusterdeployments_controller.go, subsystem/kubeapi_test.go
When an `AgentClusterInstall` is changed, the related `InfraEnv` resource should reconcile.
For example: if the user deletes and recreates the `AgentClusterInstall` resource, the
backend cluster ID will change (essentially deregister and register a new backend
cluster), and the `InfraEnv` image URL points to an image that no longer exists.
The `clusterDeployments` controller will now notify the `InfraEnv` controller via the
updates channel that it should reconcile. The `InfraEnv` controller will generate a
new image, to be later picked up by `BMH`. This scenario will also allow users to
retry a cluster installation.
how this code was tested. Here are some questions that may …
=> Bug 1972525: CD controller to notify InfraEnv for backend cluster registration

internal/bminventory/inventory.go, internal/bminventory/mock_installer_internal.go, internal/common/db.go, internal/controller/controllers/agent_controller.go, internal/host/host.go, internal/host/host_test.go, internal/host/mock_host_api.go
Currently, deleting agent from one namespace causes all agents
with the same name to be deleted from all namespaces.
In this PR I added GetHostByKubeKey to inventory API which
consider namespaces and used when getting host from db in
order to check if deregistration is needed.
Please, add one or two reviewers that could help review this PR. Use `/assign` if you want …
=> OCPBUGSM-30296: Delete unregistered hosts agents by namespace

internal/bminventory/inventory.go, internal/bminventory/mock_installer_internal.go, internal/constants/files.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go
Before the PR the secret containing the kubeconfig for the installed
cluster was created only if the installation was successful.
- Create secret with kubeconfig-noingress when install starts
- Update secret with kubeconfig-ingress when installs succeed
Kubeconfig Secret was created at the start of the installation, while the credentials secret was created at the end:
```
test-infra-cluster-assisted-installer-admin-kubeconfig   Opaque                                1      35m
test-infra-cluster-assisted-installer-admin-password     Opaque                                2      4m21s
```
how this code was tested. Here are some …
=> Bug 1969547: Create KubeConfig Secret when install starts

go.mod, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/transition.go, internal/cluster/transition_test.go, internal/host/host.go, internal/host/host_test.go, internal/metrics/metricsManager.go, internal/metrics/mock_metrics_manager_api.go
We need to remove cluster_id from the metrics we are sending to Prometheus because it causes overloading by assisted-installer pods and scraped by Prometheus.
* testing on deployment Prometheus DB 
/cc @nmagnezi 
=> OCPBUGSM-30203: remove cluster_id from prometheus metrics + update tests

internal/controller/controllers/bmh_agent_controller.go, internal/controller/controllers/bmh_agent_controller_test.go
Currently for the `baremetalhost.metal3.io/detached` annotation we are
using `"true"` as a value whenever we decide to create it. Given that,
based on the behaviour of the baremetal-operator, this annotation
accepts string and not a boolean, it may create a confusion if an
administrator decides to set the value to e.g. `"false"` or
`"disabled"`.
It is a design decision in the upstream that the annotation could
provide a context from whatever external system the annotation is coming
from and that the value itself is completely ignored.
Conflicts:
- internal/controller/controllers/bmh_agent_controller_test.go
Cherry-picks: openshift#1974
Closes: [OCPBUGSM-30953](https://issues.redhat.com/browse/OCPBUGSM-30953)
=> Bug 1972262: Change default value for BMH_DETACHED_ANNOTATION

deploy/operator/utils.sh
Disconnected mode needs a bit more time for assisted-service pod to be ready, that's because all nodes need (semi-serially) to reload ``registry.conf`` configuration, restart crio and kubelet and wait to be ready.
/cc @YuviGold 
=> NO-ISSUE: increase timeout of waiting for pod for disconnected flow

deploy/operator/deploy.sh, deploy/operator/libvirt_disks.sh, deploy/operator/mirror_utils.sh, deploy/operator/setup_assisted_operator.sh, deploy/operator/setup_hive.sh, deploy/operator/setup_lso.sh
The entire disconnected logic should be implemented in the same place
as where the connected logic is located.
Currently that's assisted-service repository hence moving the logic
from openshift/release.
- Patch nodes mirror-by-digest-only to be false. This would be
configurable in OCP 4.9 https://issues.redhat.com/browse/OCPNODE-521 .
The script goes over all the cluster nodes (currently supports a
single dev-scripts cluster), and modifies
/etc/containers/registries.conf if necessary.
This solution is mainly for local deployment since the CI images pull
specs are with digest.
- mirror_rhcos for assisted operator from_community_operators.
- Call setup_assisted_operator.sh from_community_operators function in
case of a disconnected.
- Merge authfiles for disconnected env.
- No need to check …
=> MGMT-5171: Deploy assisted operator in disconnected ipv6 env

docs/Kube-API.md
- Explain how to delete the CD, ACI and Agents CR
- If assisted-service is down, explain how to clean finalizers on CRs
/cc @nmagnezi 
/cc @filanov  …
=> Bug 1968423: Document kube api teardown process

internal/bminventory/inventory.go, internal/bminventory/mock_installer_internal.go, internal/constants/files.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go
Before the PR the secret containing the kubeconfig for the installed
cluster was created only if the installation was successful.
- Create secret with kubeconfig-noingress when install starts
- Update secret with kubeconfig-ingress when installs succeed
It's …
=> Bug 1970395: Create KubeConfig Secret when install starts (#2041)

subsystem/kubeapi_test.go
Decreased timeout for "Check NTP Source" step in subsystem test.
The following subsystem test shouldn't fail on timeout:
"SNO deploy clusterDeployment full install and validate MetaData"
/cc @rollandf 
/cc @filanov 
=> OCPBUGSM-31316: decrease poll interval for check NTP source

config/manager/manager.yaml, config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml, deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml, docs/operator.md
Moves us more closely in line with the new name "Infrastructure Operator
for Red Hat OpenShift".
/cc @flaper87 
/cc @carbonin 
=> Bug 1974501: infrastructure operator rename

internal/controller/controllers/bmh_agent_controller.go, internal/controller/controllers/bmh_agent_controller_test.go
Because in some cases we do not have a control over the order of
creation between different resources, it helps to wait some time before
BMAC is using the generated ISO image so that we are sure all the
configuration is applied.
Closes: [OCPBUGSM-30125](https://issues.redhat.com/browse/OCPBUGSM-30125)
```
conditions:
- lastTransitionTime: '2021-06-22T12:38:46Z'
message: Image has been created
reason: ImageCreated
status: 'True'
type: ImageCreated
createdTime: '2021-06-22T12:38:46Z'
isoDownloadURL: >-
https://assisted-service-assisted-installer-manual-bundle.apps.ostest.test.metalkube.org/api/assisted-install/v1/clusters/71deabca-da7e-4440-bfab-7eb0f7fb4219/downloads/image?api_key=ey[...]VA
```
```
[...]
time="2021-06-22T12:39:07Z" level=info msg="prepare image for cluster …
```
=> Bug 1968552: Wait for ISO for 1 minute before using it

deploy/operator/deploy.sh
=> MGMT-5171: Fix setup-disconnected function if condition lacking a semi-colon

internal/controller/controllers/infraenv_controller.go, internal/controller/controllers/infraenv_controller_test.go
InfraEnv controller should always requeue for backend response
HTTP StatusConflict (code 409).
The InfraEnv controller is expected to get HTTP StatusConflict (code 409)
from the backend for requests sent in a gap smaller than 10 seconds[1].
The backend generates that response without looking at the Generate ISO
request content (which may either be valid or not). The image should always
be on par with the spec. For that, each request must be served by the backend.
Currently, the controller will not requeue in a case of 409,
if the conditions indicate an error[2].
This PR modifies the InfraEnv controller to always requeue per 409, and set
RequeueAfter to 20 seconds to avoid repeated 409s.
Conflicts:
internal/controller/controllers/infraenv_controller.go
[1] …
=> Bug 1971654: InfraEnv should always requeue on HTTP 409 backend response

deploy/operator/ztp/agentClusterInstall.j2, deploy/operator/ztp/assisted-installer-crds-playbook.yaml, deploy/operator/ztp/deploy_spoke_cluster.sh, hack/setup_env.sh
Instead of maintaing hardcoded values, since in any case the ZTP
workflow is dependant on dev-scripts, we use dev-scripts networking
variables defaults for ZTP workflow.
The networking params includes cluster network cidr, host prefix,
machine network cidr, and service network cidr. All are assigned to
AgentClusterInstall.
/cc @osherdp 
/cc @lranjbar 
=> MGMT-5171: Support IPv6 networking params on ZTP spoke cluster

internal/cluster/conditions.go
- Remove unneeded log message
- Is this PR relying on CI for an e2e test run? No
- Should this PR be tested in a specific environment? No
- Any logs, screenshots, etc that can help with the review process? No
/cc @gamli75  …
=> OCPBUGSM-31346: Production logs are spammed on "Found unpreparing host"

config/manager/manager.yaml, config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml, deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml, docs/operator.md
Manual cherry-pick of #2070 
Moves us more closely in line with the new name "Infrastructure Operator for Red Hat OpenShift".
A manual cherry-pick was required because of the following conflicts:
```diff
diff --cc config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
index 7c828a8e,bb0302bb..00000000
--- a/config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
+++ b/config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
@@@ -6,8 -6,8 +6,16 @@@ metadata
capabilities: Basic Install
categories: OpenShift Optional
createdAt: ""
++<<<<<<< HEAD
+    description: Assisted Service is used to orchestrate baremetal OpenShift installations.
+    olm.skipRange: '>=0.0.0 <0.0.5'
++||||||| parent of d2c0aa43 (Bug 1974501: infrastructure …
```
=> Bug 1974931: infrastructure operator rename

internal/cluster/cluster_test.go, internal/common/common.go, internal/common/test_configuration.go, internal/hardware/validator_test.go, internal/host/host_test.go, internal/host/hostutil/test_utils.go, internal/host/refresh_status_preprocessor.go, internal/host/statemachine.go, internal/host/transition_test.go, internal/host/validation_id.go, internal/host/validator.go, models/host_validation_id.go, restapi/embedded_spec.go, subsystem/cluster_test.go, subsystem/ipv6_test.go, subsystem/metrics_test.go, swagger.yaml
* Related to https://issues.redhat.com/browse/MGMT-4083
* Adds a new host validation during discovery that checks that the host has at least one default route defined. At this point we're validating that the route exists, but the information captured from the agent could provide further fine tuning (ipv4,ipv6 and GW IP address).
Apparently, the kubeapi-server requires to have a defined route in order to start, even if it's an air gap cluster with no outside access. There is a deferred RFE in place to address this gap, but for the time being we can presume that any deployment will require the node to have at least one default route in order for the cluster to be successfully created. 
@ori-amizur @YuviGold could you please take a look?
~~References #1752. Once that PR is merged I will …
=> MGMT-6500 Add default route host validation

internal/controller/controllers/infraenv_controller.go
/cc @rollandf
https://github.com/openshift/assisted-service/pull/2040
https://bugzilla.redhat.com/show_bug.cgi?id=1969766
=> [ocm-2.3] Bug 1969773: Fix empty cluster name after applying InfraEnv.yaml 

docs/hive-integration/kube-api-conditions.md, internal/controller/api/hiveextension/v1beta1/agentclusterinstall_types.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go
In Kube API, in case that more agents than the required are registered,
the RequirementsMet condition will not be True with AdditionalAgents
reason.
how this code was tested. Here are …
=> Bug 1964471: Add AdditionalAgent Reason to condition

deploy/operator/ztp/infraEnv.j2
Remove AgentsLabelSelector from ZTP flow as it was removed from InfraEnv Spec in #1998 …
=> NO-ISSUE: Remove AgentsLabelSelector from ZTP flow

internal/controller/controllers/infraenv_controller.go, internal/controller/controllers/infraenv_controller_test.go
https://github.com/openshift/assisted-service/pull/2027 added a more precise indication that there is no backend cluster
and directs the user to inspect AgentClusterInstall conditions.
This PR fixes a formatting issue with that msg, which looked as follows:
```yaml
message: 'Failed to create image: cluster does not exist: single-node, check AgentClusterInstall
conditions: &{Group:extensions.hive.openshift.io Version:v1beta1 Kind:AgentClusterInstall
Name:test-agent-cluster-install}'
```
With this change:
```yaml
message: 'Failed to create image: cluster does not exist: single-node, check AgentClusterInstall
conditions: name test-agent-cluster-install in namespace assisted-installer'
```
- [] None
It's recommended to take a few extra minutes to provide …
=> Bug 1969391: Fix InfraEnv missing ACI msg formatting

cmd/main.go, internal/controller/controllers/agentclusterinstall_controller.go, internal/controller/controllers/agentclusterinstall_controller_test.go, subsystem/kubeapi_test.go
Added AgentClusterInstallReconciler for watching the CRD
and set sync condition in case of a missing ClusterDeployment.
If the specified ClusterDeployment is missing the following message should be set for SpecSynced condition:
"The Spec could not be synced due to an input error: ClusterDeployment with name <name> in namespace <namespace> not found. Ensure that the CRD is already applied."
* Apply an AgentClusterInstall CRD, without creating the correlated ClusterDeployment CRD.
* Status.Conditions should include the following condition:
```
Message:               The Spec could not be synced due to an input error: ClusterDeployment with name <name> in namespace <namespace> not found. Ensure that the CRD is already applied.
Reason: …
```
=> OCPBUGSM-30214: add controller for AgentClusterInstall

docs/pull_request_template.md
- Add an issue section to the PR template
- Hide explanations from the shown PR body (using comments).
/cc @flaper87 
/cc @filanov 
=> NO-ISSUE: Add an issue type section to PR template & hide explanations

deploy/operator/gather.sh, deploy/operator/ztp/agentClusterInstall.j2, deploy/operator/ztp/assisted-installer-crds-playbook.yaml, deploy/operator/ztp/baremetalHost.j2, deploy/operator/ztp/clusterDeployment.j2, deploy/operator/ztp/deploy_spoke_cluster.sh, deploy/operator/ztp/infraEnv.j2
In the case of the hub and spoke clusters being installed on the same namespace,
and then a sysadmin would try to delete the namespace -
the deletion operation could get stuck.
Since the assisted-service might be deleted before AgentClusterInstall and
ClusterDeployment were deleted.
The CRs wouldn't be able to be deleted and the namespace deletion would get stuck.
/cc @osherdp 
/cc @lranjbar 
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTI …
=> MGMT-7082: Spoke namespace should be different than assisted-service namespace

subsystem/kubeapi_test.go
The root cause is how InfraEnv used to requeue for errors,
which changed with other fixes. We will now requeue after 20s
(as the backend limits image generation requests windows
to be above 10s), and avoid requeue for non-recoverable
issues such as BadRequest (invalid config).
=> Bug 1977449: Fix flaky test: invalid NMState config YAML 

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, subsystem/day2_cluster_test.go
When an AddHosts (Day2) Cluster is created, the ocp_release_image
is not transferred from the original installed cluster. This commit
ensures that ocp_release_image is set using the params'
OpenshiftVersion.
When OcpReleaseImage is missing for the Day2 cluster, the InfraEnv
controller reconcile results in error: "no releaseImage nor
releaseImageMirror provided." And this prevents
InfraEnv.Status.ISODownloadURL from being set and blocks remote
worker nodes from booting into discovery ISO.
- [] None
- Is this PR relying on CI for an …
=> OCPBUGSM-29100 Set OcpReleaseImage for RegisterAddHostsCluster

docs/hive-integration/README.md, docs/hive-integration/kube-api-conditions.md, internal/controller/api/v1beta1/agent_types.go, internal/controller/controllers/agent_controller.go, internal/controller/controllers/agent_controller_test.go, subsystem/kubeapi_test.go
Similar to  AgentClusterInstall, the condition `ReadyForInstallation` is changed `RequirementsMet` and set it to True after installation started/finished
Related discussion here https://coreos.slack.com/archives/C01FT9E4Q10/p1624783430043300?thread_ts=1624783425.043200&cid=C01FT9E4Q10
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1976776
Jira: https://issues.redhat.com/browse/OCPBUGSM-31522
/cc @
/cc @
=> OCPBUGSM-31522: Bug 1976776: Change agent's ReadyForInstallation condition into RequirementsMet

config/crd/bases/agent-install.openshift.io_agents.yaml, config/crd/resources.yaml, deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml, internal/controller/api/v1beta1/agent_types.go
Added the following columns to 'additionalPrinterColumns'
in Agents CRD:
* Role: The role (master/worker) of the Agent.
* Stage: The HostStage of the Agent.
* Hostname: The hostname of the Agent.
* Requested Hostname: The requested hostname for the Agent.
Note:
Adding a complex jsonPath is not supported yet[*],
so can't add columns that are consist of arrays (as IP/MAC).
[*] https://github.com/kubernetes/kubernetes/pull/101205
The following columns should be printed:
* oc -n assisted-installer get agents:
* NAME,  CLUSTER, APPROVED,  ROLE,  STAGE
* oc -n assisted-installer get agents -o wide:
* NAME,  CLUSTER, APPROVED,  ROLE,  STAGE,  HOSTNAME, REQUESTED HOSTNAME
/cc @rollandf 
/cc @filanov  …
=> OCPBUGSM-31584: added columns to Agent CRD

deploy/operator/common.sh, deploy/operator/deploy.sh, deploy/operator/destroy.sh, deploy/operator/gather.sh, deploy/operator/setup_assisted_operator.sh, deploy/operator/setup_hive.sh, deploy/operator/utils.sh, deploy/operator/ztp/deploy_spoke_cluster.sh
Improve integration between assisted operator deployment module and
spoke cluster deployment module.
Add more conditions steps for better monitoring.
- Add a `common.sh` module with common variables for the operator scripts.
- Fix `wait_for_object_amount` util not to spam numbers.
- Assisted operator deployment: Wait for `AgentServiceConfig`'s
`ReconcileCompleted` condition.
- Spoke deployment: Check namespace before creation.
- Spoke deployment: Wait for `InfraEnv`'s `ImageCreated` condition.
- Spoke deployment: Extend intervals waiting for agents from 10s to 30s.
/cc @osherdp 
/cc @lranjbar  …
=> NO-ISSUE: Add common module for operator deployment scripts

internal/oc/release.go
The execute function on release.go is appending the registry-config as
an additional parameter to the given command parameter.
In case of an error, we would like to show the full command that was
executed.
/cc @eranco74 
=> NO-ISSUE: Show full command on release.go execture error

docs/operator.md, internal/controller/controllers/agentserviceconfig_controller.go, internal/controller/controllers/agentserviceconfig_controller_test.go, internal/controller/controllers/common.go
We shouldn't force users to provide a ca-bundle when mirroring content.
Potential Use Cases:
1. Mirror registry has an official CA signed certificate, so no need for additional certificate.
2. Mirrored content into a network-unrestricted environment. Need an image mapping via registries.conf but bundle is not required.
I manually tested all of the relevant scenarios that I could think of with respect to the mirror-registry configuration:
1. [User specifies a mirror-registry configmap that doesn't exist](https://github.com/openshift/assisted-service/pull/2081#issuecomment-868933476) - working as expected
2. [User specifies a mirror-registry configmap that is missing the registries.conf](https://github.com/openshift/assisted-service/pull/2081#issuecommen …
=> BUG 1970063: Don't force ca-bundle.crt when mirroring

internal/controller/controllers/bmh_agent_controller.go, internal/controller/controllers/bmh_agent_controller_test.go
Sets the spoke BMH Spec.Image.URL to the hub BMH's Spec.Image.URL.
This fixes the spoke BMH error:
errorMessage: 'Host adoption failed: Error while attempting to
adopt node b3bb59f8-8728-43c7-b31d-5346bf9dc700: Cannot
validate image information for node b3bb59f8-8728-43c7-b31d-5346bf9dc700
because one or more parameters are missing from its
instance_info and insufficent information is present to boot
from a remote volume. Missing are: [''image_source'',
''kernel'', ''ramdisk''].'
errorType: provisioned registration error
The deleted comment mentions that if the Image field is filled in
then externallyProvisioned is ignored, that doesn't appear to be
the case. The spoke BMH still has externally provision status
with Spec.Image.URL set.
/cc @flaper87  …
=> Bug 1975452: Fix spoke BMH provisioned registration error

internal/bminventory/inventory.go, models/host_requirements_role.go, restapi/embedded_spec.go, swagger.yaml
Adds 2 fields to the `/host-requirements` endpoint to expose the network latency and packet loss for the default host requirements.
/cc @jakub-dzon 
/cc @YuviGold 
=> Bug 1975491: Added network latency and packet loss to /host-requirements

docs/hive-integration/baremetal-agent-controller.md, docs/hive-integration/kube-api-getting-started.md
This PR adds an explicit explanation to the documentation describing
lack of support for `automatedCleaningMode: metadata` in the
BareMetalHost CRs.
Closes: [OCPBUGSM-31542](https://issues.redhat.com/browse/OCPBUGSM-31542)
/cc @flaper87 
/cc @nshidlin 
=> Bug 1976983: Add docs explaining automatedCleaningMode overrides

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/bminventory/mock_crd_utils.go, internal/controller/controllers/agent_controller.go, internal/controller/controllers/crd_utils.go, internal/controller/controllers/crd_utils_test.go, internal/host/host.go, internal/host/mock_host_api.go, subsystem/kubeapi_test.go
In case a host is booted with a new ISO generated by an InfraEnv located
in the same namespace, the following steps are performed:
- Check if Host with same KubeKey exists, and delete it
- Clear the Spec of the Agent and update the ClusterDeployment Name
- Verify that the Event URL contains the new cluster ID
/cc @nmagnezi 
/cc @filanov 
=> Bug 1977354: Move agent to different cluster same NS

deploy/operator/common.sh, deploy/operator/setup_assisted_operator.sh
Fixes https://github.com/openshift/assisted-service/pull/2148 calling `set_ca_bundle.py` script from relative path.
/cc @osherdp 
/cc @lranjbar 
=> MGMT-5171: Call set_ca_bundle.py script from the correct path

internal/operators/cnv/cnv_operator.go
Since the information about unmet requirements can be easily retrieved from the UI/API for hosts, the repetitive messages are removed from log.
/cc @gamli75 
=> Bug 1975529: Remove unmet requirement message from log

internal/controller/controllers/agentserviceconfig_controller.go, internal/controller/controllers/agentserviceconfig_controller_test.go, internal/controller/controllers/common.go
This PR hashes the generated, mirror registry, and unsupported configMap(s) and uses that information to restart the assisted-service deployment if necessary. The general rule is that, if it's a part of our supported configuration, then we will restart the assisted-service. This simply means that if there is a mismatch between the "unsupported" configmap and what is currently running with the assisted-service, we will log (and emit) a warning and move on...we will take no direct action.
/cc @flaper87
=> Bug 1965117: Keep assisted-service configmap mount updated

internal/operators/handler/handler.go, internal/operators/handler/handler_test.go
Till now only CVO status update was creating an event.
We would like to expose more what happens in finalizing phase so 
we make an event for any operator status change.
Depends on https://github.com/openshift/assisted-installer/pull/298 to avoid OLM spamming
/cc @filanov 
/cc @machacekondra 
=> MGMT-6663: Make an event for any operator status change

internal/installcfg/installcfg.go, internal/installcfg/installcfg_test.go
Currently BMH resources in the clusters installed by AI are named in
the form of `openshift-{master|worker}-{0...}`. This PR changes the
convention so that a real hostname of the node will be used, or its UUID
as a fallback option.
For virtual environments this gives us 3 different naming schemas
- Node: libvirt domain name
- BareMetalHost: `openshift-{master|worker}-{0...}`
- Machine: `cluster_name-ID-{master|worker}-{0...}`
This PR unifies naming between Node and BareMetalHost, so that the
output of the 3 following commands is more consistent
- `oc get nodes`
- `oc -n openshift-machine-api get baremetalhosts`
- `oc -n openshift-machine-api get machines`
Closes: [OCPBUGSM-26086](https://issues.redhat.com/browse/OCPBUGSM-26086)
Blablabla
/assign @ …
=> Bug 1937696: Use hostname for BMH resource name

deploy/operator/setup_assisted_operator.sh
=> MGMT-5171: Fix quotes on setup_assisted_operator.sh

internal/bminventory/inventory.go, internal/cluster/cluster_test.go, internal/cluster/common.go, internal/common/db.go, internal/common/monitor_query_generator.go, internal/host/common.go, internal/host/host.go, internal/host/host_test.go, internal/host/hostutil/update_host.go, internal/host/transition.go
Longer timeout monitoring is an approach during selective monitoring.  Instead of selecting entities by catching all changes that might cause status change and react accordingly, estimate the time to reach steady state and set it as timeout.  This means that instead of using 30 seconds timeout to react for every change that might cause change (inventory, connectivity etc.), use 5 minute timeout which we estimate as the duration to reach steady state.
The timestamp will be a specially dedicated field for this purpose in the database instead of the updated_at field.
The timestamp will be updated on the following events:
- Cluster registration
- Host registration
- Cluster update
- Status change
The monitoring will be done in the following manner:
Use a timeout of 5 minutes every 10s …
=> MGMT-7083: Add additional timestamp to trigger monitoring and replace updated-at field with this timestamp for selective monitoring

internal/controller/controllers/bmh_agent_controller.go
It has been discovered during scaling tests that it sometimes happen
that the cooldown period for InfraEnv's ISO is causing BMHs to be stuck
in Ready state.
This is caused by the fact that inside mapInfraEnvToBMH function the
returned cooldown period was ignored so that the requeueing was never
happening.
The change introduced in this PR modifies the logic inside
mapInfraEnvToBMH so that we check if requeueing is needed and if so, we
proceed with reconciliation. This effectively moves the requeue logic to
the reconciliation loop.
Closes: [OCPBUGSM-31727](https://issues.redhat.com/browse/OCPBUGSM-31727)
```
conditions:
- lastTransitionTime: '2021-07-07T10:04:32Z'
message: Image has been created
reason: ImageCreated
status: 'True'
type: ImageCreated
createdTime: '2021-07-07T10:11:45Z' …
```
=> Bug 1978739: Fix requeue logic inside mapInfraEnvToBMH

internal/controller/controllers/bmh_agent_controller.go
This is a manual backport of #2173. We do not wait for the bot so that we can save some time and start CI run already in parallel as we wait for the master to merge.
/cc @flaper87 
/cc @rollandf 
/cc @akrzos
=> Bug 1979906: Fix requeue logic inside mapInfraEnvToBMH

docs/hive-integration/baremetal-agent-controller.md
This PR clarifies that it's the BMAC setting the value of the annotation
`automatedCleaningMode`.
Closes: [OCPBUGSM-31754](https://issues.redhat.com/browse/OCPBUGSM-31754)
/cc @flaper87 
/cc @rollandf 
=> Bug 1979169: Clarify documenation about automatedCleaningMode

internal/host/hostutil/test_utils.go, internal/host/transition_test.go, internal/host/validator.go
As discussed in the bug ticket,
Our memory requirements for nodes actually depend on free memory rather than the
actual physical memory.
Updated  backed error message to use
`UsableBytes` instead of `PhysicalBytes` to indicate to the user the actual memory inventory issue.
Updated `insufficient worker memory` and `insufficient master memory` tests
to validate against UsableBytes. …
=> OCPBUGSM-29517: use UsableBytes instead of PhysicalBytes

deploy/operator/setup_assisted_operator.sh
The ICSP name is derived from the index image.
We shouldn't depend on specific name.
For example, on OpenShift CI the index image looks like the following:
'registry.build01.ci.openshift.org/ci-op-bqxvrsmm/pipeline'
and the ICSP name would be 'pipeline-0'
/cc @osherdp 
/cc @lranjbar 
=> MGMT-5171: Mirror all available ICSP on script

client/installer/list_clusters_parameters.go, internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, restapi/embedded_spec.go, restapi/operations/installer/list_clusters_parameters.go, restapi/operations/installer/list_clusters_urlbuilder.go, subsystem/cluster_test.go, swagger.yaml
added new `with_hosts` optional parameter to the cluster_list API, defaults to `false`.
When `true`, the hosts array will include all hosts in cluster. otherwise the array will be empty.
Updated inventory and subsystem tests.
=> MGMT-6961: optional argument to cluster_list REST API

pkg/auth/rhsso_authenticator.go
This log is printed in one of 2 cases:
* A user tries to access a non-existing cluster
* A user tries to access a cluster that he doesn't own
The UI is getting a list of subscriptions from AMS which contains all the
clusters in the user's organization, then for each cluster it queries AI
in order to get some additional information, therefore it may:
* Try to access a GC cluster
* Try to access a cluster that someone else in the organization owns
Until we have an organization model in AI aligned with OCM we should
remove this log, otherwise, we will be spammed.
On the new code, I didn't get this log.
/cc @
/cc @
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit- …
=> OCPBUGSM-30766: Removing "Unauthorized access to cluster *" log.

internal/controller/controllers/agentserviceconfig_controller.go, internal/controller/controllers/agentserviceconfig_controller_test.go
Currently, when constructing OPENSHIFT_VERSIONS from the osImages on the
AgentServiceConfig, the values are passed by reference clumsily. This causes a
problem where the last in the `osImages` slice is used to determine the
root filesystem URL and ISO URL for all OPENSHIFT_VERSIONS.
If we use the reference directly from the agentserviceconfig, we should
avoid this problem.
/cc @flaper87
=> Bug 1978691: Fix osImages reference passing

hack/generate.sh, hack/setup_env.sh
Instead of installing spectral in our build container, just use the container image if the binary isn't available.
/cc @lranjbar 
/cc @carbonin 
=> NO-ISSUE: Use spectral image directly when needed

internal/dns/dns.go, subsystem/cluster_test.go
Updated `ValidateDNSName`.                                                                 
The function was validating against `apps.<clusterName>.<baseDNSDomain>` .
This is why via the API `baseDNSDomain=example` is responding with 200. because it actually validates `apps.<cluster_name>.example`.
The update adds a validation on the baseDNS itself in addition to the validations we already have.
Updated subsytem tests to ensure validation
- Any logs, …
=> Bug 1966586: 200 OK returned when setting invalid BaseDNSdomain via API

internal/cluster/cluster.go, internal/network/connectivity_groups.go, internal/network/connectivity_groups_test.go
- Separate connectivity groups to handle L2 and L3 with special code analyzing
connectivity for each
This is a refactoring of the connectivity groups code that it will support both L2 and L3.  For this, it was divided to 
factory and implementation which are interfaces.  Their purpose is to analyze if there is connectivity from a specific 
host to a remote host.  There are two implementations for this: L2, and L3.
hostQueryFactory is the factory for hostQuery which checks the connectivity from a specific host to remote hosts.
/cc @empovit 
=> MGMT-7170: Adapt connectivity groups to support L3 connectivity

internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/transition.go, internal/cluster/transition_test.go, internal/metrics/metricsManager.go, internal/metrics/mock_metrics_manager_api.go
Currently only complete after finalizing is measured by metrics.
This code add metric events to all branches of installation, including
ones that are prematurely ended with error
- [] None
/cc @gamli75 
/cc @YuviGold 
=> MGMT-7136: Add metric report to all installation complete scenarios

hack/generate.sh, hack/setup_env.sh
Instead of installing spectral in our build container, just use the container image if the binary isn't available.
/cc @djzager 
=> NO-ISSUE: Fix spectral linter

internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go
The `setClusterConditionsUnknown` function is being invoked in two scenarios:
1. `AgentClusterInstall` controller: There is no `clusterDeployment` resource
to match the reconciled `AgentClusterInstall`, and thus no backend cluster is defined.
2. `ClusterDeployments `controller: the `updateStatus` function about to update
the `AgentClusterInstall` conditions, although there is no backend cluster
retrieved from the database.
In both scenarios, the indication is that the backend doesn't currently hold any
information about this cluster, and thus the controllers will clean up
`DebugInfo.State` and `DebugInfo.StateInfo`.
This change will also add a cleanup for `DebugInfo.LogsURL` and `DebugInfo.EventsURL`,
which, if had any URLs set, are currently broken. An example of such a scenario
is …
=> OCPBUGSM-30272: Clear ACI LogsURL and EventsURL in ClusterConditionsUnknown

openshift/template.yaml
Remove deprecated `IMAGE_BUILDER` var
/cc @filanov 
/cc @gamli75 
=> NO-ISSUE: Remove deprecated IMAGE_BUILDER var

deploy/operator/mirror_utils.sh, deploy/operator/setup_assisted_operator.sh, deploy/operator/setup_lso.sh
Remove `mirror_package_from_official_index` function as it is just
a minor wrapper for `mirror_package` that causes confusion.
No need to mirror all available ICSPs for assisted configmap.
The ISCP name is derived from the index image, and only the assisted
`INDEX_IMAGE` should be used.
`INDEX_IMAGE` would be overriden with community-operator-index image in
case used.
/cc @osherdp 
/cc @lranjbar 
=> MGMT-5171: Mirror only assisted index image

deploy/operator/setup_assisted_operator.sh
Using namespaces looked as a good solution at first, but images might be
on different repositories and we should mirror the right ones to avoid
confusion.
For example, on CI the release image looks like that:
registry.build01.ci.openshift.org/ci-op-89v28h20/release@sha256:<sha>
While its images are on a different repository:
registry.build01.ci.openshift.org/ci-op-89v28h20/stable@sha256:<sha>
/cc @osherdp 
/cc @lranjbar 
=> MGMT-5171: Mirror OCP release repositories instead of namespaces

internal/cluster/transition.go, internal/cluster/transition_test.go, subsystem/metrics_test.go
Use the original cluster instead of updateCluster that may be nil
- [] None
/cc @gamli75 
=> MGMT-7212: Fix crash in PostRefreshCluster

.github/dependabot.yml
Currently, dependabot PRs fail on the commit-message linter. We would like to prefix its commits with NO-ISSUE to be aligned with our other commit messages convention.
/cc @osherdp 
/cc @eliorerz 
=> NO-ISSUE: Make dependabot commits prefixed with NO-ISSUE

internal/host/common.go, internal/host/hostutil/test_utils.go, internal/host/transition_test.go, internal/host/validator.go
Resolves BZ-1974085. The issue was that the IPs stored in the inventory include the CIDR, and the original code expected to find just the IP without the CIDR. 
I've tested it manually in one of my environments with success: during failure, the validation message now contains the name of the remote host that fails the validation.
- [] None
Please, add one or two reviewers that could help …
=> Bug 1974085: fixes network&latency host validations

internal/host/validator.go
The library used in the agent to capture the network routes can return a "nil" in the Gateway or Destination field if they are not available in the OS routing table. When this happens, the agent will return an empty string instead of a nil (because we store the value as a string and not as a pointer to string/IP).
This PR adapts the service to evaluate the value of the gateway and the destination for empty strings, and ignore the entry when any of these 2 fields is empty. 
The agent's counterpart PR can be found here:
https://github.com/openshift/assisted-installer-agent/pull/217
- [] None
/cc @
/cc @ …
=> Bug 1980901: Gateway is '<nil>' in route

deploy/assisted-service-service.yaml, subsystem/image_test.go
The service.beta.kubernetes.io/aws-load-balancer-type=nlb annotation
results in a "Network" load balancer rather than a "Classic" one which
seems to work better for our use case.
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1982447
/cc @YuviGold
=> MGMT-7054: Use a network LB to avoid download issue

internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/cluster/installer.go, internal/cluster/installer_test.go, internal/cluster/mock_cluster_api.go
This code isn't used anymore.
Old implementation:
When the user press "install cluster" we called that method.
New implementation:
When the user press "install cluster", the cluster moves to
prepare-for-installation stage and when it is ready to be installed it
will be installed by the monitoring process.
/cc @
/cc @
=> NO-ISSUE: Removing Install() method from cluster's API.

Dockerfile.assisted-service, Dockerfile.assisted-service-build, Dockerfile.assisted-service-debug, Dockerfile.bundle, Dockerfile.test, go.mod
Older versions of go are out of support, so for security compliance, we were trying to get all components on the latest version. 1.14 is already out of support, i.e. https://endoflife.date/go
Note that the `COPY . ./` statement in `Dockerfile.test` had to have
been moved to a point in the file after the utilities' `go get ...`
statements because running `go get` while the working directory is
a go module directory can cause changes in `go.mod` and `go.sum`.
Somehow these caused no issues on 1.15, but with 1.16, it started
breaking things when trying to build our go module binaries since
those `go get ...` invocations modifies `go.mod` and `go.sum` in
ways I did not bother to understand. By moving the COPY statement,
we ensure that the directory is not considered a go module directory …
=> MGMT-7210 Upgrade Go version to 1.16

cmd/main.go, internal/host/hostcommands/container_image_availability_cmd.go, internal/host/hostcommands/container_image_availability_cmd_test.go, internal/host/hostcommands/instruction_manager.go
We want to verify that the timeout of all underlying tools in preparing--for-installation is
less than the global timeout in that status.  The reason for that is that we want the tools
to terminate on timeout before the global termination on timeout.  This way the failure reason
will be clearer.
/cc @avishayt 
=> MGMT-6977: Make sure that preparing for installation timeout is more than the tools timeouts

internal/cluster/cluster.go, internal/cluster/common.go, internal/cluster/transition.go
Remove unused srcStatus from `updateLogsProgress()` func
/cc @rollandf 
/cc @filanov 
=> NO-ISSUE: Remove unused srcStatus from updateLogsProgress func

internal/migrations/20210713123129_populate_infra_env.go, internal/migrations/20210713123129_populate_infra_env_test.go
This PR fixes a bug in the migration of Cluster DB entries to InfraEnv DB entries
@yevgeny-shnaidman @gamli75 
/cc @
/cc @
=> MGMT-7086: Migrate data from Cluster to IngraEnv

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go, internal/common/common.go, internal/network/manifests_generator.go, internal/network/manifests_generator_test.go, internal/network/mock_manifests_generator.go, models/cluster.go, models/cluster_create_params.go, models/cluster_update_params.go, restapi/embedded_spec.go, subsystem/cluster_test.go, swagger.yaml
Allow the scheduling of workloads on masters at installation time. This will make the installations with 3 masters and 1 worker nodes possible.
The implementation adds a new boolean cluster property ("schedulable_masters") which is disabled by default if not specified at cluster creation time.
- Is this PR relying on CI for an e2e test run? No
- Should this PR be tested in a specific environment? No
- Any logs, screenshots, etc that can help with the review process? No, but can be provided if needed
/cc @YuviGold 
/cc @tsorya  …
=> MGMT-4540: Support schedulable masters cluster property

internal/ignition/ignition.go
The message of the day is shown whenever logging into the agent node.
It should provide information about how to debug the agent in case necessary. Currently it guides how to watch the agent status. it should include as well how to monitor the agent logs.
```
This is a host being installed by the OpenShift Assisted Installer.
It will be installed from scratch during the installation.
The primary service is agent.service. To watch its status, run:
sudo journalctl -u agent.service
To view the agent log, run:
sudo journalctl TAG=agent
```
/cc @empovit 
/cc @osherdp 
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONT …
=> MGMT-7297: Add view agent logs command to the agent message of the day

hack/generate.sh
In Prow CI image pulls to the external image registry, docker.io, are rate limited. Check for the image in the local CI image registry and use it instead of pulling from docker.io.
I ran `make generate-all` locally on my machine while logged in to the CI OCP cluster. This will affect the jobs that use assisted-test-infra so we should wait for those to pass.
/cc @djzager 
/cc @YuviGold 
/cc @osherdp 
RE: Backporting if this setting for spectral stays in the assisted-service repo will need to be backported at some point for ocm-2.3.z releases. 🤔 
=> MGMT-7306: Use local CI image for spectral if it is available

internal/controller/controllers/clusterdeployments_controller.go
On Secret watch, in the ClusterDeployment controller, let's make sure the controller only loads
the ClusterDeployments that exist in the same namespace as the Secret being watched. This will
help reducing interations, and resources.
The above is possible because ClusterDeployment holds a LocalObjectReference to a secret, which means
the secret must exist in the same namespace as the Clusterdeployment.
/cc @nmagnezi 
/cc @rollandf 
=> NO-ISSUE: Filter out Clusterdeployments from non-relevant namespaces

deploy/operator/ztp/deploy_spoke_cluster.sh
We are noticing that it is taking longer for the agents to join in this flow. Increasing the timeout as a start towards debugging.
/cc @YuviGold 
/cc @osherdp 
=> MGMT-7308: Increase timeout for agents in ZTP flow

docs/enhancements/agent-late-binding.md
The late binding feature disconnects the ISO generation from the cluster
creation.  One persona may generate ISOs and boot hosts, whose agents
register and show up not bound to any cluster, then another persona
takes unbound agents and uses them to create/expand clusters.
=>  NO-ISSUE Enhancement for late binding

hack/generate.sh, hack/setup_env.sh
Because of docker hub's rate limiter, we sometimes have problems pulling spectral image.
This PR changes logic so that we will still use prow's image or local installation (if any of them is relevant) but download the binaries from GitHub instead of the docker image.
/cc @YuviGold 
/cc @rollandf 
/cc @nmagnezi 
=> NO-ISSUE: download binaries instead of using docker-hub

.golangci.yml, Dockerfile.assisted-service, cmd/main.go
Enable pprof when running in `DEBUG` mode so that it's possible to inspect the traces, heap data, as well as other profile data from assisted-service.
This has proven to be useful when doing scale test and needing to debug performance issues.
This PR also adds the following flags to the `Dockerfile`
```
GODEBUG=madvdontneed=1
GOGC=50
```
These two flags instruct the GC to free memory more often. These flags have a cost in terms of CPU resources but it's not as significant to prevent us from using them. More testing will be done.
=> OCPBUGSM-28683: Enable pprof when running in debug mode

deploy/operator/deploy.sh, deploy/operator/mirror_utils.sh, deploy/operator/setup_assisted_operator.sh
No reason to use `--to-release-image` flag that just confuses the release
images into 2 different repositories. It would be much simpler if the
release image and the operators images would be in the same place
From the help message:
```
--to-release-image='': Specify an alternate locations for the release image instead as tag 'release' in --to.
```
/cc @osherdp 
/cc @lranjbar 
=> MGMT-5171: Mirror OCP release image to a single repository

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go, subsystem/kubeapi_test.go
`Status.DebugInfo.LogsURL` used to be added to `ACI` as soon as
`clusterDeployments` controller reconciles with a valid backend cluster.
This scenario created an issue where it displayed the `LogsURL` before
host(s) or controller logs were collected and uploaded to storage,
creating a bad user experience with a "broken" link.
This change adds a function that validates logs collection before
displaying `Status.DebugInfo.Logs` to the user. It checks both
`ControllerLogsCollectedAt` (cluster) and `LogsCollectedAt` (host).
/cc @rollandf 
/cc @filanov 
=> OCPBUGSM-31406: Validate log collection before displaying LogsURL

internal/host/validator.go
When connectivity report is missing in the host, the validation should be `ValidationPending`. This PR changes the status from `ValidationFailure` to `ValidationPending`.
/cc @lalon4 
/assign @ori-amizur 
=> Bug 1983412: Wrong validation status for network&packet loss

internal/bminventory/inventory.go, internal/usage/consts.go
Feature usage is set to show us if different platform (rather then baremetal) is set and if credentials are set.
https://issues.redhat.com/browse/MGMT-7141
/cc @slaviered
/cc @gamli75 
/cc @michaellevy101
=> MGMT-7141: Add VMWare to feature_usage

go.mod, go.sum, subsystem/kubeapi_test.go
Using GinkgoT we can get the name of the test in any part of the code,
including BeforeEach. It enable us to log the name of the cluster
that is being created, then we can use the cluster name to find the
relevnt logs in the service logs when debugging failing tests
To make it usuful each test should add a rundom saffix/prefix for the
resouce that they are creating and the name should appear in the service
logs as well
/cc @YuviGold 
/cc @nmagnezi 
=> NO-ISSUE update ginko version and add logs to kube-api subsystem tests

cmd/operator/main.go, config/rbac/role.yaml, deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml, go.mod, go.sum, internal/controller/controllers/agentserviceconfig_controller.go, internal/controller/controllers/agentserviceconfig_controller_test.go, internal/controller/controllers/common.go
This commit adds, to the operator, the ability to create a ServiceMonitor CR when Assisted Service is being
deployed. This will allow for collecting Assited Service metrics and send them to the local prometheus.
By doing this, it will be possible to have OCM and other tools collect metrics from the local prometheus. It will also
be possible to query prometheus directly, and deploy custom Assisted Service dashboards to grafana
Tested this with CRC and following the local-development guidelines in the `operator.md` docs:
1. Built images (assisted-service and bundle)
2. Pushed to `quay.io/fpercoco/$IMAGE:service-monitor`
3. `operator-sdk -n assisted-installer run bundle quay.io/fpercoco/assisted-service-operator-bundle:service-monitor`
4. …
=> MGMT-7262: Create a ServiceMonitor when deploying Assisted Service

docs/enhancements/bmac-reboot-hosts-on-iso-change.md
When an InfraEnv's ISO gets regenerated, particularly when that is due
to a NMStateConfig being added or modified, only those agents affected
should be rebooted.
=> NO-ISSUE: enhancement proposal to avoid agent reboots

subsystem/kubeapi_test.go
Remove ntp validation from 'SNO deploy clusterDeployment full install
and validate MetaData'
because ntp doesn't affect agent state there are some reces that can
cause this validation to fail for example:
1. Host is registered and get inventory
2. Monitor set the host to known state
3. Test set ntp to success then to failure (time diff less the a sec)
4. Monitor triggered again but when comparing the old validation info
with the new he see only the failed state, current status is empty
so the controller doesn't get any notification.
There is a unit test that check that NTP info is copied from the backend
so this test case covered in unit tests.
It's possible to resolve it by reporting the ntp before reporting inventory but it feels hacky
/cc @YuviGold 
/cc @rollandf  …
=> MGMT-7319 remove ntp validation from kube-api test

internal/hardware/mock_validator.go, internal/hardware/validator.go, internal/host/conditions.go, internal/host/hostutil/test_utils.go, internal/host/refresh_status_preprocessor.go, internal/host/validator.go
currently host validations also require existence of the cluster for the host.
in late binding cluster does not necessary exists for the host.
we split the validtion in 2, based on clusterID. the validations for infra-env host
ignore the operators validations, and the cluster conditions
/cc @
/cc @
=> MGMT-7358: change host validation to support infra env

internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go
bug fix - if function return an error return value should not be used. 
/cc @carbonin 
/cc @nmagnezi 
=> NO-ISSUE fix panic in host reference

cmd/main.go, internal/host/hostcommands/free_addresses_cmd.go, internal/host/hostcommands/free_addresses_cmd_test.go, internal/host/hostcommands/instruction_manager.go, internal/host/hostcommands/instruction_manager_test.go
using DISABLED_STEPS to achieve what SupportFreeAddresses did.
Removed the need for `SUPPORT_FREE_ADDRESSES` environment variable.
SUPPORT_FREE_ADDRESSES was true by default. this aligns with the fact that `StepTypeFreeNetworkAddresses` is enabled by default (all steps are).
When running with `enableKubeAPI=true` we force `StepTypeFreeNetworkAddresses` to be disabled.
/cc @YuviGold 
/hold
=> MGMT-7268: Remove SupportFreeAddresses

deploy/s3/deployment.yaml
It would allow reaching the MinIO UI from outside the cluster.
This way, a developer would be able to browse the storage easily.
/cc @carbonin 
/cc @filanov 
=> NO-ISSUE: Deploy MinIO as a LoadBalancer

Makefile, config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml, deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml, hack/generate.sh, hack/operator-release.sh
This introduces a `hack/operator-release.sh` script that can be invoked
via:
```
BUNDLE_CHANNELS="alpha" OPERATOR_VERSION="0.1.0" ./hack/operator-release.sh
```
that can update community-operators and add the new operator version to
the skips in our base clusterserviceversion.
/cc @lranjbar 
/cc @celebdor 
=> MGMT-6750: Automate community-operator updates

internal/bminventory/inventory.go, internal/common/test_configuration.go, internal/constants/files.go, internal/host/host.go, internal/host/hostcommands/domain_name_resolution_cmd.go, internal/host/hostcommands/domain_name_resolution_cmd_test.go, internal/host/hostcommands/instruction_manager.go, internal/host/hostcommands/instruction_manager_test.go, internal/host/mock_host_api.go, internal/host/refresh_status_preprocessor.go, internal/host/statemachine.go, internal/host/transition_test.go, internal/host/validation_id.go, internal/host/validator.go, models/host.go, models/host_validation_id.go, restapi/embedded_spec.go, swagger.yaml
Add new host validation that checks if the following domains name were resolved correctly:
- api.`cluster_name`.`base_dns_domain_name`
- api-int.`cluster_name`.`base_dns_domain_name`
- *.apps.`cluster_name`.`base_dns_domain_name`
For `user_managed_networking`, if the hosts cant resolve the above domains name to any IP address the installation 
won't start until the right DNS records will be created.
/cc @omertuc
/cc @eranco74 
/cc @ori-amizur
=> MGMT-6425 Add validation for API DNS name resolution

internal/bminventory/inventory.go, internal/host/host.go, internal/host/host_test.go, subsystem/day2_cluster_test.go
For day2 hosts, 'Rebooting' stage is the last known stage as the
controller doesn't run anymore on the client's cluster, and even if
it did we shouldn't access user's clusters, therefore, it should be
taken into consideration when computing the host progress percentage.
/cc @
/cc @
=> NO-ISSUE: Adding BE progress for day2 hosts.

subsystem/kubeapi_test.go, subsystem/metrics_test.go, subsystem/utils_test.go
When clearing the DB in the subsystem tests, we should
use also the REST API in order to delete any clusters' resources
managed by the service. (e.g. discovery ISO)
`DeregisterCluster` API isn't necessarily available (e.g. cluster is being installed)
So we would log in case of a failure.
Bugfix: Metrics tests were relying on having a singluar metric and
return its counter when the total of all the metrics should be verified.
/cc @carbonin 
/cc @filanov 
=> MGMT-7382: Delete clusters using REST API on subsystem tests

internal/network/manifests_generator.go
Add `pool 0.rhel.pool.ntp.org iburst` to defaultChronyConf
as suggested [here](https://docs.openshift.com/container-platform/4.5/installing/install_config/installing-customizing.html#installation-special-config-chrony_installing-customizing) 
Closes: [OCPBUGSM-31319](https://issues.redhat.com/browse/OCPBUGSM-31319)
/cc @YuviGold 
=> Bug 1975383: Update the defaultChronyConf

api/hiveextension/v1beta1/agentclusterinstall_types.go, config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml, config/crd/resources.yaml, deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml, docs/hive-integration/kube-api-conditions.md, internal/controller/controllers/clusterdeployments_controller.go, internal/controller/controllers/clusterdeployments_controller_test.go
Hold day1 instalaltion
This feature is relevant mostly for UI, to give users an option to
review the deployment before we trigger the intallation
day2 flow will start installation automatically once hosts are added to
the cluster when they are in a ready state.
No effect on ZTP
/cc @rollandf 
/cc @avishayt 
=> MGMT-7333 Add a HoldInstallation flag to AgentClusterInstall

deploy/operator/utils.sh, deploy/operator/ztp/agentClusterInstall.j2, deploy/operator/ztp/assisted-installer-crds-playbook.yaml, deploy/operator/ztp/deploy_spoke_cluster.sh
For [MGMT-6735](https://issues.redhat.com/browse/MGMT-6735) we are adding a multi node spoke cluster in the ZTP flow. This is configuration changes made in my local dev-scripts environment to support spoke clusters.
/cc @YuviGold 
/cc @osherdp
/cc @djzager 
=> MGMT-6735: Add configurations for multi node spoke in ZTP

config/manager/manager.yaml, deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
Don't use the wrong operator image on the ocm-2.3 branch.
=> NO-ISSUE: fix operator image version

internal/ignition/ignition.go
This will cause the agent to use V2 APIs when accessing assisted service
/cc @ravidbro 
=> MGMT-7362: Change to infa env id from cluster id in discovery ignition

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go, internal/cluster/cluster.go
Generate the discovery ignition, when requested, on demand.
/cc @carbonin 
/cc @
=> MGMT-7250: Generate discovery ignition on demand

deploy/operator/gather.sh
There has been a rename of the operator from assisted-service-operator to infrastructure-operator, which made our ``oc logs`` command to look for the wrong pod.
/cc @YuviGold 
/cc @lranjbar 
=> Fix gathering of operator after operator rename

internal/bminventory/inventory.go, internal/bminventory/inventory_test.go
**Organize UpdateNetworkParams tests**
No tests were removed. :)
Group UpdateNetwork tests together with "Single Node" context and
"UserManagedNetworking" context.
Verify failures messages.
**Organize UpdateNetworkParams**
- No need to reset VIPs when DHCP mode changes because they will get changed anyway inside the inner
updateDHCP and updateNonDHCP functions.
- The change of VIP DHCP mode can be checked only incase userManagedNetworking is false, since it's being verified
For userManagedNetworking validations.
- `setMachineNetworkCIDRForUpdate` was called from multiple places in the code. It should only be called eventually
in case an update is needed.
- Move machineNetwork CIDR handling scope under SNO to be under userManagedNetworking.
/cc @tsorya 
/cc @empovit 
/cc …
=> Organize update network params
