openshift/assisted-service

- deploy/operator/README.md
- deploy/operator/utils.sh
- deploy/operator/ztp/add-remote-nodes-playbook.yaml
- deploy/operator/ztp/add_day2_remote_nodes.sh
- deploy/operator/ztp/assisted-installer-crds-playbook.yaml
- deploy/operator/ztp/baremetalHost.j2
- deploy/operator/ztp/deploy_spoke_cluster.sh
- deploy/operator/ztp/none_platform_utils.sh
- Fix day2 installation scripts for day2
- Add port 22624 to load balancer since it is used for day2
- Make day1 ZTP wait for agent CR representing masters, and not just any
agent CR
/cc @flaper87 
> MGMT-8879: Add ZTP None platform day2 flow

- docs/user-guide/rest-api-day2.md
Added a note on register InfraEnv sections regarding openshift_version property.
I.e. openshift_version is optional and defaults to the latest available openshift version.
/cc @nmagnezi 
/cc @filanov 
> NO-ISSUE: update day2 API doc

- internal/bminventory/mock_installer_internal.go
Specifically these should have been removed by https://github.com/openshift/assisted-service/pull/3417 and https://github.com/openshift/assisted-service/pull/3412
/cc @nmagnezi 
/cc @slaviered
> NO-ISSUE: Remove mocks missed in previous PRs

- deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
- deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
- hack/generate.sh
operator-sdk doesn't know how to work with sub-modules so it require to
enter into api directory and run the commands from there, in addition
the PROJECT file need to be located in the same place, according to
operator-sdk code i saw that it is not configurable to set the path to
this file.
For some reason even after setting input and output dir it still creates
a local copy of config/manifests/kustomization.yaml so i had to do a
cleanup and remove it.
/cc @osherdp 
/cc @djzager 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelin …
> MGMT-9527 fix generate-bundle after moving api to sub modules

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- subsystem/operators_test.go
When operators (CNV in particular) are enabled or disabled
the host validation status may change since the HW requirement
change as well.
The latter can cause a cluster to become not ready for installation.
However, since hosts are not refreshed synchronously, this is not relayed
immediately to the UI, causing a bad UX.
This PR refreshes the hosts within the UpdateCluster
/cc @
/cc @
> MGMT-8794: refresh hosts on cluster update

- pkg/auth/auth_assisted_service_mock_test.go
- pkg/auth/authz_handler_test.go
> MGMT-9467: Port authz_handler unit-tests to use V2 APIs

- docs/enhancements/automatic-agent-classification-labels.md
Enhancement for automatic user-defined agent labels
> MGMT-9221 Automatic user-defined agent labels enhancement

- deploy/operator/utils.sh
This change will give Hive additional time to acknowledge
the cluster installation.
/cc @
/cc @
> MGMT-9556: ZTP CI fix: increase the timeout clusterDeployment installed status

- data/default_okd_os_images.json
- data/default_okd_release_images.json
- deploy/podman/okd-configmap.yml
> MGMT-9546: update OKD configuration to 4.10

- api/hiveextension/v1beta1/agentclusterinstall_types.go
- config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
- docs/user-guide/network-configuration.md
- internal/cluster/transition_test.go
- internal/cluster/validator.go
- internal/cluster/validator_test.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
- internal/installcfg/builder/builder.go
- internal/installcfg/builder/builder_test.go
- subsystem/kubeapi_test.go
- Do not allow OpenShiftSDN as a network type for SNO
- Select OVNKubernetes automatically if no network type was specified
/cc @
/cc @
> MGMT-9177: OVNKubernetes as network type with SNO

- go.mod
- go.sum
- internal/cluster/cluster.go
- internal/migrations/20201019194303_change_overrides_to_text_test.go
- internal/migrations/20201202140700_change_image_ssh_key_text_test.go
- internal/migrations/20210218160100_validations_info_to_text_test.go
- internal/migrations/20210223090000_host_validations_info_to_text_test.go
- internal/migrations/20211115162400_modify_events_id_test.go
- internal/migrations/20220113152127_change_cluster_ssh_key_to_text_test.go
- internal/migrations/migrations_suite_test.go
- subsystem/cluster_test.go
- In migration tests, open new db connection when checking column type
since gorm uses cached query for that, which causes error, since
column type changed
- In cluster tests,Progress is returned as null if it has default
values.
/cc @filanov 
> MGMT-9577: Upgrade gorm to v1.23.2 (latest)

- cmd/main.go
See commit message
/cc @vrutkovs
> MGMT-9279: Remove assisted-service database timeout

- dashboards/grafana-dashboard-assisted-elasticsearch.configmap.yaml
- dashboards/grafana-dashboard-assisted-events-scrape.configmap.yaml
This PR adds basic grafana dashoards for events scrape and elasticsearch.
Stage:
https://grafana.stage.devshift.net/d/eUOTqvP7x/elasticsearch?orgId=1
https://grafana.stage.devshift.net/d/eUOTqvP7z/assisted-events-scrape?orgId=1
Manually created dashboards for staging, then exported them
Validated manifests manually (`oc apply -f <manifest> --dry-run`)
/cc @gamli75 
- [x ] Title and description added to both, commit and PR.
- [ x] Relevant issues have been associated (see [CONTRIBUTING] guide)
- [ x] Reviewers have been listed
- [ x] This change does not require a documentation update (docstring, `docs`, README, etc) …
> MGMT-9468: Add dashboards for events scraper and elasticsearch

- internal/bminventory/inventory.go
- internal/cluster/cluster.go
- internal/cluster/progress_test.go
- internal/host/common.go
- internal/host/host.go
Calculating the cluster progress takes long time since all the hosts are
retrieved from DB every time.
To fix, the counts of hosts are retrieved from DB grouped by role and
stage.  This makes the query and calculation much more efficient.
/cc @filanov 
> MGMT-9566: Improve UpdateInstallProgress performance calculating cluster progress

- internal/controller/controllers/agent_controller.go
In kube API, in agent controller, there is a function updateIfNeeded
that updates host record in DB.  There are severeal updates in this
function.  The first is to synchronize the approved flag with the spec.
When the clusterDeployment controller attempts to install day2 host, it
checks if it ready and if it is approved.  If the answer answer to both
is yes, then it starts installation.
There might be a situation that agent flag is set to true, but not all
host updates have been performed yet (hostname in our case).  In this
case the install-config will not reflect completely the host data after
update.
The solution is to move the update of te approved flag to be the last
operation in that function (after all the other updates).
/cc @flaper87  …
> MGMTBUGSM-191: Race between agent and clusterDeployment reconciler causes day2 host installation to ignore requested hostname

- hack/generate.sh
> NO-ISSUE: generate CRDs in root and api dir

- subsystem/wiremock_stubs.go
Add stubs for AMS Cluster Editor access query in preparation for tenancy authorization code changes
/cc @
/cc @
> MGMT-9403: cluster editor wiremock stubs

- dashboards/grafana-dashboard-assisted-installer-agent-api.configmap.yaml
- dashboards/grafana-dashboard-assisted-installer-basic-cluster-operation.configmap.yaml
- dashboards/grafana-dashboard-assisted-installer-general-overview.configmap.yaml
- dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml
> MGMT-9653: Update Assisted Grafana dashboards V2

- Dockerfile.assisted-service-build
This change should save extra 150 MB.
/cc @
/cc @
> NO-ISSUE: Reduce build image size with yum clean all

- cmd/main.go
- internal/bminventory/inventory_v2_handlers.go
- internal/controller/controllers/common.go
- internal/controller/controllers/infraenv_controller.go
- internal/controller/controllers/infraenv_controller_test.go
- internal/imageservice/url_test.go
- internal/imageservice/urls.go
When reconciling the infra env, set the boot artifact (rootfs, kernel, initrd, ipxe-script) links.
This includes some refactoring to move the logic for creating URLs to the image service out of the inventory API package and into a separate one so that they can be shared between the API and controller.
Depends on https://github.com/openshift/assisted-service/pull/3460
https://issues.redhat.com/browse/MGMT-9349
Deployed this code in a CRC cluster using the operator, created an infra-env and saw the values get correctly populated.
Example infra-env status:
```
status:
agentLabelSelector:
matchLabels:
infraenvs.agent-install.openshift.io: infra-env-74322c8
bootArtifacts:
initrd: https://assisted-image-service-assisted-installer.apps-crc.testing/images/a2c1dc4f-de0d-4955-a861-7e333906caad/pxe-i …
```
> Bug 2066917: Set boot artifact URLs in infra-env

- tools/handle_ocp_versions.py
The same error found across multiple jobs (different ocp versions):
- pull-ci-openshift-assisted-service-master-e2e-metal-assisted-ipv4v6
- pull-ci-openshift-assisted-service-master-e2e-metal-assisted
- periodic-ci-openshift-release-master-nightly-4.8-e2e-metal-assisted-ipv6
- pull-ci-openshift-assisted-service-master-e2e-metal-assisted-single-node
```
RuntimeError: command=oc adm release info 'quay.io/openshift-release-dev/ocp-release:4.6.16-x86_64' --registry-config '/tmp/tmp0iq20rme' -o template --template {{.metadata.version}} exited with an error=error: unable to read image quay.io/openshift-release-dev/ocp-release:4.6.16-x86_64: Head "https://quay.io/v2/openshift-release-dev/ocp-release/manifests/4.6.16-x86_64": received unexpected HTTP status: 500 Internal Server Error code=1
make: …
```
> MGMT-9734: Fix networking issue while trying to get cluster's current release

- models/install_cmd_request.go
- models/logs_gather_cmd_request.go
- models/next_step_cmd_request.go
- restapi/embedded_spec.go
- swagger.yaml
[MGMT-9451](https://issues.redhat.com/browse/MGMT-9451): Move cmd commands from service to agent
removing ca_cert_path from commands swagger as not needed
/cc @eranco74 
/cc @avishayt 
> MGMT-9451: Move cmd commands from service to agent

- go.mod
- go.sum
Updated github.com/moby to v20.10.14
/cc @filanov 
/cc @osherdp 
> NO-ISSUE: bump github.com/moby version

- deploy/assisted-image-service.yaml
Previously when the UI was deployed alongside the image service using
test-infra downloading the iso through the UI would throw a CORS error.
We can't know what host the user will expose the UI on when using test
infra, but we also don't care much in the test environment so just allow
all to avoid the error.
https://issues.redhat.com/browse/MGMT-9034
Made the change in a live environment and validated that the CORS error didn't occur anymore.
/cc @osherdp 
/cc @eliorerz 
> MGMT-9034: Allow all domains for CORS when deploying locally

- Makefile
- tools/wait_for_cluster_info.py
> MGMT-9779: CI - Retry cluster-info readiness

- restapi/embedded_spec.go
- swagger.yaml
New API was added to get cluster hosts by using filters.
The assisted installer should use this API, but agentAuth was missing
from API definition.
(X-Secret-Key header).
This fixes the missing definition.
/cc @osherdp 
> MGMT-9776: [Assisted-4.10] [Staging] multi cluster - installation failing

- internal/host/validations_test.go
- internal/host/validator.go
[Bug 2065034](https://bugzilla.redhat.com/show_bug.cgi?id=2065034)
Originally when a day 2 host is added to a cluster, the ignition
validation will fail and show the message that the ignition is not
downloadable, which is not true and will confuse the user.
This change will show validation as pending when the API VIP connectivity
in newly added day 2 hosts is empty and only shows the failure
when the connection is not successful. It also modifies the pending
message to reflect this.
Manual test:
1. Used the assisted-test-infra to set up the environment and deploy day 2 node
````
TEST_TEARDOWN=no TEST=./src/tests/test_day2.py TEST_FUNC=test_deploy_day2_nodes_cloud $(MAKE) test;
````
3. Added debug logging to see when API VIP connectivity failed while adding day 2 node
- All hosts …
> Bug 2065034: Correct ignition validation message for day 2 host

- docs/events.yaml
- internal/bminventory/inventory.go
- internal/common/events/events.go
In a case where that InfraEnv is already bounded to a cluster,
include that cluster_id in image_info_updated event.
This will also allow the UI to get this event included in the events
query by cluster_id.
/cc @
/cc @
> MGMT-9793: Include an optional cluster_id for image_info_updated event

- internal/bminventory/inventory.go
- internal/cluster/validations/validation_test.go
- internal/cluster/validations/validations.go
- internal/dns/dns.go
- internal/host/hostutil/host_utils.go
- internal/host/hostutil/host_utils_test.go
- pkg/validations/validations.go
- pkg/validations/validations_test.go
\
[MGMT-9453](https://issues.redhat.com/browse/MGMT-9453): moving part of validation logic to pkg to use in agent
moving common validations to pkg as it should be used in agent too
/cc @eranco74 
/cc @avishayt 
> MGMT-9453: moving part of validation logic to pkg to use in agent

- internal/host/hostcommands/connectivity_check_convertor.go
- models/connectivity_check_nic.go
- models/container_image_availability_request.go
- models/domain_resolution_request.go
- models/install_cmd_request.go
- models/next_step_cmd_request.go
- restapi/embedded_spec.go
- swagger.yaml
[MGMT-9747](https://issues.redhat.com/browse/MGMT-9747): adding image validation regex to steps  request objects
[MGMT-9893](https://issues.redhat.com/browse/MGMT-9893): Add validation for domain name resolution and host nic
/cc @avishayt 
/cc @eranco74 
> MGMT-9747: adding image validation regex to steps  request objects

- Dockerfile.assisted-service
Updated the oc-image to an updated version of oc that support the new oc mirror behavior
https://bugzilla.redhat.com/show_bug.cgi?id=2069976
https://bugzilla.redhat.com/show_bug.cgi?id=1823143
Describe in the [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2069976)
/cc @tsorya 
> Bug 2069976: Error with oc-mirror using an old outdated unsupported oc client in AI

- deploy/assisted-image-service.yaml
This is required for `make deploy-test` running on local machine in kind/minikube
/cc @omertuc 
> NO-ISSUE: deploy: ensure that ServiceAccount is being created

- cmd/main.go
- internal/cluster/cluster_test.go
- internal/cluster/installer_test.go
- internal/cluster/transition_test.go
- internal/controller/controllers/controller_event_wrapper_test.go
- internal/events/event.go
- internal/events/event_test.go
- internal/events/events_api.go
- internal/host/host_test.go
- pkg/ocm/client.go
- subsystem/events_test.go
- subsystem/kubeapi_test.go
The event handler implements its access checks within the application layer. These verifications do not conform to the new tenancy policies.
This PR re-implements the access restrictions using OwnedBy API and corresponding SQL queries that conform to the new API.
It also aligns the List behavior of events with the standard requirements for list behavior.
/cc @
/cc @
> MGMT-9778: align authorization for events

- go.mod
- go.sum
Deployemnts to integration were failing with the following logs:
```
time="2022-04-11T17:59:05Z" level=info msg="NO LONGER LEADER" func="github.com/openshift/assisted-service/pkg/leader.(*Elector).createLeaderElector.func2" file="/go/src/github.com/openshift/origin/pkg/leader/leaderelector.go:203" lock=assisted-service-migration-helper pkg=migrationLeader
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb7e817]
goroutine 1 [running]:
database/sql.(*ColumnType).DatabaseTypeName(...)
/usr/local/go/src/database/sql/sql.go:3131
gorm.io/gorm/migrator.ColumnType.DatabaseTypeName(...)
/go/pkg/mod/gorm.io/gorm@v1.23.4/migrator/column_type.go:44
gorm.io/driver/postgres.Migrator.AlterColumn.func1.1(0xc00026e4e0) …
```
> MGMT-9970: Upgrade gorm PG driver to fix segfault

- docs/enhancements/ipxe-host-boot.md
- docs/user-guide/boot-discovery-image-on-aws-ec2.md
- docs/user-guide/deploy-on-bare-metal.md
- internal/bminventory/inventory_test.go
- internal/bminventory/inventory_v2_handlers.go
[MGMT-9934](https://issues.redhat.com/browse/MGMT-9934)
The iPXE script initially used did not have a compatible
syntax for different iPXE versions.
This PR modifies the syntax of the iPXE script so that it
is compatible with different iPXE versions.
/cc @filanov 
/cc @javipolo 
> MGMT-9934: Use compatible iPXE script format

- internal/host/hostutil/test_utils.go
- internal/host/refresh_status_preprocessor.go
- internal/host/statemachine.go
- internal/host/transition_test.go
- internal/host/validation_id.go
- internal/host/validator.go
- internal/network/cidr_validations.go
- internal/network/utils.go
- models/host_validation_id.go
- restapi/embedded_spec.go
- swagger.yaml
When installing host with overlapping subnets, the installation may
fail.
Added validation that no host has addresses that belong to overlapping
networks.
/cc @filanov 
/cc @avishayt 
> Bug-2070838: Installation on baremetal SNO failed because 2 interfaces had overlapping subnets

- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
There are cases that agent CR gets out of sync from the corresponding
host database record.  It happens after host database record has been
updated.
Although additional reconcile is expected at this point, there are
cases that the update result is not reflected in the CR.
In order to avoid such case, the returned value from the host
update is taken and used to update the agent status.
/cc @filanov  …
> Bug 2072929: agent is stuck on pending input condition when configuring the network for a multi node/compact ipv6 spoke

- docs/user-guide/additional-operator-notes.md
Common place for user-oriented-notes regarding additional AI operators.
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>
/cc @avishayt 
/cc @
> NO-ISSUE: Add additional operator user guide doc

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- subsystem/infra_env_test.go
Previously if the user didn't set https proxy, but did set http the
service would copy http to https. If the user then went to edit the
proxy settings the copied https proxy would display in the https proxy
text box and the http proxy would not get copied to https proxy if http
proxy was changed.
This is confusing for the user because the expectation would be that if
https proxy was copied the first time, it would be copied the second
time as well. The least surprising thing for the user is to not edit
their inputs at all even if it means they need to copy and paste the
proxy setting if they're supposed to be the same.
https://issues.redhat.com/browse/MGMT-8850
Deployed the new code and saw that https proxy was no longer filled in the proxy dialog when only http proxy was specified.
/cc …
> MGMT-8850: Don't copy http proxy to https proxy

- deploy/olm-catalog/pin-latest.py
The `pin-latest.py` script should only perform pinning for image manifest tags
that are also pointed at by another persistent, unmoving tag. This is because
otherwise the sha we pin to may get garbage collected. This is not a problem
for assisted components because we have such persistent tag. But recently we
moved to using the postgres image from a quay organization outside of our
control. That organization doesn't not have a persistent tag for every manifest
the `:latest` tag happened to be on, so we can not do pinning for the postgres
image. Pinning postgres is not too important anyway because it's very stable.
- Ran the script, saw it doesn't pin postgres
/cc @
- Is there a bug required …
> Bug 2076901: `pin-latest.py` script should exclude the postgres image

- internal/bminventory/inventory_test.go
Previously these tests defaulted to testing the old s3 code which is no
longer used in any production environment.
Changing these tests will make removing the old s3 code much easier
https://issues.redhat.com/browse/MGMT-9460
/cc @nmagnezi 
> MGMT-9460: Always use the image service in inventory unit tests

- deploy/podman/README.md
> Fix small typo in podman readme

- cmd/main.go
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/inventory_v2_handlers.go
Removes all code in bminventory which is unreachable and untested now
that the image service is required in all deployments and is also used
in unit-tests.
Part 1 of https://issues.redhat.com/browse/MGMT-9495
Later PRs will clean up parts of other packages that this patch renders unreachable.
~~Built on top of https://github.com/openshift/assisted-service/pull/3681~~ Merged
/cc @nmagnezi  …
> MGMT-9495: Remove unreachable image handling code

- Dockerfile.assisted-service
Recent updates to the oc client used by the assisted-service seems to break ICSP in disconnected environment.
This PR revert these changes:
1. Revert "NO-ISSUE: Add a retry when fetching oc with curl (#3687)"
This reverts commit 0da8d3899d8e421a424a78816bbcc75b22683384.
2. Revert "[MGMT-5442](https://issues.redhat.com//browse/MGMT-5442): assisted-service should use official oc client (#3657)"
This reverts commit cdbb65b98076673d156f5a5b787bad9378528531.
3. Revert "Bug 2069976: Error with oc-mirror using an old outdated unsupported oc client in AI (#3598)"
This reverts commit 53616082111984bbb43f4c848f7ce11c915f579f.
- Is this PR relying on CI for an e2e test run? Yes
- Should this PR be tested in a specific environment? Disconnected env
- Any …
> Bug 2077162: Can not provision SNOs in a disconnected environment

- models/disk.go
- models/host_validation_id.go
- restapi/embedded_spec.go
- swagger.yaml
[MGMT-9561](https://issues.redhat.com//browse/MGMT-9561): vsphere disk UUID enabled validation API changes
Include a flag for uuid support in the Inventory disk object. Added to the disk level instead of the host level for debugging purposes (recognize which disk has no uuid)
/cc @
/cc @
> MGMT-9561: MGMT-9562: vsphere host API changes

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/inventory_v2_handlers.go
- internal/manifests/manifests.go
- internal/manifests/manifests_test.go
- pkg/auth/auth_assisted_service_mock_test.go
- pkg/filemiddleware/middleware.go
- pkg/filemiddleware/middleware_test.go
Allow callers to provide a Last-Modified time when creating a file
download middleware. This will allow specifying the infra-env
updated time for things like the discovery ignition.
This will allow the image service to use this same time for the image
Last-Modified time.
https://issues.redhat.com/browse/MGMT-7274
Deployed assisted service with the patch, created an infra-env, and downloaded the discovery ignition:
```
$ curl -vv "http://localhost:8090/api/assisted-install/v2/infra-envs/e01468c5-9563-462c-8e32-3c46840b3fad/downloads/files?file_name=discovery.ign"
*   Trying ::1:8090...
* Connected to localhost (::1) port 8090 (#0)
> GET /api/assisted-install/v2/infra-envs/e01468c5-9563-462c-8e32-3c46840b3fad/downloads/files?file_name=discovery.ign HTTP/1.1
> Host: localhost:8090
> …
```
> MGMT-7274: Add Last-Modified to file middleware

- pkg/auth/rhsso_authz_handler.go
- pkg/auth/rhsso_authz_handler_test.go
Allow EditCluster to also delete hosts, manifests and other objects
on the cluster/infra-env including te cluster itslef
/cc @
/cc @
> MGMT-10142: EditClusterRole can delete objects

- docs/architecture.md
This would be a good resource to reference in our app-interface
documentation, but it should be up-to-date first.
https://issues.redhat.com/browse/MGMT-9060
/cc @avishayt 
> MGMT-9060: Update arch doc with image service info

- deploy/operator/capi/assisted-installer-crds-playbook.yaml
- deploy/operator/capi/baremetalHost.j2
- deploy/operator/capi/deploy_capi_cluster.sh
- deploy/operator/capi/infraEnv.j2
- deploy/operator/utils.sh
This PR creates a script responsible for deploying a cluster using CAPI
in the setup with Infrastructure Operator. It creates a required
InfraEnv, leverages BareMetalHost created by dev-scripts and later
installs HyperShift to install a cluster.
It is meant to be used by the e2e-metal-assisted-operator-capi job.
/cc @javipolo 
/cc @eranco74 
> MGMT-9227: Create deploy_capi_cluster script for CAPI CI

- deploy/operator/capi/deploy_capi_cluster.sh
As the fix that was supposed to fix the issue
https://bugzilla.redhat.com/show_bug.cgi?id=2079177 has been merged
already, we should be safe to use the hypershift:latest instead our
custom build of the image.
/cc @eranco74 
/cc @
> NO-ISSUE: Use official Hypershift image in E2E test

- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/network/manifests_generator.go
- internal/network/manifests_generator_test.go
- internal/network/mock_manifests_generator.go
[MGMT-10174](https://issues.redhat.com//browse/MGMT-10174): Add node ip hint manifest for sno.
We want to be able to set ip for kubelet that will match machine cidr
that we set for cluster.
- [] None
/cc @flaper87 
/cc @eranco74 
> MGMT-10174: Add node ip hint manifest for sno

- docs/user-guide/deploy-on-bare-metal.md
https://issues.redhat.com/browse/MGMT-9787
/cc @javipolo 
> MGMT-9787: Add the built-in ipxe script endpoint to baremetal deploy docs

- Dockerfile.assisted-service.ocp
Python client was removed for OCP changes. This commit removes the redundant command.
/cc @
/cc @
> AGENT-104: Removed redundant command

- internal/network/cidr_validations.go
- internal/network/machine_network_cidr.go
- internal/network/machine_network_cidr_test.go
CIDR block size should be large enough to accommodate all the hosts' IPs. When a user chooses a smaller range than required, the error message is not clear enough.
This PR adds a recommendation to the error message to guide the users.
/cc @
/cc @
> MGMT-8796: clear msg about cidr range

- subsystem/subsystem_suite_test.go
> NO-ISSUE: Remove unused subsystem client agentBMClient2

- api/vendor/github.com/openshift/assisted-service/models/step.go
- internal/host/hostcommands/api_vip_connectivity_check_cmd.go
- internal/host/hostcommands/connectivity_check_cmd.go
- internal/host/hostcommands/container_image_availability_cmd.go
- internal/host/hostcommands/dhcp_allocate_cmd.go
- internal/host/hostcommands/disk_performance_cmd.go
- internal/host/hostcommands/domain_name_resolution_cmd.go
- internal/host/hostcommands/free_addresses_cmd.go
- internal/host/hostcommands/instruction_manager.go
- internal/host/hostcommands/inventory_cmd.go
- internal/host/hostcommands/logs_cmd.go
- internal/host/hostcommands/ntp_synchronizer_cmd.go
- internal/host/hostcommands/stop_installation_cmd.go
- models/step.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/step.go
[MGMT-9452](https://issues.redhat.com//browse/MGMT-9452): Remove "command" from get next step api
As we are not sending command in step anymore we should remove it
/cc @eranco74 
> MGMT-9452: Remove "command" from get next step api

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/mock_cluster_api.go
- subsystem/cluster_test.go
[MGMT-10237](https://issues.redhat.com//browse/MGMT-10237): Add events and cluster metadata to cluster logs
We want to have all the data inside same tar file that will allow users
to upload tar to BZ and we will get events and cluster metadata inside
it
- [] None
/cc @eranco74 
/cc @avishayt 
> MGMT-10237: Add events and cluster metadata to cluster logs

- api/v1beta1/agentserviceconfig_types.go
- cmd/main.go
- config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
- config/crd/resources.yaml
- config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
- config/rbac/ocp/role.yaml
- config/rbac/role.yaml
- deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
- deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
- go.mod
- go.sum
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/inventory_v2_handlers.go
- internal/controller/controllers/agentserviceconfig_controller.go
- internal/controller/controllers/agentserviceconfig_controller_test.go
- internal/controller/controllers/infraenv_controller.go
- internal/controller/controllers/infraenv_controller_test.go
- internal/imageservice/url_test.go
- internal/imageservice/urls.go
- pkg/app/middleware.go
- pkg/app/middleware_test.go
- vendor/github.com/openshift/assisted-image-service/LICENSE
- vendor/github.com/openshift/assisted-image-service/pkg/servers/servers.go
- vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
- vendor/modules.txt
This adds a new HTTP route to operator to serve kernel/rootfs artifacts for IPXE deployments. iPXE deployments can't access HTTPS endpoints, so we should have a plain HTTP endpoint to serve these artifacts.
Note that it doesn't apply to console.redhat.com deployment - users are expected to copy those internally and host them via http themselves.
TODO:
/cc @carbonin 
> Bug 2078531: Expose ipxe boot artifacts via HTTP

- internal/bminventory/inventory.go
- internal/bminventory/inventory_v2_handlers.go
- internal/bminventory/mock_installer_internal.go
- internal/common/common.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
With the removal of V1 API, this flag is no longer needed.
/cc @filanov 
/cc @carbonin 
> MGMT-9430: Remove v1Flag from V2ImportClusterInternal

- openshift/template.yaml
Memory consumption is currently reaching somewhere shy of 1.6Gi in production (stablizes at this value).
Parametrizing this values would allow us to change it directly from CD when consumption changes, without the need of merging PR within the codebase
- [] None
/cc @osherdp 
/cc @oourfali 
> NO-ISSUE: increase memory requests and limits, and parametrize them

- docs/enhancements/saas-per-organization-feature-access.md
> MGMT-10196: feature enablement enhancement doc

- pkg/staticnetworkconfig/generator.go
[MGMT9574](https://issues.redhat.com/browse/MGMT-9574
)
Improvement PR for https://github.com/openshift/assisted-service/pull/3767
The error message returned is now more clear and includes
the actual error when nmstatectl is run and which host
the error occurred on.
1. Deploy assisted-service with changes
2. Run make deploy_nodes to deploy a cluster
3. Curl the infra-envs patch API
````
curl -XPATCH  --header "Content-Type: application/json" $SERVICE_URL/api/assisted-install/v2/infra-envs/$INFRA_ENV_ID -d '{"static_network_config":[{"network_yaml":"aaaa","mac_interface_map":[{"mac_address":"52:54:00:ee:42:e1","logical_nic_name":"eth0"}]}]}'
````
5. Check the error message returned
````
{"code":"400","href":"","id":400,"kind":"Error","reason":"1 error occurred:\n\t* failed to validate …
```
> MGMT-9574: Improve error message when updating static network

- dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
This PR is fixing:
* gauges on top for resource usage were not displaying data. Metric has been fixed and also duplicated to show both limits and requests ratio
* added more info to CPU chart: limits and requests lines and throttled time
* added more info to Memory chart: limits and requests lines
It will look something like:
/cc @
/cc @
> NO-ISSUE: fix and tweak grafana dashboard about resource usage

- openshift/template.yaml
This will improve readability for memory requests/limits.
At the moment they are set using Gibibytes (`Gi`), but read and possibly rounded up using Gigabytes (`G`).
This PR changes declared value to Gigabytes (`G`), so that it can be round up cleanly.
/cc @
/cc @
> NO-ISSUE: improve readability for memory limits and requests

- internal/controller/controllers/agent_controller.go
> MGMT-10535: Set inventory+labels after inventory reported

- internal/host/common.go
- internal/host/host.go
- internal/host/transition.go
- internal/host/transition_test.go
> MGMT-10305: fix disconnect validation on bootstrap

- api/vendor/github.com/openshift/assisted-service/models/cluster.go
- api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
- api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
- cmd/main.go
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/progress_test.go
- internal/cluster/transition_test.go
- internal/common/common.go
- internal/operators/odf/validation_test.go
- internal/provider/baremetal/consts.go
- internal/provider/baremetal/inventory.go
- internal/provider/base.go
- internal/provider/mock_base_provider.go
- internal/provider/ovirt/inventory.go
- internal/provider/registry/mock_providerregistry.go
- internal/provider/registry/registry.go
- internal/provider/registry/registry_test.go
- internal/provider/vsphere/inventory.go
- models/cluster.go
- models/cluster_create_params.go
- models/v2_cluster_update_params.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/cluster.go
- vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
- vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
This reverts commit 7296f386338fe038eab9f7bf2463eac66eda7c63.
/cc @
/cc @
> Revert "MGMT-9259: Enhance the schedulable masters feature (#2861)"

- internal/controller/controllers/preprovisioningimage_controller.go
- internal/controller/controllers/preprovisioningimage_controller_test.go
Just adding UT
-->
skipper make all
/cc @tsorya 
/cc @avishayt 
> MGMT-10004: Add UT for PreprovisioningImage controller

- hack/setup_env.sh
While not perfect (as it will not retry for non-transient errors) this
will make those kind of failures happen less:
```
+ echo 'Installing spectral...'
+ curl -L
https://github.com/stoplightio/spectral/releases/download/v5.9.1/spectral-linux
-o /usr/local/bin/spectral
% Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
Dload  Upload   Total   Spent    Left
Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
0
83 54.4M   83 45.3M    0     0  34.0M      0  0:00:01  0:00:01 --:--:--
34.0M
95 54.4M   95 51.9M    0     0  34.9M      0  0:00:01  0:00:01 --:--:--
42.5M
curl: (18) transfer closed with …
```
> NO-ISSUE: Retry and redirect all curl actions

- data/default_okd_os_images.json
- data/default_okd_release_images.json
- deploy/podman/okd-configmap.yml
Update release image to latest stable and OS image to FCOS stable
/cc @
/cc @
> deploy/podman: update OKD images

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster.go
- internal/cluster/mock_cluster_api.go
- internal/host/host_test.go
- internal/host/monitor.go
- subsystem/cluster_test.go
Trigger recalculation of suggested role for auto-assign hosts
when hosts are added or deleted and when operators are added
or deleted.
These triggers affect the considerations for role assignment
so reevaluation is in order.
/cc @
/cc @
> MGMT-8202: recalc suggested roles on host/operator changes

- docs/hive-integration/README.md
- docs/hive-integration/baremetal-agent-controller.md
Add documentation for the converged flow
https://issues.redhat.com/browse/MGMT-10281
/cc @flaper87
/cc @avishayt 
> MGMT-10281: Add documentation for the converged flow

- internal/versions/versions.go
- internal/versions/versions_test.go
- pkg/auth/authz_utils.go
- subsystem/versions_test.go
> MGMT-10643: V2ListSupportedOpenshiftVersions should not err for ValidateAccessToCPUArchitecture false

- api/vendor/github.com/openshift/assisted-service/models/host.go
- client/installer/v2_get_next_steps_parameters.go
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster_test.go
- internal/cluster/transition_test.go
- internal/common/common.go
- internal/host/host_test.go
- internal/host/hostutil/test_utils.go
- models/host.go
- restapi/embedded_spec.go
- restapi/operations/installer/v2_get_next_steps_parameters.go
- restapi/operations/installer/v2_get_next_steps_urlbuilder.go
- subsystem/cluster_test.go
- subsystem/host_v2_test.go
- subsystem/ipv6_test.go
- subsystem/metrics_test.go
- subsystem/utils_test.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/host.go
If the timestamp from get-next-steps does not exist, use the timestamp
from inventory.
This change is the first step before the timestamp will be removed from
the inventory.
/cc @filanov 
/cc @avishayt 
> MGMT-10662: Add timestamp to get-next-steps and let the service use it

- Makefile
- dashboards/grafana-dashboard-assisted-installer-agent-api.configmap.yaml
- dashboards/grafana-dashboard-assisted-installer-basic-cluster-operation.configmap.yaml
- dashboards/grafana-dashboard-assisted-installer-cluster-overview.configmap.yaml
- dashboards/grafana-dashboard-assisted-installer-deployment-overview.configmap.yaml
- dashboards/grafana-dashboard-assisted-installer-general-overview.configmap.yaml
- dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
- dashboards/grafana-dashboard-assisted-installer-rnd-overview.configmap.yaml
- dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml
- dashboards/grafana-dashboard-assisted-resource-dashboard.yaml
Configmap metadata  got "eaten" by one of the previous PRs.
This PR aims to:
* restore such metadata
* reorganize all dashboards metadata so that this issue would be less likely to happen in the future
* add Makefile validation for `dashboards/` folder
- [] None
/cc @
/cc @
> NO-ISSUE: fix dashboards metadata

- internal/host/transition_test.go
- internal/host/validator.go
Presently the validation "hostname-valid" does nothing to ensure that
"localhost.localdomain" is not considered valid.
This PR rectifies that and introduces a unit-test to ensure that this
works.
- [] Manual (Elaborate on how it was tested)
/cc @osherdp 
/cc @filanov 
> MGMT-10722: Hostname 'localhost.localdomain' should not be valid

- internal/operators/cnv/cnv_operator.go
- internal/operators/cnv/cnv_operator_test.go
[MGMT-9388](https://issues.redhat.com//browse/MGMT-9388): Incorrect minimal CPU and RAM requirements for cnv operator shown in UI
Changing cnv minimum requirements for sno (master)
- [] None
/cc @
/cc @
> MGMT-9388: Incorrect minimal CPU and RAM requirements for cnv operator shown in UI

- internal/hardware/validator.go
- internal/host/host.go
- internal/host/host_test.go
- internal/host/transition.go
- internal/host/transition_test.go
- internal/host/validator.go
- subsystem/metrics_test.go
Presently this var is hardwired to three minutes, it is desirable to
make this configurable but with a 3 minute default.
This PR addresses this.
/cc @filanov 
/cc @omertuc 
> MGMT-9553: Ensure that MaxHostDisconnectionTime is configurable.

- internal/controller/controllers/preprovisioningimage_controller.go
- internal/ignition/ironic.go
Updated the default ironic agent image
- Should this PR be tested in a specific environment? devscripts
-->
https://bugzilla.redhat.com/show_bug.cgi?id=2096460
/cc @tsorya 
/cc @avishayt 
> BZ-2096460: Spoke BMH stuck inspecting when deployed via the converged workflow

- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
If a multipath device is detected add the "rd.multipath=default" karg.
If a multipath device is being used for installation, also add the "root=/dev/disk/by-label/dm-mpath-root" karg.
/cc @
/cc @
> MGMT-10801: Add necessary kargs for multipath

- internal/garbagecollector/garbageCollector.go
> NO-ISSUE: Remove unused GarbageCollectors interface

- Makefile
- tools/wait_for_cluster_info.py
Several[1] jobs are failing for this, and it looks like
the cluster was just not ready on time. This is an attempt
to retry cluster-info several times before we fail the job.
[1] one example: periodic-ci-openshift-assisted-service-release-ocm-2.5-subsystem-kubeapi-aws-periodic
/cc @omertuc
> BUG 2097700: CI - Retry cluster-info readiness

- hack/Makefile
- models/vendor/github.com/PuerkitoBio/purell/purell.go
- models/vendor/github.com/asaskevich/govalidator/patterns.go
- models/vendor/github.com/asaskevich/govalidator/validator.go
- models/vendor/github.com/mailru/easyjson/jlexer/lexer.go
- models/vendor/golang.org/x/net/idna/idna10.0.0.go
- models/vendor/golang.org/x/net/idna/idna9.0.0.go
These should have been updated previously, but were missed it seems.
/cc @nmagnezi 
> NO-ISSUE: Generate /models/vendor directory correctly

- deploy/operator/ztp/deploy_spoke_cluster.sh
We need to make sure that the appropriate ports have been exposed for
the services that have been exposed via libvirt DNS.
This is to ensure the assisted-service is able to connect to the API
server.
/cc @omertuc 
/cc @osherdp 
> MGMT-10597: Open firewall ports after DNS setup.

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
BMAC should reconcile BMH only if the BMH isn't detached and has an InfraEnv label
- Should this PR be tested in a specific environment? devscripts
-->
/cc @tsorya 
> bz-2096106: Assisted service triggers the worker nodes re-provisioning on the hub cluster when the converged flow is enabled

- docs/enhancements/4-nodes-cluster-deployment.md
Enhancement to define the support and implementation of a 4-nodes
cluster deployment flow through assisted service.
/cc @omertuc 
/cc @avishayt 
/cc @mhrivnak 
> MGMT-8987: 4 nodes cluster deployment

- cmd/main.go
- deploy/operator/setup_assisted_operator.sh
- docs/hive-integration/README.md
Add ALLOW_CONVERGED_FLOW env to setup_assisted_operator.sh
Once this merges jobs that should test the converged flow will set this env to "True" (the current default in the assisted-service is False)
-->
https://issues.redhat.com/browse/MGMT-10488
/cc @osherdp 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#comm …
> MGMT-10488: Add assisted-operator-ztp job for the converged flow

- cmd/agentbasedinstaller/agent_based_installer.go
- cmd/agentbasedinstaller/client/main.go
- subsystem/agent_based_installer_client_test.go
For the agent-based-installer the release mirror needs to be set when configured in the agent. Use the assisted-service environment variable to accomplish this.
/cc @
/cc @
> AGENT-215: Set release mirror for agent-based-installer

- deploy/operator/gather.sh
> MGMT-10864: Collect CAPI data in assisted-baremetal-operator-gather

- internal/ignition/ignition.go
[MGMT-10330](https://issues.redhat.com//browse/MGMT-10330): do not change network manager config in case of SNO
In sno case there is no network scripts that requires us to touch
network manager
/cc @omertuc 
> MGMT-10330: do not change network manager config in case of SNO

- internal/featuresupport/support_levels_list.go
Some customer has the following message indicating that their clusters are not supported because of usage of CMN configuration on their mixed baremetal+virtual machines clusters:
```
Cluster support level: Limited
Your cluster will be subject to support limitations because it includes:
* Cluster-managed networking with some or all discovered hosts as
virtual machines
```
This changes the feature-levels list to not marked this usage as not-supported.
/cc @gamli75 
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelin …
> MGMT-10889: consider usage of CMN with VMs as supported

- Dockerfile.assisted-service.ocp
Once the images are building successfully in OSBS (and only then), they can be added to the release payload image by setting a label in the Dockerfile:
`LABEL io.openshift.release.operator=true`
/cc @
/cc @
> AGENT-75: Add assisted installer images into OCP playload for Agent Work

- deploy/operator/gather.sh
> MGMT-10493: Don't truncate CAPI/Hypershift logs in CI

- deploy/operator/capi/deploy_capi_cluster.sh
Allow overriding the provider image when creating a hostedcluster
- Should this PR be tested in a specific environment? CI jobs
https://issues.redhat.com/browse/MGMT-10916
/cc @
> MGMT-10916: Change capi-provider-agent jobs to use the operator workflow

- deploy/ui/ui_ingress.yaml
Seems like when we moved to ``networking.k8s.io/v1`` in https://github.com/openshift/assisted-service/pull/4001 we also needed to apply some new format of Ingress objects, otherwise we get:
```
error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field \"serviceName\" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field \"servicePort\" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0]): missing required field \"pathType\" in io.k8s.api.networking.v1.HTTPIngressPath]
```
/cc @eliorerz 
/cc @lalon4 
- Should …
> NO-ISSUE: fix assisted-installer-ui ingress format

- Dockerfile.assisted-service.ocp
install `libvirt-libs` and `nmstate` packages for openshift-install 
/cc @
/cc @
> AGENT-224:  install packages for openshift-install

- internal/network/utils.go
- internal/network/utils_test.go
To check equivalence between 2 lists we use a function
areListsEquivalent.
The function didn't work correctly if one list had duplicate items and
the other didn't.
/cc @tsorya 
/cc @
> MGMT-10865: Machine network is not changing if list has same values

- internal/bminventory/inventory.go
Use the pre-generated infra env id by agent installer in case of agent-based installation. Otherwise, continue the usual way to generate the infra env id and register the infra env.
/cc @
/cc @
> AGENT-144: Use pre-generated InfraEnv ID

- deploy/operator/ztp/deploy_spoke_cluster.sh
> [release-ocm-2.5] more indicative message when agents not coming back (#3671)

- deploy/operator/gather.sh
> NO-ISSUE: Gather service pods definitions in the operator CI

- openshift/template.yaml
During triage we found a lot of cases of media disconnection from users
using full-iso, we would like to set the default for SAAS as
minimal-iso. This PR enabling the configuraion for the SAAS, if we find
it helpfull we will switch the default in the service as well.
/assign @gamli75 
/assign @oourfali 
> MGMT-10967: Set minimal ISO as default for SAAS deployment

- internal/controller/controllers/preprovisioningimage_controller.go
- internal/controller/controllers/preprovisioningimage_controller_test.go
Fixed reason format in case of unsupported image format condition
-->
https://issues.redhat.com/browse/MGMT-10989
While writing the subsystem test, will be added in another PR
/cc @tsorya 
/cc @avishayt  …
> MGMT-10989: Missing condition status in case of unsupported image format

- deploy/podman/configmap.yml
- deploy/podman/okd-configmap.yml
onprem job fails because rootfs_url is not set anymore in `OS_IMAGES`,
we then need to define `IMAGE_SERVICE_HOST` and `IMAGE_SERVICE_SCHEME`.
/cc @osherdp 
> NO-ISSUE: Fix onprem job

- Makefile
- hack/converged_flow_crds/config.openshift.io_clusteroperators.yaml
- hack/converged_flow_crds/metal3.io_preprovisioningimage.yaml
- hack/converged_flow_crds/metal3.io_provisioning.yaml
- hack/converged_flow_crs/baremetal_operrator.yaml
- hack/converged_flow_crs/metal3.yaml
- hack/converged_flow_crs/provisioning.yaml
- subsystem/kubeapi_test.go
- tools/deploy_assisted_installer_configmap.py
- tools/deploy_converged_flow_requirements.py
- tools/deploy_crd.py
- tools/utils.py
-->
https://issues.redhat.com/browse/MGMT-10767
/cc @tsorya 
/cc @avishayt 
> MGMT-10767: Add subsystem for converged flow

- deploy/operator/setup_lso.sh
Currently all our ZTP jobs that are using 4.11 hub-cluster are failing to install LSO, as no 4.11 specific release has been made so far (and it will only be made around 4.11 GA date).
Changing currently automation to use ``4.10`` registry as a temporal workaround.
/cc @eranco74 
> MGMT-11011: use 4.10 index for LSO installation in 4.11

- OWNERS_ALIASES
> NO-ISSUE: Add @rccrdpccl as approver

- internal/host/statemachine.go
- internal/host/transition_test.go
Backports #4061
In more details:
Vsphere Hosts with "pending for input" status cannot be modified
Getting "no condition passed to run transition RefreshHost from state pending-for-input"
Updating it to be part of "sufficient for install" checks will resolve this issue
> [cloud_hotfix_releases] MGMT-11000: Failed to update the cluster when select Integrate with vSphere

- internal/host/statemachine.go
- internal/host/transition_test.go
Getting "no condition passed to run transition RefreshHost from state pending-for-input"
Updating it to be part of sufficient for install checks will resolve this issue
/cc @
/cc @
> MGMT-11000: Failed to update the cluster when select Integrate with vsphere

- deploy/operator/setup_lso.sh
> NO-ISSUE: added some logging in setup_lso.sh

- deploy/operator/ztp/add_day2_remote_nodes.sh
Nothing interesting, just changed some names / moved things
to make the script a bit easier to understand
> NO-ISSUE: Some cleanup of `add_day2_remote_nodes.sh`

- internal/common/test_configuration.go
- internal/host/hostutil/test_utils.go
- internal/host/transition_test.go
- internal/host/validator.go
- internal/network/utils.go
This commit adds a check to ensure that when validating the DNS resolution of the API address that none of these addresses are matched to a current master as this is the incorrect API address.
/cc @
/cc @
> MGMT-10921: Ensure that API DNS validation checks for resolution to a master.

- go.mod
- internal/provider/ovirt/base.go
- internal/provider/ovirt/base_test.go
- internal/provider/ovirt/consts.go
- internal/provider/ovirt/ignition.go
- internal/provider/registry/registry.go
- internal/provider/registry/registry_test.go
It looks like the master's manifest file names can change between
openshift installer versions and makes the assisted installer to fail
when activating the oVirt provider.
The proposed changes make use of file globs to find the actual
master files.
/cc @eliorerz 
/cc @osherdp 
- [] Relevant issues have been associated (see [CONTRIBUTING] guide)
> Bug 2100857: Fix master's manifest file pattern for oVirt provider

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
When no operators are updated, the UI sends an empty list of
operators with the update request and not nil as the BE expects.
Check for this case before resetting the auto-assigned roles to avoid redundant resets.
/cc @
/cc @
> MGMT-10838: do not reset roles when operators are not updated

- dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Adding new panel CPU vs response time.
This will be useful once we can tweak limits and verify how the service is affected.
Current CPU and Memory usage charts:
Proposed CPU and Memory usage charts:
Additional chart CPU vs response time:
- [] None
/cc @
/cc @
> NO-ISSUE: add CPU vs response time panel, unify limits and resources

- hack/setup_env.sh
> NO-ISSUE: aws cli isn't available as a package in centos9

- data/default_okd_release_images.json
- deploy/podman/okd-configmap.yml
Update deployed OKD to 4.10.0-0.okd-2022-07-09-073606
/cc @
/cc @
> Update OKD version to latest stable

- hack/start_db.sh
- pg_ctl could be at /usr/bin or at /opt/rh/rh-postgresql12/root/usr/bin/
Use the PATH instead of specific location
/cc @
/cc @
> Update postgres path - use PATH instead of absolute location

- Makefile
- hack/setup_env.sh
…tead of the huge builder container
/cc @
/cc @
> Minimize CI image - extract unit-tests requirements 

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/usage/consts.go
> MGMT-10985: add feature usage for static IP

- internal/controller/controllers/bmh_agent_controller.go
An extermely rare scenario during development caused the service to crash
because there were no machine resources whne looking for the spoke
masters.
Even though this scenario is not expected to happen during regular flows
of installation, it is still good habit to check if the list of machine
has items in it before referencing them.
/cc @
/cc @
> MGMT-10570: check that are master machine found before referencing them

- internal/ignition/templates.go
- internal/ignition/templates/discovery.ign
- internal/ignition/templates/multipath.conf
Currently some of the files included in the ignition configurations are
generated with opaque data URLs like this:
```
{
"overwrite": true,
"path": "/etc/multipath.conf",
"mode": 420,
"user": {
"name": "root"
},
"contents": { "source": "data:text/plain;charset=utf-8;base64,ZGVmYXVsdHMgewogICAgdXNlcl9mcmllbmRseV9uYW1lcyB5ZXMKICAgIGZpbmRfbXVsdGlwYXRocyB5ZXMKICAgIGVuYWJsZV9mb3JlaWduICJeJCIKfQpibGFja2xpc3RfZXhjZXB0aW9ucyB7CiAgICBwcm9wZXJ0eSAiKFNDU0lfSURFTlRffElEX1dXTikiCn0KYmxhY2tsaXN0IHsKfQo=" }
}
```
That is difficult to change and to review, because the contents of the
file aren't immediately visible. To improve that this patch adds an new
`toBase64` template function that combined with the `executeTemplate`
template function introduced in a previous patch make it possible to
write those …
> NO-ISSUE: Use template function go generate data URL

- Dockerfile.assisted-service
This is in preparation for upcoming NMState work done in [MGMT-8568](https://issues.redhat.com//browse/MGMT-8568)
/cc @
/cc @
> MGMT-10866: Compile assisted-service with CentOS stream 9

- api/v1beta1/infraenv_types.go
- config/crd/bases/agent-install.openshift.io_infraenvs.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
- internal/controller/controllers/infraenv_controller.go
- internal/controller/controllers/infraenv_controller_test.go
- vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go
This is needed to support boot control in Kube API.
/cc @carbonin 
/cc @
> MGMT-11174: Add IPXE boot control flag to infra env in kube API

- internal/bminventory/inventory.go
- restapi/embedded_spec.go
- subsystem/cluster_test.go
- subsystem/host_test.go
- subsystem/operators_test.go
- subsystem/utils_test.go
- swagger.yaml
> MGMT-10840: Change VIP DHCP allocation default to false

- api/vendor/github.com/openshift/assisted-service/models/platform.go
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/provider/baremetal/inventory.go
- internal/provider/base.go
- internal/provider/mock_base_provider.go
- internal/provider/ovirt/consts.go
- internal/provider/ovirt/ignition.go
- internal/provider/ovirt/installConfig.go
- internal/provider/ovirt/inventory.go
- internal/provider/registry/mock_providerregistry.go
- internal/provider/registry/registry.go
- internal/provider/registry/registry_test.go
- internal/provider/vsphere/consts.go
- internal/provider/vsphere/inventory.go
- models/platform.go
- pkg/generator/generator.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/platform.go
- Ovirt has it's own property under platform. This PR remove the ovirt object.
- Remove the ovirt credentials from the service database 
Basically the main logic for ovirt platform has stayed the same, the option to change/add credentials was removed
/cc @gamli75 
/cc @avishayt 
/cc @eranco74 
/cc @oourfali 
> MGMT-10007: Remove ovirt-platform object under platform. Change cluster.platform to PlatformType

- cmd/main.go
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/mock_installer_internal.go
- internal/cluster/validations/mock_validations.go
- internal/cluster/validations/validation_test.go
- internal/cluster/validations/validations.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
- internal/controller/controllers/common.go
- internal/controller/controllers/infraenv_controller.go
- internal/controller/controllers/infraenv_controller_test.go
- internal/controller/controllers/pullsecret_handler.go
- subsystem/kubeapi_test.go
> MGMTBUGSM-412: validate pull secret in kube-api cluster deployment

- docs/events.yaml
- internal/bminventory/inventory.go
- internal/common/events/events.go
- internal/common/validations.go
- internal/feature/flags.go
- internal/hardware/validator.go
- internal/host/hostcommands/instruction_manager.go
- internal/host/hostcommands/upgrade_agent_cmd.go
- internal/host/hostcommands/upgrade_agent_cmd_test.go
- internal/host/hostutil/test_utils.go
- internal/host/refresh_status_preprocessor.go
- internal/host/transition_test.go
- internal/host/validation_id.go
- internal/host/validations_test.go
- internal/host/validator.go
- openshift/template.yaml
This patch implements the agent upgrade feature.
The more relevant changes are the following:
- Added a new `ENABLE_UPGRADE_AGENT` feature flag that enables or
disables the feature completely.
- Added a new `compatible-agent` validation that will fail when the
agent sends an image reference that isn't compatible with what the
service expects.
- Added a new `upgrade-agent` step that the service will use to ask the
agent to upgrade. This step will replace all the usual steps when
`compatible-agent` validation fails.
- Added events to inform the user when the upgrade starts, finishes or
fails.
Related: https://github.com/openshift/assisted-service/blob/master/docs/enhancements/agent-upgrade.md  
Related: https://issues.redhat.com/browse/MGMT-11026  
Related: …
> MGMT-11027: Implement agent upgrade feature

- api/vendor/github.com/openshift/assisted-service/models/inventory.go
- internal/common/common.go
- models/inventory.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/inventory.go
The timestamp is not in use.
/cc @avishayt 
/cc @
> MGMT-9506: Remove timestamp from host inventory

- docs/cloud.md
It was using v1 instead of v2, and also had some typos / disorganization.
/cc @romfreiman
> NO-ISSUE: cloud.md needs a little refresh

- internal/host/hostutil/host_utils.go
This PR fixes the wrong formula for converting bytes to gigabytes.
/cc @omertuc
> NO-ISSUE: Fix conversion of disk size for device hints

- data/default_okd_os_images.json
- data/default_okd_release_images.json
- deploy/podman/okd-configmap.yml
Update OKD to 4.11.0-0.okd-2022-07-29-154152
> deploy/podman: update okd to 4.11

- openshift/template-monitoring.yaml
As servicemonitors are deployed to app-interface namespace, we need different name for different environments, as integration and stage are run on the same cluster
/cc @gamli75 
/cc @osherdp 
> MGMT-11309: add suffix to servicemonitor name

- internal/host/hostcommands/instruction_manager.go
- internal/host/hostcommands/instruction_manager_test.go
-->
https://issues.redhat.com/browse/MGMT-11441
/cc @avishayt 
/cc @jhernand 
> MGMT-11441: Allow Agent Upgrade while hosts are pending-for-input

- Dockerfile.assisted-service
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/common/common.go
- internal/oc/extract.go
- internal/oc/release.go
- internal/oc/release_test.go
- internal/versions/versions.go
- internal/versions/versions_test.go
- subsystem/kubeapi_test.go
This PR adds support of multiarch OCP release images to the Assisted
Service.
The following happens now when a multiarch release image is provided via
the ClusterImageSet
1) cluster.CPUArchitecture is set as "multiarch"
2) validation of existence of OS image matching version and architecture
is offloaded to the InfraEnv when the ISO is created
3) validation of matching cluster's and InfraEnv's architecture is
removed
The rationale for (1) is that if using multiarch release image, the
cluster is no longer bound to one particular architecture but can rather
be deployed with any architecture as long as release image contains an
image for it and OS image that matches the version and architecture
exists.
The rationale for (2) is that the set of architectures supported by the
release image can …
> MGMT-8890: Integrate support for multiarch release images

- vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
This was originally changed in 226c77f2828e0494b0ebed64a783c514d31dc5e4,
but the service vendor was missed.
https://github.com/openshift/assisted-service/pull/4219
/cc @avishayt 
> NO-ISSUE: Vendor recent changes to api module in service

- docs/hive-integration/README.md
- docs/user-guide/network-configuration/static-configuration.md
Each InfraEnv can include a limited number of NMStateConfigs.
The limitation comes from the  ignition content length limit.
With the attached sample config, each InfraEnv can include up to 3960 configurations.
/cc @carbonin 
/cc @filanov 
> MGMT-10638: Document nmstate limits

- internal/host/statemachine.go
- internal/host/transition_test.go
Without these transitions the host monitor complains with errors like:
```
time="2022-08-09T19:39:52Z" level=error msg="failed to refresh host 16d46e6d-14b2-438b-878e-0ac9d4ab0815 state" func="github.com/openshift/assisted-service/internal/host.(*Manager).infraEnvHostMonitoring" file="/assisted-service/internal/host/monitor.go:223" error="no condition passed to run transition RefreshHost from state reclaiming" pkg=host-state request_id=f4381df3-449f-4573-a81d-748a801ec635
time="2022-08-09T19:40:32Z" level=error msg="failed to refresh host 16d46e6d-14b2-438b-878e-0ac9d4ab0815 state" func="github.com/openshift/assisted-service/internal/host.(*Manager).infraEnvHostMonitoring" file="/assisted-service/internal/host/monitor.go:223" error="no condition passed to run transition RefreshHost from …
```
> MGMT-10734: Add noop refresh transitions for reclaim states

- docs/user-guide/README.md
fix broken doc link
/cc @
/cc @
> NO-ISSUE: Fix incorrect network docs link in main README.md

- deploy/operator/gather.sh
- Should this PR be tested in a specific environment? operator job
- Any logs, screenshots, etc that can help with the review process? yes, look for the PPI CRs in the BMH folder under artifacts
-->
https://issues.redhat.com/browse/MGMT-11509
/cc @carbonin 
/cc @tsorya 
> MGMT-11509: Collect preprovisioningimages CR in operator gather job

- internal/network/connectivity_groups.go
When having a large cluster that has many varying connectivity problems,
there are many possible groups.  Finding the optimal one takes a very
long time. This causes cluster monitor to never return which causes the
assisted installer pod to be restarted due to health problems.
The fix to this problem, is to provide a semi optimal problem. In case
there is full mesh connectivity between all nodes, the change will
provide the correct answer which means full connectivity.
In case that there are many possible full mesh connectivity groups, it
might not find the optimal one  (although in the tests that were run the
previous algorithm and the current one produce same results).
/cc @filanov 
/cc @ …
> MGMT-11542: Fix connectivity check running forever on large cluster

- deploy/operator/gather.sh
This PR changes the way we collect ZTP logs to be more graceful. This is
so that we try to lazily collect as much as possible instead of failing
in the first unsuccessful "oc get".
/cc @osherdp
> NO-ISSUE: CI to be more graceful with ZTP log

- Dockerfile.assisted-service-build
This PR removes COPY . . instruction in skipper's dockerfile
Skipper mounts the current directory so it's not needed for local development.
CI needs have been addressed in https://github.com/openshift/release/pull/31076
This way we won't need to rebuild the image everytime and it will be slightly lighter
Tested through https://github.com/openshift/release/pull/30780
/cc @osherdp 
/cc @omertuc  …
> MGMT-11507: remove COPY . . instruction from skipper Dockerfile

- internal/bminventory/inventory_test.go
> MGMT-11550: Remove unit test duplicates - Update Network

- docs/user-guide/network-configuration/static-configuration.md
> NO-ISSUE: Static net config disclaimer

- docs/user-guide/network-configuration/static-configuration.md
> NO-ISSUE: Clarify MAC interface mapping for static nmstate

- docs/hive-integration/README.md
-->
/cc @avishayt 
/cc @filanov 
> NO-ISSUE: updated the converged flow docs

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/host/hostcommands/api_vip_connectivity_check_cmd.go
- internal/host/hostutil/host_utils.go
- internal/host/hostutil/host_utils_test.go
Contributes-to: [MGMTBUGSM-525](https://issues.redhat.com//browse/MGMTBUGSM-525)
> Bug-2118970: Create an utility GetIgnitionEndpoint function

- docs/enhancements/day2-master.md
> MGMT-11121: Add enhancement document for day2 master

- Dockerfile.assisted-service
A fix for https://github.com/nmstate/nmstate/issues/1914 (needed for MGMT-8568)
got pushed to a CentOS 9 RPM, which also brings a more recent version of nmstate.
This is a good incentive to move to CentOS 9 stream - so we can get
the nmstate-devel C libs that include the generate config command.
/cc @
/cc @
> MGMT-10866: Update assisted container to CentOS 9

- dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Added following panel:
This stacks all errors, so by hovering with the mouse we can see what component returned error (we also show retries from OCM gateway).
By checking this, we can infer what component/link failed.
Big thanks to @jhernand to help me understand how components are interconnected and their metrics.
/cc @jhernand 
/cc @gamli75 
> MGMT-11711: add dashboard for 5xx errors

- pkg/validations/validations.go
- pkg/validations/validations_test.go
- subsystem/cluster_test.go
Enable top level domain DNS name to be used for support of local
dns servers.
/cc @
/cc @
> MGMT-11182: Allow base level domain

- dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Due to C&P error we did not copy the multiplier for retries (as it is measured as retries/s), so it doesn't align with rest of measurements.
This PR fixes the above mentioned issue.
/cc @jhernand 
> MGMT-11711: align retries units with rest of measuramentes

- dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Ratio was wrong, being most likely copy&pasted from CPU.
it has been now fixed.
/cc @
> NO-ISSUE: fix resource ratio for memory usage

- dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Related to https://github.com/openshift/assisted-service/pull/4316/files , we forgot to check if limits had the same problem, and indeed it had it.
/cc @
> NO-ISSUE: fix ratio for memory limit in grafana dashboard

- docs/hive-integration/README.md
- docs/hive-integration/crds/agentClusterInstall.yaml
- docs/hive-integration/platform-selection.md
Add k8s API platform support to upstream docs
/cc @filanov 
> MGMT-11523: Add k8s API platform support to upstream docs

- hack/setup_env.sh
subsystem job started failing with the following message:
```
not enough arguments in call to ignition.New
have ([]byte, []byte, string, string, string, string, string,
string, string, string, string)
want ([]byte, []byte, string, string, string, string, string,
string, string, string, string, string)
```
For example:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/4277/pull-ci-openshift-assisted-service-master-edge-subsystem-aws/1563770339555545088
It turns out it removes some packages, making unnecessary changes to
``go.mod``.
/cc @eranco74 
/cc @filanov  …
> Bump mockgen to prevent dependencies removal

- cmd/main.go
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/inventory_v2_handlers.go
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_reclaimer.go
- internal/controller/controllers/agent_reclaimer_test.go
- internal/controller/controllers/infraenv_controller.go
- internal/controller/controllers/infraenv_controller_test.go
- internal/gencrypto/token.go
- internal/gencrypto/token_test.go
- internal/host/hostcommands/download_boot_artifacts_cmd.go
- internal/host/hostcommands/download_boot_artifacts_cmd_test.go
- internal/host/hostcommands/instruction_manager.go
- internal/host/hostcommands/instruction_manager_test.go
- internal/host/hostcommands/reboot_for_reclaim_cmd.go
- internal/host/hostcommands/reboot_for_reclaim_cmd_test.go
- internal/imageservice/url_test.go
- internal/imageservice/urls.go
- internal/versions/mock_versions.go
- internal/versions/versions.go
- internal/versions/versions_test.go
[MGMT-11549](https://issues.redhat.com/browse/MGMT-11549)
Sends the correct reclaim steps (either download boot
artifacts or reboot) to an agent when the host is in
reclaiming or reclaiming reboot.
/cc @carbonin 
/cc @filanov 
> MGMT-11549: Send reclaim steps to agent

- deploy/operator/setup_hive.sh
> NO-ISSUE: Specify Hive channel explicitly

- docs/user-guide/install-customization.md
> Fix wrong var name in "Add additionalTrustbundle in install-config"

- cmd/agentbasedinstaller/register.go
Agent Installer: When creating DHCP only cluster with agent config ( i.e. only RendezvousIP), do not require any networkConfig to be provided.
/cc @rwsu 
/cc @lranjbar 
/cc @bfournie
> OCPBUGSM-47740: No networkconfig needed with DHCP agent config

- subsystem/kubeapi_test.go
This commit extends subsystem test to ensure that if for a specific OCP version there is single- and multi-arch release payload, we are never accidentally picking the multi-arch unless requested.
> MGMT-8890: Add subsystem test for overlapping multiarch releases

- Dockerfile.assisted-service
- Dockerfile.assisted-service-build
- go.mod
- go.sum
- vendor/github.com/nmstate/nmstate/rust/src/go/nmstate/Makefile
- vendor/modules.txt
> MGMT-11936: Use NMState Go binding with CentOS8 Stream

- internal/bminventory/inventory_test.go
- internal/installcfg/builder/builder.go
- internal/installcfg/builder/builder_test.go
- internal/installcfg/installcfg.go
- internal/provider/baremetal/base.go
- internal/provider/none/base.go
- internal/provider/none/consts.go
- internal/provider/none/ignition.go
- internal/provider/none/installConfig.go
- internal/provider/none/inventory.go
- internal/provider/registry/registry.go
- internal/provider/vsphere/installConfig.go
- Separate none platform install-config from baremetal.
- Add support for platforms alongside enabled user-managed-networking
/cc @tsorya 
/cc @gamli75 
/cc @vrutkovs
> MGMT-10817: Fix install-config on vsphere platform

- deploy/operator/setup_hive.sh
> NO-ISSUE: Specify Hive channel explicitly for RHACM 2.5

- internal/ignition/ignition.go
- internal/oc/release.go
> NO-ISSUE: Fix trivial log formatting issues

- deploy/podman/README.md
- deploy/podman/configmap_tls.yml
- deploy/podman/configmap_tls_certs.yml
- deploy/podman/pod_tls.yml
/cc @filanov 
/cc @jkilzi 
/cc @mhrivnak 
/cc @avishayt 
/cc @carbonin 
/cc @vrutkovs 
/cc @oourfali
> MGMT-11590: Documentation Podman deployment with TLS

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/host/hostcommands/api_vip_connectivity_check_cmd.go
- internal/host/hostutil/host_utils.go
- internal/host/hostutil/host_utils_test.go
This is a manual cherry-pick of #4274 and #4289.
> MGMTBUGSM-537: Create an utility GetIgnitionEndpoint function

- OWNERS_ALIASES
> NO-ISSUE: Remove michaellevy101 from OWNERS

- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/network/machine_network_cidr_test.go
- internal/network/manifests_generator.go
- internal/network/manifests_generator_test.go
- internal/network/mock_manifests_generator.go
We want to be able to set ip for kubelet that will match machine cidr that we set for cluster. OVN will still run with default route one but in sno case it doesn't influence cluster
> Bug 2082979: Add node ip hint manifest for sno.

- cmd/main.go
This PR can potentially reduce 10x the size of the payload hence the speed of transfer.
It would impact the most biggest requests, but it will improve all requests to the API if performed with compression.
- [] None
Deployed the image from the branch in integration, and tested requests against it.
It returned compressed payload reducing the transfer size by 10 times.
If we perform the same tests against the current integration, the response body is unchanged.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelin …
> NO-ISSUE: add compression handler to http server

- Dockerfile.assisted-service-build
Reduce the final size of assisted-service-build image from 3.5GB to
2.8GB.
> NO-ISSUE: Reduce assisted-service-build image size

- dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Currently network transfer widget are showing a ever-increasing line (showing total).
We add rate so we can show how it changes over time. This would help us measuring the impact that compression will have on this metric
> NO-ISSUE: fix network transfer widget in grafana dashboard

- internal/infraenv/infraenv_test.go
on a fast machine there is chance to get a case where infra env is created at the same time that the GC function try to delete it. It can cause a case where the infra env is not deleted and the tests fails. Adding several seconds to the GC function will make sure that the interval will see the infra-env as old
> MGMT-12117: fix flaky infra-env UT

- internal/ignition/ignition.go
- internal/ignition/ignition_test.go
> MGMT-12074: Add unitests for bootstrap kubelet ip set

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- restapi/embedded_spec.go
- swagger.yaml
> MGMT-11293: Added default network type setting during registration

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
Currently we can't install sno cluster as ai is searching for x86 image as it thinks that sno is baremetal platform. In master it was fixed by setting platform to None for SNO but this fix is too big and all we need is not to allow overriding image for sno installation.
> Bug 2131023: Allow arm64 sno installation

- internal/host/host.go
> MGMTBUGSM-529: fix error msg in update disk path scenario

- internal/controller/controllers/infraenv_controller.go
- internal/controller/controllers/infraenv_controller_test.go
- subsystem/kubeapi_test.go
Previously only the ISO URL was getting updated when the image content changed. This will be a problem when assisted service is configured to boot machines through ironic using the initrd. In this case when something is changed in the infraenv that should change the content of the initrd the infraenv, and thus, the preprovisioning image were not being updated.
With this change the infraenv controller will recreate the token on the initrd URL whenever the ISO URL changes. This will force ironic to redownload the image and cause the machines to reboot, applying the changes.
https://issues.redhat.com/browse/MGMT-8864
Subsystem tests …
> MGMT-12217: Update infraEnv initrd URL when image content is updated

- tools/pvc_size_utils.py
Users have encountered the following stack trace during CI runs:
```
[INFO] 2022-10-03 00:49:14,276 - deploy_postgres - Deploying /home/assisted/assisted-service/build/ocp-edge-qe/postgres-deployment.yaml", "deployment.apps/postgres unchanged", "service/postgres unchanged
[INFO] 2022-10-03 00:49:14,798 - deploy_postgres - Updating pvc size for postgres-pv-claim
File \"./tools/deploy_postgres.py\", line 97, in <module>
main()", "  File \"./tools/deploy_postgres.py\", line 19, in main
deploy_postgres_storage(deploy_options)
File \"./tools/deploy_postgres.py\", line 78, in deploy_postgres_storage
docs=docs", "  File \"/home/assisted/assisted-service/tools/pvc_size_utils.py\", line 69, in update_size_in_yaml_docs
size = determine_which_size_to_deploy(req, …
```
> NO-ISSUE: Change `get_current_size_if_exist` to inspect PVC `.spec` and not `.status`

- docs/dev/feature-per-customer.md
> MGMT-10557: Docs for per-customer feature enablement

- docs/user-guide/day2-master/411-healthy.md
- docs/user-guide/day2-master/411-unhealthy.md
- docs/user-guide/day2-master/README.md
- docs/user-guide/day2-master/link-machine-and-node.sh
Contributes-to: [MGMT-8578](https://issues.redhat.com//browse/MGMT-8578)
Closes: [MGMT-11945](https://issues.redhat.com//browse/MGMT-11945)
> MGMT-8578: Describe process for day2 master for OCP 4.11

- deploy/operator/setup_lso.sh
> NO-ISSUE: Use 4.11 index for LSO installation in 4.12

- deploy/operator/gather.sh
- deploy/operator/setup_assisted_operator.sh
- deploy/operator/utils.sh
/cc @vrutkovs 
/test edge-e2e-ai-operator-ztp
> NO-ISSUE: In CI check status of Deployment and not Pod

- internal/host/host.go
- internal/host/host_test.go
[MGMT-11129](https://issues.redhat.com/browse/MGMT-11129)
Initially there wasn't a check to see if the host was attached to a cluster before setting the bootstrap host. In a scenario like late-binding, there could be hosts without a cluster, which would cause a panic.
This checks to make sure the cluster is not nil before executing the logic to set a bootstrap host.
Refactored logic based on previous PR https://github.com/openshift/assisted-service/pull/4118#discussion_r918931182
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guidelin …
> MGMT-11129: Only set bootstrap host when it's attached to a cluster

- docs/user-guide/README.md
- docs/user-guide/cloud-with-mirror.md
Documentation on how to use the SaaS version of the Assisted Installer with an internal mirror registry. As called out in the documentation, it is not possible to be 100% reliant on the internal mirror, but the end resulting cluster will use an internal mirror to pull all images. This documentation is based on a request from @romfreiman 
Signed-off-by: Mark D <xphyr@users.noreply.github.com>
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING. …
> Document using SaaS with internal registry

- deploy/postgres/postgres-deployment.yaml
> NO-ISSUE: unlimit postgres CPU due to spiky nature of tests

- internal/controller/controllers/preprovisioningimage_controller.go
- internal/controller/controllers/preprovisioningimage_controller_test.go
- subsystem/kubeapi_test.go
Previously the preprovisioning controller was unconditionally looking
for the created time in the infraEnv status. This would cause the entire
assisted-service container to crash if the created time was not set.
This is only set after the infraEnv controller sets the image URLs and
may not be set for some time if there are, for example, format errors in
nmstate config associated with the infraEnv. Once the container starts
crashing it is unlikely to recover even if the underlying issues are
resolved as the preprovisioning controller seemed to consistently reconcile
before the infraenv controller got a chance to set the created time.
This patch checks that the image created time is set and sets a
condition if not. The preprovisionsing image controller is watching for
infraenv events so it …
> MGMT-12188: Fix panic when infraEnv image has not been created

- docs/dev/feature-per-customer.md
> NO-ISSUE: Update doc for per-customer feature enablement

- OWNERS_ALIASES
> NO-ISSUE: Add Javi as reviewer

- deploy/operator/setup_assisted_operator.sh
- deploy/operator/utils.sh
Ensure `wait_for _deployment` references a variable `timeout` set in
its context.
> NO-ISSUE: Ensure timeout is set in wait_for_deployment

- pkg/validations/validations_test.go
/cc @paul-maidment 
/cc @nmagnezi
> MGMT-11878: Extend URL validator to check for trailing whitespaces

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
> MGMT-12067: Support discovery kernel arguments during infra-env registration and updates

- internal/controller/controllers/bmh_agent_controller_test.go
- internal/host/hostutil/host_utils.go
We should reject disks that are *smaller* than the minimum size.
> Bug 2131017: Fix MinSizeGigabytes root device hint

- internal/controller/controllers/agentserviceconfig_controller.go
- internal/controller/controllers/hypershiftagentserviceconfig_controller.go
- internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
Extracted the following from ASC reconciler for using in HASC:
* Finalizers
* image-service StatefulSet
* Storage validation
* IPXE HTTPRoute
>     MGMT-12214: extract reconciler logic for using HASC

- docs/ocm-integration.md
This patch adds a section to the `ocm-integration.md` document explaining how to add capabilities to the OCM accounts management service.
> NO-ISSUE: Document how to add OCM capabilities

- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
> MGMT-12056: changing default network type kube api

- docs/enhancements/add-kernel-parameters.md
> MGMT-12083: Create enhancement document for discovery kernel parameters

- dashboards/grafana-dashboard-assisted-installer-logs.yaml
Adding dashboard to quickly access production logs through grafana:
Created from staging, copied JSON model
Unique name:
```$ grep -snr assisted-installer-logs dashboards 
dashboards/grafana-dashboard-assisted-installer-logs.yaml:4:  name: assisted-installer-logs
```
/cc @carbonin @nmagnezi 
> NO-ISSUE: add logs dashboard

- api/vendor/github.com/openshift/assisted-service/models/feature_support_level.go
- api/vendor/github.com/openshift/assisted-service/models/host.go
- internal/featuresupport/support_levels_list.go
- models/feature_support_level.go
- models/host.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/feature_support_level.go
- vendor/github.com/openshift/assisted-service/models/host.go
There are a couple of problems with current version of swagger.yaml file:
* We're sometimes using ``format: datetime`` instead of ``format: date-time``, while datetime isn't a built-in format. E.g.: https://github.com/openshift/assisted-service/blob/f267d0a7caa5a3f1e3f981dab345e1408845decf/swagger.yaml#L3973
* We're not annotating optional fields as nullable. E.g.: https://github.com/openshift/assisted-service/blob/f267d0a7caa5a3f1e3f981dab345e1408845decf/swagger.yaml#L4645-L4651
* required fields list is not under properties: https://github.com/openshift/assisted-service/blob/cd50460292ee175db28ec18f20f651140a59a5ec/swagger.yaml#L3578-L3584
* It is probably redundant to specify both ``type: object`` and referencing it to a type definition: …
> MGMT-12462: Fix assisted-service swagger file

- internal/bminventory/inventory_test.go
- internal/bminventory/inventory_v2_handlers.go
> MGMT-12053: Add support for additional kernel arguments when serving iPXE script

- internal/host/hostcommands/free_addresses_cmd.go
- internal/host/hostcommands/free_addresses_cmd_test.go
cherry-pick of https://github.com/openshift/assisted-service/pull/4601
> [cloud_hotfix_releases] MGMT-12528 - Disable network scanning for very large IPv4 subnets

- dashboards/grafana-dashboard-assisted-installer-logs.yaml
Adding additional panels to quickly glance over different loglevels.
- [] None
> NO-ISSUE: add warning and info panel to log dashboard

- internal/host/hostcommands/free_addresses_cmd.go
- internal/host/hostcommands/free_addresses_cmd_test.go
In [MGMT-1219](https://issues.redhat.com//browse/MGMT-1219) it was decided that scanning would only be done for up to
8000 addresses. The issue with that is that it would make the service
think that the other (n - 8000) addresses in the subnet were in use,
because they were not reported as "free addresses", because they were
never scanned.
This commit makes it so that the service will not even request scanning
for subnets larger than 4096.
When there's no free-addresses agent response for a particular subnet,
the validation that makes sure the VIP doesn't lend on a used address is
simply skipped, so not requesting scanning is the same as basically
disabling the validation for that subnet. …
> MGMT-12528 - Disable network scanning for very large IPv4 subnets

- api/vendor/github.com/openshift/assisted-service/models/infra_env.go
- api/vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
- api/vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
- docs/enhancements/add-kernel-parameters.md
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/inventory_v2_handlers.go
- internal/migrations/20221110174000_rename_kernel_arguments.go
- internal/migrations/20221110174000_rename_kernel_arguments_test.go
- internal/migrations/migrations.go
- models/infra_env.go
- models/infra_env_create_params.go
- models/infra_env_update_params.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/infra_env.go
- vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
- vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
> MGMT-12545: Rename "discovery kernel arguments" to "kernel arguments" in infra-env context

- Dockerfile.assisted-service-debug
- hack/setup_env.sh
Backports https://github.com/openshift/assisted-service/pull/4538.
It seems like a very probably cause of the failure [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/4609/pull-ci-openshift-assisted-service-release-ocm-2.6-subsystem-aws/1591782050333986816):
```
vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/imagecontentpolicy.go:25:50: undefined: "github.com/openshift/api/config/v1".ImageContentPolicy
vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/imagecontentpolicy.go:26:50: undefined: "github.com/openshift/api/config/v1".ImageContentPolicy
...
``` …
> [release-ocm-2.6] MGMT-11799: change all 'go get' commands

- api/vendor/github.com/openshift/assisted-service/models/os_image.go
- models/os_image.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/os_image.go
This is the version of the os image, it doesn't necessarily have anything to do with the version of the cluster that will eventually be installed.
> Describe openshift_version in os_image better

- dashboards/grafana-dashboard-assisted-installer-logs.yaml
Adding logs panel for stage in grafana
> NO-ISSUE: add stage logs to grafana

- internal/bminventory/inventory.go
Daedlock occurs when there are 2 resources (a,b)  to be locked by 2 users.  If user 1 locks resource "a", then user 2 locks resource "b", then user 1 tries to lock resource "b" and user 2 tries to lock resource "a". This may occure between 2 different database transactions.  In case of database deadlock, the database engine selects a victim and terminates its transaction.
One of the ways to avoid deadlock is to keep always the same locking order.  This is what was done here.  The 2 resources are cluster and host.  The change verifies that in case cluster and host need to be locked in a transaction, the cluster is locked before the host. …
> MGMT-12555: Try avoid deadlocks when updating cluster or host

- internal/cluster/cluster_test.go
Currently some of the mock controllers in the cluster tests aren't finished. As a result some of the expectations aren't verified, and some of the tests are incorrect. With the introduction of Ginkgo 2 the controllers will be automatically finished, and that will make these tests fail. In order to reduce the size of that migration to Gingo 2 this patch fixes those tests and changes them to explicitly finish the mock controllers. …
> NO-ISSUE: Explicitly finish mock controller in cluster tests

- internal/common/common.go
- internal/hardware/validator.go
- internal/hardware/validator_test.go
- subsystem/cluster_test.go
[MGMT-12500](https://issues.redhat.com//browse/MGMT-12500): DPU cpu arch can be aarch64 and not arm64, adding aarch64 to allowed values
> MGMT-12500: DPU cpu arch can be aarch64 and not arm64, adding aarch64 to allowed values

- deploy/operator/gather.sh
- deploy/operator/hypershift/deploy_hypershift_cluster.sh
- deploy/operator/hypershift/playbooks/bmh-playbook.yaml
- deploy/operator/hypershift/playbooks/hasc-playbook.yaml
- deploy/operator/hypershift/playbooks/spoke-crs-playbook.yaml
- deploy/operator/hypershift/playbooks/templates/baremetalHost.j2
- deploy/operator/hypershift/playbooks/templates/hasc.j2
- internal/controller/controllers/agentserviceconfig_controller.go
Added deploy_hypershift_cluster.sh script for deploying a spoke cluster using an hypershift zero-node cluster
(see enhancement: https://github.com/openshift/assisted-service/blob/master/docs/enhancements/ai-on-zero-worker-hypershift.md).
> MGMT-12460: added deploy_hypershift_cluster script

- internal/host/host_test.go
Currently some of the mock controllers in the host tests aren't finished. As a result some of the expectations aren't verified, and some of the tests are incorrect. With the introduction of Ginkgo 2 the controllers will be automatically finished, and that will make these tests fail. In order to reduce the size of that migration to Gingo 2 this patch fixes those tests and changes them to explicitly finish the mock controllers. …
> NO-ISSUE: Explicitly finish mock controller in host tests

- internal/bminventory/inventory_test.go
> MGMT-12605: Remove duplicated tests: Dual-stack UpdateCluster

- api/v1beta1/agentserviceconfig_types.go
- internal/controller/controllers/agentserviceconfig_controller.go
- internal/controller/controllers/hypershiftagentserviceconfig_controller.go
- internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
- vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
Webhook configuration consists of an admission server, the validation and mutation hook configurations, and the routing between the API server and the admission service.
To fulfill this setup in a hypershift environment we need to:
1. Deploy a service that exposes the webhook admission server on L0
2. Define the admission pod on L0
3. Define a headless service with an endpoint that points to the L0 service's ClusterIP …
> MGMT-11740: WebHook configuration in HASC

- deploy/operator/mirror_utils.sh
- deploy/operator/setup_lso.sh
Cherry-picks: #4476
Cherry-picks: #4478
/cc @vrutkovs
> NO-ISSUE: In 4.12 use 4.11 LSO and legacy security context

- dashboards/grafana-dashboard-assisted-installer-logs.yaml
- internal/host/host_test.go
Take advantage of loki datasource to show logs (only available in stage at the moment):
* deduplicate log lines by signature
* filter single dashboard by log level
* filter log panel by query on log line 
> NO-ISSUE: add loki datasource for stage logs

- internal/controller/controllers/infraenv_controller.go
- internal/controller/controllers/infraenv_controller_test.go
- subsystem/kubeapi_test.go
> MGMT-12332: Kube API subsystem tests for kernel arguments

- internal/hardware/validator.go
- internal/hardware/validator_test.go
> MGMT-12686: Allow installing on FC disks

- docs/user-guide/hypershift-agent-service-config.md
Add user facing documnetation on how to install hypershift and HASC CR
> MGMT-11813: how to install HASC doc

- api/vendor/github.com/openshift/assisted-service/models/cluster.go
- api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
- api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
- models/cluster.go
- models/cluster_create_params.go
- models/v2_cluster_update_params.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/cluster.go
- vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
- vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Those will be replaced by plural API and Ingress VIPs
> MGMT-12678: Deprecate API and Ingress VIP (Singular)

- docs/dev/olm-operator-plugins.md
While studying the OLM operator plugin API I stumbled upon some relevant details of the interface that weren't documented, so I thought it could have been useful to report them for the benefits of the other plugin authors. Thanks @avishayt and @gamli75 for the clarifications provided.
> Small doc addition for OLM operator plugins

- openshift/template.yaml
This PR will allow us to produce access logs without changing the service's code.
It will produce lines similar to:
```
{"response_flags":"-","user_agent":"curl/7.61.1","authority":"localhost:8090","x_forwarded_for":"-","protocol":"HTTP/1.1","path":"/api/assisted-install/v2/clusters/foobar","upstream_host":"127.0.0.1:8090","route_name":"-","response_code":"401","x_agent_name":"-"}
```
Run in integration environment. …
> MGMT-12684 add envoy as sidecar to produce access log

- internal/bminventory/inventory.go
> MGMT-12723: Fix log formatting in inventory.go

- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
Prior to this change if the agent_controller successfully got the clusterdeployment it wouldn't use it for getting the AdminKubeConfigSecretName, resulting an attempt to fetch the secret by the fallback template name that didn't exist. This commit fix the bug by calling getClusterDeploymentAdminKubeConfigSecretName if we successfully got the clusterdeployment or not
- Should this PR be tested in a specific environment? ACM-2.6
-->
https://issues.redhat.com/browse/MGMT-12689
- Should this PR …
> MGMT-12689: Day-2 agent stuck with status_info rebooting although the node is already part of the cluster

- docs/enhancements/platform-integration.md
This enhancement describes existing "Integrate with vSphere/BM" feature and describes an updated proposal to extend the API to support more providers
/cc @
/cc @
> MGMT-11265: add platform integration enhancement

- internal/host/hostcommands/instruction_manager.go
> MGMT-12795: Make agent to restart on upgrade (Temporary Patch)

- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
In day2 flow, when reconciling an agent the CSRs should be manually approved if not done by the cluster-machine-approver. As the automatic approval is done only when a BMH exists for an agent (and non-UMN), we should try to approve agents without associated BMHs.
Hence, approving CSRs for rebooting hosts when:
* Agent belongs to a none platform cluster
* No BMH exists for agent
> MGMT-11386: approve day2 CSRs for an agent without BMH

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
Hypershift spoke clusters store root CA in a different location,
BMH Agent controller should fall back to a different location when
`root-ca` at `default` is not available
> MGMT-12749: BMH: add fallback location for spoke's root CA

- internal/bminventory/inventory.go
- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/common.go
- internal/cluster/transition.go
- internal/cluster/transition_test.go
- internal/cluster/validations/validations.go
- internal/controller/controllers/clusterdeployments_controller.go
- internal/network/utils.go
- subsystem/cluster_test.go
Contributes-to: [MGMT-12797](https://issues.redhat.com//browse/MGMT-12797)
/cc @nmagnezi
> MGMT-12797: Missing dual-stack VIP values in SNO cluster

- docs/enhancements/dual-stack-vips.md
This is an enhancement for dual-stack VIPs. It describes the proposed
design of the integration with the feature that has already a stable API
in the upstream OCP.
Closes: [MGMT-11525](https://issues.redhat.com//browse/MGMT-11525)
/cc @mhrivnak 
/cc @avishayt 
/cc @filanov 
/cc @carbonin
> MGMT-9915: Enhancement for dual-stack VIPs

- api/vendor/github.com/openshift/assisted-service/models/cluster.go
- api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
- internal/cluster/mock_cluster_api.go
- internal/common/common_test.go
- internal/host/refresh_status_preprocessor.go
- internal/host/statemachine.go
- internal/host/transition_test.go
- internal/host/validation_id.go
- internal/host/validations_test.go
- internal/host/validator.go
- models/cluster.go
- models/host_validation_id.go
- restapi/embedded_spec.go
- subsystem/kubeapi_test.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/cluster.go
- vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Presently we do not have a way to report on IP collissions.
In conjunction with the changes in https://github.com/openshift/assisted-installer-agent/pull/433 this commit will add IP collission detection to assisted service.
- [] None
I will make sure to deploy assisted-installer in beaker and to use this version of the agent https://github.com/openshift/assisted-installer-agent/pull/433
I will then deliberately create a cluster that has IP collisions and check to see how these are reported.
- x] Title and description added to both, commit and PR. …
> MGMT-11970: Add a validation to check for IP collissions.

- docs/hive-integration/crds/agentClusterInstall-dualstack-vips-SNO.yaml
- docs/hive-integration/crds/agentClusterInstall-dualstack-vips.yaml
Implements: #4245 
/cc @carbonin
> MGMT-9915: Prepare sample CRs for dual-stack VIPs

- internal/controller/controllers/bmh_agent_controller.go
- internal/host/monitor.go
- pkg/conversions/conversions.go
Don't put GiB in the MiB field.
- [x Bug fix
> NO-ISSUE: Set the correct RAM size in BMH HardwareDetails

- internal/controller/controllers/preprovisioningimage_controller.go
- internal/controller/controllers/preprovisioningimage_controller_test.go
This will allow the kernel parameters set on the infra-env to also apply to discovery when using ipxe boot with ZTP converged flow.
Resolves https://issues.redhat.com/browse/ACM-2270
Deployed a devscripts environment with BMHs configured to boot using iPXE.
Created an infra-env with:
```
kernelArguments:
- operation: append
value: rd.net.timeout.carrier=60
```
Observed that the preprovisioningimage had the expected `extraKernelParams` value:
```
extraKernelParams: coreos.live.rootfs_url=https://assisted-image-service-assisted-installer.apps.ostest.test.metalkube.org/boot-artifacts/rootfs?arch=x86_64&version=4.12
rd.net.timeout.carrier=60
format: initrd
```
cc @eranco74 @ori-amizur 
- Is there a bug required (and …
> Set infra-env kernel params on preprovisioning image

- internal/operators/lvm/config.go
- internal/operators/lvm/lvm_operator.go
- internal/operators/lvm/lvm_operator_test.go
removing confusing text `require minimum size 0GB` from lvm requirement.
Signed-off-by: subhamkrai <srai@redhat.com>
> MGMT-12433: remove text minimum Size 0GB in lvm

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/operators/manager.go
- internal/operators/manager_test.go
setting lvmo on non-SNO cluster should return bad request
Signed-off-by: subhamkrai <srai@redhat.com>
> MGMT-12591:setting lvmo on non-SNO cluster should return bad request

- docs/enhancements/short-url-enhancement.md
> MGMT-12743: adds enhancement proposal for shorter image URLs

- subsystem/kubeapi_test.go
> NO-ISSUE: disable invalid nmstate test

- pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
- pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go
This reverts commit 84a6437646af566564cfd3d15123a8c92eba34d7.
Reverting the PR in order to submit a fix where we allow to change only the controlPlane fields in the ACI instead of all the fields (post install). It will be safer this way.
> Revert "MGMT-12794: allow to edit ACI post install (#4831)"

- internal/cluster/cluster.go
- internal/cluster/common.go
- internal/cluster/common_test.go
Based on code review comments:
1. Change the name of the function to UpdateMachineNetwork, which is a more descriptive name
2. Change the input variables in the same way
3. Use the transaction variable inside the transaction block to ensure atomicity
> NO-ISSUE: improve UpdateMachineCidr

- internal/bminventory/inventory_test.go
- internal/provider/common.go
[MGMT-13080](https://issues.redhat.com//browse/MGMT-13080): [Nutanix] - UMN and machine_network = [] - bootstrap is in insufficient
This PR is blocking UMN for nutanix platform
> MGMT-13080: [Nutanix] - UMN and machine_network = [] - bootstrap is in insufficient

- internal/constants/scripts.go
In situations where users are struggling to determine why their network configuration is not taking effect it would be helpful to log a bit more verbosely from the service that sets up the network config files. Specifically if a host does not match any of the provided mappings we currently write "None of host directories are a match for the current host" which is not particularly helpful. It should at least say something about possible mac address mismatches. We probably could also find a few more places to log something useful.
This PR attempts to address these concerns by adding more verbose logging.
The extra verbose logging has been manually tested by running this version of the service in a cluster and then booting a node from an ISO generated by an infraenv from the cluster.
General …
> MGMT-12273: Updated logging in PreNetworkConfig script.

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/validations/validations.go
See original PR: https://github.com/openshift/assisted-service/pull/4656
> MGMT-13058: backport vsphere validation in sno to 2.6

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
Throw Bad Request if nutanix platform cluster is requested with version less than 4.11
> MGMT-13906: inventory: limit allowed Nutanix versions in API

- docs/user-guide/install-customization.md
As part of [Assisted Installer Customization](https://github.com/openshift/assisted-service/blob/master/docs/user-guide/install-customization.md), added documentation for configuring nodes storage using a MachineConfig manifest. The doc includes a specific example for adding a partition to master nodes by setting it on sda device in the ignition config.
> MGMT-7878: storage config doc using MachineConfig manifest

- internal/network/manifests_generator.go
- internal/network/manifests_generator_test.go
[MGMT-13240](https://issues.redhat.com//browse/MGMT-13240): Create ip hint file in sno installation even if there is
only one ip on the host.
> MGMT-13240: Create ip hint file in sno installation even if there is     only one ip on the host.

- api/vendor/github.com/openshift/assisted-service/models/completion_params.go
- docs/events.yaml
- internal/bminventory/inventory_test.go
- internal/bminventory/inventory_v2_handlers.go
- internal/common/events/events.go
- models/completion_params.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/completion_params.go
send an event with the list of failing cluster operators.
The controller is reposnsible for filling out the data and if it exist the service processes it into a message.
> MGMT-10785: report failing cluster operators

- internal/hardware/validator.go
- internal/hardware/validator_test.go
> Disable installation on FC disks

- internal/bminventory/inventory_test.go
- internal/operators/lvm/config.go
- internal/operators/lvm/lvm_operator.go
- internal/operators/lvm/lvm_operator_test.go
- internal/operators/lvm/manifest.go
- internal/operators/manager.go
Signed-off-by: subhamkrai <srai@redhat.com>
> MGMT-13305: update the min version for lvm

- internal/operators/manager.go
Signed-off-by: subhamkrai <srai@redhat.com>
> remove testing log message

- pkg/stream/event_stream.go
We should not block when sending kafka messages for events, as we do not need guarantee of delivery.
> MGMT-13432: fire and forget kafka messages for event notification

- openshift/template.yaml
Explicitly declaring envoy-sidecar timeout, and parametrizing the value.
This way we can increase/decrease at will by just changing its value in the deployment and avoid the lengthy PR-merging process in case we need to tweak it.
> NO-ISSUE: explicitly declare timeout

- openshift/template.yaml
Backports https://github.com/openshift/assisted-service/pull/4916
/cc @jhernand
> [cloud_hotfix_releases] MGMT-12697: Add ENABLE_REJECT_UNKNOWN_FIELDS to SaaS template

- internal/events/event.go
This event was not correctly labeled, we are renaming it in this PR
> NO-ISSUE: rename event that was erroneusly named as InfraEnv

- docs/enhancements/on-prem-data-collection.md
[MGMT-12193](https://issues.redhat.com/browse/MGMT-12193)
Epic: [MGMT-10308](https://issues.redhat.com/browse/MGMT-10308)
> MGMT-12193: Add enhancement doc for collecting on-prem data

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
As a follow-up to https://github.com/openshift/assisted-service/pull/4894, added the ignition size validation also to RegisterInfraEnv and UpdateInfraEnv APIs.
These APIs were missed in the aforementioned PR. Also, removed the validation in v2UpdateHostIgnition API which is redundant as we don't embed the host ignition in the ISO.
> MGMT-13008: ignition size validation on register infraenv

- openshift/template.yaml
This important field was forgotten :flushed: 
> NO-ISSUE: add method to access log

- cmd/main.go
- internal/bminventory/inventory.go
- internal/cluster/common.go
- internal/cluster/common_test.go
- internal/events/event.go
- internal/host/host.go
- internal/host/host_test.go
This PR will stream to the event stream model data instead of raw DB data:
* improves consistency of json keys (also reduce amount of work to do in the consumer: less fields to remove or to transform keys)
* makes clearer what the interface is between assisted-service and the consumer
> MGMT-13493: stream model data instead of DB data

- skipper.yaml
> NO-ISSUE: skipper error when podman is missing

- data/default_okd_os_images.json
- data/default_okd_release_images.json
- deploy/podman/okd-configmap.yml
Bump OKD configs to use 4.12 release. `OKD_RPMS` setting is no longer necessary as assisted-service now uses `okd-rpms` image from the release image
> OKD: update to OKD 4.12

- cmd/main.go
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/inventory_v2_handlers.go
- internal/cluster/auth.go
- internal/cluster/cluster.go
- internal/ignition/boot-reporter/assisted-boot-reporter.sh
- internal/ignition/dummy.go
- internal/ignition/ignition.go
- internal/ignition/ignition_test.go
- internal/ignition/mock_ignition.go
- pkg/generator/generator.go
Implements: https://github.com/openshift/assisted-service/pull/4444
> MGMT-12329: Implements assisted boot reporter and add to ignition

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/host/hostutil/test_utils.go
- internal/operators/cnv/cnv_operator.go
- internal/operators/cnv/cnv_operator_test.go
- internal/operators/lvm/config.go
- internal/operators/lvm/lvm_operator.go
- internal/operators/lvm/lvm_operator_test.go
- internal/operators/lvm/manifest.go
- internal/operators/manager.go
- internal/operators/manager_test.go
Backport of https://github.com/openshift/assisted-service/pull/4942
/cc @eliorerz
> MGMT-13305: Fix invalid lvms version installed on 4.11

- internal/bminventory/inventory.go
> NO-ISSUE: Add logs to getOLMOperators LVM flow

- deploy/operator/capi/deploy_capi_cluster.sh
Update the hypershift test to verify we can successfully delete the hosted cluster
- Should this PR be tested in a specific environment? operator workflow + hypershift + capi
-->
> Hypershift test delete

- docs/enhancements/template.md
> NO-ISSUE: Add scenarios to consider to enhancement template

- internal/network/manifests_generator.go
- internal/network/manifests_generator_test.go
MGMT-13471: SNO installation with OCP 4.13 lacks proper dnsmasq configuration
> MGMT-13471: SNO installation with OCP 4.13 lacks proper dnsmasq configuration

- docs/enhancements/support-node-labeling.md
> MGMT-13045: Enhancement document for node labeling

- internal/bminventory/inventory.go
Add logs to get supported platforms flow (on success and on failure) due to non reproducible  502 when requesting the cluster supported-platforms
> NO-ISSUE: Add logs to supported-platforms

- internal/ignition/ignition.go
- internal/ignition/ignition_test.go
The pointer ignition contains a link to pull the ignition associated with the MCP(i.e master/worker). If a worker node is associated with custom role which is associated with custom MCP, the node will reboot just to move to the custom MCP.  This reboot causes additional delay during the installation process which is undesirable. With this change, the pointer ignition is modified according to the custom MCP name.  Thus, no extra reboots will be performed by the node to move to the custom MCP.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-mess …
> MGMT-13620: Make worker to use custom MCP if it was set as part of the host DB record

- deploy/operator/README.md
- deploy/operator/libvirt_disks.sh
> NO-ISSUE: customize the image path for disk creation

- internal/network/manifests_generator.go
- internal/network/manifests_generator_test.go
Revert "[MGMT-13471](https://issues.redhat.com//browse/MGMT-13471): SNO installation with OCP 4.13 lacks proper dnsmasq configuration"
The change for dnsmasq was provided through MCO, no need to duplicate it in assisted
> Revert "MGMT-13471: SNO installation with OCP 4.13 lacks proper dnsmasq configuration

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/validations/validations.go
Block platform=nutanix when ARM64 CPU arch is set
> MGMT-13313: bminventory: throw Bad Request error on arm64 Nutanix clusters

- docs/enhancements/add-feature-support-by-generic-attributes.md
```
Error in user YAML: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1
```
/cc @osherdp
> Fix invalid character in feature-support enhancement

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
In order to allow for full node life-cycle management for spoke clusters this commit will delete the agent resource associated with a BMH when the BMH is deleted and the new annotation
`bmac.agent-install.openshift.io/full-management` has also been set on the BMH.
Resolves https://issues.redhat.com/browse/MGMT-13504
Test steps:
1. Annotate the BMH with `bmac.agent-install.openshift.io/full-management: "true"`
2. Check that the finalizer was added
3. Remove BMH
4. Validate agent was removed
Docs WIP
> Allow removing the agent when BMH is deleted

- openshift/template.yaml
To stop receiving unwanted logs from customers.
/cc @osherdp @tsorya 
> MGMT-13957: deny requests with query parameters matching node-boot. 

- openshift/template.yaml
[MGMT-12486](https://issues.redhat.com/browse/MGMT-12486)
Epic: https://issues.redhat.com/browse/MGMT-10308
The new environment variable for data collection needs to be included in the openshift/template.yaml file to be configurable.
/cc @osherdp @rccrdpccl
> MGMT-12486: Add ENABLE_DATA_COLLECTION environment variable to template.yaml

- openshift/template.yaml
[MGMT-14042](https://issues.redhat.com/browse/MGMT-14042)
To avoid extra configuration, have this environment variable disabled by default.
/cc @osherdp
> MGMT-14042: Disable data collection for SaaS by default

- data/default_okd_release_images.json
- deploy/podman/okd-configmap.yml
Bump OKD release to latest stable
> OKD: bump to latest stable release

- internal/controller/controllers/bmh_agent_controller.go
- Always use the passed logger
- Don't log entire objects in info messages
- Add agent fields
- Remove unnecessary agent/bmh name and namespaces in messages (use fields)
- Remove logger from functions that don't use it
> Cleanup BMAC logging

- docs/user-guide/support-level.md
> MGMT-14000: Document support-level new API

- README.md
This should have been removed in 78f640c3ba3792eca41150fba58a43890807ef52
> Remove README section about the assisted-service live iso

- internal/uploader/events_uploader.go
- internal/uploader/events_uploader_test.go
[MGMT-14073](https://issues.redhat.com/browse/MGMT-14073)
The cluster events uploader's debug logs were
not logging any level other than info since they
were not using the correct logger. This makes
it so they use the logger attached to the event
upload client.
> MGMT-14073: Fix logging for event uploader

- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agentserviceconfig_controller.go
- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/common.go
- internal/controller/controllers/hypershiftagentserviceconfig_controller.go
- internal/controller/controllers/preprovisioningimage_controller.go
This allows us to get rid of a bunch of nil checks by handling this in one place.
> Add a function for setting annotations

- internal/network/utils.go
> NO-ISSUE: Wrap VIP update in the DB with transaction

- internal/cluster/common.go
> NO-ISSUE: Make DB transaction terminate function only when error

- api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/featuresupport/architecture_support_level.go
- internal/featuresupport/architectures.go
- internal/featuresupport/common.go
- internal/featuresupport/feature_support_level.go
- internal/featuresupport/feature_support_test.go
- internal/featuresupport/features.go
- internal/provider/common.go
- models/feature_support_level_id.go
- restapi/embedded_spec.go
- subsystem/feature_support_levels_test.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
- Allow installing Power architecture with cluster managed networking
- Add minimal iso ID and allow to create cluster with Power architecture
/cc @eliorerz
> MGMT-14190: Allow installing Power architecture with CMN and MinimalISO

- api/vendor/github.com/openshift/assisted-service/models/infra_env.go
- api/vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
- models/infra_env.go
- models/infra_env_create_params.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/infra_env.go
- vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
Removing "multi" cpu architecture for infra envs
> MGMT-14161: removing "multi" cpu architecture for infra envs

- internal/host/host.go
- internal/host/host_test.go
- internal/host/hostutil/update_host.go
- internal/host/hostutil/update_host_test.go
- internal/host/mock_transition.go
- internal/host/statemachine.go
- internal/host/transition.go
> MGMT-12301: refactor the progress bar to use state machine

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
Remove unclear message and use the feature support validation message format
/cc @gamli75
> MGMT-14266: Fix unclear message when creating a P/Z cluster with OCP version 4.10

- internal/provider/common.go
Set UMN enabled for Power architecture
> MGMT-14239: Enable UMN as default for Power architecture (ppc64le)

- internal/events/event.go
- internal/events/event_test.go
Currently, while trying to fetch events using `cluster_id`, `host_ids` and `severities` we don't get severity filtered correctly because of the precedence of AND, OR in `SQL`.
We change the all the disjunctive conditions to the right order.
> MGMT-14317: Fix events filtering

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- subsystem/cluster_v2_test.go
Set Full ISO as default for s390x architecture
/cc @eliorerz
> MGMT-14298: Set full ISO as default for Z architecture

- docs/dev/testing.md
Force FF master to  `release-ocm-2.9`
/cc @osherdp
> NO-ISSUE: Fix grammar mistakes

- openshift/template.yaml
This change should allow nullable values for limits, potentially needed to reduce throttling.
> NO ISSUE: use literal for cpu limits, to enable nulliable value

- docs/enhancements/api-for-ignoring-validations.md
Ignoring a disk size validation will lead to a scenario where there are no eligible disks for installation. This is non trivial to "work around" so has been added to the known issues for now.
> MGMT-13955: Add known issue regarding ignoring disk size validations

- Makefile
> MGMT-14462: Allow to deploy assisted-service with all available images

- README.md
- deploy/podman/README.md
- docs/enhancements/platform-integration.md
- docs/user-guide/rest-api-getting-started.md
- tools/deploy_ui.py
The Phase 1/PSI deployment was failing due to the changes in the paths in the UI repository.
> NO-ISSUE: Fixes the UI deployment

- pkg/app/middleware.go
In order for the UI scripts to be able to access response headers, we need to expose them for CORS requests
> MGMT-14507: Exposing event headers for scripts

- go.mod
- go.sum
- vendor/github.com/moby/moby/pkg/ioutils/fswriters.go
- vendor/github.com/moby/moby/pkg/ioutils/temp_unix.go
- vendor/github.com/moby/moby/pkg/ioutils/temp_windows.go
- vendor/modules.txt
[MGMT-14226](https://issues.redhat.com/browse/MGMT-14226)
Upgrades go mod github.com/moby/moby to version
20.10.24 for CVEs in the issue.
> MGMT-14226: Upgrade moby to 20.10.24

- client/events/v2_list_events_responses.go
- internal/common/common.go
- internal/events/event.go
- internal/events/event_test.go
- internal/events/events_api.go
- restapi/embedded_spec.go
- restapi/operations/events/v2_list_events_responses.go
- swagger.yaml
At present, we collect 4 headers for event counts of each severity level, which indicate the number of filtered events based on their severity. However, we aim to modify these counts to exclude severity filtering. To accomplish this, we require an additional count header that represents the total number of retrieved events after all filtering.
> MGMT-14425: Changing event counts behavior

- internal/host/hostutil/host_utils.go
> OCPBUGS-13356: Fix 'vendor' root device hint evaluation

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
When using the converged flow the BMH needs to be deprovisioned to properly reboot into the discovery image when an agent is unbound.
To do this BMAC must unset the bmh.Spec.CustomDeploy field then set it back to start the provisioning process over again.
Resolves https://issues.redhat.com/browse/MGMT-13936
Deployed this code to a dev-scripts spoke.
Created an SNO using late-binding
Unbound the agent
Observed the required changes in the BMH and the agent move through `unbinding-pending-user-action` back to `known-unbound` after BMO rebooted the host and it re-registered.
> MGMT-13936: Make unbind work for converged flow BMHs

- api/vendor/github.com/openshift/assisted-service/models/domain_resolution_request.go
- models/domain_resolution_request.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/domain_resolution_request.go
> MGMT-14526: Allow trailing dot (.) to be appended to domain name

- api/hiveextension/v1beta1/agentclusterinstall_types.go
- config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
- internal/controller/controllers/clusterdeployments_controller.go
- subsystem/kubeapi_test.go
- vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
Replacement for #3146
see https://docs.openshift.com/container-platform/4.9/nodes/nodes/nodes-nodes-working.html#nodes-nodes-working-master-schedulable_nodes-nodes-working for more details
/cc @
/cc @
> MGMT-8097: masters schedulable kube-api

- api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
- internal/bminventory/inventory_test.go
- internal/featuresupport/common.go
- internal/featuresupport/feature_support_level.go
- internal/featuresupport/feature_support_test.go
- internal/featuresupport/features.go
- models/feature_support_level_id.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
Set OCI validations as described in [feature-support matrix](https://docs.google.com/spreadsheets/d/1IJugmChJTKMBjdXHojEgfsyE8WT-dGbUpETn8fhuI7g/edit#gid=0) 
/cc @adriengentil @gamli75
> MGMT-14649: Add feature support for OCI platform

- internal/featuresupport/feature_support_test.go
- internal/featuresupport/features.go
Return bad request on LSO on ARM architecture
/cc @eliorerz
> MGMT-14781: Make LSO operator to support all CPU architectures

- api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
- internal/featuresupport/common.go
- internal/featuresupport/feature_support_level.go
- internal/featuresupport/feature_support_test.go
- internal/featuresupport/features.go
- internal/network/dual_stack_validations.go
- models/feature_support_level_id.go
- restapi/embedded_spec.go
- subsystem/cluster_test.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
> MGMT-14600: Prevent installing dual-stack vSphere on OCP version less than 4.13 

- internal/featuresupport/features.go
Continue of https://github.com/openshift/assisted-service/pull/5221
> MGMT-14631: Removing leftover of support for openshift 4.8

- internal/bminventory/inventory.go
Cherry pick of https://github.com/openshift/assisted-service/pull/5302
Image Type is colliding with the default value on Z architecture (s390x). This PR handle both in the same place.
> [cloud_hotfix_releases] MGMT-14992: Fix Minimal ISO set as default in s390x

- internal/featuresupport/feature_support_test.go
- internal/featuresupport/features.go
> MGMT-15025: Forbid register Z architecture cluster with OCI platform

- cmd/main.go
[MGMT-13284](https://issues.redhat.com/browse/MGMT-13284)
Explicitly check for the existence of the BMH CRD before allowing the controller to register with the manager. This prevents an unclear fatal error if the controller was created and the BMH CRD is not defined.
/cc @carbonin
> MGMT-13284: Check for BMH CRD before creating controller

- internal/controller/controllers/agent_controller_test.go
- internal/controller/controllers/csr_utils.go
As of OCP 4.14 this isn't present in new node CSRs.
Before this change day-2 worker node CSRs in non-baremetal 4.14
spoke clusters would not get approved because of the mismatch in usages.
Resolves https://issues.redhat.com/browse/OCPBUGS-15152
Analogous changes in cluster-machine-approver:
https://github.com/openshift/cluster-machine-approver/pull/184
https://github.com/openshift/cluster-machine-approver/pull/186
https://github.com/openshift/cluster-machine-approver/pull/189
Deployed this image to a management cluster where a hypershift spoke was failing to add a node due to this issue and saw the node get successfully added. …
> OCPBUGS-15152: Don't require key encipherment usage for approving CSRs

- internal/featuresupport/feature_support_test.go
- internal/featuresupport/features.go
> MGMT-15126: Add missing incompatible features in some of the feature-support feature

- docs/hive-integration/baremetal-agent-controller.md
- docs/hive-integration/kube-api-getting-started.md
https://issues.redhat.com/browse/MGMT-14851
Epic: https://issues.redhat.com/browse/MGMT-13017
Updates the docs surrounding Ironic's automatedCleaningMode so that users will know what to expect when they use this and later version of assisted service.
> MGMT-14851: Update docs for allowing automatedCleaningMode

- deploy/podman/README.md
- deploy/podman/okd-configmap.yml
- internal/ignition/ignition.go
- internal/ignition/ignition_test.go
- openshift/template.yaml
OKD files generation it's currently very expensive because of shelling out `oc` command. This makes us vulnerable to potential DoS attacks.
Disabling OKD support by default in SaaS should help mitigate the issue.
/cc @osherdp @gamli75 @carbonin @tsorya
> MGMT-15389: add feature flag to enable/disable OKD support

- deploy/podman/README.md
- deploy/podman/okd-configmap.yml
- internal/ignition/ignition.go
- internal/ignition/ignition_test.go
- openshift/template.yaml
Backports https://github.com/openshift/assisted-service/pull/5400
> MGMT-15389: add feature flag to enable/disable OKD support (#5400)

- internal/host/statemachine.go
- internal/host/transition_test.go
Whenever we update baremetal platform to not supported platform we get `no condition found to run transition` error 
/cc @eliorerz
> MGMT-15335: Fix missing transition when trying to update to not supported platform

- internal/bminventory/inventory.go
After the PR for [MGMT-11456](https://issues.redhat.com//browse/MGMT-11456) was merged, it was discovered that there was a duplication of functionality. This PR removes that duplication.
> MGMT-11456: Bugfix - remove redundant code

- subsystem/feature_support_levels_test.go
Add more tests to test the platform support level 
/cc @gamli75
> NO-ISSUE: Add subsystem tests to platform support level

- config/rbac/role.yaml
- deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
- internal/controller/controllers/agentserviceconfig_controller.go
- internal/controller/controllers/clusterdeployments_controller.go
- pkg/localclusterimport/import_local_cluster.go
- pkg/localclusterimport/import_local_cluster_test.go
- pkg/localclusterimport/local_cluster_import_operations.go
- pkg/localclusterimport/local_cluster_import_operations_mocks.go
During the QE process for this feature, it was discovered that there are some bugs preventing the proper creation of a ClusterDeployment in some environments. The owner of the ClusterDeployment has been changed to the AgentServiceConfig as it should be and a permission has been added to permit "ManagedClusterSet/join" as this is required to be able to create a ClusterDeployment.
Tested using a cluster running CIM, restarted assisted-service deployment and observed that the correct CR's are created.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/ …
> MGMT-15704 - Bugfix for local cluster import

- cmd/main.go
- internal/uploader/events_uploader.go
- internal/uploader/events_uploader_test.go
- internal/uploader/uploader.go
> NO-ISSUE: Add versions file to onprem event upload

- internal/uploader/events_uploader.go
- internal/uploader/events_uploader_test.go
This change will return error on upload if the response code for the upload request is not 2XX.
For example, when using the wrong pull secret, at the moment this request will return 401, but logging would say "successfully uploaded events". This change would change this and we'd notify of the error.
@CrystalChun 
> NO-ISSUE: fail upload if response is not 2XX

- OWNERS_ALIASES
/cc @filanov @gamli75 @romfreiman
> MGMT-15507: Set restricted list of approvers for protected release-ocm-2.9 branch

- deploy/operator/ztp/baremetalHost.j2
- deploy/operator/ztp/infraEnv-latebinding.j2
- deploy/operator/ztp/infraEnv.j2
Add console output in order to help debugging
> NO-ISSUE: add console output for ztp CI jobs

- internal/feature/flags.go
This reverts commit 0e73e3f0d6458e8ccb8fcc02eff8119d24a037a2.
The problem with ZTP test was fixed.
> Revert "NO-ISSUE: Set default ENABLE_SKIP_MCO_REBOOT: false (#5560)"

- hack/setup_env.sh
Reverts openshift/assisted-service#5572
> Revert "MGMT-15997: use kubectl 1.28.2"

- internal/network/manifests_generator.go
[MGMT-16061](https://issues.redhat.com//browse/MGMT-16061): SNO: dnsmasq and force dns should be configurable in order to support ip change
1. Change dnsmasq configuration to use template and set ip to single-node.conf taken from nodeip-configuration primary ip file
2. Allow setting new ip to force dns dispatcher script
> MGMT-16061: changing dnsmasq configuration for sno in order to meet single ip installation flow for ibu

- internal/controller/controllers/infraenv_controller.go
> MGMT-15680: Adds InfraEnv ctrl watch for pull secret changes

- openshift/template.yaml
Downloading logs for big clusters was timing out.
We will override in the deployment with even higher timeout to avoid such issues, but let's increase slightly the default.
> MGMT-16151: change default envoy sidecar timeout value

- deploy/operator/setup_lso.sh
This change just bumps our hack of using 4.14 catalog for `LSO` installation to `OCP` grater than `4.14`.
> MGMT-16164: Install 4.14 redhat-operators catalog for LSO

- pkg/app/middleware.go
As preflight checks are performed by the browser, the presigned url throws CORS error/warning on HEAD request.
Although this doesn't seem to be harmful, it throws a lot of warning and errors that might confuse users.
> MGMT-16151: allow CORS HEAD for s3 presigned url

- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/bmh_agent_controller.go
> NO-ISSUE: BMH and Agent controllers code cleanup

- .github/dependabot.yml
Optimizting dependabot, 
major changes cause test not to pass, thus spliting to different groups 
1. minor group which conatins bug fixes and security
2. major group which may need some fixes in code / lint to make test pass 
- [ X] CI/CD 
- [] None
> NO-ISSUE: dependabot optimize

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/inventory_v2_handlers.go
> NO-ISSUE: Inventory code cleanups

- deploy/operator/capi/deploy_capi_cluster.sh
Mirrors images and sets up hypershift for disconnected
IPv6 capi agent cluster.
---
Details:
Disconnected hypershift requires:
1. The pull secret to be created in the hypershift namespace
(where the hypershift operator pod runs)
2. The hypershift operator to be mirrored to the local registry
3. The hypershift CLI to be available locally
4. The openshift release to be mirrored to the local registry
5. The cluster-api-provider-agent image to be mirrored to the local registry
6. Image content policy for the local registry
7. Flags for the hypershift create command
Relevant release PR: https://github.com/openshift/release/pull/43723
- Is there a bug required (and linked) …
> HOSTEDCP-999: Setup CI for disconnected ipv6 CAPI

- internal/cluster/cluster.go
- internal/cluster/registrar.go
- internal/cluster/statemachine.go
- internal/cluster/validator.go
> NO-ISSUE: Cluster code cleanups

- internal/installcfg/builder/builder_test.go
- internal/installcfg/installcfg.go
Include the BMC fields in install-config overrides in order to allow these settings to be configured at install time.
> AGENT-740: Include baremetal host BMC fields in install-config override

- internal/controller/controllers/agent_reclaimer.go
- internal/controller/controllers/agent_reclaimer_test.go
https://issues.redhat.com/browse/MGMT-16001
Originally replaced all periods `.` with an underscore `_` character, which is actually not allowed. Now
all periods will be replaced by a dash character `-`.
/cc @elsapassaro @filanov
> MGMT-16001: Sanitize reclaim agent daemonset name

- deploy/operator/common.sh
Updated OS_IMAGES list filter in deploy/operator to 4.11. I.e. filter the list to images of OCP version >= 4.11.
> NO-ISSUE: update OS_IMAGES filter to 4.11

- cmd/main.go
> MGMT-16289: Add configuration variable and cluster attribute defining if soft timeouts feature is enabled

- internal/network/manifests_generator.go
Cherry pick for new dnsmasq configuration
https://github.com/openshift/assisted-service/pull/5658
https://github.com/openshift/assisted-service/pull/5613
> [release-ocm-2.9] MGMT-16312:  changing dnsmasq configuration for sno in order to meet single ip installation flow for ibu 

- internal/featuresupport/feature_support_test.go
- internal/featuresupport/features_misc.go
Verified that cluster with architecture s390x doesn't have active feature skip MCO reboot.
/cc @filanov 
/cc @tsorya
> MGMT-16414: When trying to create cluster with s390x architecture, an error occurs that stops cluster creation

- deploy/operator/capi/deploy_capi_cluster.sh
Changes:
1. Get the control plane operator image from the release instead of the local hypershift image.
2. Add Image Content Source for hosted cluster
3. Add registry override flag for MCO image
/cc @filanov @avishayt
> HOSTEDCP-999: Fix images used for disconnected CAPI test

- internal/installcfg/installcfg.go
- internal/provider/external/installConfig.go
Manual cherrypick of https://github.com/openshift/assisted-service/pull/5548
> OCPBUGS-26764: set CloudControllerManager to External for OCI

- api/go.mod
- api/vendor/modules.txt
- client/go.mod
- client/vendor/modules.txt
- deploy/operator/deploy.sh
- hack/setup_env.sh
- models/go.mod
- vendor/modules.txt
- This change is for testing change to go1.20  
> NO-ISSUE: testing go1.20 in all packages

- OWNERS_ALIASES
> NO-ISSUE remove filanov from approves

- deploy/operator/gather.sh
The hypershift operator image doesn't ship with 'oc' which errors out when gathering hypershift artifacts.
This now downloads the hypershift cli if there's a hypershift cluster to gather from and runs the gather command locally instead of from the hypershift image.
> NO-ISSUE: Fix Hypershift must-gather

- .tekton/assisted-service-q2vh-pull-request.yaml
> NO-ISSUE: migrate pipeline task init from 0.1 to 0.2

- .tekton/assisted-service-q2vh-pull-request.yaml
- .tekton/assisted-service-q2vh-push.yaml
> NO-ISSUE: migrate rhtap init step to v0.2

- internal/host/host.go
- internal/host/host_test.go
- internal/host/hostcommands/instruction_manager_test.go
- internal/host/hostutil/update_host.go
- internal/host/hostutil/update_host_test.go
- internal/host/monitor_test.go
- internal/host/transition.go
- internal/host/transition_test.go
- internal/host/validations_test.go
We were not notifying about status_info update in some cases, this PR addresses this issue.
> MGMT-16612: notify when host updates status

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
- subsystem/kubeapi_test.go
In order to allow declarative association of host with a cluster in late binding flow, annotation support will be added to bmc. The annotation is "bmac.agent-install.openshift.io/cluster-reference". The annotation value is a json encoded string containing dictionary with keys [name,namespace] that correspond to the name and namespace of the cluster deployment. Reconcile of the BMH will cause the value of this annotation to be reflected to the cluster deployment in the corresponding agent spec.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-me …
> MGMT-16603: Allow setting agent cluster reference via BHM

- internal/featuresupport/feature_support_test.go
- internal/featuresupport/features_olm_operators.go
- internal/featuresupport/features_platforms.go
`CNV` should be disabled when select platform `VSphere` as it is not supported by `OCP`
> MGMT-16757: CNV should be disabled when select platform vSphere

- go.mod
- go.sum
- vendor/github.com/docker/docker/api/types/container/hostconfig_unix.go
- vendor/github.com/docker/docker/api/types/filters/parse.go
- vendor/github.com/docker/docker/api/types/registry/registry.go
- vendor/modules.txt
[MGMT-14226](https://issues.redhat.com/browse/MGMT-14226)
Upgrades go dependency github.com/docker/docker to 20.10.24 to fix CVE. https://github.com/moby/moby/security/advisories/GHSA-33pg-m6jh-5237
> MGMT-14226: Upgrade docker to 20.10.24 for CVE-2023-28842

- go.mod
- go.sum
- vendor/github.com/docker/docker/api/types/container/hostconfig_unix.go
- vendor/github.com/docker/docker/api/types/filters/parse.go
- vendor/github.com/docker/docker/api/types/registry/registry.go
- vendor/modules.txt
Cherry-pick of PR https://github.com/openshift/assisted-service/pull/5951
https://issues.redhat.com/browse/MGMT-14226
Upgrades go dependency github.com/docker/docker to 20.10.24 to fix CVE. https://github.com/moby/moby/security/advisories/GHSA-33pg-m6jh-5237
> [release-ocm-2.9] MGMT-14226: Upgrade docker to 20.10.24 for CVE-2023-28842 (#5951)

- internal/featuresupport/feature_support_test.go
- internal/featuresupport/features_networking.go
Disable vip auto allocation for 4.15 and later
> MGMT-16791: disable VipAutoAllocation for 4.15 and above

- subsystem/kubeapi_test.go
kubeapi subsystem tests which attempt to deploy `BareMetalHost` resource are failing because their name must have a string format instead of uuid -
```
Expected
<*errors.StatusError | 0xc000f37540>: 
admission webhook "baremetalhost.metal3.io" denied the request: BareMetalHost resource name cannot be a UUID
{
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "admission webhook \"baremetalhost.metal3.io\" denied the request: BareMetalHost resource name cannot be a UUID",
Reason: "Forbidden",
Details: nil,
Code: 403,
},
}
to be nil
```
- …
> NO-ISSUE: Change bare metal host CRD name to a non-uuid format

- cmd/main.go
https://issues.redhat.com/browse/MGMT-16523
The agent team sets the env var INSTALL_INVOKER to "agent-installer" during their deployment. This can be used to determine that it's an ABI deployment in our on-prem data collection.
Slack thread https://redhat-internal.slack.com/archives/C02SPBZ4GPR/p1705424434231019
/cc @rccrdpccl
> MGMT-16523: Set ABI deployment type for on-prem data collection

- internal/operators/lvm/config.go
- internal/operators/lvm/lvm_operator.go
- internal/operators/lvm/lvm_operator_test.go
- internal/operators/manager.go
- internal/operators/manager_test.go
> MGMT-16926: fix validation bug + allow CNV and LVM multi node

- internal/feature/flags.go
> MGMT-16980: Change the default value of ENABLE_SKIP_MCO_REBOOT to false

- openshift/template.yaml
> NO-ISSUE: Add environment variable ENABLE_SKIP_MCO_REBOOT to openshift/template.yaml

- internal/feature/flags.go
> OCPBUGS-29818: Spoke will not boot after agent install with error "Failed to mount /sysroot

- cmd/main.go
- deploy/assisted-service.yaml
- deploy/podman/configmap-disconnected.yml
- deploy/podman/configmap.yml
- deploy/podman/configmap_tls.yml
- internal/uploader/events_uploader.go
- internal/uploader/events_uploader_test.go
- internal/uploader/uploader.go
- openshift/template.yaml
Cherry-pick of:
1. Add Env Var On-Prem Data Deployment Type https://github.com/openshift/assisted-service/pull/5874
2. https://github.com/openshift/assisted-service/pull/5967 (https://issues.redhat.com/browse/MGMT-16523) to set it to ABI when it's an agent-based install
/cc @gamli75 @zaneb
> [release-4.15] MGMT-16517: Add Env Var Deployment Type & Set ABI

- internal/versions/versions.go
Currently the code that accesses the must gather versions cache uses a map without any protection agains concurrent writes. As a result in some situations this results in a concurrent writes error:
```
2024-03-12 03:44:13
fatal error: concurrent map writes
github.com/openshift/assisted-service/internal/versions.(*handler).GetMustGatherImages(0xc000222c40, {0xc001dea8a0, 0xb}, {0xc001dea8d4, 0x5}, {0xc0037be000, 0xad2})
/assisted-service/internal/versions/versions.go:95 +0x2e5
```
This patch uses a mutex to protect access to that map.
Note that this is a simple solution, but not ideal, as it means that concurrent calls to the `GetMustGatherImages` method will be serialized. I am not sure if the logic inside that method takes long to execute. If it does this could impact performance.
- Are …
> NO-ISSUE: Protect must gather versions cache with mutex

- openshift/template.yaml
> NO-ISSUE: Add environment variable ENABLE_SOFT_TIMEOUTS to openshift/template.yaml

- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
Before this commit the only in-progress clusters that could be successfully deleted were ones in states "installing" or "preparing-for-installation".
This means that if a cluster failed in, for example, "installing-pending-user-action" and a user deleted the cluster deployment the delete would hang on the finalizer handling because the controller wouldn't cancel the install and the hosts would fail to be unbound when install was in progress.
This commit aligns the states we call cancel for a cluster in the agent cluster install finalizer handling with the states that the state machine allows a cluster to be canceled in.
Resolves https://issues.redhat.com/browse/MGMT-16706
1. Deployed a dev-scripts cluster
2. Created an infraenv with RHCOS version 4.15
3. Booted 3 hosts
4. Bound agents to …
> MGMT-16706: Allow in-progress clusters to be deleted in more cases

- internal/cluster/validator.go
For non-OVN/SDN networkTypes, the hostPrefix validation is not required and it is skipped. This fixes a regression introduced in the fix for https://issues.redhat.com/browse/OCPBUGS-23069 in which IPv6 CIDRs were not using the correct default hostPrefix. In addition, all cases where the validation is used are now covered.
> OCPBUGS-30232: Handle skipping hostPrefix validation for IPv6

- Makefile
- config/manager/manager.yaml
- config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
- deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
- deploy/podman/pod-persistent-disconnected.yml
- deploy/podman/pod-persistent.yml
- deploy/podman/pod.yml
- deploy/podman/pod_tls.yml
- deploy/postgres/postgres-deployment-ephemeral.yaml
- deploy/postgres/postgres-deployment.yaml
- docs/dev/testing.md
- internal/common/common_unitest_db.go
- internal/controller/controllers/images.go
Backport of https://github.com/openshift/assisted-service/pull/6116
> [release-ocm-2.10] NO-ISSUE: replace postgres images as current image disappeared from quay.io

- Makefile
- config/manager/manager.yaml
- config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
- deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
- deploy/podman/pod-persistent-disconnected.yml
- deploy/podman/pod-persistent.yml
- deploy/podman/pod.yml
- deploy/podman/pod_tls.yml
- deploy/postgres/postgres-deployment-ephemeral.yaml
- deploy/postgres/postgres-deployment.yaml
- docs/dev/testing.md
- internal/common/common_unitest_db.go
backport of https://github.com/openshift/assisted-service/pull/6116
> NO-ISSUE: replace postgres images as current one disappeared from quay

- internal/installcfg/builder/builder.go
- internal/installcfg/builder/builder_test.go
Openshift releases earlier than 4.14 do not support the ImageDigestMirrorSet so configure ImageContentSources when building the install-config for these versions.
> MGMT-17367: Use ICSP in install-config for older OCP releases

- internal/versions/api.go
- internal/versions/api_test.go
Add multi-arch release images to as well when setting `only_latest=true` in `.../openshift-versions`
> MGMT-17369: Add multi-arch release images to as well when setting "only_latest=true" in ".../openshift-versions"

- internal/feature/flags.go
This reverts commit 0eb0c73b4d778b64fb37fe62a419f45c2b23d383.
/cc @gamli75
> Revert "MGMT-16980: Change the default value of ENABLE_SKIP_MCO_REBOOT to false (#6011)"

- Makefile
- config/manager/manager.yaml
- config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
- deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
- deploy/podman/pod-persistent-disconnected.yml
- deploy/podman/pod-persistent.yml
- deploy/podman/pod.yml
- deploy/podman/pod_tls.yml
- deploy/postgres/postgres-deployment-ephemeral.yaml
- deploy/postgres/postgres-deployment.yaml
- docs/dev/testing.md
- internal/common/common_unitest_db.go
- internal/controller/controllers/images.go
backport of https://github.com/openshift/assisted-service/pull/6116
> [release-ocm-2.9] NO-ISSUE: replace postgres images as current one disappeared from quay

- docs/operator.md
Plain HTTP is supported, and this adds doc
on how to use it.
/cc @carbonin
> NO-ISSUE: Add doc for iPXE HTTP

- deploy/s3/deployment.yaml
Original image is now not possible to fetch without right permission:
```
$ podman pull quay.io/cloudservices/minio:latest
Trying to pull quay.io/cloudservices/minio:latest...
Error: initializing source docker://quay.io/cloudservices/minio:latest: reading manifest latest in quay.io/cloudservices/minio: unauthorized: access to the requested resource is not authorized
```
> NO-ISSUE: replace minio quay.io image repository

- OWNERS_ALIASES
>    NO-ISSUE: Add my account as an approver

- OWNERS_ALIASES
> NO-ISSUE: Add more accounts as approvers

- OWNERS_ALIASES
> NO-ISSUE: Add missing accounts for PR approvals

- Makefile
- config/manager/manager.yaml
- config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
- deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
- deploy/podman/pod-persistent-disconnected.yml
- deploy/podman/pod-persistent.yml
- deploy/podman/pod.yml
- deploy/podman/pod_tls.yml
- deploy/postgres/postgres-deployment-ephemeral.yaml
- deploy/postgres/postgres-deployment.yaml
- docs/dev/testing.md
- internal/common/common_unitest_db.go
backport of https://github.com/openshift/assisted-service/pull/6116
> [release-ocm-2.7] NO-ISSUE: replace postgres images as current one disappeared from quay

- OWNERS_ALIASES
> [release-ocm-2.9] NO-ISSUE: Add missing accounts for PR approvals

- deploy/operator/capi/deploy_capi_cluster.sh
Now that hypershift is compiled with CGO_ENABLED=1 the hypershift CLI fails with
/lib64/libc.so.6: version `GLIBC_2.32' not found (required by hypershift) /lib64/libc.so.6: version `GLIBC_2.34' not found (required by hypershift)
So instead we'll try to run it in a pod as we do for connected tests.
> MGMT-17489: Fix disconnected CAPI tests

- internal/network/connectivity_groups.go
Hosts were incorrectly marked as connected to each other even if there were no IP address connections found.
/cc @ori-amizur
> NO-ISSUE: Prevent false positive host connectivity

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
https://issues.redhat.com/browse/MGMT-17313
Previously, only day 2 workers had BMH and Machines created for them. We want the same behavior for day 2 control plane nodes (added in https://issues.redhat.com/browse/MGMT-8578) so that their CSRs will be approved automatically.
> MGMT-17313: Create day 2 BMH and Machine for control plane nodes

- internal/common/version.go
- internal/common/version_test.go
- internal/versions/api.go
- internal/versions/api_test.go
Currently when requesting the latest openshift versions at `../openshift-versions?only_latest=true`, you get at most one CPU architecture in the list. This PR fixes that issue.
> MGMT-17503: Fix the cpu architectures retrieved in ../openshift-versions endpoint

- internal/versions/versions.go
- internal/versions/versions_test.go
Cherry-pick of #6066 
https://issues.redhat.com/browse/MGMT-17544
Original PR message:
https://issues.redhat.com/browse/MGMT-16813
Previously, the `getReleaseImageFromCache` would get all release images that included the CPU architecture and return the first instance it found that matched the desired Openshift version.
Since multi-arch images include the CPU architecture, it led to undesireable selection of the multi-arch image over the exact matching image with the specified CPU architecture.
This fix ensures that the release image will be found with the following priority:
1. Exact CPU Architecture & OpenShift x.y.z version match
2. Exact CPU Architecture & OpenShift Major Minor (x.y) version match
3. Multi-arch CPU with specified CPU Architecture & OpenShift x.y.z version match
4. …
> [release-ocm-2.8] MGMT-17544: Prioritize finding release image with exact CPU architecture

- OWNERS_ALIASES
Add openshift-edge-bot as an OWNER in order to run konflux pipelines on its PRs
> NO-ISSUE: Add openshift-edge-bot as an OWNER

- internal/versions/rest_api_versions.go
- internal/versions/rest_api_versions_test.go
Update the latest image search functionality in the `RestAPI` flow to correctly compare pre-release versions
> MGMT-17764: Update the latest image search functionality in the RestAPI flow to correctly compare pre-release versions

- deploy/operator/setup_lso.sh
> NO-ISSUE: wait for LSO to be installed

- internal/versions/osimages.go
- internal/versions/osimages_test.go
Fail when OS images CPU architecture is missing instead of giving it default value in order not to generate false infraenv
> MGMT-17523: [backport-release-ocm-2.10] Fail when OS images CPU architecture is missing instead of giving it default value

- internal/cluster/validations/validation_test.go
- internal/cluster/validations/validations.go
Manual cherry-pick of https://github.com/openshift/assisted-service/pull/6362
> [release-4.15] OCPBUGS-34641: Invalid Pull-Secret when using password which contains a colon character

- internal/featuresupport/feature_support_test.go
- internal/featuresupport/features_platforms.go
Remove OCI from technology preview as it is now a supported integration.
> MGMT-18059: Mark OCI as supported integration

- openshift/template.yaml
> NO-ISSUE: Remove double 'required: false' in openshift template

- internal/uploader/events_uploader.go
- internal/uploader/events_uploader_test.go
- internal/uploader/extract.go
- internal/uploader/extract_test.go
- pkg/uploader/events.go
- pkg/uploader/models/metadata.go
Adding some helper to parse events generated by assisted-service and then parsed by assisted-events-stream.
IMHO it is more maintainable to gather the code that create the tar.gz content next to the code that parse that tar.gz content. Assisted-events-stream shouldn't take hypothesis about how assisted-service internally generate this binary
> MGMT-18041: Expose helper to parse uploaded events (on-prem)

- OWNERS_ALIASES
To successfully pass the konflux job and merge PRs, I must include my account in the OWNER_ALIASES file.
> NO-ISSUE: Add Linoy Hadad to OWNER_ALIASES file

- internal/bminventory/inventory.go
Currently, during cluster registration, the new cluster parameters display addresses instead of values:
`log.Infof("Register cluster: %s with id %s and params %+v", swag.StringValue(params.NewClusterParams.Name), id, params.NewClusterParams)`
To resolve this issue, I've modified the logging behavior. Now, the log shows values instead of addresses by marshaling the struct to JSON. Additionally, I've masked the pull-secret value with "***" to protect sensitive information from being exposed in the logs.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#c …
> MGMT-17708: Adjust the logs to show values when registering the cluster

- OWNERS_ALIASES
Add Omer Vishlitzky to OWNERS_ALIASES file
> NO-ISSUE: Add omer-vishlitzky to OWNERS_ALIASES file

- docs/enhancements/transactional-custom-manifests.md
We would like to improve the custom manifest feature to make it more consistent, more reliable and more user friendly. By addressing the following points
We have had a recent bug report about an edge case
The following bug was contributed to by this issue: https://issues.redhat.com/browse/MGMT-18019
In this edge case, if there is a failure in S3 with unfortunate timing then it is possible to store a manifest with inconsistent metadata.
This is not a situation that is acceptable moving forward and we need to do something.
There are some problems with the existing implementation of manifest storage when it comes to metadata and we need to change the implementation to ensure that any manifest creation or update is performed in a single operation to the underlying storage. …
> MGMT-18163: Enhancement - Transactional Custom Manifests

- Makefile
if build directory is missing, 
`podman save -o build/assisted_service_image.tar localhost/assisted-service:latest` 
will return an error
> NO-ISSUE: Create 'build' directory if missing

- OWNERS_ALIASES
> NO-ISSUE: Add pastequo as approver

- docs/dev/running-test.md
> NO-ISSUE: Add missing 'make' command

- .tekton/assisted-service-saas-main-pull-request.yaml
- .tekton/assisted-service-saas-main-push.yaml
Fix Konflux PR https://github.com/openshift/assisted-service/pull/6471
> NO-ISSUE: Fix Konflux git clone params

- .tekton/assisted-service-saas-main-pull-request.yaml
- .tekton/assisted-service-saas-main-push.yaml
> NO-ISSUE: Increase Konflux git clone depth

- Makefile
`subsystem-clean` target was removed in https://github.com/openshift/assisted-service/pull/6385/files, retrieving it
> NO-ISSUE: Retrieve 'subsystem-clean' target as it is used by the QE

- renovate.json
Since Konflux added renovates a lot of PR are created
Adding this configuration will
* gather PRs created simultaneously into a single one
* PRs will be created once a week (on Saturday)
* It seems that PR will still requires some manual /lgtm (still require some investigation)
> [cloud_hotfix_releases] NO-ISSUE: Add renovate config

- Dockerfile.assisted-service
Remove the python client form the image as it is no longer required - https://github.com/openshift/assisted-test-infra/pull/2486
> MGMT-18333: Remove the python client from the image

- internal/controller/controllers/agentserviceconfig_controller.go
- internal/controller/controllers/agentserviceconfig_controller_test.go
- internal/controller/controllers/kube_compat.go
Resolves https://issues.redhat.com/browse/MGMT-18305
> MGMT-18305: Add certs to ingress when deploying in non-OCP clusters

- Dockerfile.assisted-service
Tailored backport of https://github.com/openshift/assisted-service/pull/6579
> [release-ocm-2.10] MGMT-18333: Remove the python client from the image

- Dockerfile.assisted-service
Tailored backport of https://github.com/openshift/assisted-service/pull/6579
> [release-ocm-2.9] MGMT-18333: Remove the python client from the image

- Dockerfile.assisted-service
Tailored backport of https://github.com/openshift/assisted-service/pull/6579
> [release-ocm-2.8] MGMT-18333: Remove the python client from the image

- ci-images/Dockerfile.base
Tidy is required before vendoring - this is failing dependabot PRs
> NO-ISSUE: Tidy golang dependencies before vendoring in base image

- .tekton/assisted-service-saas-hotfix-pull-request.yaml
- .tekton/assisted-service-saas-hotfix-push.yaml
> NO-ISSUE: Konflux migration

- .tekton/assisted-service-saas-hotfix-pull-request.yaml
- .tekton/assisted-service-saas-hotfix-push.yaml
Deprecated image check migration
> NO-ISSUE: Deprecated image check migration

- internal/versions/common.go
- internal/versions/common_test.go
When creating an infraenv, a validation is performed to ensure that the release images contain a compatible image for a given Openshift version.
This based on the MajorMinor version of The desired Openshift version and and MajorMinor version of the relase image Openshift version.
This is performed within the context of a specific architecture.
The error message presented to the user when no suitable release image could be isolated is not helpful and needs to contain more clues on how the user might resolve the issue.
This PR will list available Openshift versions supported in the release images for the user's architecture when this error occurs.
- Should …
> MGMT-16242: Suggest OCP images based on availability for architecture

- Makefile
Use `skipper` to build debug image as it requires `nmstate` package
> NO-ISSUE: Use skipepr to build images as debug image requires nmstate packages

- pkg/auth/agent_local_authenticator.go
- pkg/auth/agent_local_authenticator_test.go
For the agent installer, parse the expiration time from the token and verify if the token is valid.
> AGENT-930: Verify token expiration

- internal/hardware/validator.go
- internal/hardware/validator_test.go
Currently, customers can select an iSCSI disk as an installation disk when its holder is multipath. We have decided to block this option for now.
> MGMT-18231: Block iSCSI as an installation disk when its holder is multipath

- .golangci.yml
- Dockerfile.assisted-service
- Dockerfile.assisted-service-build
- Dockerfile.assisted-service-debug
- ci-images/Dockerfile.base
- ci-images/Dockerfile.code-generation
- hack/container_build_scripts/install_build_deps.sh
- hack/container_build_scripts/replace_dnf_repositories_ref_if_needed.sh
* Replace Centos Linux 7 based golang images with ubi9 based golang images
* Replaces deprecated lint package
This PR will be later followed by a PR to apply the new build arg in openshift/release
> MGMT-18313: Replace golang base image as it is based on Centos Linux 7

- .golangci.yml
- Dockerfile.assisted-service
- Dockerfile.assisted-service-build
- Dockerfile.assisted-service-debug
- ci-images/Dockerfile.base
- ci-images/Dockerfile.code-generation
- subsystem/kubeapi_test.go
Backport of https://github.com/openshift/assisted-service/pull/6637
> [release-ocm-2.9] MGMT-18313: Replace golang base image as it is based on Centos Linux 7

- .golangci.yml
- Dockerfile.assisted-service
- Dockerfile.assisted-service-build
- Dockerfile.assisted-service-debug
- ci-images/Dockerfile.base
- ci-images/Dockerfile.code-generation
- hack/container_build_scripts/install_build_deps.sh
- hack/container_build_scripts/replace_dnf_repositories_ref_if_needed.sh
Backport of https://github.com/openshift/assisted-service/pull/6637
> [release-ocm-2.11] MGMT-18313: Replace golang base image as it is based on Centos Linux 7

- .golangci.yml
- Dockerfile.assisted-service
- Dockerfile.assisted-service-build
- Dockerfile.assisted-service-debug
- ci-images/Dockerfile.base
- ci-images/Dockerfile.code-generation
Backport of https://github.com/openshift/assisted-service/pull/6637
> [release-ocm-2.10] MGMT-18313: Replace golang base image as it is based on Centos Linux 7

- .golangci.yml
- Dockerfile.assisted-service
- Dockerfile.assisted-service-build
- Dockerfile.assisted-service-debug
- ci-images/Dockerfile.base
- ci-images/Dockerfile.code-generation
- subsystem/kubeapi_test.go
Backport of https://github.com/openshift/assisted-service/pull/6637
> [release-ocm-2.8] MGMT-18313: Replace golang base image as it is based on Centos Linux 7

- Dockerfile.assisted-service-debug
Leftover from - https://github.com/openshift/assisted-service/pull/6637
> NO-ISSUE: Fix debug image by adding required packages

- Dockerfile.assisted-service-debug
- Makefile
Currently we can't test the debug image in the CI as it requires building the binaries prior to the image building. This PR changes it so it will be done during the image building
> NO-ISSUE: Change debug Dockerfile so it will not require prior actions

- Dockerfile.assisted-service-debug
- Makefile
cherry-pick of https://github.com/openshift/assisted-service/pull/6674
> [release-ocm-2.10] NO-ISSUE: Change debug Dockerfile so it will not require prior actions

- Dockerfile.assisted-service-debug
- Makefile
cherry-pick of https://github.com/openshift/assisted-service/pull/6674
> [release-ocm-2.11] NO-ISSUE: Change debug Dockerfile so it will not require prior actions

- Dockerfile.assisted-service-debug
- Makefile
cherry-pick of https://github.com/openshift/assisted-service/pull/6674
> [release-ocm-2.9] NO-ISSUE: Change debug Dockerfile so it will not require prior actions

- Dockerfile.assisted-service-debug
- Makefile
cherry-pick of https://github.com/openshift/assisted-service/pull/6674
> [release-ocm-2.8] NO-ISSUE: Change debug Dockerfile so it will not require prior actions

- internal/featuresupport/features_olm_operators.go
- internal/featuresupport/features_olm_operators_test.go
- internal/operators/cnv/cnv_operator.go
- internal/operators/cnv/cnv_operator_test.go
- internal/operators/manager_test.go
- subsystem/cluster_test.go
Enabling CNV for ARM platfrom for versions 4.14+ as dev preview
Adding unit-tests for CNV
API:
```console
> curl -s -X GET 'http://127.0.0.1:6000/api/assisted-install/v2/support-levels/features?openshift_version=4.14&cpu_architecture=arm64' | jq .features.CNV
"dev-preview"
```
UI:
/cc @AlonaKaplan 
/cc @danmanor
> MGMT-18378:  allow CNV on ARM Dev preview

- .ci-operator.yaml
- Dockerfile.assisted-service.ocp
> NO-ISSUE: change ci operator to 4.17

- docs/enhancements/backup-restore-support.md
Enhancement document for improving the backup/restore support.
> MGMT-18589: Enhancement doc for backup/restore support

- OWNERS_ALIASES
> NO-ISSUE: Add mlorenzofr to OWNERS_ALIASES file

- deploy/operator/setup_lso.sh
> NO-ISSUE: workaround for LSO on 4.17

- docs/dev/running-test.md
Replaced the missing `destroy-kind-cluster` target with the new `destroy-hub-cluster` target.
> NO-ISSUE: fixed destroy target in running-test doc

- pkg/auth/agent_local_authenticator.go
- pkg/auth/agent_local_authenticator_test.go
> CORS-3664: Authentication tech debt for agent based installer

- .github/dependabot.yml
> MGMT-18466: grouping all other updates

- OWNERS_ALIASES
> NO-ISSUE: Add linoyaslan to approvers list

- internal/operators/cnv/cnv_operator.go
- internal/operators/cnv/cnv_operator_test.go
> MGMT-19006, MGMT-19004, MGMT-19007: rremove default LVM for CNV deployments

- deploy/operator/capi/deploy_capi_cluster.sh
The script used to deploy a CAPI cluster creates a `ImageContentSourcePolicy` object to configure the mirrors used in disconnected environments. That is deprecated since OpenShift 4.14. This patch changes it to check if the new `ImageDigestMirrorSet` object is available, and use it instead if it is.
The alternative to use the `ImageContentSourcePolicy` is preserved for older OpenShift versions.
Related: https://issues.redhat.com/browse/MGMT-17229
Related: https://github.com/openshift/enhancements/blob/master/enhancements/api-review/add-new-CRD-ImageDigestMirrorSet-and-ImageTagMirrorSet-to-config.openshift.io.md
[Kubernetes …
> MGMT-17229: Use IDMS if possible in CAPI deploy script

- subsystem/kubeapi_test.go
Due to a temporary issue, the kube-api subsystem tests passed falsely.
Thus, masking a couple of failures in https://github.com/openshift/assisted-service/pull/6705. See [job](https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-openshift-assisted-service-master-edge-subsystem-kubeapi-aws-periodic).
As a workaround for now, added 'skip-spoke-cleanup' annotation to agent.
Note: probably should fix later the missing kubeconfig to handle these tests properly:
```
Last Transition Time:  2024-09-29T09:33:18Z
Message:               failed to get secret assisted-installer/test-cluster-3b9806a1-admin-kubeconfig from API: secrets "test-cluster-3b9806a1-admin-kubeconfig" not found
Reason:                CleanupFailed
Status:                False
Type: …
```
> MGMT-10006: fix agent delete kube-api tests

- Dockerfile.assisted-service-debug
- docs/dev/debug.md
> NO-ISSUE: Fix debugging image and docs

- internal/hardware/virt/virt.go
> MGMT-19029: Fix issue where validation failed on CNV with ARM host

- pkg/staticnetworkconfig/backward_compatibility.go
> MGMT-19032: Use old static network flow if OCP version is empty

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
In order to ensure BMH deprovision by Ironic, removing the 'paused' annotation (if exists) as part of the finalizer.
> MGMT-18980: BMH finalizer - remove paused annotation

- internal/ignition/discovery.go
- internal/ignition/templates/discovery.ign
The common methods script for the old static network flow was missing in the full ISO flow.
> MGMT-19067: fix static network for fulliso old flow

- internal/common/test_configuration.go
- internal/ignition/discovery_test.go
- openshift/template.yaml
- pkg/staticnetworkconfig/backward_compatibility.go
- pkg/staticnetworkconfig/generator_test.go
- subsystem/infra_env_test.go
This is a manually cherry-pick of #6887 
> [cloud_hotfix_releases] MGMT-19099: modify default value of MIN_VERSION_FOR_NMSTATE_SERVICE flag to 4.19

- internal/common/test_configuration.go
- internal/ignition/discovery_test.go
- openshift/template.yaml
- pkg/staticnetworkconfig/backward_compatibility.go
- pkg/staticnetworkconfig/generator_test.go
- subsystem/infra_env_test.go
Since the current version of nmstate has a bug, it was decided to set the value to 4.19 for now. This means that no one will use the new flow until version 4.19 is released, with the assumption that the bug will be resolved by that time.
> MGMT-19099: Modify default value of MIN_VERSION_FOR_NMSTATE_SERVICE flag to 4.19

- hack/setup_env.sh
As done in https://github.com/openshift/assisted-service/pull/6900, pinning `github.com/axw/gocov` version to v1.1.0 (thanks @CrystalChun!).
Also, pinning `github.com/AlekSi/gocov-xml` version to v1.1.0 (which was missing from the original PR).
This should resolve the following error:
```
+ go install github.com/AlekSi/gocov-xml@v0.0.0-20190121064608-3a14fb1c4737
go: downloading github.com/AlekSi/gocov-xml v0.0.0-20190121064608-3a14fb1c4737
go: finding module for package github.com/axw/gocov
go: downloading github.com/axw/gocov v1.2.1
go: toolchain upgrade needed to resolve github.com/axw/gocov
go: github.com/axw/gocov@v1.2.1 requires go >= 1.22.0 (running go 1.21.13; GOTOOLCHAIN=local)
``` …
> NO-ISSUE: Pin gocov version

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
Previously BMAC was setting our finalizer for every BMH in the cluster and only removing them when we either saw the delete agent annotation or the paused annotation. This meant that no other BMHs could be removed without manually removing this finalizer.
This commit ensures the finalizer handling sees the finalizer being removed as a change and sets the "dirty" return flag accordingly and also ensures we never set out finalizer on a BMH without an infraenv label (one we don't own).
Resolves https://issues.redhat.com/browse/MGMT-19141
Manually tested by deploying to an environment with BMHs for multiple purposes.
Saw that finalizers were no longer being set for BMHs without the infraenv label. …
> MGMT-19141: Ensure no finalizer is set for BMHs without the infraenv label

- OWNERS_ALIASES
> NO-ISSUE: add carbonin to the owner list

- deploy/operator/setup_lso.sh
Bump LSO version override to 4.18 to enable assisted operator deployment scripts for OCP 4.18
> MGMT-19190: Bump LSO version override to 4.18

- .tekton/assisted-service-saas-main-pull-request.yaml
- .tekton/assisted-service-saas-main-push.yaml
The rpms-signature-scan task is a new task that must be included in all tekton pipeline by November 1st.
Part of [MGMT-19174](https://issues.redhat.com//browse/MGMT-19174)
> MGMT-19174: Add rpms-signature-scan task to tekton pipelines

- pkg/staticnetworkconfig/generator.go
- pkg/staticnetworkconfig/generator_test.go
The current solution doesn't account for situations where a user might select a name that matches one of the YAML keys or even a single character. The following change addresses this issue.
Some edge cases were checked, including:
```
interfaces:
- name: t
type: ethernet
state: up
ipv4:
enabled: true
address:
- ip: 192.168.101.3
prefix-length: 24
dhcp: false
dns-resolver:
config:
server:
- 192.168.101.1
routes:
config:
- destination: 0.0.0.0/0
next-hop-address: 192.168.101.1
next-hop-interface: t
table-id: 254
```
```
interfaces:
- name: bond99
type: bond
state: up
ipv4:
address:
- ip: 192.0.2.0
prefix-length: 24
enabled: true
link-aggregation:
mode: balance-rr
options:
miimon: '140'
port:
- t
- p
```
- Is there …
> MGMT-19171: Fix nmpolicy injection into nmstate YAML

- .tekton/assisted-service-saas-hotfix-pull-request.yaml
- .tekton/assisted-service-saas-hotfix-push.yaml
- hack/setup_env.sh
We need to migrate assisted-service to konflux, so we need the release pipeline to pass.
Currently it fails because the tasks in our build pipeline are to old, and the konflux-bot cannot update them itself because the migration of some of the task to their newer versions require user action.
This PR updates the necessary tasks and removes the deprecated task sbom-json-check.
Also cherry-picked [this](https://github.com/openshift/assisted-service/commit/b4205068e25d47e29dea27c220658d2b3d854173).
Part of [MGMT-19177](https://issues.redhat.com//browse/MGMT-19177) …
> [cloud_hotfix_releases] MGMT-19177: Update tekton pipelines' tasks to latest versions

- docs/dev/operator-on-kind.md
- docs/dev/running_kind_rootless.md
- hack/hub_cluster.sh
> NO-ISSUE: allow kind to run with non root user

- deploy/monitoring/grafana/assisted-installer-ocp-grafana.yaml
- deploy/monitoring/prometheus/assisted-installer-ocp-prometheus-subscription-instance.yaml
Update origin-oauth-proxy to fix security issues raised by app-sre
> MGMT-18417: Update openshift/origin-oauth-proxy image

- build_deploy.sh
- build_images.sh
cherry-pick https://github.com/openshift/assisted-service/commit/9525a42944e3cefd3cc686191dca37112e132a08
> [cloud_hotfix_releases] cherry-pick MGMT-19129: Migrate assisted-service to Konflux (#6911)

- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
Before this change, the paused annotation is added when the BMH reaches `provisioned` state.
But since the detached annotation is added only afterwards, the status annotation is stored with: `operationalStatus: OK` (i.e. instead of `operationalStatus: detached`).
Thus, when deleting the BMH, the wrong operationStatus is restored according to the status annotation (upon deleting the paused annotation). So this change ensures that the paused annotation is added only if the BMH is already detached.
Note: also added an info log in the finalizer to help with debugging. …
> MGMT-19215: add paused annotation only when BMH is detached

- internal/bminventory/inventory.go
- internal/bminventory/mock_installer_internal.go
- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
- subsystem/kubeapi_test.go
Cherry-pick of two PRs to restore hosts with Agent CRs:
https://github.com/openshift/assisted-service/pull/6730
https://github.com/openshift/assisted-service/pull/6957
/cc @gamli75 @danielerez @carbonin
> [release-ocm-2.11] MGMT-19194: Restore hosts using Agent CRs

- hack/setup_env.sh
```
go: downloading github.com/axw/gocov v1.2.1
go: github.com/axw/gocov/gocov@latest (in github.com/axw/gocov@v1.2.1): go.mod:3: invalid go version '1.22.0': must match format 1.23
```
> NO-ISSUE: pin compatible gocov version

- internal/controller/controllers/agent_reclaimer_test.go
`release-ocm-2.11` [publish job failed](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-assisted-service-release-ocm-2.11-operator-publish/1854481169215655936). This PR fixes a minor test name but its intent is to have the publish job be rerun on the branch.
Update: `mce-images` failed to run recently https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-assisted-service-release-ocm-2.11-mce-images/1856385862175035392
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-gui …
> NO-ISSUE: PR to rerun ACM 2.11 publish CI Job

- internal/featuresupport/features_olm_operators.go
- internal/featuresupport/features_olm_operators_test.go
> MGMT-19277: allow mtv to run on SNO clusters

- internal/host/validations_test.go
- internal/host/validator.go
iSCSI validation gets stuck because machine networks is not prompted to
user when using UMN.
This change skips the validation when user tries to spawn a multi-node
cluster with UMN (the right machine network will be choose at install
time).
We will also skip the validation for imported and day 2 cluster because 
we don't have all the information to perform this validation.
> MGMT-19290: iSCSI validation blocks UMN cluster installation

- internal/operators/lvm/lvm_operator.go
- subsystem/cluster_test.go
> MGMT-19283: fix output for preflight requirements

- internal/bminventory/inventory_test.go
- internal/featuresupport/feature_support_test.go
- internal/featuresupport/features_misc.go
> MGMT-19369: Restrict non-standard HA OCP control plane feature to x86_64 architecture

- cmd/main.go
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/bminventory/mock_installer_internal.go
- internal/cluster/capabilities.go
- internal/controller/controllers/bmh_agent_controller.go
- internal/controller/controllers/bmh_agent_controller_test.go
- internal/controller/controllers/common.go
- internal/installcfg/installcfg.go
If a spoke cluster is installed with BareMetal platform, but doesn't have MAPI enabled, we should not copy the BMH and Machine into the spoke cluster. 
> MGMT-18288: Don't copy BMH and Machine to Baremetal Spoke Cluster without MAPI

- OWNERS_ALIASES
> NO-ISSUE: Add giladravid16 to approvers list

- Dockerfile.assisted-service-rhel8-mce
- Dockerfile.assisted-service-rhel9-mce
As part of migrating to konflux, we need to update our downstream dockerfiles for mce and put them in our upstream repos.
Part-of [MGMT-19371](https://issues.redhat.com//browse/MGMT-19371)
> MGMT-19371: Add downstream dockerfiles for mce

- .tekton/assisted-service-rhel8-mce-downstream-main-pull-request.yaml
- .tekton/assisted-service-rhel8-mce-downstream-main-push.yaml
- .tekton/assisted-service-rhel9-mce-downstream-main-pull-request.yaml
- .tekton/assisted-service-rhel9-mce-downstream-main-push.yaml
Update the tekton pipelines used to build mce downstream images to be multi-arch.
Part-of [MGMT-19390](https://issues.redhat.com//browse/MGMT-19390)
> MGMT-19390: Update mce's tekton pipelines to be multi-arch

- api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
- client/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
- models/cluster_create_params.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
Since new param `control_plane_count` was introduced, `high_availability_mode` is redundant.
> MGMT-19348: Mark cluster-create-param high_availability_mode as deprecated

- .tekton/assisted-service-saas-hotfix-pull-request.yaml
- .tekton/assisted-service-saas-hotfix-push.yaml
> [cloud_hotfix_releases] NO-ISSUE: Update konflux pipeline ref

- internal/host/monitor.go
We are seeing that the query udpated in
https://github.com/openshift/assisted-service/pull/7030 causes
performance issues in stage, and causes the liveness probe to fail.
This change updates the query using a join instead of 2 sub-queries:
Before this change:
```
[
{
"schema": {
"refId": "A",
"meta": {
"typeVersion": [
0,
0
],
"executedQueryString": "EXPLAIN ANALYSE SELECT * FROM \"clusters\" WHERE ((id IN (SELECT cluster_id FROM hosts WHERE hosts.status in ('discovering','known','disconnected','insufficient','pending-for-input','preparing-for-installation','preparing-failed','preparing-successful','installing','installing-in-progress','installing-pending-user-action','resetting-pending-user-action') OR (hosts.status in ('cancelled','error') AND hosts.logs_info not in …
```
> [cloud_hotfix_releases] MGMT-19360: Improve monitor host query performance

- .tekton/assisted-service-rhel8-mce-downstream-2-13-pull-request.yaml
- .tekton/assisted-service-rhel8-mce-downstream-2-13-push.yaml
- .tekton/assisted-service-rhel9-mce-downstream-2-13-pull-request.yaml
- .tekton/assisted-service-rhel9-mce-downstream-2-13-push.yaml
This will finish the onboarding process for acm 2.13
Part-of [MGMT-19408](https://issues.redhat.com//browse/MGMT-19408)
> MGMT-19408: Create tekton pipelines for acm 2.13

- renovate.json
https://docs.renovatebot.com/configuration-options/#addlabels
> NO-ISSUE: renovate to add labels for auto-merge

- internal/host/monitor.go
We are seeing that the query udpated in
https://github.com/openshift/assisted-service/pull/7030 causes
performance issues in stage, and causes the liveness probe to fail.
This change updates the query using a join instead of 2 sub-queries:
Before this change:
```
[
{
"schema": {
"refId": "A",
"meta": {
"typeVersion": [
0,
0
],
"executedQueryString": "EXPLAIN ANALYSE SELECT * FROM \"clusters\" WHERE ((id IN (SELECT cluster_id FROM hosts WHERE hosts.status in ('discovering','known','disconnected','insufficient','pending-for-input','preparing-for-installation','preparing-failed','preparing-successful','installing','installing-in-progress','installing-pending-user-action','resetting-pending-user-action') OR (hosts.status in ('cancelled','error') AND hosts.logs_info not in …
```
> MGMT-19360: Improve monitor host query performance

- internal/featuresupport/feature_support_test.go
- internal/featuresupport/features_misc.go
- internal/featuresupport/features_platforms.go
> MGMT-19370: Enable none platfrom with non-standard HA control plane

- api/vendor/github.com/openshift/assisted-service/models/cluster.go
- api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
- api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
- client/vendor/github.com/openshift/assisted-service/models/cluster.go
- client/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
- client/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/cluster/cluster_test.go
- internal/cluster/transition_test.go
- internal/cluster/validator_test.go
- internal/common/db.go
- internal/migrations/20241122160000_update_new_column_control_plane_count_value_for_existing_cluster_records_test.go
- internal/operators/odf/validation_test.go
- models/cluster.go
- models/cluster_create_params.go
- models/v2_cluster_update_params.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/cluster.go
- vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
- vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Export control_plane_count cluster property so it will be accessible by clients. The UI needs the value tp present to the user his previous selection. 
> MGMT-19410: Export control_plane_count cluster property

- .tekton/assisted-service-rhel8-mce-downstream-2-13-pull-request.yaml
- .tekton/assisted-service-rhel8-mce-downstream-2-13-push.yaml
- .tekton/assisted-service-rhel8-mce-downstream-main-pull-request.yaml
- .tekton/assisted-service-rhel8-mce-downstream-main-push.yaml
- .tekton/assisted-service-rhel9-mce-downstream-2-13-pull-request.yaml
- .tekton/assisted-service-rhel9-mce-downstream-2-13-push.yaml
- .tekton/assisted-service-rhel9-mce-downstream-main-pull-request.yaml
- .tekton/assisted-service-rhel9-mce-downstream-main-push.yaml
A lot of time our pipelines as well as other teams' pipelines are stuck because they are unable to provision hosts with different architectures to build the images.
Because we currently don't use the multi-arch images we build with konflux, we will stop building multi-arch for now and readd those architectures when we need them.
Part-of [MGMT-19507](https://issues.redhat.com//browse/MGMT-19507)
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTI …
> MGMT-19507: Stop using multi-arch builds in konflux

- api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
- client/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
- internal/host/refresh_status_preprocessor.go
- internal/host/validation_id.go
- internal/host/validations_test.go
- internal/host/validator.go
- internal/network/utils.go
- internal/network/utils_test.go
- models/host_validation_id.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/host_validation_id.go
This PR introduces new validations for MTU. There are two separate validations: one for the CMN and another for the UMN. For CMN, we focus on reports from the agent that related specifically to the machine network. For UMN, we consider reports related to all interfaces. You can find the MTU checker added to the agent here - https://github.com/openshift/assisted-installer-agent/pull/821
> MGMT-19166: Implement MTU validations for CMN and UMN

- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
Manual cherry-pick of https://github.com/openshift/assisted-service/pull/6962
/cc @gamli75 
---
Previously, the ClusterImageSet defined by a ClusterDeployment was only cached if the cluster was being created. This is problematic in the long run if assisted is restarted and the cluster is not recreated. Errors "getting the release image" will occur due to this.
To prevent this, we'll now always try to cache the ClusterImageSet defined for a cluster even if it's already installed. This also allows us to ensure that the image the user specified in the ClusterImageSet as the release image to be installed. …
> [release-ocm-2.11] MGMT-19158: Always try to cache the ClusterImageSet (#6962)

- internal/controller/controllers/clusterdeployments_controller.go
- internal/controller/controllers/clusterdeployments_controller_test.go
Manual cherry-pick of https://github.com/openshift/assisted-service/pull/6962
---
Previously, the ClusterImageSet defined by a ClusterDeployment was only cached if the cluster was being created. This is problematic in the long run if assisted is restarted and the cluster is not recreated. Errors "getting the release image" will occur due to this.
To prevent this, we'll now always try to cache the ClusterImageSet defined for a cluster even if it's already installed. This also allows us to ensure that the image the user specified in the ClusterImageSet as the release image to be installed. …
> [release-ocm-2.12] MGMT-19158: Always try to cache the ClusterImageSet

- .tekton/assisted-service-rhel8-mce-downstream-2-13-pull-request.yaml
- .tekton/assisted-service-rhel8-mce-downstream-2-13-push.yaml
- .tekton/assisted-service-rhel8-mce-downstream-main-pull-request.yaml
- .tekton/assisted-service-rhel8-mce-downstream-main-push.yaml
- .tekton/assisted-service-rhel9-mce-downstream-2-13-pull-request.yaml
- .tekton/assisted-service-rhel9-mce-downstream-2-13-push.yaml
- .tekton/assisted-service-rhel9-mce-downstream-main-pull-request.yaml
- .tekton/assisted-service-rhel9-mce-downstream-main-push.yaml
- .tekton/assisted-service-saas-main-pull-request.yaml
- .tekton/assisted-service-saas-main-push.yaml
Configure sast-snyk-check in konflux pipelines
Part-of [MGMT-18501](https://issues.redhat.com//browse/MGMT-18501)
> MGMT-18501: Configure sast-snyk-check in konflux pipelines

- internal/versions/api_test.go
As release images are not used in k8s API flow, testing the default ones from data directory is redundant. This PR changes this unit-test to validate only the default OS images by reading and parsing them.
> [release-ocm-2.10] NO-ISSUE: Remove default release images testing for OCM branches

- internal/bminventory/inventory_test.go
> MGMT-19601: Add tests for static networking in inventory_test

- internal/common/test_configuration.go
- internal/ignition/discovery_test.go
- openshift/template.yaml
- pkg/staticnetworkconfig/backward_compatibility.go
- subsystem/infra_env_test.go
> MGMT-19582: Enable static networking with nmstate service flow in 4.18

- internal/host/validations_test.go
- internal/host/validator.go
> MGMT-19626: Skip MTU validation for Day 2

- internal/hardware/validator.go
- internal/hardware/validator_test.go
> MGMT-19631: Enable FC on x86_64

- Dockerfile.assisted-service-rhel9-mce
Currently our base image use ubi9 and MintMaker wants to upgrade it to 9.5, because MintMaker looks at the repo and tries to upgrade to the newest tag.
This changes the base image to use a repo that is just for rhel9.4.
Part-of [MGMT-19381](https://issues.redhat.com//browse/MGMT-19381)
> MGMT-19381: Change downstream base image to rhel9.4 instead of ubi9

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
> NO-ISSUE: Fix typos

- .tekton/assisted-service-rhel8-mce-downstream-2-13-pull-request.yaml
- .tekton/assisted-service-rhel8-mce-downstream-2-13-push.yaml
- .tekton/assisted-service-rhel8-mce-downstream-main-pull-request.yaml
- .tekton/assisted-service-rhel8-mce-downstream-main-push.yaml
- .tekton/assisted-service-rhel9-mce-downstream-2-13-pull-request.yaml
- .tekton/assisted-service-rhel9-mce-downstream-2-13-push.yaml
- .tekton/assisted-service-rhel9-mce-downstream-main-pull-request.yaml
- .tekton/assisted-service-rhel9-mce-downstream-main-push.yaml
- .tekton/assisted-service-saas-main-pull-request.yaml
- .tekton/assisted-service-saas-main-push.yaml
In our konflux build pipelines, there is a task to check snyk to warn us on potential code vulnerabilities.
However there are some issues it find that we don't care about, so we need to add the problematic files as a list for snyk to ignore.
Part-of [MGMT-19748](https://issues.redhat.com//browse/MGMT-19748)
> MGMT-19748: Configure snyk ignore

- .tekton/assisted-service-rhel8-mce-downstream-2-13-pull-request.yaml
- .tekton/assisted-service-rhel8-mce-downstream-2-13-push.yaml
- .tekton/assisted-service-rhel8-mce-downstream-main-pull-request.yaml
- .tekton/assisted-service-rhel8-mce-downstream-main-push.yaml
- .tekton/assisted-service-rhel9-mce-downstream-2-13-pull-request.yaml
- .tekton/assisted-service-rhel9-mce-downstream-2-13-push.yaml
- .tekton/assisted-service-rhel9-mce-downstream-main-pull-request.yaml
- .tekton/assisted-service-rhel9-mce-downstream-main-push.yaml
- .tekton/assisted-service-saas-main-pull-request.yaml
- .tekton/assisted-service-saas-main-push.yaml
The current buildah images in the tekton pipelines accidentally create the SBOM with CycloneDX 1.6 which causes a violation in the ECP check.
These new images set the CycloneDX to 1.5 as the ECP check expects.
> NO-ISSUE: Update buildah image to fix a bug with SBOM

- go.mod
- go.sum
- vendor/github.com/moby/moby/AUTHORS
- vendor/github.com/moby/moby/pkg/ioutils/fswriters.go
- vendor/modules.txt
CVE-2024-36620 is impacted to moby v25.0.0 - v26.0.2. Updating moby to 27.2.1 as the fix is already in 4.18 branch.
> OCPBUGS-48390: Bump moby from v26.0.0 to v27.2.1

- deploy/operator/capi/deploy_capi_cluster.sh
There have been recent registry mismatches for
disconnected CAPI jobs due to how the mirror
registry is calculated in Hypershift.
This switches all the references so that they
are all in the same repository and cleans up the
script for CAPI jobs so it's more clear what is
required for disconnected.
/cc @danmanor @gamli75
> MGMT-19358: Switch mirror registry references for disconnected CAPI script

- openshift/template.yaml
All SaaS deployments in app-sre should have a CPU / memory limits / requests as specified in:
- https://issues.redhat.com/browse/MGMT-19651
- https://issues.redhat.com/browse/MGMT-19652
- https://issues.redhat.com/browse/MGMT-19654
- https://issues.redhat.com/browse/MGMT-19655
This PR adds these CPU limit for assisted-service envoy container. 
We want to set the highest limit which doesn't exceed the node capabilities in order to avoid unnecessary throttling.  …
> NO-ISSUE: Set CPU Limit for envoy

- .tekton/assisted-service-rhel8-acm-ds-2-13-pull-request.yaml
- .tekton/assisted-service-rhel8-acm-ds-2-13-push.yaml
- .tekton/assisted-service-rhel8-acm-ds-main-pull-request.yaml
- .tekton/assisted-service-rhel8-acm-ds-main-push.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-13-pull-request.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-13-push.yaml
- .tekton/assisted-service-rhel9-acm-ds-main-pull-request.yaml
- .tekton/assisted-service-rhel9-acm-ds-main-push.yaml
In order to simplify the release process in konflux for our product, we want related components to share a single application. To make that change as simple as possible, this PR changes the existing pipelines to point to the new components while keeping everything we already configured.
Part-of [MGMT-19815](https://issues.redhat.com//browse/MGMT-19815)
> MGMT-19815: Update tekton pipelines to point to new components

- api/vendor/github.com/openshift/assisted-service/models/bundle.go
- client/vendor/github.com/openshift/assisted-service/models/bundle.go
- internal/operators/authorino/authorino_operator.go
- internal/operators/common/common.go
- internal/operators/manager.go
- internal/operators/manager_test.go
- internal/operators/nvidiagpu/nvidia_gpu_operator.go
- internal/operators/odf/odf_operator.go
- internal/operators/openshiftai/openshift_ai_operator.go
- internal/operators/pipelines/pipelines_operator.go
- internal/operators/serverless/serverless_operator.go
- internal/operators/servicemesh/servicemesh_operator.go
- models/bundle.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/bundle.go
This patch adds a new `description` field to the object that describes an operator bundle.
```
GET /api/assisted-install/v2/operators/bundles",
[
{
"description": "Virtualization",
"name": "virtualization",
"operators": [
"odf",
"mtv",
"nmstate",
"cnv"
]
},
{
"description": "OpenShift AI with NVIDIA GPUs",
"name": "openshift-ai-nvidia",
"operators": [
"pipelines",
"servicemesh",
"openshift-ai",
"nvidia-gpu",
"serverless",
"odf",
"authorino"
]
}
]
```
https://issues.redhat.com/browse/MGMT-19860
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-me …
> MGMT-19860: Add descriptions to operator bundles

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/ignition/ignition.go
Manual cherry-pick of https://github.com/openshift/assisted-service/pull/7254 to release-ocm-2.10
> [ACM 2.10] MGMT-19857: Validate the internal ignition override (#7254)

- docs/user-guide/mirror_registry_guide.md
Fixes of https://github.com/openshift/assisted-service/pull/7259
/cc @CrystalChun
> MGMT-19847: Move version matching comment to Mirror OpenShift Release Images section

- internal/controller/controllers/agent_controller.go
- internal/controller/controllers/agent_controller_test.go
Manual cherry pick of PRs:
https://github.com/openshift/assisted-service/pull/7064 [MGMT-19413](https://issues.redhat.com//browse/MGMT-19413): Add validations info to the Agents annotations
https://github.com/openshift/assisted-service/pull/7063 [MGMT-19414](https://issues.redhat.com//browse/MGMT-19414): Add default requeue time when Hosts are created from Agents
> [release-ocm-2.12] MGMT-19413: Add validations info to the Agents annotations

- internal/ignition/installmanifests.go
- internal/ignition/installmanifests_test.go
When installing to the existing root filesystem the host finishes install with twice the data in the /sysroot and /boot filesystems as it should have.
For /sysroot this isn't much of a problem, but /boot ends up getting to ~96% utilized during upgrades with the extra kernel and initrd in there.
To handle this a script and a oneshot service to run it is added to the host pointer ignition when the host is being installed to an existing root. This script undeploys the boot entry which removes the files from /boot and removes the stateroot from /sysroot. This service only runs on the first boot of the machine.
Resolves https://issues.redhat.com/browse/MGMT-19106
Deployed a host using the existing root install method with these changes and could see successful execution of the service after …
> MGMT-19106: Remove discovery stateroot when installing to existing root

- pkg/validations/validations.go
- pkg/validations/validations_test.go
This is not allowed by ignition and will prevent the host from booting properly. Because of this it should be disallowed at the API level.
A host with a duplicate in the no_proxy setting will fail to boot with the following error:
If the host was being used with BMO integration we would fail to merge the ironic agent ignition and log an error like:
```
2025-01-30T06:03:50.792850861Z time="2025-01-30T06:03:50Z" level=error msg="Failed to format ignition config" func="github.com/openshift/assisted-service/internal/bminventory.(*bareMetalInventory).V2DownloadInfraEnvFiles" file="/remote-source/assisted-service/app/internal/bminventory/inventory.go:5902" error="error parsing ignition: config is not valid" pkg=Inventory
```
Resolves https://issues.redhat.com/browse/MGMT-19844
Unit tests for …
> MGMT-19844: Validate that no_proxy does not contain duplicate entries

- .tekton/assisted-service-rhel8-acm-ds-2-14-pull-request.yaml
- .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-14-pull-request.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
Now downstream images are built with Kofnflux, therefore we  change the references in the master branch to ocm-2.14.
> MGMT-19950: Modify Konflux YAMLs to ocm-2.14

- docs/dev/disk-image-install.md
Resolves https://issues.redhat.com/browse/MGMT-19928
> MGMT-19928: Add dev doc for disk image install

- Dockerfile.assisted-service
> [release-ocm-2.12] MGMT-19819: Add the commit reference from which the image is built to  the image

- Dockerfile.assisted-service
> [release-ocm-2.9] MGMT-19819: Add the commit reference from which the image is built to  the image

- internal/ignition/discovery_test.go
- internal/installcfg/builder/builder_test.go
Add 2 tests to verify that this feature is working as expected:
- Test on builder_test.go: check that the install config is setting ImageDigestSet as expected
- Test on discovery_test.go: check that the registries.conf in the ignition file set the file content as expected
/cc @gamli75 @CrystalChun
> MGMT-20080: Add unitests to check mirroring priority

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
Previously the coreos image would only be added to the install command for clusters that were initally being installed, this was a mistake, this install method should also be available when adding additional nodes to a cluster
Resovles https://issues.redhat.com/browse/MGMT-19939
Manually tested by deploying an SNO and adding a new node using the "install to existing root" method.
> MGMT-19939: Allow using the rootfs install method to add nodes

- .tekton/assisted-service-saas-hotfix-pull-request.yaml
- .tekton/assisted-service-saas-hotfix-push.yaml
> NO-ISSUE: Update konflux pipeline

- go.mod
- go.sum
- vendor/github.com/moby/moby/AUTHORS
- vendor/github.com/moby/moby/pkg/ioutils/fswriters.go
- vendor/modules.txt
> OCPBUGS-45244: Bump moby from v26.0.0 to v27.2.1

- docs/user-guide/finalization_stages_timeouts.md
- internal/cluster/finalizing_stages.go
In large cluster installations, some powerful worker hosts may take a long time to reboot. Currently, the controller waits for 10 minutes in the last stage of finalizing before timing out. In certain cases, this timeout is not sufficient, causing the installation process to fail prematurely.
This PR increases the timeout for the last finalizing stage to allow more time for worker nodes to complete their reboots before the cluster transitions to the "installed" state.
Additionally, this PR includes documentation explaining the timeout values for different finalization stages to improve clarity and maintainability.
[Kubernetes …
> MGMT-19832: Fix time out during cluster last finalizing stage

- subsystem/kubeapi/kubeapi_test.go
Some tests were not being run until a bug in the overall testing approach was resolved. After this was resolved, it was discovered that some of the tests did not run ever and were broken.
This PR is to fix most of those tests.
With the exception of Preprovisioning tests which will require an alternative approach.
> MGMT-19596: Fixing broken KubeAPI tests

- .tekton/assisted-service-rhel8-acm-ds-2-14-pull-request.yaml
- .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-14-pull-request.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
> NO-ISSUE: Fix Konflux configuration for ocm-2.14

- internal/host/hostcommands/install_cmd.go
The recent change in https://github.com/openshift/assisted-service/pull/7325 calls get release image when installing a host regardless if it's day-2 or not.
In the Hypershift/CAPI case, the hosts are added as day-2 hosts to clusters and they did not previously need a release image to be installed. They also do not have the openshift version defined in the cluster, and calling get release image will cause the installation of the host to fail.
This adds an extra check to prevent the installation failure caused by calling get release image during day-2 host installation when installing to disk is not required.
[Kubernetes …
> NO-ISSUE: Modify condition to get release image when installing hosts

- go.mod
- go.sum
- vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
- vendor/github.com/go-jose/go-jose/v4/README.md
- vendor/github.com/go-jose/go-jose/v4/jwe.go
- vendor/github.com/go-jose/go-jose/v4/jwk.go
- vendor/github.com/go-jose/go-jose/v4/jws.go
- vendor/github.com/stretchr/testify/assert/assertion_compare.go
- vendor/github.com/stretchr/testify/assert/assertion_format.go
- vendor/github.com/stretchr/testify/assert/assertion_forward.go
- vendor/github.com/stretchr/testify/assert/assertion_order.go
- vendor/github.com/stretchr/testify/assert/assertions.go
- vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
- vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
- vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
- vendor/github.com/stretchr/testify/mock/mock.go
- vendor/modules.txt
[ACM-18075](https://issues.redhat.com//browse/ACM-18075): CVE-2025-27144 Bump github.com/go-jose/go-jose to v4.0.5
https://issues.redhat.com/browse/ACM-18075
> [release-ocm-2.12] ACM-18075: CVE-2025-27144 Bump github.com/go-jose/go-jose to v4.0.5

- .tekton/assisted-service-rhel8-acm-ds-2-13-pull-request.yaml
- .tekton/assisted-service-rhel8-acm-ds-2-13-push.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-13-pull-request.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-13-push.yaml
Tasks will become mandatory the 1st of April
> [release-ocm-2.13] MGMT-20149: Add required sast tasks for Konflux

- OWNERS_ALIASES
Eran has left Assisted Installer team
> [release-ocm-2.13] NO-ISSUE: Remove eran ifrach account from OWNERS

- .tekton/assisted-service-rhel8-acm-ds-2-14-pull-request.yaml
- .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
- .tekton/assisted-service-rhel8-acm-ds-main-pull-request.yaml
- .tekton/assisted-service-rhel8-acm-ds-main-push.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-14-pull-request.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
- .tekton/assisted-service-rhel9-acm-ds-main-pull-request.yaml
- .tekton/assisted-service-rhel9-acm-ds-main-push.yaml
- .tekton/assisted-service-saas-main-pull-request.yaml
- .tekton/assisted-service-saas-main-push.yaml
Tasks will become mandatory the 1st of April
> MGMT-20149: Add required sast tasks for Konflux

- internal/bminventory/inventory.go
- internal/cluster/cluster.go
This adds the ability for ABI, via the OVE UI, to generate a kubeconfig when the cluster is in the ready state. Instead of adding a new endpoint to allow the UI to generate the kubeconfig, the enviroment variable - EPHEMERAL_INSTALLER_CLUSTER_TLS_CERTS_OVERRIDE_DIR - which is specific to ABI, is used. If no TLS certs have been added to the override it indicates that the certs, and the kubeconfig, should be generated. The kubeconfig can then be retrieved in the ready or preparing-for-installation states.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md …
> AGENT-538: Add ability for ABI UI to generate kubeconfig

- docs/dev/olm-operator-plugins.md
> NO-ISSUE: Update adding OLM operators doc

- internal/common/common.go
- internal/common/common_test.go
- internal/controller/controllers/agentserviceconfig_controller.go
In some scenarios in which the `user-ca-bundle` includes superfluous certificates, the `assisted-trusted-ca-bundle` ConfigMap could include duplicate certificates.
To mitigate this issue, added logic for removing such duplicates when creating the CM.
> MGMT-20032: handle duplicates in CA bundle

- go.mod
- go.sum
- vendor/github.com/golang-jwt/jwt/v4/parser.go
- vendor/modules.txt
https://issues.redhat.com/browse/OCPBUGS-54378
> [master] OCPBUGS-54378: Bump go-jwt to 4.5.2 to fix CVE-30204

- go.mod
- go.sum
- vendor/github.com/golang-jwt/jwt/v4/parser.go
- vendor/modules.txt
https://issues.redhat.com/browse/ACM-19195
> [release-ocm-2.12] ACM-19195: Bump go-jwt to 4.5.2 to fix CVE-30204

- go.mod
- go.sum
- vendor/github.com/golang-jwt/jwt/v4/parser.go
- vendor/modules.txt
https://issues.redhat.com/browse/ACM-19191
> [release-ocm-2.10] ACM-19191: Bump go-jwt to 4.5.2 to fix CVE-30204

- go.mod
- go.sum
- vendor/github.com/golang-jwt/jwt/v4/parser.go
- vendor/modules.txt
https://issues.redhat.com/browse/ACM-19192
> [release-ocm-2.9] ACM-19192: Bump go-jwt to 4.5.2 to fix CVE-30204

- go.mod
- go.sum
- vendor/github.com/golang-jwt/jwt/v4/parser.go
- vendor/modules.txt
https://issues.redhat.com/browse/ACM-19194
> [release-ocm-2.11] ACM-19194: Bump go-jwt to 4.5.2 to fix CVE-30204

- go.mod
- go.sum
- vendor/github.com/golang-jwt/jwt/v4/parser.go
- vendor/modules.txt
https://issues.redhat.com/browse/ACM-19193
> [release-ocm-2.13] ACM-19193: CVE-30204 Bump go-jwt to 4.5.2 to fix CVE-30204

- internal/hardware/validator.go
- internal/hardware/validator_test.go
> MGMT-19970: Improve iSCSI host IP validation error handling

- go.mod
- go.sum
- vendor/github.com/golang-jwt/jwt/v4/parser.go
- vendor/modules.txt
https://issues.redhat.com/browse/OCPBUGS-54402
> [release-4.17] OCPBUGS-54402: Bump go-jwt to 4.5.2 to fix CVE-30204

- internal/controller/controllers/bmh_agent_controller.go
On this PR:
- Replace deprecated method `OnPodDeletedOrEvicted` with `OnPodDeletionOrEvictionFinished` and log the new error message.
- Add timeout to the log message on drain failure.
/cc @gamli75 @carbonin
> NO-ISSUE: Update eviction/deletetion logging on failure

- go.mod
- go.sum
- vendor/github.com/golang-jwt/jwt/v4/parser.go
- vendor/github.com/golang-jwt/jwt/v4/token.go
- vendor/modules.txt
> OCPBUGS-53691: Bump jwt to 4.5.2 in release-4.14

- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
Change - [MGMT-20302](https://issues.redhat.com//browse/MGMT-20302): Remove root=/dev/disk/by-label/dm-mpath-root from kargs added when installation disk is multipath iSCSI (#7507)
> [cloud-hotfix-releases] MGMT-20302: Prepare v2.39.2

- README.md
> [release-ocm-2.13] NO-ISSUE: No-op to push to ACM

- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
adding commit - `3e1724cbabdf0e1a48ad7ba46c1f2c82898272b0` ([MGMT-20245](https://issues.redhat.com//browse/MGMT-20245))
> [cloud_hotfix_releases] NO-ISSUE: Prepare v2.39.3

- .tekton/assisted-service-saas-hotfix-pull-request.yaml
- .tekton/assisted-service-saas-hotfix-push.yaml
> NO-ISSUE: Update tekton pipeline

- internal/featuresupport/common.go
- internal/featuresupport/feature_support_test.go
- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
commits:
1. 3e1724cbabdf0e1a48ad7ba46c1f2c82898272b0
2. fc095f461c2136434824a6453e30f88b4af46007
> [cloud_hotfix_releases] NO-ISSUE: Prepare version v2.38.3

- internal/host/hostutil/host_utils.go
- internal/host/hostutil/update_host.go
- internal/host/transition.go
Truncate statusInfo if it's too long
> NO-ISSUE: Truncate statusInfo if it's too long

- internal/hardware/validator.go
- internal/hardware/validator_test.go
When updating inventory with iSCSI disks, validation was not purging all service-side error messages before re-running validation, resulting in duplicate error messages in NotEligibleReasons.
Added missing error message templates to diskEligibilityMatchers and standardized all matchers to use compileDiskReasonTemplate for consistency.
In the unit tests, added errors to verify that they are successfully captured. In the test-infra, triggered the error to confirm that the messages are no longer duplicated.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.m …
> MGMT-19968: Fix duplicate error messages in disk eligibility validation

- internal/featuresupport/feature_support_config.go
- internal/featuresupport/features_olm_operators.go
- internal/featuresupport/features_olm_operators_test.go
- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
- openshift/template.yaml
- https://github.com/openshift/assisted-service/pull/7543
- https://github.com/openshift/assisted-service/pull/7572
> [cloud_hotfix_releases] Prepare v2.39.3

- internal/controller/controllers/agent_controller.go
Setting agent annotation with the current stage incorrectly replaced the updated condition.
> NO-ISSUE: Small fix updating agent annotation

- .tekton/assisted-service-saas-hotfix-pull-request.yaml
- .tekton/assisted-service-saas-hotfix-push.yaml
> NO-ISSUE: Apply konflux migration

- .tekton/assisted-service-saas-hotfix-pull-request.yaml
- .tekton/assisted-service-saas-hotfix-push.yaml
> NO-ISSUE: Update konflux references and apply migration

- api/vendor/github.com/openshift/assisted-service/models/cluster.go
- api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
- api/vendor/github.com/openshift/assisted-service/models/disk_encryption.go
- api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
- client/vendor/github.com/openshift/assisted-service/models/cluster.go
- client/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
- client/vendor/github.com/openshift/assisted-service/models/disk_encryption.go
- client/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
- internal/hardware/validator.go
- internal/host/hostutil/host_utils.go
- internal/host/hostutil/host_utils_test.go
- internal/installcfg/builder/builder.go
- internal/installcfg/builder/builder_test.go
- internal/network/manifests_generator.go
- internal/network/manifests_generator_test.go
- models/cluster.go
- models/cluster_create_params.go
- models/disk_encryption.go
- models/v2_cluster_update_params.go
- restapi/embedded_spec.go
- swagger.yaml
- vendor/github.com/openshift/assisted-service/models/cluster.go
- vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
- vendor/github.com/openshift/assisted-service/models/disk_encryption.go
- vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
As part of adding support for TNA cluster in assisted-service, we need to allow setting hyperthreading and disk encryption for arbiter hosts.
Closes [MGMT-20468](https://issues.redhat.com//browse/MGMT-20468)
> MGMT-20468: Add arbiter to cluster's hyperthreading and disk encryption enums

- docs/enhancements/cancel-day-2-host-installation.md
> MGMT-20228: Enhancement to allow cancelling day-2 host's installation

- internal/host/hostcommands/install_cmd.go
- internal/host/hostcommands/install_cmd_test.go
This PR is following - https://github.com/openshift/assisted-installer/pull/1117. by enabling skip MCO reboot for day2 hosts
> MGMT-20567: Enable skip MCO reboot for day2 hosts

- internal/bminventory/inventory.go
- internal/bminventory/inventory_test.go
- internal/versions/api.go
- internal/versions/api_test.go
- pkg/ocm/utils.go
- subsystem/authz_test.go
- subsystem/utils_test/wiremock_stubs.go
- subsystem/versions_test.go
The multi-arch capability was previously used to allow specific organizations to deploy multi-architecture images. This is no longer needed since 'bare_metal_installer_multiarch' is now set to 'true' for all environments (see: https://gitlab.cee.redhat.com/service/ocm-resources/-/blob/master/data/uhc-production/default_capability/default_capabilities.yaml).
> MGMT-14821: Remove multi-arch capability

- openshift/template.yaml
When we'll want to enable TNA_CLUSTERS_SUPPORT in SaaS, we'll need to be able to set this environment variable to true using the template. For now keep it will keep the default value of false.
> NO-ISSUE: Allow setting TNA_CLUSTERS_SUPPORT in the template

- internal/controller/controllers/preprovisioningimage_controller.go
- internal/controller/controllers/preprovisioningimage_controller_test.go
Cherry pick of https://github.com/openshift/assisted-service/pull/7660
> MGMT-20366: ironic inspection fails with Networking Connection error 

- internal/controller/controllers/preprovisioningimage_controller.go
- internal/controller/controllers/preprovisioningimage_controller_test.go
Cherry pick of https://github.com/openshift/assisted-service/pull/7660
> MGMT-20366: ironic inspection fails with Networking Connection error

- internal/featuresupport/features_olm_operators.go
> NO-ISSUE: Change NHO, SNR, FAR, Kube Descheduler and Node Maintenance operators support level to 'tech-preview'

- internal/cluster/cluster.go
- internal/cluster/cluster_test.go
> [cloud_hotfix_releases] NO-ISSUE: Prepare release v2.41.1 (with Konflux files)

- internal/operators/nodefeaturediscovery/templates/custom/nodefeaturediscovery.yaml
> [cloud_hotfix_releases] NO-ISSUE: Prepare release v2.41.2

- .tekton/assisted-service-rhel8-acm-ds-2-14-pull-request.yaml
- .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-14-pull-request.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
> ACM-21380: Make ACM builds multi-arch

- .tekton/assisted-service-rhel8-acm-ds-2-13-pull-request.yaml
- .tekton/assisted-service-rhel8-acm-ds-2-13-push.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-13-pull-request.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-13-push.yaml
> MGMT-20858: apply tags migration

- data/default_release_sources.json
> MGMT-20914: Prepare image versions for OCP 4.19 GA

- deploy/operator/setup_lso.sh
> MGMT-20918: Override OCP 4.20 index image for LSO installation

- internal/operators/fenceagentsremediation/fence_agents_remediation_operator.go
- internal/operators/nodehealthcheck/node_healthcheck_operator.go
- internal/operators/selfnoderemediation/self_node_remediation_operator.go
Depend on https://github.com/openshift-assisted/assisted-installer-ui/pull/3014
> MGMT-20893: Remove Remediation operators from virtualization bundle

- api/hiveextension/v1beta1/agentclusterinstall_types.go
- api/hiveextension/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
- config/crd/resources.yaml
- deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
- internal/controller/controllers/clusterdeployments_controller.go
- subsystem/kubeapi/kubeapi_test.go
- vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
- vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
We've already updated the REST-API to allow setting hyperthreading and disk encryption configurations for arbiter nodes, so we now need to also add that to the kube-api.
Closes [MGMT-20988](https://issues.redhat.com//browse/MGMT-20988)
> MGMT-20988: Add arbiter to cluster's hyperthreading and disk encryption in kube-api

- .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
> NO-ISSUE: Add slack notification when merge pipeline failed

- go.mod
- go.sum
- vendor/github.com/golang/glog/glog.go
- vendor/github.com/golang/glog/glog_file.go
- vendor/github.com/golang/glog/glog_file_nonwindows.go
- vendor/github.com/golang/glog/glog_file_windows.go
- vendor/github.com/golang/glog/internal/logsink/logsink.go
- vendor/modules.txt
> OCPBUGS-59300: Bump glog to v1.2.5

- Dockerfile.assisted-service-build
- ci-images/Dockerfile.lint
> [release-ocm-2.14] NO-ISSUE: Remove redundant shellcheck image

- Dockerfile.assisted-service-build
- ci-images/Dockerfile.lint
> [release-ocm-2.10] NO-ISSUE: Remove redundant shellcheck image

- rpm-prefetching/assisted-service-rhel8/rpms.lock.yaml
- rpm-prefetching/assisted-service-rhel9/rpms.lock.yaml
> NO-ISSUE: Fix hermetic build for acm (rhel8)

- go.mod
- go.sum
- vendor/github.com/golang/glog/glog.go
- vendor/github.com/golang/glog/glog_file.go
- vendor/github.com/golang/glog/glog_file_nonwindows.go
- vendor/github.com/golang/glog/glog_file_windows.go
- vendor/github.com/golang/glog/internal/logsink/logsink.go
- vendor/modules.txt
> OCPBUGS-58640,OCPBUGS-58635: Bump glog to v1.2.5 in release-4.18

- internal/operators/nodehealthcheck/node_healthcheck_operator.go
> MGMT-21287: Remove NHO dependency in SNR

- internal/controller/controllers/agentserviceconfig_controller.go
Manual backport of https://github.com/openshift/assisted-service/pull/7788
> [release-ocm-2.11] MGMT-21328: Increase the timeout for host stage - 'waiting for control plane' for operator deployments

- go.mod
- go.sum
- vendor/github.com/golang/glog/glog.go
- vendor/github.com/golang/glog/glog_file.go
- vendor/github.com/golang/glog/glog_file_nonwindows.go
- vendor/github.com/golang/glog/glog_file_windows.go
- vendor/github.com/golang/glog/internal/logsink/logsink.go
- vendor/modules.txt
> OCPBUGS-58634,OCPBUGS-58639: Bump glog to v1.2.5 in release-4.17

- .tekton/assisted-service-saas-v2-45-pull-request.yaml
- .tekton/assisted-service-saas-v2-45-push.yaml
> NO-ISSUE: Add tekton pipeline for 2.45

- docs/enhancements/disconnected-iso-ignition-generation.md
https://issues.redhat.com/browse/MGMT-20830 enhancement doc
> MGMT-20830:Support for serving an OVE image (ISO) with an embedded custom ignition - enhancement doc

- docs/hive-integration/crds/nmstate.yaml
The error occurred because there were two conflicting default routes (0.0.0.0/0) both pointing to the same interface (eth1) but with different next-hop addresses:
- Route 1: 192.168.126.1 via eth1
- Route 2: 192.168.140.1 via eth1 This created a conflict because nmstate couldn't determine which route to use for the default gateway.
The change fixes the issue by:
- Changing the first route to use eth0 instead of eth1, which makes sense since eth0 has the IP address 192.168.126.30 that corresponds to the 192.168.126.1 gateway.
- Adding a metric value: Added metric: 100 to the second route to establish a clear priority order, making it a backup route.
Found and fixed with Cursor
Likely caused by this change in nmstate:
https://github.com/nmstate/nmstate/commit/48b139c87f9d9b2f248e27e6b8aa964b …
> MGMT-21701: Fix the nmstate example

- Dockerfile.assisted-service-build
- ci-images/Dockerfile.base
> NO-ISSUE: pin gotestsum to v1.12.3

- internal/host/hostutil/host_utils.go
- internal/host/hostutil/host_utils_test.go
See commit message
closes: https://issues.redhat.com/browse/MGMT-21419
> MGMT-21419: fix assisted ZTP day 2 workers jobs

- .tekton/assisted-service-rhel8-acm-ds-2-11-pull-request.yaml
- .tekton/assisted-service-rhel8-acm-ds-2-11-push.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-11-pull-request.yaml
- .tekton/assisted-service-rhel9-acm-ds-2-11-push.yaml
- Dockerfile.assisted-service-rhel8-mce
- Dockerfile.assisted-service-rhel9-mce
- rpm-prefetching/README.md
- rpm-prefetching/assisted-service-rhel8/rpms.in.yaml
- rpm-prefetching/assisted-service-rhel8/rpms.lock.yaml
- rpm-prefetching/assisted-service-rhel9/rpms.in.yaml
- rpm-prefetching/assisted-service-rhel9/rpms.lock.yaml
Configure konflux pipelines for ACM 2.11
> NO-ISSUE: Configure konflux pipelines for ACM 2.11

- Dockerfile.assisted-service-build
- ci-images/Dockerfile.code-generation
- ci-images/Dockerfile.subsystem
Update kustomize to v5.7.1 to match our automation
> NO-ISSUE: Update kustomize to v5.7.1
