openshift/assisted-service

internal/events/api/event.go
internal/events/api/mock_event.go
internal/events/event.go
internal/events/event_test.go
internal/host/host.go
internal/host/host_test.go
internal/metrics/metricsManager.go
internal/metrics/metricsManager_test.go

When agent fails to upgrade the generated events will be generated each
time that the agent asks for next steps, approxy once per minute. This
can fill the collection of events with useless repeated information. To
avoid that this patch changes the event handling so that it will be
possible to define a minimum distance (in time) between those events.
Events that are closer than that minimum distance will be discarded.
Related: https://issues.redhat.com/browse/MGMT-12237 …

MGMT-12237: Limit upgrade agent events

---

internal/installcfg/builder/builder.go
internal/installcfg/builder/builder_test.go
internal/oc/release.go
internal/oc/release_test.go
pkg/mirrorregistries/generator.go
pkg/mirrorregistries/generator_test.go

This is a cherry-pick of https://github.com/openshift/assisted-service/pull/4745
extractLocationMirrorDataFromRegistries had a bug that just picked the first mirror for each sources.
as long the mirror registry was created using `oc adm release mirror` this wasn't an issue since each source had a single mirror.
For some time now customers use `oc-mirror` for creating the mirror registry, `oc-mirror` create few mirrors for a single source and thus triggers the bug in the title.
https://issues.redhat.com/browse/MGMT-12866
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide …

[release-ocm-2.6] MGMT-12866: Assisted Spoke install-config does not generate icsp with multiple mirror to entries

---

internal/cluster/cluster.go
internal/cluster/cluster_test.go

This PR extends the cluster monitoring loop for scenarios where a cluster is using dual-stack and has dual-stack VIPs configured. In this case we will use available hosts' inventory in order to calculate both Machine Networks based on the VIPs configured.
This extends the current flow in which we only ever use the first pair of VIPs to calculate machine networks. In the current flow it can also happen that by mistake we remove the 2nd machine network for a dual-stack cluster manually configured. This is a bug that we are fixing with this change.
Contributes-to: [MGMT-12366](https://issues.redhat.com//browse/MGMT-12366)
/cc @nmagnezi 
/cc @omertuc

MGMT-12366: Automatically calculate 2nd Machine Network from 2nd VIP

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/mock_installer_internal.go
internal/controller/controllers/agent_controller.go
internal/host/host.go

[MGMT-12445](https://issues.redhat.com/browse/MGMT-12445)
When a host updates its install progress from an invalid state, the service
would initially respond with a 500 internal server error. This caused a lot
of noise that made it seem as if the service was down, when it wasn't.
This PR modifies the response to send a 409 conflict when updating
a host's install progress fails when updating the host from an invalid state.
Additionally, it modifies the error response sent to be the appropriate
code depending on the error that occurred.
1. Deploy assisted-service with these changes
2. Install a cluster using assisted-test-infra and let it timeout (fail), ensure the hosts have reached an error state
3. Call the update host install progress API, ensure it's a 409 error returned with the …

MGMT-12445: Update host install progress response

---

internal/controller/controllers/clusterdeployments_controller.go

Currently, during reconciliation of `clusterdeployments` , if function `updateNetworkParams` returns an error, it is failed to update the `network_type` because it encountered malformed openshift version, and we handle that error by failing the cluster's update (returning nil, err). We want to let the update process continue in that case.

NO-ISSUE: Changing the way we handle an error from 'updateNetworkParams' from returning 'nil, err' to 'cluster, err'

---

internal/host/monitor.go
internal/operators/cnv/cnv_operator.go

[MGMT-12971](https://issues.redhat.com//browse/MGMT-12971): remove 4.12.0.0-0 as openshift hardcoded version in host monitor loop monitor loop
Removing hardcoded openshift version in host monitor that was set for cnv operator, in case version is not set cnv will return lso

MGMT-12971: remove 4.12.0.0-0 as openshift hardcoded version in host monitor loop

---

internal/host/common.go
internal/host/refresh_status_preprocessor.go
internal/host/validations_test.go

Currently the agent compatibility validation is always enabled, even when the cluster is installing. If the service is restarted in the middle of the installation with a different version of the agent (with a different value for the `AGENT_DOCKER_IMAGE`) that results in warning event explaining that the agent isn't compatible with the service. That has no effect because the service will not be sending the upgrade agent step to the server, but it is confusing. This patch changes the service so that the validation is disabled when the cluster is installing.
Related: https://issues.redhat.com/browse/MGMT-12950
[Kubernetes …

MGMT-12950: Disable compatible agent validation while installing

---

deploy/operator/setup_assisted_operator.sh
docs/operator.md
internal/controller/controllers/agentserviceconfig_controller_test.go
pkg/mirrorregistries/generator_test.go

Docs update, now that we use upstream oc with its ICSP support we can document the default ICSP configuration (no need to mirror tags, mirror by digest should suffice).
-->
https://issues.redhat.com/browse/MGMT-12911 …

MGMT-12911: Update assisted service operator docs with new icsp behavior

---

internal/versions/api.go
internal/versions/api_test.go

For OCP 4.12 and later the CVO does not anymore return version suffixed with `-multi`. However for the Assisted UI we want to distinguish between single- and multi-arch release images. In order not to require any manual implementation of this, we leverage the Supported Versions API call to automatically append the `-multi` suffix for any image that is multi-arch.
Fixes: [MGMT-12978](https://issues.redhat.com//browse/MGMT-12978)

MGMT-12978: Append -multi suffix to multi-arch images in SupportedVersions

---

internal/bminventory/inventory.go
internal/cluster/validations/validation_test.go
internal/cluster/validations/validations.go

[MGMT-12755](https://issues.redhat.com/browse/MGMT-12755)
Cluster names containing periods "." are not allowed
by the openshift installer when using a platform that's
not the None platform.
This prevents a cluster name from passing the validation
if it contains any periods and if it's not the None platform.
```
Failed to registered cluster
```

MGMT-12755: Disallow periods in cluster name

---

openshift/template.yaml

Add emptyDir mount for cache directory. This way when the container is restarted we will cleanup immediately (as opposed to writing to a container layer).
Also implement resource policy for ephemeral-storage
Tried ephemeral-storage policy in integration deployment

MGMT-13036: add emptyDir mount for filesystem cache and ephemeral-storage policy

---

ci-images/Dockerfile.base

git was updated in centos 9 stream repository and now checks if the owner of the files on the filesystem match the current user.
This change disable the check because Prow runs jobs with a random user.

MGMT-13038: Git fails to trust git repository because of mismatch with files

---

internal/cluster/validations/validations.go

This PR adds an ability for network validation functions to access the HA mode of the cluster. This will be useful when those validations will have a different logic depending on whether the cluster is SNO or multi-node.
/cc @nmagnezi

NO-ISSUE: Pass HA mode of the cluster to network validations

---

internal/ignition/dummy.go
subsystem/cluster_test.go

When installing a cluster, we generate the install-config file with values specified in the cluster struct.
This change is adding some basic validations for the content of install-config.yaml.
I.e. added to subsystem tests a verification for the generated manifest to ensure relevant values are populated properly.

MGMT-11979: verify install-config manifest in subsystem

---

pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go

To support gitops ZTP ArgoCD flow we should allow editing the ACI CR after the installation has finished.
From the perspective of assisted service, this has no meaning, but for the gitops flow on day-2, it is important because they are going to use the edited CR as a template for future actions.

MGMT-12794: allow to edit ACI post install

---

pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go

This reverts commit fd129c6b3e8751bb884fb3ca5b67f6aa50959c1d.
Reverting the PR in order to submit a fix where we allow to change only the controlPlane fields in the ACI instead of all the fields (post install). It will be safer this way.

Revert "MGMT-12794: allow to edit ACI post install (#4836)"

---

internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/common.go
internal/common/test_configuration.go
internal/host/validator.go
internal/network/machine_network_cidr.go
internal/network/utils.go

To enable selecting a recommended CIDR when there are multiple options, we will use the following method:
1. Select the default route(s). Use the Metric field to choose the route with the least cost
2. Check if the gateway IP is part of any known machine CIDR
3. Choose this CIDR as the machine network
The network for the default route will also be selected by the OVN after
rebooting of the bootstrap node regardless of the selection of the user,
so this mechanism informs the user what network is the best to use
routes":[{"destination":"0.0.0.0","family":2,"gateway":"192.168.127.1","interface":"ens3","metric
":100},{"destination":"0.0.0.0","family":2,"gateway":"192.168.145.1","interface":"e
ns4","metric":101},{"destination":"10.88.0.0","family":2,"interface":"cni-podman0"} …

MGMT-6536: select default cidr in SNO based on default route metrics

---

internal/controller/controllers/hypershiftagentserviceconfig_controller.go
internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go

MGMT-12875: fail gracefully when konnectivity is missing

---

pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go

To support gitops ZTP ArgoCD flow we should allow editing the ACI CR after the installation has finished.
The only edit operation that is allowed is changing the provision requirment field.
From the perspective of assisted service, this has no meaning, but for the gitops flow on day-2, it is important because they are going to use the edited CR as a template for future actions.

MGMT-12794: allow to edit ProvisionRequirement post install

---

internal/bminventory/inventory_v2_handlers.go
subsystem/cluster_test.go

When invoking V2GetClusterInstallConfig API (/v2/clusters/{cluster_id}/install-config) the returned config doesn't include network lists (in 'networking' key). I.e. these lists are missing: clusterNetwork/machineNetwork/serviceNetwork.
To resolve this issue, added 'UseEagerLoading' when fetching the cluster in order to include the networks info.

MGMT-13098: add missing networks on V2GetClusterInstallConfig

---

internal/bminventory/inventory_v2_handlers.go

Currently when the user tries to delete a cluster via the API we perform multiple operations, in the following order:
- Delete the cluster from AMS.
- Delete DNS records.
- Delete hosts.
- Delete the cluster itself.
The last operation, deleting the cluster itself, will fail if the cluster is being installed. The result of that is that the cluster will be partially deleted, in particular the hosts will be deleted, and therefore they will try to register again and fail. To avoid that this patch adds a check so that the requests to delete a cluster that is being installed will be rejected before any of those operations.
Related: https://issues.redhat.com/browse/MGMT-13040 …

MGMT-13040: Check cluster state before delete

---

docs/hive-integration/import-installed-cluster.md

The following issue was just merged and while proof reading I found a small typo.
[MGMT-12154](https://issues.redhat.com//browse/MGMT-12154): Updating documentation to make Day 2 import process clearer.
This PR is to fix that small typo, it's just a numbering problem, so I figured we can use NO-ISSUE for this as the change is very small.
No tests needed

NO-ISSUE: Small numbering issue in doc, amendment

---

internal/versions/api_test.go
internal/versions/versions.go
internal/versions/versions_test.go

This PR fixes the behaviour of filtering release images by architecture in case there are multiple images that have exactly the same version as reported by the CVO.
As a consequence, it was no longer possible to correctly handle single- and multi-arch release payloads that correspond to the same OCP version. With this change, we again have ability to support this scenario.
Contributes-to: [MGMT-12978](https://issues.redhat.com//browse/MGMT-12978)
/cc @carbonin

MGMT-12978: Handle multiple images with the same OCP version

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
subsystem/cluster_test.go

Currently when an agent tries to register while the cluster is installing the service will return a 400 response code. As a result the agent will retry the request after one minute. To avoid that this patch changes the response code to 409, which will cause the agent to freeze.
Related: https://issues.redhat.com/browse/MGMT-13132
Manually.

MGMT-13132: Respond with 409 when rejecting registration

---

internal/host/validations_test.go
internal/host/validator.go

In some scenarios, if a host inventory is nil, it is possible for the noIPCollisionsInNetwork host validation to crash with a nil pointer dereference panic. This PR fixes that by adding a check to ensure that the validation should be skipped if the host inventory is nil and adds a unit test for this.
A unit test to cover the problematic case was written, this unit test passes.
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIB …

MGMT-13170: Fix nil pointer dereference in validation if host inventory is nil

---

config/rbac/role.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
docs/hive-integration/README.md
internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go

Previously, when using the converged flow, the service attempted to extract the ironic agent image using the spoke release. This was not ideal for a few reasons:
1. The agent version should match that of the hub ironic service
- While it was likely the agent from the spoke version would be compatible with the hub service it's objectively better for them to actually match.
2. The default image was used for late-binding cases
- This meant that a rather old and seemingly random image was used when the service didn't have a cluster from which to pull a release image
3. It's difficult to communicate to a user what to mirror in disconnected cases
With this change the agent will always match the hub service, the hub agent will be used regardless of late-binding or not, and the user just needs to …

MGMT-12894: Use the hub release image when determining the ironic agent image

---

ci-images/Dockerfile.base
ci-images/Dockerfile.lint
ci-images/Dockerfile.subsystem
internal/cluster/cluster_test.go
internal/cluster/transition_test.go
internal/events/eventstest/events_test_utils.go
internal/host/host_test.go
internal/migrations/20211115162400_modify_events_id_test.go
internal/migrations/20211125182200_change_hosts_pkey_test.go

assisted service is expected to build and run on CentOS8 / RHEL8.
This PR is aligning CI to use that instead of CentOS9.
/cc @osherdp 

MGMT-13081: CI to use CentOS8

---

subsystem/kubeapi_test.go

Broken NMState subsystem test root cause analysis:
The test in question is a negative test: It sends a configuration
file content with a single line: `"foo: bar"` and expects a response.
Response to an invalid config:
`nmstate-1.3.x` used to differ from `nmstate-2.x.x` in response to unknown
keys (`foo`, in this case). The `1.3.x` version response is an empty
configuration, whereas the response coming from `2.x.x` version
is `Unsupported keys found`.
CentOS stream8  recently got a newer NMState version.
It used to deploy `nmstate-1.3.3`, and now it deploys `nmstate-1.4.0`.
Looking[1] at the `nmstate-1.4.0` source code, it shows that the response
to invalid keys has changed to be the same as the `2.x.x` version.
The commit[2] that introduced this change is not a part of the `1.3.3` …

MGMT-13081: Re-enable and fix a negative NNState subsystem test

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

[MGMT-13192](https://issues.redhat.com//browse/MGMT-13192): dualstack SNO cluster fails to complete - getting error
In dual stack installation we should set dhcp,dhcp6 kargs in order to
wait for ipv6 address when node comes after reboot

MGMT-13192: dualstack SNO cluster fails to complete - getting error

---

subsystem/subsystem_suite_test.go

Currently, the openshift version which is used in the the subsystem tests is set to the first version in the payload of an API call that retrieves the supported openshift versions. This API call response is not guaranteed to be ordered in a specific way, which causes nondeterministic subsystem tests. I changed the openshift version to the default one.  

MGMT-12294: Run subsystem with deterministic openshift version

---

docs/enhancements/boot-status-reporter.md

MGMT-11090: Enhancement Doc: Assisted boot-reporter service

---

internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go

This PR makes the network config validation stricter so that single-stack clusters with multiple machine networks are not allowed.
As long as OCP does not allow for remote control plane, such a topology is not correct and AI should prevent it from being used.
Closes: [MGMT-10869](https://issues.redhat.com//browse/MGMT-10869)

MGMT-10869: Forbid multiple machine networks in single-stack clusters

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

This PR changes the logic of setting installation disk ID in the Agent CR so that the backend modifies CR only if user has provided a custom root device hints. This prevents a scenario when empty hints cause setting the Agent's field to the empty value even if the value has been set explicitly by the user.
With this change the behaviour will be as follows
* empty ID in Agent and empty hints - nothing happens
* empty ID in Agent and non-empty hints - autocalculation
* non-empty ID in Agent and empty hints - ID is preserved
* non-empty ID in Agent and non-empty hints - autocalculation
Contributes-to: [MGMT-12655](https://issues.redhat.com//browse/MGMT-12655)

MGMT-12655: Set Agent's installation disk ID only if hints exist

---

api/v1beta1/agent_types.go
config/crd/bases/agent-install.openshift.io_agents.yaml
config/crd/resources.yaml
deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
subsystem/kubeapi_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/agent_types.go

Contributes-to: [MGMT-12655](https://issues.redhat.com//browse/MGMT-12655)

MGMT-12655: Add installation disk ID to Agent's status

---

internal/controller/controllers/clusterdeployments_controller.go

In order to catch cases where changes to the Agent CR affect AgentClusterInstall but they do not go over the AI DB, we are adding a watch over Agents that reference the ACI in subject.
Because it's ClusterDeployment reconciler that in reality modifies the ACI CR, we are placing a watch in the CD CR and not the ACI CR.
Contributes-to: [MGMT-12423](https://issues.redhat.com//browse/MGMT-12423)
/cc @tsorya

MGMT-12423: Watch for Agent changes in ClusterDeployment

---

internal/controller/controllers/clusterdeployments_controller.go
internal/network/utils.go
internal/network/utils_test.go

This PR changes logic of comparing complex VIP structs so that only the value of IP address is compared and not the cluster ID. This is in order to simplify the UpdateCluster logic in the ClusterDeployment controller when we need to decide if the Spec of AgentClusterInstall has been updated.
Previously used reflect.DeepEqual was comparing both IP and ClusterID, whereas the newly introduced comparison function compares slices by comparing only their respective IP fields.

NO-ISSUE: When comparing VIPs, compare only IPs

---

api/vendor/github.com/openshift/assisted-service/models/logs_type.go
docs/events.yaml
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/common/events/events.go
models/logs_type.go
restapi/embedded_spec.go
restapi/operations/installer/v2_download_cluster_logs_parameters.go
restapi/operations/installer/v2_upload_logs_parameters.go
subsystem/cluster_test.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/logs_type.go

Per https://github.com/openshift/assisted-service/pull/4444, add a new log type named: `node-boot`.
This change updates both `V2UploadLogs` and `V2DownloadClusterLogs` to accept the new log type.
In addition:
1. A new event was added: `host_boot_logs_uploaded`.
2. Defined download name: `<cluster_name>_<host_role>_boot_<host_id>.tar.gz`.
3. Note that `V2UploadLogs` with log type `node-boot` will not update the host progress. …

MGMT-12312: Adds node-boot log type

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

Hypershift may generate spokes with two names for root CA:
* kube-root-ca
* kube-root-ca.crt in openshift-config namespace.
Assisted Service should look up both and attempt to use it.
Followup for https://github.com/openshift/assisted-service/pull/4696

MGMT-12749: BMH: add another fallback location for spoke's root CA

---

docs/dev/running-test.md

In local environments, we sometimes hit the rate-limitter of docker hub when creating and destroying the minikube environment. This is because the registry addon of minikube relies on images that are not in ghcr.io but from docker-hub.
This change uses images from quay.io for the registry, as a simple workaround.

Setting minikube registry addon to use images from quay.io

---

internal/host/hostutil/host_utils.go
internal/host/hostutil/host_utils_test.go

This PR fixes the issue with returning the ignition endpoint in the form of an IPv6 address by adding missing brackets around the IPv6 address. This is required in order to form a correct HTTP URI which requires brackets to make IPv6 address distinguishable from the port.
Fixes: [MGMT-12405](https://issues.redhat.com//browse/MGMT-12405)
/cc @omertuc

MGMT-12405: Enclose API endpoint with brackets if IPv6 address

---

internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go

Previously during the initramfs boot stage (specifically when the rootfs is being downloaded) hosts booted with ZTP+iPXE only had connectivity on the provisioning network. When ironic is provisioning a host on its own this is fine as it is serving the rootfs from the same service as the kernel and initrd, but in our case the rootfs is being served by the assisted-image service so we need to be able to connect on additional nics.
This commit adds the `rd.bootif=0` kernel parameter which instructs networkmanager to allow connectiviy using nics other than the one that was used for the iPXE boot.
Resolves https://issues.redhat.com/browse/MGMT-13333
Manual tests were done using a devscripts environment.
- deployed a cluster where BMO was configured to serve only iPXE to hosts.
- created an …

MGMT-13333: Fix iPXE ZTP host connectivity during initramfs

---

deploy/operator/setup_lso.sh

Instead of removing and re-adding every time a new OCP version gets
introduced, this change just bumps our hack of using 4.12 catalog for
LSO installation to OCP 4.13.

bump version for hacking LSO catalog

---

internal/host/monitor.go
internal/host/monitor_test.go

The monitor resets the 'suggested-role' field on all hosts of the clusters if one of the hosts is in auto-assign. This was done to eliminate race conditions between 'register host' and the calculation of auto-assign a synchronically in the monitor loop.
The reset may happen once in a lifetime of a host.
However, in production, we found several types of obsolete hosts mostly orphan ones that trigger that role clearance all the time
The amendment to the query does not reset the roles where the the auto-assign host is not relevant:
* in status disabled (obsolete)
* disconnected
* day2 host (old hosts - current day 2 sets the role to a worker role before registering)
* host stuck on discovering state
This PR, in combine with future improvements to GC code, will eliminate the spurious resets …

MGMT-12970: don't reset auto-assign for irrelevant hosts

---

Dockerfile.assisted-service-build

Occurs with publish-python-client job which relies on
assisted-service-build image.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-assisted-service-master-edge-publish-python-client/1615200110763839488

MGMT-13342: Git fails to trust git repository because of mismatch with files

---

openshift/template.yaml

Currently the `ENABLE_REJECT_UNKNOWN_FIELDS` can't be changed in the SaaS environment because there is not a corresponding parameter in the OpenShift template. This patch adds it.

MGMT-12697: Add `ENABLE_REJECT_UNKNOWN_FIELDS` to SaaS template

---

internal/host/common.go
subsystem/kubeapi_test.go

[MGMT-13229](https://issues.redhat.com//browse/MGMT-13229): Allow setting Joined to sno installation stages
We want to start controller right after kubelet is starting in sno flow, we should allow setting Joined state for sno in that case

MGMT-13229: Allow setting Joined to sno installation stages

---

docs/enhancements/README.md
docs/enhancements/dynamic-fetching-of-openshift-versions.md

Suggesting how assisted-service and assisted-installer UI can be adjusted to deliver all versions in the upgrade-channel API without the need of specified configuration.

MGMT-12996: enhancement for dynamic OCP fetching

---

internal/host/statemachine.go
internal/host/transition_test.go

Users can not update cluster when one of the hosts is in disconnected state due to a disconnected discovery media.
The root cause is a missing transition from disconnected to disconnected when the condition is media disconnection.

MGMT-13317: missing transition on refresh when media is disconnected

---

api/vendor/github.com/openshift/assisted-service/models/drive_type.go
models/drive_type.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/drive_type.go

This PR does nothing but define a new disk drive type for RAID, which will be used by the agent for reporting.

MGMT-12714: Define RAID drive type

---

cmd/main.go
docs/hive-integration/README.md

Going ahead and enabling this before https://github.com/openshift/assisted-service/pull/4827 is merged as it's not really necessary (we already have an env override if the architectures don't match) and that PR is taking a long time to discuss.
Resolves https://issues.redhat.com/browse/MGMT-11997
Tested as a part of all the previous PRs related to converged flow.
This doesn't change behavior, just changes the default.

Enable converged flow by default

---

Dockerfile.assisted-service-build
Makefile
ci-images/Dockerfile.lint

Waiting for #4543 to merge first, because it includes the file which we aim to lint
For as long as `assisted-boot-reporter.sh` is implemented in Bash,
which is notoriously error-prone, we'll use the `ShellCheck` linter
to at-least avoid some common Bash mistakes
- Ran the linter and saw that it works as expected

Add automatic `ShellCheck` linting for `assisted-boot-reporter.sh`

---

internal/host/validations_test.go
internal/host/validator.go

Instead of failing for an unexpected status for the lack of tang connectivity check, the disk encryption validation will now be set to 'pending' status.

MGMT-13462: Fix disk encryption validation pending

---

internal/featuresupport/support_levels_list.go

It's currently missing, which makes the UI to fail displaying the cluster view.
This adds a similar list as in OCP 4.12 (because for all I know multi-arch is still Tech-Preview).

MGMT-13548: add feature-support-level list for 4.13

---

pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go

Following a customer incident, we would like to allow the user to provide ignition overrides after the installation has started/failed for the day2. This supports fixing limitations/bugs in the main flow.
The full details are provided in the thread attached to the corresponding Jira ticket.
This PR allows editing the IgnitionEndpoint field in agent cluster install cr to facilitate the above.
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING. …

MGMT-13505: allow to edit ignition url in kube-api

---

api/vendor/github.com/openshift/assisted-service/models/cluster.go
api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
api/vendor/github.com/openshift/assisted-service/models/infra_env.go
api/vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
api/vendor/github.com/openshift/assisted-service/models/os_image.go
api/vendor/github.com/openshift/assisted-service/models/release_image.go
internal/bminventory/inventory.go
internal/common/common.go
internal/oc/release.go
internal/versions/osimages.go
internal/versions/versions.go
models/cluster.go
models/cluster_create_params.go
models/infra_env.go
models/infra_env_create_params.go
models/os_image.go
models/release_image.go
restapi/embedded_spec.go
subsystem/cluster_v2_test.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/cluster.go
vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
vendor/github.com/openshift/assisted-service/models/infra_env.go
vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
vendor/github.com/openshift/assisted-service/models/os_image.go
vendor/github.com/openshift/assisted-service/models/release_image.go

Translate arm64-> aarch64 in instances where we reference rhcos (should mirror x86_64 -> amd64 mapping)
In parallel with openshift-installer change for agent installer: https://github.com/openshift/installer/pull/6401
Manually created agent.iso and installed OCP with arm64 BM HW in our RDU2 lab

ARMOCP-417: enable arm64 for agent installer

---

internal/bminventory/inventory.go
internal/common/common_test.go
internal/common/version.go
internal/operators/cnv/cnv_operator.go
internal/operators/lvm/manifest.go
internal/operators/lvm/manifests_test.go
internal/operators/manager.go

When creating SNO cluster with LVM enabled alongside pre-release 4.12 OCP version there is wrong subscription-name (odf-lvm-operator instead of  lvms-operator)
/cc @eliorerz

MGMT-13526: Fix wrong subscription name on pre-release versions

---

docs/change-iso-password.sh
docs/set-discovery-password.md

The UI team [asked](https://issues.redhat.com/browse/MGMT-11805?focusedCommentId=21692724&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21692724) us to provide a dedicated file they can use as a
download link instead of embedding the script file inside the markdown
file.

MGMT-11805: Dedicated `.sh` file for the `docs/change-iso-password.sh` script

---

Makefile
docs/change-iso-password.sh

- Added shellcheck lint for docs/change-iso-password.sh
- Formatted it more nicely
- Fixed shellcheck complaints
- Changed mode to +x
/cc nmagnezi

MGMT-11805: `docs/change-iso-password.sh` lint

---

Makefile

ENABLE_ORG_TENANCY flag is enabled in [test target](https://github.com/openshift/assisted-service/blob/79e1671a354ac3761ee32c3432bcb3a3bda3905a/Makefile#L423), but it was missing for [deploy-test target](https://github.com/openshift/assisted-service/blob/79e1671a354ac3761ee32c3432bcb3a3bda3905a/Makefile#L393).
Thus, when using this target, subsystem tests for authorization are failing if not setting the flag in assisted-service-config. So added it also to the deploy-test target to be consistent with [ci-deploy-for-subsystem target](https://github.com/openshift/assisted-service/blob/79e1671a354ac3761ee32c3432bcb3a3bda3905a/Makefile#L378). …

NO-ISSUE: added ENABLE_ORG_TENANCY to deploy-test target

---

internal/bminventory/inventory_test.go
pkg/auth/rhsso_authz_handler.go
pkg/auth/rhsso_authz_handler_test.go
subsystem/authz_test.go

When organization tenancy is enabled, we check whether users can manipulate an object based on the AMS subscription which is stored on the cluster.
When a user creates a day2 cluster, it gets a new ID (which is different form day1 cluster), and has no AMS subscription ID. Hence, checking AccessReview on the day2 cluster fails for a non-owner user.
To mitigate this issue, 'hasSubscriptionAccess' func now searches for the day1 cluster when trying to manipulate a day2 cluster. I.e. fetching the subscription ID from the day1 cluster in order to use AccessReview. …

MGMT-13487: handle day2 cluster authz

---

internal/host/hostcommands/instruction_manager.go

[MGMT-13682](https://issues.redhat.com//browse/MGMT-13682): Gather host logs on failure in day2 flow
Enabling logs gather step on failure in day2 flow

MGMT-13682: Gather host logs on failure in day2 flow

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

This is a backport of [MGMT-12471](https://issues.redhat.com//browse/MGMT-12471) for ACM 2.6. It includes the changes from pull request #4594.
Currently the service keeps for each cluster a list of the operators that it will wait for before considering the cluster installed. This list includes the console operator. But since version 4.11 that can be disabled via the `capabilities` section of the installer configuration file. For example:
```yaml
capabilities:
baselineCapabilitySet: None
additionalEnabledCapabilities:
- baremetal
```
That will configure the cluster so that only the `baremetal` optional capability will be installed, which effectively disables the `Console` capability.
This patch changes the service so that it removes the console operator from that list when this kind of …

MGMT-13657: Don't wait for console if it is disabled - ACM 2.6

---

internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/cluster/cluster.go
internal/cluster/progress_test.go

[MGMT-13711](https://issues.redhat.com//browse/MGMT-13711): it takes the assisted-service few minutes to notice that the cluster installation is completed
Update trigger_timestamp on update finalization state when it get to 100%
Update trigger_timestamp on upload ingress ca

MGMT-13711: it takes the assisted-service few minutes to notice that the cluster installation is completed

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/mock_cluster_api.go
restapi/embedded_spec.go
restapi/operations/installer/v2_download_cluster_logs_parameters.go
subsystem/cluster_test.go
swagger.yaml

MGMT-13454: Group Host and boot logs to a single tarball

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

This is a backport of [MGMT-12471](https://issues.redhat.com//browse/MGMT-12471) for ACM 2.7. It contains the changes in pull request #4594.
Currently the service keeps for each cluster a list of the operators that it will wait for before considering the cluster installed. This list includes the console operator. But since version 4.11 that can be disabled via the `capabilities` section of the installer configuration file. For example:
```yaml
capabilities:
baselineCapabilitySet: None
additionalEnabledCapabilities:
- baremetal
```
That will configure the cluster so that only the `baremetal` optional capability will be installed, which effectively disables the `Console` capability.
This patch changes the service so that it removes the console operator from that list when this kind of …

MGMT-13664: Don't wait for console if it is disabled - ACM 2.7

---

deploy/operator/setup_assisted_operator.sh

Allow overriding image service image in subscription, that way we can
inject it as CI artifact when deploying AI through the subscription using the
index image.
x-ref: https://github.com/openshift/release/pull/36470

MGMT-13708: allow overriding image service image in subscription

---

api/vendor/github.com/openshift/assisted-service/models/cluster.go
docs/events.yaml
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/cluster/refresh_status_preprocessor.go
internal/cluster/refresh_status_preprocessor_test.go
internal/common/common.go
internal/common/events/events.go
internal/common/validations.go
internal/host/refresh_status_preprocessor.go
internal/host/refresh_status_preprocessor_test.go
internal/usage/consts.go
models/cluster.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/cluster.go

Two cluster level fields have been introduced "SkippedHostValidations" and "SkippedClusterValidations"
Each field will hold a JSON encoded list of strings with the names of the validations to be skipped or "all"
If the "all" option is chosen then all validations, including operator validations will not execute. If specific validations are entered then just these will be skipped.

MGMT-13204: Implement skipping of host and cluster validations

---

internal/host/validations_test.go
internal/host/validator.go

If the non-overlapping-subnets validation is pending, the message is "Missing inventory, or missing cluster." This message is confusing.  The message should either be "inventory not yet received" or "host is not bound to a cluster" depending on the case.
This has been modified in this PR to return the message "host is not bound to a cluster" when the cluster is not defined and "inventory not yet received" when the inventory is not defined.
This PR includes unit tests to ensure that the messaging has been correctly altered. …

MGMT-13521: Clearer messaging when non-overlapping-subnets validation is pending.

---

internal/host/validator.go

The message "please configure an NTP server via DHCP or set clock manually" from the time-synced-between-host-and-service validation is problematic because we are advising the end user to manually set their clock; an unsuppored operation.
Therefore, we are going to remove that part of the message to have it read
"please configure an NTP server via DHCP" instead
This is a simple text change, there is not much to test.
- [] Does this change include unit-tests (note that code changes require unit-tests)
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#co …

MGMT-13274: Update time-synced-between-host-and-service message to remove bad advice

---

deploy/operator/setup_assisted_operator.sh

When using the converged ZTP flow in a disconnected environment we need to ensure that the agent gets registry configuration for both the in-prow image repos as well as the internal images which will still likely be using quay.io
Specifically this is a problem for the ironic agent image which previously couldn't be pulled by the host during discovery despite being mirrored properly by dev-scripts.
https://issues.redhat.com/browse/MGMT-11998
Will be tested as a part of https://github.com/openshift/release/pull/36093

Add registry config for ironic agent image

---

deploy/operator/setup_assisted_operator.sh

After merging #4995 the disconnected job created a registries.conf entry pointing to our image mirror
(`virthost.ostest.test.metalkube.org:5000/ci-op-97wqmr59/release` in this case) rather than the one created for the hub cluster release image by ironic
(`virthost.ostest.test.metalkube.org:5000/localimages/local-release-image`)
https://issues.redhat.com/browse/MGMT-11998

Use the correct env var for the hub release image mirror

---

tools/wait_for_assisted_service.py

Reverts openshift/assisted-service#4871
Now that we have https://github.com/openshift/assisted-test-infra/pull/1989 we don't need to wait longer for image-service.
/cc @adriengentil @gamli75 @eliorerz

MGMT-13210: Revert "Increase timeout waiting for image-service"

---

deploy/operator/utils.sh

Another try to get the disconnected stuff to work. I promise I'll look more closely at the test results this time :sweat_smile: 
Previously `get_image_without_tag` would return just the registry hostname for an image with a port:
```
$ get_image_without_tag_old 'virthost.ostest.test.metalkube.org:5000/localimages/local-release-image:latest'
virthost.ostest.test.metalkube.org
```
This change makes the function work for all cases:
```
$ get_image_without_tag 'quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:51ad3c2b7792f2a0c551282b6c0650d8eb80c5cfd5fc912a6b7e79e088ad67e0'
quay.io/openshift-release-dev/ocp-v4.0-art-dev
$ get_image_without_tag 'virthost.ostest.test.metalkube.org:5000/localimages/local-release-image:latest'
virthost.ostest.test.metalkube.org:5000/localimages/local-release- …
```

Make get_image_without_tag work when registry has a port

---

Makefile
hack/display_cover_profile.sh

Coverage include mocks, as they normally are included in the interface's package.
This hack removes them from the coverage profile before uploading or manual local analysis.
- [] None
Locally with `go tool cover -html=./reports/unit_coverage.out` and other cli utils

NO-ISSUE: remove mocks from coverage

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

BMH secret is copied to the spoke only in adding the day2 worker to spoke cluster scenario.
The presence of the secret on the spoke creates a discrepancy between the status of the BMH of the day2 worker and the those of the masters and day1 workers on the spoke cluster.
By not copying the BMH secret, we align the status of all cases to unmanaged.

MGMT-13398 omit BMH secret from day2 spoke worker

---

docs/enhancements/add-feature-support-by-generic-attributes.md

As part of adding feature support per architecture alongside OCP version, an API change is needed.
This doc is describing what change is needed to be done and an proposal to solve this issue.
Note: An implementation proposal is available at https://github.com/openshift/assisted-service/pull/4989 
/cc @eliorerz

MGMT-13780: Write a feature-support-level enhancement doc

---

internal/featuresupport/feature_support_level.go
internal/featuresupport/feature_support_test.go

Description of the problem:
GetFeatureSupportList returning empty object when calling GET v2/support-levels/features?openshift_version=X
/cc @gamli75

MGMT-13913: Fix empty features list when calling GET v2/support-levels/features

---

internal/ignition/ignition.go
internal/ignition/ignition_test.go

Currently when the service generates the bare metal hosts for the installed cluster it selects the first IP address of each NIC. But if there are multiple IP addresses in the same interface this may end up selecting an IP address that isn't inside the machine CIDR of the cluster. If that happens then there will be a missmatch between the IP addresses of machines and nodes. As a result machine will not be linked to nodes and machines will never reach the `Running` phase, and therefore the corresponding machine pool will never have the minium number of replicas, which makes the installation fail.
Related: https://issues.redhat.com/browse/MGMT-13903
- Should …

MGMT-13903: Select IP inside machine CIDR for BMH

---

internal/controller/controllers/bmo_utils.go
internal/controller/controllers/bmo_utils_test.go

In case the converged flow is enabled and the assisted-service fails to get a valid ironic inspection URL it's using the Ironic URL as default, since the Ironic URL is likely the cluster API VIP this behavior leads to inspection failures in case the inspection service run on a node that isn't holding the cluster VIP. The inspection error results in Agents that never show up.
**As a temporary workaround for the issue,** the changes in this PR will return in case the inspection URL is empty, this error will cause the service to fail with a relevant error.
- Is this PR relying on CI for an e2e test run? Yes
- Should this PR be tested in a specific environment? Yes, with converged flow enabled
- Any logs, screenshots, etc that can help with the …

MGMT-13925: Handle missing inspection URL

---

cmd/main.go
go.mod
go.sum
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/versions/api_test.go
internal/versions/versions.go
internal/versions/versions_test.go
vendor/golang.org/x/sync/semaphore/semaphore.go
vendor/golang.org/x/sync/singleflight/singleflight.go
vendor/modules.txt

This reduces the amount of work we have to do every time we encounter a cache miss.
Before this change a cache miss would re-evaluate all of the cluster image sets in the cluster and would require us to pull and inspect all of the images that we don't already have cache entries for. If we had a limited set of OS images this could mean a lot of additional processing time.
In some cases there were as many as 40 cluster image sets that didn't have OS images. Processing these caused requests to time out in some cases.
Additionally, these images were all being processed serially which also slowed everything down. This PR adds concurrency to the cluster image set processing to allow the first request to download an ISO to succeed even when it needs to process all (~80 in my testing) cluster …

ACM-4127: Cache release images even if there is no matching OS image

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/mock_cluster_api.go

Currently the cluster deployment controller waits for the console to be available before marking the cluster deployment as completed. This fails when the console capability is disabled. To avoid that this patch changes the controller so that it doesn't wait when the console is disabled.
Related: https://issues.redhat.com/browse/OCPBUGS-8335
Related: https://issues.redhat.com/browse/MGMT-13941
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING …

MGMT-13941: Don't wait for console if disabled

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/mock_cluster_api.go

Currently the cluster deployment controller waits for the console to be available before marking the cluster deployment as completed. This fails when the console capability is disabled. To avoid that this patch changes the controller so that it doesn't wait when the console is disabled.
Note that this is a clone of [MGMT-13941](https://issues.redhat.com//browse/MGMT-13941) (which in turn is a clone of OCPBUGS-8335) for ACM 2.7.
Related: https://issues.redhat.com/browse/OCPBUGS-8335
Related: https://issues.redhat.com/browse/MGMT-13941
Related: https://github.com/openshift/assisted-service/pull/5022 …

MGMT-13963: Don't wait for console if disabled

---

internal/ignition/ignition.go

Currently, in case there is an internal ignition override we spam the assisted service log with the full ignition.
It's very big and there is no reason for it.
see example in the postmortem log [here](https://issues.redhat.com/browse/MGMT-13937)
--> …

NO-ISSUE: remove the full ignition from log

---

Dockerfile.assisted-service-build
ci-images/Dockerfile.code-generation
ci-images/Dockerfile.subsystem

The old k8s.gcr.io registry, which was the official source of Kubernetes-related container images for years, is being redirected automatically to the new registry (registry.k8s.io) starting this monday, March 20.
It shouldn't cause any issues to stay with the older location, but either way it's best to change it in advance.

Sparing the redirect for official k8s registery

---

api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/featuresupport/architecture_support_level.go
internal/featuresupport/feature_support_level.go
internal/featuresupport/feature_support_test.go
internal/featuresupport/features.go
models/feature_support_level_id.go
restapi/embedded_spec.go
subsystem/feature_support_levels_test.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go

[MGMT-13862](https://issues.redhat.com//browse/MGMT-13862): Return bed request on wrong feature-feature or feature-architecture combination.
[MGMT-13958](https://issues.redhat.com//browse/MGMT-13958): Delete unused feature IDs from /v2/support-levels/features
Features that are being used by the UI:
Note: `CLUSTER_MANAGED_NETWORKING_WITH_VMS` has been removed due to that we are returning `Supported` statically regardless of cpu architecture or openshift version 
/cc @gamli75

MGMT-13958: MGMT-13862: Return bed request on wrong feature-feature or feature-architecture combination

---

internal/network/manifests_generator.go

This will reportedly fix a SELinux issue that happens with the RHEL 9 rebase for OCP 4.13, where the dispatcher policy is a bit tighter for scripts by default.
See also https://github.com/fedora-selinux/selinux-policy/issues/778 which is highly related to this - the policy is stricter for bash versus executables.

manifests: Add a shebang to NM dispatcher script

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/featuresupport/feature_support_level.go
internal/featuresupport/feature_support_test.go
subsystem/feature_support_levels_test.go

Returning bad request on feature-support validation is colliding with multi platform feature. 
Whenever the user set the CPU architecture to P or Z the platform changed to multi causing loose of information and not failing the cluster registration/update
/cc @eliorerz

MGMT-14075: Fix register cluster won't fail when creating cluster with P or Z architectures on 4.12

---

openshift/template.yaml

Back in https://github.com/openshift/assisted-service/pull/5048 this parameter was only defined, but not used for the deployment definition.

actually use the ENABLE_DATA_COLLECTION parameter

---

internal/cluster/cluster.go

[MGMT-14040](https://issues.redhat.com/browse/MGMT-14040)
If event uploading was disabled when assisted-service starts running then the only log that shows is "Event uploading is not enabled". This is confusing if event uploading is eventually enabled without restarting the service and the user won't know that the event upload is running.

MGMT-14040: Add log that shows event upload is running

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/featuresupport/architectures.go
internal/featuresupport/feature_support_test.go
internal/provider/common.go
subsystem/feature_support_levels_test.go

- [MGMT-14109](https://issues.redhat.com//browse/MGMT-14109): Set P and Z architectures support label as tech-preview on 4.12
- [MGMT-14110](https://issues.redhat.com//browse/MGMT-14110): Set UserManagedNetworking default value for P and Z architectures

MGMT-14110: MGMT-14109: Set P and Z architectures support label as tech-preview on 4.12

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/mock_cluster_api.go

Currently the cluster deployment controller waits for the console to be available before marking the cluster deployment as completed. This fails when the console capability is disabled. To avoid that this patch changes the controller so that it doesn't wait when the console is disabled.
Note that this is a clone of [MGMT-14096](https://issues.redhat.com//browse/MGMT-14096) (which in turn is a clone of OCPBUGS-8335) for ACM 2.6.
Related: https://issues.redhat.com/browse/OCPBUGS-8335
Related: https://issues.redhat.com/browse/MGMT-14096
Related: https://github.com/openshift/assisted-service/pull/5022 …

MGMT-14096: Don't wait for console if disabled - ACM 2.6

---

internal/constants/scripts.go

Apparently in versions of RHCOS based on RHEL 9 when the `99-assisted-pre-static-network-config.sh` script is executed the NetworkManager service is already running and will not automatically reload the connection configuration files that we create. When using the minimal ISO that may prevent the dowload of the rootfs, as the network settings may not be correct. To avoid that this patch changes the script so that it explicitly runs `nmcli connection reload` after creating the files.
Related: https://issues.redhat.com/browse/MGMT-14074
Tested running a 9.2 minimal ISO in a virtual machine. Interrupted the boot adding `rd.break=initqueue` to the kernel command line. Then modified the shell script manually, and exited the shell to continue the boot. With the change the boot continues and the …

MGMT-14074: Reload NM config after creation

---

internal/constants/scripts.go

A recent commit introduced the use of `nmcli connection reload` in the network configuration script `99-assisted-pre-static-network-config.sh`. But the `nmcli` tool is not avaiable in the RHEL 8 initramfs. Using it in that environment will generate an error message but not cause any other noticeable effect: the script will continue running. To avoid that error message this patch changes the script so that if checks if the command exists before executing it.
Related: https://issues.redhat.com/browse/MGMT-14074
Related: https://github.com/openshift/assisted-service/pull/5066 …

MGMT-14074: Don't run `nmcli` if not available

---

internal/constants/scripts.go

This is a backport of [MGMT-14074](https://issues.redhat.com//browse/MGMT-14074), #5066 and #5087 to the ACM 2.7 branch.
Apparently in versions of RHCOS based on RHEL 9 when the `99-assisted-pre-static-network-config.sh` script is executed the NetworkManager service is already running and will not automatically reload the connection configuration files that we create. When using the minimal ISO that may prevent the dowload of the rootfs, as the network settings may not be correct. To avoid that this patch changes the script so that it explicitly runs `nmcli connection reload` after creating the files.
Related: https://issues.redhat.com/browse/MGMT-14136
Related: https://issues.redhat.com/browse/MGMT-14074
Related: https://github.com/openshift/assisted-service/pull/5066
Related: …

MGMT-14136: Reload NM config after creation - ACM 2.7

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/featuresupport/feature_support_level.go
internal/featuresupport/feature_support_test.go
internal/featuresupport/features.go
subsystem/feature_support_levels_test.go

Apparently `GetClusterFromDB` is not returning the cluster monitored operators causing the infraenv not to fail when there is incompatible feature/architecture,
Also add missing feature incompatibilities
/cc @gamli75

MGMT-14133: Fix P/Z support level allows cluster with OLM operators.

---

internal/installcfg/installcfg.go
internal/provider/registry/registry_test.go
internal/provider/vsphere/consts.go
internal/provider/vsphere/installConfig.go

On OCP 4.13, multiple vSphere data centers and multiple vSphere clusters support was added alongside deprecating the previous vsphere provider parameters.
This PR add the missing parameters and deprecate the old ones.
/cc @gamli75

MGMT-14150: Update install-config to support multi vSphere data-centers

---

internal/constants/scripts.go

Presently, in the PreNetworkConfig script, we are removing the default network manager configuration for a host in every case. This should be altered so that the default configuration is deleted only if custom nmstate configuration has been provided for the host.
This PR also addresses a breaking issue with the way in which  Dracut Initqueue scripts are handled. Consider the following directory on a given host.
```
ls /usr/lib/dracut/hooks/initqueue/settled
90-assisted-pre-static-network-config.sh 99-nm-run.sh
```
if we inject a script between the two scripts with the sole purpose of using an exit statement...
```
echo "exit 0" > /usr/lib/dracut/hooks/initqueue/settled/91-test-exit.sh && chmod +x /usr/lib/dracut/hooks/initqueue/settled/91-test-exit.sh
```
Then the script `99-nm-run.sh` …

MGMT-13793: Do not remove host default configuration unless network configuration is provided for it

---

docs/enhancements/api-for-ignoring-validations.md

The JSON examples provided for the API endpoint calls were incorrect. These have been fixed to reflect the correct values.

MGMT-13916: Update enhancement doc for ignoring validations feature

---

internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go

Once the user has started an installation, it appears that it is possible to modify ignored validation values. This may lead to issues when trying to diagnose the reasons for the failure of a cluster.
Do this PR disables the capability to modify the ignored validations in a post-install state

MGMT-13918: Modify ignored validation should not be possible post-install

---

internal/bminventory/inventory_v2_handlers.go
internal/common/common.go
subsystem/authz_test.go

During QA it was discovered that the ignored validations feature does not validate the supplied validation ID's to ensure they are valid. This PR fixes that by validating the supplied validation ID's

MGMT-14026: Add validation to ensure ignored validation ID exists

---

internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
subsystem/kubeapi_test.go

This change also fixes a case where in KubeAPI, the update flow did not
account for UserManagedNetworking updates.
API responses will match the logical order of invalid params.

MGMT-13846: Reject UserManagedNetworking true when cluster VIPs are set

---

internal/bminventory/inventory_test.go

The current implementation of the inventory test uses gomock.Any() as a matcher for the cluster, this is not very accurate. This PR changes that by ensuring each cluster matches on at least ID.

MGMT-14195: Use clusterIdMatcher instead of gomock.Any() in inventory_test

---

client/events/v2_list_events_parameters.go
internal/common/common.go
internal/events/event.go
internal/events/event_test.go
internal/events/events_api.go
restapi/embedded_spec.go
restapi/operations/events/v2_list_events_parameters.go
restapi/operations/events/v2_list_events_urlbuilder.go
swagger.yaml

As part of events pagination epic, this PR is about adding `order` parameter so the client can request the events in the desired order, and changing the counting of events by severity to apply after the filtering

MGMT-13178: Adding order parameter and changing the count of events by severity to apply only after the filtering

---

internal/bminventory/inventory_v2_handlers.go
subsystem/authz_test.go

Presently when you attempt to ignore "all" validations then a validation error will be returned. This is a bug.
This PR addresses the bug.
- [] None

MGMT-14283: Ignored validations - validation id "all" does not work

---

docs/change-iso-password.sh

This merge request changes the `change-iso-password.sh` script, which is used to add a password to the discovery ISO, slightly. It adds a private SELinux label for the volume mount content by adding the `:Z` suffix to the volume mount in the podman run command. Without it, the podman run command fails because of permissions.
Successfully executed script on a system (Fedora 37) with enforced SELinux and on a Windows machine using WSL without SELinux. …

Add private SELinux label for volume mount content

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/featuresupport/common.go
internal/featuresupport/feature_support_test.go
internal/featuresupport/features.go

This PR fixes 4 issues:
- https://issues.redhat.com/browse/MGMT-14242 - Installation of day2 arm worker in a day1 x86 cluster is blocked by assisted service due to missing OCP version
- https://issues.redhat.com/browse/MGMT-14017 -  Feature usage for power and z  not working on 2.18.0
- https://issues.redhat.com/browse/MGMT-14239 - Disable `Cluster Managed Network` support for Power(ppc64le)
- https://issues.redhat.com/browse/MGMT-14300 - Create infraenv failed for day2 add host for Power
/cc @gamli75

MGMT-14242: MGMT-14017:  MGMT-14239: MGMT-14300: Fix multiple bugs (feature support and feature usage)

---

internal/ignition/ignition.go
internal/ignition/ignition_test.go
internal/installercache/installercache.go
internal/installercache/installercache_test.go
internal/installercache/priorityqueue.go
internal/oc/mock_release.go
internal/oc/release.go
openshift/template.yaml
pkg/generator/generator.go

with lru policies
The single source of truth is the file system, so no delete failures are retried.
instead of locking in memory, the caller receives a hard link to the file and deletes it after the processing is completed.
There is also a GC logic for links if they are left behind.
The hard link makes sure that the file is always available to the caller, even if eviction is taking place in parallel (in the rare event of a request storm)
A priority queue is used to keep track of the oldest file. Whenever a file is accessed its mtime is updated so it won't get evicted. …

MGMT-13083: limit the size of release binaries

---

cmd/main.go
internal/bminventory/inventory.go
internal/usage/manager.go
internal/usage/manager_test.go

In this PR we add notifications for:
* infraenv registration
* feature usage updates
Unfortunately we do not have centralized updates, so this could happen in other parts of the code as well.

MGMT-14338: add missing stream notifications

---

internal/host/hostcommands/domain_name_resolution_cmd.go

Solves [MGMT-14395](https://issues.redhat.com//browse/MGMT-14395)
Don't request domain resolution for the cluster release image domain on
day-2 clusters
Fixes a bug where day-2 hosts get stuck in insufficient due to error
creating DNS resolution step.
We can avoid requesting DNS resolution for this domain on day-2 cluster
hosts, because we don't run the DNS validation on the release image
domain on day-2 clusters anyway (see [1]).
This bug affects only some day-2 clusters that don't have the release
image set (imported clusters). See example failure here [2].
[1] https://github.com/openshift/assisted-service/blob/654a835dd1298a727a490ba1cfa33a96e7a468b0/internal/host/validator.go#L1527
[2] https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-test-infra-m …

MGMT-14395: Day-2 domain name resolution step shouldn't include release image domain

---

internal/installercache/installercache.go
internal/installercache/installercache_test.go

If a release image mirror is specified, the binary will get extracted to a location reflecting the mirror's pullspec, not the original release pullspec.
[MGMT-14396](https://issues.redhat.com/browse/MGMT-14396)

MGMT-14396: Get correct path for binary from mirror

---

deploy/operator/README.md
deploy/operator/ztp/add-remote-nodes-playbook.yaml
deploy/operator/ztp/agentClusterInstall.j2
deploy/operator/ztp/assisted-installer-crds-playbook.yaml
deploy/operator/ztp/baremetalHost.j2
deploy/operator/ztp/deploy_spoke_cluster.sh

Modify the scripts in assisted-service/deploy/operator/ztp. The following environment variables will be added:
MANIFESTS: JSON containing the manifests to be added for day1 flow.  The key is the file name, and the value is the content.
NODE_LABELS: Dictionary of dictionaries.  The Outer dictionary key is the node name and the value is the node labels (key, value) to be applied.
MACHINE_CONFIG_POOL: Dictionary of strings.  The key is the node name and the value is machine config pool name.
SPOKE_WORKER_AGENTS: Number of worker nodes to be added as part of day1 installation.  Default 0 …

MGMT-14137: Create test flow for ZTP for node labeling and avoiding reboot for custom role

---

deploy/assisted-image-service.yaml
deploy/assisted-service.yaml

We get readiness errors as the pod is not ready yet: the service needs working postgres to pass readiness.
Image service will also need to download all images before being ready, which most of the times will take longer than 30s, but this would potentially reduce the time if images are quick to download.
I don't think it's worth parametrizing, we can just change hardcoded values if we need more or less time. …

MGMT-14108: add readiness probe initialDelaySeconds for service and image-service

---

internal/bminventory/inventory_test.go
internal/featuresupport/feature_support_level.go
internal/featuresupport/feature_support_test.go
internal/featuresupport/features.go
subsystem/feature_support_levels_test.go

Updating that SNO is dev preview on OCP 4.13 with P or Z architecture.
Also changing the way we initialize `SupportLevelFeature` - now allowing to link between 2 opposite (`CMN` or `UMN`) or related (`SNO` and `SingleNodeExpention`) features 
/cc @eliorerz

MGMT-14315: Allow to install P and Z architectures with Single Node Openshift on 4.13

---

internal/host/hostutil/test_utils.go

This PR aims to reduce race conditions in tests by creating hosts in the past.
For instance, if we check updated at timestamp to be updated and the host got updated too fast, it would seem unchanged.
This change should fix this case.

MGMT-14449: change creation time for hosts to one minute ago instead of now

---

internal/bminventory/inventory.go
pkg/validations/validations.go
pkg/validations/validations_test.go
subsystem/kubeapi_test.go

On create/update cluster, a CA certificate can be specified in the ignition endpoint.
Added validations to ensure the validity of the certificate. I.e. it should be encoded to base64 and parsable.

MGMT-11424: added validations for ignition cert

---

deploy/operator/capi/deploy_capi_cluster.sh

Hypershift will default to the control plane operator of the release image, we should override the image only if we want to test changes in CPO (from Hypershift PRs).
- Should this PR be tested in a specific environment? hypershift + capi
- Any logs, screenshots, etc that can help with the review process? check the create cluster command in the capi test
--> …

NO-ISSUE: Override the control plane operator image only if explicitly asked to

---

deploy/operator/capi/deploy_capi_cluster.sh

The latest change to this script added CONTROL_PLANE_OPERATOR_IMAGE env evaluation condition but forgot the $ sign 

NO-ISSUE: Check whether is defined

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

When host try to register if the clsuter is not exist the service should return 404, if it return 500 the host will continue to try and register again and again, it will csae the api rate to spike.
The root cause is not clear yet, meaning that we don't understand why infra-env still exist when cluster was deleted, it can probably happen if there is a bug in delete logic.
Eventailly the infra-env sohuld be deleted by GC bug we would like to avoid api skipes …

MGMT-14509 return 404 if cluster not found when host try to register

---

api/v1beta1/agent_types.go
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/agent_types.go

This commit deletes the spoke machine and BMH when removing the node if
the entire cluster is not being removed (indicated by the existence of the cluster deployment).
Removing the machine will allow the same host to be cleanly added back as a node in the future.
The machine and BMH are removed directly and separately if the machine is not part of a machine set.
If the machine is part of a set the machine is annotated to indicate it is the one which should be removed and the machineset is configured for autoscaling. Once this is done the BMH is removed. This triggers the machine set to scale down, removing the previously annotated machine.
Due to OCPBUGS-7581 the BMH will likely not be removed cleanly so we also remove the finalizers before attempting the delete.
In the case of a …

MGMT-14237: Remove all spoke resources when deleting the node

---

deploy/podman/README-disconnected.md

The previous versions seems to have been a mistake.
4.2 is required for configmap volume sources

Podman README-disconnected requires 4.2 and not 3.3

---

internal/ignition/ignition.go

Use a disk 'name' that matches the format returned by ironic inspection in Metal³ when setting the HardwareDetails for a BareMetalHost CR generated by the assisted.

OCPBUGS-13250: Fix disk name in generated HardwareDetails

---

internal/events/event.go
internal/events/event_test.go

To obtain accurate results in `SQL`, we need to escape the letters `%` and `_ `as they are considered wildcards. Also, we aim to retrieve messages that correspond to events regardless of the letter case.

MGMT-14530: Changing event message filtering to escape wildcards and not be case sensetive

---

pkg/validations/validations.go
pkg/validations/validations_test.go

[MGMT-13977](https://issues.redhat.com/browse/MGMT-13977)
Previously, the service allowed base domains
with a single character, which is not valid.
A top-level domain (TLD) aka base domain
must have at least two characters. This change
ensures that the base domain for a cluster has
at least two characters and fits the standards
for DNS:
https://datatracker.ietf.org/doc/html/rfc1123#page-13 
https://datatracker.ietf.org/doc/html/rfc952
Slack thread discussion for reference: https://redhat-internal.slack.com/archives/C68TNFWA2/p1681860903326989
Using test-infra environment: deployed three different clusters with three different base domains and ensured the domains that had one character for their base domain did not pass the validation:
```bash
$ export IPv4=true; export NUM_MASTERS=1; …
```

MGMT-13977: Disallow single character base domain

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go
internal/host/hostutil/host_utils.go
internal/ignition/ignition.go

In many cases, the /dev/disk/by-path symlink is the only way to stably identify a disk without having prior knowledge of the hardware from some external source (e.g. a spreadsheet of disk serial numbers). It should be possible to specify this path in the root device hints.
Metal³ is also changing to allow this, and both uses of the Metal³ root device hints (i.e. in the baremetal-operator and in assisted-service) should behave consistently. …

OCPBUGS-13081: Support by-path root device hints

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go
internal/host/hostutil/host_utils.go
internal/ignition/ignition.go

[release-4.13] OCPBUGS-13083: Support by-path root device hints

---

deploy/operator/capi/deploy_capi_cluster.sh

The previous check didn't account for jobs (e.g. collect-profiles) that might complete (and move to ready=false) before all other pods are ready.
In essence there is no reason to check each and every pod status, when we can just wait for the control plane ready status
https://issues.redhat.com/browse/MGMT-14610

MGMT-14610: Wait for the hostedcontrolplane CR ready status instead of watching the ready status of all pods in the namespace

---

internal/controller/controllers/bmh_agent_controller_test.go
internal/host/hostutil/host_utils.go

[release-4.12] OCPBUGS-13529: Support by-path root device hints

---

docs/user-guide/install-customization.md

This is a documentation fix:
* The request params for manifests now include `folder` and `file_name`
* Resource name in the example must comply with K8s rules for resource names
* HTTPS has to be used where TLS is enabled, e.g. with the SaaS API

NO-ISSUE: Fix install customization doc

---

deploy/operator/capi/deploy_capi_cluster.sh
deploy/operator/utils.sh

The the status check may fail if we try to check it before the hostedcontrolplane got created
https://issues.redhat.com/browse/MGMT-14610

NO-ISSUE: Wait for hostedcontrolplane to be created

---

subsystem/metrics_test.go

There can be a race between the cluster monitor and the api for deregister host during this test. This PR makes the test tolerant of an extra cluster event in the case that this should occur.
- [] None
Test was run locally in bulk by focussing the test and running it a lot of times. Observed that intermittent failure disappeared.

MGMT-14648: Make "sufficient-masters-count - failed" subsystem test tolerate extra event.

---

internal/common/test_configuration.go
internal/host/hostcommands/domain_name_resolution_cmd.go
internal/host/hostcommands/domain_name_resolution_cmd_test.go
internal/host/validations_test.go
internal/host/validator.go
subsystem/utils_test.go

There was a case that a user set up their DHCP to have domain-search entry for the *.apps.cluster-name.cluster-domain. suffix, our wildcard validation failed even though the user never set up a *.cluster-name.cluster-domain. wildcard (validation false positive)
The reason for the failure is that with search domain the actual resolution was to validateNoWildcardDNS.cluster-name.cluster-domain.apps.cluster-name.cluster-domain.
The solution to avoid it is to append a dot "." to the domain name to resolve.
Since such a problem might happen (OCP does not append dot), we need to verify that such case doesn't happen.  So the failure was recognized but with different error message in order not to confuse the end user.
- …

MGMT-14526: Possible issue with validateNoWildcardDNS resolution validation

---

internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go

This change fixes a case where `UserManagedNetworking` and `VipDhcpAllocation` are being changed at the same API update.
The `ValidateClusterUpdateVIPAddresses` func will now use `VipDhcpAllocation` from update params, if relevant, before taking the DB cluster `VipDhcpAllocation` into account.
Additionally, an additional error surfaced while fixing the aforementioned
issue, displaying a `User Managed Networking cannot be set with API VIP` to the user.
This change will also handle such a scenario by clearing up API and Ingress VIPs
that were set by DHCP, in case the user switched to `User Managed Networking`.
[Kubernetes …

MGMT-14416: VipDhcpAllocation from update params should take precedence

---

internal/installcfg/builder/builder_test.go
internal/installcfg/installcfg.go

The struct tag for cpu partitioning was using but in order for the
install config to be rendered correctly in all cases it need the yaml
tag like the other fields.
Without the yaml tag cpu partitioning was being included in the install
config even if it was empty with an invlid name.
This meant that all 4.10 installs always failed to prepare for
installation with an event like:
```
Failed to prepare the installation due to an unexpected error: failed
generating install config for cluster
1583dc9b-e059-48fc-96b9-5e711d1de6b1: error running openshift-install
manifests, level=fatal msg=failed to fetch Master Machines: failed to
load asset "Install Config": failed to unmarshal install-config.yaml:
failed to parse first occurence of unknown field: error unmarshaling
JSON: while decoding JSON: …
```

Fix cpu partitioning struct tag/field

---

api/vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
api/vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
internal/bminventory/inventory_test.go
models/infra_env_create_params.go
models/infra_env_update_params.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go

As the max length of a string in postgres is 65,535 bytes, additional_trust_bundle property length should be limited on: infra-env-create-params and infra-env-update-params.

MGMT-13643: added MaxLength to additional_trust_bundle

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

When the BMH has the delete annotation the detached annotation value contains metadata that causes BMO to pause its finalizer handling until it is removed.
This means that BMAC needs to ensure the detached annotation is removed whenever the BMH is being deleted and the finalizer is going to be removed or is already gone.
Previosuly if the agent was deleted BMAC removed the finalizer, but not the detached annotation leading to the BMH not being deleted.
https://issues.redhat.com/browse/MGMT-14498

MGMT-14498: Remove the detached annotation when BMH is being deleted

---

docs/hive-integration/import-installed-cluster.md

Update docs/hive-integration/import-installed-cluster.md. When creating the kubeconfig secret for the imported ClusterDeployment, ensure that the kubeconfig is stored within a `kubeconfig` key within the secret data.
The previous example command would result in the kubeconfig being stored within a `kubeconfig.some-other-cluster` key within secret data if followed verbatim and eventually Hive would populate a `kubeconfig` key within the secret with an empty string value. client-go within Hive will fail to be able to use the kubeconfig as empty or missing within the secret resulting in conditions like the following set on the ClusterDeployment,
```
- lastProbeTime: '2023-05-23T13:33:43Z'
lastTransitionTime: '2023-05-23T13:33:01Z'
message: >-
invalid configuration: no configuration has been …
```

Docs fix: ensure kubeconfig secret is created with a kubeconfig key.

---

internal/events/event.go
internal/events/event_test.go

A fix to a bug in which searching for events with message `\` retrieves all messages with `%` as it escapes the next char (`%`) instead of being escaped

MGMT-14728: Escape the escape char (\)

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

Cluster fails to update Nutanix with multi platform architecture
/cc @gamli75

MGMT-14734: Fix failed to update Nutanix provider cluster when on multi architecture

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

Cherry pick of https://github.com/openshift/assisted-service/pull/5253
/cc @eliorerz 

[cloud_hotfix_releases] MGMT-14734: Fix failed to update Nutanix provider cluster when on multi architecture

---

internal/controller/controllers/agent_controller.go

This avoids a race condition where assisted-service deletes the BMH finalizer on the spoke cluster, then BMO on the spoke cluster adds the finalizer back before we can mark the BMH to be deleted.
Previously the BMH would not be fully deleted in the spoke cluster due to OCPBUGS-7581
Resolves https://issues.redhat.com/browse/MGMT-14667
In progress

Delete the spoke BMH before removing the finalizer

---

internal/host/hostutil/host_utils.go
internal/host/hostutil/host_utils_test.go

Presently there is a bug where the UI will not accept the host role "Auto Assign" for Day 2 hosts. This is a valid status and should be permitted. This change updates the validation to permit this.
- [] None
Installed a day 1 cluster, added a day 2 host and observed that it will now accept "auto assign"
Validated that the day 2 host correctly gets added as a "worker"

MGMT-14306: Update host role validation to accept AutoAssign in Day2

---

internal/host/host.go

- Any logs, screenshots, etc that can help with the review process? you need to check the logs when a host validation fail
-->

NO-ISSUE: fixed misleading error message, the order of the host status was reverse

---

subsystem/feature_support_levels_test.go

This bug is appearing randomly depending on which operator is validated first.
Fixing the error:
```
Feature support levels API
/assisted-service/subsystem/feature_support_levels_test.go:29
Support Level
/assisted-service/subsystem/feature_support_levels_test.go:35
Update cluster
/assisted-service/subsystem/feature_support_levels_test.go:72
Create infra-env after updating OLM operators on s390x architecture  [It]
/assisted-service/subsystem/feature_support_levels_test.go:108
Expected
<string>: cannot use Local Storage Operator because it's not compatible with the s390x architecture on version 4.13.0-rc.8-multi of OpenShift
to contain substring
<string>: cannot use OpenShift Virtualization because it's not compatible with the s390x architecture on version 4.13
```
/cc @gamli75

MGMT-14723: Fix randomly failing subsystem test

---

go.mod
go.sum
internal/cluster/validator_test.go
internal/network/machine_network_cidr.go
vendor/github.com/IBM/netaddr/.travis.yml
vendor/github.com/IBM/netaddr/LICENSE
vendor/github.com/IBM/netaddr/README.md
vendor/github.com/IBM/netaddr/iprange.go
vendor/github.com/IBM/netaddr/ipset.go
vendor/github.com/IBM/netaddr/iptree.go
vendor/github.com/IBM/netaddr/net_utils.go
vendor/modules.txt

This change is to ensure that the API VIP and the Ingress VIP  are checked against the broadcast address of the machine network to ensure that they are not the broadcast address.
- [] None

MGMT-13685: Make sure ingress and api vip are not broadcast address.

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/cluster/validations/validations.go
pkg/auth/rhsso_authz_handler.go
pkg/ocm/utils.go

Ensure OCI platform cannot be set if user's organization doesn't
have `bare_metal_installer_platform_oci` capability.

MGMT-14582: Set OCI platform behind a capability

---

api/vendor/github.com/openshift/assisted-service/models/drive_type.go
internal/common/test_configuration.go
internal/hardware/mock_validator.go
internal/hardware/validator.go
internal/hardware/validator_test.go
internal/host/host.go
internal/host/host_test.go
internal/host/hostutil/test_utils.go
internal/host/transition_test.go
internal/host/validations_test.go
internal/host/validator.go
models/drive_type.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/drive_type.go

Multipath cannot be enabled in day1 on s390x, so we will allow installing directly on an FC path only for this arch.  In addition, there are two new drive types for IBM DASDs (direct access storage devices).

MGMT-14750: Allow FC, ECKD, FBA drive types on s390x

---

internal/operators/odf/odf_operator.go

This bug was discovered in assisted-service with `OpenShift` version 4.12. It relates to a specific situation where the service generates a `StorageCluster` manifest containing an incorrect number of `ODF` disks. This issue seems to arise when the service uses the default value of `o.config.ODFDisksAvailable` in the manifest, as there exists a scenario where this attribute is not properly set with the appropriate count due to the involvement of a separate instance of the service.
As a solution, I added an additional count prior to manifest generation. This ensures an accurate count of disks, regardless of whether it is performed by a single instance or multiple instances of the service.
- Is there a bug required …

MGMT-13431: ODF storage class not recognizing all available disks in the cluster

---

internal/installcfg/installcfg.go
internal/provider/external/installConfig.go
internal/provider/registry/registry_test.go

External platform will only be available behind the `TechPreviewNoUpgrade`
feature set. This change enables it automatically when an external
platform is selected (e.g.: oci).

MGMT-14830: Enable TechPreviewNoUpgrade when platform is external

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

Currently, when IgnitionConfigOverride is specified on InfraEnv creation/update, we ensure its size isn't larger than 256KiB. This validation is done since the size of the padding for ignition in discovery image is limited.
Thus, in order to accurately validate the size, we need to calc the size of the entire discovery ignition (i.e. instead of only the 'IgnitionConfigOverride' property).
Note that this change still performs the validation only if IgnitionConfigOverride is specified, since it should still contain the substantial amount of data to reach the limitation. The other potentially large property is AdditionalTrustBundle but it's already limited to 64KiB.
- Is there a bug required (and linked) for this …

MGMT-13746: validate discovery ignition size

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

[OCPBUGS-7076](https://issues.redhat.com/browse/OCPBUGS-7076)
Previously the BMAC would copy the BMH and 
Machine CRs of a Day2 worker to the spoke cluster before
the Agent began installing. If the Agent doesn't
start installing within the two hours these CRs
were copied over, the CSRs for these nodes will
not be approved by the machine approver pod.
To prevent this from happening, only copy
the BMH and Machine CRs to the spoke cluster
when the Agent has started installing. …

OCPBUGS-7076: Copy Day2 BMH if Agent is installing

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go

This is identical to how the API server handles configuring its service monitor and it also is using service serving certs.
Also remove some complication from the `newServiceMonitor` function and remove the http port from the config as metrics are only served over https.
Resolves https://issues.redhat.com/browse/MGMT-14756
Manually deployed the operator build from this branch and saw that the service monitor was deployed correctly.

MGMT-14756: Add tls config for the service monitor

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

On update InfraEnv, should return StatusBadRequest(400), when discovery ignition image size validation fails.

MGMT-14904: fix error code for ignition size validation

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/featuresupport/common.go
internal/featuresupport/feature_support_level.go
internal/featuresupport/features.go

It shouldn't be possible to create a cluster with platform = OCI and OCP < 4.14
- [  ] No tests needed

MGMT-14883: Fix feature-support validation fail to validate openshift version

---

internal/manifests/manifests.go
internal/manifests/manifests_test.go

etcd resources in k8s are limited to 1.5 MiB as indicated here https://etcd.io/docs/v3.5/dev-guide/limit/#request-size-limit
however, one the the resource types that can be created from a manifest is a ConfigMap
which has a size limit of 1MiB as cited here https://kubernetes.io/docs/concepts/configuration/configmap
so this limit has been chosen based on the lowest permitted resource size (the size of the ConfigMap)
Presently we do not validate the maximum size during upload or edit.
This pull request addresses that by validating that the file does not exceed this limit.
- [] None …

MGMT-14730: Validate that manifest file size does not exceed 1MB

---

internal/common/conversions.go
internal/provider/common.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook_test.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go

Not all Platform and `UserManageNetworking` configurations are valid.
In REST-API, assisted service will attempt to calculate either of the two
configs to handle misconfigurations. This behavior cannot work the same way
in KubeAPI, as the DB cannot be updated separately from the ACI spec.
This webhook is placed to prevent such updates, to begin with, while basing
on the same backend business logic as the REST-API does, excluding the
backend-driven "fixes".
Mutating webhook:
1. patching `userManagedNetworking` for cases where the `platform` is not set will stay the same.
2. SNO and / or None platform: `userManagedNetworking`  --> `true`
3. BareMetal platform: userManagedNetworking  --> `false`
4. Nutanix and VSphere platform: `userManagedNetworking` not patched.
5, In case of a mismatch …

MGMT-14165: `AgentClusterInstall` Webhooks improvements and fixes

---

internal/operators/mce/config.go

MCE 2.2 will not be available in OCP 4.14. Only MCE 2.3+, for that MCE operator subscription manifest channel need to be updated to `stable-2.3`.
/cc @gamli75

MGMT-14975: Update MCE operator installation to use stable-2.3 channel

---

internal/bminventory/inventory.go
internal/common/conversions.go

When patching platform and leaving umn without change, than umn in the logs shows "false" instead of nil, causing us to think that the cluster is not in a valid state (e.g. none + umn disabled)
```
time="2023-06-15T09:59:54Z" level=info msg="Platform verification completed, setting platform type to none and user-managed-networking to false" func="github.com/openshift/assisted-service/internal/bminventory.(*bareMetalInventory).validateUpdateCluster" file="/assisted-service/internal/bminventory/inventory.go:1928" cluster_id=468bffe8-ce24-400e-a104-b0aab378eb75 go-id=94310 pkg=Inventory request_id=2fbb74ba-4390-4f27-b6fd-ee11ac1a7895 
```
/cc @adriengentil @gamli75 @nmagnezi

MGMT-14973: Fix misleading logs showing wrong platform and user_managed_networking combination

---

internal/bminventory/inventory.go

/cc @eliorerz 
Image Type is colliding with the default value on Z architecture (s390x). This PR handle both in the same place.

MGMT-14992: Fix Minimal ISO set as default in s390x

---

internal/bminventory/inventory.go

Cherry pick of https://github.com/openshift/assisted-service/pull/5302
Image Type is colliding with the default value on Z architecture (s390x). This PR handle both in the same place.
/cc @eliorerz

[release-ocm-2.8] MGMT-14992: Fix Minimal ISO set as default in s390x

---

cmd/main.go
internal/network/manifests_generator.go
internal/network/manifests_generator_test.go

Chrony configuration applied into machine config manifest based on the reply from the agent, meaning that when user add additional ntp source first the service will ask the agent to add it then return the reply to the service it will be stored in the DB and used to create the machine config chrony configuration
Because NTP is a soft validation, in ZTP flow there are cases that the installation will start before the agent return a reply to the service, it will mean that those sources will not be applied, to avoid that when building the manifests in addition to taking the agent reply the additional ntp sources will be added directly from the DB
The downside of this solution is that if the source is incorrect it will appear in /etc/chrony.conf but not in `chronyc sources` and it will not be …

OCPBUGS-13738 enforce additional ntp sources added into chrony

---

api/vendor/github.com/openshift/assisted-service/models/platform.go
api/vendor/github.com/openshift/assisted-service/models/platform_type.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go
internal/common/conversions.go
internal/provider/common.go
internal/provider/external/base.go
internal/provider/external/consts.go
internal/provider/external/ignition.go
internal/provider/external/installConfig.go
internal/provider/external/inventory.go
internal/provider/registry/registry.go
internal/provider/registry/registry_test.go
models/platform.go
models/platform_type.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook_test.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/platform.go
vendor/github.com/openshift/assisted-service/models/platform_type.go

**:warning: Note: this cherry-pick includes https://github.com/openshift/assisted-service/pull/5143, as it changed the code in a way that we have to include it. Otherwise, it leads to a lot of manual git conflicts.**
Not all Platform and UserManageNetworking configurations are valid.
In REST-API, assisted service will attempt to calculate either of the two
configs to handle misconfigurations. This behavior cannot work the same way
in KubeAPI, as the DB cannot be updated separately from the ACI spec.
This webhook is placed to prevent such updates, to begin with, while basing
on the same backend business logic as the REST-API does, excluding the
backend-driven "fixes".
Mutating webhook:
patching userManagedNetworking for cases where the platform is not set will stay the same.
SNO and / or …

[release-ocm-2.8] MGMT-15013: AgentClusterInstall Webhooks improvements and fixes

---

internal/provider/registry/registry.go
internal/provider/registry/registry_test.go

Print the platform from the arguments and not the reply from the get function to avoid using nil reply

MGMT-15015 Provider IsHostSupported panic if platform is not found

---

internal/provider/external/external_suite_test.go
internal/provider/external/ignition.go
internal/provider/external/ignition_test.go

Patch directly the Infrastructure CR from PostCreateManifestsHook
function which makes it easier to test.
This part of the code is a workaround until the openshift installer
supports external platform.

MGMT-15034: Fix patch of infrastructure CR with external platform

---

openshift/template.yaml

Needed to change reference for kafka secrets (as username, password, bootstrap servers url, etc)

NO-ISSUE: parametrize template to enable switching secrets

---

api/vendor/github.com/openshift/assisted-service/models/cluster.go
api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
models/cluster.go
models/cluster_create_params.go
models/v2_cluster_update_params.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/cluster.go
vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go

Deprecate user managed networking - use platform to determine the network configuration instead.
This PR only deprecate `user_managed_networking` attribute
/cc @avishayt @gamli75

MGMT-14937: Deprecate `user_managed_networking` attribute

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go
internal/network/utils.go
subsystem/operators_test.go

This change fixes a case where the user attempts to remove Ingress and API VIPs. Cleanup used to fail due to a missing deletion as a part of the deletion db transaction.
Added unit tests to verify all deletion combination works for singular, plural, and a combination of VIP params.

 OCPBUGS-13621: Fix singular Ingress and API cluster VIPs removal

---

docs/hive-integration/README.md
internal/controller/controllers/infraenv_controller.go
internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go
subsystem/kubeapi_test.go

If the override annotation (`infraenv.agent-install.openshift.io/ironic-agent-image-override`) is set in the infraEnv use it instead of pulling the image from the hub cluster or using the default image.
Resolves https://issues.redhat.com/browse/MGMT-10534
Unit and subsystem tests should be sufficient for this.

MGMT-10534: Create an override annotation for the ironic agent image

---

ci-images/Dockerfile.lint

Backports to 2.7 are failing lint tests due
to the base image missing this package.
Example of failing PRs:
https://github.com/openshift/assisted-service/pull/5287 ([lint test](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/5287/pull-ci-openshift-assisted-service-release-ocm-2.7-lint/1673755453261090816))
https://github.com/openshift/assisted-service/pull/5272 ([lint test](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/5272/pull-ci-openshift-assisted-service-release-ocm-2.7-lint/1666108134181048320)) …

NO-ISSUE: Add diffutils to lint Dockerfile

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

https://issues.redhat.com/browse/MGMT-14871
Backport to ACM 2.7
Cherry pick of https://github.com/openshift/assisted-service/pull/5250
https://issues.redhat.com/browse/OCPBUGS-7076
Previously the BMAC would copy the BMH and Machine CRs of a Day2 worker to the spoke cluster before
the Agent began installing. If the Agent doesn't
start installing within the two hours these CRs
were copied over, the CSRs for these nodes will
not be approved by the machine approver pod.
To prevent this from happening, only copy
the BMH and Machine CRs to the spoke cluster
when the Agent has started installing. …

[release-ocm-2.7] MGMT-14871: Copy Day2 BMH if Agent is installing

---

deploy/operator/setup_lso.sh

Instead of removing and re-adding every time a new OCP version gets introduced, this change just bumps our hack of using 4.13 catalog for LSO installation to OCP grater than 4.13.
/cc @adriengentil @gamli75

MGMT-15107: Bump version for hacking LSO catalog

---

internal/bminventory/inventory.go
internal/cluster/cluster.go
internal/constants/manifests.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
internal/manifests/api/interface.go
internal/manifests/api/mock_manifests_api.go
internal/manifests/api/mock_manifests_internal.go
internal/manifests/manifests.go
internal/manifests/manifests_test.go
internal/manifests/manifests_v2.go
internal/network/manifests_generator.go
internal/network/manifests_generator_test.go
internal/operators/manager.go
internal/operators/manager_test.go
subsystem/manifests_test.go

It has been reported that users have no way to determine whether or not a manifest is a custom manifest or one generated by the assisted-service. This PR introduces a change that uses the file system to store additional metadata about a manifest to indicate whether or not the manifest is a custom one.
For example, if the original file is stored in
```
"e09df13f-6f31-42c2-8361-2b5605f80e77/manifests/openshift/99-openshift-machineconfig-master-kargs.yaml"
```
Then, if an only if the manifest is custom -  a corresponding metadata file will be created in the following path.
```
"e09df13f-6f31-42c2-8361-2b5605f80e77/manifest-attributes/openshift/99-openshift-machineconfig-master-kargs.yaml/user-defined"
```
Any internally generated manifests are considered to be "non custom" and are created as …

MGMT-14704: Provide info on custom/vs non custom manifest in manifest endpoint.

---

docs/user-guide/day2-master/411-healthy.md

Minor clarification to apply yamls
Change cluster name to be the same along the doc

MGMT-14374: update day2 master docs

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

https://issues.redhat.com/browse/MGMT-14852
Epic: https://issues.redhat.com/browse/MGMT-13017
Removes setting automated cleaning mode to disabled by default, which lets the user set the field.
Part of the larger epic to allow wiping disks before installing by using Ironic's automated cleaning feature.

MGMT-14852: Allow AutomatedCleaningMode to be set by user

---

api/vendor/github.com/openshift/assisted-service/models/platform.go
models/platform.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/platform.go

MGMT-15064: Update is_external API description

---

internal/manifests/manifests.go
internal/manifests/manifests_test.go

Ensure that in any cases where we are writing or updating a manifest file that the filename does not contain any spaces.

MGMT-14726: Ensure that manifest filename does not contain spaces.

---

internal/bminventory/inventory.go
internal/ignition/dummy.go
internal/ignition/ignition.go
internal/ignition/mock_ignition.go
internal/installercache/installercache.go
internal/installercache/installercache_test.go
internal/oc/mock_release.go
internal/oc/release.go
internal/oc/release_test.go
pkg/generator/generator.go

There's nothing special about platform:none that requires it to use a different installer binary. This was originally done to avoid a problem with the openshift-baremetal-install binary not being available for non-x86 targets, but this was resolved by 1d025b8108 ([MGMT-9206](https://issues.redhat.com//browse/MGMT-9206)). We no longer need all this complexity.
This partially reverts commit f9b2f3d3246f91f7e80eab0b85eb9c34742eaa46. …

MGMT-15150: Use same installer binary for all platform types

---

internal/manifests/manifests.go
internal/manifests/manifests_test.go

Presently, if a manifest has no content then it passes validation. This breaks bootkube when empty content is submitted.
This PR validates that manifest content is not empty before accepting it.
Submitted an empty file to the API endpoint and observed that validation now fails.

MGMT-14634: Ensure that empty manifest may not be added.

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

When working with dual stack, and there is an attempt to update the machine networks only, they are not updated.  This change fixes it.
/cc @filanov

MGMT-15070: Unable to change machine-network with dual stack

---

cmd/main.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/mock_cluster_api.go
internal/cluster/progress_test.go
internal/cluster/transition_test.go
internal/manifests/api/interface.go
internal/manifests/api/mock_manifests_api.go
internal/manifests/api/mock_manifests_internal.go
internal/manifests/manifests.go
internal/manifests/manifests_test.go
internal/operators/odf/validation_test.go
subsystem/cluster_test.go

Presently when a cluster is reset, we perform all sorts of awkward workarounds to exclude files from deletion, when in reality all we should do is delete only the system generated manifests, leaving all other files and logs intact.
Moreover, when performing a permenant deletion, ALL files should be deleted.

MGMT-15073:Cluster reset - only system generated manifests to be deleted

---

internal/controller/controllers/agent_controller_test.go
internal/controller/controllers/csr_utils.go

Manual cherry-pick of https://github.com/openshift/assisted-service/pull/5322

[release-ocm-2.7] OCPBUGS-15152: Don't require key encipherment usage for approving CSRs

---

internal/bminventory/inventory.go
internal/oc/release.go
internal/oc/release_test.go

There's nothing special about platform:none that requires it to use a different installer binary. This was originally done (in f9b2f3d324) to avoid a problem with the openshift-baremetal-install binary not being available for non-x86 targets, but this was resolved by 1d025b8108 ([MGMT-9206](https://issues.redhat.com//browse/MGMT-9206)).
(Backported from #5346)

[release-4.12] MGMT-15150: Use same installer binary for all platform types

---

internal/manifests/manifests.go
internal/manifests/manifests_test.go

This reverts commit 10a88f557b971c66e2734d08b1e7526ed356f6df.
It was found that this validation is causing issues for the UI. We have some mitigations planned for the issues, however this commit needs to be rolled back for now to prevent ongoing breakage while the issues are addressed.

No-ISSUE: Revert "MGMT-14634: Ensure that empty manifest may not be added. (#5348)"

---

internal/ignition/ignition.go
internal/ignition/ignition_test.go

When applying manifests when installation is started, we should skip any
manifests that are of zero size to prevent them from causing bootstrap
problems later.
We can't validate zero size at the point of file upload as the UI is
presently using an approach where it uploads an empty manifest file to
track that the user wishes to add user defined manifests.
Discussions are underway to change this but for now we need to take this
alternative approach.
This PR implements this. …

MGMT-15243: Skip any zero size manifests when applying

---

internal/bminventory/inventory.go
internal/oc/release.go
internal/oc/release_test.go

There's nothing special about platform:none that requires it to use a different installer binary. This was originally done (in f9b2f3d324) to avoid a problem with the openshift-baremetal-install binary not being available for non-x86 targets, but this was resolved by 1d025b8108 ([MGMT-9206](https://issues.redhat.com//browse/MGMT-9206)).
(Backport from #5334)

[release-4.13] MGMT-15150: Use same installer binary for all platform types

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

MGMT-14491: Invalid node label returns error 500 instead of 400

---

internal/manifests/manifests.go
internal/manifests/manifests_test.go

While making a behavioural change to the way in which we list manifests https://github.com/openshift/assisted-service/commit/689a73c61b264d5e794d89e9a8f595a4ee920774 A bug was introduced. This bug causes a crash when manifests are listed.
This PR corrects the bug and introduces a test of the code in which the bug was found

MGMT-15295: Fix bug in list manifests

---

api/v1beta1/infraenv_types.go
cmd/agentbasedinstaller/client/main.go
cmd/agentbasedinstaller/register.go
config/crd/bases/agent-install.openshift.io_infraenvs.yaml
config/crd/resources.yaml
deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
internal/bminventory/inventory.go
internal/controller/controllers/infraenv_controller.go
internal/controller/controllers/infraenv_controller_test.go
subsystem/agent_based_installer_client_test.go
subsystem/kubeapi_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go

Users that install OCP on servers that communicate through transparent proxies must trust the proxy's CA for the communication to work.
The only way users can currently do that is by using both infraenv ignition overrides and install-config overrides. These are generic messy APIs that are very error prone. We should give users a more formal, simpler API to achieve both at the same time.
The epic surrounding this PR [MGMT-11520](https://issues.redhat.com//browse/MGMT-11520) aims to resolve this by allowing the user to specify an "Additional Trust Bundle", in essence the CA for the proxy.
This work has already been completed for the REST API in https://issues.redhat.com/browse/MGMT-11455
The aim of this PR is to ensure that the same changes are effective in KubeAPI CRD's
- [] Manual …

MGMT-11456: kube-api should allow user to specify infraenv additional trust bundle

---

pkg/validations/validations.go
pkg/validations/validations_test.go

https://issues.redhat.com/browse/OCPBUGS-16077
Both the TLD (base domain) validation and the full domain validation were incorrect. Originally,
the TLD didn't allow numbers and dashes; the
full domain validation didn't allow multiple
dashes. This fixes their regex to allow
these valid domains.
Domains such as `cat--rahul.com` and `do--main` will now be valid

OCPBUGS-16077: Fix DNS validation

---

api/v1beta1/infraenv_types.go
config/crd/bases/agent-install.openshift.io_infraenvs.yaml
config/crd/resources.yaml
deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
internal/controller/controllers/infraenv_controller.go
internal/controller/controllers/infraenv_controller_test.go
pkg/webhooks/agentinstall/v1beta1/infraenv_admission_hook.go
pkg/webhooks/agentinstall/v1beta1/infraenv_admission_hook_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go

Introduced a new property to InfraEnvSpec: `OSImageVersion`.
The property can be used for creating an InfraEnv through kube-api with a specific OS image version.
The `OSImageVersion` is useful for HyperShift flows which use late binding, hence, the InfraEnv isn't created according to a cluster version (thus, the latest OS image is used as a fallback).
Notes:
* The specified version should refer to an OSImage from the list in AgentServiceConfig, otherwise the condition is set to failure.
* When a ClusterRef is provided, we still use the cluster's version for creating the InfraEnv. Thus, The property should not be provided along with OSImageVersion to avoid a conflict (validated with a WebHook). …

MGMT-14923: add OSImageVersion to InfraEnvSpec

---

internal/ignition/ignition.go
internal/ignition/ignition_test.go
internal/ignition/templates/discovery.ign

**Background**
When we run our agent we set the proxy environment variables as can be seen here
When the user SSHs into the host, the shell does not have those environment variables set.
**Issue**
This means that when the user is trying to debug network connectivity (for example, in day-2 users often SSH to see why they can't reach the day-1 cluster's API), they will usually try to run curl to see whether they can reach the URL themselves, but it might behave differently than the agent because the shell, by default, doesn't use the proxy settings.
**Solution**
Set the default environment variables (through .profile) of the core and root shells to include the same proxy environment variables as the agent, so that when the user logs into the host to run commands, they would have the same …

MGMT-14793: Assisted discovery core and root user shell should have proxy environment set

---

api/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
internal/cluster/refresh_status_preprocessor.go
internal/cluster/validation_id.go
internal/cluster/validator.go
internal/cluster/validator_test.go
models/cluster_validation_id.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go

MGMT-15264: Block installation if no custom manifests in OCI cluster

---

hack/setup_env.sh

openssl/ossl_typ.h is missing when compiling
with golang-1.20.5 so installing openssl-devel
to cover the missing package.
When ACM compiles with 
```
FROM registry-proxy.engineering.redhat.com/rh-osbs/openshift-golang-builder:v1.20.1-1.202302170000.nofips.testonly.el8.ga291c02 AS go-builder
```
The following error happens
````
INFO - # vendor/github.com/golang-fips/openssl-fips/openssl
INFO - In file included from /usr/lib/golang/src/vendor/github.com/golang-fips/openssl-fips/openssl/aes.go:10:
INFO - ./goopenssl.h:17:10: fatal error: openssl/ossl_typ.h: No such file or directory
INFO -  #include <openssl/ossl_typ.h>
INFO -           ^~~~~~~~~~~~~~~~~~~~
INFO - compilation terminated.
````
Installing openssl-devel fixes this
Slack discussion …

NO-ISSUE: Add missing openssl package

---

.github/dependabot.yml

remove dependabot docker image changes
reason: following  downstream images 

MGMT-15343: dependabot remove docker

---

internal/provider/nutanix/consts.go
internal/provider/nutanix/ignition.go
internal/provider/registry/registry_test.go

- Prevent from the control-plane-machine-set operator from being degraded due to placeholder credentials on installation.
- Update prism central and prism element address placeholder, so it won't be confusing on post installation steps.
/ cc @eliorerz

MGMT-15128: Nutanix: Remove control plane machine set on OCP greater or equal to 4.14

---

cmd/agentbasedinstaller/client/main.go
cmd/agentbasedinstaller/register.go

The split is desired to enable the interactive flow. Users will register the cluster through the GUI instead of including the cluster information in the ignition/agent ISO.
registerCluster is able to detect if a cluster has already been registered with the REST-API and exits with status 0, skipping cluster registration from manifest files.
registerInfraEnv requires and checks that a cluster has been registered with the REST-API. It also skips infraenv registration if it detects one has already been created.
- [] None
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pu …

AGENT-557: Split register into registerCluster and registerInfraEnv

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/provider/common.go

Currently we check for the hosts supported platforms and return it without taking in any consideration if the platform is supported in the cluster openshift version or CPU architecture.
This PR uses feature support to remove the not supported platforms before returning the actual value to the user.
/cc @eliorerz

MGMT-15388: Remove unsupported platforms from the supported-platforms endpoint

---

Dockerfile.assisted-service
Dockerfile.assisted-service.ocp

MGMT-11949: MGMT-12278: Update libksba and libxml2

---

internal/bminventory/inventory.go
internal/ignition/dummy.go
internal/ignition/ignition.go
internal/ignition/mock_ignition.go
internal/installercache/installercache.go
internal/installercache/installercache_test.go
internal/oc/mock_release.go
internal/oc/release.go
internal/oc/release_test.go
pkg/generator/generator.go

Cherry-pick of https://github.com/openshift/assisted-service/pull/5334
https://issues.redhat.com/browse/MGMT-15413
---
* [MGMT-15150](https://issues.redhat.com//browse/MGMT-15150): Use same installer binary for all platform types
There's nothing special about platform:none that requires it to use a different installer binary. This was originally done (in f9b2f3d324) to avoid a problem with the openshift-baremetal-install binary not being available for non-x86 targets, but this was resolved by 1d025b8108 ([MGMT-9206](https://issues.redhat.com//browse/MGMT-9206)).
* Remove platform argument when extracting installer
Since we no longer use different installer binaries for different platforms, we no longer need to pass the platform type down. This allows us to clean up a lot of function …

[release-ocm-2.8] MGMT-15413: Use same installer binary for all platform types (#5334)

---

openshift/template.yaml

Parametrise envoy configmap name:
* can add private infra details
* can change it with much quicker build cycle (only app-interface MR instead of full service build)
/cc @osherdp @gamli75 @jhernand

MGMT-15424: parametrize envoy configmap name

---

.tekton/assisted-service-q2vh-pull-request.yaml
.tekton/assisted-service-q2vh-push.yaml

The build process requires tags to be presented (it runs git describe). Configure the pipeline to fetch the recent 100 commits and all the tags.

RHTAPBUGS-318: Fetch tag in RHTAP build

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

Before this, if a BMH existed in the cluster where BMAC was running and was both provisioned and deteched BMAC would set the detached annotation value to "assisted-service-controller" even if the BMH didn't have an infraenv label.
Resolves https://issues.redhat.com/browse/MGMT-15489

MGMT-15489: Don't set detached for BMHs without infraenv label

---

internal/host/validator.go

Change the user message from: 'Host is not compatible with cluster platform %s; either disable this host or choose a compatible cluster platform (%v)' to 'Host is not compatible with cluster platform %s; either disable this host or discover a new, compatible host.'

MGMT-15423: Change the user message when host is not compatible with platform type

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

Recently a validation was merged that prevents hardware details from being set on a BMH when inspection is enabled. This is blocking BMHs from being created on 4.14 spoke clusters when using converged flow with the following error:
```
time="2023-08-01T17:52:14Z" level=error msg="failed to create or update spoke BareMetalHost" func="github.com/openshift/assisted-service/internal/controller/controllers.(*BMACReconciler).reconcileSpokeBMH" file="/assisted-service/internal/controller/controllers/bmh_agent_controller.go:1008" agent=a04cbfd5-729e-4103-b9e1-a97435e19420 agent_namespace=assisted-installer bare_metal_host=ostest-extraworker-0 bare_metal_host_namespace=assisted-installer error="admission webhook \"baremetalhost.metal3.io\" denied the request: inspection has to be disabled for …
```

MGMT-15382: Ensure inspection is disabled on day-2 spoke node BMHs

---

internal/common/common_unitest_db.go

Sometimes when debugging unittest without skipper the 5 seconds timeout is not enough and will fail if the test start before DB container is ready.
This PR extend the waiting to 30 seconds which is most of the time is enough.
/cc @osherdp @adriengentil

NO-ISSUE: Extend waiting time to test DB container to be ready

---

internal/host/host_test.go
internal/host/hostrole_test.go
internal/host/monitor_test.go
internal/host/transition_test.go
internal/host/validations_test.go
internal/host/validator.go

If disk.EnableUUID flag is not enabled on vSphere VMs in any platform, including baremetal, then no symlinks are generated in /dev/disk/by-id for attached disks.
Installing ODF via LSO or something on such a platform results in somewhat fragile installation because disks themselves could be renamed on reboot and since no permanent ids exists for disks, the PVs could become invalid.
/cc @eliorerz

MGMT-15491: Validate vSphere disk.EnableUUID ignoring cluster platform

---

internal/manifests/manifests.go
internal/manifests/manifests_test.go

In [MGMT-15336](https://issues.redhat.com//browse/MGMT-15336) it was reported that it is possible to upload a file with the same name to the openshift and manifests directories when creating or updating a manifest.
Because of the way in which manifest files are later merged into a single directory, this leads to a scenario where the user may not be aware that a manifest uploaded to "openshift" has overwritten a manifest that was uploaded to "manifests".
To prevent any confusion, we should ensure that filenames are distinct between the two directories when attempting to create or upload a manifest.
This PR implements this functionality.
- [] None …

MGMT-15356: Ensure filenames are distinct between openshift and manifest directories.

---

hack/setup_env.sh

Without this this command was failing with the following output:
```
[2023-08-09 17:01:25] + /tmp/golang_installer
[2023-08-09 17:01:25] Welcome to the Go installer!
[2023-08-09 17:01:26] Downloading Go version go1.21.0
[2023-08-09 17:01:26] time 2023-08-04T20:14:06Z to /root/.go
[2023-08-09 17:01:26] This may take a bit of time...
[2023-08-09 17:01:26] Downloading Go from 400 Bad Request failed with HTTP status %!s(MISSING)
```
Also correct a minor typo in a function name.

MGMT-15525: Use go 1.18 when setting up environment

---

internal/host/validations_test.go
internal/host/validator.go

fix bug where host has failed validation when disk not been found.

MGMT-14881 - return a valid error when no disks has been found

---

internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go

Updating or setting install config is not relevant for day2 clusters because install config is not used in day2, the installer is not invoked in day2.
the issue that this change comes to resolve is when user is using backup restore on a multi node baremetal cluster that use install config overrides without specifying machine network that is calculated automatically from the hosts, it will mean that it will not be set in the spec and not going to be restored, in this case the controller will try to update the install config and get and error that machine network is not set for a baremetal cluster
This change  was tested in test-infra by creating an installed day2 cluster with install config overrides annotation, i saw that the spec was synced and had no errors
In addition i added a …

OCPBUGS-17992 day2 skip install config overrides

---

docs/hive-integration/README.md

Previously we said which fields could be set using annotations, but didn't document the annotation keys

Add BMH annotation keys to docs

---

hack/setup_env.sh

Even when using ``set -o errexit``, bash ignores exit codes when they are part of an explicitly tested command. Commands using ``&&`` are considered tested and therefore are not being checked.
For example, in the following job we eventually got to the following error:
```
./setup_env.sh: line 45: unzip: command not found
```
(see
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/5439/pull-ci-openshift-assisted-service-master-edge-e2e-metal-assisted/1694619719769788416)
But looking a few lines above, it shows that:
```
dnf install -y --setopt=skip_missing_names_on_install=False unzip
diffutils python3-pip genisoimage skopeo
Main config did not have a skip_missing_names_on_install attr. before
setopt
Main config did not have a …
```

Fix setup_env.sh failure handling

---

pkg/validations/validations.go
pkg/validations/validations_test.go

This reverts commit d052c2cff55394be61e1219f230185ed10782f1b.
We discovered a few regressions in behavior that may or may not be critical to customers. At the time being we're reverting this code and releasing a patch version so we can concentrate on delivering 2.24. A future fix will be developed in parallel.

Revert "Fix DNS validation (#5371)"

---

internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go

This fix handles cluster updates that patch UMN and VIPs at the same request. There was an issue in which the code overrode an empty VIPs array (which is how VIPs should get deleted) with a nil, indicating no update to this field.
This change also includes tests that validate those exact scenarios.

MGMT-15306: Fix UpdateCluster for requests that include VIPS and UMA

---

pkg/validations/validations.go
pkg/validations/validations_test.go

https://issues.redhat.com/browse/MGMT-15653
The previous DNS regex validation allowed domains
ending in a period '.' which is incorrect. It also did not allow base domains that had more than one
character before the dash. This fixes the domain
validation regex to ensure the issues mentioned
are fixed and adds a check for wildcard domains.
/cc @gamli75 @filanov

MGMT-15653: Fix DNS regex validation

---

.tekton/assisted-service-q2vh-pull-request.yaml
.tekton/assisted-service-q2vh-push.yaml

Auto upgrade is not clever enough, we need to remove the workspace section in this specific case

NO-ISSUE: update RHTAP deprecated image check

---

deploy/operator/capi/deploy_capi_cluster.sh
deploy/operator/hypershift/deploy_hypershift_cluster.sh

https://issues.redhat.com/browse/MGMT-15732
Hypershift install command can change or require
additional flags such as in this issue. This adds the variable in case we need to pass such flags in the future CI tests.

MGMT-15732: Add extra flag var for hypershift install

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

[MGMT-15559](https://issues.redhat.com/browse/MGMT-15559)
Day 2 workers create BMH and Machine CRs on the spoke cluster when the host starts installing. The non-converged flow initially added the detached annotation for the BMH when the host starts installing too. This causes the BMH to stop being reconciled so the BMH and Machine CRs aren't created in the spoke cluster.
This change adds the detached annotation when the host reaches rebooting, joined, or failed instead of installing so that it doesn't conflict with adding the BMH/Machine to the spoke cluster.
[MGMT-15639](https://issues.redhat.com/browse/MGMT-15639) …

MGMT-15559: Change detached annotation condition in non-converged flow

---

Dockerfile.assisted-service
Dockerfile.assisted-service-build
ci-images/Dockerfile.base

Now that D/S building system fully supports RHEL-9 base images (and allows easy installation of nmstate and other libs that were previously unsupported) we can move U/S to stream9 and D/S to ubi9-minimal.
It doesn't seem possible to easily use ubi9-minimal U/S, because installation of nmstate packages (and libvirt-libs) either requires entitlements running on a RHEL node, or maybe alternatively an access to RedHat's internal network (which can be a major problem for development U/S).
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-guid …

MGMT-15808: change base image to stream9

---

internal/uploader/auth_utils.go
internal/uploader/events_uploader.go

Email domain was set to Unknown by default for
clusters. This modifies the check for that and
ensures it's set to an actual email domain for
on-prem event uploading.
/cc @rccrdpccl

NO-ISSUE: Fix email domain for event uploader

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

https://issues.redhat.com/browse/MGMT-15559
Day 2 workers create BMH and Machine CRs on the spoke cluster when the host starts installing. The non-converged flow initially added the detached annotation for the BMH when the host starts installing too. This causes the BMH to stop being reconciled so the BMH and Machine CRs aren't created in the spoke cluster.
This change adds the detached annotation when the host reaches rebooting, joined, or failed instead of installing so that it doesn't conflict with adding the BMH/Machine to the spoke cluster.
Backport of PR https://github.com/openshift/assisted-service/pull/5445 …

[release-ocm-2.7] MGMT-15559: Change detached annotation condition in non-converged flow

---

client/manifests/v2_list_cluster_manifests_parameters.go
internal/manifests/manifests.go
internal/manifests/manifests_test.go
restapi/embedded_spec.go
restapi/operations/manifests/v2_list_cluster_manifests_parameters.go
restapi/operations/manifests/v2_list_cluster_manifests_urlbuilder.go
swagger.yaml
vendor/github.com/openshift/assisted-service/client/manifests/v2_list_cluster_manifests_parameters.go

Recently we made a change to the manifest list to filter out the system generated manifests when listing them.
This has led to issues with data gathering for triage which requires full access to all manifests, system generated or otherwise.
I have introduced a boolean parameter IncludeSystemGenerated which defaults to false. When set to true, the manifest list endpoint will show all manifests, irrespective of how they were created.
It is intended that we will make a change in assisted-test-infra that will send this parameter.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors …

MGMT-15598: Add a parameter to manifest list to disable filter

---

api/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
client/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
internal/feature/flags.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/hostcommands/instruction_manager.go
models/install_cmd_request.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/install_cmd_request.go

Send the feature flag through the install command to indicate if the skip mco reboot feature is enabled.
The relevant logic is logic is done by the assisted installer.

MGMT-15699: Service changes for avoiding MCO reboot

---

Dockerfile.assisted-service-build

For some reason it's no longer findable even though it seems like we correctly added the repository:
```
Complete!
Adding repo from:
https://download.docker.com/linux/centos/docker-ce.repo
CentOS Stream 9 - CRB                            12 MB/s | 5.7 MB
00:00
Last metadata expiration check: 0:00:02 ago on Mon Sep 18 13:28:09 2023.
No match for argument: docker-ce-cli
Error: Unable to find a match: docker-ce-cli
```
(see
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/5497/pull-ci-openshift-assisted-service-master-edge-images/1703760418561855488)
As we're no longer relying much about docker support (as podman takes preference) we are removing its installation in the assisted-service-build image. …

NO-ISSUE: fix docker-ce-cli package missing

---

.gitignore
internal/operators/odf/odf_operator.go
internal/operators/odf/odf_operator_test.go
internal/operators/odf/validation_test.go
internal/operators/odf/validations.go

This PR fixing issue where if one of the disk is small it will fail the validation even if there is sufficient disks 
* add new test cases for this scenario 
* return test disk to random UUID 

MGMT-15762 - fix odf validation failing where is one small disk

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/gencrypto/token.go
internal/imageservice/url_test.go
internal/imageservice/urls.go

Generate short URL in the infraenv to download discovery ISO, see the [enhancement](https://github.com/openshift/assisted-service/blob/master/docs/enhancements/short-url-enhancement.md) for more details.
Test locally if there are no issues updating an infraenv from the former URL to the short URL. Tested also the opposite if we do a rollback.

MGMT-14409: generate short image URL

---

deploy/operator/utils.sh
deploy/operator/ztp/add-worker-nodes-to-local-cluster-playbook.yaml
deploy/operator/ztp/add_day2_local_cluster_nodes.sh
deploy/operator/ztp/add_day2_remote_nodes.sh
deploy/operator/ztp/assisted-installer-crds-playbook.yaml
deploy/operator/ztp/infraEnv.j2

In [MGMT-15704](https://issues.redhat.com//browse/MGMT-15704) we introduced functionality to automatically import the local cluster into the infrastructure operator, this would make it possible to add nodes to the local cluster.
This commit is part of an effort (using the openshift/release project) to perform an E2E test. To support the test, we need to add an infraenv to support the addition of a node to the local cluster.
Most of the fields in this infraenv are intentionally preset to known defaults used by assisted-service with only the `ssh_public_key` field being injected by ansible. …

MGMT-15738: Support for E2E test, make sure we have an infraenv for adding a node to the local cluster.

---

OWNERS_ALIASES

Add adriengentil in order to align the configuration with other assisted repos.

MGMT-15507: Add adriengentil as approver in ocm-2.9

---

deploy/assisted-installer-ingress-tls.yaml
deploy/assisted-installer-ingress.yaml

Add short URL routes into the ingress object when deploying through the
scripts.

MGMT-15947: Add assisted images service short URL routes

---

pkg/validations/validations.go
pkg/validations/validations_test.go

DNS wildcard domain starts with validateNoWildcardDNS. The domain may have an optional trailing dot. Currently the assumption is that the trailing dot is mandatory for the domain name.
/cc @tsorya

MGMT-15950:  Fix DNS wilcard domain validation

---

internal/feature/flags.go

NO-ISSUE: Set default ENABLE_SKIP_MCO_REBOOT: false

---

internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go

This is a combination of 2 commits.
This is the 1st commit message:
**[MGMT-14416](https://issues.redhat.com//browse/MGMT-14416): VipDhcpAllocation from update params should take precedence (https://github.com/openshift/assisted-service/pull/5209)**
This change fixes a case where UserManagedNetworking and
VipDhcpAllocation are being changed at the same API update.
The ValidateClusterUpdateVIPAddresses func will now use VipDhcpAllocation
from update params, if relevant, before taking the DB cluster
VipDhcpAllocation into account.
Additionally, an additional error surfaced while fixing the aforementioned
issue, displaying a "User Managed Networking cannot be set with API VIP" to the user.
This change will also handle such a scenario by clearing up API and Ingress VIPs
that were set by DHCP, …

[release-ocm-2.8] MGMT-15306: Fix UpdateCluster for requests that include VIPS and UMA

---

deploy/operator/ztp/baremetalHost.j2
deploy/operator/ztp/infraEnv-latebinding.j2
deploy/operator/ztp/infraEnv.j2

https://github.com/openshift/assisted-service/pull/5550 was merged by mistake.
The installer params don't allow `--console` flags, using `--append-karg`
instead.

NO-ISSUE: Fix console output in ZTP jobs

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go

Assisted service will watch for hive.openshift.io/reconcile-pause annotation on cluster deployment in addition to the existing hold installation field in agent cluster install, the reason for the duplication is and integration with Ansible in ACM product that is not longer maintained so the implementation is done in Assisted
The logic will check both fields on day1 installation and if one of them is set the installation will be paused …

MGMT-15572 Hold installation when reconcile-pause annotation is set on cluster deployment

---

internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go

The 'validateClusterDeployment' func is ensuring that ImageSetRef is specified for day1 cluster.
Thus, it should be invoked **before** trying the create a cluster. This change moves the validation and fixing the day1 unit-test. Note that test passed before as it didn't check for a specific error. I.e. it actually failed due to 'Missing reference to pull secret'.

MGMT-15949: fix missing ImageSetRef validation

---

hack/setup_env.sh

Workaround to download kubectl 1.28.2 because kubectl 1.28.3 version doesn't
look to be propagated by the CDN and makes our CI jobs fail.
x-ref: https://github.com/kubernetes/k8s.io/issues/5996

MGMT-15997: use kubectl 1.28.2

---

internal/controller/controllers/agentserviceconfig_controller.go

In order to enable ValidatingWebhook on InfraEnv creation, added 'Create' to operations list.
E.g. the following error should be thrown when an InfraEnv is created with both clusterRef and osImageVersion:
```
Error from server (BadRequest): error when creating "infraEnv.yaml": admission webhook "infraenvvalidators.admission.agentinstall.openshift.io" denied the request: Either Spec.ClusterRef or Spec.OSImageVersion should be specified (not both).
``` …

MGMT-15980: added missing Create op to infraenvs Webhook

---

cmd/main.go

This will be released in ACM 2.10 and is being disabled by default for now.

NO-ISSUE: Disable local cluster import in ACM 2.9

---

internal/controller/controllers/agent_reclaimer.go
internal/controller/controllers/agent_reclaimer_test.go

[MGMT-16001](https://issues.redhat.com/browse/MGMT-16001)
Recently there have been errors running the reclaim agent when unbinding due to the daemonset's
container's name containing dots. This replaces all dot characters `.` with underscore characters `_`.

MGMT-16001: Sanitize reclaim daemonset name

---

.github/dependabot.yml

1. create groups for each `go.mod`
2. allowing updates for all versions 

NO-ISSUE: fixing dependabot issues

---

Dockerfile.assisted-service.ocp

Skopeo is missing from the ocp build of assisted-service, causing this error when using the 'multi' payload with agent installer:
```
'skopeo inspect --raw --no-tags docker://quay.io/openshift-release-dev/ocp-release:4.15.0-ec.0-multi --authfile /tmp/registry-config1256292744' 
exited with non-zero exit code -1: \nexec: \"skopeo\": executable file not found in $PATH"
```

Add skopeo to OCP build

---

docs/events.yaml
internal/common/events/events.go

MGMT-15902:  Add event that shows the number of reboots for a node before completing installation

---

internal/bminventory/inventory.go
internal/cluster/common.go
internal/stream/utils.go
internal/stream/utils_test.go
internal/usage/manager.go

When creating big clusters, we get kafka complaining about message size.
This should never happen: clusters should keep installation even if messaging fails.
Also, the message should never be this big. This PR attempts to address both issues.

MGMT-16037: fix messaging errors on big clusters

---

internal/manifests/manifests.go
internal/manifests/manifests_test.go

When validating the manifest file path, the assisted service presently returns a 400 (Bad Request) HTTP error code in the case of a request that contains invalid manifest file paths.
It has been pointed out that this should be a 422 (Unprocessable Entity) error code instead.
This PR changes the returned error code and updates tests to match.
- [] None

MGMT-15684: Return appropriate HTTP error code for invalid manifest file path

---

internal/manifests/manifests.go
internal/manifests/manifests_test.go

Presently when uploading a manifest, it's possible to upload a filename with just an extension, for example a filename '.yaml' is considered to be valid.
Clearly this is incorrect and this PR seeks to rectify this issue.
- [] None

MGMT-15683: Ensure that manifest filename has valid name part

---

api/vendor/github.com/openshift/assisted-service/models/boot.go
client/vendor/github.com/openshift/assisted-service/models/boot.go
models/boot.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/boot.go

With the support of zVM in Assisted Installer, the necessary kernel arguments to boot a zVM nodes need to be considered. During the first boot of a zVM node a parm file will be provided to activate the necessary devices or specify a static IP w/o nmstate. This parm file looks like:
rd.neednet=1 console=ttysclp0 coreos.live.rootfs_url=http://172.23.236.156:8080/assisted-installer/rootfs.img ip=10.14.6.3::10.14.6.1:255.255.255.0:master-0.boea3e06.lnxero1.boe:encbdd0:none nameserver=10.14.6.1 ip=[fd00::3]::[fd00::1]:64::encbdd0:none nameserver=[fd00::1] zfcp.allow_lun_scan=0 rd.znet=qeth,0.0.bdd0,0.0.bdd1,0.0.bdd2,layer2=1 rd.dasd=0.0.5235 rd.dasd=0.0.5236 random.trust_cpu=on rd.luks.options=discard ignition.firstboot ignition.platform.id=metal console=tty1 console=ttyS1,115200n8
These …

MGMT-15271: Add the boot command line to the host inventory

---

internal/cluster/validator.go
internal/cluster/validator_test.go

For plugins other than OVN/SDN (e.g. Calico), the clusterNetwork hostPrefix setting is not used so remove the validation. Since the networkType for plugins other than OVN/SDN can be passed in installconfig-overrides, that must also be checked.
Note that this is similar to the installer change to ignore the hostPrefix for these networkTypes - https://github.com/openshift/installer/pull/3888.
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.m …

OCPBUGS-19823: Ignore hostPrefix validation for plugins other than OVN/SDN

---

api/v1beta1/infraenv_types.go
config/crd/bases/agent-install.openshift.io_infraenvs.yaml
config/crd/resources.yaml
deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
internal/controller/controllers/infraenv_controller.go
internal/controller/controllers/infraenv_controller_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go

In [MGMT-11443](https://issues.redhat.com//browse/MGMT-11443) a download link was created for static network config.
This PR adds the generated URL for the static network to the infraenv if the static network config is defined.
- [] Bug fix
- [] None

MGMT-15405: Add a URL to infraenv to show download link from static network config

---

internal/provider/common.go
subsystem/kubeapi_test.go

The validator function CheckPlatformWrongParamsInput compares HighAvailabilityMode when it is possibly still nil. This fix is to access it safely.

MGMT-16052: Fix cluster HighAvailabilityMode nil pointer in update flow

---

cmd/graphstatemachine/main.go
cmd/main.go
internal/cluster/statemachine.go
internal/host/common.go
internal/host/config.go
internal/host/mock_transition.go
internal/host/monitor.go
internal/host/statemachine.go
internal/host/transition.go
internal/host/transition_test.go

When preparation fails for a host, we do not implement any kind of a timeout for the host to indicate that this has occurred.
This means that it is sometimes not possible for the user to determine the cause of a cluster timeout (which will inevitably be caused by the timeout of a host during preparation.)
Presently, there are two ways in which a host may time out (no result received within the cluster timeout)
- An inconclusive result from the pulling of cluster images
- An inconclusive result from the disk speed check
This PR introduces a timeout to detect these scenarios and report on them in a host timeout event so that the user may have a clue as to what has happened. 
This PR is in addition to [MGMT-15814](https://issues.redhat.com//browse/MGMT-15814) which introduces a cluster …

MGMT-15878: Ensure that hosts emit event showing why preparation failed.

---

deploy/operator/utils.sh

This was already assumed but it is not the case now

NO-JIRA:  Allow the command in wait_for_cmd_amount to receive arguments to pass to the inner function

---

cmd/main.go
go.mod
internal/controller/controllers/agent_controller.go
internal/oc/debug.go
internal/oc/debug_test.go
internal/spoke_k8s_client/factory.go

This is done for kube api client only when spoke kubeconfig is available.
The implementation is done using debug command (as in oc command). The number of reboots are counted by 'last reboot' linux command.
/cc @filanov

MGMT-15902: Trigger reboots for node event when day2 node moves to done

---

deploy/operator/utils.sh

This fixes a breaking change in CI that is caused by incorrect parameter handling.
- [] None

NO-ISSUE: Fix for error in wait_for_cmd_amount function

---

cmd/main.go
pkg/localclusterimport/import_local_cluster.go
pkg/localclusterimport/import_local_cluster_test.go

Presently, the locally imported hub cluster will show up in the UI of MCE as a "Disconnected" cluster.
This means that the end user will be unable to perform actions such as adding nodes to the cluster.
This PR addresses this issue by changing the naming, and namespacing of the AgentClusterInstall and ClusterDeployment CR's so that they reference the already existing ManagedCluster
Going to run up MCE UI and make sure that the Hosted Cluster shows up as "Connected" once automatically created
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-re …

MGMT-15971: Create ManagedCluster CR so that the hub will show up as "Ready" in MCE

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go

The commit db30aab7ba0b6b490f1d307c9837bdd700e72188 attempted to add TLS
to the service monitor but it forgot to change the scheme to https and
this was noticed during QE for the ticket associated with that commit
Solves [MGMT-14756](https://issues.redhat.com//browse/MGMT-14756)
- Ran a hub cluster and checked that servicemonitor was working

Add missing scheme to `ServiceMonitor`

---

internal/controller/controllers/infraenv_controller.go

NO-ISSUE: InfraEnv controller code cleanup

---

Dockerfile.assisted-service-debug

The debug image is broken because the version of delve is too old for v1.20 of go. This PR updates the debug image so that debugging may continue to work
- [] None
I made sure that debugging in subsystem tests works after the change when it did not before.

NO-ISSUE: Upgrade debug image to latest delve

---

deploy/operator/capi/deploy_capi_cluster.sh

After the initial changes were merged and rehearsed, small bugs were found. This PR attempts to fix them.
1. Corrected pull secret file passed into hypershift command.
2. Added service-cidr flag for ipv6
/cc @avishayt @filanov

HOSTEDCP-999: Minor fixes for disconnected CAPI CI

---

deploy/operator/capi/deploy_capi_cluster.sh

Initial PRs missed adding service-cidr flag for hypershift cluster creation for ipv6.
See previous, which added it only for dual-stack
https://github.com/openshift/assisted-service/pull/5713

HOSTEDCP-999: Missed service-cidr for capi ipv6 CI test

---

cmd/main.go
internal/hardware/mock_validator.go
internal/hardware/validator.go
internal/hardware/validator_test.go
internal/host/host_test.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/transition_test.go
internal/host/validations_test.go
internal/host/validator.go

Allow booting from iSCSI for x86_64 OpenShift versions at least 4.15.0 on the OCI platform.

MGMT-16273: Allow installing on iSCSI disks on OCI

---

deploy/operator/capi/deploy_capi_cluster.sh

Incorrectly checked if the the CAPI Agent image in CI was missing when it should check if it's set.
Affects CI testing disconnected.
/cc @filanov @avishayt

HOSTEDCP-999: Fix incorrect check for CAPI image in ci

---

api/vendor/github.com/openshift/assisted-service/models/cluster.go
api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
client/vendor/github.com/openshift/assisted-service/models/cluster.go
client/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
client/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
internal/migrations/20231010101010_drop_cluster_api_vip_and_ingress_vip.go
internal/migrations/20231010101010_drop_cluster_api_vip_and_ingress_vip_test.go
internal/migrations/migrations.go
models/cluster.go
models/cluster_create_params.go
models/v2_cluster_update_params.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/api/build/v1/generated.proto
vendor/github.com/openshift/api/build/v1/types.go
vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/assisted-service/models/cluster.go
vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go

Additionaly, add a db migration to populate those VIPs in api_vips and ingress_vips arrays.

MGMT-15972: Remove Swagger definition for api_vip and ingress_vip

---

internal/controller/controllers/agent_controller.go
subsystem/kubeapi_test.go

Presently when a user updates a secret assosciated with the ignition endpoint token of a host, no agent reconciliation is performed. This means that the host associated with any agents that use that ignition endpoint token will not be updated.
This PR fixes that by adding a watch on secrets that will then map to agents that need to be updated as a result of the change.
- [] None
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTR …

MGMT-16235: Ensure that agent controller will watch for changes to ignition endpoint token.

---

deploy/operator/capi/deploy_capi_cluster.sh

Previously, the ICSP pointed to the incorrect mirror registry URL for OCP. OCP release was already mirrored in deploy/operator/deploy.sh and this change now uses that mirrored registry URL for the ICSP.
/cc @filanov @avishayt

HOSTEDCP-999: Fix incorrect ICSP for CAPI CI

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

Becuase of a recover function in V2UpdateHostIgnition if a panic occurs
then a controller will get nil as a reply and assume that the call
didn't fail, it casued a hot loop that tried to update the ignition
again and again, because and event was called before the panic and
before the ignition was commited we ended up with 95 million events
before we ran out of space on the disk
This commit will remove the recover in order to return a proper error
and fail the service if tehre is a painc
The pacin was caused by calling setIgnitionConfigOverrideUsage and
assuming that cluster ID exists, added a validation for the cluster id
before using it.
added unit tests to check functionality to unbound host …

MGMT-16312 fix update host ignition for unbound host

---

deploy/operator/gather.sh

https://issues.redhat.com/browse/MGMT-14605
Collects more relevant data and logs for hypershift tests. Includes:
1. hostedcluster nodes
2. hostedcluster pods yamls and logs
3. hypershift pods' operator logs
/cc @eranco74

MGMT-14605: Gather more data for hypershift tests

---

deploy/operator/common.sh
deploy/operator/setup_assisted_operator.sh

When deploying the operator, OS_IMAGES env var should propagate if already defined.
This should solve e2e failures of jobs that use superfluous storage. I.e. download all OS images, instead of the ones in the list filtered by test-infra.
In addition, passing 'osImages' to AgentServiceConfig to propagate the filtered list to assisted-image-service.

MGMT-16250: Propagate OS_IMAGES var in operator deploy

---

internal/featuresupport/features_misc.go
internal/host/hostcommands/install_cmd_test.go

Image overwriting fails on s390x.  It leaves the disk in unstable state which causes the installation to fail.
/cc @filanov

MGMT-16303: Disable skip MCO reboot for architecture s390x

---

Makefile

This would enable us to pass BUILD_TAGS from downstream build to produce, for instance, FIPS-enable artifacts

NO-ISSUE: add build tags option

---

Dockerfile.assisted-service-build
ci-images/Dockerfile.lint

app-sre made their repo mirroring golangci-lint private for legal reasons, and
now our jobs are failing to install it. Installing it now from the cli.
We could also have pulled golangci-lint from dockerhub, but rate
limitation there is quite aggressive.

NO-ISSUE: fix golangci-lint failing to be pulled

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/cluster/registrar.go
internal/cluster/transition.go
internal/operators/handler/handler.go

The downside of recover is that it may hide bugs like accessing nil pointer and can create a situation where a function panic and instead of returning an error it will return nil, in some cases it cause a hot loop in our controllers, or just move a bug to an upper later.
To avoid those situations we decided to remove the recover function usage in the transaction code and move to a new transaction style that will make scope of the transaction and handling of errors clearer. …

MGMT-16157 Remove recover usage from DB transactions

---

Dockerfile.assisted-service-build
ci-images/Dockerfile.lint

app-sre made their repo mirroring golangci-lint for legal reasons, and
now out jobs are failing to install it. Installing it now from the cli.
We could also have pulled golangci-ling from dockerhub, but rate
limitation there is quite aggressive.

[release-ocm-2.8] MGMT-16370: fix golangci-lint failing to be pulled

---

internal/bminventory/inventory.go
internal/cluster/registrar.go
internal/events/event.go
internal/host/host_test.go
internal/host/transition_test.go

The new format will reduce the need for a defer function to handle db transaction failues and avoid hiding panic in case somone will add a recover function
make the code shorter and cleaner

MGMT-16157 move db transactions to new format

---

internal/cluster/cluster.go
internal/cluster/cluster_test.go
subsystem/cluster_test.go

When the user downloads the logs for the cluster, we would like to include any cluster manifets in these logs so that they may be examined.
Manually set up a cluster with manifests and then triggered a download of the manifests, a CURL request similar to 
`curl -X GET $SERVICE_URI/api/assisted-install/v2/clusters/61e94f28-bbd7-4719-b555-d7d7f9d5cc60/logs?logs_type=all --output logs.tar.gz` was used. 
I also checked in the UI to ensure that the download looks appropriate.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-mess …

MGMT-14633: Include manifest information in the log download

---

pkg/validations/validations.go
pkg/validations/validations_test.go
subsystem/cluster_test.go

https://issues.redhat.com/browse/MGMT-15886
Modify domain validation to adhere to the RFC standard for domains https://datatracker.ietf.org/doc/html/rfc1034#section-3.5 
Rules for labels:
1. start with a letter
2. end with a letter or digit
3. and have as interior characters only letters, digits, and hyphen
Domains contains either one label or multiple labels separated by a period.
Top level (base) domains must have at least two characters and cannot end in a dash. …

MGMT-15886: Fix domain validation

---

internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go

Before this change a user would get an error if, for example, arm64 was provided in the infraenv, but aarch64 was provided in the BMH when in reality those should match.
Resolves https://issues.redhat.com/browse/MGMT-16047
Unit tests

MGMT-16047: Compare normalized infraenv and preprov image architectures

---

deploy/operator/setup_lso.sh

LSO is now avilable on 4.15 catalog 
- Removing workaround for 4.15 ( deploy 4.14 version )
- updating OPM version 

MGMT-16420: enable latest lso for 4.15 ztp

---

internal/migrations/20231219105000_update_oci_to_external_platform_type.go
internal/migrations/20231219105000_update_oci_to_external_platform_type_test.go
internal/migrations/migrations.go

Update existing clusters with platform type oci to use the external platform type

MGMT-16428: create migration from oci to external platform type

---

internal/controller/controllers/infraenv_controller.go
subsystem/kubeapi_test.go

Presently when an infraenv is created via KubeAPI for the S390x architecture it is created with the default "minimum-iso" imagetype. This is incompatible with S390x.
This PR makes sure that the imagetype is updated to "full-iso" to maintain compatibility.
- [] None

MGMT-16373: KubeAPI - Ensure that ISO type is full-iso when cpuarchitecture is S390x

---

Dockerfile.assisted-service
dev-requirements.txt

Bump `requests` package and change `pybuilder` to use am image which is more python 'pure' with more recent python

MGMT-16216: Bump requests package, change to a pure python builder

---

internal/controller/controllers/infraenv_controller.go
subsystem/kubeapi_test.go

When deleting an NMStateConfig CR, the discovery ISO and static network config are not updated accordingly. I.e. the previous config remains intact. Hence, ensure that the StaticNetworkConfig is emptied when the CR is deleted (set on InfraEnvUpdateParams).

OCPBUGS-25434: handle NMStateConfig deletion

---

internal/cluster/cluster.go
subsystem/cluster_test.go

It seems there is a small variation between the Object Store and S3 implementations. This means that the "Download Cluster Logs" test fails locally while passing on AWS.
I have updated the test so that it passes locally by generating a filename in a way that is consistent in both environments.
- [] None

NO-ISSUE: Fix for subsystem test that fails locally.

---

api/vendor/github.com/openshift/assisted-service/models/last_installation_preparation.go
client/vendor/github.com/openshift/assisted-service/models/last_installation_preparation.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/transition_test.go
models/last_installation_preparation.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/last_installation_preparation.go

A recent change to how cluster installation is presented introduced a bug that caused problems when encountering an
error during installation. On fixing the error, the user would have to start the installation twice in order to move
to the `installing` state.
This issue addresses that by resetting the LastInstallationPreparationStatus when an installation is started.

MGMT-16241: Ensure that LastInstallationPreparationStatus is reset on cluster install.

---

internal/bminventory/inventory.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go

When setting VIPs data for DHCP vips allocation, the VIPs tables are not loaded.  This causes the VIPs to be always be updated when VIPs allocation response arrives from host.
NO-ISSUE: Remove redundant AfterEach in SetVipsData tests

MGMT-16505: Huge amount of "Cluster was updated with api-vip <IP ADDRESS>, ingress-vip <IP ADDRESS>" in cluster events

---

internal/featuresupport/feature_support_test.go
internal/featuresupport/features_networking.go
internal/featuresupport/features_olm_operators.go
internal/featuresupport/features_olm_operators_test.go

- allowing deployment for multi node LVMS on 4.15+ 
- creating separated file for olm feature testing
- full unit testing for all LVM deployments and versions
- fixing feature support levels as follows
- 4.11 dev preview
- 4.12 - 4.14  supported  only SNO (GA )
- 4.15:
- supported SNO (GA )
- Multi node (GA )

MGMT-16332: allow lvms on multi node

---

cmd/agentbasedinstaller/register.go

Ensure that any passwords included in installConfigOverrides are redacted in logs.

OCPBUGS-24428: Redact passwords logged in installConfigOverrides

---

api/vendor/github.com/openshift/assisted-service/models/cluster_progress_info.go
api/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
client/vendor/github.com/openshift/assisted-service/models/cluster_progress_info.go
client/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
cmd/main.go
docs/events.yaml
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/common.go
internal/cluster/finalizing_stages.go
internal/cluster/finalizing_stages_test.go
internal/cluster/mock_cluster_api.go
internal/cluster/mock_transition.go
internal/cluster/progress_test.go
internal/cluster/statemachine.go
internal/cluster/transition.go
internal/cluster/transition_test.go
internal/cluster/validator_test.go
internal/common/events/events.go
internal/host/common.go
internal/operators/odf/validation_test.go
models/cluster_progress_info.go
models/finalizing_stage.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/cluster_progress_info.go
vendor/github.com/openshift/assisted-service/models/finalizing_stage.go

Add the controller stages and the timeouts handling to the assisted service.  This includes handling both for "soft" and "hard" timeouts.
Add API handling for reporting controller timeouts.
Add new event for soft finalizing stage timeouts
/cc @filanov

MGMT-16208: Add controller stages to assisted service

---

pkg/validations/validations.go
pkg/validations/validations_test.go
subsystem/cluster_test.go

[OCPBUGS-27376](https://issues.redhat.com/browse/OCPBUGS-27376)
[RFC 1034](https://datatracker.ietf.org/doc/html/rfc1034#section-3.5) initially stated domain names should only start with a letter, but that was later revised by [RFC 1123](https://datatracker.ietf.org/doc/html/rfc1123#page-13). Updates the domain regex to allow domains to start with a number. Also adds a check to prevent dotted decimal domains. 
Includes changes that also check for the length of domains. [RFC 1123](https://datatracker.ietf.org/doc/html/rfc1123#page-13) also states that a label must be no more than 63 characters and a full domain must be no more than 255 characters.
Revision to the previous incorrect PR https://github.com/openshift/assisted-service/pull/5801 …

OCPBUGS-27376: Allow domain names starting with a number

---

internal/featuresupport/feature_support_test.go
internal/featuresupport/features_platforms.go

Update feature support to return tech-preview for OCI platform feature
from OCP 4.15.
Fixes [MGMT-16661](https://issues.redhat.com//browse/MGMT-16661) that should return dev-preview for OCI platform feature
for OCP 4.14.

MGMT-16660: OCI is tech-preview from OCP 4.15

---

deploy/assisted-service.yaml
deploy/podman/configmap-disconnected.yml
deploy/podman/configmap.yml
deploy/podman/configmap_tls.yml
internal/uploader/events_uploader.go
internal/uploader/events_uploader_test.go
internal/uploader/uploader.go
openshift/template.yaml

[MGMT-16517](https://issues.redhat.com/browse/MGMT-16517)
Adds the environment variables `DEPLOYMENT_TYPE`
and `DEPLOYMENT_VERSION` to determine how assisted was deployed. Expected values for deployment type
include ACM, MCE, ABI, podman, standalone operator.
Also changes the versions file to metadata file to encompass the new data.
/cc @rccrdpccl

MGMT-16517: Add Env Var for On-Prem Data Deployment Type

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go

https://issues.redhat.com/browse/MGMT-16521
Read the deployment data from the environment
variables when deploying with the operator.
Possible values include ACM, MCE, and operator
(indicates stand-alone operator).
The block querying for ACM and MCE deployments
are a temporary work-around until ACM/MCE
allows injecting environment variables into the
infrastructure operator deployment.
https://issues.redhat.com/browse/ACM-9362
Slack thread context https://redhat-internal.slack.com/archives/CUEMEHRA9/p1704996574257619
Test steps:
1. Built operator image with changes
2. Deploy ACM in OCP 4.14 aws cluster (from cluster bot)
3. Paused MCE and used operator image in infrastructure operator deployment
````
$ oc annotate multiclusterengine multiclusterengine pause=true
$ oc edit deploy …
```

MGMT-16521: Identify Operator-based Deployment Data

---

pkg/validations/validations.go
pkg/validations/validations_test.go
subsystem/cluster_test.go

Backport of PR #5914
https://issues.redhat.com/browse/MGMT-16717
https://issues.redhat.com/browse/OCPBUGS-27376
RFC 1034 initially stated domain names should only start with a letter, but that was later revised by RFC 1123. Updates the domain regex to allow domains to start with a number. Also adds a check to prevent dotted decimal domains. Includes changes that also check for the length of domains. RFC 1123 also states that a label must be no more than 63 characters and a full domain must be no more than 255 characters.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guid …

[release-ocm-2.9] MGMT-16717: Allow domain names starting with a number (#5914)

---

pkg/validations/validations.go
pkg/validations/validations_test.go
subsystem/cluster_test.go

Cherry pick of PR #5914
https://issues.redhat.com/browse/MGMT-16719
https://issues.redhat.com/browse/OCPBUGS-27376
RFC 1034 initially stated domain names should only start with a letter, but that was later revised by RFC 1123. Updates the domain regex to allow domains to start with a number. Also adds a check to prevent dotted decimal domains. Includes changes that also check for the length of domains. RFC 1123 also states that a label must be no more than 63 characters and a full domain must be no more than 255 characters.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/g …

[release-ocm-2.7] MGMT-16719: Allow domain names starting with a number (#5914)

---

pkg/validations/validations.go
pkg/validations/validations_test.go
subsystem/cluster_test.go

Cherry pick of PR #5914
https://issues.redhat.com/browse/MGMT-16718
https://issues.redhat.com/browse/OCPBUGS-27376
RFC 1034 initially stated domain names should only start with a letter, but that was later revised by RFC 1123. Updates the domain regex to allow domains to start with a number. Also adds a check to prevent dotted decimal domains. Includes changes that also check for the length of domains. RFC 1123 also states that a label must be no more than 63 characters and a full domain must be no more than 255 characters.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/g …

[release-ocm-2.8] MGMT-16718: Allow domain names starting with a number (#5914)

---

internal/featuresupport/feature_support_test.go
internal/featuresupport/features_olm_operators.go
internal/featuresupport/features_olm_operators_test.go
internal/featuresupport/features_platforms.go

`CNV` and `MCE` should be disabled when select platform `Nutanix` as it is not supported by `OCP`

MGMT-16739: CNV and MCE should be disabled when select platform Nutanix

---

deploy/operator/gather.sh

Agentclusterinstall and clusterdeployment queried only for objects in the spoke namespace, which is not applicable in the hypershift/capi space. This modifies it to look for all those CRs in all the namespaces.

NO-ISSUE: Fix CI gather script for baremetal operator

---

internal/host/hostcommands/tang_connectivity_check_cmd.go
internal/host/hostcommands/tang_connectivity_check_cmd_test.go
internal/host/validator.go

In line 41 of internal/host/hostcommands/tang_connectivity_check_cmd.go
Both `luks` and `luks.Clevis` are pointers which can be nil, there was no checking in place to ensure that we avoid a nil pointer dereference
This PR fixes that by making appropriate checks to ensure that neither of these pointers are nil.

MGMT-16721: handle hosts with no luks

---

api/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
client/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
docs/events.yaml
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/finalizing_stages.go
internal/cluster/statemachine.go
internal/cluster/transition.go
internal/cluster/transition_test.go
internal/common/events/events.go
models/finalizing_stage.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/finalizing_stage.go

OLM operators are not considered mandatory for installation. Therefore, they are treated as soft timeouts even if soft timeouts are not enabled.
When assisted installer detects that one of the OLM stages is timed out, it stops working on the current stage and moves to the next finalizing stage.
/cc @gamli75 
/cc @carbonin

MGMT-16684: Make OLM finalizing stages behave as soft timeouts even if soft timeouts are not enabled

---

api/vendor/github.com/openshift/assisted-service/models/cluster.go
client/vendor/github.com/openshift/assisted-service/models/cluster.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/transition.go
internal/cluster/transition_test.go
internal/host/conditions.go
internal/host/transition_test.go
models/cluster.go
pkg/ocm/utils.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/cluster.go

We would like to control invocation of soft timeouts based on organizational permissions.  Therefore, capability for allowing soft timeouts was added.
This capability is used in conjunction with corresponding soft timeouts environment variable.  Soft timeouts will be used for cluster insallation if both it is enabled by the assisted service environment variable and if it is allowed by capability.
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBU …

MGMT-16704: Add organization capability to control soft timeouts

---

api/vendor/github.com/openshift/assisted-service/models/host.go
client/vendor/github.com/openshift/assisted-service/models/host.go
internal/host/common.go
internal/host/conditions.go
internal/host/host_test.go
internal/host/mock_transition.go
internal/host/refresh_status_preprocessor.go
internal/host/statemachine.go
internal/host/transition.go
internal/host/transition_test.go
models/host.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/host.go

When soft timeouts are enabled and host is disconnected while installing, send indication that such timeout occured and continue installation.
The indication is special status-info and event generation. When the hosts reconnects, another status-info is emitted indicating that the host is now connected.
/cc @avishayt 
/cc @carbonin

MGMT-16625: Make host connection timeout soft

---

internal/host/validations_test.go
internal/host/validator.go
subsystem/day2_cluster_test.go

Currently, the `assisted-service` code attempts to validate host compatibility with the cluster at - https://github.com/openshift/assisted-service/blob/99a3b96819cade4b6d7ae142d663cd53dde731fb/internal/host/validator.go#L359C21-L359C50. 
However, this validation seems unjustified because every `day2` cluster is expected to pass it, given their kind is `addHostsCluster`. We want to validate the host's platform against the cluster's platform, so the mentioned line of code should be removed.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message …

MGMT-16588: Adding host with incompatible platform to day2 cluster should fail

---

internal/bminventory/inventory.go
internal/host/hostutil/test_utils.go
internal/operators/cnv/cnv_operator.go
internal/operators/cnv/cnv_operator_test.go
internal/operators/lvm/config.go
internal/operators/lvm/lvm_operator.go
internal/operators/lvm/lvm_operator_test.go
internal/operators/lvm/manifest.go
internal/operators/lvm/manifests_test.go
internal/operators/manager.go

Fixing requirements for LVM multinode deployment
1. full cluster should require disk on worker nodes only
2. full cluster shouldn't allow auto assign 
3. fixing requirment calculation 
4. adding tests for requirements  resources 

MGMT-16332: fix validation for LVM multinode

---

subsystem/kubeapi_test.go

The error message for an invalid nmstate config has changed from containing "Unsupported keys found" to "Invalid YAML string: unknown field". See kubeapi subsystem test history for failing tests https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-assisted-service-master-edge-subsystem-kubeapi-aws
/cc @gamli75

NO-ISSUE: Fix subsystem test for invalid nmstate config error message

---

cmd/main.go
deploy/assisted-service.yaml
deploy/podman/configmap-disconnected.yml
deploy/podman/configmap.yml
deploy/podman/configmap_tls.yml
internal/uploader/events_uploader.go
internal/uploader/events_uploader_test.go
internal/uploader/uploader.go
openshift/template.yaml

Backport of PRs: 
1. https://github.com/openshift/assisted-service/pull/5514 to add the versions file when sending onprem data
2. https://github.com/openshift/assisted-service/pull/5874 (https://issues.redhat.com/browse/MGMT-16517) to add environment variable DEPLOYMENT_TYPE 
3. https://github.com/openshift/assisted-service/pull/5967 (https://issues.redhat.com/browse/MGMT-16523) to set it to ABI when it's an agent-based install …

[release-4.14] MGMT-16517: Add Env Var Deployment Type & Set ABI

---

api/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
client/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/finalizing_stages.go
internal/cluster/mock_cluster_api.go
internal/cluster/statemachine.go
internal/cluster/transition.go
models/finalizing_stage.go
restapi/embedded_spec.go
subsystem/cluster_test.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/finalizing_stage.go

Since all status changes are now handled by the assisted service, complete installation will only report operator status in case of failure in the controller.
/cc @tsorya

MGMT-4458: Remove status change from old CompleteInstallation API

---

cmd/agentbasedinstaller/client/main.go
cmd/agentbasedinstaller/import.go

This patch adds a CLI command to ABI that will be called by an agent-import-cluster service running on the day2 add-nodes ISO to register an existing cluster to assisted-service as part of the day2 workflow.

AGENT-860: Add command to import cluster for agent-based-installer

---

internal/operators/lvm/lvm_operator.go

MGMT-16995 fixing lvm requirement message

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

OCPBUGS-29772: All nodes fail to become managed when installConfigOverrides defined
We are marshalling install config as yaml and this actually causing it to return with empty values, moving to json fixes the issue

OCPBUGS-29772: All nodes fail to become managed when installConfigOverrides defined

---

internal/operators/lvm/lvm_operator.go
internal/operators/lvm/lvm_operator_test.go

MGMT-17008: fix lvm host requirement

---

cmd/main.go

There have been several reported issues with this feature and we need to look at this further. To unblock the ACM release, we are disabling the feature.
/cc @carbonin

MGMT-17095: Disable local cluster import

---

internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go

Before this, when deploying an IPv6 spoke from a dualstack hub only the machine network was being used to determine the address family of the spoke cluster.
This was an issue because the machine network is not generally set until after hosts are discovered.
This change uses all the cluster networks to determine the address family and should allow the preprovisioning image controller to correctly determine the IP family and set the ironic and inspector urls accordingly.
Resolves https://issues.redhat.com/browse/MGMT-16814
QE will test this fix fully before merge

MGMT-16814: Use all cluster networks to determine IP family for ironic

---

cmd/agentbasedinstaller/register.go

Fixes OCPBUGS-27787, requires https://github.com/openshift/installer/pull/7349 as well.

OCPBUGS-27787: Use multi payload with ABI

---

config/rbac/role.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
internal/controller/controllers/agentserviceconfig_controller.go
pkg/localclusterimport/import_local_cluster.go
pkg/localclusterimport/import_local_cluster_test.go
pkg/localclusterimport/local_cluster_import_operations.go
pkg/localclusterimport/local_cluster_import_operations_mocks.go

The settings for HTTPProxy and HTTPSProxy should be copied to the AgentClusterInstall that is created during the import of the local cluster.
This PR ensures that this takes place.

MGMT-16759: Copy cluster proxy settings to imported local-cluster AgentCluster Install

---

docs/user-guide/install-customization.md

Disabling capabilities could cause problems in some situations, e.g. disabling the baremetal-operator on a baremetal platform cluster will cause installation to fail. The docs should be more clear about these consequences.
```
Mar 06 15:38:49 master1 bootkube.sh[5424]: "99_openshift-cluster-api_master-machines-0.yaml": failed to create machines.v1beta1.machine.openshift.io/minimal-xkgn9-master-0 -n openshift-machine-api: the server could not find the requested resource
``` …

NO-ISSUE: Docs - clarifying consequences of capabilities override

---

pkg/auth/auth_handler_test_utils.go
pkg/auth/rhsso_authenticator.go

The `clientId` claim will be replaced by `client_id` from the SSO server in order to be compliant with the OAuth2 specification. During a transition period the old `clientId` will be preserved. This patch changes our code so that it first tries to use the newer and more correct `client_id`, and then if it doesn't exist it tries the older `clientId`.
In the future we should check if we are really using the value of this `client_id` claim at all. If we aren't then it would probably be good to remove the code completely.
Related: https://issues.redhat.com/browse/MGMT-16766
Related: https://datatracker.ietf.org/doc/html/rfc9068#section-2.2 …

MGMT-16766: Use `client_id` instead of `clientId`

---

internal/versions/versions.go
internal/versions/versions_test.go
subsystem/operators_test.go

https://issues.redhat.com/browse/MGMT-16813
Previously, the `getReleaseImageFromCache` would get all release
images that included the CPU architecture and return the first
instance it found that matched the desired Openshift version.
Since multi-arch images include the CPU architecture, it led
to undesireable selection of the multi-arch image over the
exact matching image with the specified CPU architecture.
This fix ensures that the release image will be found with
the following priority:
1. Exact CPU Architecture & OpenShift x.y.z version match
2. Exact CPU Architecture & OpenShift Major Minor (x.y) version match
3. Multi-arch CPU with specified CPU Architecture & OpenShift x.y.z version match
4. Multi-arch CPU with specified CPU Architecture & OpenShift Major Minor (x.y) version match …

MGMT-16813: Prioritize finding release image with exact CPU architecture

---

cmd/agentbasedinstaller/client/main.go
cmd/agentbasedinstaller/host_config.go

for day-2/addnodes workflow.
Updated the LoadHostConfigs function to only load the current host's HostConfig if the workflow is addnodes.
Only the current host's HostConfig is needed because each host in the addnodes workflow has its own assisted-service. Loading other node's HostConfigs would cause the apply-host-config service to continually wait for other hosts to register with assisted-service because each node is added in isolation. …

AGENT-860: Update configure command to handle multiple HostConfigs

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

On s390x there are some network configurations where MAC addresses are not static and lead to issues using Assisted Installer, Agent based Installer and HCP (see attached net conf).
For AI and HCP there is a possibility to patch kernel arguments but using the UI there is a separate manual step needed using the API. This will be a bad user experience.
In addition patching the kernel arguments for ABI is not possible.
To solve this, a config override parameter need to be added to the parm file by the user and the ip settings will be automatically passed to the coreos installer regardless what the user configure (DHCP or static IP using nmstate).
See matrix in ticket:
https://issues.redhat.com/browse/MGMT-17196
Doc ticket:
https://issues.redhat.com/browse/MULTIARCH-4537
- [x ] Bug fix
- …

MGMT-17196: Fix none existens of static MAC adr. in case of specific network devices on s390x.

---

api/vendor/github.com/openshift/assisted-service/models/create_manifest_params.go
api/vendor/github.com/openshift/assisted-service/models/update_manifest_params.go
client/vendor/github.com/openshift/assisted-service/models/create_manifest_params.go
client/vendor/github.com/openshift/assisted-service/models/update_manifest_params.go
docs/user-guide/install-customization.md
internal/manifests/manifests.go
internal/manifests/manifests_test.go
models/create_manifest_params.go
models/update_manifest_params.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/create_manifest_params.go
vendor/github.com/openshift/assisted-service/models/update_manifest_params.go

Presently we do not accept filenames containing *yml.patch* or *yaml.patch*
We should accept these files.
This PR rectifies that.
Performed curl requests against an assisted-test-infra based cluster that is running this service image. *yml.patch* and *yaml.patch* files were accepted as expected.

MGMT-16002: Accept *yml.patch* and *yaml.patch* extensions

---

internal/cluster/common.go
internal/cluster/mock_transition.go
internal/cluster/statemachine.go
internal/cluster/transition.go
internal/cluster/transition_test.go

Missing 24h statemachine transition for soft timeouts was added.
/cc @gamli75 
/cc @tsorya

MGMT-17241: [soft-timeout] Installation not timeout /aborted after 24 Hours

---

Makefile
config/manager/manager.yaml
config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
deploy/podman/pod-persistent-disconnected.yml
deploy/podman/pod-persistent.yml
deploy/podman/pod.yml
deploy/podman/pod_tls.yml
deploy/postgres/postgres-deployment-ephemeral.yaml
deploy/postgres/postgres-deployment.yaml
docs/dev/testing.md
internal/common/common_unitest_db.go
internal/common/testcontainers_db_context.go
internal/controller/controllers/images.go

```$ podman pull quay.io/centos7/postgresql-12-centos7:latest
Trying to pull quay.io/centos7/postgresql-12-centos7:latest...
WARN[0001] Failed, retrying in 1s ... (1/3). Error: initializing source docker://quay.io/centos7/postgresql-12-centos7:latest: reading manifest latest in quay.io/centos7/postgresql-12-centos7: unknown: Tag latest was deleted or has expired. To pull, revive via time machine
WARN[0003] Failed, retrying in 1s ... (2/3). Error: initializing source docker://quay.io/centos7/postgresql-12-centos7:latest: reading manifest latest in quay.io/centos7/postgresql-12-centos7: unknown: Tag latest was deleted or has expired. To pull, revive via time machine
WARN[0006] Failed, retrying in 1s ... (3/3). Error: initializing source docker://quay.io/centos7/postgresql-12-centos7:latest: …
```

NO-ISSUE: rename docker image for postgres 12 as latest tag disappeared

---

go.mod
go.sum
internal/controller/controllers/bmo_utils.go
vendor/github.com/openshift/cluster-baremetal-operator/provisioning/baremetal_pod.go
vendor/github.com/openshift/cluster-baremetal-operator/provisioning/image_cache.go
vendor/github.com/openshift/cluster-baremetal-operator/provisioning/image_customization.go
vendor/github.com/openshift/cluster-baremetal-operator/provisioning/ironic_proxy.go
vendor/github.com/openshift/cluster-baremetal-operator/provisioning/machine_os_images.go
vendor/github.com/openshift/cluster-baremetal-operator/provisioning/utils.go
vendor/modules.txt

Updates CBO to include https://github.com/openshift/cluster-baremetal-operator/pull/380 which is required for a single stack ipv6 cluster to be deployed from a dual-stack hub when the hub is a single node.
https://issues.redhat.com/browse/MGMT-17354

MGMT-17354: Update CBO to support dual stack SNO hub deploying an IPv6 spoke

---

Makefile
config/manager/manager.yaml
config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
deploy/podman/pod-persistent-disconnected.yml
deploy/podman/pod-persistent.yml
deploy/podman/pod.yml
deploy/podman/pod_tls.yml
deploy/postgres/postgres-deployment-ephemeral.yaml
deploy/postgres/postgres-deployment.yaml
docs/dev/testing.md
internal/common/common_unitest_db.go
internal/controller/controllers/images.go

backport of https://github.com/openshift/assisted-service/pull/6116

NO-ISSUE: replace postgres images as current one disappeared from quay

---

cmd/main.go
internal/releasesources/release_sources.go

Currently, when an assisted-service instance starts, it first checks if it is the leader. If it is, the instance deletes all the release images from the database and adds the configuration ones. If not, it bypasses this procedure. Due to the deployment strategy of the service in SaaS, a scenario arises where none of the instances become the leader when executing this flow. This results in an empty database if the service is run for the first time, leading the `/openshift-versions` endpoint to return an empty list. Consequently, the UI is unable to display the new cluster page. To address this issue, I propose modifying the current flow to operate similarly to how migrations are handled: wait to become the leader, then execute the code, and finally release the lock. …

MGMT-17361: Changing the addition of configuration release images to run when the instance becomes leader instead of skipping if it not

---

internal/network/connectivity_groups.go
internal/network/connectivity_groups_test.go

IPv6 L2 connectivity check uses nmap.  nmap uses NDP (Network Discovery Protocol) to check L2 connectivty to IPv6 hosts. There are cases that NDP response does not arrive or it is not captured by nmap which means that the system assumes there is no connectivity to the host.  However, there might be L3 connectivity (ping) to the same host. So change adds fallback for IPv6 L2 connectivity.  In case there is failure in L2 connectivity to IPv6 host and success in L3 connecivity to the same host, the host is assumed connected on L2, providing that the remote address is part of the L2 subnet being checked. …

OCPBUGS-31631: Deploy dual stack with IPv6 on top of bond/vlan fails

---

cmd/main.go
internal/releasesources/release_sources.go
internal/releasesources/release_sources_test.go
internal/versions/common.go

If release images are already present in the database, the service should continue to use this stale data instead of failing. In addition, currently failure to fetch new release images from the API does not trigger an error, allowing the service to proceed, truncate the table, and insert only static images. Hence, I propose treating failures to fetch release images as errors as well.
| Scenario              | Currently                                                                                   | Target                                                                                       |
|-----------------------|---------------------------------------------------------------------------------------------|------------------------------------------------------------------------------- …

MGMT-17412: Change fallbck behavior when error occuring in OpenShift Release Syncer

---

Dockerfile.assisted-service-build

The reference to the quay image has been replaced with
`RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/bin v1.53.2`
If we leave this unchanged, the skipper build container fails with an error about a missing image.

MGMT-17541: Replace broken golangci reference

---

internal/operators/lvm/config.go
internal/operators/lvm/lvm_operator.go
internal/operators/lvm/lvm_operator_test.go

As part of the effort to reduce LVM footprint. We have Adjusted new requirement for OCP 4.16.
Memory required:
- Before: 400MiB
- New: 100MiB

MGMT-17414: Changing requirements for LVM on 4.16

---

internal/versions/common.go
internal/versions/common_test.go
internal/versions/kube_api_versions.go
internal/versions/kube_api_versions_test.go
internal/versions/osimages.go
internal/versions/osimages_test.go
internal/versions/rest_api_versions.go
internal/versions/rest_api_versions_test.go

Currently assisted-service `normalizes` only release images in `kubeAPI` flow. we want it to `normalize` in `restAPI` flow as well. This is due to the nature of `ABI` flow currently, which starts the service with a release image with CPU architecture `aarch64`, but registers a cluster with `arm64` release image, and same with OS imags. In order to neatralize these differentials, this PR changes the way release and OS images are created and later fetched by normalizing it in creation and then during fetching.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-reques …

MGMT-17468: Use x86_64 over amd64 and arm64 over aarch64 for CPU architecture of both release and OS images to comply with ABI current behavior

---

docs/hive-integration/README.md
internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go
internal/controller/controllers/crd_utils.go

BMH is the custom resource that is used to add a new host. Agent on the other hand is created automatically when a host registers. Since there is a need to control agent labels the following agent label support was added:
In order to add an entry that controls agent label, a new BMH annotation needs to be added.
The annotation key is prefixed with the string
'bmac.agent-install.openshift.io.agent-label.'.  The remainder of the annotation is considered the label key.
The value of the annotation is a JSON dictionary with 2 possible keys. The key 'operation' can contain one of the values ["add","delete"] which mean that the label can either added , or deleted. The dictionary key 'value' contains the label value.
The value of the annotation is identical to the agent label value.
Note: agent …

MGMT-17365: Add support for setting agent labels in BMH as annotations

---

internal/hardware/mock_validator.go
internal/hardware/validator.go
internal/hardware/validator_test.go
internal/host/host_test.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/transition_test.go
internal/host/validations_test.go
internal/host/validator.go

Open installation of OCP on iSCSI boot volume to all platforms, as it was
allowed only on OCI.
Remove `ip=ibft` from the kernel arguments as it prevent proper network
configuration when several NICs are in use. RHCOS team recommend to
leave DHCP configuration.

MGMT-17558: Allow installation on iSCSI volume

---

internal/common/version.go
internal/common/version_test.go
internal/versions/api.go
internal/versions/api_test.go

Currently in `../openshift-versions?only_latest=true` request latest release images are compared with base version only, while this doesn't work for early beta releases. This PR fixed this issue by comparing all version.  

NO-ISSUE: Change only-latest api response to compare versions according to pre-release suffix as well instead of just base version

---

internal/versions/rest_api_versions.go
internal/versions/rest_api_versions_test.go
subsystem/cluster_v2_test.go
subsystem/feature_support_levels_test.go
subsystem/operators_test.go

Up until https://issues.redhat.com/browse/MGMT-10088, assisted-service was handling multi-arch release images in a way that basically means if you requested for (in GetReleaseImage) a release image with `openshiftVersion` and `cpuArchitecture` where cpuArchitecture is single-arch, you could get back a multi-arch release if it contains the requested architecture in its manifest. This behavior seems to evolve due to historical reasons where CPU architectures like `s390x` and `ppc64le` where only accessible using multi-arch images. In https://issues.redhat.com/browse/MGMT-10088 PRs, this behavior was changed to require `cpuArchitecture-multi` in case where openshiftVersion=<multi-arch-release>, as the reasoning before no longer true. Nevertheless, the UI still registers cluster with …

MGMT-17620: Change the way multi-arch release images are handled in RestAPI flow 

---

data/default_okd_os_images.json
data/default_okd_release_images.json
deploy/podman/okd-configmap.yml

The goal is to have an assisted installer job on master that installs
OKD.
x-ref: https://github.com/openshift/release/pull/50983

NO-ISSUE: Update OKD images to 4.16

---

.ci-operator.yaml
Dockerfile.assisted-service.ocp

Move the image to rhel9. To do so, the openshift-clients rpm is installed rather than the oc binary plucked from the cli image. 

CORS-2750: Move to rhel9, decouple from cli image

---

deploy/operator/capi/deploy_capi_cluster.sh

Missed modifying the hypershift destroy command
after changing the hypershift cli function to always run in the pod.

NO-ISSUE: Fix hypershift destroy in CI test script

---

internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/host/transition_test.go
internal/host/validator.go
internal/network/connectivity_groups.go
internal/network/connectivity_groups_test.go

Currently when L3 connectivity groups, there must be symmetrical connectivity between all nodes. This poses restriction that nodes cannot have networks that do not participate in cluster networking.
Instead, the L3 connectivity will change to connected addresses. A connected address is in address that can be reached from all other hosts. So if a host has a connected address, then it is regarded as host that belongs to majority group (the validation).
[MGMT-17698](https://issues.redhat.com//browse/MGMT-17698): Add to majority groups connected addresses
n order to use the L3 connected addresses the JSON encoded string in the ConnectivityMajorityGroups field in cluster must be changed. It will become a dictionary. One key will be the "majority_groups". It will contain the old dictionary as …

MGMT-17697: Change L3 connectivity to use connected addresses instead of majority groups

---

internal/provider/vsphere/ignition.go

The control-plane-machine-set (CPMS) cluster operator fails to deploy on 4.16-ec.5 build for ABI deployments on vSphere. That build removed the CPMS feature gate.
Because ABI and assisted deployments do not create or include machines in the manifests, and the control plane machine operator expects machines to be present for each control plane node, the CO fails to deploy.
The CPMS manifest should be removed for ABI and other UPI-like deployments.
For UPI there is documentation indicating the CPMS manifest must be removed: https://docs.openshift.com/container-platform/4.15/installing/installing_vsphere/upi/installing-vsphere.html#installation-user-infra-generate-k8s-manifest-ignition_installing-vsphere
- [] None
- Are the title and description (in both PR and commit) …

OCPBUGS-31733: Remove CPMS manifest for vSphere platform

---

internal/versions/osimages.go
internal/versions/osimages_test.go

Fail when OS images CPU architecture is missing instead of giving it default value in order not to generate false infraenv

MGMT-17523: Fail when OS images CPU architecture is missing instead of giving it default value

---

cmd/main.go
go.mod
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
vendor/modules.txt

When mirror registries are enabled, it is not possible to use a tag based image (for example quay.io/openshift-release-dev/ocp-release:4.15.0-multi) for the release image of a cluster being deployed by assisted.
The user should use digest a based image (such as quay.io/openshift-release-dev/ocp-release@sha256:b86422e972b9c838dfdb8b481a67ae08308437d6489ea6aaf150242b1d30fa1c)
This PR ensures that we check for this scenario during the validation of the ClusterDeployment.
This will be propagated to the ClusterDeployments_Controller as a validation failure if the image is tag based.
A spec Sync failure will be indicated in the conditions of the controller.
- …

MGMT-17194: Ensure releaseImage is not tag based when mirror registry enabled.

---

cmd/main.go
go.mod
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
vendor/modules.txt

If the user relies on mirror registries, and clusterimageset is set to a tagged image (e.g. quay.io/openshift-release-dev/ocp-release:4.15.0-multi)
as opposed to a by digest image (e.g. quay.io/openshift-release-dev/ocp-release@sha256:b86422e972b9c838dfdb8b481a67ae08308437d6489ea6aaf150242b1d30fa1c)
then oc will fail to pull with:
--icsp-file only applies to images referenced by digest and will be ignored for tags
This PR adds some additional information to the SpecSynced condition of the AgentClusterInstall 
if Mirror Registries is enabled, a tag is detected in the registry reference and there was a problem with `oc`
This should make it clearer to the user that there might be an issue the tagged image reference.
- Are the title and description (in both PR and commit) meaningful and …

MGMT-17194: Ensure that we improve error messages for mirror registry tagged images

---

api/vendor/github.com/openshift/assisted-service/models/create_manifest_params.go
api/vendor/github.com/openshift/assisted-service/models/update_manifest_params.go
client/vendor/github.com/openshift/assisted-service/models/create_manifest_params.go
client/vendor/github.com/openshift/assisted-service/models/update_manifest_params.go
docs/user-guide/install-customization.md
internal/manifests/manifests.go
internal/manifests/manifests_test.go
models/create_manifest_params.go
models/update_manifest_params.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/create_manifest_params.go
vendor/github.com/openshift/assisted-service/models/update_manifest_params.go

This PR addresses a few bugs in docs, regexes and code that cause inconsistency in the handling of patch manifests.
Patch manifests should end with the extension `.patch` or should end with a suffixed patch extension such as `.patch_extension`

MGMT-17775: Ensure that patch manifest filenames are consistent and correct.

---

api/vendor/github.com/openshift/assisted-service/models/domain_resolution_response.go
client/vendor/github.com/openshift/assisted-service/models/domain_resolution_response.go
internal/common/test_configuration.go
internal/host/validations_test.go
internal/host/validator.go
models/domain_resolution_response.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/domain_resolution_response.go

In order to support F5 DNS load balancer, CNAMES resolutions will be added.  If a CNAME record exists for a domain-name, it means that the domain is resolved.
This change includes:
- Swagger changes to include the cnames in the domain resolution response
- Validation changes to refer cnames in the domain resolution response
/cc @zaneb 
/cc @gamli75

MGMT-17866: Assisted service change for F5 DNS load balancer

---

internal/controller/controllers/local_cluster_import_controller.go
internal/controller/controllers/local_cluster_import_controller_test.go

The code in master to create the local cluster namespace is not working due to a copy/paste error (it's really creating a clusterImageSet)
While looking into this, I considered that the local-cluster namespace does not need to be managed or updated by us as it is owned by ACM.
So I am removing the code to create/update a namespace in production code.
In tests, we will create a local-cluster namespace for the purpose of testing. …

MGMT-17811: Do not create local cluster namespace

---

pkg/staticnetworkconfig/generator.go
pkg/staticnetworkconfig/generator_test.go
subsystem/image_test.go
subsystem/infra_env_test.go

In case there is static networking configuration without mac-interface mapping, it is created but the configuration is not applied.
This change validates that for every ethernet interface there is a corresponding mac-interface mapping when the static network configuration is set during infa-env registration or during infra-env update.
/cc @gamli75

MGMT-17618: NMStateConfig interfaces presence should be validated

---

internal/cluster/validations/pull_secret_validation.go
internal/cluster/validations/validation_test.go

Fix the validation rule while parsing pull secret. Fix some typos in test file.
An unit test had been updated to test a problematic input
Will be tested next week
Should be backported in openshift 4.15 & 4.16
I guess
Started locally assisted-service with podman. Issue was reproduced & fixed with the changes.
However I didn't check if the installation could go until the end with a password containing a ':'
Seems to be a legit char tho. …

OCPBUGS-31727: Invalid Pull-Secret when using password which contains a colon character

---

internal/common/common.go
internal/ignition/installmanifests.go
internal/ignition/installmanifests_test.go
internal/network/none_platform_node_ips_allocation.go
internal/network/none_platform_node_ips_allocation_test.go
internal/provider/none/installConfig.go

When none platform is in use, if there is ambiguity in node-ip assignment, then incorrect assignment might lead to installation failure. This happens when etcd detects that the socket address from an etcd node does not match the expected address in the peer certificate. In this case etcd rejects such connection.
Example: assuming two networks - net1 and net2.
master node 1 has 1 address that belongs to net1.
master node 2 has 2 addresses. one that belongs to net 1, and another that belongs to net 2 master node 3 has 1 address that belongs to net 1. If the selected node-ip of master node 2 belongs to net 2, then when it will create a connection with any other master node, the socket address will be the address that belongs to net 1. Since etcd expects it to be the same as the node-ip, it …

MGMT-17700: Assign none platform node-ips based on connected addresses and etcd restrictions

---

pkg/ocm/client.go

Currently or `ocm/client` package supports authentication to OCM using an offline token via the `OCM_SELF_TOKEN` environment variable. But the OCM team has deprecated this authentication mechanism and will remove it in the future. The alternative is to use a client identifier and client secret, which is what we use in the SaaS environment. This patch disables by default that support, and will make the server fail with an explicit error message if it is used. Users that really need to use it will need to explicitly enable it setting the `ACKNOWLEDGE_DEPRECATED_OCM_SELF_TOKEN` environment variable to `yes`. In that case the server will start, but a warning will be written to the log.
- Is there a bug required (and …

NO-ISSUE: Deprecate and disable support for OCM offline token

---

internal/common/disk_formatting.go
internal/host/hostcommands/install_cmd_test.go

Exclude multipath drive type from being formatted.

MGMT-17848: Assisted service should not format multipath devices

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
pkg/mirrorregistries/generator.go
pkg/mirrorregistries/generator_test.go

Up until https://github.com/openshift/assisted-service/pull/6158/ was merged, installations flows in kubeAPI mode were not validating the `clusterImageSet` release images as they were added to the cache later in the flow. Therefore, since this PR was merged, a new issue appeared - registries specified by the user as local mirrors are not added to the ignore list, thus causing the flow to fail. The changes in this PR are adding the local registries to the ignore list.
Waiting for QE test
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#commit-message-g …

MGMT-17901: Ignore mirror registries during pull secret validation 

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go

When a cluster is single stack and DHCP VIP allocation is off, the machine-network is calculated by selecting a host network that the VIPs belong to. So machine network update is forbidden in this case. This is undesirable for KubeAPI where the machine-network is specified in a custom resource.
So this change allows machine-network update if the update arrived from KubeAPI (non interactive).
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING. …

MGMT-17763: Setting Machine network CIDR is forbidden" error is only present on cluster updates

---

config/manager/manager.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
docs/operator.md
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/images.go

A user should request the EL8 image when they are running in a FIPS-enabled cluster and intend to only install OCP versions <4.16.
This can be done by setting the
`agent-install.openshift.io/service-image-base` annotation to `el8` on the AgentServiceConfig resource
Resolves https://issues.redhat.com/browse/MGMT-17898
Deployed the new operator and configured the new image env var.
Set and unset the annotation and observed that the operator changed the image correctly.
- I don't think this is worth documenting upstream

MGMT-17898: Use the EL8 assisted-service image when requested by annotation

---

api/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
client/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/hostcommands/instruction_manager.go
models/install_cmd_request.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/install_cmd_request.go

Pass a flag in the installation command instructing the controller if notify reboots functionality is enabled.
The flag is enabled only if kube-api is not enabled in the service
/cc @tsorya 
/cc @carbonin

MGMT-17353: Debug pod left in ImagePullBackOff after install in disconnected environment

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go

This PR is a fix for - https://github.com/openshift/assisted-service/pull/6371, ehre I added the local registries instead of the public one. This PR fixed this issue. 

MGMT-17901: Add the external registry to the list of ignored registries for pull secret validation instead of the mirror one

---

internal/oc/release.go
internal/oc/release_test.go

Previously this code would use the dynamic binary for 4.16 nighlies this change ensures all 4.16 releases will get the static binary when FIPS is not enabled.
Resolves https://issues.redhat.com/browse/MGMT-18010
Unit tests were sufficient
- Should this PR be backported? - **Yes, this should go to 2.10**

MGMT-18010: Use the static installer for 4.16 nightlies when not FIPS-enabled

---

internal/oc/release.go
internal/oc/release_test.go

Previously this code would use the dynamic binary for 4.16 nighlies this change ensures all 4.16 releases will get the static binary when FIPS is not enabled.
Resolves https://issues.redhat.com/browse/MGMT-18015
Unit tests

[release-ocm-2.10] MGMT-18015: Use the static installer for 4.16 nightlies

---

Dockerfile.assisted-service
Dockerfile.assisted-service-build
ci-images/Dockerfile.base

[CentOS Linux 8 had reached the End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. It means that CentOS 8 will no longer receive development resources from the official CentOS project. After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to [vault.centos.org](https://vault.centos.org/) where they will be archived permanently. Alternatively, you may want to [upgrade to CentOS Stream](https://techglimpse.com/convert-centos8-linux-centosstream/).
from - https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
backports - https://github.com/openshift/assisted-service/pull/6397
- Should …

NO-ISSUE: [backport-release-ocm-2.9] Use archived dnf repositories for centos8 as the current ones are no longer valid

---

Dockerfile.assisted-service
Dockerfile.assisted-service-build
ci-images/Dockerfile.base

[CentOS Linux 8 had reached the End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. It means that CentOS 8 will no longer receive development resources from the official CentOS project. After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to [vault.centos.org](https://vault.centos.org/) where they will be archived permanently. Alternatively, you may want to [upgrade to CentOS Stream](https://techglimpse.com/convert-centos8-linux-centosstream/).
from - https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
backports - https://github.com/openshift/assisted-service/pull/6397
- Should …

NO-ISSUE: [backport-release-ocm-2.8] Use archived dnf repositories for centos8 as the current ones are no longer valid

---

Dockerfile.assisted-service
Dockerfile.assisted-service-build

[CentOS Linux 8 had reached the End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. It means that CentOS 8 will no longer receive development resources from the official CentOS project. After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to [vault.centos.org](https://vault.centos.org/) where they will be archived permanently. Alternatively, you may want to [upgrade to CentOS Stream](https://techglimpse.com/convert-centos8-linux-centosstream/).
from - https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
backports - https://github.com/openshift/assisted-service/pull/6397
- Should …

NO-ISSUE: [backport-release-ocm-2.7] Use archived dnf repositories for centos8 as the current ones are no longer valid

---

Dockerfile.assisted-service
hack/container_build_scripts/install_build_deps.sh
hack/container_build_scripts/replace_dnf_repositories_ref_if_needed.sh
hack/container_build_scripts/utils.sh

[CentOS Linux 8 had reached the End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. It means that CentOS 8 will no longer receive development resources from the official CentOS project. After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to [vault.centos.org](https://vault.centos.org/) where they will be archived permanently. Alternatively, you may want to [upgrade to CentOS Stream](https://techglimpse.com/convert-centos8-linux-centosstream/).
from - https://techglimpse.com/failed-metadata-repo-appstream-centos-8/ …

NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid

---

internal/featuresupport/feature_support_test.go
internal/featuresupport/features_platforms.go

Remove OCI from technology preview as it is now a supported integration.

[cloud_hotfix_releases] MGMT-18059: Mark OCI as supported integration

---

internal/controller/controllers/local_cluster_import_controller.go
internal/controller/controllers/local_cluster_import_controller_test.go

The local cluster feature does not create an infraEnv during the import process. This PR addresses that by creating the infraenv as part of the import.

MGMT-18046: Create an infraenv for the local cluster during import

---

internal/cluster/finalizing_stages.go
internal/cluster/finalizing_stages_test.go
internal/cluster/transition.go
internal/cluster/transition_test.go

Some default timeouts are very long.  For example 'waiting for cluster operators' is 10 hours.
This change adds ability to have different timeout values for soft-timeouts, and changes the value of 'waiting for cluster operators' to general-wait-timeout (70 minutes).
/cc @gamli75

MGMT-17984: [soft timeout] operators timeout after 10 hours without events

---

internal/network/manifests_generator.go

NO-ISSUE: Adding verification if file exist before sourcing it in forcedns script we use for sno
Currently if file doesn't exist we will see error in journal, even though this doesn't fail the script it is confusing, this fix removes this error

NO-ISSUE: Adding verification if file exist before sourcing it in forcedns script

---

internal/manifests/manifests.go
internal/manifests/manifests_test.go

The validation of manifest filenames as it stands has a bug
any file without a name before the extension starts is considered to be valid.
`.yaml.patch` is considered valid when it should not be for example
This fix remedies that by ensuring that, in addition to the other checks we already peform, that file filename does not begin with a `.`

MGMT-17794: Make sure that uploaded manifest files have valid filename before extensions

---

internal/ignition/installmanifests.go
internal/ignition/installmanifests_test.go

Presently, manifest patches will only be processed if they are located within the `openshift` directory This change ensures that we check the `manifests` directory for patch files also.
As we already enforce that files are distinct between these directories it is safe to do this and it seems like a more `user friendly` choice to allow the application of patches when they are uploaded to either directory. …

MGMT-17802: Ensure that manifest patches may be placed in either `manifests` or `openshift`

---

subsystem/kubeapi_test.go
subsystem/leader_test.go

Currently subsystem test doesn't clean all resources in the end of tests resulting in errors when running more than once. We want to clean this resources so the tests could be repetitive in local testing

MGMT-18086: Clean subsystem tests resources correctly

---

api/vendor/github.com/openshift/assisted-service/models/disk.go
client/vendor/github.com/openshift/assisted-service/models/disk.go
models/disk.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/disk.go

- Adding new field for disks
- `HasPartition` field will be used for new validation if disk not empty 

MGMT-17300: adding has partition field for disks

---

api/v1beta1/agentserviceconfig_types.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/hypershiftagentserviceconfig_controller.go
vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go

Currently the function for monitoring the status of components deployed by the agentserviceconfig controller doesn't differentiate between a failure to monitor and a component that is failing.
This means that the reconciliation function actually returns an error when reconcile succeeded, but some component isn't healthy. This isn't correct and causes issues when testing basic success cases.

NO-ISSUE: Differentiate between monitoring failures and component issues

---

cmd/operator/main.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/hypershiftagentserviceconfig_controller.go
internal/controller/controllers/kube_compat.go
internal/controller/controllers/kube_compat_test.go

Only watch the OCP-specific kinds from our operator when it is running in an OpenShift cluster.
This doesn't address the rest of the runtime issues, but allows the operator to start in non-OCP kubernetes clusters.
Resolves https://issues.redhat.com/browse/MGMT-18130
Deployed the operator manually to a kind cluster without error.

MGMT-18130: Allow infra-operator to start in non OCP kubernetes clusters

---

pkg/staticnetworkconfig/generator.go
pkg/staticnetworkconfig/generator_test.go

Recently a validation was added when adding static network configuration.  During this configuration there was a requirement that there will be at least one physical interface that corresponds to an entry in the mac-interface mapping.
It seems that this requirement is not always correct since with vlan an underlying interface does not have to exist.
So this change also checks for vlan and if it is vlan it will check existance of underlying interface. …

MGMT-18092: infraenv cannot be created while deploying vlan spokes with previous configuration

---

internal/uploader/auth_utils.go
internal/uploader/auth_utils_test.go
internal/uploader/events_uploader.go
internal/uploader/events_uploader_test.go
internal/uploader/extract_test.go

* Flatten pyramidal code
* Explicit data modification
* Use different creds for data enrichment & push authent
Currently, the logic to get pull secret is hard to read (and more complex than it seems). While flattening the nested logic, it highlights some shortcuts in the err check. I tried to explicit the different scenario, so there is a change of behavior. Previously the Hub cluster credentials were used by default and if not, the spoke cluster creds were used (if any). I think spoke cluster creds should be used to enrich the data (since it seems to be more accurate to reflect the cluster owner identity. Any insights/opinions about this part are welcome)
Since the code is able to use the spoke cluster credentials to push data, should we disable by default this feature if there is no …

NO-ISSUE: Refactor uploader pkg

---

pkg/validations/validations.go
pkg/validations/validations_test.go

AI doesn't support non-encoded user name and password in the proxy url. Currently if a non-encoded value is passed, the proxy won't work and it will be hard for the user to understand why.
This commit changes the behaviour to return an error message in case a non-encoded value is passed.
- [] None

MGMT-18127: User name and password in a proxy url should be url encoded

---

internal/cluster/validations/pull_secret_validation.go
internal/uploader/auth_utils.go
internal/uploader/auth_utils_test.go

Allow auth field to be empty in docker pull secret
The impacts are limited to 
* uploader/ package (for on-prem usecase)
* Saas. The code being called by https://github.com/openshift/assisted-service/blob/v2.32.0/internal/cluster/auth.go#L45
* it only looks for "cloud.openshift.com"
* this func is only called if the authType is `auth.TypeRHSSO`
I will appreciate to have the opinion of Assisted-Installer gurus to be sure I'm not missing something and it's safe to allow such entry without additional checks. For example, should I add some check here https://github.com/openshift/assisted-service/blob/v2.32.0/internal/cluster/auth.go#L32 or somewhere else to ensure that for SaaS the user:password is specified ?
Also 
* removed Password that wasn't used …

OCPBUGS-35932: Allow auth in docker credentials to be empty

---

internal/cluster/transition.go
internal/cluster/transition_test.go

FinalizingStage is not reset while resetting a cluster, leading to skipping an update for the progress field (https://github.com/openshift/assisted-service/blob/v2.31.7/internal/cluster/cluster.go#L1811) 
Then the timeout (set from the 1st install try) is more likely to be reached, flagging the installation as failed while it's not
Strictly speaking this value can be updated by this route https://github.com/openshift/assisted-service/blob/v2.31.7/swagger.yaml#L333-L338. While the body is required, the internal param is not https://github.com/openshift/assisted-service/blob/v2.31.7/swagger.yaml#L5713-L5717. That means that this API could be called with something empty (and then break the idea of setting it to empty to be able to reset the start time)
But good news, this check here will do …

MGMT-18269: Reset finalizing stage in DB while resetting cluster

---

deploy/assisted-image-service.yaml

Creating an emptyDir workaround the permission issues with the `/data` directory we are encountering in the susbsystem tests.
```
{"file":"/go/src/github.com/openshift/origin/main.go:132","func":"main.main.func1","level":"fatal","msg":"Failed to populate image store: failed to download https://mirror.openshift.com/pub/openshift-v4/ppc64le/dependencies/rhcos/4.14/4.14.15/rhcos-4.14.15-ppc64le-live.ppc64le.iso: unable to create a temp file for /data/rhcos-full-iso-4.14-414.92.202402130420-0-ppc64le.iso: open /data/.rhcos-full-iso-4.14-414.92.202402130420-0-ppc64le.iso2762773689: permission denied\n","time":"2024-07-08T11:07:48Z"}
```

NO-ISSUE: Mount emptyDir for data in image service

---

internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go

Currently the procedure to detach a cluster that was created using hosts from a late binding pool is to first delete the `ManagedCluster` object, then add the `preserveOnDelete: true` field to the `ClusterDeployment` and then delete that `ClusterDeployment`. But the cluster deployment controller doesn't look at the `preserveOnDelete` field at all. As a result the hosts of the cluster are returned to the pool and they are provisioned again, which effectively destroys the cluster.
This patch changes the deployment manager controller so that in that case it will check the `preserveOnDelete` field and if it is `true` it will delete the corresponding `Agent` objects. The result of that is that the hosts will go back to the pool, but marked the will still be marked as provisioned and they will …

MGMT-17893: Don't destroy cluster on detach

---

docs/dev/operator-on-kind.md
hack/crds/metal3.io_preprovisioningimages.yaml

Fix apply command to apply dir rather than files and add preprovisioning image CRD
Manually followed the doc to deploy the operator to kind

NO-ISSUE: Fix kind deploy

---

internal/controller/controllers/bmo_utils.go
internal/controller/controllers/bmo_utils_test.go
internal/controller/controllers/mock_bmo_utils.go
internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go
internal/oc/mock_release.go
internal/oc/release.go

When available, read the ICC secret set by BMO in order to retrieve the
agent image, the agent URL(s), and the inspector URL(s).
This this change, we wil try to:
1/ Get the agent image from the user override
2/ if 1/ is not found, get the image from the ICC configuration
3/ if 2/ is not found, get the image from the HUB cluster
4/ if 3/ is not found, return the default image

MGMT-17478: Use ICC config secret for converged flow info when available

---

skipper.yaml

Currently skipper (+ podman at least) fails with the following error:
```
Error: /home/agentil/.docker: duplicate mount destination
```
because skipper already mounts it by default.

NO-ISSUE: Fix skipper configuration

---

api/vendor/github.com/openshift/assisted-service/models/manifest.go
client/vendor/github.com/openshift/assisted-service/models/manifest.go
cmd/main.go
go.mod
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/constants/manifests.go
internal/ignition/installmanifests.go
internal/ignition/installmanifests_test.go
internal/manifests/api/interface.go
internal/manifests/api/mock_manifests_api.go
internal/manifests/api/mock_manifests_internal.go
internal/manifests/manifests.go
internal/manifests/manifests_test.go
models/manifest.go
pkg/generator/generator.go
pkg/s3wrapper/client.go
pkg/s3wrapper/filesystem.go
pkg/s3wrapper/filesystem_test.go
pkg/s3wrapper/mock_s3wrapper.go
restapi/embedded_spec.go
subsystem/cluster_test.go
subsystem/manifests_test.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/manifest.go

As detailed in the epic [MGMT-18165](https://issues.redhat.com//browse/MGMT-18165) and the corresponding enhancement doc, there is a need to make transaction storage work in a more transactional way.
This PR addresses that by storing manifest metadata with the file being stored
In S3 this will be performed in a single write and will store user defined attributes alongside the file itself.
In the filesystem implementation, this will be performed using xattr, whereas we cannot make this completely atomic, we can effectively do so by applying all changes to a temporary file and then moving it to the correct location.
This PR includes `read only` support for the legacy method (at the time of writing,
the current method) of marking a file as `user-supplied`;
When generating a list of …

MGMT-18165: Make manifest metadata storage more transactional in nature

---

tools/deploy_wiremock.py

Lately, we have been starting to see these failures in subsystem-tests in the CI -
```
[INFO] 2024-07-12 18:06:51,928 - deploy_wiremock - Wiremock is accessible
deployment.apps/wiremock created
service/wiremock created
File "/assisted-service/./tools/deploy_wiremock.py", line 126, in <module>
main()
File "/assisted-service/./tools/deploy_wiremock.py", line 20, in main
deploy_wiremock(deploy_options)
File "/assisted-service/./tools/deploy_wiremock.py", line 65, in deploy_wiremock
populate_stubs(hostname=hostname, port=port)
File "/assisted-service/./tools/deploy_wiremock.py", line 97, in populate_stubs
utils.check_output(cmd)
File "/assisted-service/tools/utils.py", line 88, in check_output
raise RuntimeError(f'command={command} exited with an error={err …
```

NO-ISSUE: Fix subsystem tests in the CI - Wiremock stubs script is failing to reach Wiremock pod occasionally 

---

api/v1beta1/agentserviceconfig_types.go
config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
config/crd/bases/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
config/crd/resources.yaml
config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
deploy/olm-catalog/manifests/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go

Issue: https://github.com/openshift/assisted-service/issues/6552
- [] None

MGMT-18105: Update registry.svc.ci.openshift.org to registry.ci.openshift.org (bugzilla #6552)

---

.snyk

We don't want snyk to open PR against files in the vendor directory.
https://docs.snyk.io/scan-using-snyk/import-project-repository/exclude-directories-and-files-from-project-import#use-the-.snyk-file-to-exclude-directories-and-files-from-import

NO-ISSUE: Exclude vendor directory from snyk code analysis

---

Makefile
tools/deploy_wiremock.py

tailored backport of - https://github.com/openshift/assisted-service/pull/6569

[release-ocm-2.11] NO-ISSUE: Fix subsystem tests in the CI - WireMock stubs script is failing to reach WireMock from time to time

---

internal/cluster/validations/validations.go
internal/uploader/auth_utils.go

Manual cherry-pick of https://github.com/openshift/assisted-service/pull/6523

[release-ocm-2.10] OCPBUGS-36504: Allow auth in docker credentials to be empty

---

pkg/staticnetworkconfig/generator_test.go

This PR updates the package naming in `generator_test.go` to use the "_test" suffix. This change follows the convention for organizing test files, making our project structure clearer. By using the black-box testing methodology, we focus on testing the package's functionality from an external perspective. Tests interact only with the package's exported interfaces and behavior. This simplifies our test suite, making it easier to add new tests and make changes in the future. …

MGMT-18380: Update package naming in generator_test.go for black-box testing methodology

---

.tekton/assisted-service-saas-main-pull-request.yaml
.tekton/assisted-service-saas-main-push.yaml
Dockerfile.assisted-service

* Add labels
* Add default user
* Add licenses under /licenses/
Requirements come from https://docs.redhat.com/en/documentation/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#additional_resources and would prevent us from releasing an image (we have an exception for "based_on_ubi image")

KONFLUX-1611: Add labels, licenses & user to Dockerfile

---

internal/host/statemachine.go

When installing a day2 node, in some scenraios, the process can be stucked on 'installing-pending-user-action' state while the node is in Done stage.
E.g. after fixing an invalid certificate that failed verfication when trying to reach the using kubeconfig.
Thus, added 'InstallingPendingUserAction' as a SourceState for the relevant TransitionRule (which should move state to the final 'AddedToExistingCluster' DestinationState). …

MGMT-18155: handle state of day2 node in Done stage

---

hack/generate.sh

The naming of the python package changed since setuptool upgrade in
https://github.com/openshift/assisted-service/pull/6576.

NO-ISSUE: Fix python client generation

---

internal/ignition/discovery.go
internal/ignition/discovery_test.go
internal/ignition/templates/add-ntp-sources.service
internal/ignition/templates/add-ntp-sources.sh
internal/ignition/templates/discovery.ign

Currently when the user provides additional NTP sources for the installation they are used by the installed cluster, but not by the discovery environment. That means that the system clock of the discovery environment may be wrong if the default NTP servers can't be reached, and as result it may fail to pull images because the system clock may be before the validity date of the certificates of the registry server. To avoid that this patch changes the ignition of the discovery environment so that it will also use the NTP sources provided by the user.
Related: https://issues.redhat.com/browse/MGMT-18411
Tested creating a libvirt virtual machine that has the clock fixed in the past:
```bash
946681200
```
```xml
<clock offset='absolute' start='946681200'>
...
</clock>
```
The blocked access to …

MGMT-18411: Add NTP sources to discovery environment

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/kube_compat.go

This reverts commit 77219eebd4c4fd4ad4e7486ecd97dc9cdee3b974.
When using BMO to deploy hosts the ironic server didn't trust the certs
used for the ingress. This failed the deployment.
Revert the cert addition while we investigate a different way to handle
this.
Related to https://issues.redhat.com/browse/MGMT-18418

MGMT-18418: Revert "Add certs to ingress when deploying in non-OCP clusters (#6564)"

---

Dockerfile.assisted-service

Currently, the assisted service fails to start using podman with a
permission error:
```
Unable to create directory for file data /data/0e4d8f88-9eb9-441c-84e5-7f4569be78e0/manifests/openshift/50-masters-chrony-configuration.yaml: mkdir /data/0e4d8f
88-9eb9-441c-84e5-7f4569be78e0: permission denied" pkg=Inventory
```
This change ensures that /data is writable by the UID specified in the
Dockerfile, and when deployed on OCP, we allow the group "root" to write
because the UID will be randomly selected.
https://docs.openshift.com/container-platform/4.16/openshift_images/create-images.html#use-uid_create-images
Similar to:
https://github.com/openshift/assisted-image-service/pull/258
https://github.com/openshift/assisted-image-service/pull/243

NO-ISSUE: Adjust permissions on /data directory

---

deploy/operator/mirror_utils.sh

Based on mirror.openshift.com being migrated to deliver bits from a different cloud provider
So add the -L option to the curl command to follow redirects.

NO-ISSUE: Add -L option to curl command to follow redirects

---

api/v1beta1/agentserviceconfig_types.go
internal/controller/controllers/local_cluster_import_controller.go
internal/controller/controllers/local_cluster_import_controller_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go

We need to make sure that the local cluster import may be disabled.
The import should be switched off by default and only overridden with an annotation.
This PR implements this functionality.
If the local cluster import functionality is disabled then all local cluster entities controlled
by assisted will be left intact, we will simply skip the reconcile loop.
Customers who need to enable the feature may do so by placing an annotation on the AgentServiceConfig. …

MGMT-18448: Allow local cluster import to be disabled.

---

pkg/validations/validations.go
pkg/validations/validations_test.go

Reverts openshift/assisted-service#6467
The PR introduced a regression, it blocked any proxy URL with special characters, even if it was url encoded.

MGMT-18456: Revert "MGMT-18127: User name and password in a proxy url should be url encoded"

---

Makefile
docs/dev/debug.md
docs/dev/running-test.md
hack/kind/kind-config.yaml
tools/deploy_inventory_service.py

- Enable debugging assisted-service
- set kind as the default deploy target
This PR continues https://github.com/openshift/assisted-service/pull/6385

MGMT-18451: Enable debugging assisted-service on kind

---

go.mod
go.sum
internal/controller/controllers/bmo_utils.go
internal/controller/controllers/bmo_utils_test.go
vendor/github.com/openshift/image-customization-controller/pkg/ignition/builder.go
vendor/modules.txt

This allows ironic inspector URL to be missing in ICC config secret.
In 4.17 this is expected to be missing as the inspector service as been
removed.
If this URL is provided the agent will attempt to contact the inspector
service when it shouldn't causing the install to fail.
In earlier versions the secret will not be present so the controller
will continue to provide the inspector service URL as before.
Resolves https://issues.redhat.com/browse/MGMT-18505
Deployed a 4.17 hub cluster and installed a 4.17 SNO from assisted installed on it with this branch image.

MGMT-18505: Fix installation from a 4.17 hub with converged flow

---

go.mod
go.sum
internal/controller/controllers/bmo_utils.go
internal/controller/controllers/bmo_utils_test.go
internal/controller/controllers/mock_bmo_utils.go
internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go
internal/oc/mock_release.go
internal/oc/release.go
vendor/github.com/openshift/image-customization-controller/pkg/ignition/builder.go
vendor/modules.txt

This PR backports https://github.com/openshift/assisted-service/pull/6533 and https://github.com/openshift/assisted-service/pull/6639
Together these PRs allow successful discovery of hosts using a 4.17 hub cluster and converged flow which will be required in 2.11 when 4.17 is released.
Resolves https://issues.redhat.com/browse/MGMT-18508

[release-ocm-2.11] MGMT-18508: Allow converged from 4.17 hub

---

Makefile

When we started using kind we stopped printing the test environment variables before running the test, this PR adds those back.
/cc @eliorerz

NO-ISSUE: Print subsystem environment variables before test

---

Makefile

Fix subsystem kubeapi tests when `ENABLE_KUBE_API` is not exported.
As described in https://github.com/openshift/assisted-service/blob/master/docs/dev/running-test.md#running-the-tests - exporting `ENABLE_KUBE_API` should be transparent to whom running the tests
/cc @danmanor

NO-ISSUE: Add missing kube api flag on kube api subsystem test

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

AutomatedCleaningMode should not be used when the
converged flow is disabled since it requires IPA
which is only enabled when the converged flow is enabled.
Caused by regression in PR
https://github.com/openshift/assisted-service/pull/5319 which relies on users to set the automatedCleaningMode spec, but did not take into account the converged flow being disabled.
/cc @carbonin @eranco74

MGMT-18560: Fix AutomatedCleaningMode behavior

---

docs/operator.md
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/common.go

Previously when a user provided mirror registry certs the assisted-service pod would be deployed in such a way that those would be the _only_ certs trusted by most commands running on the pod.
This would cause issues when, for example, the spoke cluster release image is mirrored internally, but the hub cluster image is not.
This was the case in https://issues.redhat.com/browse/OCPBUGS-27238 where assisted-service failed to pull the hub cluster release image because it didn't trust a certificate it otherwise should have.
To address this the infrastructure-operator creates a configmap which is annotated such that the cluster network operator will inject the public CA bundle into it as described in [1]. This content is then merged with the user-provided content (if any is provided) into a …

OCPBUGS-27238: Use both the OCP cluster trusted certs and user certs

---

internal/provider/base.go
internal/provider/external/base.go
internal/provider/external/external.go
internal/provider/external/oci.go
internal/provider/none/installConfig.go

Since external platform relies on user managed networking, we need the
feature introduced in
https://github.com/openshift/assisted-service/pull/6257 to determine the
machine networks.
This change is useful when using iSCSI boot drive on Oracle Cloud
Infrastructure, in order to select the machine network that doesn't
belong to the iSCSI subnet.

MGMT-18514: Calculate machine networks in external platform

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

Manual cherry-pick/backport of https://github.com/openshift/assisted-service/pull/6662
------
AutomatedCleaningMode should not be used when the
converged flow is disabled since it requires IPA
which is only enabled when the converged flow is enabled.
Caused by regression in PR
https://github.com/openshift/assisted-service/pull/5319 which relies on users to set the automatedCleaningMode spec, but did not take into account the converged flow being disabled. …

[release-ocm-2.9] MGMT-18585: Fix AutomatedCleaningMode behavior

---

internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/network/manifests_generator.go
internal/network/manifests_generator_test.go
internal/network/mock_manifests_generator.go

When iSCSI boot is enabled, DNS configuration will be missing on first
boot, even though the information was advertised by DHCP:
https://issues.redhat.com/browse/OCPBUGS-26580.
The workaround consists at re-applying the network configuration on all
the network interfaces when we detect if `/sysroot` is mounted from an
iSCSI block volume.
PRs part of this story:
- Validate iSCSI volume eligibility on hosts: https://github.com/openshift/assisted-service/pull/6434
- Report iSCSI host ip address: https://github.com/openshift/assisted-installer-agent/pull/727
- Configure DHCP on iSCSI network interface: https://github.com/openshift/assisted-service/pull/6602
- Workaround DNS issue on first boot: https://github.com/openshift/assisted-service/pull/6603
- Filter out machine networks: TODO

MGMT-17560: Workaround missing DNS on iSCSI

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/ignition/templates/discovery.ign
internal/ignition/templates/iscsi-oci-configure-secondary-nic.service
internal/ignition/templates/iscsi-oci-configure-secondary-nic.sh

A secondary network interface is required in OCI in order to install clusters on iSCSI boot volumes. Extra interfaces in OCI must be statically set, this change adds a script that configures the secondary network interface on OCI during discovery. We ensure that we execute the script only for machines in OCI with an iBFT configuration.
Since the secondary interface is the one that will be part of the machine networks, we will prevent its configuration with DHCP though the kernel arguments.
Unfortunately, we cannot propagate the network configuration set during discovery to the installed system because `--copy-network` won't work with iSCSI boot volumes: https://github.com/coreos/coreos-installer/issues/1389. As an alternative, the user will need to pass extra custom manifests to configure …

MGMT-18121: Configure networking when using ISCSI over OCI

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

Only BMAC should be aware of the BMH and its status. When deprovisioning a node by deleting a BMH, make BMAC wait for the node to fully deprovision before annotating and deleting the agent and removing the finalizer.
This adds a new annotation for the agent resource (`agent.agent-install/clean-spoke-on-delete`) which is used in place of the bmac annotation to communicate to the agent controller that the node should be removed.
This gets us a bit closer to https://issues.redhat.com/browse/MGMT-10006 by removing the BMH concept from the "remove a node" flow in the agent controller. This will allow this logic to be more easily reused in the late-binding/non-bmh case.
https://issues.redhat.com/browse/MGMT-10006
Tested manually using a dev-scripts cluster.
1. Deployed a 6 node OCP cluster from …

MGMT-10006: Wait for host to deprovision in BMAC

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/kube_compat.go

This reverts commit 9964f0870d5df042a782bb9c6394835d05ad807a.
The re-adds the ingress certs now that the CAPI provider is using the internal service IP for the BMH.
Resolves https://issues.redhat.com/browse/MGMT-18418
Requires https://github.com/openshift-assisted/cluster-api-agent/pull/51 (merged)
Tested manually in a Sylva test environment with the updated CAPI provider.
Saw that a SNO was installed successfully.

MGMT-18418: Reapply "Add certs to ingress when deploying in non-OCP clusters (#6564)"

---

internal/host/validator.go

We want to allow hosts to have slightly less memory than in the official documentation because some setups (like VMs) might give slightly less than the required amount. This PR changes the host validator to tolerate a slightly lower memory amount.
Apart from automatic tests this was also tested in the following way:
1. deploy a k8s cluster with assisted installer with an image for assisted-service from this branch
2.  create a vm with 16284 mb (100 mb less than 16 gb)
3. try to install an sno and add the vm as a host
4. check that the ui shows that minimum memory requirement is 16 gb even though the host is valid
5. finish the installation to make sure everything is fine
6. try the same with a vm that has 16283 mb
7. check that the host is insufficient with the error message saying it …

MGMT-16212: Allow Assisted-Installer to tolerate a slightly lower memory than required

---

docs/dev/olm-operator-plugins.md

Updating the developer docs for the OLM operator plugin infrastructure to include MCE and the relevant repo link.

NO-ISSUE: add MCE to OLM operators dev docs

---

internal/featuresupport/feature_support_test.go
internal/featuresupport/features_misc.go
internal/host/hostcommands/install_cmd_test.go

Problem: For s390x architectures a multiarch payload is blocked and choosing a multi image via Assisted Installer or Agend-based Installer shows the error: "cannot use Skip MCO reboot because it's not compatible with the s390x architecture..."
This check is obsolete because s390x is supporting mutlitarch payloads.
Solution: With this fix the feature will be enabled for s390x architectures.
Test: The switch was removed for s390x architecture and the existing tests where adapted. Test was done using assisted-test-infra by using the branch. 
Doc: There is a misleading information in the Doc and should be removed but this is not related to this PR because e.g. for ppc64le architecture the statement is wrong, too (Bug). Nevertheless the doc for Assisted Installer need to be verified and …

MGMT-17805: Fix MCO reboot error for s390x

---

Makefile
deploy/kind/agent-svc-config.yaml
deploy/kind/assisted-service-portmap.yaml
docs/dev/kind/README.md
hack/hub_cluster.sh
hack/kind/dev-env-infra.sh
hack/kind/dev-env-sylva.sh
hack/kind/kind-config.yaml
hack/kind/kind.sh

This commit adds additional documentation and files to create development environments using kind.
In this 1st phase, a couple of scenarios have been created to start an environment with the infrastructure operator and another with CAPI (sylva project).
In future, I will continue by getting feedback from other team members and evolving the functionalities to increase the coverage of our work scenarios.
- With these changes it should be possible to start small `assisted-service` environments using `make deploy-dev-infra`. More specific information on how to try this out is in the README file included with the commit.

NO-ISSUE: Prepare base documents and targets for devel environments using kind

---

cmd/operator/main.go
internal/controller/controllers/local_cluster_import_controller.go
internal/controller/controllers/local_cluster_import_controller_test.go

When performing a local cluster import - the local cluster name is hardwired to "local-cluster", this is not flexible enough and needs to be changed.
We should be picking up the name from the ManagedCluster that is labelled as "local-cluster" - this should then be used wherever we use the present local-cluster name.
An additional check is performed to ensure that the clusterID referenced in the labels of ManagedCluster matches the clusterID in the labels found in the
clusterVersion of the hub on which the LocalClusterImport is running.
This should be sufficient at this stage as we do not need to handle scenarios such as a "rename", mainly because ACM will be enforcing some rules
From ACM-DDR-022:
```
To ensure backward compatibility, we will not directly allow renaming the local cluster …
```

MGMT-18659: Local cluster name should be picked up from ACM ManagedCluster label

---

internal/controller/controllers/local_cluster_import_controller.go

When the local cluster name could not be resolved, we inadvertantly try to clean it up. This issue addresses that by ensuring we do not attempt cleanup in the absence of a name derived from ManagedCluster

MGMT-18702: Fix error due to missing local cluster name

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_storage_validation_test.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go

A race condition exists where the assisted-service deployment mounts
the assisted-service trusted ca bundle config map before it contains
anything. This can cause the certificate validation to fail when
using mirror registries because the ca bundle is empty.
This adds a check to make sure the ca bundle config map contains a value
before creating the assisted-service deployment.
/cc …

MGMT-18645: Ensure CA bundle exists before assisted-service

---

internal/manifests/manifests.go
internal/manifests/manifests_test.go

Presently if an empyty filename is passed or if the filename is nil, the code may panic This PR addresses that by adding suitable validations to ensure these panics do not occur.

MGMT-14634: Ensure that nil values and empty values for filenames are handled correctly.

---

pkg/staticnetworkconfig/generator.go
pkg/staticnetworkconfig/generator_test.go

For static network interface names that match physical interfaces don't require mac-address mapping. This allows the names to be in the networkConfig section only to handle, for example, disabled interfaces.

MGMT-18694, MGMT-18575, OCPBUGS-34849: Don't require mapping for names matching physical interfaces

---

docs/hive-integration/README.md
internal/controller/controllers/infraenv_controller.go
internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go

Currently when a hub cluster is dual-stack the only way the preprovisioning image controller can determine which callback IP family to provide to the ironic agent is to use the cluster reference in the infraenv. If there is no cluster reference (for late binding cases) then the controller always provides the primary IP family of the hub cluster.
This prevents users from using late-binding to deploy ipv6 only hosts from an ipv4-primary dual-stack hub (or vice versa).
This commit adds an annotation on the infraenv that can be used to override the ip family used when discovering hosts with a particular discovery image. `infraenv.agent-install.openshift.io/ip-family` can be set to `v4`, `v6`, or `v4,v6` to indicate to the controller which family should be used.
In newer OCP versions the …

MGMT-18510: Add an annotation to override ironic IP family to provide in dual-stack hubs

---

cmd/main.go
internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

This change is introducing a solution for reprovisioned BMHs of restored spoke clusters.
The suggested logic ensures that a 'status' annotation is always available for BMHs in state 'provisioned'.
By that, as suggested in BMO docs[1] for moving BMHs bwtween hub, the status is restored from the annotation.
I.e. When the status is available, BMHs reprovisioning by Ironic is prevented.
See full flow and more details in the enhancement[2], 'Solution for BMHs reconcile' section.
[1] BMO documentation:
https://github.com/metal3-io/metal3-docs/blob/6a656b3eb195c1b09ba35fcad4d011c6cb02dbc2/docs/user-guide/src/bmo/status_annotation.md
[2] Enhancement: https://github.com/openshift/assisted-service/pull/6683
- Is there a …

MGMT-18636: Handle status annotation in provisioned BMHs

---

.github/dependabot.yml

Moving depndabot to security updates only due for the following issues
1. updates the Golang versions 
2. breaking code changes 
3. some URL's stop  working when using `go get -u`

MGMT-18466: moving to security updates only

---

internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go

This is a manual backport of #6532 and [MGMT-17893](https://issues.redhat.com//browse/MGMT-17893) to OCM 2.10.
Currently the procedure to detach a cluster that was created using hosts from a late binding pool is to first delete the `ManagedCluster` object, then add the `preserveOnDelete: true` field to the `ClusterDeployment` and then delete that `ClusterDeployment`. But the cluster deployment controller doesn't look at the `preserveOnDelete` field at all. As a result the hosts of the cluster are returned to the pool and they are provisioned again, which effectively destroys the cluster.
This patch changes the deployment manager controller so that in that case it will check the `preserveOnDelete` field and if it is `true` it will delete the corresponding `Agent` objects. The result of …

MGMT-18455: Don't destroy cluster on detach - OCM 2.10 backport

---

pkg/staticnetworkconfig/generator.go
pkg/staticnetworkconfig/generator_test.go

I removed the execution of generateConfiguration and its associated error check in GenerateStaticNetworkConfigDataYAML because it is not needed at this stage of the code. The validation, where it is required, already handles this.

MGMT-18579: Remove generateConfiguration call and its associated error check

---

internal/bminventory/inventory.go
internal/bminventory/mock_installer_internal.go
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
subsystem/kubeapi_test.go

When applying an Agent CR with a missing associated host, the Agnet CR is currently being deleted by the reconciler. This scenario would happen on restore to a new hub flows since the host is a DB only entity.
Thus, this change introduces handling of a missing host by restoring the object into DB according to properties from the Agent CR.
For restoring the host's status, added 'state' annotation to the agent which is set on reconcile.
See full flow and more details in the enhancement: https://github.com/openshift/assisted-service/blob/master/docs/enhancements/backup-restore-support.md#solution-for-deleted-agent-crs …

MGMT-18635: Restore missing Host by Agent CR

---

internal/migrations/20240918161800_drop_cluster_platform_is_external.go
internal/migrations/20240918161800_drop_cluster_platform_is_external_test.go
internal/migrations/migrations.go

`platform_is_external` is a left over of the development of the external
platform. Its usage was removed with https://github.com/openshift/assisted-service/pull/5787/files#diff-8b1949772e223a1da6a2049ada2733fa506410975b241cf86cf44c7a8665bc62L5394-L5399
more than half a year ago.

MGMT-16437: drop platform_is_external column

---

Makefile
tools/deploy_assisted_installer_configmap.py

This PR fixes the local deployment of assisted-service with `AUTH_TYPE=rhsso`, previously was failing on creating authenticator, due to invalid `JWKS_URL`.
Also adds an option to insert custom `JWKS_URL` via environment variable.
JWKS_URL from configmap after deploying :
`JWKS_URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/certs`
ensure all pods are running :
logs from assisted service pods :
`time="2024-09-18T17:35:16Z" level=info msg="Created rhsso authenticator" func=github.com/openshift/assisted-service/pkg/auth.NewAuthenticator file="/assisted-service/pkg/auth/authenticator.go:60" pkg=auth`
`time="2024-09-18T17:35:51Z" level=info msg="Starting http handler on :8090..."`
`curl -X GET "http://10.6.48.63:8090/api/assisted-install/v2/clusters" -H …

MGMT-18618: Fix local rhsso deployment

---

internal/common/dedent.go
internal/common/dedent_test.go

This patch adds a new `common.Dedent` function that removes all common leading white space from strings. This is intended for situations where it is convenient to include JSON or YAML documents inside Go code, but it is cumbersome to have very long lines or concatenation of strings.
Note that this code has been copied from here: https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/tree/main/ztp/internal/text
Tested with the included unit tests. …

NO-ISSUE: Add Dedent function

---

deploy/operator/mirror_utils.sh
deploy/operator/setup_assisted_operator.sh
deploy/podman/README-disconnected.md
docs/operator.md
docs/user-guide/cloud-with-mirror.md

This patch updates scripts and documentation to use the `ImageDigestMirrorSet` instead of the deprecated
`ImageContentSourcePolicy` where possible. The deprecated behaviour is preserved to support versions of OpenShift older than 4.14.
Related: https://issues.redhat.com/browse/MGMT-17230
Related: https://github.com/openshift/enhancements/blob/master/enhancements/api-review/add-new-CRD-ImageDigestMirrorSet-and-ImageTagMirrorSet-to-config.openshift.io.mdTmp …

MGMT-17230: Update scripts and docs to use IDMS instead of ICSP

---

Makefile

Conditioning a bash var according if it is set or not is a bad practice especially because we use multiple layers of variables setting in this scripts.

NO-ISSUE: Explicitly set DEBUG_SERVICE with true value to avoid unexplicit setting

---

internal/oc/release.go
internal/oc/release_test.go

Currently when we run the 'oc' command in disconnected environments whe generate a `ImageContentSourcePolicy` object inside a YAML file and reference it with the `--icsp-file` command line flag. That is deprecated since OpenShift 4.14, and replaced by the `ImageDigestMirrorSet` object and the `--idms-file` command line flag.
This patch changes the code so that it checks if the `--idms-file` command line flag is available, and if it is it generates a `ImgeDigestMirrorSet` and uses the `--idms-file` flag instead of the deprecated `--icsp-file`.
The previous behaviour is preserved when the `--idms-file` flag isn't available in order to keep supporting older OpenShift versions.
Related: https://issues.redhat.com/browse/MGMT-17230
Related: …

MGMT-17230: Use IDMS when possible

---

internal/oc/release.go
internal/oc/release_test.go

This reverts commit c7c506cb4d94ed5fa5e793b66c14663f82c691cb.
This is necessary because the `oc image info` command doesn't support the `--idms-file` flag yet.
Related: https://issues.redhat.com/browse/MGMT-17230
Related: https://github.com/openshift/assisted-service/pull/6764
Related: https://github.com/openshift/enhancements/blob/master/enhancements/api-review/add-new-CRD-ImageDigestMirrorSet-and-ImageTagMirrorSet-to-config.openshift.io.md …

MGMT-17230: Revert use IDMS when possible

---

subsystem/kubeapi_test.go

Due to a temporary issue, the kube-api subsystem tests passed falsely. Thus, masking the failure of `deploy clusterDeployment and infraEnv and with an invalid NMState config YAML`  in https://github.com/openshift/assisted-service/pull/6695. See [job](https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-openshift-assisted-service-master-edge-subsystem-kubeapi-aws-periodic). To avoid blocking PRs, I am temporarily removing this test until it is fixed.
A follow up issue - https://issues.redhat.com/browse/MGMT-19027 …

NO-ISSUE: Remove failing NMState kube api test until it is fixed

---

api/vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
client/vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/controller/controllers/infraenv_controller.go
models/infra_env_update_params.go
restapi/embedded_spec.go
subsystem/infra_env_test.go
subsystem/kubeapi_test.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go

Allow updating the InfraEnv OpenshiftVersion in both the REST and kube APIs.
This is useful when after initial install a user wants to add a new node to a cluster, but the cluster has been upgraded between install and the scale out. Previously a user would need to create a new infraenv with identical settings to the old one and a newer version.
With this change users will be able to update the infraenv os image version just like other attributes.
For some background:
The field was added to the InfraEnv CR in https://github.com/openshift/assisted-service/pull/5365 for https://issues.redhat.com//browse/MGMT-14923 and I don't see any discussion there about updates.
Based on the PR that added infraenv update (https://github.com/openshift/assisted-service/pull/2319) the update params were …

ACM-14502: Allow updates to InfraEnv version

---

pkg/staticnetworkconfig/generator.go
subsystem/kubeapi_test.go

This PR addresses the failing kubeapi test, follow-up [this](https://github.com/openshift/assisted-service/pull/6839) PR.

MGMT-19027: Fix failing kubeapi subsystem test invalid NMstate YAML

---

subsystem/kubeapi_test.go

Fixed timing issue in kube-api test on agent update (when using kind):
```
Operation cannot be fulfilled on agents.agent-install.openshift.io "b070fb06-3e15-4a11-99b2-0bcc165edd4a": the object has been modified; please apply your changes to the latest version and try again
```

NO-ISSUE: fix 'object has been modified' error in kubeapi subsystem

---

cmd/main.go
internal/bminventory/inventory.go
internal/common/test_configuration.go
internal/ignition/discovery.go
internal/ignition/discovery_test.go
internal/isoeditor/rhcos_test.go
openshift/template.yaml
pkg/staticnetworkconfig/backward_compatibility.go
pkg/staticnetworkconfig/generator.go
pkg/staticnetworkconfig/generator_test.go
pkg/staticnetworkconfig/mock_generator.go
subsystem/infra_env_test.go

Since version 4.18 includes an updated nmstate, it was decided to enable the nmstate service flow for static networking starting from ocp version 4.18 and above. To provide flexibility, this is implemented as a feature flag, with the default set to 4.18. The version can be adjusted if needed, primarily for testing purposes.

MGMT-18579, MGMT-19018: Add feature flag for minimal OCP version for nmstate service flow

---

internal/oc/release.go
internal/oc/release_test.go

Currently when we run the 'oc' command in disconnected environments we generate a `ImageContentSourcePolicy` object inside a YAML file and reference it with the `--icsp-file` command line flag. That is deprecated since OpenShift 4.14, and replaced by the `ImageDigestMirrorSet` object and the `--idms-file` command line flag.
This patch changes the code so that it checks if the `--idms-file` command line flag is available, and if it is it generates a `ImageDigestMirrorSet` and uses the `--idms-file` flag instead of the deprecated `--icsp-file`.
The previous behavior is preserved when the `--idms-file` flag isn't available in order to keep supporting older OpenShift versions.
Note that this is the second take of this fix. The first was reverted because, unlike the other commands, the `oc …

MGMT-17230: Use IDMS when possible, take two

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go

This is the default in openshift, but some storage implementations will look for this value when configuring the filesystem on a PVC.
Resolves https://issues.redhat.com/browse/MGMT-18996
Before the code change the command referenced from the issue returned data missing the runAsGroup field, after the runAsGroup field is present:
Before:
```
{
"fsGroup": 1000740000,
"seLinuxOptions": {
"level": "s0:c27,c19"
},
"seccompProfile": {
"type": "RuntimeDefault"
}
}
```
After:
```
{
"fsGroup": 1000740000,
"runAsGroup": 0,
"seLinuxOptions": {
"level": "s0:c27,c19"
},
"seccompProfile": {
"type": "RuntimeDefault"
}
}
```

MGMT-18996: Set pod security context to ensure group is root.

---

deploy/podman/pod-persistent-disconnected.yml

Currently this pod definition uses a `subPath` to mount the CA bundle, but that isn't necessary and fails with this error:
```
starting container bcb65834269b94764596a6f4ee1a70fd2b1af8f424e724792c7b6a166ee13554: crun: mount `/run/containers/storage/overlay-containers/bcb65834269b94764596a6f4ee1a70fd2b1af8f424e724792c7b6a166ee13554/userdata/subpath360836111` to `etc/pki/ca-trust/extracted/pem`: Not a directory: OCI runtime error
```
This patch removes that incorrect line. …

NO-ISSUE: Don't use `subPath` in `pod-persistent-disconnected.yml`

---

internal/operators/cnv/cnv_operator.go

- fix issue where you can't deploy CNV on ARM due to LSO dependencies 
/cc @AlonaKaplan

MGMT-19054: remove LSO as default for CNV on ARM

---

cmd/main.go

In OCP 4.17, debug logging was enabled for the agent-based installer which started pprof. This had the side effect of conflicting with the port in use by CCO.
- [ x] This change does not require a documentation update (docstring, `docs`, README, etc)

OCPBUGS-42525: Disable pprof for agent-based installer

---

subsystem/kubeapi_test.go

Similar to https://github.com/openshift/assisted-service/pull/6850, fixed timing issue in kube-api test on BMH update. Also, removed BMH finalizers on cleanup.

MGMT-19085: fix 'object has been modified' error in kubeapi subsystem

---

build_deploy.sh
build_images.sh

We want to change app-interface to deploy the images that Konflux builds and by default Konflux uses the full commit sha as the tag.
In order to avoid issues with telling app-interface to use the full commit sha, I am updating build_deploy.sh to push both the full sha and the short sha as image tags.
Part of [MGMT-19129](https://issues.redhat.com//browse/MGMT-19129)

MGMT-19129: Migrate assisted-service to Konflux

---

api/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
client/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
internal/cluster/finalizing_stages.go
internal/cluster/finalizing_stages_test.go
models/finalizing_stage.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/finalizing_stage.go

This patch adds a new finalizing stage that indicates that the assisted installer controller is waiting for OLM setup jobs to complete.
https://issues.redhat.com/browse/MGMT-19148
https://issues.redhat.com/browse/MGMT-19056

MGMT-19148: Add OLM operator setup jobs finalizing stage

---

deploy/operator/capi/deploy_capi_cluster.sh
deploy/operator/gather.sh

Upgrades the default hypershift image tag from
4.11 to latest.
Collects agentmachinetemplates CRs.
Patches the nodepool if scaling it with `oc scale` fails.
---
Came from the CAPI CI tests (such as [this](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-cluster-api-provider-agent-master-e2e-ai-operator-ztp-capi-periodic/1848091909545791488))
with the following failure logs
```
[2024-10-20 22:13:08] + oc get nodepool/assisted-test-cluster --selector= --namespace=assisted-spoke-cluster
[2024-10-20 22:13:08] NAME                    CLUSTER                 DESIRED NODES   CURRENT NODES   AUTOSCALING   AUTOREPAIR   VERSION   UPDATINGVERSION   UPDATINGCONFIG   MESSAGE
[2024-10-20 22:13:08] assisted-test-cluster   assisted-test-cluster   0 …
```

NO-ISSUE: Update CI gather script and fix failing to scale nodepool

---

ci-images/Dockerfile.code-generation
deploy/olm-catalog/bundle.Dockerfile
deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
deploy/olm-catalog/metadata/annotations.yaml
hack/setup_env.sh

replace `operator-sdk` binary version as the new version omits `releatedImages` in the code generation, and `releatedImages` is required in the catalog publish. The version was bumped in - https://github.com/openshift/assisted-service/pull/6882/commits/f00f890174b2d7fc29a876c61856ac3846e91aebas. 
link to a failing job - https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-assisted-service-master-edge-assisted-operator-catalog-publish/1848357706071543808.
**Note** - This should be a temporary solution until the operator publish script will be modified to the new behaviour …

MGMT-19176: Reduce the version of operator-sdk binary

---

cmd/agentbasedinstaller/agentbasedinstaller_suite_test.go
cmd/agentbasedinstaller/client/main.go
cmd/agentbasedinstaller/import.go

This patch allows the agent-installer-client to consume the new ISO config file `/etc/assisted/clusterconfig/worker-ignition-endpoint.json` to further configure a cluster after having imported it, during the add nodes workflow (day2).
Required by https://github.com/openshift/installer/pull/9129
- [] None

OCPBUGS-43513: allow configuring cluster UserManagedNetworking field when importing a cluster

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

For Hypershift's backup and restore of hosted cluster from one hub to a new hub, the Agent requires these status fields to be restored in order for the NodePool to successfully re-adopt the Nodes for the hosted cluster.
/cc @danielerez @jhernand @carbonin

MGMT-19194: Save Agent inventory and status in annotation

---

internal/ignition/discovery.go
internal/ignition/discovery_test.go

An InfraEnv that's not attached to a cluster will not know what release image to use so it'll be unable to find an OKD image. This removes getting the OKD image unless the InfraEnv is attached to a Cluster.
Mentioned in the original introduction that this flow is not broken https://github.com/openshift/assisted-service/pull/4650/files#r1044872735

MGMT-19218: Remove getting OKD for late-binding InfraEnv

---

internal/events/event.go
internal/events/event_test.go

There is a scenario in which a user will use the same host for multiple installation attempts, in this scenario the cluster, infra env and original host will be deleted each time an installation is attempted.
When a new cluster is created and the host is added, it will have the same ID as the previously installed host. The events will contain entries for all previous incarnations of that host.
The problem occurs when the user attempts to fetch "host bound" events for that host, providing the host ID exclusively.The existing implementation of the events endpoint will return all events for a given host ID.
This creates an excessively large number of results, many of which are invalid.
The solution implemented in this PR
is to ensure that when fetching host exclusive events we condsider only …

MGMT-18863: Fix bug in host event list endpoint

---

internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go

Previously, the `ClusterImageSet` defined by a `ClusterDeployment` was only cached if the cluster was being created. This is problematic in the long run if assisted is restarted and the cluster is not recreated. Errors "getting the release image" will occur due to this.
To prevent this, we'll now always try to cache the ClusterImageSet defined for a cluster even if it's already installed. This also allows us to ensure that the image the user specified in the ClusterImageSet as the release image to be installed.
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-req …

MGMT-19158: Always try to cache the ClusterImageSet

---

internal/installercache/installercache.go
internal/installercache/installercache_test.go
internal/oc/release.go
internal/oc/release_test.go

Currently, the local image mirror url is used when running the 'oc' commands. This can cause a problem if the mirror configuration has multiple mirrors, since there will be no failover if the url is unreachable. Instead, the actual releaseImage should be used when the icsp or idms configuration is provided to ensure proper failover.

OCPBUGS-42705: Use icsp/idms for oc commands instead of releaseMirror

---

internal/ignition/ignition.go
internal/ignition/ignition_test.go

Manual cherry-pick of https://github.com/openshift/assisted-service/pull/6963
Original commit message:
---
An InfraEnv that's not attached to a cluster will not know what release image to use so it'll be unable to find an OKD image. This removes getting the OKD image unless the InfraEnv is attached to a Cluster.
Mentioned in the original introduction that this flow is broken https://github.com/openshift/assisted-service/pull/4650/files#r1044872735 …

[release-ocm-2.10] MGMT-19218: Remove getting OKD for late-binding InfraEnv

---

internal/bminventory/inventory_test.go
internal/cluster/cluster_test.go
internal/operators/handler/handler_test.go

This patch fixes several tests that fail when executed locally with a recent version of PostgreSQL, in particular version 16.
- _Test that DHCP VIPs were cleared when switching to UserManagedNetworking: true_.
This test fails when executed individually because it tries to update
the VIPs in the database doing `db.Save(&cluster)`, but that only
saves the cluster itself, and not other referenced tables, like the
VIPs tables. I believe this works in CI today because of the state of
the database generated by previous tests. The patch changes it to
explicitly save the VIPs using `db.Save(&models.APIVip{...})`.
- _single SNO vsphere host_ and other related tests.
These fail because in recent versions of PostgreSQL it is not the OK to update the database with zero timestamps: the database server …

NO-ISSUE: Fix unit tests that fail locally

---

docs/operator.md

This is documentation to describe the feature that allows a user to define headers and query params to be used by the image service every time a request to pull an OS image is made.

MGMT-16691: Document OSImageAdditionalParamsRef functionality for infrastructure operator

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/progress_test.go
internal/cluster/transition.go
internal/cluster/transition_test.go
internal/constants/installation_preparation_status_reasons.go
internal/host/refresh_status_preprocessor_test.go
subsystem/cluster_test.go

There is a bug that manifests when the installation endpoint for a cluster is called while the cluster is in an invalid state for install.
The installation request is correctly rejected, however the "Last Installation Preparation Status" fields are prematurely reset to LastInstallationPreparationStatusNotStarted.
These should only be reset when the cluster transitions between the "ready" and "preparing for installation" states.
This PR introduces a test for this assertion and additionally changes behaviour to match.
I introduced a test for "reset" cluster and functionality to apply the Last Installation Preparation Status reset when the cluster installation is reset. …

MGMT-19230: Handle installation preparation status in statemachine

---

internal/hardware/validator.go
internal/hardware/validator_test.go

Openshift version is empty when the cluster is day2.
This fix infer the openshift version from the infraenv when the cluster
is not available or is day2.

MGMT-19280: iSCSI volume should be eligible on day2

---

internal/hardware/validator.go
internal/hardware/validator_test.go

From openshift 4.14 users have been allowed to use nodes with intel vroc, which makes the device look like a software RAID device (md device).
This pr allows using this device type in assisted-installer as well, if the openshift version is 4.14 or above.
Part of [MGMT-19150](https://issues.redhat.com//browse/MGMT-19150) together with [this pr](https://github.com/openshift/assisted-installer-agent/pull/820) to assisted-installer-agent.
I tested the PRs together, I created an md device on a node I wanted to install as an SNO and saw in the ui that the md device shows up and can be chosen as the installation device if the openshift version is 4.14 or above.
- …

MGMT-19150: add support for RAID drivers for openshift 4.14 an above

---

internal/common/conversions.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook_test.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go

Update the conversion function that maps hive palatform to AI platform
to handle the external platform spec.

MGMT-19237: Update validation hook to support external platform

---

internal/operators/openshiftai/openshift_ai_config.go
internal/operators/openshiftai/openshift_ai_operator.go
internal/operators/openshiftai/openshift_ai_operator_test.go
openshift/template.yaml

Currently the OpenShift AI operator only supports NVIDIA GPUs. This complicates testing in environments where there are no such GPUs. To simplify that this patch adds a new `OPENSHIFT_AI_SUPPORTED_GPUS` environment variable that contains the vendor identifiers of the supported GPUs. By default the value is `10de`, which is the NVIDIA vendor identifier, so we still only support NVIDIA GPUs by default. But the value can be a comma separated list of vendor identifiers. For example, the value `10de,1af4` means that both NVIDIA and Virtio GPUs are supported. This can be used in the testing environments to be able to test the operator using virtual GPUs without any real hardware.
Note that this use of Virtio GPUs is intended only for tests: it isn't possible to actually use those virtual GPUs …

NO-ISSUE: Allow configuring suported GPUs

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

For completeness, if a host has begun installing, store the current stage in the Agent's annotations so that if a host needs to be restored, we'll also have that data.
- Installed a hypershift `HostedCluster` and scaled up the `NodePool` to include one `Agent`
- wait until the `Agent` was in `Done` stage
- Saved the `Agent` CR and deleted the `Agent` (ensuring to annotate before deleting with `oc annotate agent --all -n spoke-cluster agent.agent-install.openshift.io/skip-spoke-cleanup=true`)
- Removed the host from the DB and restored the `Agent` (oc apply)
- After the `Agent` is restored, checked `oc get agent` to verify that the stage was `Done`
- Should …

MGMT-19192: Add current stage when restoring host by Agent

---

internal/installcfg/builder/builder.go
internal/installcfg/installcfg.go
internal/provider/baremetal/installConfig.go
internal/provider/baremetal/installConfig_test.go
internal/provider/baremetal/suite_test.go
internal/provider/base.go
internal/provider/external/base.go
internal/provider/mock_base_provider.go
internal/provider/none/installConfig.go
internal/provider/nutanix/installConfig.go
internal/provider/registry/mock_providerregistry.go
internal/provider/registry/registry.go
internal/provider/registry/registry_test.go
internal/provider/vsphere/installConfig.go
vendor/github.com/openshift/assisted-service/api/common/common_types.go

In OpenShift 4.18 a new `additionalNTPServers` field was added to the baremetal platform section of the `install-config.yaml` file . This needs to be populated with the NTP sources provided by the user in order to correctly set time before installation of new nodes using the baremetal provisioning flow.
https://issues.redhat.com/browse/OCPBUGS-44882
Tested creating a baremetal cluster and checking the generated installer configuration file. …

OCPBUGS-44882: Add NTP sources to generated install-config.yaml

---

internal/host/monitor.go
internal/host/monitor_test.go

Performance test in stage showed that the assisted-service continued to
monitor hosts even after the cluster installed. This behavior consumes
a lot of CPU, this PR disables it by stopping monitoring  hosts in "Installed" 
state when cluster state is "Installed".
Also, move the logic from `SkipMonitoring` function into the SQL query so
we avoid to retrieve hosts that we be skipped anyway (and save some
un-marshaling operations).

MGMT-19360: do not monitor hosts with status installed

---

internal/installcfg/builder/builder.go
internal/installcfg/installcfg.go
internal/provider/baremetal/installConfig.go
internal/provider/baremetal/installConfig_test.go
internal/provider/baremetal/suite_test.go
internal/provider/base.go
internal/provider/external/base.go
internal/provider/mock_base_provider.go
internal/provider/none/installConfig.go
internal/provider/nutanix/installConfig.go
internal/provider/registry/mock_providerregistry.go
internal/provider/registry/registry.go
internal/provider/registry/registry_test.go
internal/provider/vsphere/installConfig.go

This is a backport of OCPBUGS-44882 for ACM 2.12.
In OpenShift 4.18 a new `additionalNTPServers` field was added to the baremetal platform section of the `install-config.yaml` file . This needs to be populated with the NTP sources provided by the user in order to correctly set time before installation of new nodes using the baremetal provisioning flow.
Related: https://issues.redhat.com/browse/MGMT-19388
Related: https://issues.redhat.com/browse/OCPBUGS-44882
Tested manually verifying that the generated `install-config.yaml` contains the NTP sources. …

MGMT-19388: Add NTP sources to generated install-config.yaml - ACM 2.12

---

internal/host/monitor.go
internal/host/monitor_test.go

Performance test in stage showed that the assisted-service continued to
monitor hosts even after the cluster installed. This behavior consumes
a lot of CPU, this PR disables it by stopping monitoring  hosts in "Installed" 
state when cluster state is "Installed".
Also, move the logic from `SkipMonitoring` function into the SQL query so
we avoid to retrieve hosts that we be skipped anyway (and save some
un-marshaling operations).

[cloud_hotfix_releases] MGMT-19360: do not monitor hosts with status installed (#7030)

---

deploy/operator/capi/deploy_capi_cluster.sh
deploy/operator/hypershift/deploy_hypershift_cluster.sh
deploy/operator/setup_assisted_operator.sh
deploy/operator/setup_hive.sh
deploy/operator/utils.sh
deploy/operator/ztp/deploy_spoke_cluster.sh

Improve waiting function and debugging messages when deploying resources 
This is a fix for unstable tests, which are failing to loops timed out without error or displaying error message 

MGMT-18628: fix better waiting for deployment

---

internal/operators/nvidiagpu/nvidia_gpu_operator.go
internal/operators/nvidiagpu/nvidia_gpu_operator_test.go

Currently when the _OpenShift AI_ operator is enabled the NVIDIA GPU is automatically enabled as well. But this operator will not work if secure boot is enabled: the NVIDIA drivers are built dinamically, and not signed, so they can't be loaded. To ensure that the user is aware of that this patch adds a validation to check that.
https://issues.redhat.com/browse/MGMT-19331

MGMT-19331: Secure boot must be disabled for NVIDIA GPUs

---

docs/dev/README.md

MGMT-18227: Add quickstart document for new developers

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

Primarily affects hosted control planes.
After restoring Agents, the validations status showed up as failing in the AgentMachines. This adds the validations information to the Agent's status so that it is picked up and restored to the host.

MGMT-19413: Add validations info to the Agents annotations

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/ignition/discovery.go
internal/ignition/discovery_test.go
pkg/staticnetworkconfig/backward_compatibility.go
pkg/staticnetworkconfig/generator.go
pkg/staticnetworkconfig/generator_test.go
pkg/staticnetworkconfig/mock_generator.go

Since we now fetch nmstatectl binary from the rootfs (https://issues.redhat.com/browse/MGMT-18577) instead of from the assisted- image pod, each architecture uses the appropriate nmstatectl binary for its own arch. Therefore, we can remove the condition checking for x86, which enabling the nmstate flow for all architectures.

NO-ISSUE: Enable static network using the nmstate flow across all architectures

---

internal/network/manifests_generator.go
internal/network/manifests_generator_test.go

The server instructs the agent to perform NTP synchronization, and when the results are received it stores the results in the `ntp_sources` column of the `hosts` table. But in the ZTP flow installation may start before that response is received, so that `ntp_sources` column may be empty. The value of this column is used to build the `MachineConfig` that configures NTP for the hosts, and we have a fallback that intends to use the NTP servers provided by the user in the `additionalNTPSources` field of the `InfraEnv` object. But the current code skips that fallback logic when the `ntp_sources` is empty. This patch fixes that.
Related: https://issues.redhat.com/browse/ACM-6053
Tested removing the NTP synchronization step, adding the additional NTP sources to the infrastructure environment and …

ACM-6053: Add NTP to machineconfig even if no sync

---

deploy/operator/setup_assisted_operator.sh

- removing `wait` which cause early failures

NO-ISSUE: fixing late binding

---

internal/featuresupport/features_misc.go
internal/featuresupport/features_olm_operators.go
internal/featuresupport/features_olm_operators_test.go

The OpenShift AI requires ODF, and that means that it is indirectly incompatible with LVM and SNO. But our feature support mechanism doesn't currently understand dependencies between operators. As a result it is possible to update a cluster so that it will have OpenShift AI and SNO, for example, enabled simultaneously. To avoid that this patch adds those indirect incompatibilities to the OpenShift AI operator, like they were direct incompatibilities.
https://issues.redhat.com/browse/MGMT-19362
Tested manually creating a cluster with SNO enabled and then patching it to add OpenShift AI. Same for LVM. …

MGMT-19362: Explicitly add OpenShift AI incompatibilities

---

internal/spoke_k8s_client/factory.go
internal/spoke_k8s_client/mock_spoke_k8s_client_factory.go

This patch removes the `CreateFromStorageKubeconfig` method, as it isn't used and complicates changes to that client factory.
https://issues.redhat.com/browse/MGMT-19120

NO-ISSUE: Remove unused method from spoke client factory

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

Observed in an environment when restoring Hosts from Agents that the Agents aren't requeued and their statuses are never updated. This adds a requeue timer so that they actually get requeued.

MGMT-19414: Add default requeue time when Hosts are created from Agents

---

internal/network/manifests_generator.go
internal/network/manifests_generator_test.go

This is a backport of [ACM-6053](https://issues.redhat.com//browse/ACM-6053) for ACM 2.11.
The server instructs the agent to perform NTP synchronization, and when the results are received it stores the results in the `ntp_sources` column of the `hosts` table. But in the ZTP flow installation may start before that response is received, so that `ntp_sources` column may be empty. The value of this column is used to build the `MachineConfig` that configures NTP for the hosts, and we have a fallback that intends to use the NTP servers provided by the user in the `additionalNTPSources` field of the `InfraEnv` object. But the current code skips that fallback logic when the `ntp_sources` is empty. This patch fixes that.
https://issues.redhat.com/browse/ACM-16164 …

ACM-16164: Add NTP to machineconfig even if no sync - ACM 2.11

---

internal/network/manifests_generator.go
internal/network/manifests_generator_test.go

This is a backport of [ACM-6053](https://issues.redhat.com//browse/ACM-6053) for ACM 2.10.
The server instructs the agent to perform NTP synchronization, and when the results are received it stores the results in the `ntp_sources` column of the `hosts` table. But in the ZTP flow installation may start before that response is received, so that `ntp_sources` column may be empty. The value of this column is used to build the `MachineConfig` that configures NTP for the hosts, and we have a fallback that intends to use the NTP servers provided by the user in the `additionalNTPSources` field of the `InfraEnv` object. But the current code skips that fallback logic when the `ntp_sources` is empty. This patch fixes that.
https://issues.redhat.com/browse/ACM-16166 …

ACM-16166: Add NTP to machineconfig even if no sync - ACM 1.10

---

internal/controller/controllers/spoke_client_cache.go
internal/controller/controllers/spoke_client_cache_test.go
internal/spoke_k8s_client/factory.go
internal/spoke_k8s_client/factory_test.go
internal/spoke_k8s_client/mock_spoke_k8s_client_factory.go
internal/spoke_k8s_client/suite_test.go

This patch removes the `CreateFromRawKubeconfig` method that is only used in one place, replacing it with the `CreateFromSecret` method. This simplifies the client factory, which is convenient for future refactorings.
The more relevant change is that the spoke client cache now uses the complete data of the secret (serialized using JSON) to calculate the hash that is used to check if the kubeconfig should be re-created. That is to avoid having the logic to extract the kubeconfig from the `kubeconfig` field, as that is already part of the `CreateFromSecret` method of the factory. The tests related to that have also been moved to the `spoke_k8s_client` package.
https://issues.redhat.com/browse/MGMT-19120
- Is there …

NO-ISSUE: Simplify spoke client factory

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/common.go

There are no spoke bmh and machines created for a host that's installed to a cluster with baremetal platform without MAPI capability. We need to approve their CSRs too.

MGMT-18288: Approve CSRs for agents with baremetal platform without MAPI

---

internal/versions/api_test.go

As release images are not used in k8s API flow, testing the default ones from data directory is redundant. This PR changes this unit-test to validate only the default OS images by reading and parsing them.

[release-ocm-2.9] NO-ISSUE: Remove default release images testing for OCM branches

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/ignition/discovery.go
internal/ignition/discovery_test.go
pkg/staticnetworkconfig/backward_compatibility.go
pkg/staticnetworkconfig/backward_compatibility_test.go
pkg/staticnetworkconfig/generator.go
pkg/staticnetworkconfig/generator_test.go
pkg/staticnetworkconfig/mock_generator.go

As a temporary workaround, until the nmstate team resolves the issue with the MAC identifier, we will use the old static networking flow when the MAC identifier is present in the nmstate YAML.

MGMT-18891: Use old static network flow when MAC identifier exists

---

internal/ignition/ignition.go
internal/ignition/ignition_test.go
internal/ignition/templates/add-ntp-sources.service
internal/ignition/templates/add-ntp-sources.sh
internal/ignition/templates/discovery.ign

This is a backport of [MGMT-18411](https://issues.redhat.com//browse/MGMT-18411) and #6591 for ACM 2.10.
Currently when the user provides additional NTP sources for the installation they are used by the installed cluster, but not by the discovery environment. That means that the system clock of the discovery environment may be wrong if the default NTP servers can't be reached, and as result it may fail to pull images because the system clock may be before the validity date of the certificates of the registry server. To avoid that this patch changes the ignition of the discovery environment so that it will also use the NTP sources provided by the user.
https://issues.redhat.com/browse/MGMT-19672
https://issues.redhat.com/browse/MGMT-18411
Tested using the included unit tests.
- Are the …

MGMT-19672: Add NTP sources to discovery environment - ACM 2.10

---

cmd/main.go
internal/ignition/installmanifests.go
internal/ignition/installmanifests_test.go
internal/installercache/installercache.go
internal/installercache/installercache_test.go
pkg/generator/generator.go

To support Ephemeral storage improvement efforts in [MGMT-13917](https://issues.redhat.com//browse/MGMT-13917) It is desirable to have some statistics from the installer cache
ReleaseId                 The release being downloaded
Cached                    Was the release found in the cache (true) or did it need to be downloaded/extracted? (false)
StartTime                 The start time of the install cache request
EndTime                   The time at which the caller finished using the request
ExtractDuration           The time taken to extract the file in seconds (zero if no extraction took place)
This wil be sent in a single metrics event, the event time of the event represents the time that the release was no longer needed by callers. All of the above should be sufficient to give …

MGMT-19573: Track release stats in installercache

---

cmd/agentbasedinstaller/host_config.go

If the rootDeviceHint is not found, log info about eligible disks. This is needed because the disk inventory in the the logs does not always reflect eligible disks.
Note that this is the first part of a change to reflect this info in the agent-based installer wait-for output.
- [ x] Enhancement 

OCPBUGS-43578: Log disk info if rootDeviceHint not found

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/validations/validations.go
internal/cluster/validator.go
internal/cluster/validator_test.go
internal/featuresupport/features_networking.go
internal/host/validations_test.go
internal/host/validator.go
internal/network/cidr_validations.go
internal/network/cidr_validations_test.go
internal/network/machine_network_cidr.go
internal/network/machine_network_cidr_test.go
internal/network/utils.go

This PR continues - https://github.com/openshift/assisted-service/pull/7096 by expanding user-managed load balancer support to support load balancers IP which could be outside the hosts subnet as well.
**Note** - OpenShift network operator requires each VIP to be part of at least one machine network. Therefore, we require from the user to provide the necessary machine networks for both the hosts and VIPs when using user-managd load balancer, and enable using more than one. 
Two e2e tests were configured to test this flow:
- `edge-e2e-metal-assisted-umlb-4-18` (REST API)
- `edge-e2e-metal-assisted-kube-api-umlb-4-18` (k8s AI)
This PR also disables `dual-stack` features with this one, as they seem to be incompatible at the moment. It could be enabled in the future in case they will be …

MGMT-19590: Enable user managed load balancer with hosts in the same subnet but load balancer outside this subnet on baremetal

---

internal/featuresupport/features_misc.go
internal/featuresupport/features_networking.go
internal/host/validations_test.go
internal/host/validator.go
internal/ignition/installmanifests.go
internal/ignition/installmanifests_test.go
internal/installcfg/builder/builder.go
internal/installcfg/builder/builder_test.go
internal/network/machine_network_cidr.go
internal/network/machine_network_cidr_test.go
internal/provider/baremetal/installConfig.go
internal/provider/baremetal/installConfig_test.go
internal/provider/registry/registry_test.go

This PR continues - https://github.com/openshift/assisted-service/pull/7187 by expanding user-managed load balancer support to support hosts on different subnets as well.
**Note** - OpenShift network operator requires each VIP to be part of at least one machine network. Therefore, we require from the user to provide the necessary machine networks for both the hosts and VIPs when using user-managd load balancer, and enable using more than one. 
Two e2e tests were configured to test this flow:
- `edge-e2e-metal-assisted-umlb-4-18` (REST API)
- `edge-e2e-metal-assisted-kube-api-umlb-4-18` (k8s AI)
This PR also disables `SNO` feature with this one, as SNO requires `user-managed networking` which is incompatible with this one.
- Are the title and description (in both PR and commit) meaningful …

MGMT-19733: Enable user-managed load balancer with hosts on different subnets

---

api/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
client/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
internal/host/conditions.go
internal/host/conditions_test.go
internal/host/config.go
internal/host/host.go
internal/host/hostcommands/disk_performance_cmd.go
internal/host/hostcommands/disk_performance_cmd_test.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/hostcommands/instruction_manager.go
internal/host/refresh_status_preprocessor.go
internal/host/refresh_status_preprocessor_test.go
internal/host/validator.go
internal/oc/mock_release.go
internal/oc/release.go
models/install_cmd_request.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/install_cmd_request.go

In order to allow for new CAPI install methods this PR enables the installer to write to a new stateroot on the existing root filesystem as opposed to installing to an entire device using `coreos-installer`.
This PR creates an environment variable (`INSTALL_TO_EXISTING_ROOT`) which when set will fetch the coreos image content from the selected release and provide it to the installer. This (along with the changes in https://github.com/openshift/assisted-installer/pull/1003) will trigger the installer to write the image to a new stateroot on the existing disk rather than installing to a target device.
This functionality is disabled by default and should only be used when the host is not running in the live-iso environment.
In order to enable (and succeed when using) the new install flow the …

MGMT-19100: Allow install to the existing root filesystem

---

internal/metrics/disk_stats_helper.go
internal/metrics/os_disk_stats_helper_test.go

When we measure the disk usage for metrics, we need to ensure that hard links are accounted for as these may lead to an inaccurate count. This PR modifies the gathering of filesizes slightly to perform a stat on each file and take into account the unique inode number.
Hard links and actual files share the same inode number as this is a reference to the underlying data.

NO-ISSUE: Ensure that hard links are accounted for when measuring disk usage

---

cmd/main.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/mock_installer_internal.go
internal/cluster/validations/mock_pull_secret_validation.go
internal/cluster/validations/pull_secret_validation.go
internal/cluster/validations/validation_test.go
internal/cluster/validations/validations.go
internal/controller/controllers/clusterdeployments_controller_test.go
internal/controller/controllers/infraenv_controller_test.go
internal/controller/controllers/pullsecret_handler.go

When a mirror registry configuration is provided to assisted, we will assume that the registry does not require authentication. This is a better user experience so that the user will not have to provide credentials for a registry if a mirror registry will be used in its place.
I've broken up the commits so that the first commit is for mirror configuration in assisted (globally) and the following commits are for mirror configurations per cluster. …

MGMT-19708: Ignore mirrored registries when validating pull secrets

---

api/v1beta1/agent_types.go
api/vendor/github.com/openshift/assisted-service/models/boot.go
client/vendor/github.com/openshift/assisted-service/models/boot.go
config/crd/bases/agent-install.openshift.io_agents.yaml
config/crd/resources.yaml
deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
internal/controller/controllers/agent_controller.go
models/boot.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/api/v1beta1/agent_types.go
vendor/github.com/openshift/assisted-service/models/boot.go

This PR creates an API in the agent inventory and in the agent CR for storing the boot device type. The options for this type are ephemeral when an ISO or ipxe is being used for discovery, or persistent when discovery is being done from the same device we're installing to.
In a follow up PR (after the agent changes are merged to populate this field) this field will be used to determine if install should target the existing root filesystem or a separate device.
Deployed assisted manually and installed a cluster to a host using the existing root filesystem and also using the ISO from the same assisted deployment. This test included the changes from https://github.com/openshift/assisted-service/pull/7220 as well as the agent changes to populate the new inventory field. …

MGMT-19102: Add boot device type

---

cmd/main.go
internal/cluster/validations/pull_secret_validation.go
internal/cluster/validations/validation_test.go
internal/cluster/validations/validations.go

Partial backport of https://github.com/openshift/assisted-service/pull/7193
Only the [first commit](https://github.com/openshift/assisted-service/pull/7193/commits/599df3eae02100b636ce8fbf4087d791607a8eef) is backported as the rest of the commits involve a new feature ([MGMT-18013](https://issues.redhat.com/browse/MGMT-18013)) for ACM 2.13 and are not relevant for this release 
---
When a mirror registry configuration is provided to assisted, we will assume that the registry does not require authentication. This will take any mirror registry that assisted is configured with and will add it to the public registries list in the pull secret validator. That way, any pull secret being validated will not be required to have authentication credentials for the registry since it's pulling from the …

[release-ocm-2.12] MGMT-19708: Add assisted mirror registries to public registries list

---

internal/host/conditions.go
internal/host/conditions_test.go
internal/host/config.go
internal/host/host.go
internal/host/hostcommands/disk_performance_cmd.go
internal/host/hostcommands/disk_performance_cmd_test.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/hostcommands/instruction_manager.go
internal/host/refresh_status_preprocessor.go
internal/host/refresh_status_preprocessor_test.go
internal/host/validator.go

When the boot device is persistent the install will write to that device, when the boot device is ephemeral (iso, ipxe, etc), the install will write to a separate disk.
The replaces the environment variable (`INSTALL_TO_EXISTING_ROOT`) which was added to originally expose this behavior.
https://issues.redhat.com/browse/MGMT-19102
Manually tested that an assisted service deployment with this code would install correctly based on how discovery was started.

MGMT-19102: Use inventory to determine if install is on the existing root

---

cmd/main.go
internal/cluster/validations/validation_test.go
internal/cluster/validations/validations.go

Manual and partial backport cherry-pick of https://github.com/openshift/assisted-service/pull/7193
Modified version of the [first commit](https://github.com/openshift/assisted-service/pull/7193/commits/599df3eae02100b636ce8fbf4087d791607a8eef) is backported as the rest of the commits involve a new feature ([MGMT-18013](https://issues.redhat.com/browse/MGMT-18013)) for ACM 2.13 and are not relevant for this release. Also the modification is due to the fact that the pull secret validation was different at the time of this release.
---
When a mirror registry configuration is provided to assisted, we will assume that the registry does not require authentication. This will take any mirror registry that assisted is configured with and will add it to the public registries list in the pull secret …

[release-ocm-2.10] MGMT-19708: Add assisted mirror registries to public registries list

---

cmd/main.go
internal/cluster/validations/pull_secret_validation.go
internal/cluster/validations/validation_test.go
internal/cluster/validations/validations.go

Partial backport of https://github.com/openshift/assisted-service/pull/7193
Only the [first commit](https://github.com/openshift/assisted-service/pull/7193/commits/599df3eae02100b636ce8fbf4087d791607a8eef) is backported as the rest of the commits involve a new feature ([MGMT-18013](https://issues.redhat.com/browse/MGMT-18013)) for ACM 2.13 and are not relevant for this release 
---
When a mirror registry configuration is provided to assisted, we will assume that the registry does not require authentication. This will take any mirror registry that assisted is configured with and will add it to the public registries list in the pull secret validator. That way, any pull secret being validated will not be required to have authentication credentials for the registry since it's pulling from the …

[release-ocm-2.11] MGMT-19834: Add assisted mirror registries to public registries list

---

Dockerfile.assisted-service

MGMT-19819: Add the commit reference from which the image is built to the image

---

api/v1beta1/infraenv_types.go
config/crd/bases/agent-install.openshift.io_infraenvs.yaml
config/crd/resources.yaml
deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
internal/controller/controllers/infraenv_controller.go
internal/controller/controllers/infraenv_controller_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go

This will mainly be used with integrations that provide the discovery ignition as metadata to hosts that boot with a generic disk image rather than the discovery ISO, but can also be used for debugging.
Resolves https://issues.redhat.com/browse/MGMT-19792
Deployed assisted service with this change, created an infraenv, downloaded and checked the discovery ignition using the URL in new API

MGMT-19792: Add discovery ignition URL to the infraenv status

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/ignition/ignition.go

Users have seen some situations where they are unable to download the
discovery ISO because the ignition doesn't generate correctly on the
service side.
The only explanation seems to be that there is a malformed override and
the only override we're adding in all of these cases is the internal one
which also happens to not be validated.
Relates to https://issues.redhat.com/browse/MGMT-19844

MGMT-19844: Validate the internal ignition override

---

internal/network/manifests_generator.go

network.target doesn't garantee that interfaces are configured
(https://systemd.io/NETWORK_ONLINE/), so we may have cases were dnsmasq
fails to start because `resolv.conf` is not there yet.
This fix will start dnsmasq after `ovs-configuration` service so we are
sure that the network is configured at this point.

OCPBUGS-47627: dnsmasq service on OCP SNO fails to read /etc/resolv.conf file during system startup

---

client/operators/v2_list_bundles_responses.go
docs/enhancements/operator-marketplace.md
internal/operators/manager.go
internal/operators/manager_test.go
internal/operators/mock_operators_api.go
restapi/embedded_spec.go
restapi/operations/operators/v2_list_bundles_responses.go
swagger.yaml
vendor/github.com/openshift/assisted-service/client/operators/v2_list_bundles_responses.go

This is a followup PR following a review comment https://github.com/openshift/assisted-service/pull/7170#discussion_r1922569273

MGMT-19599: Update get bundles endpoint to return a list of bundles instead of list of bundles names

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

Manual cherry-pick of https://github.com/openshift/assisted-service/pull/7026
#
For completeness, if a host has begun installing, store the current stage in the Agent's annotations so that if a host needs to be restored, we'll also have that data.

MGMT-19193: Add current stage when restoring host by Agent (#7026)

---

internal/hardware/validator.go
internal/hardware/validator_test.go
internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go
internal/host/hostutil/host_utils.go
internal/host/hostutil/host_utils_test.go
internal/host/validations_test.go
internal/host/validator.go
internal/network/manifests_generator.go
internal/network/manifests_generator_test.go

Building on the work done to enable iSCSI as an installation disk, this PR extends support to enable multipath+iSCSI as an installation disk.
Details about the testing setup are here - https://github.com/openshift/assisted-service/blob/master/docs/dev/multipath-iscsi.md

MGMT-19670, MGMT-19484: Enable multipath + iSCSI as installation disk

---

internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go

This PR ensures that GET /v2/clusters/{cluster_id}/install-config correctly handles Day2 clusters. Since install-config is not required for Day2, the request now returns a 400 Bad Request instead of a 500 Internal Server Error.
/cc @gamli75 @eliorerz

MGMT-19490: Day 2 clusters /install-config endpoint is broken

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/ignition/ignition.go

Manual cherry-pick of https://github.com/openshift/assisted-service/pull/7254 to release-ocm-2.12

[ACM 2.12] MGMT-19855: validate internal ignition

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/ignition/ignition.go

Manual cherry-pick of https://github.com/openshift/assisted-service/pull/7254 to release-ocm-2.11

[ACM 2.11] MGMT-19856: MGMT-19844: Validate the internal ignition override (#7254)

---

internal/controller/controllers/agent_controller.go

This code was added to handle OCPBUGS-7581, and it was meant to be removed after it was resolved. Its fix has long merged and was backported till OCP 4.12; therefore this code can now be removed.
Removing the BMH finalizer causes the BMH to instantly be deleted, which means that BMO is unable to do any necessary cleanup. In OCPBUGS-25927, BMO encounters an error while attempting to update the status of an already deleted BMH:
2024-11-13T07:28:35.215792213Z {"level":"info","ts":1731482915.2157853,"logger":"controllers.BareMetalHost","msg":"saving host status","baremetalhost":{"name":"gateway-1.workload.fc18.lab","namespace":"openshift-machine-api"},"provisioningState":"unmanaged","operational status":"discovered","provisioning state":"deleting"}
2024-11-13T07:28:35.220351574Z …

MGMT-14495: Stop removing the finalizers from BMH

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
subsystem/day2_cluster_test.go

This is a backport of OCPBUGS-42059 and #7249  for ACM 2.12.
Currently when a cluster is imported the `openshift_version` column of the database is not populated. As a result that version will not be available for validations, in particular for the validation that checks if dual-stack VIPs are supported. A side effect of that is that adding a node to a cluster with dual-stack VIPs will always fail with an error message like this, regardless of the version:
```
"dual-stack VIPs are not supported in OpenShift "
```
That error happens because we are trying to see if the version is less than 4.12, but the result is always true because the version is empty.
To avoid that this patch changes the cluster import code so that it populates the `openshift_version` database column. …

ACM-17553: Save version of imported clusters - ACM 2.12

---

cmd/agentbasedinstaller/client/main.go
cmd/agentbasedinstaller/register.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
subsystem/agent_based_installer_client_test.go

Add the ability for the agent-based installer to pass in a file containing a list of operators to be installed. The operators will be added to the cluster create params and adding when registering the cluster.

AGENT-1074: Add support for ABI to install OLM operators

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
subsystem/day2_cluster_test.go

Currently when a cluster is imported the `openshift_version` column of the database is not populated. As a result that version will not be available for validations, in particular for the validation that checks if dual-stack VIPs are supported. A side effect of that is that adding a node to a cluster with dual-stack VIPs will always fail with an error message like this, regardless of the version:
```
"dual-stack VIPs are not supported in OpenShift "
```
That error happens because we are trying to see if the version is less than 4.12, but the result is always true because the version is empty.
To avoid that this patch changes the cluster import code so that it populates the `openshift_version` database column.
https://issues.redhat.com/browse/OCPBUGS-42059
- Are the title and description …

OCPBUGS-42059: Save version of imported clusters

---

docs/user-guide/mirror_registry_guide.md

This PR adds documentation for using the new mirror registry feature in Assisted Service. The documentation provides detailed steps on how to initialize and configure a mirror registry, apply updated CRDs, and leverage per-cluster mirror registry configurations. It also explains how to mirror OpenShift release images and Assisted Installer images, ensuring proper cluster deployment in disconnected or restricted network environments.
- The new documentation file `mirror_registry_setup.md` is located under `docs/user-guide/`.
- The guide explains how to configure per-cluster mirror registries using different registry names and ports, providing flexibility in multi-cluster environments.
- It includes steps for secure and insecure registry setups (with insecure mode currently being a work in …

MGMT-19847: Add Documentation for Mirror Registry Feature

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
subsystem/day2_cluster_test.go

This is a backport of OCPBUGS-42059 and #7249 for ACM 2.10.
Currently when a cluster is imported the `openshift_version` column of the database is not populated. As a result that version will not be available for validations, in particular for the validation that checks if dual-stack VIPs are supported. A side effect of that is that adding a node to a cluster with dual-stack VIPs will always fail with an error message like this, regardless of the version:
```
"dual-stack VIPs are not supported in OpenShift "
```
That error happens because we are trying to see if the version is less than 4.12, but the result is always true because the version is empty.
To avoid that this patch changes the cluster import code so that it populates the `openshift_version` database column. …

ACM-17555: Save version of imported clusters - ACM 2.10

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

Manual cherry pick of PRs:
https://github.com/openshift/assisted-service/pull/7026 [MGMT-19193](https://issues.redhat.com//browse/MGMT-19193): Add current stage when restoring host by Agent
https://github.com/openshift/assisted-service/pull/7064 [MGMT-19413](https://issues.redhat.com//browse/MGMT-19413): Add validations info to the Agents annotations
https://github.com/openshift/assisted-service/pull/7063 [MGMT-19414](https://issues.redhat.com//browse/MGMT-19414): Add default requeue time when Hosts are created from Agents
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/gu …

[release-ocm-2.11] MGMT-19193: Add current stage when restoring host by Agent

---

internal/operators/openshiftai/openshift_ai_config.go
internal/operators/openshiftai/openshift_ai_operator.go
internal/operators/openshiftai/openshift_ai_operator_test.go

With the introduction of operator bundles it is no longer necessary to add dependencies to the OpenShift AI operator because those will be part of the bundle.
https://issues.redhat.com/browse/MGMT-19860:

MGMT-19860: Remove dependencies from OpenShift AI operator

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

The intention in the agent controller was to only remove the spoke resources when the entire cluster was not being removed. This was previously done my check the cluster deployment, but the agent cluster install is what actually triggers the agent removal. This means that we really should be checking both resources to avoid a race when everything is removed at the same time.
Before this change it was possible for a node or two to be removed before the deletion timestamp was set on the cluster deployment. Now this will no longer happen as one of the resources will need to be marked as deleted before any agent gets removed.
Resolves https://issues.redhat.com/browse/ACM-17767
Manually tested by deploying a 6-node cluster. Before the change one of the nodes would be removed when deleting all …

ACM-17767: Don't remove spoke resources when cluster is being deleted

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

The intention in the agent controller was to only remove the spoke resources when the entire cluster was not being removed. This was previously done my check the cluster deployment, but the agent cluster install is what actually triggers the agent removal. This means that we really should be checking both resources to avoid a race when everything is removed at the same time.
Before this change it was possible for a node or two to be removed before the deletion timestamp was set on the cluster deployment. Now this will no longer happen as one of the resources will need to be marked as deleted before any agent gets removed.
Resolves https://issues.redhat.com/browse/ACM-17877
Manual cherry-pick of https://github.com/openshift/assisted-service/pull/7303
- Are the title and description (in …

[ACM 2.12] ACM-17877: Don't remove spoke resources when cluster is being deleted

---

internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

The intention in the agent controller was to only remove the spoke resources when the entire cluster was not being removed. This was previously done my check the cluster deployment, but the agent cluster install is what actually triggers the agent removal. This means that we really should be checking both resources to avoid a race when everything is removed at the same time.
Before this change it was possible for a node or two to be removed before the deletion timestamp was set on the cluster deployment. Now this will no longer happen as one of the resources will need to be marked as deleted before any agent gets removed.
Resolves https://issues.redhat.com/browse/ACM-17953
Manual cherry-pick of https://github.com/openshift/assisted-service/pull/7303
- Are the title and description (in …

[release-ocm-2.11] ACM-17953: Don't remove spoke resources when cluster is being deleted

---

Dockerfile.assisted-service

[release-ocm-2.10] MGMT-19819: Add the commit reference from which the image is built to the image

---

Dockerfile.assisted-service

[release-ocm-2.11] MGMT-19819: Add the commit reference from which the image is built to the image

---

internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/host/monitor.go
internal/host/monitor_test.go
internal/metrics/metricsManager.go
internal/metrics/mock_metrics_manager_api.go

This PR updates the monitoring metrics, which were previously reported as gauge, to use histograms.
Instead of simply counting the number of monitored hosts and clusters, the new histograms will track the duration of each monitoring operation, allowing us to retain valuable timing data and improve performance insights.
Previously, using gauge led to misleading metrics—since the host monitoring loop runs every few seconds but Prometheus scrapes at different intervals, a significant number of monitored hosts could be lost, leading to inaccurate analysis. The same issue applied to monitored clusters.
By switching to histograms, we can now accurately measure how long each monitoring process takes and identify potential performance bottlenecks. …

MGMT-19887: Add Histogram Metric for Host Monitoring Time

---

internal/isoeditor/rhcos.go
internal/isoeditor/rhcos_test.go

This PR is to solve an issue where discovering nodes with minimal iso and authenticated proxy with special characters will fail, same as #6356, need to escape '%' with '%%' in order to properly pass the Environment variables to coreos-livepxe-rootfs service in order to properly boot the node with minimal iso

MGMT-19622: Proxy setting with special characters are ignored when minimal ISO is used

---

cmd/main.go
internal/ignition/installmanifests_test.go
internal/installercache/installercache.go
internal/installercache/installercache_test.go
internal/metrics/metricsManager.go
internal/metrics/mock_metrics_manager_api.go

We implement the following metrics:
Record cache hits and misses
The purpose of this metric is to measure efficiency of the cache. This metric should be a counter. The total sum should be the equivalent to the sum of hits+misses (each request served). Errors should be logged instead.
assisted_installer_release_cache{hit=(true|false),release="\d.\d"} 
Labels
hit: hit should either be true or false
release: release is major and minor openshift version, so that cardinality is contained. if we can't retrive major/minor, we label it as `unknown`
Record cache evictions
This metric is a counter. The purpose of this metric is to count the number of eviction attempts. For each eviction attempt we should just count one with success=true label if the operation evicted at least one file, false if …

MGMT-19840: Gather operational metrics from installercache

---

restapi/embedded_spec.go
swagger.yaml

[MGMT-20099](https://issues.redhat.com//browse/MGMT-20099): add nmstate to /v2/supported-operators
nmstate was missing from the list of supported operators

MGMT-20099: add nmstate to /v2/supported-operators

---

internal/host/validator.go

This PR fixes a bug introduced in the previous PR ([#7384](https://github.com/openshift/assisted-service/pull/7357)), where the validation success return was placed too early. As a result, there's a chance that a failure report appears after a success report, causing failed reports to be missed.

NO-ISSUE: Fix bug in MTU validation for CMN - validation should pass if all reports are checked

---

internal/featuresupport/feature_support_test.go
internal/featuresupport/features_networking.go
internal/featuresupport/features_platforms.go
internal/provider/baremetal/installConfig.go
internal/provider/vsphere/installConfig.go
internal/provider/vsphere/installConfig_test.go

This PR adds support for installations with user-managed LB on `vSphere` platform. As most of the logic already added in previous PRs while enabling for `baremetal` platform, this PR only adds the required data to the `install-config.yaml` file. A dedicated e2e job was added to test this flow - `edge-e2e-vsphere-assisted-umlb-4-18`

MGMT-19830: Enable installation of OCP clusters in vSphere environments with user-managed LB

---

ci-images/Dockerfile.base
ci-images/Dockerfile.subsystem
hack/setup_env.sh

building of `ci-images/subsystem` fails:
```
Installing collected packages: waiting, vcversioner, zipp, wheel, urllib3, tqdm, setuptools, rfc3986, pyyaml, pyparsing, Pygments, pycparser, py, pkginfo, nh3, more-itertools, MarkupSafe, jeepney, idna, docutils, decorator, colorama, charset-normalizer, certifi, backports.tarfile, retry, requests, readme-renderer, packaging, jinja2, jaraco.functools, jaraco.context, jaraco.classes, importlib-metadata, cffi, requests-toolbelt, cryptography, SecretStorage, keyring, twine
Attempting uninstall: setuptools
Found existing installation: setuptools 53.0.0
error: uninstall-no-record-file
```
Due to conflict with existing `python3-setuptools` package in different version. This PR activates the `virtualenv` to solve this issue  …

NO-ISSUE: Fix setuptools issue

---

internal/featuresupport/features_olm_operators.go
internal/featuresupport/features_platforms.go

Closes [MGMT-19903](https://issues.redhat.com/browse/MGMT-19903)
This PR updates the Assisted Installer service to disable **OpenShift AI** and **OpenShift Data Foundation** operators when integrating with **OCI (Oracle Cloud Infrastructure)**.  
Previously, these operators were **available** for Oracle, but this change ensures they are now **disabled** when OCI is selected as the platform.
[CONTRIBUTING]: https://github.com/openshift/assisted-service/blob/master/CONTRIBUTING.m …

MGMT-19903: Disable ODF and OpenShift AI Operators for Oracle (OCI)

---

hack/agent_installer/start_db.sh

OKD installations are failing when using agent and assisted service as described here: https://github.com/okd-project/okd/discussions/2068#discussioncomment-11733877 with:
```
FATAL:  could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock": No such file or directory"
```
Explicitly tell postgres to use /tmp as the unix socket directory to fix the issue.

NO-JIRA: OKD: Use /tmp as socket directory when calling pg_ctl and postgres

---

internal/operators/nmstate/config.go
internal/operators/nmstate/operator.go
internal/operators/nmstate/operator_test.go
subsystem/cluster_test.go

[MGMT-20216](https://issues.redhat.com//browse/MGMT-20216): Remove memory and CPU requirements
The assisted installer should not make any assumptions regarding the operator resource requirements unless those are specifically stated in official documentation. Nmstate operator has no such requirements.

MGMT-20216: Remove memory and CPU requirements

---

api/hiveextension/v1beta1/agentclusterinstall_types.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go

Defines the label `"agentclusterinstalls.agent-install.openshift.io/consumer"` in the `AgentClusterInstall` that can be set by the CAPI OpenshiftAssisted providers to indicate the cluster is used by these providers. 
The value of the label is added to the `tags` field of the cluster, which is sent with the cluster data during on-prem data collection
/cc @rccrdpccl

MGMT-18437: Consumer label on AgentClusterInstall to identify clusters used by CAPI providers

---

deploy/operator/capi/deploy_capi_cluster.sh

Starting from ACM 2.13/MCE 2.8, Hypershift
blocks and prevents installation of hosts to a hosted cluster if the catalog sources are unreachable,
which will always happen in the disconnected case unless the catalog is mirrored.
To resolve this, the OLM catalog will now be disabled during the hosted cluster creation and the OLM catalog is now set to guest mode.
---
Note: this will need to be backported to ACM 2.13 branch …

MGMT-20134: Disable OLM Catalog for CAPI CI tests

---

internal/operators/nodemaintenance/node_maintenance_consts.go

Fix ignition creation conflict between `node-maintenance` operator and `node-healthcheck` operator by changing `node-maintenance` namespace
```
Mar 31 13:13:04 master-0 service[2580]: time="2025-03-31T13:13:04Z" level=error msg="error running openshift-install create ignition-configs, stdout: level=info msg=Consuming Certificate (admin-kubeconfig-signer) from target directory\nlevel=info msg=Consuming Certificate (kube-apiserver-localhost-signer) from target directory\nlevel=info msg=Consuming Certificate (kube-apiserver-service-network-signer) from target directory\nlevel=info msg=Consuming Certificate (kube-apiserver-lb-signer) from target directory\nlevel=fatal msg=failed to fetch Bootstrap Ignition Config: failed to fetch dependency of \"Bootstrap Ignition Config\": failed to generate …
```

NO-ISSUE: Change node-maintenance operator namespace to avoid conflict with node-healthcheck operator

---

internal/ignition/installmanifests.go
internal/ignition/installmanifests_test.go

Previously we were assuming that deployment 1 would be the discovery deployment, but that's not the case if we need to do multiple to handle kernel args.
Use the built-in `rpm-ostree cleanup` commands to remove unused deployments instead.
Related to https://issues.redhat.com/browse/MGMT-20153
Manually deployed along with https://github.com/openshift/assisted-installer/pull/1076 and installed several clusters. …

MGMT-20153: Improve ostree cleanup service

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/validations/validations.go
pkg/ocm/utils.go

This PR removes code related to platform_oci and platform_external capabilities that are now enabled globally as specified in [MGMT-20181](https://issues.redhat.com//browse/MGMT-20181).
Changes:
- Removed PlatformOciCapabilityName and PlatformExternalCapabilityName constants
- Removed ValidatePlatformCapability function as it was using these removed constants
- Removed function calls to ValidatePlatformCapability
- Updated tests to remove references to the removed capabilities …

MGMT-20181: cleanup platform_oci and platform_external capabilities

---

internal/bminventory/inventory.go
internal/cluster/cluster.go
internal/common/error_utils.go
internal/constants/files.go
pkg/generator/generator.go

In https://github.com/openshift/assisted-service/pull/7391 changes were made to allow the kubeconfig to be retrieved in the Ready state for ABI only, in order to be integrate with the OVE UI. This change should also be made for kubeadmin-password, to allow it be retrieved prior to installing the cluster.
Some related changes address additional comments in the PR above.
- [] Bug fix

AGENT-538: For ABI, also allow early retrieval of kubeadmin-password

---

internal/common/common.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/common.go
pkg/mirrorregistries/generator.go
pkg/mirrorregistries/mirror_registry_test.go

When generating the install config, it should not include the entire system CA bundle. I.e. when setting the AdditionalTrustBundle[1]. However, when using a mirror regsitry (e.g. with MirrorRegistryRef[2] in ASC), the installConfigBuilder is adding the content of tls-ca-bundle.pem[3]. This pem file is created[4] by ASC controller, and includes the full system CA bundle since the bundle[5] is injected into 'cluster-trusted-ca-bundle'.
Therefore, the suggestion solution is to create a separate pem file just for the certificates specified in MirrorRegistryRef. I.e. generate a new 'user-registry-ca-bundle.pem' file, that will be included as part of AdditionalTrustBundle. These certificates will propagate into the 'user-ca-bundle' CM during cluster installation.
This will ensure that …

MGMT-20207: avoid adding system CA bundle to AdditionalTrustBundle

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

coreos-installer automatically generates the root=UUID kernel argument, which makes adding a root karg via assisted-service unnecessary. Additionally, it's been found that using root with a by-label value works fine when there's only a single multipath device. However, with multiple multipath devices, it can lead to issues — since the initramfs will scan all available devices for a filesystem with the matching label, potentially causing a race condition.
**Note**: Currently, I’ve kept the appending of the root karg for multipath setups that are not iSCSI. Once we confirm it’s unnecessary for other types, it can be safely removed.
**Explain how it was tested:**
1. Using test-infra, I created a 3-master cluster, each node configured with a multipath iSCSI installation disk. During …

MGMT-20302: Remove root=/dev/disk/by-label/dm-mpath-root from kargs added when installation disk is multipath iSCSI

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

Intel VROC supports raid creation from BIOS and creates raid devices on booted os.
When raid is installation disk, reboot fails because device not detectd. Enable kernel args - rd.md=1 and rd.auto=1

MGMT-20245: Add kernel args for raid (Intel VROC)

---

internal/common/common.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/common.go
pkg/mirrorregistries/generator.go
pkg/mirrorregistries/generator_test.go

This is a cherry-pick of https://github.com/openshift/assisted-service/pull/7448

[release-ocm-2.12] MGMT-20207: avoid adding system CA bundle to AdditionalTrustBundle

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/github.com/golang-jwt/jwt/v4/token.go
vendor/modules.txt

[release-4.13]  OCPBUGS-53693: Bump go-jwt to 4.5.2 to fixCVE-30204

---

internal/featuresupport/common.go
internal/featuresupport/feature_support_test.go

Disable feature validation when creating and updating assisted objects due to an error when user is trying to add hosts on day2 with P/Z arch
/cc @gamli75

MGMT-20324:  Fix day2 add hosts with P/Z CPU architectures

---

renovate.json

Add renovate configuration to update linter and golang
* golangci-lint should be updated as soon as possible to avoid blocking golang update.
* PR should happen as soon as there is a new release
* major updates are disabled, golangci-lint 2.0.x is already out
* golang version can be updated once the linter has been updated.
* Since we are using a variable in Dockerfile.assisted-service, I assume that ubi8/go-toolset and ubi9/go-toolset will have the same tag, so I used ubi9/go-toolset to update that from (this is why there is a custom manager).
* PR should happen as soon as there is a new release
* major updates are disable because of the tagging mechanism of that image (9.4 is a tag, it makes renovate think it's a golang version)
* Konflux should be unchanged.
* PR should still happen …

MGMT-18518: Renovate configuration tu update golang and golangci-lint

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

We are disabling `skip MCO reboot` for day2 hosts because it doesn't work, and enabled by default. It results in a 20 min delay in the installations. We have a open issue to fix it. 

MGMT-20339: Disable skip mco reboot for day2 hosts

---

ci-images/Dockerfile.base
ci-images/Dockerfile.subsystem

Cherry-picking https://github.com/openshift/assisted-service/pull/7442/commits/e90b02b19ba986a99f1c42dad1663630fd4a012f that was lost with the last cloud-hotfix-releases reset

NO-ISSUE: ci: Use virtualenv to avoid conflict with setuptools

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

This PR follows up on - https://github.com/openshift/assisted-service/pull/7507
Based on testing by @AmadeusPodvratnik  with multipath + FC, appending the root kernel argument via Assisted is not necessary. For FC under multipath, the root=UUID is automatically added by CoreOS, and the installation completes successfully. 

NO-ISSUE: Remove root=/dev/disk/by-label/dm-mpath-root from kargs added when installation disk is multipath 

---

internal/featuresupport/feature_support_config.go
internal/featuresupport/features_olm_operators.go
internal/featuresupport/features_olm_operators_test.go
openshift/template.yaml

The AMD GPU operator was available in version 4.17 of OpenShift in the certified operators catalog, but it isn't yet in that same catalog for 4.18. As a result when the operator is enabled for 4.18 the installation will start but will never finish correctly because the operator will never be installed. To avoid that this patch adds a new environment variable to control for what versions of OpenShift the operator will be enabled. For example, to explicitly enable both 4.17 and 4.18:
```shell
AMD_GPU_SUPPORTED_OPENSHIF_VERSION="4.17,4.18"
```
The default value for the variable is `*`, which means that the operator is enabled for all versions of OpenShift.
The variable is set to `4.17` in the deployment template, so that in the production environment the operator will only be enabled for …

MGMT-20384: Feature flag for AMD GPU supported OCP versions

---

pkg/generator/generator.go

If the work directory exists the InstallConfig will be skipped to avoid regenerating the kubeadmin-password. This should only be checked for the agent-based installer.
- [] None

MGMT-20375: Skip installconfig generation only for agent-based installer

---

internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go

As part of https://github.com/openshift/assisted-service/pull/7448, a new 'mirror-registry-ca-bundle' volume has been added when MirrorRegistryRef is specified in AgentServiceConfig.
However, the Volume (and VolumeMount) should be added only if the ca-bundle.crt key exists in the mirror registry CM (since the key is optional).
This should prevent an error when starting the service pod when providing a mirror registry CM without the key:
```
MountVolume.SetUp failed for volume "mirror-registry-ca-bundle" : configmap references non-existent config key: ca-bundle.crt
``` …

MGMT-20413: support missing ca-bundle.crt in mirror registry ConfigMap

---

docs/enhancements/arbiter-clusters.md

Enhancement to define the implementation of installing TNA clusters.
See [openshift's enhancement](https://github.com/openshift/enhancements/blob/master/enhancements/arbiter-clusters.md) for more details about TNA clusters.

MGMT-19980: TNA clusters

---

internal/operators/nvidiagpu/nvidia_gpu_operator.go
internal/operators/nvidiagpu/nvidia_gpu_operator_test.go

Currently we don't add any dependencies for operators that are parts of bundles, in particular for the NVIDIA GPU operator we don't automatically add the node feature discovery operator. But some users wish to have the dependency because they are not interested in bundle, just in the GPU operator. This patch adds that dependency.
https://issues.redhat.com/browse/MGMT-20455
Tested with the included unit test. …

MGMT-20455: Add NFD as dependency of NVIDIA GPU

---

internal/host/validations_test.go
internal/host/validator.go

The vSphere installation was failing due to a false validation error stating that disk.EnableUUID was not enabled, despite it being correctly configured in the VM settings. 
For example, there are two types of disks:
- Installable disk (HDD or other types): A disk eligible for installation with a valid UUID (HasUUID:true). This disk should be validated and mounted correctly.
- Non-installable disk (e.g., ISO, small SSD): A disk not eligible for installation (InstallationEligibility.Eligible:false), often used for media or other purposes, and may not have a UUID. This disk should be ignored in the validation process.
The issue occurred because the validation logic was incorrectly checking both types of disks for UUIDs. The fix ensures that only installable disks are validated for HasUUID, …

OCPBUGS-52285: ABI vSphere Installation Fails Due to disk.EnableUUID 

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/README.md
vendor/github.com/golang-jwt/jwt/v4/claims.go
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/github.com/golang-jwt/jwt/v4/token.go
vendor/modules.txt

[release-4.12] OCPBUGS-53692: Bump go-jwt to 4.5.2 to fix-CVE-30204

---

pkg/staticnetworkconfig/generator.go
pkg/staticnetworkconfig/generator_test.go

This commit changes the logging behavior in the StaticNetworkConfigGenerator to reduce log verbosity by consolidating multiple individual "Adding NMConnection file" log messages into a single message. Instead of logging each NM connection file separately, the code now collects all file names and outputs them in a single log entry.

MGMT-18930: Consolidate static network configuration log messages

---

api/vendor/github.com/openshift/assisted-service/models/monitored_operator.go
client/vendor/github.com/openshift/assisted-service/models/monitored_operator.go
models/monitored_operator.go
restapi/embedded_spec.go
swagger.yaml
vendor/github.com/openshift/assisted-service/models/monitored_operator.go

This property should be reserved for operator that can not be installed as standalone operator.
This change is a prerequisite to be able to remove nvidia-gpu, amd-gpu or kmm operator if, after choosing openshiftai, we found that no host has amd/nvidia gpu.
Alongside with the initiative to have a single openshiftAI bundle, we need to be able to add dependent operators (namely nvidia-gpu or amd-gpu) based on the host discovery result
Which also imply to be able to remove those dependency-operator if they are not needed (in the first palce or if the only host with nvidia GPU has been removed for example)
This PR proposes to add a new property on Operator that describes if the operator can only exist as a dependency of another operator. So that another PR can remove those operator if they are …

MGMT-20124: Introduce DependencyOnly property on Operator

---

cmd/main.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/progress_test.go
internal/cluster/refresh_status_preprocessor.go
internal/cluster/refresh_status_preprocessor_test.go
internal/cluster/transition_test.go
internal/operators/common/common.go
internal/operators/manager.go
internal/operators/odf/validation_test.go
vendor/github.com/dustin/go-humanize/english/words.go
vendor/modules.txt

Reopening https://github.com/openshift/assisted-service/pull/7227 
cc @jhernand 
Also adding 
* Write DB changes in one transaction
* Add call to EnsureOperatorPrerequisite after the operator list is updated
At first I added some logic to
* Reset auto-assign roles if anything changed
but I removed it since it's already done in the HostStateMonitor
Was tested locally with others changes to have a single openshift AI bundle that add/remove nvidia or amd operator based on the host inventory during the discovery
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-reques …

MGMT-20233: Recompute operator dependencies after discovering the hosts

---

internal/bminventory/inventory.go
internal/host/transition.go
internal/host/transition_test.go

Currently, when an installed host boots from the ISO, it triggers the PostRegisterAfterInstallation method. The error returned from this method is of type Error with a status code of 403 Forbidden.
However, on the client side, the response reader expects a 403 to be of type InfraError, which leads to an unmarshaling failure and a non-informative error message.
To resolve this, the returned status code was changed to 409 Conflict, which is both semantically accurate and correctly maps to the Error type on the client side — fixing the decoding issue.
the non-informative error before the fix:
`json: cannot unmarshal string into Go struct field InfraError.code of type int32`
Note that this change also requires an update in the agent repository — see: [assisted-installer-agent …

MGMT-20296: Fix returned error code in PostRegisterAfterInstallation

---

internal/oc/release.go
internal/oc/release_test.go

OKD doesn't use rhel-coreos, it uses stream-coreos instead

MGMT-20369: retrieve stream-coreos image instead of rhel-coreos when installing OKD

---

pkg/generator/generator.go

When OVE UI uses the downloads/credentials endpoint the API handler generates the InstallConfig for the agent-based installer in order to make the credentials available in the Ready state. In order to prevent overwriting the kubeadmin-password, the generation of the InstallConfig the second time was bypassed (https://github.com/openshift/assisted-service/pull/7546). This inadvertently prevented the operator manifests from also being generated, and since the OVE UI configures the operators after it retrieves the credentials, the operators are not correctly installed.
This fix removes the bypass of the GenerateInstallConfig. To prevent the kubeadmin-password overwrite a installer change has been made https://github.com/openshift/installer/pull/9679 …

OCPBUGS-55300: For agent-installer remove bypass of manifest generation

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

The agent validates no_proxy using the `ValidateNoProxyFormat` function which was recently changed to ensure no duplicates exist.
If a user adds one of the entries that the install command is trying to add automatically, this caused duplicates and the install command failed verification.
Resolves https://issues.redhat.com/browse/MGMT-20527
Unit tests and @trewest is testing manually in the environment where the bug was found.

MGMT-20527: Ensure no_proxy contains no duplicates in the install command

---

internal/ignition/templates/oci-eval-user-data.sh

Mirror changes to [oci-eval-user-data.sh](https://github.com/openshift/installer/blob/main/data/data/agent/files/usr/local/bin/oci-eval-user-data.sh) in the installer
- [] Operator Managed Deployments
The fix was run locally with an assisted setup.
- NA on unit-tests due to being a shellscript
- Are the title and description (in both PR and commit) meaningful and clear? yes
- Is there a bug required (and linked) for this change? yes
- Should this PR be backported? yes to 4.18

OCPBUGS-54319: mirror changes to openshift-installer with oci-eval-user-data

---

internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go

fix ironic inspection bug when ironic image override annotation is provided in disconnected environments
https://issues.redhat.com/browse/MGMT-20366

MGMT-20366: fix ironic inspection bug when ironic image override annotation is provided in disconnected environments

---

internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go

If an InfraEnv's creation time gets updated, but the ISO image URL does not change, the PreprovisioningImage can get stuck in an error status.
This ensures that we update the status once the cooldown time is reached while still not triggering the BMH to reboot when the image URL is the same.
/cc @carbonin @gamli75

MGMT-20506: Reset preprovisioningimage status after cooldown period

---

internal/featuresupport/feature_support_test.go
internal/featuresupport/features_misc.go
internal/host/hostcommands/install_cmd_test.go

Currently, assisted-installer prevents overwriting OS image for `s390x` hosts. This is used only for skip `MCO` reboot feature, therefore no need to enable it for such hosts - It only delays the installation completion. Reference - https://github.com/openshift/assisted-installer/pull/941 

MGMT-20378: Disable skip MCO reboot for s390x

---

internal/network/manifests_generator.go
internal/network/manifests_generator_test.go

There are a few manifests we generate for clusters before installing them that are duplicated for each MachineConfigPool.
Because TNA clusters have a new MCP for arbiter nodes, we need to also generate the manifests for it.
Those manifests are:
- chrony configuration
- nic reapply (used when one of the nodes is using iscsi)
Closes [MGMT-20610](https://issues.redhat.com//browse/MGMT-20610)

MGMT-20610: Generate manifests for arbiter hosts for chrony and nic reapply

---

internal/cluster/cluster.go
internal/cluster/cluster_test.go

This reverts commit 324c74eca63dded25474ee0a094c49fb596b8fe2. The commit was based on a misunderstanding and caused https://issues.redhat.com/browse/MGMT-20700. More details could be find on https://issues.redhat.com/browse/MGMT-20272. 

MGMT-20700: Revert "MGMT-20272: Cluster attribute finalizing_stage_started_at show wrong value (#7594)"

---

internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go

https://issues.redhat.com/browse/MGMT-20664
Currently in mixed-architecture deployments with ironic agent image override, we incorrectly discard the ICC config when hub and spoke architectures are different, causing fallback to the default `fillServiceUrls` method. This change preserves ironic urls from ICC regardless of image architecture compatibility by separating url concerns from image selection.

MGMT-20664: ironic inspection fails when hub and spoke architectures are different

---

pkg/staticnetworkconfig/backward_compatibility.go
pkg/staticnetworkconfig/backward_compatibility_test.go

Minor improvement to the Global DNS workaround from PR #[7563](https://github.com/openshift/assisted-service/pull/7653). It’s more accurate to explicitly check for dhcp: true when auto-dns: false is set, since it's the combination of both that triggers the use of Global DNS, and only for this combination we want to fallback to old flow.

MGMT-20604: Modify Global DNS workaround to also check for dhcp: true

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/host/common.go
internal/host/host_test.go
internal/host/statemachine.go
internal/host/transition_test.go

In kube-API, an Agent will be allowed to have its Cluster Deployment unset while the host is installing. This procedure indicates a host install cancellation. The host should be allowed to have its installation cancelled only if it's a day-2 host. The typical procedure to unbind a host while it's not installing should not change. 
1. Install a dev-scripts cluster with 2 extra hosts, these changes, hypershift enabled, and the changes for the webhook (PR: https://github.com/openshift/assisted-service/pull/7643)
2. Create a hosted cluster, boot the hosts using BMHs
3. Scale up the NodePool to 1
4. When the host goes into installing, scale down the NodePool to 0
5. Observe the Agent getting its clusterDeploymentName reference removed and its status moving to `unbinding-pending-user-action`
6. …

MGMT-20605: Add logic to handle cancelling a day-2 host installation

---

pkg/staticnetworkconfig/generator.go
pkg/staticnetworkconfig/generator_test.go

This is a manual backport for PR 6715, as requested here - [MGMT-20740](https://issues.redhat.com/browse/MGMT-20740)
* Do not require interface mapping for physical network names
* add support for identifier field, e.g. mac-address
* Move logic to check that interface map is not empty into separate function

[release-ocm-2.11] MGMT-20740: Don't require mapping for names matching physical interfaces (PR #6715)

---

internal/installcfg/builder/builder_test.go
internal/installcfg/installcfg.go

The agent-based installer added support for setting the AdditionalTrustBundlePolicy in install-config-overrides, however the field was not included in the installConfig definition. This results in the overrides not being set (the failure was silently ignored due to agent-installer bug
https://issues.redhat.com/browse/OCPBUGS-56913).

OCPBUGS-56596: Include AdditionalTrustBundlePolicy in installConfig

---

docs/hive-integration/README.md
internal/controller/controllers/preprovisioningimage_controller.go
internal/controller/controllers/preprovisioningimage_controller_test.go

https://issues.redhat.com/browse/MGMT-19999
This pr allows automatic detection of ironic agent image in case of mixed arch installations, assuming the hub cluster has a multi release image or has a `ClusterImageSet` of the spoke cpu arch and the hub cluster version

MGMT-19999: allow automatic detection of ironic agent image in case of multi arch installation

---

internal/controller/controllers/bmh_agent_controller.go
internal/controller/controllers/bmh_agent_controller_test.go

Previously, once a BMH was provisioned, the BMH would be detached and paused (in the form of annotations added by assisted-service's BMAC controller) to prevent BMO from further updating it.
Host management after the BMH is provisioned is a feature that requires the BMH to still be attached and unpaused after it is provisioned. The request to allow this features requires assisted-service to be aware that the user wants to use it and to then either remove or not add the detached and paused annotations to the BMH once it has provisioned.
----
Significant changes:
Modifies the original BMAC flow to:
1. First analyze whether the annotations need to be added/removed
2. Continue the remaining reconcile function (apart from reconcileBMH) even if detached is set 
- includes: reconcile spoke BMH, …

ACM-21001: Allow Host Management if explicitly set

---

internal/featuresupport/feature_support_test.go
internal/featuresupport/features_misc.go
internal/installcfg/builder/builder.go
internal/installcfg/builder/builder_test.go

removed setting a featureSet for arbiter, the arbiter feature is in TechPreview in 4.19 and slated for GA in 4.20 as such users should set an intall override to set featureSet to TechPreviewNoUpgrade in 4.19 and nothing should be needed for 4.20.

OCPEDGE-1933: feat: update featureSet for arbiter

---

internal/ignition/installmanifests.go
internal/ignition/installmanifests_test.go

When the agent-installer rendezvous host is not the lowest value, e.g. when its 'master-2', the OVE UI fails in updateBootstrap since the hosts are out of sync with the BareMetalHosts. In this case the first BMH file corresponds to the rendezvous host (master-2) but the host removed in the first call to popNextHost() is 'master-0'.
Instead of relying on the dependency between BMH files and hosts, use the hostname to determine which host entry should be removed from the list of hosts for the role.
- [] None
[Kubernetes community documentation]: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests …

OCPBUGS-57361: Use hostname to match hosts to BMH ignition

---

internal/host/hostutil/host_utils.go
internal/host/hostutil/host_utils_test.go
internal/host/transition.go
internal/host/transition_test.go

Previously, if the host's installation disk wasn't found, the code would panic when trying to use a nil value. This PR adds a check in `GetHostInstallationDisk` to return an error if the disk is missing.
Also, in `replaceMacros`, we now handle this error properly by logging a warning and replacing `$INSTALLATION_DISK` with an empty string instead of crashing.
/cc @gamli75 @rccrdpccl

MGMT-20651: Assisted Service panics if both installation_disk_id and installation-disk_path are empty

---

api/hiveextension/v1beta1/agentclusterinstall_types.go
config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
config/crd/resources.yaml
deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
internal/common/db_test.go
internal/controller/controllers/clusterdeployments_controller.go
internal/controller/controllers/clusterdeployments_controller_test.go
vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go

When running the agent installer scripts we need to pass in the correct number of arbiter agents to the scripts so we know the number of nodes to wait for with out needing to infer the number of arbiters.

OCPEDGE-1931: add arbiter agents counts

---

Dockerfile.assisted-service-build
ci-images/Dockerfile.lint

The image was removed from quay.io/coreos and this binary is not used during build or lint phases

NO-JIRA: Remove refs to shellcheck

---

internal/operators/fenceagentsremediation/fence_agents_remediation_operator.go
internal/operators/nodehealthcheck/node_healthcheck_operator.go

NO-ISSUE: Add NHO and FAR back to the virtualization bundle

---

internal/operators/fenceagentsremediation/fence_agents_remediation_operator.go
internal/operators/nodehealthcheck/node_healthcheck_operator.go

(cherry picked from commit 777efb649ef520b1cad3ce5638c459681f53c6fb)

[v2.43] NO-ISSUE: Add NHO and FAR back to the virtualization bundle (#7869)

---

internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/cluster/mock_cluster_api.go
internal/network/connectivity_groups.go
internal/network/connectivity_groups_test.go

- **[MGMT-21252](https://issues.redhat.com//browse/MGMT-21252): Make l3_connected_addresses output deterministic**
- **[MGMT-21253](https://issues.redhat.com//browse/MGMT-21253): RefreshSchedulableMastersForcedTrue lead to extra reads from DB**

[v2.43] MGMT-21252: MGMT-21253: Performance fixes for cluster monitoring

---

internal/network/connectivity_groups.go
internal/network/connectivity_groups_test.go

The algorithm adding connected IPs to host relies on [map iterations which are random](https://nathanleclaire.com/blog/2014/04/27/a-surprising-feature-of-golang-that-colored-me-impressed/)
in golang. Therefore, the order to the connected IPs is not
deterministic. This behaviour leads to useless updates to the `connectivity_majority_groups`
field in `clusters` table whereas [we try to prevent that](https://github.com/openshift/assisted-service/blob/master/internal/cluster/cluster.go#L1434-L1443).
This change sorts the slices of the connected IPs to ensure that
multiple calls to this function will have the same result. Test are also
updated to expect the exact same order.

MGMT-21252: Make l3_connected_addresses output deterministic

---

internal/migrations/20250728120000_add_host_by_cluster_id_index.go
internal/migrations/migrations.go

This patch adds a new `hosts_by_cluster_id` index that accelerates fetch of hosts for a specific cluster. This is an operation that we perform very frequently, and currently it requires a sequential scan of the hosts tables.

MGMT-21312: Index hosts by cluster id

---

internal/cluster/cluster.go

This patch removes the unused `offset` and `limit` variables from the cluster monitoring loop. This doesn't have any effect in performance, but it is confusing to have things that aren't used.

NO-ISSUE: Remove unused variables from cluster monitor loop

---

internal/host/hostcommands/install_cmd.go
internal/host/hostcommands/install_cmd_test.go

The NIC name is sensible to PCI enumeration and some hardware may not
enumerate the devices in the same order after a reboot, which leads to a
different NIC name, and RHCOS goes to emergency mode.
This change refers to the NIC using its MAC address which is not
subject to change.
This issue has been observed on Oracle Cloud baremetal, but I think it can
affect offer hardware vendors as well.

MGMT-21063: Use mac address to configure dhcp on kargs

---

internal/cluster/validator.go
internal/cluster/validator_test.go
internal/common/test_configuration.go
internal/network/utils.go
internal/network/utils_test.go

The `isMachineCidrEqualsToCalculatedCidr` validation was failing when users provided IPv6 CIDRs with uppercase letters/ leading zeros / both (e.g., `2A00:8A00:4000:0d80::/64`), even when they were functionally equivalent to the calculated CIDR.
This occurred because:
- User-provided CIDRs could contain uppercase letters and leading zeros
- Calculated CIDRs from host inventories are normalized (lowercase, no leading zeros)
- Direct string comparison would fail even for equivalent networks
Updated the validation logic to normalize user-provided CIDRs before comparison with the calculate one using `network.NormalizeCIDR()`
**Assisted-by:** flightctl ai-issue-resolver, Cursor
To reproduce the bug:
1. Create a Hub cluster
2. Deploy a spoke cluster and configure AgentClusterInstall with …

OCPBUGS-59393: Fix IsMachineCidrEqualsToCalculatedCidr validation to handle unnormalized IPv6 addresses

---

cmd/main.go
internal/host/monitor.go
internal/host/monitor_test.go
internal/metrics/metricsManager.go
internal/metrics/mock_metrics_manager_api.go

[MGMT-21274](https://issues.redhat.com//browse/MGMT-21274): Report duration of monitored hosts
Send an event that records how long each host takes to be monitored, making it easy to spot hosts that slow the monitoring loop.
Adds the SLOW_HOST_MONITOR_LOG_THRESHOLD env-var (default 1 s) and unit-tests for the new behaviour.
How I verified the change:
1. Set the env-var so every pass is considered slow:
```
SLOW_HOST_MONITOR_LOG_THRESHOLD=0ms
```
2. Installed a test cluster.
3. Queried the metrics-category events and confirmed `host_monitor.slow_host`
entries appear:
```bash
curl -s \
"http://10.1.178.25:8090/api/assisted-install/v2/events?cluster_id=4c951ccb-f47a-4e57-87a5-2af635f73e2e&categories=metrics&message=host_monitor.slow_host&limit=20&order=descending" \
| jq '.[] | {time: …
```

MGMT-21274: Report duration of monitored hosts

---

docs/dev/olm-operator-plugins.md
internal/operators/amdgpu/amd_gpu_manifests_test.go
internal/operators/amdgpu/templates/openshift/50_amd_gpu_namespace.yaml
internal/operators/amdgpu/templates/openshift/50_amd_gpu_prometheus-role.yaml
internal/operators/amdgpu/templates/openshift/50_amd_gpu_prometheus-rolebinding.yaml
internal/operators/clusterobservability/templates/openshift/50_cluster_observability_namespace.yaml
internal/operators/kubedescheduler/templates/openshift/50_kube_descheduler_namespace.yaml
internal/operators/lso/manifest.go
internal/operators/lso/manifests_test.go
internal/operators/manager_test.go
internal/operators/nodefeaturediscovery/templates/openshift/50_nodefeaturediscovery_namespace.yaml
internal/operators/numaresources/numaresources_manifests_test.go
internal/operators/numaresources/templates/openshift/50_numaresources_namespace.yaml
internal/operators/numaresources/templates/openshift/50_numaresources_prometheus-role.yaml
internal/operators/numaresources/templates/openshift/50_numaresources_prometheus-rolebinding.yaml

To provide a consistent, out-of-the-box monitoring experience, the Assisted Installer automatically enables cluster monitoring for all operators that support this feature (i.e., those with the "Enable Operator-recommended cluster monitoring..." option in OperatorHub). This choice is enabled by default and cannot be changed by the user during the assisted installation process. To enforce this, the Assisted Installer's code must perform two key actions for each monitoring-aware operator:
1. apply the ```openshift.io/cluster-monitoring=true``` label to the operator's pre-created namespace
2. if an operator does not provide its own RBAC, the installer code is responsible for creating the standard Prometheus Role and RoleBinding in the operator's namespace.
**Note:** When a developer adds a …

MGMT-21395: Add monitoring label and Prometheus RBAC for supported OLM operators

---

cmd/main.go
cmd/operator/main.go
internal/spoke_k8s_client/factory.go
internal/spoke_k8s_client/factory_test.go
internal/system/mock_system.go
internal/system/system.go

When running inside of MCE/ACM, performing some day2 operations require the use of the cluster's kubeconfig which we create when installing the cluster. But that kubeconfig has self generated CA data, and users can change the certificate of the clster's API to one that was signed by their CA. That causes the issue: "tls: failed to verify certificate: x509: certificate signed by unknown authority".
To fix this we will read the our own system ca-bundle (created as a configmap by the AgentServiceConfig controller running in the infrastructure-operator and then mounted into assisted-service) and merge it with the CA data that exists in the kubeconfig.
I tested this by doing the following:
- Deploy a hub cluster with MCE, without my custom image
- Use MCE to install a spoke cluster
- Change …

ACM-21902: Merge system ca-bundle into spoke client

---

internal/bminventory/inventory.go
internal/bminventory/mock_installer_internal.go
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go

- Update agent finalizer to delete hosts regardless of namespace
- Block Agent creation when host ID already exists in different namespace
- Update Agent status conditions to report conflicts
https://issues.redhat.com/browse/MGMT-19854

MGMT-19854: Fix Agent deletion across namespaces and prevent duplicate host IDs

---

docs/hive-integration/crds/nmstate.yaml
internal/ignition/templates/pre-network-manager-config-with-nmstatectl.service

This is a manually cherry-pick of https://github.com/openshift/assisted-service/pull/7977
/assign linoyaslan

[release-ocm-2.13] MGMT-21688: Order pre-nm-config after NM-wait-online to fix race on full ISO

---

Dockerfile.assisted-service-rhel8-mce

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini

KONFLUX-6210: fix and set name and cpe label for assisted-service-rhel8-acm-ds-2-14

---

internal/host/hostutil/host_utils.go
internal/host/hostutil/host_utils_test.go
internal/host/transition.go
internal/host/transition_test.go

Manual cherry-pick of #7764
https://issues.redhat.com/browse/ACM-24232
---
Original PR message
Previously, if the host's installation disk wasn't found, the code would panic when trying to use a nil value. This PR adds a check in GetHostInstallationDisk to return an error if the disk is missing.
Also, in replaceMacros, we now handle this error properly by logging a warning and replacing $INSTALLATION_DISK with an empty string instead of crashing.
/cc @gamli75

[release-ocm-2.13] MGMT-20651: Assisted Service panics if both installation_disk_id and installation-disk_path are empty 

---

internal/featuresupport/features_misc.go
internal/featuresupport/features_olm_operators.go
internal/featuresupport/features_olm_operators_test.go
internal/operators/openshiftai/openshift_ai_manifests.go
internal/operators/openshiftai/openshift_ai_manifests_test.go
internal/operators/openshiftai/openshift_ai_operator.go
internal/operators/openshiftai/templates/files/setup.sh

Allow openshiftAI installation on SNO cluster
On SNO cluster, ODF can't be installed, so we have to rely another storage class. Here I'm using the storage class created by LVM, this is why it's added as dependency for SNO cluster

MGMT-21450: Allow OpenshiftAI installation on SNO cluster

---

api/v1beta1/agentserviceconfig_types.go
api/v1beta1/infraenv_types.go
cmd/main.go
internal/bminventory/inventory.go
internal/bminventory/inventory_test.go
internal/bminventory/inventory_v2_handlers.go
internal/controller/controllers/agent_controller.go
internal/controller/controllers/agent_controller_test.go
internal/controller/controllers/agentserviceconfig_controller.go
internal/controller/controllers/agentserviceconfig_controller_test.go
internal/controller/controllers/hypershiftagentserviceconfig_controller.go
internal/controller/controllers/infraenv_controller.go
internal/controller/controllers/infraenv_controller_test.go
internal/host/hostcommands/download_boot_artifacts_cmd.go
internal/host/hostcommands/instruction_manager_test.go
internal/versions/api_test.go
internal/versions/kube_api_versions_test.go
internal/versions/osimages.go
internal/versions/osimages_test.go
vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go

Allow Image Service to be disabled. This is useful for user data flow (AKA install in same root flow), as we don't use ISOs to boot (but only ignition), image service is not needed. When not disabled, it would still download base images for the ISOs which will delay the whole service readiness (other than use a considerable amount of bandwidth). Disconnected envs will also benefit from this (in userdata flow mode), as the images will not need to be mirrored. …

MGMT-20192: add possibility to disable image service
